### ISSUE TITLE
./mach do not support paths with Unicode characters 

### ISSUE THREAD

**Issue by qaxi** [servo/servo#10002]
```
$ cd ~/Stažené/servo
$ ./mach build --dev
Traceback (most recent call last):
  File "./mach", line 25, in <module>
    main(sys.argv)
  File "./mach", line 21, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "./python/mach_bootstrap.py", line 154, in bootstrap
    if ' ' in topdir:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 15: ordinal not in range(128)
```

When moved it works well

```
$ mv ../servo ../../Desktop/
$ ./mach build --dev
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in XXX/Desktop/servo/python/_virtualenv/bin/python2.7
Also creating executable in XXX/Desktop/servo/python/_virtualenv/bin/python
Installing setuptools, pip...done.
... 
```

**Comment by frewsxcv** [comment]
It might be sufficient to just do:

`if u' ' in topdir:` instead of `if ' ' in topdir:` on line 154 in 'python/mach_bootstrap.py'

**Comment by qaxi** [comment]
No, it does not work either. The same exception.

**Comment by timvandermeij** [comment]
Fixed by #10003?

**Comment by jdm** [comment]
I think it's worth leaving this open, since #10003 just tells users not to use paths containing non-ascii :)

**Comment by frewsxcv** [comment]
I'll look into this.

**Comment by frewsxcv** [comment]
Looked into this. Changing our code to support it is pretty trivial:

```diff
diff --git a/python/mach_bootstrap.py b/python/mach_bootstrap.py
index 05b21c4..a376dde 100644
--- a/python/mach_bootstrap.py
+++ b/python/mach_bootstrap.py
@@ -111,7 +111,9 @@ def _activate_virtualenv(topdir):
         except (subprocess.CalledProcessError, OSError):
             sys.exit("Python virtualenv failed to execute properly.")

-    execfile(activate_path, dict(__file__=quote(activate_path)))
+    fsenc = sys.getfilesystemencoding()
+    execfile(activate_path.encode(fsenc),
+             dict(__file__=quote(activate_path)))

     # TODO: Right now, we iteratively install all the requirements by invoking
     # `pip install` each time. If it were the case that there were conflicting
@@ -147,16 +149,7 @@ def _activate_virtualenv(topdir):


 def bootstrap(topdir):
-    topdir = os.path.abspath(topdir)
-
-    # We don't support paths with Unicode characters for now
-    # https://github.com/servo/servo/issues/10002
-    try:
-        topdir.decode('ascii')
-    except UnicodeDecodeError:
-        print('Cannot run mach in a path with Unicode characters.')
-        print('Current path:', topdir)
-        sys.exit(1)
+    topdir = os.path.abspath(topdir).decode('utf8')

     # We don't support paths with spaces for now
     # https://github.com/servo/servo/issues/9442
```

A bigger problem is that virtualenv itself [doesn't support](https://github.com/pypa/virtualenv/issues/457) unicode paths:

```
coreyf@frewbook-pro /tmp> virtualenv é
New python executable in /private/tmp/é/bin/python2.7
Also creating executable in /private/tmp/é/bin/python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
ERROR: The executable /private/tmp/é/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/private/tmp' (should be u'/private/tmp/\xe9')
ERROR: virtualenv is not compatible with this system or executable
```

Also, for the record, mach doesn't support unicode paths either.

**Comment by tigercosmos** [comment]
related to pypa/virtualenv#457
