### ISSUE TITLE
mozjs could not be able build under win32, cause it can not find which

### ISSUE THREAD

**Issue by lygstate** [servo/servo#10046]
```
/c/CI-Cor/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: line 3772: test: (GNU: integer expression expected
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\CI-Cor\servo\.cargo\git\checkouts\mozjs-06d7f04b6dbb8a8e\master\mozjs\python\mozbuild\mozbuild\base.py", line 14, in <module>
    import which
ImportError: No module named which
configure: error: Python environment does not appear to be sane.
make: *** [all] Error 1
thread '<main>' panicked at 'assertion failed: result.success()', C:/CI-Cor/servo/.cargo\git\checkouts\mozjs-06d7f04b6dbb8a8e\master\build.rs:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by lygstate** [comment]
```
cd /c/CI-Cor/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out && \
PYTHON=""c:/python27/python.exe"" \
MOZ_TOOLS="/" CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
/c/CI-Cor/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure --disable-jemalloc --disable-shared-js --disable-export-js
loading cache ./config.cache
checking host system type... x86_64-pc-mingw64

```

According to this, it's using the system default python by default, and that cause problems
