### ISSUE TITLE
Intermittent fontconfig crash closing summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#1007]
```
#0  0x000000321c2153e4 in ft_cmap_done_internal () from /lib64/libfreetype.so.6
#1  0x000000321c2156c9 in destroy_charmaps () from /lib64/libfreetype.so.6
#2  0x000000321c217aee in destroy_face () from /lib64/libfreetype.so.6
#3  0x000000321c217c24 in FT_Done_Face () from /lib64/libfreetype.so.6
#4  0x00007ffff474e21c in drop () at /home/jdm/sdb/servo/src/components/gfx/platform/linux/font.rs:69
#5  0x0000000000483572 in gfx..font_list..FontFamily::glue_drop_23247::_548dc3f7e6abed39 ()
#6  0x00000000004831f4 in std..hashmap..HashMap$LT$$UP$str$C$$SP$mut$x20gfx..font_list..FontFamily$GT$::glue_drop_23210::_1325829bb95148c8 ()
#7  0x000000000048257e in gfx..font_context..FontContext::glue_drop_23078::_69af401129a7127 ()
#8  0x00000000004df571 in layout..layout_task..LayoutTask::glue_drop_30819::_70b1c51c678f7aef () at /home/jdm/sdb/servo/src/components/main/pipeline.rs:52
#9  0x00000000004dcd39 in fn_30735 () at /home/jdm/sdb/servo/src/components/main/layout/layout_task.rs:95
#10 0x00007ffff788021c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#11 0x00007ffff7920e84 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#12 0x00007ffff782355c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#13 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#14 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#15 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#16 0x00007ffff2e61a73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#17 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#18 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#19 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#20 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#21 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#22 0x0000000000000000 in ?? ()
```

**Comment by sviter** [comment]
Is it still valid?

**Comment by jdm** [comment]
No; the code is too old for this to be meaningful.
