### ISSUE TITLE
browserhtml: crash/hang after resizing window to absurdly small size

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#10118]
Using i3 allows me to resize windows ignoring any preferences they might have set.
When reducing browserhtml ( ./mach run --release --browserhtml ) to absurd sizes (620x22 px), the window freezes or panics.

````
ompile "/home/matthias/vcs/github/servo/resources/shaders/quad.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/quad.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/blit.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/blit.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/border.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/border.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/blend.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/blend.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/filter.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/filter.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/box_shadow.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/box_shadow.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/blur.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/blur.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/mask.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/mask.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/debug_font.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/debug_font.fs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/debug_color.vs.glsl"
compile "/home/matthias/vcs/github/servo/resources/shaders/debug_color.fs.glsl"
ERROR:js::rust: Error at file:///home/matthias/vcs/github/servo/target/release/build/browserhtml-6c4c8f086420ecc3/out/components/browser/index.js:4:8053: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
thread '<unnamed>' panicked at 'Failed to call XSendEvent after wakeup: XError { description: "136", error_code: 136, request_code: 134, minor_code: 15 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x5559f11a8c30 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x5559f11adb7f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x5559f11ad7f8 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x5559f119757c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x5559f1198528 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x5559f11a7f31 - rust_begin_unwind
   7:     0x5559f11e559f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x5559f03e8163 - result::unwrap_failed::h11915907684431442101
   9:     0x5559f03e8a50 - api::x11::window::WindowProxy::wakeup_event_loop::h871f99db8961702f3dg
  10:     0x5559f01cd398 - window::GlutinCompositorProxy.CompositorProxy::send::h54323fbccafba3c6E7a
  11:     0x5559f0257852 - compositor_thread::Box<CompositorProxy$u2b$$u20$$u27$static$GT$.RenderListener::recomposite::h8e95e8d86a14b608mkd
  12:     0x5559f039cd13 - render_backend::RenderBackend::publish_frame::hf4019b365f62f688brp
  13:     0x5559f0367ff4 - render_backend::RenderBackend::run::hc2e26b0ba1eed6b2ngp
  14:     0x5559f0310d5b - sys_common::unwind::try::try_fn::h679943626664401698
  15:     0x5559f11a7ebb - __rust_try
  16:     0x5559f11a7e4d - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  17:     0x5559f031114a - boxed::F.FnBox<A>::call_box::h9945412416957969614
  18:     0x5559f11ac149 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  19:     0x7f4ecf1cb609 - start_thread
  20:     0x7f4ececeea4c - clone
  21:                0x0 - <unknown>
````

**Comment by nox** [comment]
Does this still happen?

**Comment by mateon1** [comment]
@nox 
Yes, it still happens, can be shown with
```html
<script>window.resizeTo(0, 0)</script>
```

The window doesn't actually resize, but Servo still crashes. I've seen two stack traces:

<details>
<summary>Failed to call XPeekEvent</summary>

```gdb
Failed to call XPeekEvent: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 12, minor_code: 0 } (thread main, at /checkout/src/libcore/result.rs:906)
stack backtrace:
   0:     0x558c929b0854 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x558c929ac27f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x558c8d024f5e - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x558c94bd45d6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x558c94bd43f4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x558c94bd4369 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x558c94bd42fa - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x558c94c0e730 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x558c8d13bf4c - core::result::unwrap_failed<glutin::api::x11::xdisplay::XError>
                        at /checkout/src/libcore/macros.rs:23
   9:     0x558c8d10472c - core::result::{{impl}}::expect<(),glutin::api::x11::xdisplay::XError>
                        at /checkout/src/libcore/result.rs:799
  10:     0x558c8d115abd - glutin::api::x11::window::{{impl}}::next
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/api/x11/window.rs:286
  11:     0x558c8d0a9c43 - glutin::window::{{impl}}::next
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/window.rs:588
  12:     0x558c8d0ad838 - glutin_app::window::{{impl}}::handle_next_event
                        at /shared/dev/rust/servo/ports/glutin/window.rs:645
  13:     0x558c8d0adf0f - glutin_app::window::{{impl}}::wait_events
                        at /shared/dev/rust/servo/ports/glutin/window.rs:692
  14:     0x558c8d0244b4 - servo::main
                        at /shared/dev/rust/servo/ports/servo/main.rs:178
  15:     0x558c94bdb76c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  16:     0x558c94bd4dbb - std::panicking::try<(),closure>
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind<closure,()>
                        at /checkout/src/libstd/panic.rs:361
                         - std::rt::lang_start
                        at /checkout/src/libstd/rt.rs:59
  17:     0x558c8d02551d - main
  18:     0x7f2ff31fd2e0 - __libc_start_main
  19:     0x558c8cf41339 - _start
  20:                0x0 - <unknown>
ERROR:servo: Failed to call XPeekEvent: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 12, minor_code: 0 }
Servo exited with return value 101
```
</details>

<details>
<summary>Failed to call XSendEvent</summary>

```gdb
Failed to call XSendEvent after wakeup: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 12, minor_code: 0 } (thread Constellation, at /checkout/src/libcore/result.rs:906)
stack backtrace:
   0:     0x5626f6e7e854 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x5626f6e7a27f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5626f14f2f5e - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x5626f90a25d6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5626f90a23f4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x5626f90a2369 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x5626f90a22fa - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x5626f90dc730 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x5626f1609f4c - core::result::unwrap_failed<glutin::api::x11::xdisplay::XError>
                        at /checkout/src/libcore/macros.rs:23
   9:     0x5626f15d272c - core::result::{{impl}}::expect<(),glutin::api::x11::xdisplay::XError>
                        at /checkout/src/libcore/result.rs:799
  10:     0x5626f15e25e4 - glutin::api::x11::window::{{impl}}::wakeup_event_loop
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/api/x11/window.rs:132
  11:     0x5626f1576c54 - glutin::platform::platform::api_dispatch::{{impl}}::wakeup_event_loop
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/platform/linux/api_dispatch.rs:56
  12:     0x5626f1575aec - glutin::window::{{impl}}::wakeup_event_loop
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/window.rs:560
  13:     0x5626f157da0d - glutin_app::window::{{impl}}::create_event_loop_waker::{{impl}}::wake
                        at /shared/dev/rust/servo/ports/glutin/window.rs:1086
  14:     0x5626f719e086 - compositing::compositor_thread::{{impl}}::send
                        at /shared/dev/rust/servo/components/compositing/compositor_thread.rs:44
  15:     0x5626f17a3ae9 - constellation::constellation::{{impl}}::handle_request_from_script<script_layout_interface::message::Msg,layout_thread::LayoutThread,script::script_thread::ScriptThread>
                        at /shared/dev/rust/servo/components/constellation/constellation.rs:1172
  16:     0x5626f178c67c - constellation::constellation::{{impl}}::handle_request<script_layout_interface::message::Msg,layout_thread::LayoutThread,script::script_thread::ScriptThread>
                        at /shared/dev/rust/servo/components/constellation/constellation.rs:892
  17:     0x5626f17b19ea - constellation::constellation::{{impl}}::run<script_layout_interface::message::Msg,layout_thread::LayoutThread,script::script_thread::ScriptThread>
                        at /shared/dev/rust/servo/components/constellation/constellation.rs:615
  18:     0x5626f1977b89 - constellation::constellation::{{impl}}::start::{{closure}}<script_layout_interface::message::Msg,layout_thread::LayoutThread,script::script_thread::ScriptThread>
                        at /shared/dev/rust/servo/components/constellation/constellation.rs:603
  19:     0x5626f197205a - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  20:     0x5626f1863dd3 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
  21:     0x5626f1863c6a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  22:     0x5626f1647932 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  23:     0x5626f90a976c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  24:     0x5626f16477fc - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  25:     0x5626f1863d35 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  26:     0x5626f19958eb - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
  27:     0x5626f1997883 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:726
  28:     0x5626f90a125b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:736
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  29:     0x7fa8af642493 - start_thread
  30:     0x7fa8af16fabe - __clone
  31:                0x0 - <unknown>
ERROR:servo: Failed to call XSendEvent after wakeup: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 12, minor_code: 0 }
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }" (thread RenderBackend, at /checkout/src/libcore/result.rs:906)
IpcSelectionResult::unwrap(): channel 1 closed (thread ResourceManager, at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.8.0/src/ipc.rs:308)
called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread StorageManager, at /checkout/src/libcore/result.rs:906)
WARNING: YOU ARE LEAKING THE WORLD (at least one JSRuntime and everything alive inside it, that is) AT JS_ShutDown TIME.  FIX THIS!
stack backtrace:
   0:     0x5626f6e7e854 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x5626f6e7a27f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5626f14f2f5e - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x5626f90a25d6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5626f90a23f4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x5626f90a2369 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x5626f80acf9d - ipc_channel::ipc::{{impl}}::unwrap
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.8.0/src/ipc.rs:308
   7:     0x5626f1fe596d - net::resource_thread::{{impl}}::start::{{closure}}
                        at /shared/dev/rust/servo/components/net/resource_thread.rs:136
   8:     0x5626f1fe3030 - core::ops::function::impls::{{impl}}::call_once<(ipc_channel::ipc::IpcSelectionResult),closure>
                        at /checkout/src/libcore/ops/function.rs:271
   9:     0x5626f1fd376e - core::option::{{impl}}::map<ipc_channel::ipc::IpcSelectionResult,(u64, ipc_channel::ipc::OpaqueIpcMessage),&mut closure>
                        at /checkout/src/libcore/option.rs:398
  10:     0x5626f1fda4a9 - core::iter::{{impl}}::next<(u64, ipc_channel::ipc::OpaqueIpcMessage),alloc::vec::IntoIter<ipc_channel::ipc::IpcSelectionResult>,closure>
                        at /checkout/src/libcore/iter/mod.rs:1123
  11:     0x5626f1fdb7f6 - net::resource_thread::{{impl}}::start
                        at /shared/dev/rust/servo/components/net/resource_thread.rs:136
  12:     0x5626f22fcde2 - net::resource_thread::new_core_resource_thread::{{closure}}
                        at /shared/dev/rust/servo/components/net/resource_thread.rs:80
  13:     0x5626f22f4c47 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  14:     0x5626f22cd69d - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
  15:     0x5626f22cca17 - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  16:     0x5626f20df57f - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  17:     0x5626f90a976c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  18:     0x5626f20de45c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  19:     0x5626f22ccfb2 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  20:     0x5626f210df22 - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
  21:     0x5626f21126c6 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:726
  22:     0x5626f90a125b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:736
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  23:     0x7fa8af642493 - start_thread
  24:     0x7fa8af16fabe - __clone
  25:                0x0 - <unknown>
ERROR:servo: IpcSelectionResult::unwrap(): channel 1 closed
stack backtrace:
   0:     0x5626f6e7e854 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x5626f6e7a27f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5626f14f2f5e - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x5626f90a25d6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5626f90a23f4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x5626f90a2369 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x5626f90a22fa - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x5626f90dc730 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x5626f160a493 - core::result::unwrap_failed<std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<core::option::Option<glutin::api::x11::window::WindowProxyData>>>>
                        at /checkout/src/libcore/macros.rs:23
   9:     0x5626f15d2a6b - core::result::{{impl}}::unwrap<std::sync::mutex::MutexGuard<core::option::Option<glutin::api::x11::window::WindowProxyData>>,std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<core::option::Option<glutin::api::x11::window::WindowProxyData>>>>
                        at /checkout/src/libcore/result.rs:772
  10:     0x5626f15e2388 - glutin::api::x11::window::{{impl}}::wakeup_event_loop
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/api/x11/window.rs:115
  11:     0x5626f1576c54 - glutin::platform::platform::api_dispatch::{{impl}}::wakeup_event_loop
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/platform/linux/api_dispatch.rs:56
  12:     0x5626f1575aec - glutin::window::{{impl}}::wakeup_event_loop
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.12.0/src/window.rs:560
  13:     0x5626f157da0d - glutin_app::window::{{impl}}::create_event_loop_waker::{{impl}}::wake
                        at /shared/dev/rust/servo/ports/glutin/window.rs:1086
  14:     0x5626f719e556 - compositing::compositor_thread::{{impl}}::send
                        at /shared/dev/rust/servo/components/compositing/compositor_thread.rs:83
  15:     0x5626f719e72f - compositing::compositor_thread::{{impl}}::recomposite
                        at /shared/dev/rust/servo/components/compositing/compositor_thread.rs:116
  16:     0x5626f719ba54 - compositing::compositor::{{impl}}::new_frame_ready
                        at /shared/dev/rust/servo/components/compositing/compositor.rs:330
  17:     0x5626f7415594 - webrender::render_backend::{{impl}}::publish_frame_and_notify_compositor
                        at /shared/dev/rust/servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/faa9cfe/webrender/src/render_backend.rs:579
  18:     0x5626f74141b9 - webrender::render_backend::{{impl}}::run
                        at /shared/dev/rust/servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/faa9cfe/webrender/src/render_backend.rs:485
  19:     0x5626f732b160 - webrender::renderer::{{impl}}::new::{{closure}}
                        at /shared/dev/rust/servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/faa9cfe/webrender/src/renderer.rs:1713
  20:     0x5626f725497a - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  21:     0x5626f74c37c3 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
  22:     0x5626f7488cca - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  23:     0x5626f74c4e02 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  24:     0x5626f90a976c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  25:     0x5626f74c45dc - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  26:     0x5626f74c31d5 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  27:     0x5626f725795b - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
  28:     0x5626f728c853 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:726
  29:     0x5626f90a125b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:736
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  30:     0x7fa8af642493 - start_thread
  31:     0x7fa8af16fabe - __clone
  32:                0x0 - <unknown>
stack backtrace:
ERROR:servo: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
   0:     0x5626f6e7e854 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x5626f6e7a27f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5626f14f2f5e - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x5626f90a25d6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5626f90a23f4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x5626f90a2369 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x5626f90a22fa - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x5626f90dc730 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x5626f21fe500 - core::result::unwrap_failed<alloc::boxed::Box<bincode::internal::ErrorKind>>
                        at /checkout/src/libcore/macros.rs:23
   9:     0x5626f2360f18 - core::result::{{impl}}::unwrap<net_traits::storage_thread::StorageThreadMsg,alloc::boxed::Box<bincode::internal::ErrorKind>>
                        at /checkout/src/libcore/result.rs:772
  10:     0x5626f2362cac - net::storage_thread::{{impl}}::start
                        at /shared/dev/rust/servo/components/net/storage_thread.rs:59
  11:     0x5626f22fd491 - net::storage_thread::{{impl}}::new::{{closure}}
                        at /shared/dev/rust/servo/components/net/storage_thread.rs:26
  12:     0x5626f22f46a2 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  13:     0x5626f22cdaca - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
  14:     0x5626f22cc5a2 - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  15:     0x5626f20df604 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  16:     0x5626f90a976c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  17:     0x5626f20debd5 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  18:     0x5626f22cd049 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  19:     0x5626f210d5ce - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
  20:     0x5626f2112337 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:726
  21:     0x5626f90a125b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:736
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  22:     0x7fa8af642493 - start_thread
  23:     0x7fa8af16fabe - __clone
  24:                0x0 - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
*Servo hangs*
```
</details>

**Comment by arihant2math** [comment]
That specific test case no longer works, but I can't test it on i3.

**Comment by mrobinson** [comment]
browserhtml doesn't exist any longer, so I think it's safe to close this.
