### ISSUE TITLE
Panic on "No texture page for ID TextureId"

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#10121]
Open https://servo.org in servo (webrender), scroll down, and try to click a link:

```
thread '<unnamed>' panicked at 'No texture page for ID TextureId(1022)', /home/manishearth/Mozilla/servo/./../.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/texture_cache.rs:591
stack backtrace:
   1:     0x7fbfd9a59120 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7fbfd9a5e06f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7fbfd9a5dce8 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7fbfd9a47a6c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7fbfd9a48a18 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7fbfd8b7f770 - texture_cache::TextureCache::free::hd68d2ddd238d5dfbiQr
   7:     0x7fbfd8b7e904 - resource_cache::ResourceCache::expire_old_resources::h06425c24da19448bSNp
   8:     0x7fbfd8b9708c - frame::Frame::build::he207ba9335af9c08WIk
   9:     0x7fbfd8be45e5 - render_backend::RenderBackend::render::h399a87d9731a7750uqp
  10:     0x7fbfd8bafbd0 - render_backend::RenderBackend::run::h9e3a566a890c0335ngp
  11:     0x7fbfd8b58b7b - sys_common::unwind::try::try_fn::h3665366914357747444
  12:     0x7fbfd9a583ab - __rust_try
  13:     0x7fbfd9a5833d - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  14:     0x7fbfd8b58f6a - boxed::F.FnBox<A>::call_box::h18329420530714971588
  15:     0x7fbfd9a5c639 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  16:     0x7fbfd58a46a9 - start_thread
  17:     0x7fbfd53c3eec - clone
  18:                0x0 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7fbfd9a59120 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7fbfd9a5e06f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7fbfd9a5dce8 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7fbfd9a47a6c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7fbfd9a48a18 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7fbfd9a58421 - rust_begin_unwind
   7:     0x7fbfd9a95a8f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7fbfd902804e - result::unwrap_failed::h15280464711631318330
   9:     0x7fbfd902979e - api::RenderApi::translate_point_to_layer_space::ha61d190e8c00dacdU0b
  10:     0x7fbfd7ea18de - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h4401965578861993469
  11:     0x7fbfd7ed722c - Browser::handle_events::hc90d4a7819f1c950Wea
  12:     0x7fbfd7e8d105 - main::h816805d8d509cd3eMaa
  13:     0x7fbfd9a5d944 - sys_common::unwind::try::try_fn::h11728613996190555864
  14:     0x7fbfd9a583ab - __rust_try
  15:     0x7fbfd9a5d3db - rt::lang_start::h660c7a8519a9d7d5NSz
  16:     0x7fbfd52dda3f - __libc_start_main
  17:     0x7fbfd7e83348 - _start
  18:                0x0 - <unknown>
```

cc @glennw

**Comment by jdm** [comment]
Looks like #9931.
