### ISSUE TITLE
crashes on <h1> inside <div>

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#10217]
Originally reduced from servo.org
The crash occurs regardless of using webrender or not.

```` html
<html>
<body>
<div>
    <h1>Servo, the Parallel Browser Engine Project</h1>
</div>

</body>
</html>
````

````
thread 'FontCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 105, message: "No buffer space available" } }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x5573255abca0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x5573255b0bef - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x5573255b0868 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x55732559a5ec - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x55732559b598 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x5573255aafa1 - rust_begin_unwind
   7:     0x5573255e860f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x5573249170b0 - result::unwrap_failed::h7854541832628155971
   9:     0x5573249306ab - font_cache_thread::FontCacheThread::new::_$u7b$$u7b$closure$u7d$$u7d$::closure.43782
  10:     0x55732492d4cd - sys_common::unwind::try::try_fn::h8767407717917585763
  11:     0x5573255aaf2b - __rust_try
  12:     0x5573255aaebd - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x557324931076 - boxed::F.FnBox<A>::call_box::h16129109917155709238
  14:     0x5573255af1b9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7f179b7a2609 - start_thread
  16:     0x7f179b2c5a4c - clone
  17:                0x0 - <unknown>
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x5573255abca0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x5573255b0bef - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x5573255b0868 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x55732559a5ec - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x55732559b598 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x5573255aafa1 - rust_begin_unwind
   7:     0x5573255e860f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x55732490c76e - result::unwrap_failed::h7474706132464293239
   9:     0x557324931b6c - result::Result<T, E>::unwrap::h16505181804837749939
  10:     0x55732493180c - font_cache_thread::FontCacheThread::find_font_template::h18c419dedaeff360GKn
  11:     0x55732493e806 - font_context::FontContext::layout_font_group_for_style::h4d1430ea0efb399eGWn
  12:     0x557323d4c61c - text::TextRunScanner::scan_for_runs::h5f9e346f22135589JBx
  13:     0x557323d2b56b - construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode>::build_flow_for_block_starting_with_fragments::h4455803879579171058
  14:     0x557323d2a06f - construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode>::build_flow_for_block_like::h5586221946916951625
  15:     0x557323d32a7a - construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode>::build_flow_for_block::h15231746827140286670
  16:     0x557323d2714a - construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode>.PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>::process::h12345065336607125364
  17:     0x557323d2292b - traversal::RecalcStyleAndConstructFlows<'lc>.DomTraversalContext<ServoLayoutNode<'ln>>::process_postorder::h9dd2c4b3f9663a82Zcy
  18:     0x557323cb42e2 - parallel::top_down_dom::h4098627431376538356
  19:     0x557323c0f4c6 - sys_common::unwind::try::try_fn::h4219736108192194145
  20:     0x5573255aaf2b - __rust_try
  21:     0x5573255aaebd - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  22:     0x557323c10c09 - boxed::F.FnBox<A>::call_box::h11484742310783387253
  23:     0x5573255af1b9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  24:     0x7f179b7a2609 - start_thread
  25:     0x7f179b2c5a4c - clone
  26:                0x0 - <unknown>
````
I believe this was introduced today at some point (since 9b2ae3a62faafc ? )

EDIT: reproducible with example on 68a8085a2f11d052948145980a0bf8a46471e3a7

**Comment by Manishearth** [comment]
I've been seeing a similar panic earlier (webrender-only), but it stopped happening (or maybe was just intermittent). Might not be that commit.


cc @pcwalton @glennw

**Comment by matthiaskrgr** [comment]
I can no longer reproduce  (  @ f6c29249360134b2a437de0674f606b36327bfb1 ). Shall I close this?

**Comment by jdm** [comment]
Yep, sounds like the various ipc-channel fixes corrected this.
