### ISSUE TITLE
github.com - panic when loading page with webrender

### ISSUE THREAD

**Issue by bobthekingofegypt** [servo/servo#10232]
Load up github and it just crashes, sometimes takes a couple of seconds other time I need to scroll down a bit.  But it always crashes.

No issue without -w flag.

```
bob@mainpc ~/code/servo $ ./mach run -r -- -w http://github.com
compile "/home/bob/code/servo/resources/shaders/quad.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/quad.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/blit.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/blit.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/border.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/border.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/blend.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/blend.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/filter.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/filter.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/box_shadow.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/box_shadow.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/blur.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/blur.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/mask.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/mask.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/debug_font.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/debug_font.fs.glsl"
compile "/home/bob/code/servo/resources/shaders/debug_color.vs.glsl"
compile "/home/bob/code/servo/resources/shaders/debug_color.fs.glsl"
ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-eadd096b8f37795fc0cf0934c37c7ec3d1eb7f3020e9d6c817b0a6525c417b5a.js:4:8365: history is not defined

ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-eadd096b8f37795fc0cf0934c37c7ec3d1eb7f3020e9d6c817b0a6525c417b5a.js:0:1072: Could not find module github/sliding-promise-queue

thread '<unnamed>' panicked at 'No texture page for ID TextureId(1021)', /home/bob/code/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/texture_cache.rs:591
stack backtrace:
   1:     0x55f5e77822b0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x55f5e77871ff - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x55f5e7786e78 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x55f5e7770bfc - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x55f5e7771ba8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x55f5e68d89e0 - texture_cache::TextureCache::free::hc9c1dcdc4146407eYQr
   7:     0x55f5e68b6754 - resource_cache::ResourceCache::expire_old_resources::hd4b9ed185486884byOp
   8:     0x55f5e68ca91c - frame::Frame::build::h586b83af0a487bc2WIk
   9:     0x55f5e691ebc5 - render_backend::RenderBackend::render::h7c0e4ba50c3f6b78arp
  10:     0x55f5e68ebe83 - render_backend::RenderBackend::run::h1b1b1af30a36a589xgp
  11:     0x55f5e6893315 - sys_common::unwind::try::try_fn::h16694144935241978885
  12:     0x55f5e778153b - __rust_try
  13:     0x55f5e77814cd - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  14:     0x55f5e6893797 - boxed::F.FnBox<A>::call_box::h4446538387879343988
  15:     0x55f5e77857c9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  16:     0x7fcc16262313 - start_thread
  17:     0x7fcc15d92bdc - __clone
  18:                0x0 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x55f5e77822b0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x55f5e77871ff - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x55f5e7786e78 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x55f5e7770bfc - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x55f5e7771ba8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x55f5e77815b1 - rust_begin_unwind
   7:     0x55f5e77bec1f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x55f5e6d1431e - result::unwrap_failed::h13329851452021507508
   9:     0x55f5e6d1646e - api::RenderApi::translate_point_to_layer_space::h2db8b973561c898c1Vb
  10:     0x55f5e5bf6323 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h10732067452496601127
  11:     0x55f5e5c2bcdc - Browser::handle_events::h6be134fb85f5275fWea
  12:     0x55f5e5be1a75 - main::h816805d8d509cd3eMaa
  13:     0x55f5e7786ad4 - sys_common::unwind::try::try_fn::h11728613996190555864
  14:     0x55f5e778153b - __rust_try
  15:     0x55f5e778656b - rt::lang_start::h660c7a8519a9d7d5NSz
  16:     0x7fcc15ccc854 - __libc_start_main
  17:     0x55f5e5bd7bb8 - _start
  18:                0x0 - <unknown>
Servo exited with return value 101
```

**Comment by paulrouget** [comment]
dupe #9931
