### ISSUE TITLE
Unconditional panic "broken pipe" on browser.html

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#10260]
On ddc57fe641c3940ecdad98297ac5b2ff95c3340c, opening browser.html causes a  panic cascade.
```
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:746
stack backtrace:
thread 'ImageCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:746
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb958e80 - result::unwrap_failed::h7710534389483155061
   9:     0x7feabb96ccc8 - api::RenderApi::set_root_stacking_context::h602ef08689313c9dzTb
  10:     0x7feabaa9309e - layout_thread::LayoutThread::perform_post_main_layout_passes::hb347bb704f368aebD3r
  11:     0x7feabaa3fcd7 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h6ef7f1815c4e384fYZr
  12:     0x7feabaa45526 - layout_thread::LayoutThread::handle_reflow::h4aece6c1593cbc38hEr
  13:     0x7feabaa26b46 - layout_thread::LayoutThread::handle_request_helper::hcc380aec424dfc77Cgr
  14:     0x7feabaa0dd91 - layout_thread::LayoutThread::handle_request::ha666d5e8c9bab246Far
  15:     0x7feaba9c679a - sys_common::unwind::try::try_fn::h178074173954338454
  16:     0x7feabc3d995b - __rust_try
  17:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  18:     0x7feaba9c74ba - boxed::F.FnBox<A>::call_box::h15109310667531067309
  19:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  20:     0x7feab824e6a9 - start_thread
  21:     0x7feab7d6deec - clone
  22:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     thread '0xthread '7feabc3d99d1 - PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }LayoutWorker worker 1/6rust_begin_unwindthread '' panicked at 'thread '' panicked at '
LayoutWorker worker 2/6called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 4/6' panicked at '', ' panicked at '', ../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError../src/libcore/result.rs:  ', ', :746 ../src/libcore/result.rs../src/libcore/result.rs7746
::: 
746746 

   0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:  thread '   LayoutWorker worker 5/60x' panicked at '7feabb958e80called `Result::unwrap()` on an `Err` value: RecvError - ', ../src/libcore/result.rs:resultthread '746::LayoutWorker worker 6/6
unwrap_failed' panicked at '::called `Result::unwrap()` on an `Err` value: RecvErrorh7710534389483155061', 
../src/libcore/result.rs:746
   9:   thread '  LayoutWorker worker 3/60x' panicked at '7feabb96bffdcalled `Result::unwrap()` on an `Err` value: RecvError - ', ../src/libcore/result.rs:api746::
RenderApi::add_image::h98ebedefc0b7663fNRb
  10:     0x7feababd5e7c - image_cache_thread::ImageCache::complete_load::hc8763ef20e20545brtc
  11:     0x7feababb6c3c - image_cache_thread::ImageCache::run::h45f6b97b0a5b10ec3kc
  12:     0x7feababe85a2 - sys_common::unwind::try::try_fn::h2088214380120997475
  13:     0x7feabc3d995b - __rust_try
  14:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  15:     0x7feababe89ed - boxed::F.FnBox<A>::call_box::h2855644670016807201
  16:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  17:     0x7feab824e6a9 - start_thread
  18:     0x7feab7d6deec - clone
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:704
  19:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba9ebaed - result::unwrap_failed::h10130405368056425549
   9:     0x7feaba9eaeef - sys_common::unwind::try::try_fn::h8979842578007531737
  10:     0x7feabc3d995b - __rust_try
  11:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7feaba9eb779 - boxed::F.FnBox<A>::call_box::h11037888274056578643
  13:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7feab824e6a9 - start_thread
  15:     0x7feab7d6deec - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb41774d - result::unwrap_failed::h11357295919688266636
   9:     0x7feabb40f68e - paint_thread::PaintThread<C>::start::h17992354333706155155
  10:     0x7feabb401b3d - sys_common::unwind::try::try_fn::h6932361555717787818
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb40250a - boxed::F.FnBox<A>::call_box::h3574615901599107518
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:    thread ' thread '0xPaintWorker7feabc3df61fPaintWorker' panicked at ' - ' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'called `Result::unwrap()` on an `Err` value: RecvErrorpanicking', PaintWorker', ::../src/libcore/result.rs' panicked at ':../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvErrordefault_handler746:', ::
746../src/libcore/result.rs_
:$u7b$$u7b$closure$u7d$$u7d$746::
closure.44522
thread '  PaintWorker ' panicked at '3called `Result::unwrap()` on an `Err` value: RecvError: ', ../src/libcore/result.rs : 746 
 0x7feabc3df298 - panickingthread 'PaintWorker::' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrordefault_handler', ::../src/libcore/result.rs:h4e73712d1e927dfeH0z746

  thread ' PaintWorker4' panicked at ': called `Result::unwrap()` on an `Err` value: RecvError',  ../src/libcore/result.rs: 746 
 0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba9ebaed - result::unwrap_failed::h10130405368056425549
   9:     0x7feaba9eaeef - sys_common::unwind::try::try_fn::h8979842578007531737
  10:     0x7feabc3d995b - __rust_try
  11:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7feaba9eb779 - boxed::F.FnBox<A>::call_box::h11037888274056578643
  13:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7feab824e6a9 - start_thread
  15:     0x7feab7d6deec - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba9ebaed - result::unwrap_failed::h10130405368056425549
   9:     0x7feaba9eaeef - sys_common::unwind::try::try_fn::h8979842578007531737
  10:     0x7feabc3d995b - __rust_try
  11:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7feaba9eb779 - boxed::F.FnBox<A>::call_box::h11037888274056578643
  13:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7feab824e6a9 - start_thread
  15:     0x7feab7d6deec - clone
  16:                0x0 - <unknown>
Unhandled error occured 
stack backtrace:
ReferenceError: navigator.mozSettings API is not available
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba9ebaed - result::unwrap_failed::h10130405368056425549
   9:     0x7feaba9eaeef - sys_common::unwind::try::try_fn::h8979842578007531737
  10:     0x7feabc3d995b - __rust_try
  11:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7feaba9eb779 - boxed::F.FnBox<A>::call_box::h11037888274056578643
  13:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7feab824e6a9 - start_thread
  15:     0x7feab7d6deec - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:   thread ' ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } ' panicked at '0xcalled `Result::unwrap()` on an `Err` value: "SendError(..)"7feabc3df298',  - ../src/libcore/result.rs:panicking::746default_handler
::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba9ebaed - result::unwrap_failed::h10130405368056425549
   9:     0x7feaba9eaeef - sys_common::unwind::try::try_fn::h8979842578007531737
  10:     0x7feabc3d995b - __rust_try
  11:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7feaba9eb779 - boxed::F.FnBox<A>::call_box::h11037888274056578643
  13:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7feab824e6a9 - start_thread
  15:     0x7feab7d6deec - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba9ebaed - result::unwrap_failed::h10130405368056425549
   9:     0x7feaba9eaeef - sys_common::unwind::try::try_fn::h8979842578007531737
  10:     0x7feabc3d995b - __rust_try
  11:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7feaba9eb779 - boxed::F.FnBox<A>::call_box::h11037888274056578643
  13:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7feab824e6a9 - start_thread
  15:     0x7feab7d6deec - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabc422274 - option::expect_failed::h56e104933d0889c7LpO
   9:     0x7feaba9549cf - constellation::Constellation<LTF, STF>::handle_failure_msg::h15316904189790769346
  10:     0x7feaba8ca694 - constellation::Constellation<LTF, STF>::handle_request::h16750745435730608723
  11:     0x7feaba8bb49c - sys_common::unwind::try::try_fn::h1461965658370480272
  12:     0x7feabc3d995b - __rust_try
  13:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  14:     0x7feaba8bc95a - boxed::F.FnBox<A>::call_box::h9233829037839293807
  15:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  16:     0x7feab824e6a9 - start_thread
  17:     0x7feab7d6deec - clone
  18:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb73202d - result::unwrap_failed::h9526193255075918590
   9:     0x7feabb72b7b9 - paint_thread::WorkerThread::main::h0b1760bf617f99ddCgp
  10:     0x7feabb728090 - sys_common::unwind::try::try_fn::h10040041549250172576
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb728791 - boxed::F.FnBox<A>::call_box::h8485372392883069067
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0xthread '7feabc3c9fc8 - <main>sys_common' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"::', unwind../src/libcore/result.rs:::begin_unwind_fmt::746h45dc2fac9b5e0d23m1t

   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb73202d - result::unwrap_failed::h9526193255075918590
   9:     0x7feabb72b7b9 - paint_thread::WorkerThread::main::h0b1760bf617f99ddCgp
  10:     0x7feabb728090 - sys_common::unwind::try::try_fn::h10040041549250172576
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb728791 - boxed::F.FnBox<A>::call_box::h8485372392883069067
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb73202d - result::unwrap_failed::h9526193255075918590
   9:     0x7feabb72b7b9 - paint_thread::WorkerThread::main::h0b1760bf617f99ddCgp
  10:     0x7feabb728090 - sys_common::unwind::try::try_fn::h10040041549250172576
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb728791 - boxed::F.FnBox<A>::call_box::h8485372392883069067
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb73202d - result::unwrap_failed::h9526193255075918590
   9:     0x7feabb72b7b9 - paint_thread::WorkerThread::main::h0b1760bf617f99ddCgp
  10:     0x7feabb728090 - sys_common::unwind::try::try_fn::h10040041549250172576
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb728791 - boxed::F.FnBox<A>::call_box::h8485372392883069067
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb73202d - result::unwrap_failed::h9526193255075918590
   9:     0x7feabb72b7b9 - paint_thread::WorkerThread::main::h0b1760bf617f99ddCgp
  10:     0x7feabb728090 - sys_common::unwind::try::try_fn::h10040041549250172576
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb728791 - boxed::F.FnBox<A>::call_box::h8485372392883069067
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb73202d - result::unwrap_failed::h9526193255075918590
   9:     0x7feabb72b7b9 - paint_thread::WorkerThread::main::h0b1760bf617f99ddCgp
  10:     0x7feabb728090 - sys_common::unwind::try::try_fn::h10040041549250172576
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb728791 - boxed::F.FnBox<A>::call_box::h8485372392883069067
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabaf6e0ce - result::unwrap_failed::h693493387397716130
   9:     0x7feabaf6d62d - dom::window::Window::force_reflow::h7ca0fe6d30520e6d2bo
  10:     0x7feabaeff2ab - dom::window::Window::reflow::hf553bad52bfb14886jo
  11:     0x7feabaf7399b - dom::window::Window::handle_fire_timer::h0af9050eae7ec0aaKso
  12:     0x7feabae204ad - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.188281
  13:     0x7feabae092d1 - script_thread::ScriptThread::handle_msgs::h90dca76a951af0d7Int
  14:     0x7feabadb34d7 - sys_common::unwind::try::try_fn::h11662287144244999193
  15:     0x7feabc3d995b - __rust_try
  16:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  17:     0x7feabadb4752 - boxed::F.FnBox<A>::call_box::h10848876649555361395
  18:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  19:     0x7feab824e6a9 - start_thread
  20:     0x7feab7d6deec - clone
  21:                0x0 - <unknown>
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feaba84b0de - result::unwrap_failed::h9469585495671998005
   9:     0x7feaba878a12 - compositor::IOCompositor<Window>::process_animations::h12745672159024818116
  10:     0x7feaba87756b - compositor::IOCompositor<Window>::composite_specific_target::h6067814314774665741
  11:     0x7feaba87ca41 - compositor::IOCompositor<Window>::composite::h3262951316666432995
  12:     0x7feaba84c839 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h17586676149097272261
  13:     0x7feaba882ccc - Browser::handle_events::h6be134fb85f5275fWea
  14:     0x7feaba838aa5 - main::h816805d8d509cd3eMaa
  15:     0x7feabc3deef4 - sys_common::unwind::try::try_fn::h11728613996190555864
  16:     0x7feabc3d995b - __rust_try
  17:     0x7feabc3de98b - rt::lang_start::h660c7a8519a9d7d5NSz
  18:     0x7feab7c87a3f - __libc_start_main
  19:     0x7feaba82ebe8 - _start
  20:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7feabc3da6d0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7feabc3df61f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7feabc3df298 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7feabc3c901c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7feabc3c9fc8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7feabc3d99d1 - rust_begin_unwind
   7:     0x7feabc41703f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7feabb3ad29e - result::unwrap_failed::h18155234081082901597
   9:     0x7feabb3aaa0e - window::GlutinCompositorProxy.CompositorProxy::send::h0622932a27de3191m8a
  10:     0x7feabb3d89f7 - sys_common::unwind::try::try_fn::h1850706381270513513
  11:     0x7feabc3d995b - __rust_try
  12:     0x7feabc3d98ed - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  13:     0x7feabb3d9554 - boxed::F.FnBox<A>::call_box::h11572605626687618748
  14:     0x7feabc3ddbe9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  15:     0x7feab824e6a9 - start_thread
  16:     0x7feab7d6deec - clone
  17:                0x0 - <unknown>
/home/manishearth/Mozilla/servo/target/release/build
Servo exited with return value 101
```

**Comment by Manishearth** [comment]
@eddyb is this due to the IPC fix?

**Comment by eddyb** [comment]
@Manishearth Possibly, I get this with only my IPC change on an older master. I didn't actually try `--browserhtml` after making those changes and I'm not sure how it affects the way IPC works.

**Comment by Manishearth** [comment]
cc @pcwalton
