### ISSUE TITLE
Panic 'No texture page for ID TextureId(1022)' in texture_cache.rs:591

### ISSUE THREAD

**Issue by nical** [servo/servo#10281]
I always get this panic after a few seconds when running a local build of [today's master branch](https://github.com/servo/servo/commit/21e4936f6a4a99ed7071a8c94bc6e1d418944e67).

To reproduce, I just run "./mach run --release -w" and scroll down the page.

```
thread '<unnamed>' panicked at 'No texture page for ID TextureId(1022)', /home/nical/dev/mozilla/research/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/texture_cache.rs:591
stack backtrace:
   1:     0x562bdfc57bf0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x562bdfc5cb3f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x562bdfc5c7b8 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x562bdfc4653c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x562bdfc474e8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x562bdee16470 - texture_cache::TextureCache::free::hf63a3f8095da64caYQr
   7:     0x562bdedf41e4 - resource_cache::ResourceCache::expire_old_resources::h6ca22fdfdda585d3yOp
   8:     0x562bdee083ac - frame::Frame::build::h9a7597a0d2edc080WIk
   9:     0x562bdee5c685 - render_backend::RenderBackend::render::hea4876f9023cc5b2arp
  10:     0x562bdee29913 - render_backend::RenderBackend::run::h172a80140499b63fxgp
  11:     0x562bdedd0da5 - sys_common::unwind::try::try_fn::h6388910774152724850
  12:     0x562bdfc56e7b - __rust_try
  13:     0x562bdfc56e0d - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  14:     0x562bdedd1227 - boxed::F.FnBox<A>::call_box::h5057319158424758780
  15:     0x562bdfc5b109 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  16:     0x7eff75f44609 - start_thread
  17:     0x7eff75a67a4c - clone
  18:                0x0 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x562bdfc57bf0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x562bdfc5cb3f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x562bdfc5c7b8 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x562bdfc4653c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x562bdfc474e8 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x562bdfc56ef1 - rust_begin_unwind
   7:     0x562bdfc9453f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x562bdf24a16e - result::unwrap_failed::h13648296078549524712
   9:     0x562bdf24c2be - api::RenderApi::translate_point_to_layer_space::hbf040caa69b956381Vb
  10:     0x562bde1387ae - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h17202164066083652982
  11:     0x562bde16e12c - Browser::handle_events::he13041ac5c6f6095tea
  12:     0x562bde123d95 - main::h9cc0aa5bb4f2f2aeqaa
  13:     0x562bdfc5c414 - sys_common::unwind::try::try_fn::h11728613996190555864
  14:     0x562bdfc56e7b - __rust_try
  15:     0x562bdfc5beab - rt::lang_start::h660c7a8519a9d7d5NSz
  16:     0x7eff7598557f - __libc_start_main
  17:     0x562bde1220e8 - _start
  18:                0x0 - <unknown>
Servo exited with return value 101

```

**Comment by nical** [comment]
I also get this panic if every time I resize the window down to a small-ish size and it seems to always be the same size.

I only ran into this panic on the default page so far (reddit works fine, for example).

**Comment by paulrouget** [comment]
> default page

What's the default page?

**Comment by nical** [comment]
The default page is the one you get when starting servo without browser.html and without an url. Looks like it's [https://servo.org/](servo.org).

**Comment by paulrouget** [comment]
dupe #9931
