### ISSUE TITLE
Android: crash on start

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#10308]
I've just built 436f731 (release build) for Android, but it crashes on start:

```
I/ActivityManager( 3194): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.mozilla.servo/.MainActivity} from pid 4187
D/AndroidRuntime( 4187): Shutting down VM
D/dalvikvm( 4187): GC_CONCURRENT freed 95K, 15% free 586K/684K, paused 0ms+0ms, total 1ms
I/ActivityManager( 3194): Start proc com.mozilla.servo for activity com.mozilla.servo/.MainActivity: pid=4197 uid=10058 gids={50058, 3003, 1028, 1015, 1023}
I/servo_wrapper( 4197): Loading the NativeActivity
D/dalvikvm( 4197): GC_FOR_ALLOC freed 68K, 5% free 2849K/2976K, paused 8ms, total 8ms
I/dalvikvm-heap( 4197): Grow heap (frag case) to 6.834MB for 4194320-byte allocation
D/dalvikvm( 4197): GC_CONCURRENT freed 1K, 2% free 6943K/7076K, paused 0ms+0ms, total 6ms
D/dalvikvm( 4197): WAIT_FOR_CONCURRENT_GC blocked 6ms
D/AndroidRuntime( 4197): Shutting down VM
W/dalvikvm( 4197): threadid=1: thread exiting with uncaught exception (group=0x41a53ba8)
E/AndroidRuntime( 4197): FATAL EXCEPTION: main
E/AndroidRuntime( 4197): Process: com.mozilla.servo, PID: 4197
E/AndroidRuntime( 4197): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mozilla.servo/com.mozilla.servo.MainActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.mozilla.servo-2/libmain.so
E/AndroidRuntime( 4197): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime( 4197): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 4197): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 4197): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 4197): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4197): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4197): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 4197): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4197): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4197): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 4197): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 4197): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4197): Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.mozilla.servo-2/libmain.so
E/AndroidRuntime( 4197): 	at android.app.NativeActivity.onCreate(NativeActivity.java:183)
E/AndroidRuntime( 4197): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 4197): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 4197): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime( 4197): 	... 11 more
W/ActivityManager( 3194):   Force finishing activity com.mozilla.servo/.MainActivity
W/ActivityManager( 3194): Activity pause timeout for ActivityRecord{41f78538 u0 com.mozilla.servo/.MainActivity t6 f}
```

I'm using an Odroid XU3, running Android 4.4.4

**Comment by alopatindev** [comment]
I've built e8e354d and got the same issue on emulator (Android 4.3.1) and on Meizu MX4 (Android 5.1) when running a release build (debug build runs fine).

Loading library with `System.loadLibrary` gives more reasonable output:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "eglGetPlatformDisplay" referenced by "libmain.so"...
```

In the output of `objdump -T libmain.so` there is
```
00000000      D  *UND*  00000000 eglGetPlatformDisplay
```
in the [release build](https://gist.githubusercontent.com/alopatindev/abd66c63c87e890e66cb1979eae13189/raw/36586420716928b5a2976969b92a25ceedb8cd65/libmain_symbols_release.txt) (and probably some other problematic functions) but there's no such thing in the [debug build](https://gist.github.com/alopatindev/961629c32050efe5875820879094176d/raw/26260d9ad026c2b338c2ee5b24a4cfe5da372515/libmain_symbols_debug.txt).

So it's probably related to `servo-glutin` or `servo-egl` somehow.

(I use `android-ndk-11c`. Also please note that I compile release build with `opt-level = 2` in `[profile.release]` of `components/servo/Cargo.toml`, because `opt-level = 3` fails with `LLVM ERROR: Constant Island pass failed to converge` when compiling `.cargo/registry/src/github.com-88ac128001ac3a9a/cssparser-0.5.5/src/lib.rs` for me).

**Comment by alopatindev** [comment]
Enabling `lto` in `[profile.release]` solves this issue for me.

Maybe it's okay to enable LTO for release builds (or at least for Android release builds only, if possible) or there's a particular reason why it's disabled? Thanks!

**Comment by mmatyas** [comment]
Using `lto = true` and `opt-level = 2` did fix the build, but now I get a black screen. Not sure if related.

**Comment by mmatyas** [comment]
This got fixed, Servo now loads on Android.
