### ISSUE TITLE
link-load-event.html is failing due to wptrunner changes

### ISSUE THREAD

**Issue by jdm** [servo/servo#10375]
Something in the implementation of pipes changed in the recent upgrade (78369e95cf7ed0813cb9342747caa4984ae7c527) which broke this test:
```
 0:01.00 LOG: MainThread wptserve INFO Starting http server on 127.0.0.1:8000
 0:01.00 LOG: MainThread wptserve INFO Starting http server on 127.0.0.1:8443
 0:01.01 LOG: MainThread wptserve INFO Starting http server on 127.0.0.1:8001
 0:03.00 SUITE_START: MainThread 1
 0:03.00 LOG: MainThread INFO Running testharness tests
 0:03.00 LOG: Thread-TestrunnerManager-1 INFO Starting runner
 0:03.00 LOG: Thread-TestrunnerManager-2 INFO Starting runner
 0:03.01 LOG: Thread-TestrunnerManager-3 INFO Starting runner
 0:03.01 LOG: Thread-TestrunnerManager-4 INFO Starting runner
 0:03.01 TEST_START: Thread-TestrunnerManager-1 /html/semantics/document-metadata/the-link-element/link-load-event.html
 0:03.01 LOG: Thread-TestrunnerManager-5 INFO No more tests
 0:03.01 LOG: Thread-TestrunnerManager-6 INFO No more tests
 0:03.02 LOG: Thread-TestrunnerManager-7 INFO No more tests
 0:03.02 LOG: Thread-TestrunnerManager-8 INFO No more tests
 0:04.02 LOG: Thread-TestrunnerManager-2 WARNING u'runner_teardown' ()
 0:04.02 LOG: Thread-TestrunnerManager-2 INFO No more tests
 0:04.02 LOG: Thread-TestrunnerManager-3 WARNING u'runner_teardown' ()
 0:04.02 LOG: Thread-TestrunnerManager-3 INFO No more tests
 0:04.02 LOG: Thread-TestrunnerManager-4 WARNING u'runner_teardown' ()
 0:04.02 LOG: Thread-TestrunnerManager-4 INFO No more tests
 0:06.94 LOG: Thread-5 wptserve WARNING Traceback (most recent call last):
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/server.py", line 272, in handle_one_request
    response.write()
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 215, in write
    self.write_content()
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 209, in write_content
    for item in self.iter_content():
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 191, in iter_content
    for item in self.content:
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 252, in add_content
    modified_content.append(content[offset[0]:])
NameError: global name 'modified_content' is not defined

 0:06.94 LOG: Thread-5 wptserve WARNING Traceback (most recent call last):
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/server.py", line 272, in handle_one_request
    response.write()
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 215, in write
    self.write_content()
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 209, in write_content
    for item in self.iter_content():
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 191, in iter_content
    for item in self.content:
  File "/Users/jdm/src/dev-servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 252, in add_content
    modified_content.append(content[offset[0]:])
NameError: global name 'modified_content' is not defined
```

**Comment by jdm** [comment]
cc @jgraham

**Comment by jdm** [comment]
A bunch of Opera's script scheduling tests that rely on the trickle modifier are similarly timing out since that upgrade.

**Comment by jdm** [comment]
We're missing the changes in https://github.com/w3c/wptserve/commit/66ffd809ef8561e3f7ef63d1e9c085be12ef3ebe .

**Comment by Ms2ger** [comment]
Fixing.
