### ISSUE TITLE
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err`

### ISSUE THREAD

**Issue by ojab** [servo/servo#10383]
Testcase:
```js
var fps = 0, lrd_mtm = Date.now();

function oef() {
    if (1E3 < Date.now() - lrd_mtm) {
        console.log("FPS: " + fps);
        fps = 0;
        lrd_mtm = Date.now()
    }
    redraw();
    window.requestAnimationFrame(oef)
};

function redraw() {
    fps++;
    var canvas = document.createElement("canvas");
    var canvas2 = document.createElement("canvas");
    canvas.width = 1;
    canvas.height = 1;
    var b = canvas2.getContext("2d");
    b.drawImage(canvas, 0, 0)
};

oef();
```
Running `./mach run -d -w /tmp/index.html` (index.html contains testcase) and then hiding the servo window (i. e. minimizing it, switching to different workspace, etc) leads to
```
$ ./mach run -d -w /tmp/index.html
FPS: 60
FPS: 61
FPS: 61
FPS: 297
FPS: 393
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10f73d3f8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10f740fe9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10f740c18 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10f72c1f6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10f72d08e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10f73c797 - rust_begin_unwind
   7:        0x10f7662b0 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10e3f6e57 - result::unwrap_failed::h16364568829960559968
   9:        0x10e3f777f - result::Result<T, E>::unwrap::h5658865942815288014
  10:        0x10e3f75a1 - thread::spawn_named::h5386996217261080472
  11:        0x10e3f6a2d - canvas_paint_thread::CanvasPaintThread<'a>::start::h44d888df6308c789tha
  12:        0x10ca151ee - constellation::Constellation<LTF, STF>::handle_create_canvas_paint_thread_msg::h6896572505119110098
  13:        0x10c8a979d - constellation::Constellation<LTF, STF>::handle_request::h13027902211717275186
  14:        0x10c89e105 - constellation::Constellation<LTF, STF>::run::h2582769816899259328
  15:        0x10c88f99d - compositing::constellation::Constellation<LTF, STF>::start::_$u7b$$u7b$closure$u7d$$u7d$::closure.25795
  16:        0x10c88e233 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.25784
  17:        0x10c88e1a8 - sys_common::unwind::try::try_fn::h17565949979340975340
  18:        0x10f73c72b - __rust_try
  19:        0x10f73c6b3 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  20:        0x10c88e0e5 - sys_common::unwind::try::h15318895531005675481
  21:        0x10c88df1e - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::closure.25762
  22:        0x10c88fc77 - boxed::F.FnBox<A>::call_box::h16470970604976751852
  23:        0x10f7400cc - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  24:     0x7fff8f36d99c - _pthread_body
  25:     0x7fff8f36d919 - _pthread_start
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) })', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10f73d3f8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10f740fe9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
   3:        0x10f740c18 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10f72c1f6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10f72d08e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10f73c797 - rust_begin_unwind
   7:        0x10f7662b0 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10cf2d2e8 - result::unwrap_failed::h16066348550646723726
   9:        0x10d4eed95 - result::Result<T, E>::unwrap::h6112270607332438709
  10:        0x10d4ee5ff - dom::canvasrenderingcontext2d::CanvasRenderingContext2D::new_inherited::hac15e5011d06d31dojK
  11:        0x10d4f1167 - dom::canvasrenderingcontext2d::CanvasRenderingContext2D::new::h990c19556738bbf6nkK
  12:        0x10d539419 - dom::htmlcanvaselement::HTMLCanvasElement::get_or_init_2d_context::hf36aea6155d81d3eJa0
  13:        0x10d1e0a94 - dom::htmlcanvaselement::HTMLCanvasElement.HTMLCanvasElementMethods::GetContext::h6750294d1d96c454si0
  14:        0x10d1dfe58 - dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::getContext::__rust_abi
  15:        0x10d1df9c8 - dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::getContext::hd127d0d997b45d6aDsb
  16:        0x10ea7d7a0 - CallJitMethodOp
  17:        0x10cff50ed - dom::bindings::utils::generic_call::h0b0a431c8c93d3f7Vpg
  18:        0x10cff62ab - dom::bindings::utils::generic_method::__rust_abi
  19:        0x10cff6272 - dom::bindings::utils::generic_method::h3e7d926460f472caxtg
fatal runtime error: Could not unwind stack, error = 5
stack backtrace:
Servo exited with return value -4
```

Mac OS X 10.11.4 here.

**Comment by jdm** [comment]
Looks like we may need to be eager about shutting down canvas threads when possible. We may need more GC hinting like https://gist.github.com/jdm/1d2e71157887849c7ba2.

**Comment by nox** [comment]
This is kinda related to #10381.

**Comment by lumiscosity** [comment]
Seems to work fine on Arch Linux x86-64 (tried minimizing and suspending, fps dropped but no panic happened), GNOME DE, X11, servo built against commit 9d29017c0dc6eec4ca7cd868cc13056e0bc0c64a. The other mentioned issue has also been resolved. Still, considering the original was tested on MacOS, might be worth keeping open until a comparable Mac testcase is made...

**Comment by jdm** [comment]
Also tested on macOS and see the same thing: FPS drop, but no panic.
