### ISSUE TITLE
mach test fail on Windows

### ISSUE THREAD

**Issue by veirus** [servo/servo#10395]
Running under mingw64 shell installed with msys2 on Windows 8.1 x64 gives this result:

```
[0] % ./mach test
Checking files for tidiness...
  Progress: 100% (8083/8083)
Running the WPT lint...
  Progress: 100% (19075/19075)
tidy reported no errors.
Error running mach:

    ['test']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'/mingw64/bin/openssl', 'req', '-config', '/tmp/tmpiJgWjL/openssl.cfg', '-batch', '-new', '-newkey', 'rsa:2048', '-keyout', '/tmp/tmpiJgWjL/cakey.pem', '-out', '/tmp/tmpiJgWjL/careq.pem', '-subj', '/CN=web-platform-tests', '-passout', 'pass:web-platform-tests']' returned non-zero exit status 1

  File "/home/Neil/servo/python/servo/testing_commands.py", line 127, in test
    Registrar.dispatch("test-%s" % suite, context=self.context, **kwargs)
  File "/home/Neil/servo/python/mach/mach/registrar.py", line 115, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/home/Neil/servo/python/mach/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
  File "/home/Neil/servo/python/servo/testing_commands.py", line 320, in test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "/home/Neil/servo/python/servo/testing_commands.py", line 334, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "/home/Neil/servo/tests/wpt/run_wpt.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/home/Neil/servo/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/home/Neil/servo/tests/wpt/harness/wptrunner/wptrunner.py", line 155, in run_tests
    env_options) as test_environment:
  File "/home/Neil/servo/tests/wpt/harness/wptrunner/environment.py", line 106, in __enter__
    self.config = self.load_config()
  File "/home/Neil/servo/tests/wpt/harness/wptrunner/environment.py", line 154, in load_config
    key_file, certificate = self.ssl_env.host_cert_path(hosts)
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 350, in host_cert_path
    key, cert = self._generate_host_cert(hosts)
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 370, in _generate_host_cert
    self._generate_ca()
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 321, in _generate_ca
    "-passout", "pass:%s" % self.password)
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 69, in __call__
    output=stdout)
```

**Comment by Ms2ger** [comment]
CC @jgraham

**Comment by jgraham** [comment]
Does it happen if you use the OpenSSL setup documented at https://github.com/w3c/web-platform-tests#windows-notes ? I suspect mingw's openssl is less weird, or at least weird in a different way, compared to the other Windows distributions, and so will need to be detected and (probably) input paths changed to match what it accepts.

**Comment by veirus** [comment]
With Shining Light setup:
```
$ ./mach test-wpt
Error running mach:

    ['test-wpt']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'/c/OpenSSL-Win64/bin/openssl', 'req', '-config', '/tmp/tmpQNYvKu/openssl.cfg', '-batch', '-new', '-newkey', 'rsa:2048', '-keyout', '/tmp/tmpQNYvKu/cakey.pem', '-out', '/tmp/tmpQNYvKu/careq.pem', '-subj', '/CN=web-platform-tests', '-passout', 'pass:web-platform-tests']' returned non-zero exit status 1

  File "/home/Neil/servo/python/servo/testing_commands.py", line 320, in test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "/home/Neil/servo/python/servo/testing_commands.py", line 334, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "/home/Neil/servo/tests/wpt/run_wpt.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/home/Neil/servo/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/home/Neil/servo/tests/wpt/harness/wptrunner/wptrunner.py", line 155, in run_tests
    env_options) as test_environment:
  File "/home/Neil/servo/tests/wpt/harness/wptrunner/environment.py", line 106, in __enter__
    self.config = self.load_config()
  File "/home/Neil/servo/tests/wpt/harness/wptrunner/environment.py", line 154, in load_config
    key_file, certificate = self.ssl_env.host_cert_path(hosts)
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 350, in host_cert_path
    key, cert = self._generate_host_cert(hosts)
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 370, in _generate_host_cert
    self._generate_ca()
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 321, in _generate_ca
    "-passout", "pass:%s" % self.password)
  File "/home/Neil/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 69, in __call__
    output=stdout)
```

**Comment by yoava333** [comment]
@jgraham I've encountered the same problem, when digging a bit deeper, I get the follow error message from openssl
```
Generating a 2048 bit RSA private key
.......................................................................+++
...........................................................................................................................+++
writing new private key to 'C:/msys64/tmp/tmpg6bLcg/cakey.pem'
-----
Subject does not start with '/'.
problems making Certificate Request
```

Googling the problem lead me to this stackoverflow thread - http://stackoverflow.com/a/31990313

I've added another forward slash to https://github.com/servo/servo/blob/e273517fe06720afe0ef74815cce5e007df7dc3d/tests/wpt/web-platform-tests/tools/sslutils/openssl.py#L94

And this lead me to the next error:
```
/tmp/tmpKyWXga: No such file or directory
Using configuration from C:/msys64/tmp/tmpKyWXga/openssl.cfg
I am unable to access the /tmp/tmpKyWXga directory
```
Looking at openssl.cfg
```
[ ca ]
default_ca = CA_default

[ CA_default ]
dir = /tmp/tmpdEY2Du
certs = $dir
new_certs_dir = $certs
crl_dir = $dir/crl
database = $dir/index.txt
private_key = $dir/cakey.pem
certificate = $dir/cacert.pem
serial = $dir/serial
crldir = $dir/crl
```

changed dir from  /tmp/tmpdEY2Du to C:/msys64/tmp/tmpdEY2Du and it worked.

added
```
root_dir = 'C:/msys64/{}'.format(root_dir)
```
to https://github.com/servo/servo/blob/e273517fe06720afe0ef74815cce5e007df7dc3d/tests/wpt/web-platform-tests/tools/sslutils/openssl.py#L109

and now I get a new error:
```
$ ./mach test-wpt ./tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/
Running 8 tests in web-platform-tests

  [0/8] /html/semantics/tabular-data/the-table-element/caption-methods.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/caption-methods.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/caption-methods.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  [1/8] /html/semantics/tabular-data/the-table-element/insertRow-method-01.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/createTBody.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/createTBody.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  [2/8] /html/semantics/tabular-data/the-table-element/insertRow-method-01.html
        /html/semantics/tabular-data/the-table-element/insertRow-method-02.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/insertRow-method-01.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/delete-caption.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/delete-caption.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/insertRow-method-01.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  [4/8] /html/semantics/tabular-data/the-table-element/insertRow-method-02.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/insertRow-method-02.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/insertRow-method-02.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  [5/8] /html/semantics/tabular-data/the-table-element/table-insertRow.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/tBodies.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/tBodies.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  [6/8] /html/semantics/tabular-data/the-table-element/table-insertRow.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/table-insertRow.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/table-insertRow.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


  [7/8] /html/semantics/tabular-data/the-table-element/table-rows.html
STDERR: ['/c/work/rust/servo/target/debug/servo', '--cpu', '--hard-fail', '-u', 'Servo/wptrunner', '-z', u'http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/table-rows.html', '--user-stylesheet', '/c/work/rust/servo/resources/ahem.css']
  ▶ ERROR [expected OK] /html/semantics/tabular-data/the-table-element/table-rows.html
  └   → Traceback (most recent call last):
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/base.py", line 133, in run_test
    result = self.do_test(test)
  File "/c/work/rust/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 100, in do_test
    self.proc.run()
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/c/work/rust/servo/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable


Ran 8 tests finished in 2.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 8 tests had errors unexpectedly
```

**Comment by yoava333** [comment]
I investigated a big further, it seems that we're hitting an msys64 bug.
When running the same code on *nix it works.
I've reduced the error to this snippet:
```
from multiprocessing import Process
import threading
import subprocess
import time

class A(threading.Thread):
    def run(self):
        print "inside A.run"
        Process(target=create_process, args=('notepad', )).start()
        time.sleep(20)


def create_process(process_name):
    print "create_process"
    subprocess.call([process_name]) 

print "starting"

A().start()
time.sleep(5)

print "done"
```

The error I'm getting:
```
$ python2.7 main.py
starting
inside A.run
create_process
      0 [main] python2.7 22692 fork: child -1 - forked process 14624 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 15, in create_process
    subprocess.call([process_name])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
done
```

I'm using msys python:
```
$ python2.7
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by zeusintuivo** [comment]
I have researched and documented an effective way to have windows environments set up for 32 and 64 bits in Windows 7. I assume this will work in all windowses. 
Please see documentation I posted in this ticket. #12356

**Comment by nox** [comment]
Does this still happen?

**Comment by dralley** [comment]
Bump

**Comment by jdm** [comment]
It should now be possible to run individual WPT tests on Windows. Running multiple tests still is broken (#20365).
