### ISSUE TITLE
thread 'CanvasThread' panicked at 'called `Result::unwrap()` on too large IPC messages

### ISSUE THREAD

**Issue by ojab** [servo/servo#10390]
Testcase:

``` js
var canvas = document.createElement("canvas");
var canvas2 = document.createElement("canvas");
canvas.width = 10000;
canvas.height = 10000;
var b = canvas2.getContext("2d");
b.drawImage(canvas, 0, 0)
```

leads to 

```
thread 'CanvasThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10b4399b8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b43d5a9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b43d1d8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b4285c6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b4295fe - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10b438d57 - rust_begin_unwind
   7:        0x10b463190 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10a77d7f9 - result::unwrap_failed::h12921039295456747958
   9:        0x10a78761d - canvas_paint_thread::CanvasPaintThread<'a>::start::_$u7b$$u7b$closure$u7d$$u7d$::closure.18386
  10:        0x10a77e160 - sys_common::unwind::try::try_fn::h8885834032707868043
  11:        0x10b438ceb - __rust_try
  12:        0x10b438c73 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  13:        0x10a78898e - boxed::F.FnBox<A>::call_box::h7550699622691377600
  14:        0x10b43c68c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  15:     0x7fff8f36d99c - _pthread_body
  16:     0x7fff8f36d919 - _pthread_start
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) })', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10b4399b8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b43d5a9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b43d1d8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b4285c6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b4295fe - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10b438d57 - rust_begin_unwind
   7:        0x10b463190 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x109db30b7 - result::unwrap_failed::h13001563860650491539
   9:        0x109e3f4c1 - dom::canvasrenderingcontext2d::CanvasRenderingContext2D::draw_html_canvas_element::hee206703e3709de0QsK
  10:        0x109e3e196 - dom::canvasrenderingcontext2d::CanvasRenderingContext2D::draw_image::hf20909b5d94a4860MpK
  11:        0x109e476a0 - dom::canvasrenderingcontext2d::CanvasRenderingContext2D.CanvasRenderingContext2DMethods::DrawImage::hb335da68690d609dXQK
  12:        0x10a07f060 - dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::drawImage::h3dd3e3224bb376ae9jE
  13:        0x10aab6720 - CallJitMethodOp
  14:        0x10a07a18f - dom::bindings::utils::generic_call::h02d2ee2892d4f1e0Vpg
  15:        0x10ac2fe7b - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  16:        0x10ac416c9 - _ZL9InterpretP9JSContextRN2js8RunStateE
  17:        0x10ac3766a - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  18:        0x10ac46d38 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeENS_16AbstractFramePtrEPS9_
  19:        0x10ac46e63 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  20:        0x10af535e5 - _ZL8EvaluateP9JSContextN2JS6HandleIP8JSObjectEERKNS1_22ReadOnlyCompileOptionsERNS1_18SourceBufferHolderENS1_13MutableHandleINS1_5ValueEEE
  21:        0x10af5375a - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
  22:        0x109fa905c - dom::htmlscriptelement::HTMLScriptElement::execute::h25ea3a536f8d0cb7D97
  23:        0x109fa5b14 - dom::document::Document::finish_load::h5eaa5836b7b14f35GhQ
  24:        0x109fcf39d - dom::htmlscriptelement::ScriptContext.AsyncResponseListener::response_complete::hf7c02280c496b354DX7
  25:        0x10a98d25a - ResponseAction::process::hffa69e07da1057e4Ypf
  26:        0x109fd4d10 - network_listener::ListenerRunnable<T>.Runnable::handler::h335806639348041197
  27:        0x10a1ea55e - script_thread::ScriptThread::handle_msg_from_script::hc81dcf61b00f79e3JRv
  28:        0x10a2597e8 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.191045
  29:        0x10a241f3e - script_thread::ScriptThread::handle_msgs::h690f4ba0a9c05601nDv
  30:        0x10a1d4077 - sys_common::unwind::try::try_fn::h5752586391069964203
  31:        0x10b438ceb - __rust_try
  32:        0x10b438c73 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  33:        0x10a1d53aa - boxed::F.FnBox<A>::call_box::h2773429460149096240
  34:        0x10b43c68c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  35:     0x7fff8f36d99c - _pthread_body
  36:     0x7fff8f36d919 - _pthread_start
Servo exited with return value -11
```

**Comment by ojab** [comment]
Mac OS X here, if it's important.

**Comment by nox** [comment]
This still happens.

**Comment by jdm** [comment]
The ipc-channel issue was fixed.
