### ISSUE TITLE
Correctly validate WebGL linkProgram and following commands

### ISSUE THREAD

**Issue by autrilla** [servo/servo#10478]
I was writing a new test for WebGL uniform handling and I stumbled upon this issue. It can be reproduced running `tests/wpt/web-platform-tests/webgl/uniformMatrixNfv.html`. Running it on Chromium displays an error, `WebGL: INVALID_OPERATION: getUniformLocation: program not linked`, so my guess is tests should link their shaders by themselves, but hey don't. The thread probably should not panic anyway. Here's the trace:

```
 0:06.75 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "thread 'WebGLThread' panicked at 'Unexpected WebGL error: 0x502 (1282)', /home/autrilla/projects/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:413"
 0:06.75 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "stack backtrace:"
 0:07.37 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   1:     0x5655516ff950 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   2:     0x565551704a6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   3:     0x5655517046d2 - std::panicking::default_hook::h08ad3bb09872855b"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   4:     0x565550da85f0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h9cbc21e67942d4f0"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   5:     0x565550d577b0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h9705b3ed3f7d4b45"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   6:     0x56554e9046a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h8a3a5b46e98dfc25"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   7:     0x56554e8ed350 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7ccc4343a7f21125"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   8:     0x56554f7690c0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h833555d5ac1b1973"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   9:     0x56554e5b4f30 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6945826352f28d62"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  10:     0x56554e92f5a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::ha6793451269441f6"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  11:     0x56554f4000a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h509038c0caf5876e"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  12:     0x56554f423c10 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h574e8acaf52a3457"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  13:     0x56554eec9dd0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4329d9fc61427647"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  14:     0x56554eec9dd0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4329d9fc61427647"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  15:     0x56554eec9dd0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4329d9fc61427647"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  16:     0x56554e79ea20 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2183bfabf9092325"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  17:     0x56554f79c6a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf5e9bc412078cf28"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  18:     0x56554f79c6a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf5e9bc412078cf28"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  19:     0x56554f79c6a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf5e9bc412078cf28"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  20:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  21:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  22:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  23:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  24:     0x5655503a2430 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6e2629f1d9eca42e"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  25:     0x5655516eda03 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  26:     0x5655516eecb8 - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  27:     0x565550392de6 - webrender_traits::webgl::WebGLCommand::apply::h4535da6699e09e5a"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/servo/<std macros>:8"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  28:     0x56555038f262 - canvas::webgl_paint_thread::WebGLPaintThread::handle_webgl_message::h65bdc6730a2fcc5c"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/canvas/webgl_paint_thread.rs:52"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  29:     0x5655503a1653 - canvas::webgl_paint_thread::WebGLPaintThread::start::_$u7b$$u7b$closure$u7d$$u7d$::h23915070ee1eb562"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/canvas/webgl_paint_thread.rs:79"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  30:     0x5655503a1cd8 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::h53c6b4f9ee08cc76"
 0:07.38 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  31:     0x5655503a33f5 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hd7573e8ede423b2e"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  32:     0x5655503a3362 - std::sys_common::unwind::try::try_fn::hdb9a2154dcb7da0c"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at ../src/libstd/sys/common/unwind/mod.rs:127"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  33:     0x5655516feb2b - __rust_try"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  34:     0x5655516feabd - std::sys_common::unwind::inner_try::h4e97625a08807651"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  35:     0x5655503a32ae - std::sys_common::unwind::try::h0410cd6f9a2d3fe5"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at ../src/libstd/sys/common/unwind/mod.rs:123"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  36:     0x5655503a30de - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hc362376056b0e38d"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  37:     0x5655503a3b5b - _<F as std..boxed..FnBox<A>>::call_box::hf62698d151c86230"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at ../src/liballoc/boxed.rs:541"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  38:     0x565551702f44 - std::sys::thread::Thread::new::thread_start::h74af400293164137"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  39:     0x7f8e6b99b423 - start_thread"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  40:     0x7f8e6b4c4cbc - clone"
 0:07.39 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  41:                0x0 - <unknown>"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }).', /home/autrilla/projects/servo/components/compositing/compositor.rs:764"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "stack backtrace:"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   1:     0x5655516ff950 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   2:     0x565551704a6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   3:     0x5655517046d2 - std::panicking::default_hook::h08ad3bb09872855b"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   4:     0x565550da85f0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h9cbc21e67942d4f0"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   5:     0x565550d577b0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h9705b3ed3f7d4b45"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   6:     0x56554e9046a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h8a3a5b46e98dfc25"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   7:     0x56554e8ed350 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7ccc4343a7f21125"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   8:     0x56554f7690c0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h833555d5ac1b1973"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "   9:     0x56554e5b4f30 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6945826352f28d62"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  10:     0x56554e92f5a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::ha6793451269441f6"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  11:     0x56554f4000a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h509038c0caf5876e"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  12:     0x56554f423c10 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h574e8acaf52a3457"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  13:     0x56554eec9dd0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4329d9fc61427647"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  14:     0x56554eec9dd0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4329d9fc61427647"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  15:     0x56554eec9dd0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4329d9fc61427647"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  16:     0x56554e79ea20 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2183bfabf9092325"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  17:     0x56554f79c6a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf5e9bc412078cf28"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  18:     0x56554f79c6a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf5e9bc412078cf28"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  19:     0x56554f79c6a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf5e9bc412078cf28"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  20:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  21:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  22:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  23:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  24:     0x5655503a2430 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6e2629f1d9eca42e"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  25:     0x56554e7ca2a0 - util::thread::spawn_named::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfd27fae8dc13bd14"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  26:     0x5655516eda03 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  27:     0x5655516eecb8 - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196"
 0:07.79 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  28:     0x56554e4877cc - _<servo..compositing..compositor..IOCompositor<Window>>::pipeline::hbb2bd9337bbcc42f"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/servo/<std macros>:8"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  29:     0x56554e52bb4c - _<servo..layers..layers..Layer<servo..compositing..compositor_layer..CompositorData> as servo..compositing..compositor_layer..CompositorLayer>::send_event::hd85ff704da0f63cf"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/compositing/compositor_layer.rs:404"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  30:     0x56554e52c4a7 - _<servo..layers..layers..Layer<servo..compositing..compositor_layer..CompositorData> as servo..compositing..compositor_layer..CompositorLayer>::send_mouse_move_event::h2f8f503e8875b2da"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/compositing/compositor_layer.rs:398"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  31:     0x56554e52d573 - _<servo..compositing..compositor..IOCompositor<Window>>::on_mouse_window_move_event_class::he712fbeba18a1177"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/compositing/compositor.rs:1401"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  32:     0x56554e525e4e - _<servo..compositing..compositor..IOCompositor<Window>>::handle_window_message::h1f7d8b3b995f72c3"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/compositing/compositor.rs:1212"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  33:     0x56554e46d895 - _<servo..compositing..compositor..IOCompositor<Window> as servo..compositing..CompositorEventListener>::handle_events::h2bb00a2c342e0363"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/compositing/compositor.rs:2421"
 0:07.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  34:     0x56554e53d434 - servo::Browser::handle_events::h27e7f0761976cb3a"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/servo/lib.rs:187"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  35:     0x56554e419cf1 - servo::main::h6924e5658370f6b5"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "                        at /home/autrilla/projects/servo/components/servo/main.rs:77"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  36:     0x565551704164 - std::sys_common::unwind::try::try_fn::hfe4b14ce00a3f42f"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  37:     0x5655516feb2b - __rust_try"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  38:     0x565551703bab - std::rt::lang_start::h12d9b3310b48a726"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  39:     0x56554e530bd9 - main"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  40:     0x7f8e6b3fd70f - __libc_start_main"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  41:     0x56554e419598 - _start"
 0:07.91 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:11238) "  42:                0x0 - <unknown>"
```

cc @Ms2ger

**Comment by emilio** [comment]
Yeah, this means an INVALID_OPERATION error ocurred in the back-end.

Servo crashes this way until we implement all the tests necessary to detect errors before reaching the back-end, to prevent difficult-to-debug behavior.

In fact, if you use RUST_LOG=debug, you'll see the exact webgl call that triggered the error. This one is easy to fix I expect, but it's not problematic per se.
