### ISSUE TITLE
Map and zooming tools are not rendered on openstreetmap

### ISSUE THREAD

**Issue by lhirlimann** [servo/servo#10951]
From ssh://github.com/mozilla/servo
   ca29192..77cb2ca  master     -> origin/master
   d9dc6dd..fc1e4c8  auto       -> origin/auto
- fb5fa4d...84a128b try        -> origin/try  (forced update)
  Updating ca29192..77cb2ca

[ludo@Oulanl servo]$ ./mach run --release http://www.openstreetmap.org
ERROR:js::rust: Error at http://www.openstreetmap.org/assets/application-6acb3ade0c3d81c622fed4391615eb0bc8bafc9a3b1d2ed22edbc4ad58f776bf.js:24:25930: i is undefined

ERROR:js::rust: Error at http://piwik.openstreetmap.org/piwik.js:36:946: J.name is undefined

ERROR:js::rust: Error at http://www.openstreetmap.org/assets/index-8145a65c8ea791c70d09224ce507f438960420f2e013c81ee2cd4e555eb89e18.js:6:25477: OSM.router is undefined

![screenshot from 2016-05-01 07-11-53](https://cloud.githubusercontent.com/assets/415751/14940207/44bfcd48-0f6c-11e6-909f-075dc15c6931.png)

**Comment by krk** [comment]
They are still not rendered, there are no errors logged to the terminal, tested with a14b952fa3eedec86e6308213c525538bcb20827

**Comment by lumiscosity** [comment]
Still no errors, still no icons. Tested on Arch Linux x86_64, Servo built against commit 7aad72838a6729beda2c69a02cbf908479f101dd, dev build.

<img width="1146" height="899" alt="Image" src="https://github.com/user-attachments/assets/05bf450c-a702-4228-a4de-a49dbae580d5" />

**Comment by jdm** [comment]
I suspect that this is an artifact of how we implement inline SVG right now. We serialize all the children of the `<svg>` element, but openstreetmap's icons look like this:

<img width="751" height="116" alt="Image" src="https://github.com/user-attachments/assets/72da0927-0542-489b-886b-69fba043fec6" />

Since we don't serialize shadow roots by default, the serialized SVG doesn't contain the actual icon element that the `<use>` references.

**Comment by jdm** [comment]
Mmm, my last analysis was incorrect—it's not that the page source contains shadow DOM elements that Servo is not serializing. Firefox implements the `<use href="...">` behaviour for SVG using the shadow DOM (https://searchfox.org/firefox-main/rev/931471037b8a4f16ce3ccfa864310540cac255c1/dom/svg/SVGUseElement.cpp#410). Servo _would_ run into the shadow DOM serialization problem if we did the same thing, but currently the issue is that the referenced elements exist in a totally separate SVG tree within the same document.


This testcase shows two plus signs in Firefox, but only one in Servo:
```html
<svg>
  <use href="#icon-zoomin"></use>
  <symbol id="icon-zoomin" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor">
    <path d="M16 8H12V4L11 3H10L9 4V8H5L4 9v1l1 1H9v4l1 1h1l1-1V11h4l1-1V9z"></path>
  </symbol>
</svg>

<svg>
  <use href="#icon-zoomin"></use>
</svg>
```

**Comment by jdm** [comment]
I think we should start with the simplest thing here: right before we serialize the SVG tree, we should iterate over the children, find any relevant `<use>` elements, then clone the source nodes and append them to the tree. After serialization, we should remove the cloned nodes from the tree.

In more detail:
1. before calling https://github.com/servo/servo/blob/813280860e5c6caa1af84dd3dc811f5073711c66/components/script/dom/svgsvgelement.rs#L67-L69, [iterate all the children](https://github.com/servo/servo/blob/918d101b02ff23ad5c4c6d7044d19fba132b451e/components/script/dom/node.rs#L872)
2. for each element with a [`local_name()`](https://doc.servo.org/script/dom/element/struct.Element.html#method.local_name) of "use", [check for an `href` attribute](https://doc.servo.org/script/dom/element/struct.Element.html#method.get_string_attribute)
3. ignore any attribute values that have any contents other than a fragment id (that's https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Element/use#loading_resources_from_external_files_via_use but we're not going to try to solve that in this issue)
7. use GetElementById to find a matching element, verify that the element has a `SVGSVGElement` [ancestor](https://github.com/servo/servo/blob/59526928afc81c840f9890eb0a653b16e8128ba6/components/script/dom/node.rs#L1233)
9. [clone](https://github.com/servo/servo/blob/918d101b02ff23ad5c4c6d7044d19fba132b451e/components/script/dom/node.rs#L3721) the referenced element and append the clone to the root SVG element

This implementation doesn't address the case where the referenced node is mutated and the SVG tree needs to be re-serialized as a result. We should file a followup issue for that; it likely requires the use of MutationObserver and supporting native Rust observer callbacks.
