### ISSUE TITLE
Intermittent timeout in /html/dom/reflection-embedded.html

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11100]
```
▶ TIMEOUT [expected OK] /html/dom/reflection-embedded.html
  │ 
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, ../src/libstd/rand/mod.rs:159
  │ stack backtrace:
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, ../src/libstd/rand/mod.rs:159
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x1073866e9 - std::rand::thread_rng::THREAD_RNG_KEY::__init::h536e3917997a1628
  │    8:        0x10736d98c - std::rand::thread_rng::h789d00d1fce4f79b
  │    9:        0x105d81121 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   10:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   11:        0x10737ef0b - __rust_try
  │   12:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   13:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   14:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   15:     0x7fff8bd4d059 - _pthread_body
  │   16:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x1073866e9 - std::rand::thread_rng::THREAD_RNG_KEY::__init::h536e3917997a1628
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │    8:        0x10736d98c - std::rand::thread_rng::h789d00d1fce4f79b
  │    9:        0x105d81121 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   10:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   11:        0x10737ef0b - __rust_try
  │   12:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │   13:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   14:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   15:     0x7fff8bd4d059 - _pthread_body
  │   16:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/rand-0.3.14/src/lib.rs:873
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, ../src/libstd/rand/mod.rs:159
  │    1:        0x10737f</span><span class="stdout">ca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │ thread &#39;http_loader for http://web-platform.test:8000/html/dom/test-valueOf&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, ../src/libstd/rand/mod.rs:159
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x10718656f - rand::thread_rng::THREAD_RNG_KEY::__init::h95086aa3feb19f11
  │    8:        0x1071863ac - rand::thread_rng::h685796b33c6d5157
  │    9:        0x106b67842 - uuid::Uuid::new_v4::hf5742953332a48bd
  │   10:        0x105d81bb9 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   11:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   12:        0x10737ef0b - __rust_try
  │   13:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   14:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   15:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   16:     0x7fff8bd4d059 - _pthread_body
  │   17:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x1073866e9 - std::rand::thread_rng::THREAD_RNG_KEY::__init::h536e3917997a1628
  │    8:        0x10736d98c - std::rand::thread_rng::h789d00d1fce4f79b
  │    9:        0x105d81121 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   10:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   11:        0x10737ef0b - __rust_try
  │   12:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd</span><span class="stdout">
  │   13:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   14:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   15:     0x7fff8bd4d059 - _pthread_body
  │   16:     0x7fff8bd4cfd6 - _pthread_start
  │ stack backtrace:
  │    1:        0x10737fca8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x1073860c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x107385cde - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x106b2e892 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x10736d388 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x10736ecbe - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x1073866e9 - std::rand::thread_rng::THREAD_RNG_KEY::__init::h536e3917997a1628
  │    8:        0x10736d98c - std::rand::thread_rng::h789d00d1fce4f79b
  │    9:        0x105d81121 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   10:        0x105d7e79d - std::sys_common::unwind::try::try_fn::h94855ca93006dd22
  │   11:        0x10737ef0b - __rust_try
  │   12:        0x10737ee93 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   13:        0x105d7f87d - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hca0e8efc2dc5954d
  │   14:        0x107385148 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   15:     0x7fff8bd4d059 - _pthread_body
  └   16:     0x7fff8bd4cfd6 - _pthread_start
```

**Comment by Ms2ger** [comment]
I suspect this has something to do with the increased parallelism for wpt runs. @metajack ?

**Comment by metajack** [comment]
I checked all the linked PRs. This intermittent appears isolated to mac-rel-wpt.

**Comment by metajack** [comment]
I don't see anything in relection-embedded.html that would create files. Am I missing something? I can understand why we'd run out of file descriptors, but why always on this specific test?

**Comment by Ms2ger** [comment]
That's the one that handles `iframe` and `img`.

**Comment by metajack** [comment]
All instances seem to be on servo-mac3 or servo-macpro1.

**Comment by metajack** [comment]
On linux we seem to be happy with the default number of file descriptors (1024). We also run many more simultaneous tests on linux since there are more processors.

On the mac, we attempt to set the limit to 30k via sysctl, but according to http://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard this is no longer enough. `launchctl limit` shows us limited to 256.

I have manually run `launchctl limit maxfiles 1024 unlimited` on servo-mac1, servo-mac2, servo-mac3, and servo-macpro1, to see if this problem is alleviated.

Is there any reason why OS X runs would want more file descriptors than linux runs?

**Comment by larsbergstrom** [comment]
Aha, I recently had to pave mac3 and macpro1 and I must have done something similarly manual that we haven't properly automated in salt yet that I didn't do when restoring them. Thanks!

I thought that our linux machines were defaulting to unlimited the last time I checked.

**Comment by metajack** [comment]
`ulimit -a` and `launchctl limit` showed 10240 and 256 respectively. I guess `ulimit` just lies on OS X now.

**Comment by metajack** [comment]
Note that this was consistent across servo-mac1, servo-mac2, servo-mac3, and servo-macpro1. I didn't find any configuration differences, but it is possible I missed something.

**Comment by larsbergstrom** [comment]
This is what I used to do, pre-salt:
```
echo 'kern.maxfiles=60000\nkern.maxfilesperproc=20000\nkern.ipc.somaxconn=2048' | sudo tee -a /etc/sysctl.conf
echo -e 'limit maxfiles 8192 20480\nlimit maxproc 1000 2000' | sudo tee -a /etc/launchd.conf
echo 'ulimit -n 10240' | sudo tee -a /etc/profile
```

**Comment by metajack** [comment]
launchd.conf only exists on servo-mac2. All of them seem to have the /etc/profile change, and they also all had the sysctl.conf change (salt manages that one currently).

**Comment by metajack** [comment]
I wonder if we used to run mac-rel-wpt on servo-mac2 before? That would explain why this popped up.

**Comment by larsbergstrom** [comment]
@metajack Almost all our macs except for -mac2 have been paved in the last few weeks. I would not call OSX a stable OS for long-running automated systems :-)

**Comment by metajack** [comment]
I'm unsure whether my changes were in effect for #11173, but it seems to have failed :(

**Comment by metajack** [comment]
I spent some time investigating this to see whether it was opening excessive numbers of files. Here's a dtrace script I used:

```
#!/usr/sbin/dtrace -s

#pragma D option quiet

syscall::open*:entry,
syscall::socket*:entry,
syscall::accept*:entry,
syscall::socketpair*:entry,
syscall::pipe*:entry
/execname == "servo"/
{
  @calls[execname,probefunc] = count();
  printf("%s %s %s\n", execname, probefunc, copyinstr(arg0));
ustack();
}

syscall::open*:return,
syscall::socket*:return,
syscall::pipe*:return
/execname == "servo" && arg0 == -1/
{
  @errors[execname, probefunc] = count();
}
     
syscall::close:entry
/execname == "servo"/
{
  @calls[execname,probefunc] = count();
  printf("%s %s\n", execname, probefunc);
}
```

This seems to show it does open a lot more files than say `/html/dom/elements/elements-in-the-dom/unknown-element.html` but it seems to be all the threads initializing their RNG from `/dev/urandom`. I didn't measure concurrent fd counts, and I may have missed some syscalls that create fds.

**Comment by aneeshusa** [comment]
The FD limits were Salted in https://github.com/servo/saltfs/pull/227, so the configuration should be consistent everywhere. Note that OS X doesn't use `/etc/launchd.conf` anymore: http://stackoverflow.com/a/26311753.

**Comment by metajack** [comment]
@pcwalton This the too many fds intermittent we discussed.

**Comment by KiChjang** [comment]
Disabled in #11414.

**Comment by nox** [comment]
@metajack Apparently we use the request ID only to pass it to devtools... Do we really need it be an UUIDv4?

**Comment by nox** [comment]
We could also use the impl `Rand` for `Uuid` and somehow share the source of randomness across all HTTP loaders.

**Comment by jdm** [comment]
It isn't required to be a UUIDv4, it just needs to be a globally unique value.

**Comment by metajack** [comment]
I don't understand how changing this helps? Won't we still initialize the thread rng regardless? Or does this only happen on threads which eventually call rand()?

Even if every thread we have opens /dev/random, why would we have so many open at once? Surely there are 256+ threads in Servo?

**Comment by nox** [comment]
@metajack Well apart from `Uuid::new_v4`, is there anything in `http_loader::load` that should initialise the RNG?

**Comment by nox** [comment]
@metajack I'm not sure it helps btw, but it should reduce the pressure until we find the actual problem (probably we load too many things concurrently?).

**Comment by nox** [comment]
@metajack So AFAIK these UUID are the only thing that initialises the thread-local RNG state. We could probably fix this more generally by putting HTTP load requests behind a thread pool though.

**Comment by KiChjang** [comment]
Consider disabling this since it's been hitting #14227 3 times in a row.

**Comment by Ms2ger** [comment]
Disabling in #14293.
