### ISSUE TITLE
Intermittent timeout in /cors/redirect-origin.htm

### ISSUE THREAD

**Issue by nox** [servo/servo#11276]
```
  ▶ TIMEOUT [expected OK] /cors/redirect-origin.htm
  │ 
  │ thread &#39;http_loader for http://www1.web-platform.test:8000/cors/resources/cors-makeheader.py?origin=*&amp;location=http%3A%2F%2Fwww1.web-platform.test%3A8000%2Fcors%2Fresources%2Fcors-makeheader.py%3Forigin%3Dhttp%3A%2F%2Fwww1.web-platform.test%3A8000%26get_value%3Dlast%2640_1&amp;40_0&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, ../src/libstd/rand/mod.rs:159
  │ stack backtrace:
  │    1:        0x104e4dea8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x104e54335 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x104e53f4e - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x1045e2ff2 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::ha2bd86c312dc8d7a
  │    5:        0x104e3bb02 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
  │    6:        0x104e548f6 - std::panicking::begin_panic::h4889569716505182
  │    7:        0x104e3d3f8 - std::panicking::begin_panic_fmt::h484cd47786497f03
  │    8:        0x104e54d69 - std::rand::thread_rng::THREAD_RNG_KEY::__init::h536e3917997a1628
  │    9:        0x104e3c10c - std::rand::thread_rng::h789d00d1fce4f79b
  │   10:        0x1035d03ac - _&lt;collections..hash..map..RandomState as core..default..Default&gt;::default::ha847494db5044892
  │   11:        0x10360e304 - net::http_loader::load::h4cdeddfa5dca9e93
  │   12:        0x10360a83c - std::panicking::try::call::h7738ffab0c454f42
  │   13:        0x104e57abb - __rust_try
  │   14:        0x104e57a55 - __rust_maybe_catch_panic
  │   15:        0x10360c844 - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hfad4324b0bbd8499
  │   16:        0x104e53358 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   17:     0x7fff8c3c2059 - _pthread_body
  │   18:     0x7fff8c3c1fd6 - _pthread_start
  │ thread &#39;http_loader for http://www1.web-platform.test:8000/cors/resources/cors-makeheader.py?origin=*&amp;location=http%3A%2F%2Fwww2.web-platform.test%3A8000%2Fcors%2Fresources%2Fcors-makeheader.py%3Forigin%3Dhttp%3A%2F%2Fwww1.web-platform.test%3A8000%26get_value%3Dlast%2641_1&amp;41_0&#39; panicked at &#39;could not initialize thread_rng: Too many open files (os error 24)&#39;, ../src/libstd/rand/mod.rs:159
  │ stack backtrace:
  │    1:        0x104e4dea8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x104e54335 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x104e53f4e - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x1045e2ff2 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::ha2bd86c312dc8d7a
  │    5:        0x104e3bb02 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
  │    6:        0x104e548f6 - std::panicking::begin_panic::h4889569716505182
  │    7:        0x104e3d3f8 - std::panicking::begin_panic_fmt::h484cd47786497f03
  │    8:        0x104e54d69 - std::rand::thread_rng::THREAD_RNG_KEY::__init::h536e3917997a1628
  │    9:        0x104e3c10c - std::rand::thread_rng::h789d00d1fce4f79b
  │   10:        0x1035d03ac - _&lt;collections..hash..map..RandomState as core..default..Default&gt;::default::ha847494db5044892
  │   11:        0x10360e304 - net::http_loader::load::h4cdeddfa5dca9e93
  │   12:        0x10360a83c - std::panicking::try::call::h7738ffab0c454f42
  │   13:        0x104e57abb - __rust_try
  │   14:        0x104e57a55 - __rust_maybe_catch_panic
  │   15:        0x10360c844 - _&lt;F as std..boxed..FnBox&lt;A&gt;&gt;::call_box::hfad4324b0bbd8499
  │   16:        0x104e53358 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   17:     0x7fff8c3c2059 - _pthread_body
  └   18:     0x7fff8c3c1fd6 - _pthread_start

  ▶ Unexpected subtest result in /cors/redirect-origin.htm:
  │ TIMEOUT [expected PASS] remote (*) to remote (http://www1.web-platform.test:8000), expect to fail
  └   → Test timed out

  ▶ Unexpected subtest result in /cors/redirect-origin.htm:
  │ TIMEOUT [expected PASS] remote (*) to remote2 (http://www1.web-platform.test:8000), expect to fail
  └   → Test timed out
```

**Comment by jdm** [comment]
Same cause as #11100.
