### ISSUE TITLE
"Float position error" panic in LayoutWorker on window resize

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#11424]
With `./mach run -r http://en.wikipedia.org/wiki/Paris`, I got this in the terminal while playing with resizing the window:

```
thread 'LayoutWorker worker 2/3' panicked at 'Float position error', /home/simon/projects/servo2/components/layout/floats.rs:246
stack backtrace:
   1:     0x564affa1f900 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x564affa2747b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x564affa270e3 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x564aff6aac97 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0af6702035551a7d
   5:     0x564affa0cf2c - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
   6:     0x564afdf503ff - std::panicking::begin_panic::h4ebf9fe884b2415f
   7:     0x564afdfa108e - layout::floats::Floats::available_rect::hbe96c25b58a83c25
   8:     0x564afdf68671 - layout::floats::Floats::place_between_floats::h0a8f7e9aa85c4ab3
   9:     0x564afdfb0166 - layout::inline::LineBreaker::initial_line_placement::h3cfefcf4dcc07905
  10:     0x564afdfb24c6 - _<inline..InlineFlow as flow..Flow>::assign_block_size::hb401c2f44b6ec74f
  11:     0x564afdfb5ccb - layout::flow::Flow::assign_block_size_for_inorder_child_if_necessary::h944d4b2817118e58
  12:     0x564afdf64111 - _<block..BlockFlow as flow..Flow>::fragment::h1f49da6be9f5cd6e
  13:     0x564afdf65b6e - _<block..BlockFlow as flow..Flow>::assign_block_size_for_inorder_child_if_necessary::hff6f76c7b70f357e
  14:     0x564afdf64111 - _<block..BlockFlow as flow..Flow>::fragment::h1f49da6be9f5cd6e
  15:     0x564afdf65b6e - _<block..BlockFlow as flow..Flow>::assign_block_size_for_inorder_child_if_necessary::hff6f76c7b70f357e
  16:     0x564afdf64111 - _<block..BlockFlow as flow..Flow>::fragment::h1f49da6be9f5cd6e
  17:     0x564afdf65b6e - _<block..BlockFlow as flow..Flow>::assign_block_size_for_inorder_child_if_necessary::hff6f76c7b70f357e
  18:     0x564afdf64111 - _<block..BlockFlow as flow..Flow>::fragment::h1f49da6be9f5cd6e
  19:     0x564afdf65b6e - _<block..BlockFlow as flow..Flow>::assign_block_size_for_inorder_child_if_necessary::hff6f76c7b70f357e
  20:     0x564afdf64111 - _<block..BlockFlow as flow..Flow>::fragment::h1f49da6be9f5cd6e
  21:     0x564afdf65b6e - _<block..BlockFlow as flow..Flow>::assign_block_size_for_inorder_child_if_necessary::hff6f76c7b70f357e
  22:     0x564afdf632ef - _<block..BlockFlow as flow..Flow>::fragment::h1f49da6be9f5cd6e
  23:     0x564afdf62524 - _<block..BlockFlow as flow..Flow>::assign_block_size::hd3fa823d72a8a21f
  24:     0x564afe0936e3 - _<traversal..AssignISizes<'a> as parallel..ParallelPreorderFlowTraversal>::run_parallel::hc80de1a6500200bf
  25:     0x564afe093e9f - layout::parallel::assign_inline_sizes::h55b5a3eea5c31552
  26:     0x564afdfdb936 - std::panicking::try::call::hf2fae8d8c8553613
  27:     0x564affa31d6b - __rust_try
  28:     0x564affa31d0e - __rust_maybe_catch_panic
  29:     0x564afdfdd1c7 - _<F as std..boxed..FnBox<A>>::call_box::h88fc8e1d09714dbb
  30:     0x564affa25864 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  31:     0x7f650f5c9473 - start_thread
  32:     0x7f650f0f269c - clone
  33:                0x0 - <unknown>
```

After that I could scroll, but resizing the window further didn’t seem to affect layout.

I saw this once and didn’t manage to reproduce it again.

This is Servo e18bf819059e4439d276b02083a60f6353aaa359 (master on 2016-05-24), on Linux x64. I think without WebRender since it’s not the default yet. (https://github.com/servo/servo/pull/11136 hasn’t landed.)

**Comment by Ms2ger** [comment]
I get the same on initial load of https://en.wikipedia.org/wiki/Red_rail (1da1b62128251c23bafd3eb8682986c9c0f3e796).

**Comment by Ms2ger** [comment]
```html
<!DOCTYPE html>
<style>
div.tright {
    clear: right;
    float: right;
    margin: .5em 0 1.3em 1.4em
}
div.tleft {
    float: left;
    clear: left;
    margin: .5em 1.4em 1.3em 0;
}
div.thumbinner {
    border: 1px solid #ccc;
    padding: 3px;
}
</style>
<div style="margin-left: 11.5em; padding: 1.14em; line-height: 1.6; font-size: 0.875em;">
  <div class="tright">
    <div class="thumbinner" style="width:172px;">
      <img width="170" height="234" class="thumbimage">
      <div class="thumbcaption">
        1869 adaptation of the Hoefnagel painting
      </div>
    </div>
  </div>
  <p>Though Mauritius had previously been visited by Arab vessels in the
  Middle Ages and Portuguese ships between 1507 and 1513, they did not
  settle on the island.[23] The Dutch Empire acquired the island in 1598,
  renaming it after Maurice of Nassau, and it was used from then on for
  the provisioning of trade vessels of the Dutch East India Company.[24]
  To the sailors who visited Mauritius from 1598 and onwards, the fauna
  was mainly interesting from a culinary standpoint. The dodo was
  sometimes considered rather unpalatable, but the red rail was a very
  popular gamebird for the Dutch and French settlers. The reports dwell
  upon the varying ease with which the bird could be caught according to
  the hunting method and the fact that when roasted it was considered
  similar to pork.[12]</p>
  <div class="tleft">
    <div class="thumbinner" style="width:222px;">
      <img class="thumbimage">
      <div class="thumbcaption">
        1617 drawing of a dodo, a one-horned sheep, and a red rail
      </div>
    </div>
  </div>
  <p>Johann Christian Hoffmann, who was on Mauritius in the early 1670s, described a red rail hunt as follows:</p>
</div>
```

triggers it consistently for me

**Comment by Meyermagic** [comment]
I'm also getting this issue:
URL: https://en.wikipedia.org/wiki/Nuclear_weapon
Version: Servo 0.0.1-4b78b9a (downloaded compiled binary from servo site)
Log:
$ RUST_BACKTRACE=1 ./runservo.sh 
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
Exception in module-execute in module mediawiki.action.view.redirect:
ReferenceError: history is not defined
ReferenceError: history is not defined
thread 'LayoutWorker worker 9/9' panicked at 'Float position error', /home/servo/buildbot/slave/linux-nightly/build/components/layout/floats.rs:246
stack backtrace:
   1:     0x7f5525c3700f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f5525c3ec3b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f5525c3e89f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f55257f2167 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x7f5525c2508c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x7f552533fcaf - std::panicking::begin_panic::h0bf39f6d43ab9349
   7:     0x7f552539557e - layout::floats::Floats::available_rect::h8aef2dcf90b37b8d
   8:     0x7f552535cb31 - layout::floats::Floats::place_between_floats::h3afcf8b33c7bb461
   9:     0x7f55253a4856 - layout::inline::LineBreaker::initial_line_placement::hc78ee6c1307777d8
  10:     0x7f55253a6ce6 - _<layout..inline..InlineFlow as layout..flow..Flow>::assign_block_size::he6279cf7b38826dd
  11:     0x7f552445d6fb - layout::flow::Flow::assign_block_size_for_inorder_child_if_necessary::h760563137bb5f55e
  12:     0x7f552535836f - _<layout..block..BlockFlow as layout..flow..Flow>::fragment::haf3e2f8b9186d523
  13:     0x7f5525359dbe - _<layout..block..BlockFlow as layout..flow..Flow>::assign_block_size_for_inorder_child_if_necessary::haf4b6d56b80002c6
  14:     0x7f552535836f - _<layout..block..BlockFlow as layout..flow..Flow>::fragment::haf3e2f8b9186d523
  15:     0x7f5525359dbe - _<layout..block..BlockFlow as layout..flow..Flow>::assign_block_size_for_inorder_child_if_necessary::haf4b6d56b80002c6
  16:     0x7f552535836f - _<layout..block..BlockFlow as layout..flow..Flow>::fragment::haf3e2f8b9186d523
  17:     0x7f5525359dbe - _<layout..block..BlockFlow as layout..flow..Flow>::assign_block_size_for_inorder_child_if_necessary::haf4b6d56b80002c6
  18:     0x7f552535836f - _<layout..block..BlockFlow as layout..flow..Flow>::fragment::haf3e2f8b9186d523
  19:     0x7f5525359dbe - _<layout..block..BlockFlow as layout..flow..Flow>::assign_block_size_for_inorder_child_if_necessary::haf4b6d56b80002c6
  20:     0x7f552535836f - _<layout..block..BlockFlow as layout..flow..Flow>::fragment::haf3e2f8b9186d523
  21:     0x7f5525359dbe - _<layout..block..BlockFlow as layout..flow..Flow>::assign_block_size_for_inorder_child_if_necessary::haf4b6d56b80002c6
  22:     0x7f5525357560 - _<layout..block..BlockFlow as layout..flow..Flow>::fragment::haf3e2f8b9186d523
  23:     0x7f5525356794 - _<layout..block..BlockFlow as layout..flow..Flow>::assign_block_size::heccee273b0b2a60e
  24:     0x7f55253adb23 - _<layout..traversal..AssignISizes<'a> as layout..parallel..ParallelPreorderFlowTraversal>::run_parallel::h33ac94b440f423e6
  25:     0x7f55253ae588 - layout::parallel::assign_inline_sizes::h5ab39faed390e99d
  26:     0x7f5524386ba6 - std::panicking::try::call::h5ceeb75d0e3d7f90
  27:     0x7f5525c4907b - __rust_try
  28:     0x7f5525c4901e - __rust_maybe_catch_panic
  29:     0x7f5524388437 - _<F as alloc..boxed..FnBox<A>>::call_box::h70e854acba4de844
  30:     0x7f5525c3d044 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  31:     0x7f5521785183 - start_thread
  32:     0x7f552129c37c - clone
  33:                0x0 - <unknown>

**Comment by JanZerebecki** [comment]
I translated the above test case into code (see the above commit). When translate() is called between adding floats their state may get inconsistent with each other as the offset/ceiling is not updated. I don't know enough of the servo design yet. Is it better to solve this by keeping enough state (it is currently not keep in add_float()) in the Floats struct to recompute the placement of all floats or by recreating at least the whole Floats instance?

**Comment by jdm** [comment]
Paging @notriddle for layout question.

**Comment by nox** [comment]
Servo now hangs indefinitely when I try to open the reduced test case.

**Comment by simonwuelker** [comment]
This issue only affects layout-2013, which has since been removed. The testcase does not panic in layout-2020.
