### ISSUE TITLE
Building Servo fails on OS X El capitan

### ISSUE THREAD

**Issue by kumikumi** [servo/servo#11887]
I'm having trouble building Servo on my installation of OS X 10.11 El Capitan.

I have installed the prerequisites listed on [this page](https://github.com/servo/servo#prerequisites), namely ran the commands

```
brew install automake pkg-config python cmake
pip install virtualenv
```
and
```
brew install openssl
brew link --force openssl
```

I have cloned the repository with git and tried to do a build with `./mach build --release`

Here's the output of the build command:
[servo-build-output.txt](https://github.com/servo/servo/files/336018/servo-build-output.txt)

I'm not sure if this problem affects other people. I'll provide more information regarding my setup as requested.

**Comment by larsbergstrom** [comment]
Very interesting! Looks like `locale.Error: unsupported locale setting`, which makes it sound like either we have hardcoded `en_US` somewhere and it is not available on your system or we're picking up the default locale from your operating system but it's not available in python.

@jdm @ms2ger have you ever seen this in the SM build?


```
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#2af5849a)`
Process didn't exit successfully: `/Users/mikko/Documents/programming/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/build-script-build` (exit code: 101)
--- stdout
touch /Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure
cd /Users/mikko/Documents/programming/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out && \
    MOZ_TOOLS="" CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
    /Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-shared-js --without-intl-api || (cat config.log && exit 1)
Using real prefix '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7'
New python executable in /Users/mikko/Documents/programming/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out/_virtualenv/bin/python2.7
Also creating executable in /Users/mikko/Documents/programming/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out/_virtualenv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/mikko/Documen...ualenv/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/virtualenv/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/Users/mikko/Documents/programming/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out/_virtualenv/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/virtualenv/virtualenv.py", line 2316, in <module>
    main()
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/virtualenv/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/virtualenv/virtualenv.py", line 941, in create_environment
    download=download,
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/virtualenv/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/virtualenv/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/mikko/Documen...ualenv/bin/python2.7 - setuptools pip wheel failed with error code 1

--- stderr
makefile.cargo:65: Extraneous text after `else' directive
Creating Python environment
Traceback (most recent call last):
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/../../configure.py", line 94, in <module>
    sys.exit(main(sys.argv))
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/../../configure.py", line 22, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 164, in run
    self.exec_file(path)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 157, in exec_file
    exec(code, self)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/moz.configure", line 7, in <module>
    include('build/moz.configure/init.configure')
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 344, in include_impl
    self.exec_file(what)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 157, in exec_file
    exec(code, self)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/build/moz.configure/init.configure", line 165, in <module>
    @advanced
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 327, in decorator
    self._results[func] = func(*resolved_args)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/build/moz.configure/init.configure", line 215, in virtualenv_python
    manager.build(python)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 424, in build
    self.create(python)
  File "/Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 188, in create
    'Failed to create virtualenv: %s' % self.virtualenv_root)
Exception: Failed to create virtualenv: /Users/mikko/Documents/programming/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out/_virtualenv
cat: config.log: No such file or directory
make: *** [all] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /Users/mikko/Documents/programming/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/build.rs:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'pyobjc' is not installed.
Build completed in 0:11:12
```

**Comment by kumikumi** [comment]
I can confirm that the issue is locale related. Someone on IRC figured out a workaround: running `export LC_ALL=C` before build fixes the issues and makes the build succeed.

If someone is still interested in fixing this issue, I'll be glad to assist by providing information and trying things out.

**Comment by jdm** [comment]
My googling suggested that this was a thing that virtual enc was complaining about, rather than something that we have done in particular.
