### ISSUE TITLE
Thread panic while loading github

### ISSUE THREAD

**Issue by severin-lemaignan** [servo/servo#12037]
Tested on Ubuntu 16.04 (64bits)

```
$ ./servo --version
Servo 0.0.1-4f81384
```

Console output:
```
$ ./runservo.sh 
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
61 FPS
60 FPS
60 FPS
61 FPS
61 FPS
60 FPS
61 FPS
58 FPS
60 FPS
61 FPS
ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-6fe6a7604ec4c2601272849e1b99a3a9aa12c79b3e25be0360f8d114768e7578.js:6:6359: history is not defined

thread 'FontCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:785
```

**Comment by jdm** [comment]
From components/gfx/platform/freetype/font_template.rs:
```
                // TODO: Handle file load failure!
                let mut file = File::open(&*identifier).unwrap();
```

**Comment by jdm** [comment]
Looks like the FontTemplateData::new API should return a Result value.
