### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by AoD314** [servo/servo#12139]
``` bash
$ RUST_BACKTRACE=1 ./runservo.sh
./servo: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib64/libssl.so.1.0.0: no version information available (required by ./servo)
error: XDG_RUNTIME_DIR not set in the environment.
thread 'FontCacheThread' panicked at 'Unable to find any fonts that match (do you have fallback fonts installed?)', /home/servo/buildbot/slave/linux-nightly/build/components/gfx/font_cache_thread.rs:376
stack backtrace:
   1:     0x557db37f956f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x557db380119b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x557db3800dff - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x557db36df857 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x557db37e6dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x557db30df89f - std::panicking::begin_panic::h0bf39f6d43ab9349
   7:     0x557db30f8f3f - gfx::font_cache_thread::FontCache::run::hdaaa2c889b9695d1
   8:     0x557db3119cdc - std::panicking::try::call::h4ca3851bd12ff60d
   9:     0x557db380b5db - __rust_try
  10:     0x557db380b57e - __rust_maybe_catch_panic
  11:     0x557db311a7d0 - _<F as alloc..boxed..FnBox<A>>::call_box::h5a5134f7400689cd
  12:     0x557db37ff5a4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  13:     0x7f1c75d14433 - start_thread
  14:     0x7f1c75842efc - __clone
  15:                0x0 - <unknown>
thread 'LayoutWorker worker 2/9' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x557db37f956f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x557db380119b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x557db3800dff - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x557db36df857 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x557db37e6dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x557db38013e1 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x557db37e863a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x557db380137e - rust_begin_unwind
   9:     0x557db383797f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x557db30f9693 - core::result::unwrap_failed::hdbe36c893c34e283
  11:     0x557db311e34f - gfx::font_cache_thread::FontCacheThread::last_resort_font_template::h416490de476aad60
  12:     0x557db3120813 - gfx::font_context::FontContext::layout_font_group_for_style::h94a71a4e0cb1b1fe
  13:     0x557db30ae6a2 - layout::text::font_metrics_for_style::h4deb9971b0c312ad
  14:     0x557db30b5cb9 - layout::inline::InlineFlow::compute_minimum_ascent_and_descent::h0f7246e4490372a3
  15:     0x557db1f522ab - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_flow_for_block_starting_with_fragments::h94cf936e5ea23833
  16:     0x557db1f4ff13 - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_flow_for_block_like::hb1a9aa6413141174
  17:     0x557db1f5c1d2 - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_flow_for_block::hc4ffcc494791b275
  18:     0x557db1f49fb1 - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode> as layout..traversal..PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>>::process::hdc60d17cc668729c
  19:     0x557db1f43fb3 - _<layout..traversal..RecalcStyleAndConstructFlows<'lc> as style..traversal..DomTraversalContext<N>>::process_postorder::h3a9ef481b87d85ee
  20:     0x557db1f6d5e7 - style::parallel::top_down_dom::h64b271679154ad97
  21:     0x557db1e82916 - std::panicking::try::call::he98ee6aa5e6d694a
  22:     0x557db380b5db - __rust_try
  23:     0x557db380b57e - __rust_maybe_catch_panic
  24:     0x557db1e841a7 - _<F as alloc..boxed..FnBox<A>>::call_box::hfb90f724b3d98084
  25:     0x557db37ff5a4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  26:     0x7f1c75d14433 - start_thread
  27:     0x7f1c75842efc - __clone
  28:                0x0 - <unknown>

$ ./servo --version
./servo: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib64/libssl.so.1.0.0: no version information available (required by ./servo)
Servo 0.0.1-4f81384
```

**Comment by aneeshusa** [comment]
I think this may be caused by `XDG_RUNTIME_DIR` being unset in your environment variables. Can you try setting it to something? I believe we don't use this variable so it shouldn't matter what you set it to, but a safe choice is probably a subdirectory in `/tmp`.

**Comment by jdm** [comment]
It looks to me like the missing fonts are a bigger problem.

**Comment by Obikawa** [comment]
Why is this a problem? I have full sets of Droid and Noto fonts, which should cover me for pretty much anything. Does servo expect some specific fonts to be installed?

**Comment by Obikawa** [comment]
./mach -v run -d --browserhtml -Z full-backtraces &> crash.log

https://gist.github.com/Obikawa/6d03efc3f687efdd6d9a35b4dcf9ced2

**Comment by jdm** [comment]
Looks like any of the fonts at https://dxr.mozilla.org/servo/source/components/gfx/platform/freetype/font_list.rs#141 should satisfy.

**Comment by nox** [comment]
Closing for inactivity.
