### ISSUE TITLE
GL context creation failed, LibreSSL errors

### ISSUE THREAD

**Issue by ar25812** [servo/servo#12134]
Servo does not start
libcrypto and libssl were symlinked. 
ldd -v servo reports no errors besides OpenSSL not found
System: x86_64, Void Linux, Kernel 4.6.2_3 SMP PREEMPT

```
> [user@void servo]$ RUST_BACKTRACE=1 ./runservo.sh 
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
thread 'main' panicked at 'Failed to create window.: OsError("GL context creation failed")', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55c00712256f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55c00712a19b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55c007129dff - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55c007008857 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x55c00710fdcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x55c00712a3e1 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x55c00711163a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x55c00712a37e - rust_begin_unwind
   9:     0x55c00716097f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x55c0052fdff0 - core::result::unwrap_failed::hd132ba2b7d75f379
  11:     0x55c0052fcdf4 - glutin_app::window::Window::new::h750be0f1f60f008a
  12:     0x55c0052fbdf0 - glutin_app::create_window::hae774cdda1762e66
  13:     0x55c0052a4f45 - servo::main::h6924e5658370f6b5
  14:     0x55c007129778 - std::panicking::try::call::h852b0d5f2eec25e4
  15:     0x55c0071345db - __rust_try
  16:     0x55c00713457e - __rust_maybe_catch_panic
  17:     0x55c00712921e - std::rt::lang_start::hfe4efe1fc39e4a30
  18:     0x7fbe1323e78f - __libc_start_main
                        at ../csu/libc-start.c:289
  19:     0x55c0052a3f09 - <unknown>
  20:                0x0 - <unknown>
```

**Comment by pintergreg** [comment]
Same here, with Arch Linux 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux
```
$ RUST_BACKTRACE=1 ./runservo.sh 
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
thread 'main' panicked at 'Failed to create window.: OsError("GL context creation failed")', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55b2638bbfaf - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55b2638c3bdb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55b2638c383f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55b2637a2257 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x55b2638a980c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x55b2638c3e21 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x55b2638ab07a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x55b2638c3dbe - rust_begin_unwind
   9:     0x55b2638fa3bf - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x55b261a95e10 - core::result::unwrap_failed::hd132ba2b7d75f379
  11:     0x55b261a94c14 - glutin_app::window::Window::new::h750be0f1f60f008a
  12:     0x55b261a93c10 - glutin_app::create_window::hae774cdda1762e66
  13:     0x55b261a3cf25 - servo::main::h6924e5658370f6b5
  14:     0x55b2638c31b8 - std::panicking::try::call::h852b0d5f2eec25e4
  15:     0x55b2638ce01b - __rust_try
  16:     0x55b2638cdfbe - __rust_maybe_catch_panic
  17:     0x55b2638c2c5e - std::rt::lang_start::hfe4efe1fc39e4a30
  18:     0x7feaadd8a740 - __libc_start_main
  19:     0x55b261a3bee9 - <unknown>
  20:                0x0 - <unknown>
```

**Comment by NgoHuy** [comment]
Hi guys,
You must remove `-w` option in `runservo.sh` to run in archlinux

**Comment by jdm** [comment]
The GL context creation failure is tracked in #12053. Thanks for reporting it!
