### ISSUE TITLE
Servo does not quit on super+q

### ISSUE THREAD

**Issue by nagisa** [servo/servo#12147]
where super+q is my WM shortcut which kills windows.

Servo instead starts consuming 100% of cpu.

Servo stdout:

```
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
ERROR:js::rust: Error at file:///tmp/servo/build/browserhtml-3e3805f69808f24d/out/components/main.js:7:13639: e.matches[e.items[e.selected]] is undefined

ERROR:js::rust: Error at file:///tmp/servo/build/browserhtml-3e3805f69808f24d/out/components/main.js:7:13639: e.matches[e.items[e.selected]] is undefined

Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
```

[Thread backtraces](https://gist.github.com/nagisa/9ea6b23628bf78b8a4d267452f4f5b70)

Steps to reproduce:
- sh runservo.sh;
- Open 2 tabs;
- alt+f4/cmd+q/super+q/whatever other combo kills windows;
- Enjoy the portable heater.

**Comment by jwilm** [comment]
Was this on X11?

**Comment by nagisa** [comment]
Yes.

**Comment by jwilm** [comment]
Might be related to https://github.com/tomaka/glutin/pull/818 in which case upgrading Glutin would fix it. Patch hasn't landed yet.
