### ISSUE TITLE
crashes on i3 when starting and not having focus

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#12273]
When I quickly launch servo and make sure it is on a different workspace (using i3) than what I currently look at, it will crash on startup:

```
./mach run -d --browserhtml 
/home/matthias/vcs/github/servo/target/debug/build
thread 'main' panicked at 'Failed to set the icon: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 42, minor_code: 0 }', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55ceea80bfcf - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55ceea813bfb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55ceea81385f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55ceea1a010a - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hd08da729b0ab92ba
                        at /home/matthias/vcs/github/servo/components/util/panicking.rs:45
   5:     0x55ceea19ffc9 - _<std..thread..local..LocalKey<T>>::with::h190356b87bf1968b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:211
   6:     0x55ceea19fe46 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf955a34756acac10
                        at /home/matthias/vcs/github/servo/components/util/panicking.rs:40
   7:     0x55ceea7f973c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   8:     0x55ceea813e41 - std::panicking::begin_panic::he426e15a3766089a
   9:     0x55ceea7fafaa - std::panicking::begin_panic_fmt::hdddb415186c241e7
  10:     0x55ceea813dde - rust_begin_unwind
  11:     0x55ceea84a3df - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  12:     0x55cee66921f1 - core::result::unwrap_failed::hb87c432c52c2156e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  13:     0x55cee6691fea - _<core..result..Result<T, E>>::expect::h2fb4e0ce7b8e2c05
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:747
  14:     0x55cee669e86a - glutin::api::x11::window::Window::set_icon::h49ace1003a0c42d3
                        at /home/matthias/vcs/github/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.4.25/src/api/x11/window.rs:766
  15:     0x55cee669a557 - glutin::api::x11::window::Window::new::h2c3e099dba7cec8e
                        at /home/matthias/vcs/github/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.4.25/src/api/x11/window.rs:711
  16:     0x55cee66a5cd6 - glutin::platform::platform::api_dispatch::Window::new::ha8e435fc89be4899
                        at /home/matthias/vcs/github/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.4.25/src/platform/linux/api_dispatch.rs:197
  17:     0x55cee66a6fb4 - glutin::window::_<impl glutin..WindowBuilder<'a>>::build::h99cdcf453332ce38
                        at /home/matthias/vcs/github/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.4.25/src/window.rs:235
  18:     0x55cee65dde4d - glutin_app::window::Window::new::h602578792f939950
                        at /home/matthias/vcs/github/servo/ports/glutin/window.rs:161
  19:     0x55cee65dd440 - glutin_app::create_window::h6aa21324e7f57f24
                        at /home/matthias/vcs/github/servo/ports/glutin/lib.rs:48
  20:     0x55cee6492526 - servo::main::h6924e5658370f6b5
                        at /home/matthias/vcs/github/servo/components/servo/main.rs:112
  21:     0x55ceea8131d8 - std::panicking::try::call::h852b0d5f2eec25e4
  22:     0x55ceea81e03b - __rust_try
  23:     0x55ceea81dfde - __rust_maybe_catch_panic
  24:     0x55ceea812c7e - std::rt::lang_start::hfe4efe1fc39e4a30
  25:     0x55cee65c9369 - main
  26:     0x7f214d0f0730 - __libc_start_main
  27:     0x55cee6490328 - _start
  28:                0x0 - <unknown>
Servo exited with return value 101
```

**Comment by dolftax** [comment]
I reproduced the same. FYI, https://dpaste.de/Lh1z/raw

**Comment by Aaron1011** [comment]
I can reproduce this on Arch Linux, with Awesome WM.

**Comment by nox** [comment]
Is this still an issue?

**Comment by dralley** [comment]
If there's no recent reports of this, it is probably fixed or was a bug in some external component
