### ISSUE TITLE
Windows 7 32 Bit and Windows 7 64 Bit - harfbuzz not Compiling

### ISSUE THREAD

**Issue by zeusintuivo** [servo/servo#12486]
After following the windows setup, as I also documented it right here https://github.com/servo/servo/issues/12356

It all seems to compile, except harfbuzz.

**Comment by zeusintuivo** [comment]
Here is the Windows 7 32 Bit Error Output:
``` 

------ ERROR WITH harfbuzz --------
C:\_\servo (master)
λ set RUST_BACKTRACE=1 & sh mach build --dev
   Compiling harfbuzz-sys v0.1.5
   Compiling openssl v0.7.14
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `harfbuzz-sys v0.1.5`
Process didn't exit successfully: `C:\_\servo\target\debug\build\harfbuzz-sys-7379a0f03f5c3e69\build-script-build` (exit code: 101)
--- stdout
cd C:\_\servo\target\debug\build\harfbuzz-sys-7379a0f03f5c3e69\out && C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\harfbuzz-sys-0.1.5/harfbuzz/configure --prefix=C:\_\servo\target\debug\build\harfbuzz-sys-7379a0f03f5c3e69\out --host=x86_64-pc-windows-msvc --enable-static --without-icu --without-freetype --without-glib \
        CFLAGS="-fPIC -g" CXXFLAGS="-fPIC -g"

--- stderr
/bin/sh: line 0: cd: C:_servotargetdebugbuildharfbuzz-sys-7379a0f03f5c3e69out: No such file or directory
make: *** [makefile.cargo:35: all] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env :: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\harfbuzz-sys-0.1.5\build.rs:14
stack backtrace:
   0:        0x13ff5c17c - std::rt::lang_start::hfe4efe1fc39e4a30
   1:        0x13ff5b789 - std::rt::lang_start::hfe4efe1fc39e4a30
   2:        0x13ff4646d - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   3:        0x13ff339a2 - begin_panic<&str>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:328
   4:        0x13ff313ce - main
                        at C:\_\servo\components\servo\<std macros>:3
   5:        0x13ff5b17c - std::rt::lang_start::hfe4efe1fc39e4a30
   6:        0x13ff5fcb1 - _rust_maybe_catch_panic
   7:        0x13ff5aeb4 - std::rt::lang_start::hfe4efe1fc39e4a30
   8:        0x13ff33ff9 - main
   9:        0x13ff64558 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  10:         0x771c652c - BaseThreadInitThunk

Build completed in 0:00:04

C:\_\servo (master)
λ set RUST_BACKTRACE=1 & sh mach build --dev --verbose
cargo.exe build -v
       Fresh odds v0.2.12
       Fresh utf8-ranges v0.1.3
       Fresh alloc-no-stdlib v1.2.0
       Fresh void v1.0.2
       Fresh mac v0.0.2
       Fresh unreachable v0.1.1
       Fresh simd v0.1.0 (https://github.com/huonw/simd#03de1cd0)
       Fresh cfg-if v0.1.0
       Fresh rustc-serialize v0.3.19
       Fresh heapsize_plugin v0.1.5
       Fresh num-traits v0.1.32
       Fresh inflate v0.1.1
       Fresh tenacious v0.2.1
       Fresh ref_filter_map v1.0.1
       Fresh plugins v0.0.1 (file:///C:/_/servo/components/plugins)
       Fresh lzw v0.10.0
       Fresh rustc-demangle v0.1.0
       Fresh typeable v0.1.2
       Fresh matches v0.1.2
       Fresh bit-vec v0.4.3
       Fresh quickersort v2.0.1
       Fresh bit-set v0.4.0
       Fresh brotli v1.0.6
       Fresh device v0.0.1 (https://github.com/servo/devices#3c39846a)
       Fresh unicode-bidi v0.2.3
       Fresh winapi-build v0.1.1
       Fresh byteorder v0.5.3
       Fresh libc v0.2.13
       Fresh quasi v0.13.0
       Fresh freetype v0.1.0 (https://github.com/servo/rust-freetype#d564ff90)
       Fresh num_cpus v0.2.13
       Fresh utf-8 v0.6.0
       Fresh make-cmd v0.1.0
       Fresh smallvec v0.1.8
       Fresh log v0.3.6
       Fresh hpack v0.2.0
       Fresh scoped_threadpool v0.1.7
       Fresh sig v0.1.1
       Fresh debug_unreachable v0.1.1
       Fresh khronos_api v1.0.0
       Fresh glob v0.2.11
       Fresh aster v0.19.0
       Fresh threadpool v1.3.1
       Fresh quasi_codegen v0.13.0
       Fresh xi-unicode v0.0.1
       Fresh quasi_macros v0.13.0
       Fresh memchr v0.1.11
       Fresh fnv v1.0.3
       Fresh aho-corasick v0.5.2
       Fresh semver v0.1.20
       Fresh browserhtml v0.1.15 (https://github.com/browserhtml/browserhtml?branch=gh-pages#48eed185)
       Fresh rustc_version v0.1.7
       Fresh winapi v0.2.7
       Fresh ws2_32-sys v0.2.1
       Fresh user32-sys v0.2.0
       Fresh getopts v0.2.14
   Compiling script v0.0.1 (file:///C:/_/servo/components/script)
     Running `C:\_\servo\target\debug\build\script-73e4c764adb42655\build-script-build`
       Fresh lazy_static v0.1.16
       Fresh rand v0.3.14
       Fresh color_quant v1.0.0
       Fresh gif v0.9.0
       Fresh solicit v0.4.4
       Fresh shell32-sys v0.1.1
       Fresh open v1.1.1
       Fresh lazy_static v0.2.1
       Fresh nodrop v0.1.6
       Fresh httparse v1.1.2
       Fresh unicase v1.4.0
   Compiling phf_shared v0.7.15
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\phf_shared-0.7.15\src/lib.rs --crate-name phf_shared --crate-type lib -g --cfg "feature=\"unicase\"" -C metadata=807aedd749f813f0 -C extra-filename=-807aedd749f813f0 --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern unicase=C:\_\servo\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --cap-lints allow -W unused-extern-crates`
       Fresh bitflags v0.7.0
       Fresh xml-rs v0.3.4
       Fresh traitobject v0.0.1
       Fresh serde v0.7.11
       Fresh serde_json v0.7.1
       Fresh uuid v0.2.2
       Fresh mime v0.2.1
       Fresh encoding_index_tests v0.1.4
       Fresh encoding-index-korean v1.20141219.5
       Fresh encoding-index-tradchinese v1.20141219.5
       Fresh encoding-index-singlebyte v1.20141219.5
       Fresh encoding-index-simpchinese v1.20141219.5
       Fresh num-integer v0.1.32
       Fresh num-bigint v0.1.32
       Fresh dbghelp-sys v0.2.0
   Compiling phf_generator v0.7.15
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\phf_generator-0.7.15\src\lib.rs --crate-name phf_generator --crate-type lib -g -C metadata=9c3a5098c6e52893 -C extra-filename=-9c3a5098c6e52893 --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf_shared=C:\_\servo\target\debug\deps\libphf_shared-807aedd749f813f0.rlib --extern rand=C:\_\servo\target\debug\deps\librand-49a08859d086fffe.rlib --cap-lints allow -W unused-extern-crates`
   Compiling phf_macros v0.7.15
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\phf_macros-0.7.15\src/lib.rs --crate-name phf_macros --crate-type dylib -C prefer-dynamic -g -C metadata=9e2b3206481bbf6b -C extra-filename=-9e2b3206481bbf6b --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf_shared=C:\_\servo\target\debug\deps\libphf_shared-807aedd749f813f0.rlib --extern phf_generator=C:\_\servo\target\debug\deps\libphf_generator-9c3a5098c6e52893.rlib --cap-lints allow -W unused-extern-crates`
   Compiling phf_codegen v0.7.15
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\phf_codegen-0.7.15\src\lib.rs --crate-name phf_codegen --crate-type lib -g -C metadata=200ea6a768935f87 -C extra-filename=-200ea6a768935f87 --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf_shared=C:\_\servo\target\debug\deps\libphf_shared-807aedd749f813f0.rlib --extern phf_generator=C:\_\servo\target\debug\deps\libphf_generator-9c3a5098c6e52893.rlib --cap-lints allow -W unused-extern-crates`
   Compiling xml5ever v0.1.3
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\xml5ever-0.1.3\build.rs --crate-name build_script_build --crate-type bin -g --cfg "feature=\"string_cache\"" --cfg "feature=\"tendril\"" --cfg "feature=\"unstable\"" --out-dir C:\_\servo\target\debug\build\xml5ever-ad6ba0d7d2ec7596 --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern rustc_serialize=C:\_\servo\target\debug\deps\librustc_serialize-3561541d79c18212.rlib --extern phf_codegen=C:\_\servo\target\debug\deps\libphf_codegen-200ea6a768935f87.rlib --cap-lints allow -W unused-extern-crates`
   Compiling mime_guess v1.8.0
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\mime_guess-1.8.0\src/gen_mime_types.rs --crate-name build_script_gen_mime_types --crate-type bin -g --out-dir C:\_\servo\target\debug\build\mime_guess-f5dae1e7e124632f --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern unicase=C:\_\servo\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --extern phf_codegen=C:\_\servo\target\debug\deps\libphf_codegen-200ea6a768935f87.rlib --cap-lints allow -W unused-extern-crates`
     Running `C:\_\servo\target\debug\build\xml5ever-ad6ba0d7d2ec7596\build-script-build`
   Compiling html5ever v0.5.4
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\html5ever-0.5.4\build.rs --crate-name build_script_build --crate-type bin -g --cfg "feature=\"tendril\"" --cfg "feature=\"string_cache\"" --cfg "feature=\"heap_size\"" --cfg "feature=\"unstable\"" --cfg "feature=\"heapsize\"" --cfg "feature=\"heapsize_plugin\"" --out-dir C:\_\servo\target\debug\build\html5ever-323aba74762bcccb --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf_codegen=C:\_\servo\target\debug\deps\libphf_codegen-200ea6a768935f87.rlib --extern rustc_serialize=C:\_\servo\target\debug\deps\librustc_serialize-3561541d79c18212.rlib --cap-lints allow -W unused-extern-crates`
     Running `C:\_\servo\target\debug\build\html5ever-323aba74762bcccb\build-script-build`
     Running `C:\_\servo\target\debug\build\mime_guess-f5dae1e7e124632f\build-script-gen_mime_types`
   Compiling string_cache v0.2.21
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\string_cache-0.2.21\build.rs --crate-name build_script_build --crate-type bin -g --cfg "feature=\"heap_size\"" --cfg "feature=\"heapsize\"" --cfg "feature=\"heapsize_plugin\"" --cfg "feature=\"unstable\"" --out-dir C:\_\servo\target\debug\build\string_cache-bee94be66d2c6ea2 --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf_generator=C:\_\servo\target\debug\deps\libphf_generator-9c3a5098c6e52893.rlib --extern phf_shared=C:\_\servo\target\debug\deps\libphf_shared-807aedd749f813f0.rlib --cap-lints allow -W unused-extern-crates`
     Running `C:\_\servo\target\debug\build\string_cache-bee94be66d2c6ea2\build-script-build`
       Fresh regex-syntax v0.3.3
       Fresh ref_slice v1.0.0
   Compiling phf v0.7.15
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\phf-0.7.15\src/lib.rs --crate-name phf --crate-type lib -g --cfg "feature=\"phf_shared\"" --cfg "feature=\"unicase\"" -C metadata=509d4b5b6cc4d13e -C extra-filename=-509d4b5b6cc4d13e --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf_shared=C:\_\servo\target\debug\deps\libphf_shared-807aedd749f813f0.rlib --cap-lints allow -W unused-extern-crates`
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\mime_guess-1.8.0\src\lib.rs --crate-name mime_guess --crate-type lib -g -C metadata=a4c276de42fe26f1 -C extra-filename=-a4c276de42fe26f1 --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern phf=C:\_\servo\target\debug\deps\libphf-509d4b5b6cc4d13e.rlib --extern unicase=C:\_\servo\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --extern mime=C:\_\servo\target\debug\deps\libmime-40ee41a2f2e225b0.rlib --cap-lints allow -W unused-extern-crates`
       Fresh language-tags v0.2.2
       Fresh gl_generator v0.5.2
   Compiling gleam v0.2.20
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\gleam-0.2.20\build.rs --crate-name build_script_build --crate-type bin -g --out-dir C:\_\servo\target\debug\build\gleam-8cc6d4d4d5b87928 --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern gl_generator=C:\_\servo\target\debug\deps\libgl_generator-43df6ad6a16c7145.rlib --cap-lints allow -W unused-extern-crates`
   Compiling servo-glutin v0.4.25
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\servo-glutin-0.4.25\build.rs --crate-name build_script_build --crate-type bin -g --cfg "feature=\"image\"" --cfg "feature=\"default\"" --out-dir C:\_\servo\target\debug\build\servo-glutin-0450dfa97fa62eff --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern gl_generator=C:\_\servo\target\debug\deps\libgl_generator-43df6ad6a16c7145.rlib --cap-lints allow -W unused-extern-crates`
     Running `C:\_\servo\target\debug\build\gleam-8cc6d4d4d5b87928\build-script-build`
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\gleam-0.2.20\src\lib.rs --crate-name gleam --crate-type lib -g -C metadata=d057e8501214cba0 -C extra-filename=-d057e8501214cba0 --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --cap-lints allow -l opengl32 -W unused-extern-crates`
   Compiling offscreen_gl_context v0.1.9
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\offscreen_gl_context-0.1.9\build.rs --crate-name build_script_build --crate-type bin -g --cfg "feature=\"serde\"" --cfg "feature=\"default\"" --cfg "feature=\"serde_serialization\"" --out-dir C:\_\servo\target\debug\build\offscreen_gl_context-c403121f1fa779d9 --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern khronos_api=C:\_\servo\target\debug\deps\libkhronos_api-cd058630d4047ffc.rlib --extern gl_generator=C:\_\servo\target\debug\deps\libgl_generator-43df6ad6a16c7145.rlib --cap-lints allow -W unused-extern-crates`
     Running `C:\_\servo\target\debug\build\offscreen_gl_context-c403121f1fa779d9\build-script-build`
       Fresh bincode v0.5.9
       Fresh gdi32-sys v0.2.0
       Fresh dwmapi-sys v0.1.0
     Running `C:\_\servo\target\debug\build\servo-glutin-0450dfa97fa62eff\build-script-build`
       Fresh pkg-config v0.3.8
   Compiling servo-freetype-sys v2.4.11
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\servo-freetype-sys-2.4.11\lib.rs --crate-name freetype_sys --crate-type lib -g -C metadata=434ddcd162db033e -C extra-filename=-434ddcd162db033e --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --cap-lints allow -L native=C:\_\servo\target\debug\build\servo-freetype-sys-325c3f4f0378a5b6\out -l static=freetype -W unused-extern-crates`
error: could not find native static library `freetype`, perhaps an -L flag is missing?
Build failed, waiting for other jobs to finish...
error: Could not compile `servo-freetype-sys`.

Caused by:
  Process didn't exit successfully: `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\servo-freetype-sys-2.4.11\lib.rs --crate-name freetype_sys --crate-type lib -g -C metadata=434ddcd162db033e -C extra-filename=-434ddcd162db033e --out-dir C:\_\servo\target\debug\deps --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --cap-lints allow -L native=C:\_\servo\target\debug\build\servo-freetype-sys-325c3f4f0378a5b6\out -l static=freetype -W unused-extern-crates` (exit code: 101)
Build completed in 0:04:25

C:\_\servo (master)
λ _

```

**Comment by zeusintuivo** [comment]
Here is the Windows 7 32 Bit Error Output:

``` 

-------- ERROR in harfbuzz -------



C:\_\servo (master)
λ set RUST_BACKTRACE=1 & sh mach build --dev
   Compiling expat-sys v2.1.2
   Compiling harfbuzz-sys v0.1.5
error: failed to run custom build command for `harfbuzz-sys v0.1.5`
Process didn't exit successfully: `C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\build-script-build` (exit code: 101)
--- stdout
cd C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\out && C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\harfbuzz-sys-0.1.5/harfbuzz/configure --prefix=C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\out --host=i686-pc-windows-msvc --enable-static --without-icu --without-freetype --without-glib \
        CFLAGS="-fPIC -g" CXXFLAGS="-fPIC -g"

--- stderr
/bin/sh: line 0: cd: C:_servotargetdebugbuildharfbuzz-sys-18569de6f0e41aabout: No such file or directory
make: *** [makefile.cargo:35: all] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env :: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\harfbuzz-sys-0.1.5\build.rs:14
stack backtrace:
   0:   0xd2ca70 - std::rt::lang_start::hfe4efe1fc39e4a30
   1:   0xd180ed - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   2:   0xd03e11 - begin_panic<&str>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:328
   3:   0xd01516 - main
                at C:\_\servo\components\servo\<std macros>:3
   4:   0xd2c3b8 - std::rt::lang_start::hfe4efe1fc39e4a30
   5:   0xd2c11f - std::rt::lang_start::hfe4efe1fc39e4a30
   6:   0xd04670 - main
   7: 0x778b3c44 - BaseThreadInitThunk
   8: 0x77cf37ea - RtlInitializeExceptionChain

Build completed in 0:00:53

C:\_\servo (master)
λ set RUST_BACKTRACE=1 & sh mach build --dev --verbose
cargo.exe build -v
       Fresh cfg-if v0.1.0
       Fresh odds v0.2.12
       Fresh getopts v0.2.14
       Fresh pkg-config v0.3.8
       Fresh semver v0.1.20
       Fresh rustc_version v0.1.7
       Fresh language-tags v0.2.2
       Fresh rustc-serialize v0.3.19
       Fresh serde v0.7.11
       Fresh fnv v1.0.3
       Fresh bitflags v0.7.0
       Fresh xml-rs v0.3.4
       Fresh threadpool v1.3.1
       Fresh mac v0.0.2
       Fresh typeable v0.1.2
       Fresh winapi v0.2.7
       Fresh heapsize_plugin v0.1.5
       Fresh encoding_index_tests v0.1.4
       Fresh encoding-index-singlebyte v1.20141219.5
       Fresh encoding-index-korean v1.20141219.5
       Fresh serde_item v0.2.0
       Fresh byteorder v0.5.3
   Compiling unicase v1.4.0
     Running `rustc C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\unicase-1.4.0\build.rs --crate-name build_script_build --crate-type bin -g --out-dir C:\_\servo\target\debug\build\unicase-fd641fd0c5786d02 --emit=dep-info,link -L dependency=C:\_\servo\target\debug\deps -L dependency=C:\_\servo\target\debug\deps --extern rustc_version=C:\_\servo\target\debug\deps\librustc_version-4bb6b8251871bd10.rlib --cap-lints allow -W unused-extern-crates`
       Fresh traitobject v0.0.1
       Fresh lzw v0.10.0
       Fresh smallvec v0.1.8
       Fresh glob v0.2.11
       Fresh void v1.0.2
       Fresh unicode-normalization v0.1.2
       Fresh nodrop v0.1.6
       Fresh encoding-index-tradchinese v1.20141219.5
       Fresh winapi-build v0.1.1
       Fresh libc v0.2.13
       Fresh rand v0.3.14
       Fresh scoped_threadpool v0.1.7
       Fresh gcc v0.3.28
       Fresh tenacious v0.2.1
       Fresh plugins v0.0.1 (file:///C:/_/servo/components/plugins)
       Fresh arrayvec v0.3.16
       Fresh utf8-ranges v0.1.3
       Fresh libz-sys v1.0.4
       Fresh miniz-sys v0.1.7
   Compiling harfbuzz-sys v0.1.5
     Running `C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\build-script-build`
error: failed to run custom build command for `harfbuzz-sys v0.1.5`
Process didn't exit successfully: `C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\build-script-build` (exit code: 101)
--- stdout
cd C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\out && C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\harfbuzz-sys-0.1.5/harfbuzz/configure --prefix=C:\_\servo\target\debug\build\harfbuzz-sys-18569de6f0e41aab\out --host=i686-pc-windows-msvc --enable-static --without-icu --without-freetype --without-glib \
        CFLAGS="-fPIC -g" CXXFLAGS="-fPIC -g"

--- stderr
/bin/sh: line 0: cd: C:_servotargetdebugbuildharfbuzz-sys-18569de6f0e41aabout: No such file or directory
make: *** [makefile.cargo:35: all] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env :: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', C:\_\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\harfbuzz-sys-0.1.5\build.rs:14
stack backtrace:
   0:    0x6ca70 - std::rt::lang_start::hfe4efe1fc39e4a30
   1:    0x580ed - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   2:    0x43e11 - begin_panic<&str>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:328
   3:    0x41516 - main
                at C:\_\servo\components\servo\<std macros>:3
   4:    0x6c3b8 - std::rt::lang_start::hfe4efe1fc39e4a30
   5:    0x6c11f - std::rt::lang_start::hfe4efe1fc39e4a30
   6:    0x44670 - main
   7: 0x778b3c44 - BaseThreadInitThunk
   8: 0x77cf37ea - RtlInitializeExceptionChain

Build completed in 0:01:22

C:\_\servo (master)
λ _
```

**Comment by nox** [comment]
I'm pretty sure this doesn't happen anymore.
