### ISSUE TITLE
Intermittent python exception in WPT tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#12724]
```
STDERR: Exception in thread Thread-TestrunnerManager-26:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/servo/buildbot/slave/linux-rel/build/tests/wpt/harness/wptrunner/testrunner.py", line 280, in run
    if commands[command](*data) is Stop:
  File "/home/servo/buildbot/slave/linux-rel/build/tests/wpt/harness/wptrunner/testrunner.py", line 505, in test_ended
    stack=result.stack)
  File "/home/servo/buildbot/slave/linux-rel/build/python/_virtualenv/lib/python2.7/site-packages/mozlog/logtypes.py", line 46, in inner
    data = converter.convert(*args, **kwargs)
  File "/home/servo/buildbot/slave/linux-rel/build/python/_virtualenv/lib/python2.7/site-packages/mozlog/logtypes.py", line 88, in convert
    out_value = self.args[key](value)
  File "/home/servo/buildbot/slave/linux-rel/build/python/_virtualenv/lib/python2.7/site-packages/mozlog/logtypes.py", line 121, in __call__
    (value, type(value).__name__, self.name, self.__class__.__name__))
ValueError: Failed to convert value FAILED of type unicode for field expected to type SubStatus
```

**Comment by jdm** [comment]
```
The test that triggered it was /html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html, based on investigating the raw log from WPT.
```
```
The test doesn't appear to have caused any output besides the normal Xlib stuff, but then the log shows "Unexpected count in this thread 1", which usually indicates output that shows unexpected test results. I think the python exception happens when trying to convert missing output into a code like FAIL or NOTRUN. Not sure why the output didn't show up, though.
```

**Comment by Ms2ger** [comment]
Not intermittent; needed
```diff
--- a/tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html.ini
+++ b/tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html.ini
@@ -1,5 +1,5 @@
 [navigation_unload_same_origin.html]
   type: testharness
   [Same-origin navigation started from unload handler]
-    expected: FAILED
+    expected: FAIL
```
