### ISSUE TITLE
Build failed for the Script component on Windows

### ISSUE THREAD

**Issue by artptr** [servo/servo#12919]
```
$ ./mach build -r -j1
   Compiling script v0.0.1 (file:///D:/projects/my/servo/components/script)
error: failed to run custom build command for `script v0.0.1 (file:///D:/projects/my/servo/components/script)`
process didn't exit successfully: `D:/projects/my/servo/target\release\build\script-65db5afac5752e05\build-script-build` (exit code: 101)
--- stdout
detected home dir change, cleaning out entire build directory
running: "cmake" "D:\\projects\\my\\servo\\components\\script\\." "-G" "MSYS Makefiles" "-DCMAKE_INSTALL_PREFIX=D:/projects/my/servo/target\\release\\build\\script-65db5afac5752e05\\out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is GNU 6.1.0
-- The CXX compiler identification is GNU 6.1.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/projects/my/servo/target/release/build/script-65db5afac5752e05/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--" "-j1"
Scanning dependencies of target ParserResults
[  1%] Generating Bindings
[  1%] Generating _cache
[  1%] Generating ParserResults.pkl

--- stderr
Traceback (most recent call last):
  File "D:/projects/my/servo/components/script/dom/bindings/codegen/pythonpath.py", line 61, in <module>
    main(sys.argv[1:])
  File "D:/projects/my/servo/components/script/dom/bindings/codegen/pythonpath.py", line 52, in main
    execfile(script, frozenglobals)
  File "D:/projects/my/servo/components/script/dom/bindings/codegen/GlobalGen.py", line 89, in <module>
    main()
  File "D:/projects/my/servo/components/script/dom/bindings/codegen/GlobalGen.py", line 56, in main
    with open(fullPath, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'D:/projects/my/servo/components/script/D:/projects/my/servo/components/script/dom/webidls/Attr.webidl'
make[2]: *** [CMakeFiles/ParserResults.dir/build.make:276: ParserResults.pkl] Error 1
make[1]: *** [CMakeFiles/Makefile2:2180: CMakeFiles/ParserResults.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', D:/projects/my/servo/.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.17\src\lib.rs:463
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build FAILED in 0:00:20
```

**Comment by Ms2ger** [comment]
@vvuk 

```
IOError: [Errno 2] No such file or directory: 'D:/projects/my/servo/components/script/D:/projects/my/servo/components/script/dom/webidls/Attr.webidl'
```

seems like fallout from the cmakization.

**Comment by nox** [comment]
@artptr Is this fixed now?

**Comment by artptr** [comment]
@nox Yes, thanks.
