### ISSUE TITLE
Intermittent "Operation not permitted" when killing servo process during test-wpt

### ISSUE THREAD

**Issue by jdm** [servo/servo#13400]
```
  ▶ ERROR [expected OK] /websockets/constructor/013.html
  └   → Traceback (most recent call last):
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/executors/base.py", line 149, in run_test
    result = self.do_test(test)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/executors/executorservo.py", line 133, in do_test
    self.proc.kill()
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 749, in kill
    self.proc.kill(sig=sig)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 165, in kill
    send_sig(signal.SIGTERM)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 152, in send_sig
    os.killpg(pid, sig)
OSError: [Errno 1] Operation not permitted
```

**Comment by samgiles** [comment]
Pretty sure I found a fix for this. PR incoming!

**Comment by samgiles** [comment]
Fix is upstream in `mozprocess` https://bugzilla.mozilla.org/show_bug.cgi?id=1329528.

Not sure how servo picks up those dependencies.

**Comment by samgiles** [comment]
This has been published to PyPI,
Looks like the fix should be picked up automatically \o/.

```
tests/wpt/harness/requirements_chrome.txt
1:mozprocess >= 0.19

tests/wpt/harness/requirements_firefox.txt
3:mozprocess >= 0.19

tests/wpt/harness/requirements_servo.txt
1:mozprocess >= 0.19
```

**Comment by nox** [comment]
@jdm Did the change ultimately land in our repo?

**Comment by dralley** [comment]
Bump

**Comment by jdm** [comment]
We have a more recent version of mozprocess in use now.
