### ISSUE TITLE
Build fails on macOS Sierra

### ISSUE THREAD

**Issue by gil0mendes** [servo/servo#13491]
The build fails on macOS Sierra when I execute the `./mach build --dev` command.

```text
Python virtualenv failed to execute properly:
Output: Running virtualenv with interpreter /usr/local/bin/python2.7

Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1129, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 352, in copyfile
    copyfileordir(src, dest, symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 327, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/gil0mendes/Documents/projects/experiments/servo/python/_virtualenv/lib/python2.7/config'
```

**Comment by jdm** [comment]
Is there any difference if you run `rm -rf python/_virtualenv/`?
