### ISSUE TITLE
Crash at GitHub

### ISSUE THREAD

**Issue by notriddle** [servo/servo#13533]
### How to reproduce

Visit https://github.com/servo/servo/pulls

### Output

```
$ ./mach run -r -w https://github.com/servo/servo/pulls
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-411d610e4b2b1ffa3d063904534406d08c8351d9ba9b4b3f339bab35e86bb4f3.js:7:29812 Promise is not defined
assertion failed: !obj.is_null() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/michael/Experiments/Rust/servo/components/script/dom/promise.rs:111)
stack backtrace:
   0:     0x55f12915a05d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
   1:     0x55f12915a6e2 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
   2:     0x55f127c67aed - servo::main::_{{closure}}::he119048d0362badc
   3:     0x55f12972b395 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   4:     0x55f128066c9f - std::panicking::begin_panic::h0914615a412ba184
   5:     0x55f128422249 - script::dom::promise::Promise::new::h551da5f7c88d54f5
   6:     0x55f1284b3f0e - script::fetch::Fetch::hc0c7f599470da7a5
   7:     0x55f128493840 - _<script..dom..window..Window as script..dom..bindings..codegen..Bindings..WindowBinding..WindowBinding..WindowMethods>::Fetch::h50be3aef15d4200d
   8:     0x55f1280c468c - std::panicking::try::do_call::h491e59f2d49474c0
   9:     0x55f129733d16 - __rust_maybe_catch_panic
  10:     0x55f128655030 - script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::fetch::h9ecb31483cb52563
  11:     0x55f128767784 - CallJitMethodOp
  12:     0x55f1282fbcd4 - script::dom::bindings::utils::generic_call::h9f59e3ba7a062443
  13:     0x55f128b0b062 - 2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgs
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxtinlines.h:232
                         - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:453
  14:     0x55f128b06841 - 2js13CallFromStackEP9JSContextRKN2JS8CallArgs
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:504
                         - Interpret
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:2873
  15:     0x55f128b0ad87 - 2js9RunScriptEP9JSContextRNS_8RunState
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:399
  16:     0x55f128b0afb0 - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:471
  17:     0x55f128b0b267 - 2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_E
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:517
  18:     0x55f12899dae2 - _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
                        at /home/michael/Experiments/Rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsapi.cpp:2781
  19:     0x55f128574f5c - script::dom::bindings::codegen::Bindings::EventListenerBinding::EventListener::HandleEvent::hdf64ae549a6a1b9d
  20:     0x55f128574b85 - script::dom::bindings::codegen::Bindings::EventListenerBinding::EventListener::HandleEvent_::haed055a0ab99b3ad
  21:     0x55f12836e40b - script::dom::eventdispatcher::handle_event::h2886639085893158
  22:     0x55f128370a25 - script::dom::eventdispatcher::invoke::he66bb8f013f74a75
  23:     0x55f12836fd7f - script::dom::eventdispatcher::dispatch_event::hf8825562746e78ab
  24:     0x55f12849efd1 - script::dom::window::Window::report_an_error::h3686abb3f9cc43bf
  25:     0x55f1282ea027 - script::dom::bindings::error::report_pending_exception::ha88356f8d5b5d5dc
  26:     0x55f128494485 - _<&'a T as script..dom..window..ScriptHelpers>::evaluate_script_on_global_with_result::hea7238f7b9399ac4
  27:     0x55f1283dd71a - script::dom::htmlscriptelement::HTMLScriptElement::execute::hbee98d66a491cc70
  28:     0x55f12833545a - script::dom::document::Document::finish_load::h907176fd0963a528
  29:     0x55f1283d864e - _<script..dom..htmlscriptelement..ScriptContext as net_traits..FetchResponseListener>::process_response_eof::ha8c7d056c86cd55f
  30:     0x55f1284bcb0c - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h0503c89e40659e6f
  31:     0x55f1284cd39f - _<script..script_thread..CancellableRunnable<T> as script..script_thread..Runnable>::handler::ha504209b2225f8b1
  32:     0x55f1284e7415 - script::script_thread::ScriptThread::handle_msg_from_script::hd50fd472b8a01259
  33:     0x55f128684b8d - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h838b3efffe42423e
  34:     0x55f1284db8d4 - script::script_thread::ScriptThread::handle_msgs::hab14e71319dde53c
  35:     0x55f1280a8f07 - std::panicking::try::do_call::h34f1203af96b4017
  36:     0x55f129733d16 - __rust_maybe_catch_panic
  37:     0x55f128227134 - _<F as alloc..boxed..FnBox<A>>::call_box::h447b3066cef1db2a
  38:     0x55f1297299d0 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  39:     0x7fe9189e2554 - start_thread
  40:     0x7fe918505dec - __clone
  41:                0x0 - <unknown>
ERROR:servo: assertion failed: !obj.is_null()
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-411d610e4b2b1ffa3d063904534406d08c8351d9ba9b4b3f339bab35e86bb4f3.js:6:3108 No such property on self-hosted object: window.fetch(...)
called `Result::unwrap()` on an `Err` value: RecvError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:799)
stack backtrace:
   0:     0x55f12915a05d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
   1:     0x55f12915a6e2 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
   2:     0x55f127c67aed - servo::main::_{{closure}}::he119048d0362badc
   3:     0x55f12972b395 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   4:     0x55f12972b262 - std::panicking::begin_panic::hfbeda5aad583dc32
   5:     0x55f12972b1a0 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   6:     0x55f12972b121 - rust_begin_unwind
   7:     0x55f129767bac - core::panicking::panic_fmt::h4395919ece15c671
   8:     0x55f1281ecfd0 - core::result::unwrap_failed::h06d2cd4980fcf11b
   9:     0x55f128685d37 - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h838b3efffe42423e
  10:     0x55f1284db8d4 - script::script_thread::ScriptThread::handle_msgs::hab14e71319dde53c
  11:     0x55f1280a8f07 - std::panicking::try::do_call::h34f1203af96b4017
  12:     0x55f129733d16 - __rust_maybe_catch_panic
  13:     0x55f128227134 - _<F as alloc..boxed..FnBox<A>>::call_box::h447b3066cef1db2a
  14:     0x55f1297299d0 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  15:     0x7fe9189e2554 - start_thread
  16:     0x7fe918505dec - __clone
  17:                0x0 - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:constellation::constellation: about:failure failed
```

**Comment by notriddle** [comment]
I just realized it might be worth doing a fresh build. I ran `git clean -dfx`, so now I'll see if it's just leftover bits-n-pieces of MozJS or something.

**Comment by notriddle** [comment]
Sorry for the noise. It's just an unclean build.
