### ISSUE TITLE
Build sometimes fails because of non-C locale

### ISSUE THREAD

**Issue by jorrete** [servo/servo#13536]
Building fails in mozjs_sys compilation.

```
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#34c3e075)`
process didn't exit successfully: `/home/jorro/Development/contributions/mozilla/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/build-script-build` (exit code: 101)
--- stdout
[[ /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure -ot /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure.in ]] && touch /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure || true
[[ /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure -ot /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure.in ]] && touch /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure || true
! [[ /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure.in -ot /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure ]] && touch /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure || true
! [[ /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure.in -ot /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure ]] && touch /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure || true
if [[ /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure -nt /home/jorro/Development/contributions/mozilla/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out/config.status ]] ; then \
  cd /home/jorro/Development/contributions/mozilla/servo/target/release/build/mozjs_sys-661d4efe7c7ca939/out && \
  PYTHON="python" MOZ_TOOLS="" \
  CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
  /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --without-intl-api --build-backends=RecursiveMake --enable-sm-promise --disable-shared-js || (cat config.log && exit 1) ; \
fi
Reexecuting in the virtualenv
checking for a shell... /usr/bin/sh
checking for host system type... x86_64-pc-linux-gnu
checking for target system type... x86_64-pc-linux-gnu
checking for the Android toolchain directory... not found
checking whether cross compiling... no
checking for pkg_config... /usr/bin/pkg-config
checking for pkg-config version... 0.29
checking for yasm... not found
checking for the target C compiler... /usr/bin/gcc
checking whether the target C compiler can be used... INFO: checking for a shell... 
INFO: /usr/bin/sh
INFO: checking for host system type... 
INFO: x86_64-pc-linux-gnu
INFO: checking for target system type... 
INFO: x86_64-pc-linux-gnu
INFO: checking for the Android toolchain directory... 
INFO: not found
INFO: checking whether cross compiling... 
INFO: no
INFO: checking for pkg_config... 
DEBUG: pkg_config: Trying pkg-config
INFO: /usr/bin/pkg-config
INFO: checking for pkg-config version... 
DEBUG: Executing: `/usr/bin/pkg-config --version`
INFO: 0.29
INFO: checking for yasm... 
DEBUG: yasm: Trying yasm
INFO: not found
INFO: checking for the target C compiler... 
DEBUG: _cc: Trying gcc
INFO: /usr/bin/gcc
INFO: checking whether the target C compiler can be used... 
DEBUG: Creating `/tmp/conftest.H_qOGM.c` with content:
DEBUG: | #if defined(_MSC_VER)
DEBUG: | #if defined(__clang__)
DEBUG: | %COMPILER clang-cl
DEBUG: | %VERSION _MSC_FULL_VER
DEBUG: | #else
DEBUG: | %COMPILER msvc
DEBUG: | %VERSION _MSC_FULL_VER
DEBUG: | #endif
DEBUG: | #elif defined(__clang__)
DEBUG: | %COMPILER clang
DEBUG: | #  if !__cplusplus || __cpp_static_assert
DEBUG: | %VERSION __clang_major__.__clang_minor__.__clang_patchlevel__
DEBUG: | #  endif
DEBUG: | #elif defined(__GNUC__)
DEBUG: | %COMPILER gcc
DEBUG: | %VERSION __GNUC__.__GNUC_MINOR__.__GNUC_PATCHLEVEL__
DEBUG: | #endif
DEBUG: | 
DEBUG: | #if __cplusplus
DEBUG: | %cplusplus __cplusplus
DEBUG: | #elif __STDC_VERSION__
DEBUG: | %STDC_VERSION __STDC_VERSION__
DEBUG: | #elif __STDC__
DEBUG: | %STDC_VERSION 198900L
DEBUG: | #endif
DEBUG: Executing: `/usr/bin/gcc -E /tmp/conftest.H_qOGM.c`
makefile.cargo:120: fallo en las instrucciones para el objetivo 'maybe-configure'

--- stderr
gmake: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
DEBUG: <truncated - see config.log for full output>
DEBUG: | %VERSION _MSC_FULL_VER
DEBUG: | #endif
DEBUG: | #elif defined(__clang__)
DEBUG: | %COMPILER clang
DEBUG: | #  if !__cplusplus || __cpp_static_assert
DEBUG: | %VERSION __clang_major__.__clang_minor__.__clang_patchlevel__
DEBUG: | #  endif
DEBUG: | #elif defined(__GNUC__)
DEBUG: | %COMPILER gcc
DEBUG: | %VERSION __GNUC__.__GNUC_MINOR__.__GNUC_PATCHLEVEL__
DEBUG: | #endif
DEBUG: | 
DEBUG: | #if __cplusplus
DEBUG: | %cplusplus __cplusplus
DEBUG: | #elif __STDC_VERSION__
DEBUG: | %STDC_VERSION __STDC_VERSION__
DEBUG: | #elif __STDC__
DEBUG: | %STDC_VERSION 198900L
DEBUG: | #endif
DEBUG: Executing: `/usr/bin/gcc -E /tmp/conftest.H_qOGM.c`
Traceback (most recent call last):
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/../../configure.py", line 93, in <module>
    sys.exit(main(sys.argv))
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/../../configure.py", line 22, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 260, in run
    func(*args)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 302, in _value_for
    return self._value_for_depends(obj)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/util.py", line 922, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 329, in _value_for_depends
    return func(*resolved_args)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 518, in wrapper
    ret = template(*args, **kwargs)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/build/moz.configure/checks.configure", line 53, in wrapped
    ret = func(*args, **kwargs)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/build/moz.configure/toolchain.configure", line 515, in valid_compiler
    info = check_compiler(wrapper + [compiler] + flags, language)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/build/moz.configure/toolchain.configure", line 297, in check_compiler
    info = get_compiler_info(compiler, language)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/build/moz.configure/toolchain.configure", line 260, in get_compiler_info
    if line.startswith('%'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
gmake: *** [maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /home/jorro/Development/contributions/mozilla/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/build.rs:43
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build FAILED in 0:05:15
```

Thanks.

**Comment by jdm** [comment]
Given output like `gmake: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.`, I suspect the build might work if you temporarily switch your language to english.

**Comment by jorrete** [comment]
You were right.
export LANG=EN before ./mach build fixed it.
Thanks!

**Comment by nox** [comment]
I've repurposed the ticket accordingly.

**Comment by mrobinson** [comment]
I suspect that this is likely fixed due to the change to Python 3, but please comment if there are still issues.
