### ISSUE TITLE
Assertion failure (!obj.is_null()) when visiting github on Promise construction.

### ISSUE THREAD

**Issue by emilio** [servo/servo#13619]
While trying to see if #13618 reproduced on, e.g. github I got:

<details>
```
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-692b107fd3bb0b6bcba6310ba44fa11bf0a505023b59749b2f5a1d363b08fb24.js:7:14660 Promise is not defined
assertion failed: !obj.is_null() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/emilio/projects/moz/servo-2/components/script/dom/promise.rs:111)
stack backtrace:
   0:     0x5556c4b140fd - backtrace::backtrace::trace::h0e60ef08c7c34e9f
   1:     0x5556c4b14782 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
   2:     0x5556c4630ffd - servo::main::_{{closure}}::h7eca4aa0d57a79a1
   3:     0x5556c6077ec5 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   4:     0x5556c4d4737f - std::panicking::begin_panic::h0914615a412ba184
   5:     0x5556c50f08f9 - script::dom::promise::Promise::new::h41ac8eecbb9dfb04
   6:     0x5556c5182fee - script::fetch::Fetch::h1e4db3b6134908bf
   7:     0x5556c5163170 - _<script..dom..window..Window as script..dom..bindings..codegen..Bindings..WindowBinding..WindowBinding..WindowMethods>::Fetch::h1ca48125756c6d1c
   8:     0x5556c4dcbc8c - std::panicking::try::do_call::h6514874038855e95
   9:     0x5556c6080846 - __rust_maybe_catch_panic
  10:     0x5556c53245d0 - script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::fetch::h3e4e9463dda55d59
  11:     0x5556c599b214 - CallJitMethodOp
  12:     0x5556c4fc5d54 - script::dom::bindings::utils::generic_call::h7b7a2e83402f518c
  13:     0x5556c5d42e2f - 2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgs
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxtinlines.h:232
                         - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:453
  14:     0x5556c5d3dbdc - 2js13CallFromStackEP9JSContextRKN2JS8CallArgs
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:504
                         - Interpret
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:2873
  15:     0x5556c5d42b67 - 2js9RunScriptEP9JSContextRNS_8RunState
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:399
  16:     0x5556c5d42d82 - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:471
  17:     0x5556c5d43097 - 2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_E
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:517
  18:     0x5556c5bd8d04 - _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsapi.cpp:2781
  19:     0x5556c524490c - script::dom::bindings::codegen::Bindings::EventListenerBinding::EventListener::HandleEvent::hd8a6a80d417e9f18
  20:     0x5556c5244535 - script::dom::bindings::codegen::Bindings::EventListenerBinding::EventListener::HandleEvent_::hc62dfe070ba390fe
  21:     0x5556c503c6be - script::dom::eventdispatcher::handle_event::hcdc612cbe7f396ce
  22:     0x5556c503eaf5 - script::dom::eventdispatcher::invoke::hb7e6af10bb4d522e
  23:     0x5556c503de4f - script::dom::eventdispatcher::dispatch_event::hab193e3e97398e86
  24:     0x5556c516da51 - script::dom::window::Window::report_an_error::haeb31205e9c5c35b
  25:     0x5556c4fb3a67 - script::dom::bindings::error::report_pending_exception::hdc99f836712248e9
  26:     0x5556c4fb4938 - script::dom::bindings::global::GlobalRef::evaluate_script_on_global_with_result::hcc80ef98e1711be1
  27:     0x5556c50abdf3 - script::dom::htmlscriptelement::HTMLScriptElement::execute::h1431a1bf2741dbfe
  28:     0x5556c500334a - script::dom::document::Document::finish_load::he69ad7fdcfe70d5a
  29:     0x5556c50983c4 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..FetchResponseListener>::process_response_eof::he8dfe568f23b8c3a
  30:     0x5556c518c56c - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h4b9f68ca7733593e
  31:     0x5556c519c59f - _<script..script_thread..CancellableRunnable<T> as script..script_thread..Runnable>::handler::h33f8c79e7abe3afb
  32:     0x5556c51b6ec5 - script::script_thread::ScriptThread::handle_msg_from_script::h22117c26679e33df
  33:     0x5556c5352cdd - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h4c5f9a9b0f46cee6
  34:     0x5556c51ab3c6 - script::script_thread::ScriptThread::handle_msgs::h4c0028978ab9b7da
  35:     0x5556c4e2b707 - std::panicking::try::do_call::hae6136dcd28d1132
  36:     0x5556c6080846 - __rust_maybe_catch_panic
  37:     0x5556c4f05d34 - _<F as alloc..boxed..FnBox<A>>::call_box::h49057abcffe4c8f3
  38:     0x5556c6076500 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  39:     0x7f76638c0453 - start_thread
  40:     0x7f76633ec7de - __GI___clone
  41:                0x0 - <unknown>
ERROR:servo: assertion failed: !obj.is_null()
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-692b107fd3bb0b6bcba6310ba44fa11bf0a505023b59749b2f5a1d363b08fb24.js:5:19977 No such property on self-hosted object: window.fetch(...)
```
</details>

**Comment by emilio** [comment]
That was a release build. Debug:

```
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-692b107fd3bb0b6bcba6310ba44fa11bf0a505023b59749b2f5a1d363b08fb24.js:7:14660 Promise is not defined
assertion failed: !obj.is_null() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/emilio/projects/moz/servo-2/components/script/dom/promise.rs:111)
stack backtrace:
   0:     0x55731a3a5431 - backtrace::backtrace::libunwind::trace
                        at /home/emilio/projects/moz/servo-2/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:82
                         - backtrace::backtrace::trace<closure>
                        at /home/emilio/projects/moz/servo-2/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x55731a3a60b0 - backtrace::capture::{{impl}}::new
                        at /home/emilio/projects/moz/servo-2/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/lib.rs:96
   2:     0x557319038b9b - servo::main::{{closure}}
                        at /home/emilio/projects/moz/servo-2/components/servo/main.rs:121
   3:     0x55731dc6b605 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   4:     0x55731ade23c3 - std::panicking::begin_panic<&str>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   5:     0x55731bc5857b - script::dom::promise::{{impl}}::create_js_promise
                        at /home/emilio/projects/moz/servo-2/components/script/dom/promise.rs:111
   6:     0x55731bc57fae - script::dom::promise::{{impl}}::new
                        at /home/emilio/projects/moz/servo-2/components/script/dom/promise.rs:77
   7:     0x55731bcfe4b9 - script::fetch::Fetch
                        at /home/emilio/projects/moz/servo-2/components/script/fetch.rs:71
   8:     0x55731bcdb92c - script::dom::window::{{impl}}::Fetch
                        at /home/emilio/projects/moz/servo-2/components/script/dom/window.rs:907
   9:     0x55731c44f710 - script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::fetch::{{closure}}
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/mod.rs:160
  10:     0x55731c44fc38 - extern $u22$rust.call$u22$$u20$fn$LP$$u5b$closure$SP$$u2f$home$u2f$emilio$u2f$projects$u2f$moz$u2f$servo.2$u2f$target$u2f$debug$u2f$build$u2f$script.4aa19a811511d6bb$u2f$out$u2f$Bindings$u2f$WindowBinding.rs.7441.23.$u20$7477.22$u20$this.$RF$$BP$const$u20$dom..window..Window$C$$u20$args.$RF$$BP$const$u20$js..jsapi..JSJitMethodCallArgs$C$$u20$cx.$RF$$BP$mut$u20$js..jsapi..JSContext$u5d$$C$$u20$$LP$$RP$$RP$$u20$.$GT$$u20$bool::once_shim.84785::hd8462045667a63f4
  11:     0x55731b759d1a - std::panic::{{impl}}::call_once<bool,closure>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:255
  12:     0x55731b0b0ef0 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,bool>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  13:     0x55731dc73f86 - __rust_maybe_catch_panic
  14:     0x55731b0098bc - std::panicking::try<bool,std::panic::AssertUnwindSafe<closure>>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
  15:     0x55731adaaef6 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,bool>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
  16:     0x55731ba0ebf3 - script::dom::bindings::utils::wrap_panic<closure,bool>
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/utils.rs:522
  17:     0x55731bf66832 - script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::fetch
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/mod.rs:160
  18:     0x55731d4e15c0 - CallJitMethodOp
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/master/src/jsglue.cpp:472
  19:     0x55731b88d98d - script::dom::bindings::utils::generic_call
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/utils.rs:449
  20:     0x55731b88da51 - script::dom::bindings::utils::generic_method
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/utils.rs:457
  21:     0x55731d889f3f - 2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgs
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxtinlines.h:232
                         - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:453
  22:     0x55731d884cfc - 2js13CallFromStackEP9JSContextRKN2JS8CallArgs
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:504
                         - Interpret
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:2873
  23:     0x55731d889c77 - 2js9RunScriptEP9JSContextRNS_8RunState
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:399
  24:     0x55731d889e92 - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:471
  25:     0x55731d88a1a7 - 2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_E
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:517
  26:     0x55731d7203d4 - _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
                        at /home/emilio/projects/moz/servo-2/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsapi.cpp:2781
  27:     0x55731bde70bc - script::dom::bindings::codegen::Bindings::EventListenerBinding::{{impl}}::HandleEvent
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/mod.rs:160
  28:     0x55731bde6613 - script::dom::bindings::codegen::Bindings::EventListenerBinding::{{impl}}::HandleEvent_<script::dom::eventtarget::EventTarget>
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/mod.rs:160
  29:     0x55731bbb356b - script::dom::eventtarget::{{impl}}::call_or_handle_event<script::dom::eventtarget::EventTarget>
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventtarget.rs:151
  30:     0x55731bbb0934 - script::dom::eventdispatcher::handle_event
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventdispatcher.rs:46
  31:     0x55731bbb2191 - script::dom::eventdispatcher::inner_invoke
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventdispatcher.rs:218
  32:     0x55731bbb204c - script::dom::eventdispatcher::invoke
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventdispatcher.rs:193
  33:     0x55731bbb0e78 - script::dom::eventdispatcher::dispatch_to_listeners
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventdispatcher.rs:83
  34:     0x55731bbb1b48 - script::dom::eventdispatcher::dispatch_event
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventdispatcher.rs:157
  35:     0x55731bbb4f48 - script::dom::eventtarget::{{impl}}::dispatch_event
                        at /home/emilio/projects/moz/servo-2/components/script/dom/eventtarget.rs:308
  36:     0x55731bbb041a - script::dom::event::{{impl}}::fire
                        at /home/emilio/projects/moz/servo-2/components/script/dom/event.rs:316
  37:     0x55731bce4733 - script::dom::window::{{impl}}::report_an_error
                        at /home/emilio/projects/moz/servo-2/components/script/dom/window.rs:1721
  38:     0x55731b806ef0 - script::dom::bindings::global::{{impl}}::report_an_error
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/global.rs:325
  39:     0x55731b804ecc - script::dom::bindings::error::report_pending_exception
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/error.rs:249
  40:     0x55731c00693e - script::dom::bindings::global::{{impl}}::evaluate_script_on_global_with_result::{{closure}}
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/global.rs:248
  41:     0x55731ab74107 - profile_traits::time::profile<(),closure>
                        at /home/emilio/projects/moz/servo-2/components/profile_traits/time.rs:114
  42:     0x55731b80675a - script::dom::bindings::global::{{impl}}::evaluate_script_on_global_with_result
                        at /home/emilio/projects/moz/servo-2/components/script/dom/bindings/global.rs:231
  43:     0x55731bc171f7 - script::dom::htmlscriptelement::{{impl}}::execute
                        at /home/emilio/projects/moz/servo-2/components/script/dom/htmlscriptelement.rs:507
  44:     0x55731bb73158 - script::dom::document::{{impl}}::maybe_execute_parser_blocking_script
                        at /home/emilio/projects/moz/servo-2/components/script/dom/document.rs:1497
  45:     0x55731bb72a0d - script::dom::document::{{impl}}::finish_load
                        at /home/emilio/projects/moz/servo-2/components/script/dom/document.rs:1458
  46:     0x55731bc0638c - script::dom::htmllinkelement::{{impl}}::process_response_eof
                        at /home/emilio/projects/moz/servo-2/components/script/dom/htmllinkelement.rs:383
  47:     0x55731b5f6e9a - net_traits::{{impl}}::process<script::dom::htmllinkelement::StylesheetContext>
                        at /home/emilio/projects/moz/servo-2/components/net_traits/lib.rs:302
  48:     0x55731bd0c6d5 - script::network_listener::{{impl}}::handler<net_traits::FetchResponseMsg,script::dom::htmllinkelement::StylesheetContext>
                        at /home/emilio/projects/moz/servo-2/components/script/network_listener.rs:71
  49:     0x55731bd1b55c - script::script_thread::{{impl}}::handler<script::network_listener::ListenerRunnable<net_traits::FetchResponseMsg, script::dom::htmllinkelement::StylesheetContext>>
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:202
  50:     0x55731bd2541c - script::script_thread::{{impl}}::handle_msg_from_script
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:951
  51:     0x55731c0060dc - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:785
  52:     0x55731bd23ab6 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:879
  53:     0x55731bd21700 - script::script_thread::{{impl}}::handle_msgs
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:777
  54:     0x55731bd1fcec - script::script_thread::{{impl}}::start
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:631
  55:     0x55731c005e34 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:477
  56:     0x55731ab72909 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /home/emilio/projects/moz/servo-2/components/profile_traits/mem.rs:59
  57:     0x55731c2aab76 - script::script_thread::{{impl}}::create::{{closure}}
                        at /home/emilio/projects/moz/servo-2/components/script/script_thread.rs:476
  58:     0x55731b72991a - std::panic::{{impl}}::call_once<(),closure>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:255
  59:     0x55731b10637c - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  60:     0x55731dc73f86 - __rust_maybe_catch_panic
  61:     0x55731b005134 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
  62:     0x55731ad93d6f - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
  63:     0x55731c022a01 - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:277
  64:     0x55731b47b159 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:591
  65:     0x55731dc69c40 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  66:     0x7fb226f4f453 - start_thread
  67:     0x7fb226a7b7de - __GI___clone
  68:                0x0 - <unknown>
ERROR:servo: assertion failed: !obj.is_null()
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-692b107fd3bb0b6bcba6310ba44fa11bf0a505023b59749b2f5a1d363b08fb24.js:5:19977 No such property on self-hosted object: window.fetch(...)
```

**Comment by emilio** [comment]
cc @jdm

**Comment by jdm** [comment]
What happens if you remove the build folder for mozjs-sys and rebuild?

**Comment by emilio** [comment]
Testing now, but given with a fresh debugmozjs build I wasn't able to reproduce, I guess it's likely to not happen.

**Comment by emilio** [comment]
Yep, not happening, thanks Josh!
