### ISSUE TITLE
Unable to render websites

### ISSUE THREAD

**Issue by nerith** [servo/servo#13823]
On my Debian 8 machine, running a Servo release build on http://www.wikipedia.org renders a blank screen, although elements such as links and text input boxes seem to be there (hovering the mouse over where the elements would be causes the mouse cursor to change). This also occurs on other websites, such as Google.

This machine has an NVIDIA GTX 650 video card.
`VGA compatible controller: NVIDIA Corporation GK107 [GeForce GTX 650] (rev a1)`
#### Screenshot:

![servo_blank](https://cloud.githubusercontent.com/assets/5355224/19489337/e2d5870a-9538-11e6-8af9-6f1e8354069f.png)

I also get this message when closing Servo after loading Wikipedia:

```
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:799)
```

**Comment by nerith** [comment]
Testing this at commit  `cff0f01c7`, I'm getting the same result but Servo crashes and gives this backtrace:

```
Stack trace for thread "main"
stack backtrace:
   0:     0x7f83dd64eb5d - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:     0x7f83dd64f1e2 - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:     0x7f83dc15ef14 - servo::install_crash_handler::handler::ha68b0f7af03cdb5b
   3:     0x7f83dd46e3d3 - AsmJSFaultHandler
                        at /home/brandon/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   4:     0x7f83d9dd1ecf - <unknown>
   5:     0x7f83d4274d25 - <unknown>
   6:     0x7f83d42768f9 - <unknown>
   7:     0x7f83d4276dd7 - <unknown>
   8:     0x7f83d41fffd7 - <unknown>
   9:     0x7f83d4274e01 - <unknown>
  10:     0x7f83d42514ac - <unknown>
  11:     0x7f83d4251803 - <unknown>
  12:     0x7f83d41f513b - <unknown>
  13:     0x7f83d42c09f2 - <unknown>
  14:     0x7f83d42c1821 - <unknown>
  15:     0x7f83d42b3803 - <unknown>
  16:     0x7f83d42bd5ff - <unknown>
  17:     0x7f83d3fe2cae - <unknown>
  18:     0x7f83d3fb41bb - <unknown>
  19:     0x7f83d3fb55b7 - <unknown>
  20:     0x7f83d3fb5648 - <unknown>
  21:     0x7f83dd5ef1ce - webrender::renderer::Renderer::draw_ubo_batch::h920c88232d16651d
  22:     0x7f83dd5f3345 - webrender::renderer::Renderer::render::_{{closure}}::ha0f7feabb3de5842
  23:     0x7f83dd5ed8e0 - webrender::renderer::Renderer::render::hc9ed1f5d1a931c32
  24:     0x7f83dc15925d - _<compositing..compositor..IOCompositor<Window>>::composite_specific_target::h7f0f44845e1a0bd4
  25:     0x7f83dc15ccaf - _<compositing..compositor..IOCompositor<Window>>::composite::heda0d34909e95aed
  26:     0x7f83dc146b5f - _<servo..Browser<Window>>::handle_events::h994dd5794749be09
  27:     0x7f83dc1610e5 - servo::main::ha1e79b5d660fa59e
  28:     0x7f83ddc14a0a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  29:     0x7f83ddc0b3ca - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
                         - std::rt::lang_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  30:     0x7f83d982a72f - __libc_start_main
  31:     0x7f83dc136318 - _start
  32:                0x0 - <unknown>
Stack trace for thread "main"
stack backtrace:
   0:     0x7f83dd64eb5d - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:     0x7f83dd64f1e2 - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:     0x7f83dc15ef14 - servo::install_crash_handler::handler::ha68b0f7af03cdb5b
   3:     0x7f83d983d24f - <unknown>
   4:     0x7f83dc15ef9f - servo::install_crash_handler::handler::ha68b0f7af03cdb5b
   5:     0x7f83dd46e3d3 - AsmJSFaultHandler
                        at /home/brandon/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   6:     0x7f83d9dd1ecf - <unknown>
   7:     0x7f83d4274d25 - <unknown>
   8:     0x7f83d42768f9 - <unknown>
   9:     0x7f83d4276dd7 - <unknown>
  10:     0x7f83d41fffd7 - <unknown>
  11:     0x7f83d4274e01 - <unknown>
  12:     0x7f83d42514ac - <unknown>
  13:     0x7f83d4251803 - <unknown>
  14:     0x7f83d41f513b - <unknown>
  15:     0x7f83d42c09f2 - <unknown>
  16:     0x7f83d42c1821 - <unknown>
  17:     0x7f83d42b3803 - <unknown>
  18:     0x7f83d42bd5ff - <unknown>
  19:     0x7f83d3fe2cae - <unknown>
  20:     0x7f83d3fb41bb - <unknown>
  21:     0x7f83d3fb55b7 - <unknown>
  22:     0x7f83d3fb5648 - <unknown>
  23:     0x7f83dd5ef1ce - webrender::renderer::Renderer::draw_ubo_batch::h920c88232d16651d
  24:     0x7f83dd5f3345 - webrender::renderer::Renderer::render::_{{closure}}::ha0f7feabb3de5842
  25:     0x7f83dd5ed8e0 - webrender::renderer::Renderer::render::hc9ed1f5d1a931c32
  26:     0x7f83dc15925d - _<compositing..compositor..IOCompositor<Window>>::composite_specific_target::h7f0f44845e1a0bd4
  27:     0x7f83dc15ccaf - _<compositing..compositor..IOCompositor<Window>>::composite::heda0d34909e95aed
  28:     0x7f83dc146b5f - _<servo..Browser<Window>>::handle_events::h994dd5794749be09
  29:     0x7f83dc1610e5 - servo::main::ha1e79b5d660fa59e
  30:     0x7f83ddc14a0a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  31:     0x7f83ddc0b3ca - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
                         - std::rt::lang_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  32:     0x7f83d982a72f - __libc_start_main
  33:     0x7f83dc136318 - _start
  34:                0x0 - <unknown>
Servo exited with return value -4
```

**Comment by jdm** [comment]
If you could catch that in gdb and get a backtrace, that would be quite valuable.

**Comment by nerith** [comment]
@jdm I got the following backtrace from running a debug build in gdb:
```
(gdb) bt
#0  0x00007ffff0474d25 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#1  0x00007ffff04768fa in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#2  0x00007ffff0476dd8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#3  0x00007ffff03fffd8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#4  0x00007ffff0474e02 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#5  0x00007ffff04514ad in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#6  0x00007ffff0451804 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#7  0x00007ffff03f513c in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#8  0x00007ffff04c09f3 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#9  0x00007ffff04c1822 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#10 0x00007ffff04b3804 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#11 0x00007ffff04bd600 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#12 0x00007ffff01e2caf in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#13 0x00007ffff01b41bc in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#14 0x00007ffff01b55b8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#15 0x00007ffff01b5649 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#16 0x000055555987b2b6 in gleam::ffi::DrawElementsInstanced (mode=4, count=6, type_=5123, indices=0x0, instancecount=2)
    at /home/brandon/servo/target/debug/build/gleam-ad81c115f1bfab1c/out/gl_bindings.rs:1437
#17 0x00005555598793ad in gleam::gl::draw_elements_instanced (mode=4, count=6, element_type=5123, indices_offset=0, primcount=2)
    at /home/brandon/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/gleam-0.2.24/src/gl.rs:769
#18 0x0000555559964c6f in webrender::device::{{impl}}::draw_indexed_triangles_instanced_u16 (self=0x7fffffffd640, index_count=6, 
    instance_count=2)
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/device.rs:1714
#19 0x00005555599ab662 in webrender::renderer::{{impl}}::draw_ubo_batch<webrender::tiling::PrimitiveInstance> (
    self=0x7fffffffd630, ubo_data=..., shader=..., quads_per_item=1, color_texture_id=..., mask_texture_id=..., 
    max_prim_items=1024, projection=0x7fffffffa400)
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/renderer.rs:1326
#20 0x00005555599ac8f3 in webrender::renderer::{{impl}}::draw_target (self=0x7fffffffd630, render_target=..., 
    target=0x7fffeae52180, target_size=0x7fffffffa998, cache_texture=..., should_clear=false)
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/renderer.rs:1437
#21 0x00005555599ae14d in webrender::renderer::{{impl}}::draw_tile_frame (self=0x7fffffffd630, frame=0x7fffffffb2f8, 
    framebuffer_size=0x7fffffffb5e8)
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/renderer.rs:1612
#22 0x00005555599bc87d in webrender::renderer::{{impl}}::render::{{closure}} ()
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/renderer.rs:783
#23 0x0000555559977874 in webrender::profiler::{{impl}}::profile<(),closure> (self=0x7fffffffb260, callback=...)
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/profiler.rs:144
#24 0x00005555599a66c4 in webrender::renderer::{{impl}}::render (self=0x7fffffffd630, framebuffer_size=...)
    at /home/brandon/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender/src/renderer.rs:772
#25 0x00005555559ac1bd in compositing::compositor::{{impl}}::composite_specific_target::{{closure}}<glutin_app::window::Window> ()
    at /home/brandon/servo/components/compositing/compositor.rs:1464
#26 0x00005555558f9745 in profile_traits::time::profile<(),closure> (category=Compositing, meta=..., profiler_chan=..., 
    callback=...) at /home/brandon/servo/components/profile_traits/time.rs:115
#27 0x000055555596ff90 in compositing::compositor::{{impl}}::composite_specific_target<glutin_app::window::Window> (
    self=0x7fffffffd4d8, target=Window) at /home/brandon/servo/components/compositing/compositor.rs:1460
#28 0x0000555555976631 in compositing::compositor::{{impl}}::composite<glutin_app::window::Window> (self=0x7fffffffd4d8)
    at /home/brandon/servo/components/compositing/compositor.rs:1404
#29 0x0000555555967145 in compositing::compositor::{{impl}}::handle_events<glutin_app::window::Window> (self=0x7fffffffd4d8, 
    messages=...) at /home/brandon/servo/components/compositing/compositor.rs:1617
#30 0x0000555555901a5b in servo::{{impl}}::handle_events<glutin_app::window::Window> (self=0x7fffffffd4d8, events=...)
    at /home/brandon/servo/components/servo/lib.rs:209
#31 0x00005555559aa6d7 in servo::main () at /home/brandon/servo/components/servo/main.rs:154
#32 0x000055555a902d7b in panic_unwind::__rust_maybe_catch_panic ()
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
#33 0x000055555a8f973b in try<(),fn()> ()
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
#34 catch_unwind<fn(),()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
#35 std::rt::lang_start () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
#36 0x00005555559b2054 in main ()
```

**Comment by jdm** [comment]
Any suggestions @glennw?

**Comment by glennw** [comment]
@jdm Yup, this a graphics driver crash! :) It's possible we have a bug somewhere, but I'm not seeing this on any other driver, and apitrace (our graphics debug trace tool) is warning / error free at the moment (in terms of GL API errors). So my suspicion would be a driver bug - I'd suggest checking what version of nouveau is being used and seeing if any updates are available.

**Comment by mrobinson** [comment]
@nerith are you still seeing this issue?

**Comment by mrobinson** [comment]
Okay. I think it is fine to close this for now and we can open a new issue if it reappears.
