### ISSUE TITLE
Servo fails browsing https://github.com/

### ISSUE THREAD

**Issue by kpp** [servo/servo#13963]
I ran `./servo --debug wr-stats --gpu --webrender --pref dom.mozbrowser.enabled`
1.  https://github.com/servo/servo/ then https://github.com/servo/servo/watchers then https://github.com/BrendanEich then https://avatars1.githubusercontent.com/u/313317?v=3&s=400 . I entered Backspace then  ESC and servo failed:

```
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }
```
1. https://github.com/servo/servo/graphs/contributors then https://github.com/servo/servo/pulse then https://github.com/servo/servo/graphs/contributors

```
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-b204f258a370e0f57a8050c0e1ea5305b3f7929512a15a96ce81a65d52e2f448.js:5:18611 history.replaceState is not a function
ERROR:script::dom::bindings::error: Error at https://assets-cdn.github.com/assets/frameworks-b204f258a370e0f57a8050c0e1ea5305b3f7929512a15a96ce81a65d52e2f448.js:5:18611 history.replaceState is not a function
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(4) }"
stack backtrace:
   0:     0x559dec2e232d - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:     0x559dec2e29b2 - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:     0x559deadafa04 - servo::install_crash_handler::handler::hbcbca0a8e3e6b31d
   3:     0x559dec086a83 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   4:     0x7f433cd7a3cf - <unknown>
   5:     0x559debc52253 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfriendapi.cpp:357
   6:     0x559deb630d55 - _<script..fetch..FetchContext as net_traits..FetchResponseListener>::process_response::h9f7a711bfee09896
   7:     0x559deb639bbe - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h4dc5103ef4cbf9b8
   8:     0x559deb65ccc1 - script::script_thread::ScriptThread::handle_msg_from_script::h72550f18e95a8345
   9:     0x559deb80058a - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::hc8566e6311f03cd5
  10:     0x559deb6503c4 - script::script_thread::ScriptThread::handle_msgs::h56e53fd0cad830a2
  11:     0x559deb298007 - std::panicking::try::do_call::ha163e94fada5de71
  12:     0x559dec9d5a26 - __rust_maybe_catch_panic
  13:     0x559deb3984a4 - _<F as alloc..boxed..FnBox<A>>::call_box::hbb276f12439e38ec
  14:     0x559dec9cba20 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  15:     0x7f433cd706f9 - start_thread
  16:     0x7f433c890b5c - clone
  17:                0x0 - <unknown>
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(4) }"
stack backtrace:
   0:     0x559dec2e232d - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:     0x559dec2e29b2 - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:     0x559deadafa04 - servo::install_crash_handler::handler::hbcbca0a8e3e6b31d
   3:     0x7f433c7bf49f - <unknown>
   4:     0x559deadafa8f - servo::install_crash_handler::handler::hbcbca0a8e3e6b31d
   5:     0x559dec086a83 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   6:     0x7f433cd7a3cf - <unknown>
   7:     0x559debc52253 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfriendapi.cpp:357
   8:     0x559deb630d55 - _<script..fetch..FetchContext as net_traits..FetchResponseListener>::process_response::h9f7a711bfee09896
   9:     0x559deb639bbe - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h4dc5103ef4cbf9b8
  10:     0x559deb65ccc1 - script::script_thread::ScriptThread::handle_msg_from_script::h72550f18e95a8345
  11:     0x559deb80058a - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::hc8566e6311f03cd5
  12:     0x559deb6503c4 - script::script_thread::ScriptThread::handle_msgs::h56e53fd0cad830a2
  13:     0x559deb298007 - std::panicking::try::do_call::ha163e94fada5de71
  14:     0x559dec9d5a26 - __rust_maybe_catch_panic
  15:     0x559deb3984a4 - _<F as alloc..boxed..FnBox<A>>::call_box::hbb276f12439e38ec
  16:     0x559dec9cba20 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  17:     0x7f433cd706f9 - start_thread
  18:     0x7f433c890b5c - clone
  19:                0x0 - <unknown>
Illegal instruction (core dumped)
```

The second time the traceback was the same.

```
~/Downloads/servo$ stat core
  File: 'core'
  Size: 1267089408  Blocks: 2474792    IO Block: 4096   regular file
Device: 801h/2049d  Inode: 9577527     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/  humbug)   Gid: ( 1000/  humbug)
Access: 2016-10-28 19:15:57.005587695 +0300
Modify: 2016-10-28 19:13:17.952525905 +0300
Change: 2016-10-28 19:13:17.952525905 +0300
 Birth: -
```

Well, I may provide you the core, but... eh, 1.3GB...

**Comment by kpp** [comment]
```
$ ./servo --version
Servo 0.0.1-b489ba0
```

**Comment by notriddle** [comment]
Aren't you not supposed to run with --gpu and --webrender at the same time?

**Comment by kpp** [comment]
Aren't you supposed to check args? =)

**Comment by kvark** [comment]
I'm getting the same stack when doing the following:
  1. `./mach run --release https://github.com/servo/servo -Z wr-stats`
  2. maximize the window
  3. move the mouse and/or scroll

**Comment by kpp** [comment]
Hello, it's me
I was wondering if after all these years you'd like to meet

**Comment by kpp** [comment]
@kvark your case is fixed

**Comment by kpp** [comment]
My case is fixed too
