### ISSUE TITLE
Error at https://assets-cdn.github.com/assets/frameworks-35b9c541d341309b930b1c790fa1b27a30c7c44ce10c7f8242890e3d83c8adbd.js:5:19757 No such property on self-hosted object: window.fetch(...)

### ISSUE THREAD

**Issue by moimael** [servo/servo#14011]
Error at https://assets-cdn.github.com/assets/frameworks-35b9c541d341309b930b1c790fa1b27a30c7c44ce10c7f8242890e3d83c8adbd.js:5:19757 No such property on self-hosted object: window.fetch(...)
### Servo Version:
Servo 0.0.1-291f393
### Backtrace:
```

WARNING: <Constellation>: creating replacement pipeline for about:failure
ERROR: Error at https://assets-cdn.github.com/assets/frameworks-35b9c541d341309b930b1c790fa1b27a30c7c44ce10c7f8242890e3d83c8adbd.js:5:19757 No such property on self-hosted object: window.fetch(...)

stack backtrace:
   0:     0x55fbfcad359d - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:     0x55fbfcad3c22 - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:     0x55fbfc1d2354 - constellation::constellation::log_entry::ha407f45c8fa63347
   3:     0x55fbfc1d12e0 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h8bac1706cd9f1c8e
   4:     0x55fbfd00268f - log::__log::hf7539da7e3bbacdb
   5:     0x55fbfbcb5abd - script::dom::bindings::error::report_pending_exception::h63922244d6b6a14e
   6:     0x55fbfbf5d75d - script::dom::bindings::codegen::Bindings::EventListenerBinding::EventListener::HandleEvent_::h202ac8f17d5be4e6
   7:     0x55fbfbd40e56 - script::dom::eventdispatcher::handle_event::h2f7726f4494c6742
   8:     0x55fbfbd43635 - script::dom::eventdispatcher::invoke::ha718f6d6331cc640
   9:     0x55fbfbd42887 - script::dom::eventdispatcher::dispatch_event::h55a278d866421a77
  10:     0x55fbfbd53a42 - script::dom::globalscope::GlobalScope::report_an_error::h666a6b3da7b2843c
  11:     0x55fbfbcb5b2d - script::dom::bindings::error::report_pending_exception::h63922244d6b6a14e
  12:     0x55fbfbd542a9 - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::hd8b6236b4d3944ec
  13:     0x55fbfbdb96ac - script::dom::htmlscriptelement::HTMLScriptElement::execute::h9ca34bf4cf096806
  14:     0x55fbfbd07f68 - script::dom::document::Document::finish_load::h9adb8658d8a24d8b
  15:     0x55fbfbda4af4 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..FetchResponseListener>::process_response_eof::hc1e69cc18634a218
  16:     0x55fbfbeac17e - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h02e20ae0fe4c5c28
  17:     0x55fbfbeb431f - _<script..script_thread..CancellableRunnable<T> as script..script_thread..Runnable>::handler::h56f1d4f678dd23d9
  18:     0x55fbfbecfb51 - script::script_thread::ScriptThread::handle_msg_from_script::h11e12fecde38654b
  19:     0x55fbfc07369a - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h076140574a9b997b
  20:     0x55fbfbec30b4 - script::script_thread::ScriptThread::handle_msgs::h93138398ae41bf22
  21:     0x55fbfba39fb7 - std::panicking::try::do_call::h1afdd9b485ceba8d
  22:     0x55fbfd099a9a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  23:     0x55fbfbc01de4 - _<F as alloc..boxed..FnBox<A>>::call_box::h0a6a44c729eced13
  24:     0x55fbfd08f9b4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/common/thread.rs:21
                         - std::sys::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  25:     0x7f4f037c46c9 - start_thread
  26:     0x7f4f032e7f6e - clone
  27:                0x0 - <unknown>
```
This report was generated by the browser.html issue reporter.

**Comment by Manishearth** [comment]
cc @asajeffrey

**Comment by jdm** [comment]
Wait, if report_pending_exception uses error!, does that cause us to capture a backtrace? I thought we decided not to do that.

**Comment by nox** [comment]
I'm not sure I understand what this issue is about. Could someone give more details so it starts making sense?

**Comment by jdm** [comment]
There's nothing actionable here.
