### ISSUE TITLE
Task failure in DOM method causes segfault

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1423]
With this patch:

``` .diff
diff --git a/src/components/script/dom/window.rs b/src/components/script/dom/window.rs
index 9f55e3c..9c4450c 100644
--- a/src/components/script/dom/window.rs
+++ b/src/components/script/dom/window.rs
@@ -106,6 +106,8 @@ impl Window {
     }

     pub fn Stop(&self) {
+        // Used for testing task failure
+        fail!("not implemented!");
     }

     pub fn Focus(&self) {
```

a page which calls `window.stop()` produces this result:

```
$ gdb --args ./servo ../src/test/html/summit-crash.html
Reading symbols from /home/keegan/proj/servo/servo/build.debug/servo...done.
(gdb) run
Starting program: /home/keegan/proj/servo/servo/build.debug/servo ../src/test/html/summit-crash.html
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7f69700 (LWP 15706)]
[New Thread 0x7fffee39c700 (LWP 15707)]
[New Thread 0x7fffedeca700 (LWP 15708)]
[New Thread 0x7fffee29b700 (LWP 15709)]
[New Thread 0x7fffeddc9700 (LWP 15710)]
[New Thread 0x7fffed5c8700 (LWP 15711)]
[New Thread 0x7fffecdc7700 (LWP 15712)]
[New Thread 0x7fffe7fff700 (LWP 15713)]
[New Thread 0x7fffee19a700 (LWP 15714)]
[New Thread 0x7fffee02e700 (LWP 15717)]
task '<unnamed>' failed at 'not implemented!', /home/keegan/proj/servo/servo/src/components/script/dom/window.rs:110
Assertion failure: !seg_, at /home/keegan/proj/servo/servo/src/support/spidermonkey/mozjs/js/src/vm/Stack.cpp:849

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee02e700 (LWP 15717)]
0x00007ffff38b4a44 in js::ContextStack::~ContextStack (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/keegan/proj/servo/servo/src/support/spidermonkey/mozjs/js/src/vm/Stack.cpp:849
849         JS_ASSERT(!seg_);
(gdb) bt
#0  0x00007ffff38b4a44 in js::ContextStack::~ContextStack (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/keegan/proj/servo/servo/src/support/spidermonkey/mozjs/js/src/vm/Stack.cpp:849
#1  0x00007ffff36cad5b in delete_<JSContext> (p=0x20b1210) at ./dist/include/js/Utility.h:616
#2  js::DestroyContext (cx=0x20b1210, mode=<optimized out>)
    at /home/keegan/proj/servo/servo/src/support/spidermonkey/mozjs/js/src/jscntxt.cpp:400
#3  0x00007ffff364e8e5 in js::rust::Drop$Cx::drop ()
    at /home/keegan/proj/servo/servo/src/support/spidermonkey/rust-mozjs/rust.rs:104
#4  0x00007ffff364e9bd in rust..Cx::glue_drop::hd80d455e99af4aP ()
    at /home/keegan/proj/servo/servo/src/support/spidermonkey/rust-mozjs/rust.rs:110
#5  0x00007ffff777420a in cleanup::annihilate::h82984335c95fdd5aO::v0.9$x2dpre ()
   from /home/keegan/proj/servo/servo/build.debug/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.9-pre.so
#6  0x00007ffff77816b9 in rt::task::__extensions__::run::anon::anon::expr_fn::ar ()
   from /home/keegan/proj/servo/servo/build.debug/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.9-pre.so
#7  0x00007ffff7781617 in rt::task::__extensions__::run::anon::expr_fn::aq ()
   from /home/keegan/proj/servo/servo/build.debug/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.9-pre.so
#8  0x00007ffff0ad4583 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>)
    at /home/keegan/proj/servo/servo/src/compiler/rust/src/rt/rust_builtin.cpp:483
#9  0x00007ffff7781317 in rt::task::Task::run::h199ab8d6eb2269804van::v0.9$x2dpre ()
   from /home/keegan/proj/servo/servo/build.debug/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.9-pre.so
#10 0x00007ffff778311a in rt::task::__extensions__::build_start_wrapper::anon::expr_fn::ah ()
   from /home/keegan/proj/servo/servo/build.debug/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.9-pre.so
#11 0x0000000000000000 in ?? ()            
```

**Comment by dralley** [comment]
Is this still applicable?

**Comment by jdm** [comment]
Nope; we added code that catches rust panics from all C callbacks.
