### ISSUE TITLE
Layout attached to empty script thread

### ISSUE THREAD

**Issue by jdm** [servo/servo#14573]
```
(gdb) bt
#0  std::panicking::rust_panic () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:482
#1  0x000055555af77a8d in std::panicking::rust_panic_with_hook () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:467
#2  0x0000555556e17aa4 in std::panicking::begin_panic<&str> (msg="Layout attached to empty script thread.", 
    file_line=0x55555d259d68 <script::script_thread::ScriptThread::handle_new_layout::_FILE_LINE::h3c9c3434dc4f0469>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
#3  0x0000555557e19c1a in script::script_thread::{{impl}}::handle_new_layout (self=0x7fffda5fc320, new_layout_info=NewLayoutInfo = {...}) at /home/jdm/master-servo/components/script/script_thread.rs:1227
#4  0x0000555557e0fd36 in script::script_thread::{{impl}}::handle_msgs::{{closure}} () at /home/jdm/master-servo/components/script/script_thread.rs:787
#5  0x0000555557e116b8 in script::script_thread::{{impl}}::profile_event<closure,()> (self=0x7fffda5fc320, category=AttachLayout, f=closure = {...})
    at /home/jdm/master-servo/components/script/script_thread.rs:955
#6  0x0000555557e0dad7 in script::script_thread::{{impl}}::handle_msgs (self=0x7fffda5fc320) at /home/jdm/master-servo/components/script/script_thread.rs:786
#7  0x0000555557e0cc0f in script::script_thread::{{impl}}::start (self=0x7fffda5fc320) at /home/jdm/master-servo/components/script/script_thread.rs:712
#8  0x0000555557e08e65 in script::script_thread::{{impl}}::create::{{closure}}::{{closure}} () at /home/jdm/master-servo/components/script/script_thread.rs:550
#9  0x00005555566ecd76 in profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>> (self=0x7fffda5fc598, f=closure = {...}, reporter_name="script-reporter-(1,13)", 
    channel_for_reporter=Sender<script::script_thread::MainThreadScriptMsg> = {...}, msg=0x55555aaef9a0 <msg::constellation_msg::{{impl}}::fmt>) at /home/jdm/master-servo/components/profile_traits/mem.rs:63
#10 0x0000555557e09504 in script::script_thread::{{impl}}::create::{{closure}} () at /home/jdm/master-servo/components/script/script_thread.rs:549
#11 0x0000555557a08afb in std::panic::{{impl}}::call_once<(),closure> (self=AssertUnwindSafe<closure> = {...}, _args=0)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:295
#12 0x00005555570db769 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=0x7fffda5fd8a8 "\001")
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
#13 0x000055555af804db in panic_unwind::__rust_maybe_catch_panic () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
#14 0x0000555556ebb2ba in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> (f=AssertUnwindSafe<closure> = {...})
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
#15 0x0000555556defdb5 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=AssertUnwindSafe<closure> = {...})
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
#16 0x0000555556e1733d in std::thread::{{impl}}::spawn::{{closure}}<closure,()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:287
#17 0x000055555771cf6a in alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7fffe9c31300, args=0) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
#18 0x000055555af76695 in alloc::boxed::{{impl}}::call_once<(),()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
#19 std::sys_common::thread::start_thread () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
#20 std::sys::imp::thread::{{impl}}::new::thread_start () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
#21 0x00007ffff60dc70a in start_thread (arg=0x7fffda5ff700) at pthread_create.c:333
#22 0x00007ffff5bfc82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
cc @asajeffrey

**Comment by jdm** [comment]
I hit this in http://doeverything.herokuapp.com/ as well.

**Comment by asajeffrey** [comment]
The fix is to have one layout thread per script thread, as per #14885.

**Comment by nox** [comment]
Just got that on https://github.com/servo/servo/issues/14585#issuecomment-334925113.

**Comment by asajeffrey** [comment]
cc @emilio

**Comment by lumiscosity** [comment]
Appears to have been fixed. All the other linked issues got closed, and both the web archive snapshot from around that time and the latest version of the site run without issue. Tested on Arch Linux x86_64, Servo built against commit 239bdd7c1a12f7bdb5da2c20f4f5226c4a9294e9, profiling and release builds.

<img width="1146" height="899" alt="Image" src="https://github.com/user-attachments/assets/d2c87897-967b-41e8-94f5-ae47d5018a9b" />
