### ISSUE TITLE
Servo freezes when loading firefoxosdevices.org

### ISSUE THREAD

**Issue by cadeyrn** [servo/servo#14585]
The website https://firefoxosdevices.org is not usable with Servo at all. I am using macOS Sierra on a MacBook Pro (Late 2013). I tried the latest download from download.servo.org and I compiled Servo and ran it with ./mach run --release https://firefoxosdevices.org, both with the same result.

Expected result:

Servo renders the website and I can interact with the website. I don't expect that Servo is already able to render all the content, but I expect that Servo keeps responsive.

Actual result:

The website is rendered (except the "main content", that's missing), but Servo is not responsive. If I try to interact with the browser (for example to resize the window) there is the color wheel cursor of macOS and I have to force quit the Servo app.

It's the only website where I experienced this issue.

**Comment by nox** [comment]
```
ERROR:script::dom::bindings::error: Error at https://static.firefoxosdevices.org/themes/v1/js/devices.min.js:1:3170 window.history.replaceState is not a function
Layout attached to empty script thread. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(18)) }, at /Users/nox/src/servo/components/script/script_thread.rs:1475)
ERROR:script::dom::bindings::error: Error at https://visit.pixcept.de/piwik.js:40:1002 R.name is undefined
called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(1)) }, at src/libcore/option.rs:335)
stack backtrace:
   0:        0x1116e7bce - backtrace::backtrace::trace::h4deaa23f6864c795
   1:        0x1116e7c0c - backtrace::capture::Backtrace::new::hf39155232f6fad2f
   2:        0x10fefe858 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h3023a96334b3df52
   3:        0x111f2f731 - std::panicking::rust_panic_with_hook::h05e8a0383ee0c802
   4:        0x1102281e7 - std::panicking::begin_panic::h0af4fe52c6d6297b
   5:        0x11096cc26 - script::script_thread::ScriptThread::handle_new_layout::h6b0d80587469759b
   6:        0x1109563a1 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h341c04664312dde8
   7:        0x110951859 - script::script_thread::ScriptThread::handle_msgs::h92503965c793a551
   8:        0x11021cc47 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19d762cf1405eade
   9:        0x110283b8d - std::panicking::try::do_call::h2c7f3cb7bcc22fe3
  10:        0x111f3c52c - __rust_maybe_catch_panic
  11:        0x1105367d5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h196ca7e35ca94080
  12:        0x111f2e47b - std::sys::imp::thread::Thread::new::thread_start::h41434eeaf172e345
  13:     0x7fffe7e1093a - _pthread_body
  14:     0x7fffe7e10886 - _pthread_start
ERROR:servo: Layout attached to empty script thread.
stack backtrace:
   0:        0x1116e7bce - backtrace::backtrace::trace::h4deaa23f6864c795
   1:        0x1116e7c0c - backtrace::capture::Backtrace::new::hf39155232f6fad2f
   2:        0x10fefe858 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h3023a96334b3df52
   3:        0x111f2f731 - std::panicking::rust_panic_with_hook::h05e8a0383ee0c802
   4:        0x111f2f554 - std::panicking::begin_panic::h8458afd2e16a71ef
   5:        0x111f2f4a2 - std::panicking::begin_panic_fmt::h2b834632d88b17d0
   6:        0x111f2f40a - rust_begin_unwind
   7:        0x111f69033 - core::panicking::panic_fmt::hd956809ba5b6e0c9
   8:        0x111f68f36 - core::panicking::panic::h06eacc5100a91a88
   9:        0x110239420 - std::panicking::try::do_call::h082633af323154f2
  10:        0x111f3c52c - __rust_maybe_catch_panic
  11:        0x110c84c48 - script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::get_window::hb168595f7137bf1a
  12:        0x1106f1773 - script::dom::bindings::utils::generic_call::h0f3db71b5297328c
  13:        0x11115d5cd - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  14:        0x111181129 - CallGetter(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<js::Shape*>, JS::MutableHandle<JS::Value>)
  15:        0x1111741e8 - js::NativeGetExistingProperty(JSContext*, JS::Handle<JSObject*>, JS::Handle<js::NativeObject*>, JS::Handle<js::Shape*>, JS::MutableHandle<JS::Value>)
  16:        0x11117bd8b - bool js::FetchName<false>(JSContext*, JS::Handle<JSObject*>, JS::Handle<JSObject*>, JS::Handle<js::PropertyName*>, JS::Handle<js::Shape*>, JS::MutableHandle<JS::Value>)
  17:        0x111157f81 - Interpret(JSContext*, js::RunState&)
  18:        0x11114bb43 - js::RunScript(JSContext*, js::RunState&)
  19:        0x11115d656 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  20:        0x11115d815 - js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>)
  21:        0x111089b48 - js::fun_apply(JSContext*, unsigned int, JS::Value*)
  22:        0x11115d5cd - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  23:        0x111157749 - Interpret(JSContext*, js::RunState&)
  24:        0x11114bb43 - js::RunScript(JSContext*, js::RunState&)
  25:        0x11115d656 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  26:        0x11115d815 - js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>)
  27:        0x11110125b - js::Wrapper::call(JSContext*, JS::Handle<JSObject*>, JS::CallArgs const&) const
  28:        0x1110f32bb - js::CrossCompartmentWrapper::call(JSContext*, JS::Handle<JSObject*>, JS::CallArgs const&) const
  29:        0x1110f8943 - js::Proxy::call(JSContext*, JS::Handle<JSObject*>, JS::CallArgs const&)
  30:        0x1110f92b7 - js::proxy_Call(JSContext*, unsigned int, JS::Value*)
  31:        0x11115d725 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  32:        0x11115d815 - js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>)
  33:        0x11103b507 - JS_CallFunctionValue(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>)
  34:        0x110a9d758 - script::dom::bindings::codegen::Bindings::EventListenerBinding::EventListener::HandleEvent::hf0e432220d9f9d9f
  35:        0x110792021 - script::dom::event::invoke::h3c673fe5686e91fd
  36:        0x110791382 - script::dom::event::Event::dispatch::hb1efa2b1d6519b99
  37:        0x1106ac641 - _$LT$T$u20$as$u20$script..task..TaskBox$GT$::run_box::heffa8578d38d654c
  38:        0x11095dee0 - script::script_thread::ScriptThread::handle_msg_from_script::h9eeb70210496a54f
  39:        0x110957302 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h6909c8293498d7aa
  40:        0x110953754 - script::script_thread::ScriptThread::handle_msgs::h92503965c793a551
  41:        0x11021cc47 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19d762cf1405eade
  42:        0x110283b8d - std::panicking::try::do_call::h2c7f3cb7bcc22fe3
  43:        0x111f3c52c - __rust_maybe_catch_panic
  44:        0x1105367d5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h196ca7e35ca94080
  45:        0x111f2e47b - std::sys::imp::thread::Thread::new::thread_start::h41434eeaf172e345
  46:     0x7fffe7e1093a - _pthread_body
  47:     0x7fffe7e10886 - _pthread_start
ERROR:servo: called `Option::unwrap()` on a `None` value
ERROR:constellation::constellation: about:failure failed
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(1)) }"
stack backtrace:
   0:        0x1116e7bce - backtrace::backtrace::trace::h4deaa23f6864c795
   1:        0x1116e7c0c - backtrace::capture::Backtrace::new::hf39155232f6fad2f
   2:        0x10fefad81 - servo::install_crash_handler::handler::h79f0b9ac6d887552
   3:     0x7fffe7e06b39 - _sigtramp
   4:        0x1106e8f1b - script::dom::bindings::refcounted::remove_nulls::h378a096816579129
   5:        0x1106e90f9 - script::dom::bindings::refcounted::trace_refcounted_objects::hd3481bf9e6d508b3
   6:        0x1112abf91 - js::gc::GCRuntime::markRuntime(JSTracer*, js::gc::GCRuntime::TraceOrMarkRuntime, js::AutoLockForExclusiveAccess&)
   7:        0x111098f58 - js::gc::GCRuntime::beginMarkPhase(JS::gcreason::Reason, js::AutoLockForExclusiveAccess&)
   8:        0x11109ece0 - js::gc::GCRuntime::incrementalCollectSlice(js::SliceBudget&, JS::gcreason::Reason, js::AutoLockForExclusiveAccess&)
   9:        0x11109f639 - js::gc::GCRuntime::gcCycle(bool, js::SliceBudget&, JS::gcreason::Reason)
  10:        0x11109fb6d - js::gc::GCRuntime::collect(bool, js::SliceBudget, JS::gcreason::Reason)
  11:        0x11109fe70 - js::gc::GCRuntime::gc(JSGCInvocationKind, JS::gcreason::Reason)
  12:        0x111193347 - __rust_maybe_catch_panice()
  13:        0x111061913 - js::DestroyContext(JSContext*)
  14:        0x110cdd860 - _$LT$js..rust..Runtime$u20$as$u20$core..ops..drop..Drop$GT$::drop::h5f06478080917d2f
  15:        0x1105011a1 - core::ptr::drop_in_place::hca395466e9494669
  16:        0x11021d522 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19d762cf1405eade
  17:        0x110283b8d - std::panicking::try::do_call::h2c7f3cb7bcc22fe3
  18:        0x111f3c52c - __rust_maybe_catch_panic
  19:        0x1105367d5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h196ca7e35ca94080
  20:        0x111f2e47b - std::sys::imp::thread::Thread::new::thread_start::h41434eeaf172e345
  21:     0x7fffe7e1093a - _pthread_body
  22:     0x7fffe7e10886 - _pthread_start
```

**Comment by lumiscosity** [comment]
Runs with no errors now, but uses 100% of the CPU and fails to load any images past the first 6. Tested on Arch Linux x86_64, Servo built against commit 239bdd7c1a12f7bdb5da2c20f4f5226c4a9294e9, profiling and release builds.

<img width="1785" height="995" alt="Image" src="https://github.com/user-attachments/assets/0b0b8716-a79f-4906-a99e-5021e32e3a08" />

**Comment by arihant2math** [comment]
@lumiscosity the whole page works for me at around 10-15% CPU.

I used:
```
./servo --pref dom_indexeddb_enabled --enable-experimental-web-platform-features --pref dom_abort_controller_enabled
```
Although I suspect abort_controller and indexeddb are unused.

**Comment by lumiscosity** [comment]
Tested it again myself and can confirm that it works fine on dev and release now even without the extra prefs, so this can be closed.
