### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by sexwork** [servo/servo#14713]
assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-b13afcc
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(6), index: PipelineIndex(6) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(6), index: PipelineIndex(6) }>: Error at https://static.xx.fbcdn.net/rsrc.php/v3iSgH4/yC/l/en_US/i-u7L8opqbV.js:31:58 missing } after function body
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(6), index: PipelineIndex(6) }>: Error at https://static.xx.fbcdn.net/rsrc.php/v3iSgH4/yC/l/en_US/i-u7L8opqbV.js:31:58 missing } after function body
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: error loading script Internal("Network error")
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: error loading script Internal("Network error")
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: error loading script Internal("Network error")
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: error loading script Internal("Network error")
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNam
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment]
This is tracked in #13716. Thanks for reporting it!
