### ISSUE TITLE
http_loader::test_redirected_request_to_devtools intermittently fails

### ISSUE THREAD

**Issue by emilio** [servo/servo#14774]
```
failures:

---- http_loader::test_redirected_request_to_devtools stdout ----
	thread 'http_loader::test_redirected_request_to_devtools' panicked at 'assertion failed: devhttprequest.method == Method::Post', /home/servo/buildbot/slave/linux-dev/build/tests/unit/net/http_loader.rs:338
stack backtrace:
   1:     0x7fa0e3fdbb4a - std::sys::imp::backtrace::tracing::imp::write::h0d1aacfb8fc693ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fa0e3fdf78f - std::panicking::default_hook::{{closure}}::hff87359baf5754d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7fa0e3fdf32d - std::panicking::default_hook::h936f17ca3b2b98dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:359
   4:     0x7fa0e3fdfc37 - std::panicking::rust_panic_with_hook::he9c830ab830c7944
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7fa0e378f7c3 - std::panicking::begin_panic::h5c957cdcf99f7784
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7fa0e3972413 - net_tests::http_loader::test_redirected_request_to_devtools::h0555d8bac971f226
                        at /home/servo/buildbot/slave/linux-dev/build/tests/unit/net/http_loader.rs:338
   7:     0x7fa0e3d2cace - <F as test::FnBox<T>>::call_box::h9d5d1c989d8bcaca
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:1349
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:140
   8:     0x7fa0e3fe6c1a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
   9:     0x7fa0e3d20f13 - std::panicking::try::do_call::hcd637ba157053f5e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:1294
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  10:     0x7fa0e3fe6c1a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  11:     0x7fa0e3d27932 - <F as alloc::boxed::FnBox<A>>::call_box::hcb1afa4b102a7729
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  12:     0x7fa0e3fdea84 - std::sys::imp::thread::Thread::new::thread_start::h1fa04983ba2271d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  13:     0x7fa0e2703183 - start_thread
  14:     0x7fa0e221a37c - clone
  15:                0x0 - <unknown>


failures:
    http_loader::test_redirected_request_to_devtools

test result: FAILED. 412 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by nox** [comment]
This happened once, last year. Closing.

**Comment by jdm** [comment]
This appeared again in an totally unrelated PR. This is quite mysterious.

**Comment by jdm** [comment]
More specifically:
```
---- http_loader::test_redirected_request_to_devtools stdout ----
	thread 'http_loader::test_redirected_request_to_devtools' panicked at 'assertion failed: `(left == right)`
  left: `Get`,
 right: `Post`', components/net/tests/http_loader.rs:346:5
```

**Comment by paulrouget** [comment]
happened here as well: https://travis-ci.org/servo/servo/jobs/335513847

**Comment by mrobinson** [comment]
I haven't ever seen this one.
