### ISSUE TITLE
b.style is undefined using GreenSock-JS (missing SVG functionality)

### ISSUE THREAD

**Issue by jdm** [servo/servo#14779]
Before hitting #14480, http://universidad.continental.edu.pe/ shows this JS error:
```
ERROR:script::dom::bindings::error: Error at http://ucontinental.edu.pe/web/wp-content/plugins/revslider/public/assets/js/jquery.themepunch.tools.min.js:104:15909 b.style is undefined
```
This corresponds to `b.style[Da]="50% 50%"` from the minified JS, which I tracked down to https://github.com/greensock/GreenSock-JS/blob/94c5d3100f78656c3a336ff1080ce22fba63394d/src/uncompressed/TweenMax.js#L3720 in the unminified original source of GreenSock. This gives us:
```js
_createSVG = function(type, container, attributes) {
    var element = _doc.createElementNS("http://www.w3.org/2000/svg", type),
    reg = /([a-z])([A-Z])/g, p;
    for (p in attributes) {
        element.setAttributeNS(null, p.replace(reg, "$1-$2").toLowerCase(), attributes[p]);
    }
    container.appendChild(element);
    return element;
};

svg = _createSVG("svg", _docElement);
rect = _createSVG("rect", svg, {width:100, height:50, x:100});
rect.style[_transformOriginProp] = "50% 50%";
```
We always return an Element object here, which doesn't have a style attribute. If we had real SVG element interfaces they would include a style attribute per the spec.

**Comment by charlesvdv** [comment]
I'm interested to try this one.

**Comment by charlesvdv** [comment]
Ah ok ! Sorry about that!

**Comment by nox** [comment]
This still happens.

**Comment by jdm** [comment]
This also affects youtube.

**Comment by CYBAI** [comment]
Without enabling svg, I will get the `b.style is undefined` error.

But, with svg enabled, I won't get the undefined style error and get a panic instead.

I think the original issue is fixed by #26789 and we might want to close this one and file a new one for the panic?

<details>

```
→ ./mach run --pref=dom.svg.enabled http://universidad.continental.edu.pe/
JQMIGRATE: Migrate is installed, version 1.4.1
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }, at components/script/dom/document.rs:3720)
   0: backtrace::backtrace::libunwind::trace
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/mod.rs:66
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:49
   2: core::fmt::write
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/fmt/mod.rs:1069
   3: std::io::Write::write_fmt
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/mod.rs:1537
   4: servo::backtrace::print
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:17
   5: servo::main::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/main2.rs:166
   6: std::panicking::rust_panic_with_hook
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:481
   7: rust_begin_unwind
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:385
   8: core::panicking::panic_fmt
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/panicking.rs:89
   9: core::option::expect_none_failed
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/option.rs:1272
  10: core::result::Result<T,E>::unwrap
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/result.rs:1005
  11: script::dom::document::Document::remove_stylesheet
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/document.rs:3720
  12: script::dom::stylesheetlist::StyleSheetListOwner::remove_stylesheet
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/stylesheetlist.rs:51
  13: script::dom::htmlstyleelement::HTMLStyleElement::set_stylesheet
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/htmlstyleelement.rs:144
  14: script::dom::htmlstyleelement::HTMLStyleElement::parse_own_css
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/htmlstyleelement.rs:136
  15: <script::dom::htmlstyleelement::HTMLStyleElement as script::dom::virtualmethods::VirtualMethods>::children_changed
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/htmlstyleelement.rs:185
  16: script::dom::node::Node::insert
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/node.rs:2084
  17: script::dom::node::Node::pre_insert
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/node.rs:1989
  18: <script::dom::node::Node as script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::NodeMethods>::AppendChild
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/node.rs:2617
  19: script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::appendChild::{{closure}}::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/NodeBinding.rs:2010
  20: script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::appendChild::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/NodeBinding.rs:1983
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:285
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:318
  23: std::panicking::try::do_call
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  24: ___rust_try
  25: std::panicking::try
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  26: std::panic::catch_unwind
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:394
  27: mozjs::panic::wrap_panic
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/28248e1/src/panic.rs:22
  28: script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::appendChild
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/NodeBinding.rs:1983
  29: CallJitMethodOp
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/28248e1/src/jsglue.cpp:585
  30: script::dom::bindings::utils::generic_call
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/bindings/utils.rs:527
  31: script::dom::bindings::utils::generic_method
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/bindings/utils.rs:543
  32: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:456
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:548
  33: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  34: _ZNK2js22ForwardingProxyHandler4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/proxy/Wrapper.cpp:162
  35: _ZNK2js23CrossCompartmentWrapper4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/proxy/CrossCompartmentWrapper.cpp:237
  36: _ZN2js5Proxy4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/proxy/Proxy.cpp:492
  37: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:522
  38: _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:621
      _ZL9InterpretP9JSContextRN2js8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:3117
  39: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:423
  40: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:589
  41: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  42: _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/JSFunction.cpp:1123
  43: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:456
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:548
  44: _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:621
      _ZL9InterpretP9JSContextRN2js8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:3117
  45: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:423
  46: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:589
  47: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  48: _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/JSFunction.cpp:1123
  49: _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/JSFunction.cpp:1143
  50: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:456
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:548
  51: _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:621
      _ZL9InterpretP9JSContextRN2js8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:3117
  52: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:423
  53: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:589
  54: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  55: _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/jsapi.cpp:2689
  56: mozjs::rust::wrappers::JS_CallFunctionValue
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/28248e1/src/rust.rs:1453
  57: script::dom::bindings::codegen::Bindings::FunctionBinding::Function::Call
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/FunctionBinding.rs:321
  58: script::dom::bindings::codegen::Bindings::FunctionBinding::Function::Call_
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/FunctionBinding.rs:293
  59: script::timers::JsTimerTask::invoke
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/timers.rs:541
  60: script::timers::OneshotTimerCallback::invoke
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/timers.rs:87
  61: script::timers::OneshotTimers::fire_timer
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/timers.rs:222
  62: script::dom::globalscope::GlobalScope::fire_timer
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/globalscope.rs:2653
  63: script::dom::globalscope::TimerListener::handle::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/globalscope.rs:473
  64: core::ops::function::FnOnce::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  65: <script::dom::globalscope::TimerListener::handle::timer_event<F> as script::task::TaskOnce>::run_once
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/task.rs:24
  66: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/task.rs:116
  67: <T as script::task::TaskBox>::run_box
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/task.rs:57
  68: script::script_thread::ScriptThread::handle_msg_from_script
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1975
  69: script::script_thread::ScriptThread::handle_msgs::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1540
  70: script::script_thread::ScriptThread::profile_event
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1784
  71: script::script_thread::ScriptThread::handle_msgs
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1533
  72: script::script_thread::ScriptThread::start
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1356
  73: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:796
  74: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /Volumes/Transcend/codespace/mozilla/servo/components/profile_traits/mem.rs:88
  75: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:794
  76: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  77: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  78: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:318
  79: std::panicking::try::do_call
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  80: ___rust_try
  81: std::panicking::try
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  82: std::panic::catch_unwind
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:394
  83: std::thread::Builder::spawn_unchecked::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
  84: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  85: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/sys/unix/thread.rs:87
  86: __pthread_body
  87: __pthread_start
[2020-06-18T13:48:26Z ERROR servo] called `Result::unwrap()` on an `Err` value: "SendError(..)"
```

</details>

**Comment by jdm** [comment]
I still see the original error:
```
[2020-06-18T13:57:32Z ERROR script::dom::bindings::error] Error at https://ucontinental.edu.pe/www/wp-content/plugins/revslider/public/assets/js/jquery.themepunch.tools.min.js:103:16011 b.style is undefined
```

**Comment by jdm** [comment]
Oh, you're right, enabling SVG does change things. I agree!
