### ISSUE TITLE
Crash while building master on Windows 7

### ISSUE THREAD

**Issue by dcci** [servo/servo#15554]
```
[...]
Reexecuting in the virtualenv
checking for a shell... D:/fun/servo/.servo/msvc-dependencies/moztools/0.0.1-5/bin/sh.exe
checking for host system type... x86_64-pc-mingw32
checking for target system type... x86_64-pc-mingw32
checking for the Android toolchain directory... not found
checking whether cross compiling... no
checking for pkg_config... c:/Strawberry/perl/bin/pkg-config
checking for pkg-config version...
INFO: checking for a shell...
INFO: D:/fun/servo/.servo/msvc-dependencies/moztools/0.0.1-5/bin/sh.exe
INFO: checking for host system type...
INFO: x86_64-pc-mingw32
INFO: checking for target system type...
INFO: x86_64-pc-mingw32
INFO: checking for the Android toolchain directory...
INFO: not found
INFO: checking whether cross compiling...
INFO: no
INFO: checking for pkg_config...
DEBUG: pkg_config: Trying pkg-config
INFO: c:/Strawberry/perl/bin/pkg-config
INFO: checking for pkg-config version...
DEBUG: Executing: `c:/Strawberry/perl/bin/pkg-config --version`
makefile.cargo:119: recipe for target 'maybe-configure' failed

--- stderr
gmake: *** No targets specified and no makefile found.  Stop.
DEBUG: Executing: `c:/Strawberry/perl/bin/pkg-config --version`
Traceback (most recent call last):
  File "d:/fun/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/js/src/../../configure.py", line 93, in <module>
    sys.exit(main(sys.argv))
  File "d:/fun/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/js/src/../../configure.py", line 22, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 260, in run
    func(*args)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 302, in _value_for
    return self._value_for_depends(obj)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\util.py", line 922, in method_call
    cache[args] = self.func(instance, *args)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 329, in _value_for_depends
    return func(*resolved_args)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "d:/fun/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/build/moz.configure/util.configure", line 158, in wrapper
    return func(*args)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 518, in wrapper
    ret = template(*args, **kwargs)
  File "d:/fun/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/build/moz.configure/checks.configure", line 53, in wrapped
    ret = func(*args, **kwargs)
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "d:/fun/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/build/moz.configure/pkg.configure", line 13, in pkg_config_version
    return Version(check_cmd_output(pkg_config, '--version').rstrip())
  File "d:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "d:/fun/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/build/moz.configure/util.configure", line 35, in check_cmd_output
    stderr=subprocess.PIPE)
  File "C:\Python27\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
mozmake: *** [maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', D:\fun\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\7cd72d8\build.rs:43
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Please let me know if you need other infos.

**Comment by dcci** [comment]
Any hints on how to debug this one?

**Comment by dcci** [comment]
The issue here is that Strawberry perl provides a Perl module which gets exported to PATH, so when the python script tries to execute `pkg-config` it gets the "wrong" one:

```
$ file C:/Strawberry/perl/bin/pkg-config
C:/Strawberry/perl/bin/pkg-config: Perl5 module source, ASCII text
```

For now I worked around this temporarily renaming `pkg-config` but ideally we should be able to emit a better diagnostic for this case (I'll open a bug upstream)

**Comment by dcci** [comment]
There's a discussion here:  https://bugzilla.mozilla.org/show_bug.cgi?id=513617

**Comment by tigercosmos** [comment]
not support 32 bit.

**Comment by mrobinson** [comment]
Closing this since a lot of time has passed and the upstream bug is fixed.
