### ISSUE TITLE
Content test failure when sending ResizeMsg

### ISSUE THREAD

**Issue by jdm** [servo/servo#1588]
Seen in test_prototypes.html; easiest to reproduce with `./servo ../src/test/html/content/test_prototypes.html run` (skip the first failure that occurs because there's no `run` file available).

Sending ResizeMsg from handle_resized_window_msg to a closed script channel:
```
#0  0x00007ffff7987810 in rust_fail ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#1  0x00007ffff78e4558 in rt::unwind::Unwinder::begin_unwind::hd890d6617f8679e9HCaO::v0.9 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#2  0x0000000000438e4e in rt::unwind::begin_unwind::h9db4a7f21e18372aaw::v0.0 () at /home/jdm/sdb/servo/src/components/main/compositing/compositor_layer.rs:143
#3  0x0000000000475230 in send_mouse_event () at /home/jdm/sdb/servo/src/components/main/compositing/compositor_layer.rs:252
#4  handle_resized_window_msg () at /home/jdm/sdb/servo/src/components/main/constellation.rs:759
#5  servo::constellation::Constellation::handle_request () at /home/jdm/sdb/servo/src/components/main/constellation.rs:360
#6  0x0000000000461743 in run () at /home/jdm/sdb/servo/src/components/main/constellation.rs:287
#7  fn19916 () at /home/jdm/sdb/servo/src/components/main/constellation.rs:279
#8  0x00007ffff763c1f8 in task::__extensions__::build_start_wrapper::anon::anon::expr_fn::a0 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#9  0x00007ffff7983358 in rt::task::__extensions__::run::anon::expr_fn::au ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#10 0x00007ffff798a87c in rust_try () from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#11 0x00007ffff79830fd in rt::task::Task::run::hf7663b6e52130dcbk8aq::v0.9 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#12 0x00007ffff763bc1c in task::__extensions__::build_start_wrapper::anon::expr_fn::aJ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#13 0x0000000000000000 in ?? ()
```

**Comment by jdm** [comment]
We handle missing files now.
