### ISSUE TITLE
Cannot Build on ubuntu 14.04 - Python 2.7.12

### ISSUE THREAD

**Issue by jklepatch** [servo/servo#16525]
I have spent a day trying to build the project on my ubuntu, but no luck. Help would be very much appreciated.

Ubuntu: 14.04
Python: 2.7.12

`./mach build --dev`

```Output: 
Error: Traceback (most recent call last):
  File "/home/jklepatch/servo/python/_virtualenv/bin/pip2.7", line 7, in <module>
    from pip import main
  File "/home/jklepatch/servo/python/_virtualenv/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/home/jklepatch/servo/python/_virtualenv/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/jklepatch/servo/python/_virtualenv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/usr/local/lib/python2.7/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/__init__.py", line 6, in <module>
    from .ssl_ import (
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py", line 4, in <module>
    import hmac
  File "/usr/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
```

**Comment by dralley** [comment]
Can probably be closed?
