### ISSUE TITLE
sporadic segfault/abort with DISPLAY unset

### ISSUE THREAD

**Issue by sp3d** [servo/servo#1669]
It looks like 64b28decd071c1cdb11f6fe3688e42108ecb5469 isn't quite bulletproof. Every so often when starting with no DISPLAY environment variable, Servo crashes (segfault or abort, variously) after calling exit(1).

To reproduce: unset DISPLAY and run `servo http://example.com` several times until it segfaults after printing the two lines about being unable to find an X server. This crash really upset gdb when it was ptracing servo, so I recommend obtaining a core manually--run "ulimit -c unlimited" prior to testing, and invoke gdb like `gdb --core core.nnnn --exec /path/to/servo`.

~~~
Core was generated by `./servo http://example.com/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fad23dab08d in mozalloc_abort(char const*) () from /servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-68f88dae-0.1.so
(gdb) bt
#0  0x00007fad23dab08d in mozalloc_abort(char const*) () from /servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-68f88dae-0.1.so
#1  0x00007fad23dab070 in abort () from /servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-68f88dae-0.1.so
#2  0x00007fad2557fa77 in uv_mutex_lock (mutex=mutex@entry=0x7fad257d28e0 <mutex>) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/thread.c:70
#3  0x00007fad25580284 in post (q=0x7fad0c002df0) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/threadpool.c:87
#4  uv__work_submit (loop=<optimized out>, w=0x7fad0c002dd8, work=work@entry=0x7fad255784c0 <uv__fs_work>, done=done@entry=0x7fad25578200 <uv__fs_done>)
    at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/threadpool.c:164
#5  0x00007fad2557914d in uv_fs_close (loop=<optimized out>, req=<optimized out>, file=<optimized out>, cb=<optimized out>)
    at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/fs.c:714
#6  0x00007fad2555c8f4 in file::execute::h85f0b82517d08613as::v0.9 ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustuv-2ba3695a-0.9.so
#7  0x00007fad2555cba3 in file::execute_nop::h1d4a6d0c04478cacax::v0.9 ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustuv-2ba3695a-0.9.so
#8  0x00007fad25550bbd in file::Drop$FileWatcher::drop::h4bf8de4f1221fe8afxaB::v0.9 ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustuv-2ba3695a-0.9.so
#9  0x00007fad25550ac4 in file..FileWatcher::glue_drop::hbabbcfcfe7aaab90aA ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustuv-2ba3695a-0.9.so
#10 0x00007fad25550a5d in _$UP$file..FileWatcher::glue_free::h5df7ba91c51ac8deaw ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustuv-2ba3695a-0.9.so
#11 0x00007fad25afff76 in rand::task_rng::h601200ec121dff12aQ::v0.9 ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#12 0x00007fad22e8b638 in fn7861 () at /servo/src/components/net/image_cache_task.rs:93
#13 0x00007fad258041c8 in task::__extensions__::build_start_wrapper::anon::anon::expr_fn::a0 ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#14 0x00007fad25b4a348 in rt::task::__extensions__::run::anon::expr_fn::au ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#15 0x00007fad25b5189c in rust_try ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#16 0x00007fad25b4a0ed in rt::task::Task::run::hf7663b6e52130dcbk8aq::v0.9 ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#17 0x00007fad25803bec in task::__extensions__::build_start_wrapper::anon::expr_fn::aJ ()
   from /servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#18 0x0000000000000000 in ?? ()
~~~

Knowing very little about libgreen's internals, my guess would be that it's a bad idea to be using libuv functions after (i.e. temporally, but in a different thread) having called exit().

**Comment by nox** [comment]
libgreen has died a long time ago, closing this.
