### ISSUE TITLE
Run EmberPerf benchmark

### ISSUE THREAD

**Issue by metajack** [servo/servo#16720]
Get EmberPerf working in Servo. EmberPerf is here: http://emberperf.eviltrout.com/

This metabug is specifically just to get it running. Performance issues will be tracked in a separate metabug.

- [ ] ???

Part of #16717.

**Comment by metajack** [comment]
Marking this easy. The task here is to run Servo on this benchmark and file bugs for any errors you find that prevent it from running.

**Comment by jonathandturner** [comment]
Just to note, the latested (2.11.1) EmberPerf benchmark does not run successfully for me on any of the browsers I tested (Nightly Firefox, Chrome, etc).

Do we have a version we're aiming to compare against?

**Comment by metajack** [comment]
@cpeterso Do you know if this is working in Gecko currently?

**Comment by cpeterso** [comment]
The EmberPerf benchmark used to work, but now it stops at "17 test(s) remaining" in Firefox, Edge, and Chrome. I see the following JavaScript error in the devtools console:

```
TypeError: Ember.LinkView is undefined[Learn More] index.js:35:9
setup http://emberperf.eviltrout.com/benchmarks/link-to/active/index.js:35:9
runner http://emberperf.eviltrout.com/assets/test-client.js:265:30
one http://emberperf.eviltrout.com/assets/test-client.js:1209:9
apiLoadAsync/</< http://emberperf.eviltrout.com/assets/test-client.js:1425:25
load/< http://emberperf.eviltrout.com/assets/test-client.js:1461:13process http://emberperf.eviltrout.com/assets/test-client.js:1557:17
```

**Comment by eviltrout** [comment]
Apologies - the Link related tests broke some time ago on newer Ember releases. I've removed them in the latest version and deployed it to `emberperf.eviltrout.com`

**Comment by bnjbvr** [comment]
@eviltrout Hi! As of today, the two following tests are still raising errors on Firefox Nightly and Chromium stable:

- Ember.Component.create
- Render bind-attr

Is there anything to be done with these tests?

**Comment by eviltrout** [comment]
Well that's embarrassing! As you might have figured out by now we don't tend to run all the tests. We somewhat got in the habit of sticking to the Complex List tests since we found them the most reflective of Discourse performance :)

I've removed those tests now and confirmed the suite now runs all tests for the latest versions of Ember.

**Comment by bnjbvr** [comment]
> I've removed those tests now and confirmed the suite now runs all tests for the latest versions of Ember.

Thanks! That's great.

**Comment by mihajlija** [comment]
This is what I get on macOS 10.12.4 when running default settings (2.13.0)

`ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/benchmarks/ember-get/primed/index.js:13:9 Ember is not defined`

The "latest release" test works though [http://imgur.com/jNEc0lW](http://imgur.com/jNEc0lW
) :)

**Comment by eviltrout** [comment]
Is this a servo bug? I just ran the suite with default settings in safari and everything worked.

**Comment by mihajlija** [comment]
@eviltrout Servo I guess, I get the same error when running JetStream benchmark ("JetStream is not defined")

**Comment by jdm** [comment]
I cannot reproduce that JS error when running with the default settings. I have tried a debug build, a release build, and a nightly.

**Comment by jonathandturner** [comment]
I can't see the JS error, but when I run this benchmark, this is what I see:

![screen shot 2017-06-12 at 10 48 19](https://user-images.githubusercontent.com/547158/27015207-c41b2fc0-4f5c-11e7-9170-7bff5842a63e.png)

**Comment by jonathandturner** [comment]
I take that back, if I let it run long enough, I do see: 

```
ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/benchmarks/ember-set/primed/index.js:7:9 Ember is not defined
```

**Comment by jonathandturner** [comment]
As the screenshot suggests, the benchmark doesn't seem to be working the same way as on other browsers, as there doesn't appear to be any status updates as the benchmarks run

**Comment by jonathandturner** [comment]
(apologies for the spamming)

I was able to get a successful run that didn't have the error.  Not sure what causes it to occur, yet.

![screen shot 2017-06-12 at 11 42 45](https://user-images.githubusercontent.com/547158/27015554-49d69ea4-4f64-11e7-944e-4be60c950840.png)

Here's Firefox 53 for comparison:

![screen shot 2017-06-12 at 11 47 49](https://user-images.githubusercontent.com/547158/27015576-fff6ecc0-4f64-11e7-8f17-986d44f8c219.png)

**Comment by jonathandturner** [comment]
I filed a follow-up bug around the EmberPerf performance numbers here: https://github.com/servo/servo/issues/17329

**Comment by tamird** [comment]
Is it time to close this? This issue appears to be about just getting it to run, which @jonathandturner seems to have done.

This issue still appears on [ServoStarters](https://starters.servo.org/).

**Comment by jonathandturner** [comment]
@tamird - I mention in my runs that I was getting errors with some runs and not others.  I'll check and report back whether the intermittent error is still occurring.

**Comment by jonathandturner** [comment]
@tamird - I can confirm we're still seeing the "ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/assets/test-client.js:341:5 Ember is not defined" on some runs (and not others).

@jdm - I don't know how we want to handle intermittent failures.

**Comment by sanjay-swain** [comment]
This seems to be working properly now?

<img width="1282" height="997" alt="Image" src="https://github.com/user-attachments/assets/7da60469-0a49-47d3-b473-c26f6ea80593" />

I am pretty sure this issue and related issue #18618 can be closed

**Comment by jdm** [comment]
Hooray!
