### ISSUE TITLE
build error due to python3 being default version

### ISSUE THREAD

**Issue by plexigras** [servo/servo#17403]
```
$ ./mach build --dev
Traceback (most recent call last):
  File "./mach", line 93, in <module>
    main(sys.argv)
  File "./mach", line 23, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/home/superuser/git/servo/python/mach_bootstrap.py", line 230, in bootstrap
    topdir.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

```
$ python --version 
Python 3.6.1
```

**Comment by lord-re** [comment]
I got the same issue here on gentoo.

**Comment by marmeladema** [comment]
This should be fixed now.
