### ISSUE TITLE
Reddit fails with "Unexpected scheme"

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#17759]
If you open reddit with a recent nightly, leave it open for a few seconds, you see the screen disappear and this message:

<img width="373" alt="screen shot 2017-07-18 at 9 08 37 am" src="https://user-images.githubusercontent.com/547158/28289981-cc120818-6b98-11e7-91c4-ee86b507bdbb.png">

Backtrace:
```
ERROR:script::dom::bindings::error: Error at https://www.redditstatic.com/webcomponents.xriNycXog0M.js:2:10227 MutationObserver is not defined
ERROR:script::dom::bindings::error: Error at https://www.redditstatic.com/webcomponents.xriNycXog0M.js:2:3203 MutationObserver is not defined
Client Error: "ReferenceError: MutationObserver is not defined" thrown at L2:3203 in https://www.redditstatic.com/webcomponents.xriNycXog0M.js Message: "MutationObserver is not defined"
[object Object]
called `Option::unwrap()` on a `None` value (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at src/libcore/option.rs:335)
stack backtrace:
   0:        0x10536bf5e - backtrace::backtrace::trace::hcb1d1c357c61d9f4
   1:        0x10536c0fc - backtrace::capture::Backtrace::new::hde1afc496271e12d
   2:        0x104427e66 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h3eb9c088b479c914
   3:        0x1062f0271 - std::panicking::rust_panic_with_hook::ha0018323eb40c327
   4:        0x1062f0114 - std::panicking::begin_panic_new::hff1de058d2223963
   5:        0x1062effe2 - std::panicking::begin_panic_fmt::ha763a642335ca012
   6:        0x1062eff4a - rust_begin_unwind
   7:        0x10631b133 - core::panicking::panic_fmt::h7df71c4ad7c7f69d
   8:        0x10631b036 - core::panicking::panic::h66a96b2665b91c6a
   9:        0x104654897 - _$LT$layout..fragment..Fragment$u20$as$u20$layout..display_list_builder..FragmentDisplayListBuilding$GT$::build_display_list_for_background_if_applicable::hf9d60592ee9d60ec
  10:        0x10465b8fa - _$LT$layout..fragment..Fragment$u20$as$u20$layout..display_list_builder..FragmentDisplayListBuilding$GT$::build_display_list::h9ebe6e8367909f7a
  11:        0x1046616f9 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..display_list_builder..BlockFlowDisplayListBuilding$GT$::build_display_list_for_block::hd0ca708e64599c4a
  12:        0x104646608 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::build_display_list::h05590c8fa75f5306
  13:        0x1046a5424 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  14:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  15:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  16:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  17:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  18:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  19:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  20:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  21:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  22:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  23:        0x1046a5472 - layout::traversal::BuildDisplayList::traverse::h596bcae680655262
  24:        0x10468d032 - layout::sequential::build_display_list_for_subtree::h03335cb5d2b755ef
  25:        0x1045f441a - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::hc61d4fe45a06b07e
  26:        0x1045ee6e8 - layout_thread::LayoutThread::handle_reflow::h5fe156a7e682385a
  27:        0x1045e094c - layout_thread::LayoutThread::handle_request_helper::h1da08c86168f4be3
  28:        0x1045dab44 - _$LT$layout_thread..LayoutThread$u20$as$u20$layout_traits..LayoutThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h8cbe122edea03b76
  29:        0x104555b87 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f89ddfcd2586eb6
  30:        0x1045581f7 - std::panicking::try::do_call::hf8c5358ab4672f90
  31:        0x1062f140c - __rust_maybe_catch_panic
  32:        0x1045889b3 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h528fbda6651a1bb9
  33:        0x1062ed26b - std::sys::imp::thread::Thread::new::thread_start::h2c57dd454929f4df
  34:     0x7fffe24b993a - _pthread_body
  35:     0x7fffe24b9886 - _pthread_start
ERROR:servo: called `Option::unwrap()` on a `None` value
assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /Users/jturner/Source/servo/components/script/dom/window.rs:1342)
stack backtrace:
   0:        0x10536bf5e - backtrace::backtrace::trace::hcb1d1c357c61d9f4
   1:        0x10536c0fc - backtrace::capture::Backtrace::new::hde1afc496271e12d
   2:        0x104427e66 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h3eb9c088b479c914
   3:        0x1062f0271 - std::panicking::rust_panic_with_hook::ha0018323eb40c327
   4:        0x104872e17 - std::panicking::begin_panic_new::h7704170f0e38d56f
   5:        0x104e78c35 - script::dom::window::Window::reflow::h04adab2fbf46e381
   6:        0x104ce8729 - script::dom::document::Document::finish_load::hb9d873cacb9edd2d
   7:        0x104e06447 - script::dom::servoparser::ServoParser::parse_sync::he7f999a00daa2508
   8:        0x104e049b6 - script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script::h218998ed28f8d79a
   9:        0x104ce90f0 - script::dom::document::Document::process_pending_parsing_blocking_script::he37bbeee0c38cfb4
  10:        0x104ce8e2a - script::dom::document::Document::pending_parsing_blocking_script_loaded::hd60f7cb945d4905c
  11:        0x104d9354e - _$LT$script..dom..htmlscriptelement..ScriptContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::h965b8cd38ba40ddd
  12:        0x104ea9470 - _$LT$script..network_listener..ListenerRunnable$LT$A$C$$u20$Listener$GT$$u20$as$u20$script..script_thread..Runnable$GT$::handler::hc536b3e87159465b
  13:        0x104eadc42 - _$LT$script..script_thread..CancellableRunnable$LT$T$GT$$u20$as$u20$script..script_thread..Runnable$GT$::main_thread_handler::hfaaf448101e77361
  14:        0x104ec73bb - script::script_thread::ScriptThread::handle_msg_from_script::h2c91f302d3dbc830
  15:        0x104ec0c51 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h5f513743e8120ae8
  16:        0x104ebda72 - script::script_thread::ScriptThread::handle_msgs::h5f95bb682ffa510b
  17:        0x104870a77 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7dc19faea7d78e5e
  18:        0x1049ddd0d - std::panicking::try::do_call::hbd1b6d6a21027831
  19:        0x1062f140c - __rust_maybe_catch_panic
  20:        0x104b61405 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::he1564a31ee6ceb95
  21:        0x1062ed26b - std::sys::imp::thread::Thread::new::thread_start::h2c57dd454929f4df
  22:     0x7fffe24b993a - _pthread_body
  23:     0x7fffe24b9886 - _pthread_start
ERROR:servo: assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
ERROR:constellation::constellation: about:failure failed
```

**Comment by jdm** [comment]
When I do it in a debug build, I still see #17176.

**Comment by jdm** [comment]
Which is, in fact, a debug_assert. This is another duplicate, in that case.

**Comment by jonathandturner** [comment]
@jdm - 
Interesting.  Reddit had been working reliably for weeks, so this is either a regression or a change on the reddit site.
