### ISSUE TITLE
servo build error

### ISSUE THREAD

**Issue by Serkan-devel** [servo/servo#18160]
I can't figure out how to build servo.

```
user@host:~/Schreibtisch/servo$ RUST_BACKTRACE=1
user@host:~/Schreibtisch/servo$ ./mach build --dev
   Compiling encoding_index_tests v0.1.4
   Compiling mp3-metadata v0.2.3
   Compiling matches v0.1.4
   Compiling log v0.3.8
   Compiling signpost v0.1.0 (https://github.com/pcwalton/signpost.git#7ed71250)
   Compiling encoding-index-japanese v1.20141219.5
   Compiling utf-8 v0.7.1
   Compiling gamma-lut v0.2.0
   Compiling encoding-index-korean v1.20141219.5
   Compiling owning_ref v0.2.4
   Compiling lazycell v0.4.0
   Compiling khronos_api v1.0.1
   Compiling regex-syntax v0.4.1
   Compiling thread_profiler v0.1.3
   Compiling same-file v0.1.3
   Compiling quote v0.3.15
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#834ce35c)
   Compiling xi-unicode v0.1.0
   Compiling bytes v0.3.0
   Compiling traitobject v0.1.0
   Compiling walkdir v1.0.7
   Compiling error-chain v0.7.2
   Compiling webrender v0.44.0 (https://github.com/servo/webrender#a787f8ee)
   Compiling backtrace-sys v0.1.11
   Compiling semver v0.1.20
   Compiling expat-sys v2.1.4
   Compiling bitflags v0.8.2
   Compiling bitflags v0.7.0
   Compiling void v1.0.2
   Compiling open v1.2.0
   Compiling unreachable v0.1.1
   Compiling debug_unreachable v0.1.1
   Compiling mime v0.2.4
   Compiling rustc_version v0.1.7
   Compiling futf v0.1.3
   Compiling procedural-masquerade v0.1.2
   Compiling tendril v0.3.0
   Compiling unicase v1.4.0
   Compiling pulldown-cmark v0.0.8
   Compiling hyper v0.10.10
   Compiling libloading v0.4.0
   Compiling scoped_threadpool v0.1.7
   Compiling phf_shared v0.7.21
   Compiling phf v0.7.21
   Compiling blurmock v0.1.2
   Compiling servo v0.0.1 (file:///home/user/Schreibtisch/servo/ports/servo)
   Compiling heapsize v0.4.0
   Compiling dtoa v0.4.1
   Compiling alloc-no-stdlib v1.2.0
   Compiling brotli-decompressor v1.0.9
   Compiling odds v0.2.25
   Compiling itoa v0.3.1
   Compiling unicode-xid v0.0.4
   Compiling synom v0.11.3
   Compiling nodrop v0.1.8
   Compiling syn v0.11.11
   Compiling libz-sys v1.0.13
   Compiling arraydeque v0.2.3
   Compiling servo_arc v0.0.1 (file:///home/user/Schreibtisch/servo/components/servo_arc)
   Compiling precomputed-hash v0.1.0
   Compiling smallvec v0.4.0
   Compiling miniz-sys v0.1.9
   Compiling arrayvec v0.3.23
   Compiling language-tags v0.2.2
   Compiling string_cache_shared v0.3.0
   Compiling ref_filter_map v1.0.1
   Compiling xml-rs v0.3.6
   Compiling byteorder v1.0.0
   Compiling ogg v0.5.0
   Compiling deflate v0.7.5
   Compiling gl_generator v0.5.3
   Compiling ogg_metadata v0.4.1
   Compiling base64 v0.5.2
   Compiling mp4parse v0.7.1
   Compiling gleam v0.4.6
   Compiling cssparser v0.16.1
   Compiling synstructure v0.5.2
   Compiling heapsize_derive v0.1.4
   Compiling serde_derive_internals v0.15.1
   Compiling servo-glutin v0.11.0
   Compiling jstraceable_derive v0.0.1 (file:///home/user/Schreibtisch/servo/components/jstraceable_derive)
   Compiling rust-webvr v0.5.0
   Compiling html5ever v0.18.0
   Compiling domobject_derive v0.0.1 (file:///home/user/Schreibtisch/servo/components/domobject_derive)
   Compiling deny_public_fields v0.0.1 (file:///home/user/Schreibtisch/servo/components/deny_public_fields)
   Compiling unicode-segmentation v1.2.0
   Compiling color_quant v1.0.0
   Compiling bit-vec v0.4.3
   Compiling heartbeats-simple-sys v0.4.1
error: failed to run custom build command for `heartbeats-simple-sys v0.4.1`
process didn't exit successfully: `/home/user/Schreibtisch/servo/target/debug/build/heartbeats-simple-sys-8a183e2a06a057db/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/heartbeats-simple-sys-0.4.1/heartbeats-simple" "-DCMAKE_INSTALL_PREFIX=/home/user/Schreibtisch/servo/target/debug/build/heartbeats-simple-sys-9c724f9aec584f18/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:617
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build FAILED in 0:09:30
user@host:~/Schreibtisch/servo$ export RUST_BACKTRACE=1
user@host:~/Schreibtisch/servo$ ./mach build --dev
   Compiling httparse v1.2.1
   Compiling brotli v1.0.8
   Compiling x11-dl v2.14.0
   Compiling rayon-core v1.2.0
   Compiling simd v0.2.0
   Compiling angle v0.2.0 (https://github.com/servo/angle?branch=servo#a1371e8a)
   Compiling metadeps v1.1.1
error: failed to run custom build command for `angle v0.2.0 (https://github.com/servo/angle?branch=servo#a1371e8a)`
process didn't exit successfully: `/home/user/Schreibtisch/servo/target/debug/build/angle-14a70cc66d60c617/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/user/Schreibtisch/servo/.cargo/git/checkouts/angle-017278ddf8240375/a1371e8/." "-DCMAKE_INSTALL_PREFIX=/home/user/Schreibtisch/servo/target/debug/build/angle-924e8f53a584ce62/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:617
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: cmake::fail
             at /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:617
   8: cmake::run
             at /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:592
   9: cmake::Config::build
             at /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:443
  10: build_script_build::main
             at ./build.rs:9
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: main
  14: __libc_start_main
  15: _start

Build failed, waiting for other jobs to finish...
error: build failed
Build FAILED in 0:00:47
user@host:~/Schreibtisch/servo$
```

**Comment by emilio** [comment]
You need to install `cmake`, it's in the build dependencies section in the `README`. Does that fix the error?

**Comment by Serkan-devel** [comment]
Still not but I think it got further after installing it
```
user@host:~/Schreibtisch/servo$ ./mach build --release
   Compiling osmesa-src v17.2.0-devel (https://github.com/servo/osmesa-src#fe47d99a)
   Compiling style v0.0.1 (file:///home/user/Schreibtisch/servo/components/style)
   Compiling smallvec v0.4.0
   Compiling unicase v1.4.0
   Compiling hyper v0.10.10
   Compiling xcb v0.7.7
   Compiling skeptic v0.9.0
   Compiling multistr v0.5.1
   Compiling futf v0.1.3
warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/vec.rs:434:1
    |
434 | pub type SliceVec<T: 'static + Copy> = Dynamic<[T]>;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/user/Schreibtisch/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/multistr-0.5.1/src/array.rs:228:13
    |
228 |               pub type $slice_name<T: 'static + Copy> = $name<[T]>;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
242 | / gen_impl! {
243 | |     Static2, SliceArray2, StringArray2, CStringArray2, OsStringArray2, 2,
244 | |     Static3, SliceArray3, StringArray3, CStringArray3, OsStringArray3, 3,
245 | |     Static4, SliceArray4, StringArray4, CStringArray4, OsStringArray4, 4,
...   |
257 | |     Static16, SliceArray16, StringArray16, CStringArray16, OsStringArray16, 16,
258 | | }
    | |_- in this macro invocation

   Compiling regex v0.2.2
   Compiling heartbeats-simple-sys v0.4.1
   Compiling harfbuzz-sys v0.1.12
   Compiling servo-freetype-sys v4.0.3
   Compiling angle v0.5.0 (https://github.com/servo/angle?branch=servo#c598aafe)
   Compiling expat-sys v2.1.4
   Compiling miniz-sys v0.1.9
   Compiling fontsan v0.3.2 (https://github.com/servo/fontsan#ab68da17)
   Compiling backtrace-sys v0.1.11
   Compiling tinyfiledialogs v2.5.9
   Compiling rayon v0.8.1
   Compiling png v0.6.2
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#834ce35c)
   Compiling libz-sys v1.0.16
   Compiling openssl v0.9.12
   Compiling openssl-sys v0.9.12
   Compiling x11-dl v2.14.0
   Compiling synstructure v0.5.2
   Compiling domobject_derive v0.0.1 (file:///home/user/Schreibtisch/servo/components/domobject_derive)
   Compiling html5ever v0.19.0
   Compiling cssparser v0.19.1
   Compiling serde_derive_internals v0.15.1
   Compiling offscreen_gl_context v0.11.1
   Compiling servo-glutin v0.11.0
   Compiling gleam v0.4.8
   Compiling rust-webvr v0.5.0
   Compiling glx v0.1.2
   Compiling dbus v0.5.3
error: failed to run custom build command for `dbus v0.5.3`
process didn't exit successfully: `/home/user/Schreibtisch/servo/target/release/build/dbus-cda54fe6378942e5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(PkgConfig(Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }), State { next_error: None })', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Build FAILED in 0:13:39
user@host:~/Schreibtisch/servo$
```

**Comment by emilio** [comment]
Sure, you need all the dependencies in https://github.com/servo/servo#on-debian-based-linuxes. That includes libdbus.

**Comment by Serkan-devel** [comment]
it now works but how do I get the browser.html UI?

**Comment by Serkan-devel** [comment]
found it
