### ISSUE TITLE
servo-mac7 is constantly having git errors

### ISSUE THREAD

**Issue by jdm** [servo/servo#18228]
I've been seeing a bunch recently, and I'm pretty sure they're all caused by the same machine:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 322, in startStep
    result = yield self.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/servo/buildbot/master/factories.py", line 39, in run
    got_rev, rev
exceptions.Exception: Actual commit (43d3376e5d70cab93405d8ba7753beedad8c8370) differs from requested commit (89690d234c015d64bd4bfe1b3012e5608d0d2347)
```

**Comment by jdm** [comment]
Yes, the history of http://build.servo.org/builders/mac-rel-wpt3?numbuilds=45 is full of git exceptions that only occur on servo-mac7.

**Comment by jdm** [comment]
http://build.servo.org/builders/mac-rel-wpt2?numbuilds=45 shows one similar failure on servo-mac9.

**Comment by jdm** [comment]
cc @edunham

**Comment by mbrubeck** [comment]
Here's one from servo-mac2 http://build.servo.org/builders/mac-dev-unit/builds/8972
