### ISSUE TITLE
JS garbage collector crash

### ISSUE THREAD

**Issue by mateon1** [servo/servo#18312]
@emilio on IRC told me to post this issue here

While browsing through wikia.com, Servo crashed with the following stack trace, this crash is not (easily) reproducible.

```
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
stack backtrace:
   0:     0x559c593a4f2e - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo-fixed/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo-fixed/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x559c593a4f63 - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo-fixed/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x559c58101b2d - servo::install_crash_handler::handler
                        at /shared/dev/rust/servo-fixed/ports/servo/main.rs:72
   3:     0x559c59c5a81c - AsmJSFaultHandler
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   4:     0x7f82ba9cb0bf - <unknown>
   5:     0x559c59abbf6f - _ZN2js14TenuringTracer19moveObjectToTenuredEP8JSObjectS2_NS_2gc9AllocKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2292
   6:     0x559c59abc493 - _ZN2js14TenuringTracer13moveToTenuredEP8JSObject
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2188
   7:     0x559c59abc5d3 - _ZN2js14TenuringTracer8traverseI8JSObjectEEvPPT_
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2028
   8:     0x559c59abd4e6 - _ZN2js24TenuringTraversalFunctorIN2JS5ValueEEclI8JSObjectEES2_PT_PNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2034
                         - _ZN2js13DispatchTypedINS_24TenuringTraversalFunctorIN2JS5ValueEEEJPNS_14TenuringTracerEEEEDTclfp_scP8JSObjectLDn0Espcl7ForwardIT0_Efp1_EEET_RKS3_DpOS9_
                        at /shared/dev/rust/servo-fixed/target/release/build/mozjs_sys-0289558903e85459/out/dist/include/js/Value.h:1920
   9:     0x559c59ac6128 - _ZN2js14TenuringTracer8traverseIN2JS5ValueEEEvPT_
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2043
                         - _ZNK2js2gc11StoreBuffer9ValueEdge5traceERNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2160
                         - _ZN2js2gc11StoreBuffer14MonoTypeBufferINS1_9ValueEdgeEE5traceEPS1_RNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2056
  10:     0x559c59abf3d4 - _ZN2js2gc11StoreBuffer11traceValuesERNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/StoreBuffer.h:421
                         - _ZN2js7Nursery7collectEP9JSRuntimeN2JS8gcreason6ReasonEPN7mozilla6VectorIPNS_11ObjectGroupELm0ENS_17SystemAllocPolicyEEE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Nursery.cpp:423
  11:     0x559c5980f7c6 - _ZN2js2gc9GCRuntime11minorGCImplEN2JS8gcreason6ReasonEPN7mozilla6VectorIPNS_11ObjectGroupELm0ENS_17SystemAllocPolicyEEE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6530
  12:     0x559c5980f9e9 - _ZN2js2gc9GCRuntime7minorGCEP9JSContextN2JS8gcreason6ReasonE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6553
  13:     0x559c59ab03d7 - _ZN2js2gc9GCRuntime19tryNewNurseryObjectILNS_7AllowGCE1EEEP8JSObjectP9JSContextmmPKNS_5ClassE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Allocator.cpp:87
                         - _ZN2js8AllocateI8JSObjectLNS_7AllowGCE1EEEPS1_PNS_16ExclusiveContextENS_2gc9AllocKindEmNS6_11InitialHeapEPKNS_5ClassE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Allocator.cpp:51
  14:     0x559c5983dce4 - _ZN8JSObject6createEPN2js16ExclusiveContextENS0_2gc9AllocKindENS3_11InitialHeapEN2JS6HandleIPNS0_5ShapeEEENS7_IPNS0_11ObjectGroupEEE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:352
  15:     0x559c5981f321 - NewObject
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobj.cpp:671
  16:     0x559c598201af - _ZN2js29NewObjectWithClassProtoCommonEPNS_16ExclusiveContextEPKNS_5ClassEN2JS6HandleIP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobj.cpp:799
  17:     0x559c5982e405 - _ZN2js23NewObjectWithClassProtoEPNS_16ExclusiveContextEPKNS_5ClassEN2JS6HandleIP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:703
                         - NewFunctionClone
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:2213
  18:     0x559c59836a8b - _ZN2js24CloneFunctionReuseScriptEP9JSContextN2JS6HandleIP10JSFunctionEENS3_IP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindES9_
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:2248
  19:     0x559c599478d6 - _ZN2js33CloneFunctionObjectIfNotSingletonEP9JSContextN2JS6HandleIP10JSFunctionEENS3_IP8JSObjectEES9_NS_13NewObjectKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfuninlines.h:89
  20:     0x7f82aca3714e - <unknown>
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
stack backtrace:
   0:     0x559c593a4f2e - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo-fixed/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo-fixed/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x559c593a4f63 - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo-fixed/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x559c58101b2d - servo::install_crash_handler::handler
                        at /shared/dev/rust/servo-fixed/ports/servo/main.rs:72
   3:     0x7f82ba43905f - <unknown>
   4:     0x559c58101b99 - servo::install_crash_handler::handler
                        at /shared/dev/rust/servo-fixed/ports/servo/main.rs:76
   5:     0x559c59c5a81c - AsmJSFaultHandler
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   6:     0x7f82ba9cb0bf - <unknown>
   7:     0x559c59abbf6f - _ZN2js14TenuringTracer19moveObjectToTenuredEP8JSObjectS2_NS_2gc9AllocKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2292
   8:     0x559c59abc493 - _ZN2js14TenuringTracer13moveToTenuredEP8JSObject
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2188
   9:     0x559c59abc5d3 - _ZN2js14TenuringTracer8traverseI8JSObjectEEvPPT_
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2028
  10:     0x559c59abd4e6 - _ZN2js24TenuringTraversalFunctorIN2JS5ValueEEclI8JSObjectEES2_PT_PNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2034
                         - _ZN2js13DispatchTypedINS_24TenuringTraversalFunctorIN2JS5ValueEEEJPNS_14TenuringTracerEEEEDTclfp_scP8JSObjectLDn0Espcl7ForwardIT0_Efp1_EEET_RKS3_DpOS9_
                        at /shared/dev/rust/servo-fixed/target/release/build/mozjs_sys-0289558903e85459/out/dist/include/js/Value.h:1920
  11:     0x559c59ac6128 - _ZN2js14TenuringTracer8traverseIN2JS5ValueEEEvPT_
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2043
                         - _ZNK2js2gc11StoreBuffer9ValueEdge5traceERNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2160
                         - _ZN2js2gc11StoreBuffer14MonoTypeBufferINS1_9ValueEdgeEE5traceEPS1_RNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2056
  12:     0x559c59abf3d4 - _ZN2js2gc11StoreBuffer11traceValuesERNS_14TenuringTracerE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/StoreBuffer.h:421
                         - _ZN2js7Nursery7collectEP9JSRuntimeN2JS8gcreason6ReasonEPN7mozilla6VectorIPNS_11ObjectGroupELm0ENS_17SystemAllocPolicyEEE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Nursery.cpp:423
  13:     0x559c5980f7c6 - _ZN2js2gc9GCRuntime11minorGCImplEN2JS8gcreason6ReasonEPN7mozilla6VectorIPNS_11ObjectGroupELm0ENS_17SystemAllocPolicyEEE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6530
  14:     0x559c5980f9e9 - _ZN2js2gc9GCRuntime7minorGCEP9JSContextN2JS8gcreason6ReasonE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6553
  15:     0x559c59ab03d7 - _ZN2js2gc9GCRuntime19tryNewNurseryObjectILNS_7AllowGCE1EEEP8JSObjectP9JSContextmmPKNS_5ClassE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Allocator.cpp:87
                         - _ZN2js8AllocateI8JSObjectLNS_7AllowGCE1EEEPS1_PNS_16ExclusiveContextENS_2gc9AllocKindEmNS6_11InitialHeapEPKNS_5ClassE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Allocator.cpp:51
  16:     0x559c5983dce4 - _ZN8JSObject6createEPN2js16ExclusiveContextENS0_2gc9AllocKindENS3_11InitialHeapEN2JS6HandleIPNS0_5ShapeEEENS7_IPNS0_11ObjectGroupEEE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:352
  17:     0x559c5981f321 - NewObject
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobj.cpp:671
  18:     0x559c598201af - _ZN2js29NewObjectWithClassProtoCommonEPNS_16ExclusiveContextEPKNS_5ClassEN2JS6HandleIP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobj.cpp:799
  19:     0x559c5982e405 - _ZN2js23NewObjectWithClassProtoEPNS_16ExclusiveContextEPKNS_5ClassEN2JS6HandleIP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:703
                         - NewFunctionClone
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:2213
  20:     0x559c59836a8b - _ZN2js24CloneFunctionReuseScriptEP9JSContextN2JS6HandleIP10JSFunctionEENS3_IP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindES9_
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:2248
  21:     0x559c599478d6 - _ZN2js33CloneFunctionObjectIfNotSingletonEP9JSContextN2JS6HandleIP10JSFunctionEENS3_IP8JSObjectEES9_NS_13NewObjectKindE
                        at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfuninlines.h:89
  22:     0x7f82aca3714e - <unknown>
Servo exited with return value -4
```

/cc @jdm

**Comment by mateon1** [comment]
I managed to get an rr trace of this crash, unfortunately I didn't know about --debug-mozjs. I'll try to reproduce it after rebuilding with that flag.
I am willing to debug this over IRC.
Here's the backtrace, it's a segmentation fault, and `print *objp` gives a shady `$1 = (JSObject *) 0x7ffffffffff2`
```gdb
(rr) bt
#0  js::TenuringTracer::traverse<JSObject> (this=0x7f2d4d9e9c10, objp=objp@entry=0x7f2d4d9e99f8)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2027
#1  0x0000558cacad74e7 in js::TenuringTraversalFunctor<JS::Value>::operator()<JSObject> (this=<synthetic pointer>, trc=<optimized out>, t=<optimized out>)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2034
#2  js::DispatchTyped<js::TenuringTraversalFunctor<JS::Value>, js::TenuringTracer*>(js::TenuringTraversalFunctor<JS::Value>, JS::Value const&, js::TenuringTracer*&&) (val=..., f=...)
    at /shared/dev/rust/servo-fixed/target/release/build/mozjs_sys-0289558903e85459/out/dist/include/js/Value.h:1920
#3  0x0000558cacae0129 in js::TenuringTracer::traverse<JS::Value> (thingp=0x7f2d4d9eba08, this=0x7f2d4d9e9c10)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2043
#4  js::gc::StoreBuffer::ValueEdge::trace (mover=..., this=0x7f2d443ed008) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2160
#5  js::gc::StoreBuffer::MonoTypeBuffer<js::gc::StoreBuffer::ValueEdge>::trace (this=this@entry=0x7f2d52eff070, owner=owner@entry=0x7f2d52eff070, mover=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Marking.cpp:2056
#6  0x0000558cacad93d5 in js::gc::StoreBuffer::traceValues (mover=..., this=0x7f2d52eff070)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/StoreBuffer.h:421
#7  js::Nursery::collect (this=this@entry=0x7f2d52efefd0, rt=0x7f2d52efeb88, reason=reason@entry=JS::gcreason::OUT_OF_NURSERY, pretenureGroups=pretenureGroups@entry=0x7f2d4d9e9f50)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Nursery.cpp:423
#8  0x0000558cac8297c7 in js::gc::GCRuntime::minorGCImpl (this=this@entry=0x7f2d52efef88, reason=reason@entry=JS::gcreason::OUT_OF_NURSERY, pretenureGroups=pretenureGroups@entry=0x7f2d4d9e9f50)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6530
#9  0x0000558cac8299ea in js::gc::GCRuntime::minorGC (this=this@entry=0x7f2d52efef88, cx=cx@entry=0x7f2d52efe9c0, reason=reason@entry=JS::gcreason::OUT_OF_NURSERY)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6553
#10 0x0000558cacaca3d8 in js::gc::GCRuntime::tryNewNurseryObject<(js::AllowGC)1> (clasp=0x558cae0e7940 <js::CallObject::class_>, nDynamicSlots=0, thingSize=64, cx=0x7f2d52efe9c0, this=0x7f2d52efef88)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Allocator.cpp:87
#11 js::Allocate<JSObject, (js::AllowGC)1> (cx=cx@entry=0x7f2d52efe9c0, kind=kind@entry=js::gc::AllocKind::OBJECT4_BACKGROUND, nDynamicSlots=0, heap=heap@entry=js::gc::DefaultHeap, 
    clasp=clasp@entry=0x558cae0e7940 <js::CallObject::class_>) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Allocator.cpp:51
#12 0x0000558cac857ce5 in JSObject::create (cx=cx@entry=0x7f2d52efe9c0, kind=js::gc::AllocKind::OBJECT4_BACKGROUND, heap=heap@entry=js::gc::DefaultHeap, shape=shape@entry=..., group=group@entry=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:352
#13 0x0000558cac9a6c0a in js::CallObject::createTemplateObject (cx=cx@entry=0x7f2d52efe9c0, script=..., heap=js::gc::DefaultHeap)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/ScopeObject.cpp:316
#14 0x0000558cac9a6d1f in js::CallObject::create (cx=cx@entry=0x7f2d52efe9c0, script=script@entry=..., enclosing=enclosing@entry=..., callee=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/ScopeObject.cpp:337
#15 0x0000558cac9a9187 in js::CallObject::createForFunction (cx=cx@entry=0x7f2d52efe9c0, enclosing=..., enclosing@entry=..., callee=..., callee@entry=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/ScopeObject.cpp:371
#16 0x0000558cac9a92ea in js::CallObject::createForFunction (cx=cx@entry=0x7f2d52efe9c0, frame=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/ScopeObject.cpp:383
#17 0x0000558cac9a9d3a in js::InterpreterFrame::initFunctionScopeObjects (cx=0x7f2d52efe9c0, this=0x7f2d4b1f5308)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Stack.cpp:165
#18 js::InterpreterFrame::prologue (this=0x7f2d4b1f5308, cx=0x7f2d52efe9c0) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Stack.cpp:218
#19 0x0000558cac94ca8c in Interpret (cx=0x7f2d52efe9c0, state=...) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2945
#20 0x0000558cac95184d in js::RunScript (cx=cx@entry=0x7f2d52efe9c0, state=...) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
#21 0x0000558cac951b57 in js::InternalCallOrConstruct (cx=0x7f2d52efe9c0, args=..., construct=<optimized out>)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
#22 0x0000558cac952068 in js::Call (cx=cx@entry=0x7f2d52efe9c0, fval=..., fval@entry=..., thisv=..., args=..., rval=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
#23 0x0000558cac8439f9 in js::fun_call (cx=0x7f2d52efe9c0, argc=<optimized out>, vp=0x7f2d4b1f5128)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1256
#24 0x0000558cac951d45 in js::CallJSNative (args=..., native=<optimized out>, cx=0x7f2d52efe9c0)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
#25 js::InternalCallOrConstruct (cx=0x7f2d52efe9c0, args=..., construct=<optimized out>) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
#26 0x0000558cac944d80 in js::CallFromStack (args=..., cx=<optimized out>) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
#27 Interpret (cx=0x7f2d52efe9c0, state=...) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
#28 0x0000558cac95184d in js::RunScript (cx=cx@entry=0x7f2d52efe9c0, state=...) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
#29 0x0000558cac951b57 in js::InternalCallOrConstruct (cx=cx@entry=0x7f2d52efe9c0, args=..., construct=construct@entry=js::NO_CONSTRUCT)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
#30 0x0000558cac957a64 in InternalCall (args=..., cx=0x7f2d52efe9c0) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
#31 js::CallFromStack (cx=cx@entry=0x7f2d52efe9c0, args=...) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
#32 0x0000558cac5f2fc2 in js::jit::DoCallFallback (cx=0x7f2d52efe9c0, frame=0x7f2d4d9eb418, stub_=0x7f2d48c32740, argc=1, vp=0x7f2d4d9eb418, res=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jit/BaselineIC.cpp:5970
#33 0x00007f2d6082ef59 in ?? ()
#34 0xfffaff2d46d089b8 in ?? ()
#35 0x00007f2d4d9eb350 in ?? ()
#36 0xfff9000000000000 in ?? ()
#37 0x0000558caec71480 in ?? ()
#38 0x00007f2d49d36850 in ?? ()
---Type <return> to continue, or q <return> to quit---
#39 0x00007f2d6082fcb3 in ?? ()
#40 0x0000000000004822 in ?? ()
#41 0x00007f2d4d9eb418 in ?? ()
#42 0x00007f2d48c32740 in ?? ()
#43 0x0000000000000001 in ?? ()
#44 0x00007f2d4d9eb398 in ?? ()
#45 0xfffe7f2d3c717580 in ?? ()
#46 0xfff9000000000000 in ?? ()
#47 0xfffe7f2d4abca940 in ?? ()
#48 0x00007f2d4d9eb448 in ?? ()
#49 0x00007f2d48c32740 in ?? ()
#50 0x00007f2d4accc3be in ?? ()
#51 0x0000000000008021 in ?? ()
#52 0xfffe7f2d4abca940 in ?? ()
#53 0xfff9000000000000 in ?? ()
#54 0xfffe7f2d3c717580 in ?? ()
#55 0xfffa00000000000f in ?? ()
#56 0xfffe7f2d4affd2a8 in ?? ()
#57 0xfffe7f2d3c717580 in ?? ()
#58 0xfff9000000000000 in ?? ()
#59 0xfff9000000000000 in ?? ()
#60 0xfff9000000000000 in ?? ()
#61 0x00007f2d4acc6dfd in ?? ()
#62 0x00007f2d4acc6dfd in ?? ()
#63 0xfffaff2d00000080 in ?? ()
#64 0x00007f2d4affd248 in ?? ()
#65 0x00007f2d4acc700c in ?? ()
#66 0x0000000400000001 in ?? ()
#67 0x00007f2d4d9eb4c0 in ?? ()
#68 0x00007f2d60825695 in ?? ()
#69 0x0000000000002045 in ?? ()
#70 0x00007f2d46d25240 in ?? ()
#71 0x0000000000000001 in ?? ()
#72 0xfff9000000000000 in ?? ()
#73 0xfffaff2d4ab5d898 in ?? ()
#74 0xfff9000000000000 in ?? ()
#75 0xfff9000000000000 in ?? ()
#76 0x00007f2d60833024 in ?? ()
#77 0x0000000000002042 in ?? ()
#78 0x00007f2d46d25240 in ?? ()
#79 0x0000000000000001 in ?? ()
#80 0xfff9000000000000 in ?? ()
#81 0xfffaff2d4ab5d898 in ?? ()
#82 0x00007f2d4d9eb528 in ?? ()
#83 0x00007f2d43d4bdb8 in ?? ()
#84 0x00007f2d4aad4ef8 in ?? ()
#85 0x0000000000005021 in ?? ()
#86 0xfffaff2d4ab5d898 in ?? ()
#87 0xfff9000000000000 in ?? ()
#88 0xfffe7f2d46d25240 in ?? ()
#89 0x00007f2d5241d000 in ?? ()
#90 0x00007f2d52efe9c0 in ?? ()
#91 0x00007f2d00000050 in ?? ()
#92 0x00007f2d46d31ba0 in ?? ()
#93 0x0000558cac9684d0 in js::ReadBarrieredBase<js::ObjectGroup*>::read (this=0x7f2d4d9eb5b8) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Barrier.h:553
#94 js::ReadBarriered<js::ObjectGroup*>::get (this=0x7f2d4d9eb5b8) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Barrier.h:608
#95 js::ReadBarriered<js::ObjectGroup*>::operator js::ObjectGroup* const (this=0x7f2d4d9eb5b8) at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/gc/Barrier.h:620
#96 js::ObjectGroup::lazySingletonGroup (cx=0xfffaff2d4b41d358, clasp=0x7f2d4b1f5098, proto=...)
    at /shared/dev/rust/servo-fixed/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/ObjectGroup.cpp:576
#97 0x0000558cac957fd0 in ?? ()
#98 0x0000000000000000 in ?? ()
```
