### ISSUE TITLE
Intermittent content test failure on Linux

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#1857]
I couldn't repro the double-borrow error in content tests on Linux, but I did repro a different rare failure in the content tests.

```
task 'ScriptTask' failed at 'ReaderRng.fill_bytes could not fill buffer: read 50\
0 out of 2048 bytes.', /home/larsberg/servo/src/compiler/rust/src/libstd/rand/re\
ader.rs:68 
```

With backtrace:
```
Thread 12 (Thread 0x7fffde5fb700 (LWP 8410)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:83
#1  0x00007ffff12fdea0 in __nptl_deallocate_tsd () at pthread_create.c:173
#2  0x0000000000000000 in ?? ()

Thread 11 (Thread 0x7fffde7fc700 (LWP 8409)):
#0  0x0000000000601d40 in comm::Port::recv_opt::anon::expr_fn::GKaya3 ()
#1  0x00007ffff4e92c33 in task::Runtime$Ops::deschedule::h08d44bb85c4e8524q3aN::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/co\
mpiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#2  0x00007ffff7706c47 in rt::task::Task::deschedule::h18612f6dee9f7923WPag::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compi\
ler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#3  0x00000000005ffe56 in comm::Port::recv_opt::hdfe32cb19002f4fcGKay::v0.0 ()
#4  0x00000000005ffae1 in comm::Port::recv::h83e750763eed781bGKax::v0.0 ()
#5  0x00000000005ff21b in workqueue::WorkerThread::start::h10261fc10b39011evIaw::v0.0 ()
#6  0x00000000005fefe2 in workqueue::WorkQueue::new::anon::expr_fn::_4zaEai ()
#7  0x00007ffff4e9a3a8 in task::spawn_opts::anon::anon::expr_fn::aG () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_6\
4-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#8  0x00007ffff77653e8 in rt::task::__extensions__::run::anon::expr_fn::av () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#9  0x00007ffff776c93c in rust_try () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/ru\
stc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#10 0x00007ffff776518d in rt::task::Task::run::hf7663b6e52130dcbWPar::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#11 0x00007ffff4e99fcb in task::spawn_opts::anon::expr_fn::ao () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unkn\
own-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#12 0x00007ffff7766d84 in rt::thread::thread_start::h1c6c4d06897b01b3ax::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/\
rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#13 0x00007ffff12fdf6e in start_thread (arg=0x7fffde7fc700) at pthread_create.c:311
#14 0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 10 (Thread 0x7fffdeffd700 (LWP 8408)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff719b1b9 in uv_cond_wait (cond=cond@entry=0x7ffff73ede40 <cond>, mutex=mutex@entry=0x7ffff73ede00 <mutex>) at ../../../../../../../../src\
/compiler/rust/src/libuv/src/unix/thread.c:324
#2  0x00007ffff719b3d3 in worker (arg=arg@entry=0x0) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/threadpool.c:56
#3  0x00007ffff7190ec7 in uv__thread_start (arg=<optimized out>) at ../../../../../../../../src/compiler/rust/src/libuv/src/uv-common.c:269
#4  0x00007ffff12fdf6e in start_thread (arg=0x7fffdeffd700) at pthread_create.c:311
#5  0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 9 (Thread 0x7fffdf7fe700 (LWP 8407)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff719b1b9 in uv_cond_wait (cond=cond@entry=0x7ffff73ede40 <cond>, mutex=mutex@entry=0x7ffff73ede00 <mutex>) at ../../../../../../../../src\
/compiler/rust/src/libuv/src/unix/thread.c:324
#2  0x00007ffff719b3d3 in worker (arg=arg@entry=0x0) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/threadpool.c:56
#3  0x00007ffff7190ec7 in uv__thread_start (arg=<optimized out>) at ../../../../../../../../src/compiler/rust/src/libuv/src/uv-common.c:269
#4  0x00007ffff12fdf6e in start_thread (arg=0x7fffdf7fe700) at pthread_create.c:311
#5  0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 8 (Thread 0x7fffdffff700 (LWP 8406)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff719b1b9 in uv_cond_wait (cond=cond@entry=0x7ffff73ede40 <cond>, mutex=mutex@entry=0x7ffff73ede00 <mutex>) at ../../../../../../../../src\
/compiler/rust/src/libuv/src/unix/thread.c:324
#2  0x00007ffff719b3d3 in worker (arg=arg@entry=0x0) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/threadpool.c:56
#3  0x00007ffff7190ec7 in uv__thread_start (arg=<optimized out>) at ../../../../../../../../src/compiler/rust/src/libuv/src/uv-common.c:269
#4  0x00007ffff12fdf6e in start_thread (arg=0x7fffdffff700) at pthread_create.c:311
#5  0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 7 (Thread 0x7fffece30700 (LWP 8405)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff719b1b9 in uv_cond_wait (cond=cond@entry=0x7ffff73ede40 <cond>, mutex=mutex@entry=0x7ffff73ede00 <mutex>) at ../../../../../../../../src\
/compiler/rust/src/libuv/src/unix/thread.c:324
#2  0x00007ffff719b3d3 in worker (arg=arg@entry=0x0) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/threadpool.c:56
#3  0x00007ffff7190ec7 in uv__thread_start (arg=<optimized out>) at ../../../../../../../../src/compiler/rust/src/libuv/src/uv-common.c:269
#4  0x00007ffff12fdf6e in start_thread (arg=0x7fffece30700) at pthread_create.c:311
#5  0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 6 (Thread 0x7fffed835700 (LWP 8404)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff7762cd0 in unstable::mutex::Mutex::wait::h3c33ff36396f69e0Hgah::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/com\
piler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#2  0x00007ffff4e92cc2 in task::Runtime$Ops::deschedule::h08d44bb85c4e8524q3aN::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/co\
mpiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#3  0x00007ffff7706c47 in rt::task::Task::deschedule::h18612f6dee9f7923WPag::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compi\
ler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#4  0x00007ffff4bd99d9 in comm::Port::recv_opt::he2391b55418fb9e4GKag::v0.1 () at /home/larsberg/servo/src/components/util/time.rs:151
#5  0x00007ffff4bd9871 in fn6265 () at /home/larsberg/servo/src/components/util/time.rs:149
#6  0x00007ffff4e9a3a8 in task::spawn_opts::anon::anon::expr_fn::aG () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_6\
4-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#7  0x00007ffff77653e8 in rt::task::__extensions__::run::anon::expr_fn::av () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#8  0x00007ffff776c93c in rust_try () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/ru\
stc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#9  0x00007ffff776518d in rt::task::Task::run::hf7663b6e52130dcbWPar::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#10 0x00007ffff4e99fcb in task::spawn_opts::anon::expr_fn::ao () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unkn\
own-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#11 0x00007ffff7766d84 in rt::thread::thread_start::h1c6c4d06897b01b3ax::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/\
rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#12 0x00007ffff12fdf6e in start_thread (arg=0x7fffed835700) at pthread_create.c:311
#13 0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 5 (Thread 0x7fffed936700 (LWP 8403)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff719f4aa in uv__epoll_wait (epfd=<optimized out>, events=events@entry=0x7fffed932a50, nevents=nevents@entry=1024, timeout=timeout@entry=-\
1) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-syscalls.c:282
#2  0x00007ffff719dcee in uv__io_poll (loop=loop@entry=0x94ad20, timeout=-1) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-core\
.c:187
#3  0x00007ffff7192827 in uv_run (loop=0x94ad20, mode=UV_RUN_DEFAULT) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/core.c:284
#4  0x00007ffff7413f79 in sched::Scheduler::run::h132feef70efac71arqaB::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/r\
ust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#5  0x00007ffff741357f in sched::Scheduler::bootstrap::h3374bdbf1d00ca15rqak::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/comp\
iler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#6  0x00007ffff7427025 in rt::thread::Thread::start_stack::anon::expr_fn::BRabag () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compil\
er/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#7  0x00007ffff7766d84 in rt::thread::thread_start::h1c6c4d06897b01b3ax::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/\
rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#8  0x00007ffff12fdf6e in start_thread (arg=0x7fffed936700) at pthread_create.c:311
#9  0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 4 (Thread 0x7fffeda37700 (LWP 8402)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff719f4aa in uv__epoll_wait (epfd=<optimized out>, events=events@entry=0x7fffeda33a50, nevents=nevents@entry=1024, timeout=timeout@entry=-\
1) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-syscalls.c:282
#2  0x00007ffff719dcee in uv__io_poll (loop=loop@entry=0x94a260, timeout=-1) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-core\
.c:187
#3  0x00007ffff7192827 in uv_run (loop=0x94a260, mode=UV_RUN_DEFAULT) at ../../../../../../../../src/compiler/rust/src/libuv/src/unix/core.c:284
#4  0x00007ffff7413f79 in sched::Scheduler::run::h132feef70efac71arqaB::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/r\
ust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#5  0x00007ffff741357f in sched::Scheduler::bootstrap::h3374bdbf1d00ca15rqak::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/comp\
iler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#6  0x00007ffff7427025 in rt::thread::Thread::start_stack::anon::expr_fn::BRabag () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compil\
er/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#7  0x00007ffff7766d84 in rt::thread::thread_start::h1c6c4d06897b01b3ax::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/\
rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#8  0x00007ffff12fdf6e in start_thread (arg=0x7fffeda37700) at pthread_create.c:311
#9  0x00007ffff18119cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 3 (Thread 0x7fffedb38700 (LWP 8401)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:83
#1  0x00007ffff12fcf25 in do_clone (pd=pd@entry=0x7fffde5fb700, attr=attr@entry=0x7fffe088af58, stackaddr=<optimized out>, stopped=stopped@entry=1, fct\
=0x7ffff12fdea0 <start_thread>, clone_flags=4001536) at ../nptl/sysdeps/pthread/createthread.c:74
#2  0x00007ffff12fea0d in create_thread (stackaddr=<optimized out>, attr=0x7fffe088af58, pd=0x7fffde5fb700) at ../nptl/sysdeps/pthread/createthread.c:2\
00
#3  __pthread_create_2_1 (newthread=0x7fffe088af90, attr=0x7fffe088af58, start_routine=0x7ffff7766d60 <rt::thread::thread_start::h1c6c4d06897b01b3ax::v\
0.9>, arg=0x7fffe0892090) at pthread_create.c:584
#4  0x00007ffff7764501 in rt::thread::imp::create::h0c003ec76f5abdfdaM::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/r\
ust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#5  0x00007ffff7766ed7 in rt::thread::Thread::spawn_stack::h09e2b77991a4f63eBRa4::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/\
compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#6  0x00007ffff4e9403c in task::spawn_opts::h5fd260a9e6e0a9e3aG::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86\
_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#7  0x00007ffff4e93d28 in task::spawn::h77cb9dc6a07fac45au::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-u\
nknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#8  0x00000000005f0db6 in workqueue::WorkQueue::new::h934fb1cd174408b74zaE::v0.0 () at /home/larsberg/servo/src/components/main/layout/layout_task.rs:2\
91
#9  0x00000000005e303c in servo::layout::layout_task::LayoutTask::new (id=..., port=..., chan=..., constellation_chan=..., script_chan=..., render_chan\
=..., image_cache_task=..., opts=0x7fffe068bee0, profiler_chan=...) at /home/larsberg/servo/src/components/main/layout/layout_task.rs:291
#10 0x00000000005e10c7 in fn28683 () at /home/larsberg/servo/src/components/main/layout/layout_task.rs:262
#11 0x00007ffff741f1b8 in task::__extensions__::build_start_wrapper::anon::anon::expr_fn::a1 () from /home/larsberg/servo/build/x86_64-unknown-linux-gn\
u/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#12 0x00007ffff77653e8 in rt::task::__extensions__::run::anon::expr_fn::av () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#13 0x00007ffff776c93c in rust_try () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/ru\
stc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#14 0x00007ffff776518d in rt::task::Task::run::hf7663b6e52130dcbWPar::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#15 0x00007ffff741ebdc in task::__extensions__::build_start_wrapper::anon::expr_fn::aK () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/\
compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#16 0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7ffff7f58700 (LWP 8400)):
#0  0x00007ffff77698a0 in rust_fail () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/r\
ustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#1  0x00007ffff76c65d8 in rt::unwind::Unwinder::begin_unwind::hd890d6617f8679e9tUaP::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/s\
rc/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#2  0x00007ffff76c56e9 in rt::unwind::begin_unwind::h2f304945dd8fa486ax::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/\
rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#3  0x00007ffff7747395 in rand::reader::Rng$ReaderRng::fill_bytes::h54fe904e8af1b802PHaC::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-\
gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#4  0x00007ffff771afea in rand::task_rng::h601200ec121dff12aQ::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_6\
4-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#5  0x00007ffff2ec6e60 in hashmap::HashMap::with_capacity::h7375569990e0bc1cJZam::v0.1 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/\
support/spidermonkey/rust-mozjs/libjs-7e22fbae-0.1.so
#6  0x00007ffff2ec6e03 in hashmap::HashMap::new::h7fa907f6d019d80bJZaj::v0.1 () at /home/larsberg/servo/src/support/spidermonkey/rust-mozjs/rust.rs:105
#7  0x00007ffff2ea520f in js::rust::new_context (ptr=0x7fffe8005040, rt=0x7fffe048b110) at /home/larsberg/servo/src/support/spidermonkey/rust-mozjs/rus\
t.rs:105
#8  0x00007ffff2ea50c9 in js::rust::rt_rsrc::cx (self=0x7fffe048b110) at /home/larsberg/servo/src/support/spidermonkey/rust-mozjs/rust.rs:55
#9  0x00007ffff2642df9 in script::script_task::ScriptTask::load (self=0x7fffe048b170, pipeline_id=..., url=...) at /home/larsberg/servo/src/components/\
script/script_task.rs:685
#10 0x00007ffff2638bd5 in script::script_task::ScriptTask::handle_msgs (self=0x7fffe048b170) at /home/larsberg/servo/src/components/script/script_task.\
rs:534
#11 0x00007ffff2637e07 in script::script_task::ScriptTask::start (self=0x7fffe048b170) at /home/larsberg/servo/src/components/script/script_task.rs:454
#12 0x000000000055be56 in script_task::ScriptTask::create::anon::expr_fn::_9kaiak () at /home/larsberg/servo/src/components/main/pipeline.rs:136
#13 0x00007ffff741f1b8 in task::__extensions__::build_start_wrapper::anon::anon::expr_fn::a1 () from /home/larsberg/servo/build/x86_64-unknown-linux-gn\
u/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#14 0x00007ffff77653e8 in rt::task::__extensions__::run::anon::expr_fn::av () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#15 0x00007ffff776c93c in rust_try () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/ru\
stc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#16 0x00007ffff776518d in rt::task::Task::run::hf7663b6e52130dcbWPar::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#17 0x00007ffff741ebdc in task::__extensions__::build_start_wrapper::anon::expr_fn::aK () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/\
compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libgreen-83b1c0e5-0.9.so
#18 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7ffff7fbd780 (LWP 8396)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff7762cd0 in unstable::mutex::Mutex::wait::h3c33ff36396f69e0Hgah::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/com\
piler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#2  0x00007ffff4e92cc2 in task::Runtime$Ops::deschedule::h08d44bb85c4e8524q3aN::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/co\
mpiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#3  0x00007ffff7706c47 in rt::task::Task::deschedule::h18612f6dee9f7923WPag::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compi\
ler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#4  0x00000000004a1731 in comm::Port::recv_opt::h40e3f87cfd14be90GKah::v0.0 () at /home/larsberg/servo/src/components/main/compositing/headless.rs:74
#5  0x00000000004a1389 in comm::Port::recv::h439573d834c088e8GKaf::v0.0 () at /home/larsberg/servo/src/components/main/compositing/headless.rs:74
#6  0x00000000004a0e4c in servo::compositing::headless::NullCompositor::handle_message (self=0x7fffffffd288, constellation_chan=...) at /home/larsberg/\
servo/src/components/main/compositing/headless.rs:47
#7  0x00000000004a0c14 in servo::compositing::headless::NullCompositor::create (port=..., constellation_chan=..., profiler_chan=...) at /home/larsberg/\
servo/src/components/main/compositing/headless.rs:36
#8  0x00000000004ad672 in servo::compositing::CompositorTask::create (opts=..., port=..., constellation_chan=..., profiler_chan=...) at /home/larsberg/\
servo/src/components/main/compositing/compositor_task.rs:211
#9  0x0000000000663fe3 in servo::run (opts=...) at /home/larsberg/servo/src/components/main/servo.rs:190
#10 0x0000000000663852 in fn32673 () at /home/larsberg/servo/src/components/main/servo.rs:122
#11 0x00007ffff4e9a7db in run::he581c1f1e0606589aF::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-l\
inux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#12 0x00007ffff4e9a736 in start::anon::expr_fn::aT () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-g\
nu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#13 0x00007ffff77653e8 in rt::task::__extensions__::run::anon::expr_fn::av () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#14 0x00007ffff776c93c in rust_try () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/ru\
stc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#15 0x00007ffff776518d in rt::task::Task::run::hf7663b6e52130dcbWPar::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rus\
t/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-3e5aeb83-0.9.so
#16 0x00007ffff4e9a5db in start::heb40a29f71507b85aB::v0.9 () from /home/larsberg/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown\
-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libnative-cf55a53a-0.9.so
#17 0x0000000000663700 in servo::start (argc=4, argv=0x7fffffffdf08) at /home/larsberg/servo/src/components/main/servo.rs:121
#18 0x0000000000663762 in main () at /home/larsberg/servo/src/components/main/servo.rs:121
```

**Comment by Ms2ger** [comment]
Content tests are dead.
