### ISSUE TITLE
Ember Perf fails nondeterministically

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#18618]
Trying to track down why the Ember perf suite isn't working for #16720.  The current behaviour is that it will fail non-deterministically at different parts in the run.  For example, here are the last four times I ran it:

```
jturner-23759:servo jturner$ ./mach run -r http://emberperf.eviltrout.com/
DEBUG: -------------------------------
DEBUG: Ember  : 2.6.1
DEBUG: jQuery : 2.2.4
DEBUG: -------------------------------
ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/benchmarks/ember-get/index.js:6:9 Ember is not defined
Servo exited with return value -2
jturner-23759:servo jturner$ ./mach run -r http://emberperf.eviltrout.com/
DEBUG: -------------------------------
DEBUG: Ember  : 2.6.1
DEBUG: jQuery : 2.2.4
DEBUG: -------------------------------
ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/assets/test-client.js:341:5 Ember is not defined
Servo exited with return value -2
jturner-23759:servo jturner$ ./mach run -r http://emberperf.eviltrout.com/
DEBUG: -------------------------------
DEBUG: Ember  : 2.6.1
DEBUG: jQuery : 2.2.4
DEBUG: -------------------------------
ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/assets/test-client.js:341:5 Ember is not defined
Servo exited with return value -2
jturner-23759:servo jturner$ ./mach run -r http://emberperf.eviltrout.com/
DEBUG: -------------------------------
DEBUG: Ember  : 2.6.1
DEBUG: jQuery : 2.2.4
DEBUG: -------------------------------
ERROR:script::dom::bindings::error: Error at http://emberperf.eviltrout.com/benchmarks/ember-get/primed/index.js:13:9 Ember is not defined
Servo exited with return value -2
```

It's possible it's the same root cause, since each one is about the same JS variable not being defined.

**Comment by jdm** [comment]
Can't reproduce any longer!
