### ISSUE TITLE
Render task's target rect is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#18688]
Load http://pygy.github.io/servo-rendering-bugs/j2c/j2c/index.html and get this assertion immediately:
```
Should have been allocated by now! (thread RenderBackend, at src/libcore/option.rs:839)
ERROR:script::dom::bindings::error: Error at http://pygy.github.io/servo-rendering-bugs/j2c/j2c/index.html:850:1 playground is not defined
stack backtrace:
   0:        0x100fb58a4 - backtrace::backtrace::trace<closure>
                        at /Users/jdm/src/master-servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:        0x100fb93af - backtrace::capture::Backtrace::new::he650fd7fdf01c950
                        at /Users/jdm/src/master-servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:        0x10009532e - servo::main::{{closure}}
                        at /Users/jdm/src/master-servo/ports/servo/main.rs:130
   3:        0x107144b11 - std::panicking::rust_panic_with_hook::h45dfd77e4441d909
                        at src/libstd/panicking.rs:578
   4:        0x107144934 - std::panicking::begin_panic<alloc::string::String>
                        at src/libstd/panicking.rs:538
   5:        0x107144882 - std::panicking::begin_panic_fmt::hb4108dd2abc8d550
                        at src/libstd/panicking.rs:522
   6:        0x1071447ea - rust_begin_unwind
                        at src/libstd/panicking.rs:498
   7:        0x10717e4e3 - core::panicking::panic_fmt::h511718275b8414ef
                        at src/libcore/panicking.rs:71
   8:        0x10717e54d - core::option::expect_failed::h130e4c4a6c5d89b2
                        at src/libcore/option.rs:839
   9:        0x10170377a - core::option::{{impl}}::expect<(euclid::point::TypedPoint2D<i32, webrender_api::units::DevicePixel>, webrender::tiling::RenderTargetIndex)>
                        at /Users/travis/build/rust-lang/rust/src/libcore/option.rs:302
  10:        0x10179b861 - webrender::render_task::{{impl}}::get_target_rect
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_task.rs:573
  11:        0x10179ad61 - webrender::render_task::{{impl}}::write_task_data
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_task.rs:500
  12:        0x1017990b1 - webrender::render_task::{{impl}}::build
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_task.rs:108
  13:        0x10152c38e - webrender::frame_builder::{{impl}}::build
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame_builder.rs:2376
  14:        0x10165a3b5 - webrender::frame::{{impl}}::build_frame::{{closure}}
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame.rs:1253
  15:        0x101578df5 - core::option::{{impl}}::map<&mut webrender::frame_builder::FrameBuilder,webrender::tiling::Frame,closure>
                        at /Users/travis/build/rust-lang/rust/src/libcore/option.rs:398
  16:        0x10165a0bc - webrender::frame::{{impl}}::build_frame
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame.rs:1252
  17:        0x101659ea8 - webrender::frame::{{impl}}::build
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame.rs:1229
  18:        0x10166742a - webrender::render_backend::{{impl}}::render
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_backend.rs:106
  19:        0x1016690e9 - webrender::render_backend::{{impl}}::process_document
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_backend.rs:400
  20:        0x101669c2f - webrender::render_backend::{{impl}}::run
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_backend.rs:468
  21:        0x10153df5f - webrender::renderer::{{impl}}::new::{{closure}}
                        at /Users/jdm/src/master-servo/./.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/renderer.rs:1713
  22:        0x101444bea - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  23:        0x10157f3b3 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:394
  24:        0x10153faea - std::panic::{{impl}}::call_once<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:296
  25:        0x101580b22 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:480
  26:        0x10715199c - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:99
  27:        0x10157f79c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:459
  28:        0x10157ee55 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:361
  29:        0x10147b82b - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:393
  30:        0x1014a5583 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:728
  31:        0x10714385b - std::sys::imp::thread::{{impl}}::new::thread_start
                        at src/libstd/sys_common/thread.rs:24
  32:     0x7fffd9f7f93a - _pthread_body
  33:     0x7fffd9f7f886 - _pthread_start
```

cc @glennw

**Comment by pygy** [comment]
The playground global variable is created on line 763 by an HTML id: `<div id="playground">Loading the docs...</div>`.

**Comment by mateon1** [comment]
Whoops, I duplicated some work trying to independently reduce this issue.
Here's a minimal test case:
```html
x<body style="overflow:scroll;text-shadow:0 0 1px">
```

<details>
<summary>Stack trace for this testcase</summary>

```rust
Should have been allocated by now! (thread RenderBackend, at /checkout/src/libcore/option.rs:839)
...
(gdb) bt full
#0  std::panicking::rust_panic () at /checkout/src/libstd/panicking.rs:608
No locals.
#1  0x000055555c761a67 in std::panicking::rust_panic_with_hook () at /checkout/src/libstd/panicking.rs:593
No locals.
#2  0x000055555c761895 in std::panicking::begin_panic<alloc::string::String> () at /checkout/src/libstd/panicking.rs:538
No locals.
#3  0x000055555c76179a in std::panicking::begin_panic_fmt () at /checkout/src/libstd/panicking.rs:522
No locals.
#4  0x000055555c76172b in std::panicking::rust_begin_panic () at /checkout/src/libstd/panicking.rs:498
No locals.
#5  0x000055555c79bb31 in core::panicking::panic_fmt () at /checkout/src/libcore/panicking.rs:71
No locals.
#6  0x000055555c79bb9e in core::option::expect_failed () at /checkout/src/libcore/option.rs:839
No locals.
#7  0x0000555559dfa821 in core::option::Option<(euclid::point::TypedPoint2D<i32, webrender_api::units::DevicePixel>, webrender::tiling::RenderTargetIndex)>::expect<(euclid::point::TypedPoint2D<i32, webrender_api::units::DevicePixel>, webrender::tiling::RenderTargetIndex)> (self=core::option::Option::None, msg="Should have been allocated by now!") at /checkout/src/libcore/option.rs:302
        self = core::option::Option::None
        msg = "Should have been allocated by now!"
#8  0x0000555559e97da2 in webrender::render_task::RenderTask::get_target_rect (self=0x7fffe73d6c00)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_task.rs:573
        origin_and_target_index = core::option::Option::None
        size = TypedSize2D<i32, webrender_api::units::DevicePixel> = {width = 1008, height = 19, _unit = PhantomData<webrender_api::units::DevicePixel>}
        self = 0x7fffe73d6c00
#9  0x0000555559e972f2 in webrender::render_task::RenderTask::write_task_data (self=0x7fffe73d6c00)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_task.rs:500
        task = 0x7fffe73d6c78
        self = 0x7fffe73d6c00
#10 0x0000555559e95882 in webrender::render_task::RenderTaskTree::build (self=0x7fffe79f25c8) at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_task.rs:108
        task = 0x7fffe73d6c00
        __next = 0x7fffe73d6c00
        iter = IterMut<webrender::render_task::RenderTask> = {ptr = 0x7fffe73d6cb8, end = 0x7fffe73d7108, _marker = PhantomData<&mut webrender::render_task::RenderTask>}
        self = 0x7fffe79f25c8
#11 0x0000555559e8cccf in webrender::frame_builder::FrameBuilder::build (self=0x7fffe79f2ec0, resource_cache=0x7fffe79f9288, gpu_cache=0x7fffe79f9170, frame_id=FrameId = {...}, 
    clip_scroll_tree=0x7fffe723c170, pipelines=0x7fffe723c118, device_pixel_ratio=1, output_pipelines=0x7fffe723c490, texture_cache_profile=0x7fffe79f5460, gpu_cache_profile=0x7fffe79f54e0)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame_builder.rs:2376
#12 0x0000555559d0c8e6 in webrender::frame::{{impl}}::build_frame::{{closure}} (builder=0x7fffe79f2ec0)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame.rs:1253
#13 0x0000555559c23796 in core::option::Option<&mut webrender::frame_builder::FrameBuilder>::map<&mut webrender::frame_builder::FrameBuilder,webrender::tiling::Frame,closure> (self=Some = {...}, 
    f=closure = {...}) at /checkout/src/libcore/option.rs:398
#14 0x0000555559d0c5ed in webrender::frame::Frame::build_frame (self=0x7fffe723c170, resource_cache=0x7fffe79f9288, gpu_cache=0x7fffe79f9170, pipelines=0x7fffe723c118, device_pixel_ratio=1, 
    output_pipelines=0x7fffe723c490, texture_cache_profile=0x7fffe79f5460, gpu_cache_profile=0x7fffe79f54e0)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame.rs:1252
#15 0x0000555559d0c3d9 in webrender::frame::Frame::build (self=0x7fffe723c170, resource_cache=0x7fffe79f9288, gpu_cache=0x7fffe79f9170, pipelines=0x7fffe723c118, device_pixel_ratio=1, 
    pan=TypedPoint2D<f32, webrender_api::units::LayerPixel> = {...}, output_pipelines=0x7fffe723c490, texture_cache_profile=0x7fffe79f5460, gpu_cache_profile=0x7fffe79f54e0)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/frame.rs:1229
#16 0x0000555559faf28b in webrender::render_backend::Document::render (self=0x7fffe723c118, resource_cache=0x7fffe79f9288, gpu_cache=0x7fffe79f9170, resource_profile=0x7fffe79f5420)
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_backend.rs:106
#17 0x0000555559fb0da2 in webrender::render_backend::RenderBackend::process_document (self=0x7fffe79f9158, document_id=DocumentId = {...}, message=GenerateFrame = {...}, frame_counter=1, 
    profile_counters=0x7fffe79f5400) at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_backend.rs:400
#18 0x0000555559fb1958 in webrender::render_backend::RenderBackend::run (self=0x7fffe79f9158, profile_counters=BackendProfileCounters = {...})
    at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/render_backend.rs:468
#19 0x0000555559eca6e1 in webrender::renderer::{{impl}}::new::{{closure}} () at /shared/dev/rust/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/0fd01ba/webrender/src/renderer.rs:1713
#20 0x0000555559dfdb2b in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> (f=closure = {...}) at /checkout/src/libstd/sys_common/backtrace.rs:136
#21 0x0000555559c359f4 in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> () at /checkout/src/libstd/thread/mod.rs:394
#22 0x0000555559bf788b in std::panic::{{impl}}::call_once<(),closure> (self=AssertUnwindSafe<closure> = {...}, _args=()) at /checkout/src/libstd/panic.rs:296
#23 0x0000555559c370b3 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=0x7fffe79fc358 "\000") at /checkout/src/libstd/panicking.rs:480
#24 0x000055555c768b9d in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:99
#25 0x0000555559c3658d in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> (f=AssertUnwindSafe<closure> = {...}) at /checkout/src/libstd/panicking.rs:459
#26 0x0000555559c356f6 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=AssertUnwindSafe<closure> = {...}) at /checkout/src/libstd/panic.rs:361
#27 0x0000555559e009dc in std::thread::{{impl}}::spawn::{{closure}}<closure,()> () at /checkout/src/libstd/thread/mod.rs:393
#28 0x0000555559e345a4 in alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7ffff2468d80, args=()) at /checkout/src/liballoc/boxed.rs:728
#29 0x000055555c76068c in alloc::boxed::{{impl}}::call_once<(),()> () at /checkout/src/liballoc/boxed.rs:738
#30 std::sys_common::thread::start_thread () at /checkout/src/libstd/sys_common/thread.rs:24
#31 std::sys::imp::thread::{{impl}}::new::thread_start () at /checkout/src/libstd/sys/unix/thread.rs:90
#32 0x00007ffff597f494 in start_thread (arg=0x7fffe79ff700) at pthread_create.c:333
#33 0x00007ffff54acabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

</details>

**Comment by jdm** [comment]
This no longer panics.
