### ISSUE TITLE
Many layout issues on State of the Octiverse

### ISSUE THREAD

**Issue by jdm** [servo/servo#18849]
* The floating logo and github text does not appear and scroll with the page
* the grey earth does not appear
* the twinkly lights do not animate and are not positioned over where the moon should be
* the "Build/Work/Learn/Connect" has an inverse mask effect going on
* no section numbers appear by the "Build/Work/Learn/Connect" words
* the world map is missing the coloured overlay and doesn't respond to clicks
* the programming language graph does not appear
* Emojis are missing
* Student Developer Pack underline is in front of the text, not behind like it should be
* twitter/facebook/linkedin icons are missing in "Join our universe"
* can scroll past the end of the page

**Comment by jdm** [comment]
JS errors that probably are related to some of these:
```
ERROR:script::dom::bindings::error: Error at https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js:10:124560 t.measureText is not a function
ERROR:script::dom::bindings::error: Error at https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:64078 t is null
ERROR:script::dom::bindings::error: Error at https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:64078 t is null
ERROR:script::dom::bindings::error: Error at https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:64078 t is null
ERROR:script::dom::bindings::error: Error at https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:64078 t is null
ERROR:script::dom::bindings::error: Error at https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:64078 t is null
ERROR:script::dom::bindings::error: Error at https://octoverse.github.com/:1607:21 dataLayer.push is not a function
ERROR:script::dom::bindings::error: Error at https://www.googletagmanager.com/gtag/js?id=UA-3769691-36:128:410 a.slice is not a function
```

**Comment by jdm** [comment]
https://octoverse.github.com/

**Comment by nox** [comment]
The `measureText` error is probably https://github.com/servo/servo/issues/5411.

**Comment by jdm** [comment]
Not worth keeping this around anymore; the site has changed significantly in 8 years.
