### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19088]
Can't figure out why? Maybe someone would know what I missed?
on commit `77112b2b8ef7b3bff63c4aeee021754a3fa0923b` in master 
```
tigercosmos@ubuntu:~/servo$ RUST_BACKTRACE=1 ./mach build --release --android
   Compiling fontsan v0.4.0 (https://github.com/servo/fontsan#29e879c8)
error: failed to run custom build command for `fontsan v0.4.0 (https://github.com/servo/fontsan#29e879c8)`
process didn't exit successfully: `/home/tigercosmos/servo/target/release/build/fontsan-cefea115ad028a99/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/tigercosmos/servo/.cargo/git/checkouts/fontsan-75864180be477bc9/29e879c/src" "-DCMAKE_INSTALL_PREFIX=/home/tigercosmos/servo/target/armv7-linux-androideabi/release/build/fontsan-e53757c81b4cc3ed/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC --sysroot /home/tigercosmos/ndk/platforms/android-18/arch-arm -I/home/tigercosmos/ndk/sources/android/support/include -march=armv7-a -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp" "-DCMAKE_C_COMPILER=/home/tigercosmos/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC --sysroot /home/tigercosmos/ndk/platforms/android-18/arch-arm -I/home/tigercosmos/ndk/sources/android/support/include -I/home/tigercosmos/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/tigercosmos/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/include -march=armv7-a -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp" "-DCMAKE_CXX_COMPILER=/home/tigercosmos/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_TOOLCHAIN_FILE=/home/tigercosmos/servo/support/android/toolchain.cmake"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tigercosmos/servo/target/armv7-linux-androideabi/release/build/fontsan-e53757c81b4cc3ed/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--" "-j1"
[  1%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/font.cc.o
CMakeFiles/woff2.dir/build.make:62: recipe for target 'CMakeFiles/woff2.dir/ots/third_party/woff2/src/font.cc.o' failed
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/woff2.dir/all' failed
Makefile:127: recipe for target 'all' failed

--- stderr
In file included from /home/tigercosmos/servo/.cargo/git/checkouts/fontsan-75864180be477bc9/29e879c/src/ots/third_party/woff2/src/font.cc:9:0:
/home/tigercosmos/servo/.cargo/git/checkouts/fontsan-75864180be477bc9/29e879c/src/ots/third_party/woff2/src/./font.h:15:15: fatal error: map: No such file or directory
 #include <map>
               ^
compilation terminated.
make[2]: *** [CMakeFiles/woff2.dir/ots/third_party/woff2/src/font.cc.o] Error 1
make[1]: *** [CMakeFiles/woff2.dir/all] Error 2
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:617:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: cmake::fail
   8: cmake::run
   9: cmake::Config::build
  10: build_script_build::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: _start

Build FAILED in 0:00:06
```

**Comment by tigercosmos** [comment]
Seems `CMakeFiles/woff2.dir/all` is important?

**Comment by tigercosmos** [comment]
break on this [line](https://github.com/google/woff2/blob/b677a07ffdda0ecb5fd18c3816c5930c7a883b7d/src/font.h#L15)

**Comment by jdm** [comment]
It seems like something is strange in your compiler setup, since `<map>` is a standard header file that should come with any C++ compiler.

**Comment by tigercosmos** [comment]
I would  set up a clean environment to try again

**Comment by tigercosmos** [comment]
I found that is caused by NDK version. as #19095
