### ISSUE TITLE
mach bootstrap fails at Salt installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by hsivonen** [servo/servo#19094]
Steps to reproduce:

1. Use Ubuntu 16.04
2. Run `./mach bootstrap` in the `servo` checkout directory.

Actual results:

```
$ ./mach bootstrap
Checking Salt installation...failed to install Salt via pip:
Output: 
Error: Command "/opt/Projects/servo/python/_virtualenv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-17zCNt/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RQ88Z9-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/Projects/servo/python/_virtualenv/include/site/python2.7/pycrypto" failed with error code 1 in /tmp/pip-build-17zCNt/pycrypto/
```

**Comment by tigercosmos** [comment]
what I encountered in Ubuntu 17.10
```
tigercosmos@ubuntu:~/Desktop/servo$ ./mach bootstrap
Installing missing Salt dependencies...
[sudo] password for tigercosmos: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libssl-dev is already the newest version (1.0.2g-1ubuntu13).
libssl-dev set to manually installed.
python-dev is already the newest version (2.7.14-2ubuntu1).
python-dev set to manually installed.
The following NEW packages will be installed:
  libffi-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 156 kB of archives.
After this operation, 362 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu artful/main amd64 libffi-dev amd64 3.2.1-6 [156 kB]
Fetched 156 kB in 1s (105 kB/s)      
Selecting previously unselected package libffi-dev:amd64.
(Reading database ... 190066 files and directories currently installed.)
Preparing to unpack .../libffi-dev_3.2.1-6_amd64.deb ...
Unpacking libffi-dev:amd64 (3.2.1-6) ...
Processing triggers for install-info (6.4.90.dfsg.1-1build1) ...
Setting up libffi-dev:amd64 (3.2.1-6) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 added doc-base file...
Processing triggers for man-db (2.7.6.1-2) ...
Checking Salt installation...done
Running bootstrap in dry-run mode to show changes
Traceback (most recent call last):
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/scripts.py", line 367, in salt_call
    import salt.cli.call
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/cli/call.py", line 6, in <module>
    from salt.utils import parsers
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/config/__init__.py", line 41, in <module>
    import salt.utils.sdb
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/utils/event.py", line 72, in <module>
    import salt.payload
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/crypt.py", line 42, in <module>
    import salt.utils.rsax931
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/utils/rsax931.py", line 69, in <module>
    libcrypto = _init_libcrypto()
  File "/home/tigercosmos/Desktop/servo/python/_virtualenv/local/lib/python2.7/site-packages/salt/utils/rsax931.py", line 63, in _init_libcrypto
    libcrypto.OPENSSL_no_config()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: OPENSSL_no_config
Something went wrong while bootstrapping
```

**Comment by tigercosmos** [comment]
I try with a *clean* environment again.
1. VM with Ubuntu16.04
2. Setup following by README
3. `mach bootstrap`

```
Running Salt bootstrap
[sudo] password for tigercosmos: 
[ERROR   ] Command '['systemd-run', '--scope', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'libdbus-glib-1-dev', 'autoconf2.13', 'llvm-3.5-dev', 'libavcodec-dev', 'libavutil-dev', 'libclang-3.5-dev', 'xpra', 'xserver-xorg-video-dummy', 'xserver-xorg-input-void', 'ccache', 'libavformat-dev', 'clang-3.5']' failed with return code: 100
[ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-input-void : Depends: xorg-input-abi-22
                           Depends: xserver-xorg-core (>= 2:1.17.99.902)
 xserver-xorg-video-dummy : Depends: xorg-video-abi-20
                            Depends: xserver-xorg-core (>= 2:1.17.99.902)
[ERROR   ] stderr: Running scope as unit run-rd6a4c55c1cc7435890600d75b13cfb2b.scope.
E: Unable to correct problems, you have held broken packages.
[ERROR   ] retcode: 100
[ERROR   ] Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-rd6a4c55c1cc7435890600d75b13cfb2b.scope.
      E: Unable to correct problems, you have held broken packages.
[ERROR   ] Failed to examine repo 'deb http://archive.ubuntu.com/ubuntu xenial multiverse': Error: 'python-apt' package not installed
[ERROR   ] State 'debconf.set' was not found in SLS 'servo-build-dependencies'
Reason: 'debconf.set' is not available.
```

**Comment by hsivonen** [comment]
> Setup following by README

An important (implied) part of this bug report is that if one has mozilla-central experience and finds that `mach bootstrap` exists, it's reasonable to expect it to set up the environment and not even go read the README before that step.

If the expected flow is to follow the README, removing `mach bootstrap` would be a valid fix.

**Comment by tigercosmos** [comment]
That would be another issue, I thought.
Back to the point. I try again today.
It seems `mach bootstrap` fails at Ubuntu all the time...

**Comment by mrobinson** [comment]
I think we aren't using salt dependencies locally any longer.
