### ISSUE TITLE
gecko-media v0.1.0 build failed

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19275]
Tested in `Ubuntu 16.04` and `Ubuntu 17.10` in master HEAD
Both error with log:
```
error: failed to run custom build command for `gecko-media v0.1.0 (https://github.com/servo/gecko-media.git#0299b455)`
process didn't exit successfully: `/home/tigercosmos/servo/target/debug/build/gecko-media-88d42fb65b7af02f/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/tigercosmos/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/." "-DCMAKE_INSTALL_PREFIX=/home/tigercosmos/servo/target/debug/build/gecko-media-3a2a1efaee6275fe/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tigercosmos/servo/target/debug/build/gecko-media-3a2a1efaee6275fe/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
[  5%] Built target vorbis
[ 38%] Built target opus
[ 39%] Built target ogg
[ 39%] Built target speex_resampler
[ 40%] Built target ffmpeg57
[ 80%] Built target gecko_core
[ 85%] Built target theora
[ 94%] Built target stagefright
[ 94%] Building C object CMakeFiles/cubeb.dir/gecko/src/media/libcubeb/src/cubeb_pulse.c.o
CMakeFiles/cubeb.dir/build.make:206: recipe for target 'CMakeFiles/cubeb.dir/gecko/src/media/libcubeb/src/cubeb_pulse.c.o' failed
CMakeFiles/Makefile2:363: recipe for target 'CMakeFiles/cubeb.dir/all' failed
Makefile:127: recipe for target 'all' failed

--- stderr
/home/tigercosmos/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/gecko/src/media/libcubeb/src/cubeb_pulse.c:11:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/cubeb.dir/gecko/src/media/libcubeb/src/cubeb_pulse.c.o] Error 1
make[1]: *** [CMakeFiles/cubeb.dir/all] Error 2
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', .cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.27/src/lib.rs:627:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Build FAILED in 0:00:06
```

```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: cmake::fail
             at .cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.27/src/lib.rs:627
   8: cmake::run
             at .cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.27/src/lib.rs:608
   9: cmake::Config::build
             at .cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.27/src/lib.rs:515
  10: cmake::build
             at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.27/src/lib.rs:93
  11: build_script_build::compile_gecko_media
             at .cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/build.rs:28
  12: build_script_build::main
             at .cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/build.rs:63
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by tigercosmos** [comment]
This regression was caused by 2755c1a89a4576c6a737f6f1ac2e5d68f99213db
After this commit will build failed.
cc @jdm

**Comment by SimonSapin** [comment]
This seems to be the relevant part:
```
fatal error: pulse/pulseaudio.h: No such file or directory
```

You may need to install the `libpulse-dev` package, per https://github.com/servo/servo/pull/19252/files

**Comment by tigercosmos** [comment]
Oh, that‘s why! #19252
