### ISSUE TITLE
Intermittently see unexpected results from a different test

### ISSUE THREAD

**Issue by jdm** [servo/servo#19354]
```
  ▶ ERROR [expected TIMEOUT] /XMLHttpRequest/xmlhttprequest-sync-default-feature-policy.sub.html
  └   → Got results from /XMLHttpRequest/xmlhttprequest-sync-default-feature-policy.sub.html#iframe#sync-xhr, expected /XMLHttpRequest/xmlhttprequest-sync-default-feature-policy.sub.html
Traceback (most recent call last):
  File "/Users/servo/buildbot/slave/mac-rel-wpt3/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 157, in run_test
    result = self.do_test(test)
  File "/Users/servo/buildbot/slave/mac-rel-wpt3/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 123, in do_test
    result = self.convert_result(test, self.result_data)
  File "/Users/servo/buildbot/slave/mac-rel-wpt3/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 67, in __call__
    (result_url, test.url))
AssertionError: Got results from /XMLHttpRequest/xmlhttprequest-sync-default-feature-policy.sub.html#iframe#sync-xhr, expected /XMLHttpRequest/xmlhttprequest-sync-default-feature-policy.sub.html
```

**Comment by lumiscosity** [comment]
Does this still happen?

**Comment by jdm** [comment]
Nope.
