### ISSUE TITLE
travis build error: `mp4parse_capi v0.9.1` build failed

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19420]
I notice that today's many PRs on travis encounter the error:
```bash
    Running `/home/travis/build/servo/servo/target/debug/build/mp4parse_capi-3af88effe49250ca/build-script-build`

error: failed to run custom build command for `mp4parse_capi v0.9.1`

process didn't exit successfully: `/home/travis/build/servo/servo/target/debug/build/mp4parse_capi-3af88effe49250ca/build-script-build` (exit code: 101)

--- stdout

cargo:rerun-if-changed=src/lib.rs

--- stderr

thread 'main' panicked at 'Could not generate header: "couldn\'t execute `cargo metadata` with manifest \"/home/travis/build/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mp4parse_capi-0.9.1/Cargo.toml\"."', /checkout/src/libcore/result.rs:906:4

note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...

error: build failed

[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.

Build FAILED in 0:15:48

The command "./mach build -d --verbose" exited with 101.

3.42s$ ./mach test-unit

   Compiling size_of_test v0.0.1 (file:///home/travis/build/servo/servo/components/size_of_test)

   Compiling script_plugins_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/script_plugins)

   Compiling deny_public_fields_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/deny_public_fields)

   Compiling servo_remutex_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/servo_remutex)

   Compiling mp4parse_capi v0.9.1

   Compiling servo-websocket v0.20.0

   Compiling hyper-openssl v0.2.6

error: failed to run custom build command for `mp4parse_capi v0.9.1`

process didn't exit successfully: `/home/travis/build/servo/servo/target/debug/build/mp4parse_capi-3af88effe49250ca/build-script-build` (exit code: 101)

--- stdout

cargo:rerun-if-changed=src/lib.rs

--- stderr

thread 'main' panicked at 'Could not generate header: "couldn\'t execute `cargo metadata` with manifest \"/home/travis/build/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mp4parse_capi-0.9.1/Cargo.toml\"."', /checkout/src/libcore/result.rs:906:4

stack backtrace:

   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace

             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49

   1: std::sys_common::backtrace::_print

             at /checkout/src/libstd/sys_common/backtrace.rs:68

   2: std::panicking::default_hook::{{closure}}

             at /checkout/src/libstd/sys_common/backtrace.rs:57

             at /checkout/src/libstd/panicking.rs:381

   3: std::panicking::default_hook

             at /checkout/src/libstd/panicking.rs:397

   4: std::panicking::rust_panic_with_hook

             at /checkout/src/libstd/panicking.rs:577

   5: std::panicking::begin_panic

             at /checkout/src/libstd/panicking.rs:538

   6: std::panicking::begin_panic_fmt

             at /checkout/src/libstd/panicking.rs:522

   7: rust_begin_unwind

             at /checkout/src/libstd/panicking.rs:498

   8: core::panicking::panic_fmt

             at /checkout/src/libcore/panicking.rs:71

   9: core::result::unwrap_failed

             at /checkout/src/libcore/macros.rs:23

  10: <core::result::Result<T, E>>::expect

             at /checkout/src/libcore/result.rs:799

  11: build_script_build::main

             at .cargo/registry/src/github.com-1ecc6299db9ec823/mp4parse_capi-0.9.1/build.rs:36

  12: __rust_maybe_catch_panic

             at /checkout/src/libpanic_unwind/lib.rs:99

  13: std::rt::lang_start

             at /checkout/src/libstd/panicking.rs:459

             at /checkout/src/libstd/panic.rs:365

             at /checkout/src/libstd/rt.rs:58

  14: main

  15: __libc_start_main

  16: <unknown>

warning: build failed, waiting for other jobs to finish...

error: build failed

The command "./mach test-unit" exited with 101.

1.48s$ ./mach clean
```

**Comment by avadacatavra** [comment]
Thanks for filing this @tigercosmos! We have a pending fix (https://github.com/servo/servo/pull/19413) and open issue to figure out why this is happening (https://github.com/servo/servo/issues/19418)
