### ISSUE TITLE
Servo build failing on Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by abhinav-koppula** [servo/servo#19710]
Hi Folks,
I am trying to build servo using the command ./mach build --dev
but the build is failing with the below exception. Can someone help me here?

Exception stacktrace:
```
[100%] Building CXX object CMakeFiles/gecko_core.dir/gecko/src/mozglue/misc/TimeStamp_posix.cpp.o
[100%] Building C object CMakeFiles/gecko_core.dir/gecko/src/nsprpub/pr/src/md/unix/linux.c.o
[100%] Built target gecko_core
Scanning dependencies of target gecko_media_cmake
Linking CXX static library libgecko_media_cmake.a
[100%] Built target gecko_media_cmake
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/abhinav/Documents/Projects/servo/target/debug/build/gecko-media-60fd900c154328b5/out/libgecko_media_cmake.a
cargo:root=/home/abhinav/Documents/Projects/servo/target/debug/build/gecko-media-60fd900c154328b5/out
cargo:rustc-link-search=native=/home/abhinav/Documents/Projects/servo/target/debug/build/gecko-media-60fd900c154328b5/out
cargo:rustc-link-lib=static=gecko_media_cmake
cargo:rustc-link-lib=stdc++
cargo:rustc-link-lib=dl

--- stderr
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/test.cpp: In function ‘void GeckoMedia_mozilla::RunOnTaskQueue(GeckoMedia_mozilla::TaskQueue*, FunctionType) [with FunctionType = GeckoMedia_mozilla::TestMozPromise()::<lambda()>]’:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/test.cpp:223:3: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
   aQueue->Dispatch(r.forget());
   ^
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/test.cpp: In function ‘void GeckoMedia_mozilla::RunOnTaskQueue(GeckoMedia_mozilla::TaskQueue*, FunctionType) [with FunctionType = GeckoMedia_mozilla::TestMozPromise()::<lambda()>]’:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/test.cpp:223:3: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/src/media/libopus/src/opus_decoder.c:37:10: note: #pragma message: You appear to be compiling without optimization, if so opus will be very slow.
 # pragma message "You appear to be compiling without optimization, if so opus will be very slow."
          ^
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/TestMP4Demuxer.cpp: In member function ‘void GeckoMedia_mozilla::MP4DemuxerBinding::DispatchTask(FunctionType) [with FunctionType = GeckoMedia_mozilla::MP4DemuxerBinding::CheckTrackSamples(GeckoMedia_mozilla::MediaTrackDemuxer*)::<lambda()>]’:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/TestMP4Demuxer.cpp:157:5: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
     mTaskQueue->Dispatch(r.forget());
     ^
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/TestMP4Demuxer.cpp: In member function ‘void GeckoMedia_mozilla::MP4DemuxerBinding::DispatchTask(FunctionType) [with FunctionType = GeckoMedia_mozilla::MP4DemuxerBinding::CheckTrackKeyFrame(GeckoMedia_mozilla::MediaTrackDemuxer*)::<lambda()>]’:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/test/TestMP4Demuxer.cpp:157:5: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
In file included from /home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/GeckoMediaSource.cpp:9:0:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/include/GeckoMediaMacros.h:65:80: warning: backslash-newline at end of file
 #define IMPL_GECKO_MEDIA_REFLECTOR(GMClass, Class, Callbacks)                  \
 ^
In file included from /home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/GeckoMediaSourceBuffer.cpp:9:0:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/include/GeckoMediaMacros.h:65:80: warning: backslash-newline at end of file
 #define IMPL_GECKO_MEDIA_REFLECTOR(GMClass, Class, Callbacks)                  \
 ^
In file included from /home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/GeckoMediaSourceBufferList.cpp:9:0:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/include/GeckoMediaMacros.h:65:80: warning: backslash-newline at end of file
 #define IMPL_GECKO_MEDIA_REFLECTOR(GMClass, Class, Callbacks)                  \
 ^
In file included from /home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/Player.cpp:12:0:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/glue/include/GeckoMediaMacros.h:65:80: warning: backslash-newline at end of file
 #define IMPL_GECKO_MEDIA_REFLECTOR(GMClass, Class, Callbacks)                  \
 ^
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/src/nsprpub/pr/src/pthreads/ptio.c: In function ‘pt_linux_sendfile_cont’:
/home/abhinav/Documents/Projects/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/fe43744/gecko-media/gecko/src/nsprpub/pr/src/pthreads/ptio.c:1104:5: warning: implicit declaration of function ‘sendfile’ [-Wimplicit-function-declaration]
     rv = sendfile(op->arg1.osfd, op->in_fd, &op->offset, op->count);
     ^
gecko/glue/include/GeckoMediaTypes.h:16:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions], err: false
gecko/glue/include/GeckoMediaSource.h:19:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions], err: false
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', .cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.21.1/src/lib.rs:1456:0
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Build FAILED in 0:25:00
```

**Comment by SimonSapin** [comment]
This seems to be the relevant error message.
```
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments',
```

Given you’re on 14.04, I assume that the libclang version is too old. @emilio, what’s the minimum?

**Comment by tigercosmos** [comment]
It's caused by `clang`, trying update to the latest version.

**Comment by emilio** [comment]
For c++, the minimum libclang version supported should be 3.8.

**Comment by abhinav-koppula** [comment]
Thanks for replying people.
I followed the below link to install clang-3.8.
https://askubuntu.com/questions/735201/installing-clang-3-8-on-ubuntu-14-04-3
then ran
```
sudo ln -s /usr/bin/clang-3.8 /usr/bin/clang
sudo ln -s /usr/bin/clang++-3.8 /usr/bin/clang++
```
Output as follows:
```
clang --version
clang version 3.8.0-2ubuntu3~trusty5 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

clang++ --version
clang version 3.8.0-2ubuntu3~trusty5 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Next ran ./mach build --dev

```
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /home/abhinav/Documents/Projects/servo/target/debug/build/gecko-media-60fd900c154328b5/out/libgecko_media_cmake.a
cargo:root=/home/abhinav/Documents/Projects/servo/target/debug/build/gecko-media-60fd900c154328b5/out
cargo:rustc-link-search=native=/home/abhinav/Documents/Projects/servo/target/debug/build/gecko-media-60fd900c154328b5/out
cargo:rustc-link-lib=static=gecko_media_cmake
cargo:rustc-link-lib=stdc++
cargo:rustc-link-lib=dl
--- stderr
gecko/glue/include/GeckoMediaTypes.h:16:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions], err: false
gecko/glue/include/GeckoMediaSource.h:19:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions], err: false
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', .cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.21.1/src/lib.rs:1456:0
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Build FAILED in 0:00:24
```

Still fails with same error, any suggestions?

**Comment by emilio** [comment]
Note that clang is not the same as `libclang`. You should be able to point `LIBCLANG_PATH` to wherever the `libclang.so` file lives.

**Comment by abhinav-koppula** [comment]
Ok, I installed libclang and the build moved ahead but this time gave a different error.
Excerpts of the error:
```
s-simple-sys-c37d43b0a6d3f902/out/lib`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" 
85e3aada3d7.rlib" "/home/abhinav/Documents/Projects/servo/.servo/rust/2017-11-14/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d1a5738b34068936.rlib" "-Wl,-Bdynamic" "-l" "dbus-1" "-l" "stdc++" "-l" "dl" "-l" "harfbuzz" "-l" "pthread" "-l" "stdc++" "-l" "stdc++" "-l" "dl" "-l" "xcb" "-l" "xcb" "-l" "xcb" "-l" "xcb" "-l" "GL" "-l" "skia" "-l" "GL" "-l" "stdc++" "-l" "freetype" "-l" "bz2" "-l" "fontconfig" "-l" "expat" "-l" "X11" "-l" "azure" "-l" "stdc++" "-l" "bz2" "-l" "GL" "-l" "X11" "-l" "expat" "-l" "ssl" "-l" "crypto" "-l" "stdc++" "-l" "z" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util" "-fuse-ld=gold"
  = note: /usr/bin/ld.gold: error: cannot find -lbz2
          /usr/bin/ld.gold: error: cannot find -lbz2
          .cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.9.0/src/platform/unix/mod.rs:601: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `servo`.

Caused by:
  process didn't exit successfully: `rustc --crate-name servo ports/servo/main.rs --crate-type bin --emit=dep-info,link -C codegen-units=4 -C debuginfo=2 --cfg feature="default" --cfg feature="default-except-unstable" --cfg feature="libservo" --cfg feature="log" --cfg feature="max_log_level" --cfg feature="unstable" --cfg feature="webdriver" -C metadata=34cc6d974b257777 -C extra-filename=-34cc6d974b257777 --out-dir /home/abhinav/Documents/Projects/servo/target/debug/deps -L dependency=/home/abhinav/Documents/Projects/servo/target/debug/deps --extern servo=/home/abhinav/Documents/Projects/servo/target/debug/deps/libservo-00103e70dfd03c96.rlib --extern glutin_app=/home/abhinav/Documents/Projects/servo/target/debug/deps/libglutin_app-6a2c7648db1d869a.rlib --extern backtrace=/home/abhinav/Documents/Projects/servo/target/debug/deps/libbacktrace-52509c66bc535c44.rlib --extern sig

```

**Comment by jdm** [comment]
You need to install the libbz2-dev package.

**Comment by abhinav-koppula** [comment]
Yay, it worked. Thanks a lot.
@jdm - So on launching servo using  `./mach run https://www.mozilla.org`, I am not able to completely scroll to the bottom of the page, it just gets stuck after scrolling a small amount.
Is this because this is still under development or is it something to do with my system?

**Comment by jdm** [comment]
I would expect that it's a general bug in servo, rather than specific to your system.
