### ISSUE TITLE
Intermittent python/cmake segfault during codegen on servo-mac3

### ISSUE THREAD

**Issue by jdm** [servo/servo#20087]
```
--- stderr
make[2]: *** [Bindings/DOMTokenListBinding.rs] Segmentation fault: 11
make[2]: *** Deleting file `Bindings/DOMTokenListBinding.rs'
make[1]: *** [CMakeFiles/DOMTokenList.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:632:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::begin_panic
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::try::do_call
             at libstd/panicking.rs:521
   7: cmake::fail
             at /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:632
   8: cmake::run
             at /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:613
   9: <&'a mut T as core::fmt::Debug>::fmt
             at /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:520
  10: build_script_build::main
             at components/script/build.rs:45
  11: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  14: std::sys_common::bytestring::debug_fmt_bytestring
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  16: <build_script_build::Bytes<'a> as core::hash::Hash>::hash

warning: build failed, waiting for other jobs to finish...
error: build failed
[Warning] Could not generate notification! Optional Python module 'pyobjc' is not installed.
Build FAILED in 0:08:59
```

**Comment by jdm** [comment]
I've tried rebooting servo-mac3.

**Comment by jdm** [comment]
This continues to happen since the reboot.

**Comment by dralley** [comment]
Is this still the case?

**Comment by jdm** [comment]
No.
