### ISSUE TITLE
Python exceptions when closing WPT window

### ISSUE THREAD

**Issue by jdm** [servo/servo#20416]
```
 0:11.04 LOG: Thread-TestrunnerManager-1 INFO Pausing until the browser exits
 0:11.04 LOG: Thread-TestrunnerManager-1 ERROR Error running command wait with arguments ():
Traceback (most recent call last):
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 91, in run
    rv = commands[command](*args)
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 111, in wait
    self.executor.wait()
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 204, in wait
    self.protocol.base.wait()
AttributeError: 'ConnectionlessProtocol' object has no attribute 'base'

 0:11.04 LOG: Thread-TestrunnerManager-1 ERROR Traceback (most recent call last):
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 360, in run
    new_state = self.wait_event()
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 435, in wait_event
    return f(*data)
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 636, in error
    self.restart_runner()
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 627, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError

 0:11.05 LOG: Thread-TestrunnerManager-1 WARNING u'runner_teardown': ()
 0:11.05 LOG: Thread-Log INFO STDERR: Exception in thread Thread-TestrunnerManager-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 360, in run
    new_state = self.wait_event()
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 435, in wait_event
    return f(*data)
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 636, in error
    self.restart_runner()
  File "/Users/jdm/src/master-servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 627, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError
 0:11.05 LOG: MainThread INFO Got 0 unexpected results
 0:11.05 SUITE_END: MainThread
```

**Comment by jdm** [comment]
```diff
diff --git a/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py b/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py
index 708903f5dc..fbb75d658c 100644
--- a/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py
+++ b/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py
@@ -8,7 +8,7 @@ import urlparse
 from abc import ABCMeta, abstractmethod

 from ..testrunner import Stop
-from protocol import Protocol
+from protocol import Protocol, BaseProtocolPart

 here = os.path.split(__file__)[0]

@@ -411,7 +411,23 @@ class WdspecRun(object):
             self.result_flag.set()


+class ConnectionlessBaseProtocolPart(BaseProtocolPart):
+    def execute_script(self, script, async=False):
+        pass
+
+    def set_timeout(self, timeout):
+        pass
+
+    def wait(self):
+        pass
+
+    def set_window(self, handle):
+        pass
+
+
 class ConnectionlessProtocol(Protocol):
+    implements = [ConnectionlessBaseProtocolPart]
+
     def connect(self):
         pass
```
@jgraham How does this look?

**Comment by jgraham** [comment]
Yeah, that looks right. Apologies for missing this. We should add servo to the upstream smoketests now that we can download it.
