### ISSUE TITLE
Mozilla Hubs complains about setAttribute being read-only

### ISSUE THREAD

**Issue by jdm** [servo/servo#20748]
https://hubs.mozilla.com/

Output:
```
A-Frame Version: 0.7.0 (Date 2018-03-13, Commit #1e49f5e)
three Version:
github:brianpeiris/three.js#r90-culling-fix-built
WebVR Polyfill Version:
^0.9.40
ERROR 2018-05-04T19:14:52Z: script::dom::bindings::error: Error at https://assets-prod.reticulum.io/assets/js/hub-9068a3480f468c6337b2.js:1:1163005 missing : after property id
ERROR 2018-05-04T19:14:52Z: script::dom::bindings::error: Error at https://cdn.rawgit.com/brianpeiris/aframe/845825ae694449524c185c44a314d361eead4680/dist/aframe-master.min.js:32:959 "setAttribute" is read-only
%ccore:a-node:warn %cYou are attempting to attach <A-SCENE> outside of an A-Frame scene. Append this element to `<a-scene>` instead.%c
color: orange
color: inherit
color: orange
ERROR 2018-05-04T19:14:55Z: script::dom::bindings::error: Error at https://cdn.rawgit.com/brianpeiris/aframe/845825ae694449524c185c44a314d361eead4680/dist/aframe-master.min.js:482:6992 this.systems is undefined
```

**Comment by jdm** [comment]
This error goes away if we run Servo with `--pref dom.mutation_observer.enabled`.

**Comment by jdm** [comment]
Fixed by defaulting that pref to true.
