### ISSUE TITLE
Android builders are broken when launching python

### ISSUE THREAD

**Issue by jdm** [servo/servo#20774]
```
"/usr/local/bin/virtualenv" "-p" "/usr/bin/python2.7" "--system-site-packages" "/home/servo/buildbot/slave/android/build/python/_virtualenv" failed with error code 1:
Output:
New python executable in /home/servo/buildbot/slave/android/build/python/_virtualenv/bin/python2.7
Not overwriting existing python script /home/servo/buildbot/slave/android/build/python/_virtualenv/bin/python (you must use /home/servo/buildbot/slave/android/build/python/_virtualenv/bin/python2.7)
Running virtualenv with interpreter /usr/bin/python2.7
Error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2304, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 924, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 843, in install_wheel
    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
  File "/usr/lib/python2.7/pkgutil.py", line 578, in get_data
    loader = get_loader(package)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/utils/__init__.py", line 26, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3130, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3116, in _call_aside
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 956, in subscribe
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3155, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2655, in activate
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2225, in declare_namespace
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2194, in _handle_ns
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2192, in sort_key
ValueError: '/usr/local/lib/python2.7/dist-packages' is not in list
```
This isn't treated as a buildbot error, but the check_dynamic_symbols.py step fails because libservo.so is missing.

**Comment by jdm** [comment]
This was caused by the first deploy that included https://github.com/servo/saltfs/pull/830. Unfortunately it has affected every single linux build machine by overwriting the installed version of (presumably) virtualenv, in such a way that I have not found a way to undo the problem. Reverting the salt change and highstateing a brand new linux machine yields a working build environment, so the plan is to recreate all of the linux build machines from scratch.

@edunham you should be aware of this plan!

**Comment by jdm** [comment]
Recreated:
* [ ] servo-linux1
* [ ] servo-linux2
* [ ] servo-linux3
* [ ] servo-linux4
* [ ] servo-linux5
* [ ] servo-linux6
* [ ] servo-linux-cross1
* [ ] servo-linux-cross2
* [ ] servo-linux-cross3

Highstated:
* [ ] servo-linux1
* [ ] servo-linux2
* [ ] servo-linux3
* [ ] servo-linux4
* [ ] servo-linux5
* [ ] servo-linux6
* [ ] servo-linux-cross1
* [ ] servo-linux-cross2
* [ ] servo-linux-cross3

DNS updated:
* [ ] servo-linux1
* [ ] servo-linux2
* [ ] servo-linux3
* [ ] servo-linux4
* [ ] servo-linux5
* [ ] servo-linux6
* [ ] servo-linux-cross1
* [ ] servo-linux-cross2
* [ ] servo-linux-cross3

**Comment by jdm** [comment]
The servo-linux1 issue may be caused by having the buildbot service start in the middle of highstateing while a build was pending.

**Comment by edunham** [comment]
I will: 
- [x] PR a fix to not apply the problem changes to any more linuxes (https://github.com/servo/saltfs/pull/839/files)
- [ ] Recreate servo-linux-cross2 with disk matching cross1
- [ ] manually set up venv on servo-linux1
- [ ] fix perms on servo-linux3

**Comment by jdm** [comment]
I removed the venv for linux-rel-css on servo-linux1 and I'm performing another highstate while no builds are running to test my theory.

**Comment by jdm** [comment]
This is the error causing pip installation to fail:
`awscli 1.15.19 has requirement botocore==1.10.19, but you'll have botocore 1.5.95 which is incompatible.`
I think the easiest path forward is to follow https://github.com/servo/saltfs/issues/765#issuecomment-352467079 and switch the awscli installation to use the system package rather than pip.

**Comment by jdm** [comment]
I ran `chmod +x` on contents of `android/ndk/r12b/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/` on servo-linux-cross3.

**Comment by jdm** [comment]
We will need to deploy https://github.com/servo/saltfs/pull/840, fix #20784, and fix https://github.com/servo/servo/pull/20782#issuecomment-388872460 before #20782 can merge.

**Comment by edunham** [comment]
@jdm For the DNS stuff, are the correct hosts the ones currently running in AWS?

Also, will you be on IRC today? I'd rather ask you about the details of this in a shorter loop than comments if that's possible.

**Comment by jdm** [comment]
I'm on my way to the MR meeting. The correct hosts are the running EC2 instances.

**Comment by edunham** [comment]
OK, safe travels. I'll look at DNS when I get a chance and talk to you when you get here :)

**Comment by edunham** [comment]
Linux-cross[1-3] and linux-[1-6] DNS is now up to date with the new AWS hosts.

**Comment by edunham** [comment]
Uninstalling pip's aws cli with `salt servo-linux* pip.uninstall awscli` on master

**Comment by jdm** [comment]
servo-linux-cross3 continues to be in a surprising state:
```
arm-linux-androideabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
```

**Comment by edunham** [comment]
Android builds are seeing this breakage of the form 
```
make[1]: Leaving directory `/home/servo/buildbot/slave/android/build/target/armv7-linux-androideabi/debug/native/openssl/openssl-1.0.2k'

Configured for android-armv7.

*** Because of configuration changes, you MUST do the following before
*** building:

	make depend
```

since May 9th -- see http://build.servo.org/builders/android

**Comment by jdm** [comment]
Latest status!
* servo-linux-cross2 had correct permissions on android NDK files
* I deleted the android NDK directories on servo-linux-cross1 and servo-linux-cross3 and re-deployed. The permissions on those directories are now correct.
* #20784 does not appear to be blocking us any more.
* servo-mac1 has segfaulted while running clang in http://build.servo.org/builders/mac-rel-wpt1/builds/8539/steps/compile/logs/stdio . This may be a symptom of OOM on the build machine?

**Comment by jdm** [comment]
Oh, servo-linux-cross1 mystery is solved - the Android SDK totally did not finish installing correctly. Only the tools directory is present, while other build machines have several other directories as well.

**Comment by jdm** [comment]
Looks like servo-linux-cross3 is in the same state. I will delete those SDK directories and re-deploy.

**Comment by jdm** [comment]
The latest android build for #20782 passed.

**Comment by jdm** [comment]
servo-linux-cross2 is not in a good state (http://build.servo.org/builders/android/builds/11510). servo-linux2 is in a similarly bad state (http://build.servo.org/builders/linux-rel-css/builds/8721).

**Comment by jdm** [comment]
Successful builds have occurred on those machines, and #20782 merged. I'm declaring this fixed!
