### ISSUE TITLE
Chaos monkey test sometimes has JSON decode errors

### ISSUE THREAD

**Issue by jdm** [servo/servo#20788]
```
Traceback (most recent call last):
  File "./etc/ci/chaos_monkey_test.py", line 40, in <module>
    report = json.loads(line.decode('utf-8'))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 83 - line 2 column 1 (char 82 - 244)
```

**Comment by jdm** [comment]
We don't run these tests any longer.
