### ISSUE TITLE
A-Frame snowglobe example throws a bunch of errors

### ISSUE THREAD

**Issue by jdm** [servo/servo#20800]
```
godot:master-servo jdm$ ./mach run -d --pref dom.mutation_observer.enabled https://aframe.io/examples/showcase/snowglobe/
ERROR 2018-05-17T19:53:28Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
ERROR 2018-05-17T19:53:28Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
ERROR 2018-05-17T19:53:28Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
ERROR 2018-05-17T19:53:28Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
ERROR 2018-05-17T19:53:29Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
ERROR 2018-05-17T19:53:29Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
ERROR 2018-05-17T19:53:29Z: script::dom::bindings::error: Error at https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js:2:55856 Error: No input element in the page matches .docs-search-sidebar .search-field
ERROR 2018-05-17T19:53:29Z: webrender::display_list_flattener: Unknown pipeline used for iframe IframeDisplayItem { clip_id: Clip(8, PipelineId(0, 1)), pipeline_id: PipelineId(1, 3) }
A-Frame Version: 0.5.0 (Date 10-02-2017, Commit #bf8b8f9)
three Version:
^0.83.0
WebVR Polyfill Version:
dmarcos/webvr-polyfill#a02a8089b
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
ERROR 2018-05-17T19:53:36Z: script::dom::bindings::error: Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:37:22073 t.buffered is undefined
%ccore:a-assets:warn %cAsset loading timed out in %c +0ms
color: orange
color: inherit
color: orange
3000
ms
%ccore:propertyTypes:warn %c`src` property type is deprecated. Use `asset` instead.%c +374ms
color: lightseagreen
color: inherit
color: lightseagreen
```

**Comment by jdm** [comment]
These errors no longer appear. Now there is this when you press the button to begin the experience:
```
[2019-08-21T13:37:04Z ERROR script::dom::bindings::error] Error at https://2017.ronikdesign.com/assets/javascripts/main.cc7574a72bb706e76c70.js:43:28710 intro is not defined
SecurityError: The operation is insecure.
```

**Comment by jdm** [comment]
Based on reading the code, that looks like it would be fixed by #19904.
