### ISSUE TITLE
Finding Love demo fails to sniff the user agent

### ISSUE THREAD

**Issue by jdm** [servo/servo#20811]
It's more complicated than just sniffing the user agent, unfortunately:
```
godot:master-servo jdm$ ./mach run -d --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:62.0) Gecko/20100101 Firefox/62.0" --pref dom.gamepad.enabled --pref dom.mutation_observer.enabled https://findinglove.activetheory.net/
ERROR 2018-05-17T20:44:32Z: script::dom::bindings::error: Error at https://findinglove.activetheory.net/assets/js/findinglove.js:11:37861 "WebKit|Moz|MS|O".match(...) is null
ERROR 2018-05-17T20:44:32Z: script::dom::bindings::error: Error at https://findinglove.activetheory.net/assets/js/findinglove.js:11:2559 LinkedList is not defined
```
The code in question:
```js
var styles=window.getComputedStyle(document.documentElement,"");
pre=(Array.prototype.slice.call(styles).join("").match(/-(moz|webkit|ms)-/)||styles.OLink===""&&["","o"])[1];
var dom="WebKit|Moz|MS|O".match(new RegExp("("+pre+")","i"))[1]
```

**Comment by jdm** [comment]
The code in question is looking for vendor-prefixed CSS properties so it can decide what prefix to use, I suppose. However, the page in question has an expired SSL certificate and #34685 makes that impossible to ignore at the moment.

**Comment by mrobinson** [comment]
I think this is the same reason we fail to run MotionMark: #13373. Implementing any vendor prefixed longhand should fix it.

**Comment by mrobinson** [comment]
Hrm. The new failure is this one:

```
[2026-04-03T10:17:49Z ERROR script::dom::globalscope] Error at https://findinglove.activetheory.net/assets/js/findinglove.js:33:9325 this.object.elementNS.getTotalLength is not a function
```

**Comment by jdm** [comment]
Probably https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/getTotalLength
