### ISSUE TITLE
Identify webgl benchmarks

### ISSUE THREAD

**Issue by jdm** [servo/servo#21057]
* https://webglsamples.org/aquarium/aquarium.html
* https://files.unity3d.com/jonas/benchmark2015/
* http://www.fishgl.com/
* https://luic.github.io/WebGL-Performance-Benchmark/
* https://github.com/greggman/webgl-benchmarks
* http://webglreport.com/
* https://media.tojicode.com/q3bsp/
* http://madebyevan.com/webgl-water/
* https://browserbench.org/MotionMark/developer.html?test-interval=30&display=minimal&tiles=big&controller=ramp&frame-rate=50&kalman-process-error=1&kalman-measurement-error=4&time-measurement=performance&suite-name=3DGraphics&test-name=WebGL

**Comment by jdm** [comment]
The 2015 benchmark requires #19904 to run.

**Comment by jdm** [comment]
FishGL spits out `ERROR 2018-07-12T18:31:14Z: script::dom::bindings::error: Error at http://www.fishgl.com/scripts/app.js:2:22886 this.sounds[a].volume is undefine` endlessly and I can't click anything.

**Comment by jdm** [comment]
http://luic.github.io/WebGL-Performance-Benchmark/benchmark/fillpixel-nozbuffer.html reports `ERROR 2018-07-12T18:39:27Z: script::dom::bindings::error: Error at http://luic.github.io/WebGL-Performance-Benchmark/benchmark/libraries/d3.v3/d3.v3.js:742:7 this.style is undefined` after running for a few seconds.

**Comment by jdm** [comment]
http://luic.github.io/WebGL-Performance-Benchmark/benchmark/cubes.html reaches 0 cubes without hitting the target FPS, which is not a great result.

**Comment by jdm** [comment]
After dealing with #21174, MotionMark 3d results:
Firefox:
<img width="767" alt="screen shot 2018-07-13 at 4 31 43 pm" src="https://user-images.githubusercontent.com/27658/42712605-447cb590-86ba-11e8-8424-3a703042b753.png">

Servo:
<img width="927" alt="screen shot 2018-07-13 at 4 30 16 pm" src="https://user-images.githubusercontent.com/27658/42712550-1714d8bc-86ba-11e8-91e5-0a4b01d8249d.png">
