### ISSUE TITLE
The CI infra is busted, late June edition

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#21108]
The homu queue was stuck this morning, with 6 PRs ready but none pending, and buildbot being idle. After restarting them both, homu went through the entire queue and everything failed with:

```
error in RunProcess._startCommand
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/buildslave/runprocess.py", line 426, in start
    self._startCommand()
  File "/usr/local/lib/python2.7/dist-packages/buildslave/runprocess.py", line 550, in _startCommand
    usePTY=self.usePTY)
  File "/usr/local/lib/python2.7/dist-packages/buildslave/runprocess.py", line 572, in _spawnProcess
    processProtocol, uid, gid, childFDs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 728, in __init__
    self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 405, in _fork
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by SimonSapin** [comment]
CC @edunham @aneeshusa @jdm

**Comment by SimonSapin** [comment]
Free RAM on linux builders:

```
% for host in $(curl -s http://build.servo.org/json/slaves|jq 'keys | .[]' -r -|grep linux); do echo ====== $host; ssh -o 'ConnectTimeout 2' $host.servo.org free -h|grep buffers; done 
====== servo-linux-cross1
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       538M       6.8G
====== servo-linux-cross2
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       506M       6.8G
====== servo-linux-cross3
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       5.0G       2.3G
====== servo-linux1
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       1.6G        27G
====== servo-linux2
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       2.3G        27G
====== servo-linux3
ssh: connect to host servo-linux3.servo.org port 22: Connection timed out
====== servo-linux4
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       1.4G        27G
====== servo-linux5
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       1.6G        27G
====== servo-linux6
             total       used       free     shared    buffers     cached
-/+ buffers/cache:       3.1G        26G
```

`servo-linux-cross3` is the outlier, and seems to match failing jobs. Its `/usr/bin/python /usr/local/bin/buildslave start --nodaemon /home/servo/buildbot/slave` process is using 4.7 GB RSS while idle. For comparison, on `servo-linux-cross2` the same process takes 22 MB.

Clicking "Graceful shutdown" on http://build.servo.org/buildslaves/servo-linux-cross3 solves the RAM issue, but now that builder is disconnected.

Running `salt "servo-linux-cross3" state.highstate 2>&1 --force-color | tee salt_highstate_issue_servo_21108.log` on `servo-master` did not help. It ended with `Failed:     2`, some of the red includes:

```
          ID: /home/servo/buildbot/slave
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 10:12:17.842137
    Duration: 2026.132 ms
```
```
          ID: buildbot-slave
    Function: service.running
      Result: False
     Comment: One or more requisite failed: buildbot.slave./home/servo/buildbot/slave
```

**Comment by SimonSapin** [comment]
Current status: infra seems to be unblocked (https://github.com/servo/servo/pull/21102 has landed), but it is running at reduced capacity. `servo-linux-cross3` is not connected to buildbot because I shut it down and didn’t figure out how to bring it back up. `servo-mac1` and `servo-mac5` are as well, but I don’t know why.

**Comment by edunham** [comment]
Cross3 is back -- `service buildbot-slave start` on the host fixed it, though highstate errored.

**Comment by SimonSapin** [comment]
Thank you!
