### ISSUE TITLE
First build failed at macOS [pypi certificate]

### ISSUE THREAD

**Issue by marinintim** [servo/servo#21123]
Hi, I'm trying to build Servo on macOS (High Sierra).

As far as I understand, the issue is not with servo itself, but I want to track this issue there as well (so others could find it more easily)

```sh
  17:59:37 as mt on MacBook-Pro-Timofej in ~/Projects/workmate/servo at master
→ ./mach build --dev
"/Users/mt/Projects/workmate/servo/python/_virtualenv/bin/python2.7" "-m" "pip" "install" "-I" "-r" "/Users/mt/Projects/workmate/servo/python/requirements.txt" failed with error code 1:
Output:
Obtaining file:///Users/mt/Projects/workmate/servo/python/tidy (from -r /Users/mt/Projects/workmate/servo/python/requirements.txt (line 35))
Collecting blessings==1.6 (from -r /Users/mt/Projects/workmate/servo/python/requirements.txt (line 4))
  Could not fetch URL https://pypi.org/simple/blessings/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/blessings/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) - skipping
Error:
From cffi callback <function _verify_callback at 0x10500ff50>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/blessings/
From cffi callback <function _verify_callback at 0x106c58b90>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/blessings/
From cffi callback <function _verify_callback at 0x106c58a28>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/blessings/
From cffi callback <function _verify_callback at 0x106c588c0>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/blessings/
From cffi callback <function _verify_callback at 0x106c58488>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/blessings/
From cffi callback <function _verify_callback at 0x1071fa050>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement blessings==1.6 (from -r /Users/mt/Projects/workmate/servo/python/requirements.txt (line 4)) (from versions: )
No matching distribution found for blessings==1.6 (from -r /Users/mt/Projects/workmate/servo/python/requirements.txt (line 4))
(env)
  18:01:22 as mt on MacBook-Pro-Timofej in ~/Projects/workmate/servo at master
→
```

**Comment by CYBAI** [comment]
```
Obtaining file:///Users/mt/Projects/workmate/servo/python/tidy (from -r /Users/mt/Projects/workmate/servo/python/requirements.txt (line 35))
Collecting blessings==1.6 (from -r /Users/mt/Projects/workmate/servo/python/requirements.txt (line 4))
  Could not fetch URL https://pypi.org/simple/blessings/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/blessings/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) - skipping
Error:
```

Seems you've already failed to install the pip module due to SSL error.
Could you try to check your OpenSSL version in python ?

```sh
python -c "import ssl; print(ssl.OPENSSL_VERSION)"
```

Ref: https://github.com/pypa/pip/issues/5226#issuecomment-392492858

**Comment by marinintim** [comment]
@CYBAI:

```
→ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by nicoabie** [comment]
@marinintim can you check if this is solved now?

**Comment by jdm** [comment]
I'm going to go ahead and close this proactively, given the age.
