### ISSUE TITLE
NYTimes article about cedars of lebanon panics while communicating with layout thread

### ISSUE THREAD

**Issue by jdm** [servo/servo#21208]
https://www.nytimes.com/interactive/2018/07/18/climate/lebanon-climate-change-environment-cedars.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=photo-spot-region&region=top-news&WT.nav=top-news

```
godot:master-servo jdm$ ./mach run -r "https://www.nytimes.com/interactive/2018/07/18/climate/lebanon-climate-change-environment-cedars.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=photo-spot-region&region=top-news&WT.nav=top-news"
init
init
init
init
evaluating function

       0000000                         000        0000000
     111111111      11111111100          000      111111111
     00000        111111111111111111      00000      000000
     000        1111111111111111111111111100000         000
     000        1111       1111111111111111100          000
     000         11       0     1111111100              000
     000          1      00             1               000
     000               00      00       1               000
     000             000    00000       1               000
  00000            0000  00000000       1                00000
11111            000 00    000000      000                 11111
  00000          0000      000000     00000              00000
     000        10000      000000      000              0000
     000        00000      000000       1               000
     000        000000     10000        1     0         000
     000        1000000 00              1    00         000
     000         1111111                1 0000          000
     000          1111111100           000000           000
     0000          111111111111111110000000            0000
     111111111        111111111111100000          111111111
       0000000              00000000              0000000



NYTimes.com: All the code that's fit to printf()
We're hiring: developers.nytimes.com/careers



No Gateway Parameter
opty_payload
[object Object]
cover is loading
[OptimizelyNYT] growl Impression ID:Nons | Default NYT5 Experience | All Geos | 2018-05-11 – ongoing
ERROR 2018-07-19T12:55:21Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
error in _handler
TypeError: frames.__bkframe is undefined
ERROR 2018-07-19T12:55:24Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
ERROR 2018-07-19T12:55:25Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
ERROR 2018-07-19T12:55:25Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
ERROR 2018-07-19T12:55:26Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at libcore/result.rs:945)
stack backtrace:
   0:        0x106b54dde - backtrace::backtrace::trace::h53c90f7e693c3e4a
   1:        0x106b5588c - _$LT$backtrace..capture..Backtrace$u20$as$u20$core..default..Default$GT$::default::hf26626fd61b15e6b
   2:        0x106b558dd - backtrace::capture::Backtrace::new::he239b90a51ed8f1d
   3:        0x1042a6ace - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h6df244054f8391a2
   4:        0x106b7af7e - std::panicking::rust_panic_with_hook::hb67a9393fa2dec62
   5:        0x106b7aace - std::panicking::continue_panic_fmt::ha4f4d262ed9b35ca
   6:        0x106b7a9b8 - rust_begin_unwind
   7:        0x106b97261 - core::panicking::panic_fmt::hdf64b1a464eabfa2
   8:        0x104fef40d - core::result::unwrap_failed::h8cb037d721abe74c
   9:        0x10523da5d - script::dom::window::Window::force_reflow::h46440a2a261796a3
  10:        0x10523e1aa - script::dom::window::Window::reflow::h97b64431161dc42b
  11:        0x10502f81c - script::dom::element::Element::has_css_layout_box::h8a65f99ec3e294f6
  12:        0x104a2ffa8 - script::script_thread::ScriptThread::handle_msg_from_constellation::h8336d0e2e57611ca
  13:        0x104a2b6d2 - script::script_thread::ScriptThread::handle_msgs::h367d0d3e4e49408d (.llvm.10296180611949601579)
  14:        0x104dda317 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::h57fb89243b38497d
  15:        0x1050f3c70 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d499fe555221e5f
  16:        0x1046e613d - std::panicking::try::do_call::h91ad2b717e34d2d5 (.llvm.480075607669524226)
  17:        0x106b8700e - __rust_maybe_catch_panic
  18:        0x1052925e6 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h7f75dc49f5bc085e
  19:        0x106b5e50b - std::sys::unix::thread::Thread::new::thread_start::hfdfbf4ce872c8486
  20:     0x7fff9fbbb93a - _pthread_body
  21:     0x7fff9fbbb886 - _pthread_start
ERROR 2018-07-19T12:55:26Z: servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"
```

**Comment by jdm** [comment]
It would be worth figuring out if this is a layout thread that already exited or was never created somehow.
