### ISSUE TITLE
Servo is not running on Windows 10 (potentially display driver issue)

### ISSUE THREAD

**Issue by jasonwilliams** [servo/servo#21227]
Servo is not running for me on Windows 10 
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

**Display Driver issues**
Since updating to Windows 10 Spring Edition my display drivers haven't been working properly, and Windows defaults back to some built-in fallback driver.
At this point i'm not sure if this is affecting Servo from running but its likely, especially seeing that other Windows 10 builds are working.

I hope to get a new GPU next week and try it again to see if it has an affect

```
λ .\mach.bat run tests\html\about-mozilla.html
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Failed to create window.: NoAvailablePixelFormat (thread main, at libcore\result.rs:945)
stack backtrace:
   0:     0x7ff782df4555 - backtrace::backtrace::trace<closure>
                        at C:\Users\jasew\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.2\src\backtrace\mod.rs:42
   1:     0x7ff780759424 - backtrace::capture::Backtrace::new
                        at C:\Users\jasew\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.2\src\capture.rs:64
   2:     0x7ff77f6c808b - servo::main::{{closure}}
                        at C:\Users\jasew\workspace\servo\ports\servo\main.rs:146
   3:     0x7ff7807627e2 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:470
   4:     0x7ff780762357 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:350
   5:     0x7ff780762310 - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:328
   6:     0x7ff78077c7cd - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:71
   7:     0x7ff7802cdae7 - core::result::unwrap_failed<glutin::CreationError>
                        at C:\projects\rust\src\libcore\macros.rs:26
   8:     0x7ff77f6a407e - core::result::Result<glutin::GlWindow, glutin::CreationError>::expect<glutin::GlWindow,glutin::CreationError>
                        at C:\projects\rust\src\libcore\result.rs:809
   9:     0x7ff77f73500e - servo::glutin_app::window::Window::new
                        at C:\Users\jasew\workspace\servo\ports\servo\glutin_app\window.rs:214
  10:     0x7ff77f70018e - servo::glutin_app::create_window
                        at C:\Users\jasew\workspace\servo\ports\servo\glutin_app\mod.rs:19
  11:     0x7ff77f69f708 - servo::main
                        at C:\Users\jasew\workspace\servo\ports\servo\main.rs:163
  12:     0x7ff77f705170 - std::rt::lang_start::{{closure}}<()>
                        at C:\projects\rust\src\libstd\rt.rs:74
  13:     0x7ff780762257 - std::panicking::try::do_call<closure,i32>
                        at C:\projects\rust\src\libstd\panicking.rs:310
  14:     0x7ff78077ab92 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  15:     0x7ff78075e403 - std::rt::lang_start_internal
                        at C:\projects\rust\src\libstd\rt.rs:58
  16:     0x7ff77f705148 - std::rt::lang_start<()>
                        at C:\projects\rust\src\libstd\rt.rs:74
  17:     0x7ff77f6a0243 - main
  18:     0x7ff786149bfd - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  19:     0x7ffe10963034 - BaseThreadInitThunk
Servo exited with return value 101
```

**Screenshot**
![displaydriver](https://user-images.githubusercontent.com/936006/43045585-492070b4-8db3-11e8-8d4a-8afa411fc77b.png)

![displaydriverstopped](https://user-images.githubusercontent.com/936006/43045586-4935ae7a-8db3-11e8-9ba2-5db212daee4f.png)

**Comment by jasonwilliams** [comment]
@paulrouget 

```
λ cargo run --example window
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading winit v0.16.2
 Downloading lazy_static v1.0.2
 Downloading shared_library v0.1.9
 Downloading khronos_api v2.2.0
 Downloading bitflags v1.0.3
   Compiling khronos_api v2.2.0
   Compiling bitflags v1.0.3
   Compiling cfg-if v0.1.4
   Compiling winapi v0.3.5
   Compiling lazy_static v1.0.2
   Compiling libc v0.2.42
   Compiling xml-rs v0.7.0
   Compiling log v0.4.3
   Compiling shared_library v0.1.9
warning: not embedding natvis: lld-link may not support the flag        ] 4/19: khronos_api, winapi, xml-rs, log, shared_library

warning: not embedding natvis: lld-link may not support the flag        ] 6/19: khronos_api, winapi, xml-rs

   Compiling gl_generator v0.9.0
   Compiling glutin v0.17.0 (file:///C:/Users/jasew/workspace/glutin)
warning: not embedding natvis: lld-link may not support the flag       ] 13/19: winapi, glutin

   Compiling winit v0.16.2
warning: unreachable pattern====================================>      ] 17/19: glutin
   --> src\lib.rs:479:13
    |
479 |             CreationError::NotSupported(_) => "Some of the requested attributes are not supported",
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unreachable_patterns)] on by default

warning: field is never used: `config_id`
  --> src\api\egl\mod.rs:45:5
   |
45 |     config_id: ffi::egl::types::EGLConfig,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: not embedding natvis: lld-link may not support the flag===>   ] 18/19: glutin

    Finished dev [unoptimized + debuginfo] target(s) in 25.46s
     Running `target\debug\examples\window.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\examples\window.exe` (exit code: 101)
```

Testing
```
λ cargo test window
   Compiling glutin v0.17.0 (file:///C:/Users/jasew/workspace/glutin)
warning: unused import: `std::ptr`========================>            ] 20/25: glutin, glutin, glutin, glutin, glutin
 --> tests\headless.rs:3:5
  |
3 | use std::ptr;
  |     ^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `gl::types::*`
 --> tests\headless.rs:9:5
  |
9 | use gl::types::*;
  |     ^^^^^^^^^^^^

warning: unused import: `glutin::GlContext`
  --> tests\headless.rs:10:5
   |
10 | use glutin::GlContext;
   |     ^^^^^^^^^^^^^^^^^

warning: not embedding natvis: lld-link may not support the flag

warning: unreachable pattern
   --> src\lib.rs:479:13
    |
479 |             CreationError::NotSupported(_) => "Some of the requested attributes are not supported",
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unreachable_patterns)] on by default

warning: not embedding natvis: lld-link may not support the flag       ] 21/25: glutin, glutin, glutin, glutin

warning: field is never used: `config_id`
  --> src\api\egl\mod.rs:45:5
   |
45 |     config_id: ffi::egl::types::EGLConfig,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: not embedding natvis: lld-link may not support the flag

warning: not embedding natvis: lld-link may not support the flag       ] 22/25: glutin, glutin, glutin

warning: not embedding natvis: lld-link may not support the flag

    Finished dev [unoptimized + debuginfo] target(s) in 1.92s
     Running target\debug\deps\glutin-9b992133cefb05e8.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\headless-882f61771ef5e3d6.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests glutin

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out
```

**Comment by jasonwilliams** [comment]
@paulrouget ive just installed my new GPU and got my graphics drivers working again. rebuilt Servo and now its working again
