### ISSUE TITLE
Crash (illegal instruction) while browsing http://anandtech.com

### ISSUE THREAD

**Issue by ghost** [servo/servo#21238]
Page loads, browsing the site ends up with a crash.

    $ ./servo --version
    Servo 0.0.1-4997ec2
    
    $ ./servo http://anandtech.com
    ...
    Illegal instruction (core dumped)
    
    $ gdb servo core.ScriptThread\ Pi.9889
    (gdb) bt
    #0  0x0000558dabb63142 in servo::install_crash_handler::handler ()
    #1  <signal handler called>
    #2  0x0000558dabb63142 in servo::install_crash_handler::handler ()
    #3  0x0000558dae2d95e4 in AsmJSFaultHandler (signum=<optimized out>, info=0x7f8e5e9fc1b0, context=0x7f8e5e9fc080)
    at /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.4/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
    #4  <signal handler called>
    #5  JS_GetObjectRuntime (obj=0x7f8f1da4e380) at /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.4/mozjs/js/src/jsobj.h:170
    #6  0x0000558dac738aa0 in <script::dom::promise::Promise as core::ops::drop::Drop>::drop ()
    #7  0x0000558dac00a86a in <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop ()
    #8  0x0000558dac013a05 in <std::collections::hash::table::RawTable<K, V> as core::ops::drop::Drop>::drop ()
    #9  0x0000558dac8326bb in std::thread::local::fast::destroy_value ()
    #10 0x00007f8f94938847 in __GI___call_tls_dtors () at cxa_thread_atexit_impl.c:155
    #11 0x00007f8f96148932 in start_thread () at pthread_create.c:472
    #12 0x00007f8f94a01e7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`
    
    (gdb) disass
    Dump of assembler code for function _ZN5servo21install_crash_handler7handler17hdb154395c74011a1E:
       ...
       0x0000558dabb63133 <+451>:	callq  0x558dae6ea990 <std::io::stdio::_print>
       0x0000558dabb63138 <+456>:	lea    0x10(%rsp),%rdi
       0x0000558dabb6313d <+461>:	callq  0x558dabb602b0 <core::ptr::drop_in_place>
    => 0x0000558dabb63142 <+466>:	ud2    
       0x0000558dabb63144 <+468>:	ud2
       ...

**Comment by yezhizhen** [comment]
I can no longer reproduce this.
