### ISSUE TITLE
Servo for Android crashes on launch

### ISSUE THREAD

**Issue by atouchet** [servo/servo#21298]
I thought I would test out the latest Servo nightly build on Android as I have never used it before. I found out that it crashes on launch giving me the message "Unfortunately, Servo has stopped." I am using a Nexus 5 running Android 6.0.1. Is my phone a supported device for the Android port or is something else going wrong?

**Comment by jdm** [comment]
I think we may only support Android Oreo and more recent. Android 6 is Marshmallow.

**Comment by NiLSPACE** [comment]
It also crashes on my Huawei P10 lite which runs Android 8.

**Comment by paulrouget** [comment]
Can you please share the crash report from `adb logcat`?

**Comment by paulrouget** [comment]
I imagine that if it's a SDK/NDK version issue, the installation would fail.

**Comment by paulrouget** [comment]
Found an issue when no arguments are passed.

I'll submit a PR soon.

**Comment by paulrouget** [comment]
To confirm that this is the issue you both running into, can you check if you see any message when doing:

```
adb logcat|grep "Servo arguments must be formatted as a JSON array"
```

**Comment by NiLSPACE** [comment]
Yes, it's that error:
```
08-01 07:29:16.366 13326 13371 E AndroidRuntime: FATAL EXCEPTION: GLThread 1070
08-01 07:29:16.366 13326 13371 E AndroidRuntime: Process: com.mozilla.servo, PID: 13326
08-01 07:29:16.366 13326 13371 E AndroidRuntime: java.lang.Exception: Invalid arguments. Servo arguments must be formatted as a JSON array
08-01 07:29:16.366 13326 13371 E AndroidRuntime: 	at com.mozilla.servoview.NativeServo.init(Native Method)
08-01 07:29:16.366 13326 13371 E AndroidRuntime: 	at com.mozilla.servoview.ServoView.lambda$onGLReady$6$ServoView(ServoView.java:155)
08-01 07:29:16.366 13326 13371 E AndroidRuntime: 	at com.mozilla.servoview.ServoView$$Lambda$6.run(Unknown Source:12)
08-01 07:29:16.366 13326 13371 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
08-01 07:29:16.366 13326 13371 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
08-01 07:29:20.697 13436 13455 E AndroidRuntime: FATAL EXCEPTION: GLThread 1078
08-01 07:29:20.697 13436 13455 E AndroidRuntime: Process: com.mozilla.servo, PID: 13436
08-01 07:29:20.697 13436 13455 E AndroidRuntime: java.lang.Exception: Invalid arguments. Servo arguments must be formatted as a JSON array
08-01 07:29:20.697 13436 13455 E AndroidRuntime: 	at com.mozilla.servoview.NativeServo.init(Native Method)
08-01 07:29:20.697 13436 13455 E AndroidRuntime: 	at com.mozilla.servoview.ServoView.lambda$onGLReady$6$ServoView(ServoView.java:155)
08-01 07:29:20.697 13436 13455 E AndroidRuntime: 	at com.mozilla.servoview.ServoView$$Lambda$6.run(Unknown Source:12)
08-01 07:29:20.697 13436 13455 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
08-01 07:29:20.697 13436 13455 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
08-01 07:29:22.644 13480 13499 E AndroidRuntime: FATAL EXCEPTION: GLThread 1082
08-01 07:29:22.644 13480 13499 E AndroidRuntime: Process: com.mozilla.servo, PID: 13480
08-01 07:29:22.644 13480 13499 E AndroidRuntime: java.lang.Exception: Invalid arguments. Servo arguments must be formatted as a JSON array
08-01 07:29:22.644 13480 13499 E AndroidRuntime: 	at com.mozilla.servoview.NativeServo.init(Native Method)
08-01 07:29:22.644 13480 13499 E AndroidRuntime: 	at com.mozilla.servoview.ServoView.lambda$onGLReady$6$ServoView(ServoView.java:155)
08-01 07:29:22.644 13480 13499 E AndroidRuntime: 	at com.mozilla.servoview.ServoView$$Lambda$6.run(Unknown Source:12)
08-01 07:29:22.644 13480 13499 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
08-01 07:29:22.644 13480 13499 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
08-01 08:57:45.911 15268 15288 E AndroidRuntime: FATAL EXCEPTION: GLThread 1098
08-01 08:57:45.911 15268 15288 E AndroidRuntime: Process: com.mozilla.servo, PID: 15268
08-01 08:57:45.911 15268 15288 E AndroidRuntime: java.lang.Exception: Invalid arguments. Servo arguments must be formatted as a JSON array
08-01 08:57:45.911 15268 15288 E AndroidRuntime: 	at com.mozilla.servoview.NativeServo.init(Native Method)
08-01 08:57:45.911 15268 15288 E AndroidRuntime: 	at com.mozilla.servoview.ServoView.lambda$onGLReady$6$ServoView(ServoView.java:155)
08-01 08:57:45.911 15268 15288 E AndroidRuntime: 	at com.mozilla.servoview.ServoView$$Lambda$6.run(Unknown Source:12)
08-01 08:57:45.911 15268 15288 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
08-01 08:57:45.911 15268 15288 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
08-01 13:23:03.284 19419 19438 E AndroidRuntime: FATAL EXCEPTION: GLThread 1134
08-01 13:23:03.284 19419 19438 E AndroidRuntime: Process: com.mozilla.servo, PID: 19419
08-01 13:23:03.284 19419 19438 E AndroidRuntime: java.lang.Exception: Invalid arguments. Servo arguments must be formatted as a JSON array
08-01 13:23:03.284 19419 19438 E AndroidRuntime: 	at com.mozilla.servoview.NativeServo.init(Native Method)
08-01 13:23:03.284 19419 19438 E AndroidRuntime: 	at com.mozilla.servoview.ServoView.lambda$onGLReady$6$ServoView(ServoView.java:155)
08-01 13:23:03.284 19419 19438 E AndroidRuntime: 	at com.mozilla.servoview.ServoView$$Lambda$6.run(Unknown Source:12)
08-01 13:23:03.284 19419 19438 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
08-01 13:23:03.284 19419 19438 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
```

**Comment by atouchet** [comment]
I am able to launch Servo without it crashing now but I am experiencing a new crash shortly afterwards. I opened a new issue report for that: #21317
