### ISSUE TITLE
Stopping android page load crashed servo

### ISSUE THREAD

**Issue by jdm** [servo/servo#21328]
```
8-02 15:55:46.297 15284 15301 E zygote  : No implementation found for void com.mozilla.servoview.JNIServo.stop() (tried Java_com_mozilla_servoview_JNIServo_stop and Java_com_mozilla_servoview_JNIServo_stop__)
08-02 15:55:46.423 15284 15301 E AndroidRuntime: FATAL EXCEPTION: GLThread 3211
08-02 15:55:46.423 15284 15301 E AndroidRuntime: Process: com.mozilla.servo, PID: 15284
08-02 15:55:46.423 15284 15301 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.mozilla.servoview.JNIServo.stop() (tried Java_com_mozilla_servoview_JNIServo_stop and Java_com_mozilla_servoview_JNIServo_stop__)
08-02 15:55:46.423 15284 15301 E AndroidRuntime: 	at com.mozilla.servoview.JNIServo.stop(Native Method)
08-02 15:55:46.423 15284 15301 E AndroidRuntime: 	at com.mozilla.servoview.Servo.lambda$stop$4$Servo(Servo.java:57)
08-02 15:55:46.423 15284 15301 E AndroidRuntime: 	at com.mozilla.servoview.Servo$$Lambda$4.run(Unknown Source:2)
08-02 15:55:46.423 15284 15301 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
08-02 15:55:46.423 15284 15301 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

**Comment by jdm** [comment]
It's easiest to hit this in a debug build, because pages take so long to load that the screen turns off because you're waiting until it's done.

**Comment by paulrouget** [comment]
@jdm did you make a PR for this?
