### ISSUE TITLE
 windows-msvc-dev failure, CMake Error

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21406]
Failed twice:

- https://github.com/servo/servo/pull/21405#issuecomment-412927227
- https://github.com/servo/servo/pull/21404#issuecomment-412924979

Same error:

```
CMake Error at C:/Users/Administrator/.servo/msvc-dependencies/cmake/3.7.2/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/amd64/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/buildbot/slave/windows-msvc-dev/build/target/debug/build/script-18800d19f89d1f0d/out/build/CMakeFiles/CMakeTmp

  

  Run Build
  Command:"C:/Users/Administrator/.servo/msvc-dependencies/ninja/1.7.1/bin/ninja.exe"
  "cmTC_f9858"

  [1/2] Building C object CMakeFiles\cmTC_f9858.dir\testCCompiler.c.obj


  cl : Command line warning D9025 : overriding '/MD' with '/MDd'


  [2/2] Linking C executable cmTC_f9858.exe


  FAILED: cmTC_f9858.exe 


  cmd.exe /C "cd .  &&
  C:\Users\Administrator\.servo\msvc-dependencies\cmake\3.7.2\bin\cmake.exe
  -E vs_link_exe --intdir=CMakeFiles\cmTC_f9858.dir --manifests --
  C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo
  CMakeFiles\cmTC_f9858.dir\testCCompiler.c.obj /out:cmTC_f9858.exe
  /implib:cmTC_f9858.lib /pdb:cmTC_f9858.pdb /version:0.0 /machine:x64 /debug
  /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib
  winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
  advapi32.lib && cd ."


  RC Pass 1 failed to run.



  ninja: build stopped: subcommand failed.


  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\buildbot\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.29\src\lib.rs:632:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:345
   9: cmake::fail
             at C:\buildbot\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.29\src\lib.rs:632
  10: cmake::run
             at C:\buildbot\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.29\src\lib.rs:613
  11: cmake::Config::build
             at C:\buildbot\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.29\src\lib.rs:481
  12: build_script_build::main
             at .\build.rs:45
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:106
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  18: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  19: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
```

**Comment by paulrouget** [comment]
Seems fixed now.
