### ISSUE TITLE
Crash in FontHandle::face_name on wikipedia

### ISSUE THREAD

**Issue by jdm** [servo/servo#2160]
http://en.wikipedia.org/wiki/Hamster

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7c58700 (LWP 12980)]
0x0000000000fad227 in str::raw::from_c_str::h4df27cc098193f89r1q::v0.10.pre ()
Missing separate debuginfos, use: debuginfo-install libtxc_dxtn-1.0.0-2.fc17.x86_64
(gdb) bt
#0  0x0000000000fad227 in str::raw::from_c_str::h4df27cc098193f89r1q::v0.10.pre ()
#1  0x0000000000b71f53 in gfx::platform::linux::font::FontHandle.FontHandleMethods::face_name (self=0x7ffff42b68f8) at /home/jdm/sdb/servo-master/src/components/gfx/platform/linux/font.rs:129
#2  0x0000000000b97d95 in gfx::font_list::FontEntry::new (handle=...) at /home/jdm/sdb/servo-master/src/components/gfx/font_list.rs:144
#3  0x0000000000b97747 in gfx::platform::linux::font_list::FontListHandle::load_variations_for_family (self=0x7fffec109760, family=0x7fffec0f2550)
    at /home/jdm/sdb/servo-master/src/components/gfx/platform/linux/font_list.rs:124
#4  0x0000000000b96084 in gfx::font_list::FontFamily::load_family_variations (self=0x7fffec0f2550, list=0x7fffec109760) at /home/jdm/sdb/servo-master/src/components/gfx/font_list.rs:102
#5  0x0000000000b95a39 in gfx::font_list::FontFamily::find_font_for_style (self=0x7fffec0f2550, list=0x7fffec109760, style=0x7ffff42b8580) at /home/jdm/sdb/servo-master/src/components/gfx/font_list.rs:108
#6  0x0000000000b91f5f in gfx::font_list::FontList::find_font_in_family (self=0x7fffec109708, family_name=0x7ffff42b7ea8, style=0x7ffff42b8580) at /home/jdm/sdb/servo-master/src/components/gfx/font_list.rs:66
#7  0x0000000000b8df31 in gfx::font_context::FontContext::create_font_group (self=0x7fffec1096f0, style=0x7ffff42b8580) at /home/jdm/sdb/servo-master/src/components/gfx/font_context.rs:131
#8  0x0000000000b8baf3 in gfx::font_context::FontContext::get_resolved_font_for_style (self=0x7fffec1096f0, style=0x7ffff42b8580) at /home/jdm/sdb/servo-master/src/components/gfx/font_context.rs:83
#9  0x00000000005e4e41 in servo::layout::construct::FlowConstructor<'a>::set_inline_info_for_inline_child (self=0x7ffff42c2130, boxes=..., parent_node=0x7ffff42c2148)
    at /home/jdm/sdb/servo-master/src/components/main/layout/construct.rs:688
#10 0x00000000005e2989 in servo::layout::construct::FlowConstructor<'a>::build_boxes_for_nonreplaced_inline_content (self=0x7ffff42c2130, node=0x7ffff42c2148)
    at /home/jdm/sdb/servo-master/src/components/main/layout/construct.rs:660
#11 0x00000000005e8b45 in servo::layout::construct::FlowConstructor<'a>::build_boxes_for_inline (self=0x7ffff42c2130, node=0x7ffff42c2148)
    at /home/jdm/sdb/servo-master/src/components/main/layout/construct.rs:771
#12 0x00000000004f9162 in process (self=0x7ffff42c2130, node=0x7ffff42c2148) at /home/jdm/sdb/servo-master/src/components/main/layout/construct.rs:1006
#13 servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42ca020, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, applicable_declarations=
    0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...) at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:525
#14 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42d1e90, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#15 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42d9d00, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#16 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42e1b70, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#17 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42e99e0, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#18 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42f1850, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#19 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff42f96c0, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#20 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff4301530, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#21 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff43093a0, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#22 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff4311210, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#23 0x00000000004f5cce in servo::css::matching::LayoutNode<'ln>.MatchMethods::recalc_style_for_subtree (self=0x7ffff43192c8, stylist=0x7fffdc003fa0, layout_context=0x7ffff4318d98, font_context=0x0, 
    applicable_declarations=0x7ffff43187c8, applicable_declarations_cache=0x7ffff43187b0, style_sharing_candidate_cache=0x7ffff4318790, parent=...)
    at /home/jdm/sdb/servo-master/src/components/main/css/matching.rs:513
#24 0x000000000064d57a in fn28649 () at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:583
#25 0x000000000064d269 in time::profile::he1fbcded758d2256xHA::v0.0 () at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:574
#26 0x0000000000644313 in servo::layout::layout_task::LayoutTask::handle_reflow (self=0x7ffff4319c58, data=0x7fffec01eef0) at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:574
#27 0x00000000006438a0 in fn28459 () at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:355
#28 0x00000000004be99e in time::profile::h08ea46eeae50615bxHA::v0.0 () at /home/jdm/sdb/servo-master/src/components/main/compositing/compositor.rs:739
#29 0x000000000063e38c in servo::layout::layout_task::LayoutTask::handle_request (self=0x7ffff4319c58) at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:354
#30 0x000000000061eb92 in servo::layout::layout_task::LayoutTask::start (self=0x7ffff4319c58) at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:322
#31 0x000000000061e061 in fn27936 () at /home/jdm/sdb/servo-master/src/components/main/layout/layout_task.rs:275
#32 0x0000000000ee5448 in task::bootstrap_green_task::closure.7058 ()
#33 0x0000000001022783 in rt::task::Task::run::closure.40680 ()
#34 0x000000000102d68c in rust_try ()
#35 0x00000000010225e2 in rt::task::Task::run::h7977c6fd6d6e0e93148::v0.10.pre ()
#36 0x0000000000ee52fa in task::bootstrap_green_task::ha6a1ce90f7e00c6dZ5b::v0.10.pre ()
#37 0x0000000000000000 in ?? ()
```

Looks like the FontHandle isn't valid anymore.

**Comment by sviter** [comment]
No crash for me on current servo

**Comment by jdm** [comment]
Actually, let's leave this open until someone tries it on linux.

**Comment by dralley** [comment]
Cannot reproduce the segfault
