### ISSUE TITLE
Magic Leap build of blurdroid fails

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22059]
Building for Magic Leap with the android-toolchain directory removed produces:
```
     Running `/Users/ajeffrey/github/asajeffrey/servo/target/debug/build/blurdroid-34d1dca00bf7eab7/build-script-build`                                                             
thread 'main' panicked at 'Please set the ANDROID_SDK environment variable', libcore/option.rs:1010:5                                                                               
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                                                                                                  
error: failed to run custom build command for `blurdroid v0.1.6`                                                                                                                    
process didn't exit successfully: `/Users/ajeffrey/github/asajeffrey/servo/target/debug/build/blurdroid-34d1dca00bf7eab7/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Please set the ANDROID_SDK environment variable', libcore/option.rs:1010:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
Rather oddly, it builds if there's an android-toolchain present.

**Comment by jdm** [comment]
If you have a .servobuild that has android ndk/sdk paths set up, that might explain why it was working for you.

**Comment by asajeffrey** [comment]
No .servobuild. How weird.
