### ISSUE TITLE
Windows mozjs build intermittently fails on taskcluster (fork: Resource temporarily unavailable)

### ISSUE THREAD

**Issue by jdm** [servo/servo#22140]
```

--- stderr
      0 [main] sh 6040 fork_copy: linked dll data/bss pass 0 failed, 0x6F1000..0x6F1A54, done 0, windows pid 6084, Win32 error 998
C:/Users/TASK_1~3/AppData/Local/Temp/make5444-5.sh: fork: Resource temporarily unavailable
mozmake: *** [makefile.cargo:159: maybe-configure] Error 128
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\task_1541612155\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.2\build.rs:110:5
stack backtrace:
   0: <std::sync::barrier::BarrierWaitResult as core::fmt::Debug>::fmt
   1: <std::path::Iter<'a> as core::convert::AsRef<std::path::Path>>::as_ref
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic<str*>
             at \libstd\panicking.rs:410
   6: build_script_build::build_jsapi
             at .\build.rs:110
   7: build_script_build::main
             at .\build.rs:20
   8: std::rt::lang_start::{{closure}}<()>
             at \libstd\rt.rs:74
   9: std::panicking::update_panic_count
  10: _rust_maybe_catch_panic
  11: std::rt::lang_start_internal
  12: std::rt::lang_start<()>
             at \libstd\rt.rs:74
  13: main
  14: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  15: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
Build FAILED in 0:08:15
```

**Comment by SimonSapin** [comment]
Log with context: https://tools.taskcluster.net/groups/A_t6N23DRvCxcXGKU6PwXQ/tasks/OxgSb3GZQeqX8S6DxIAvkw/runs/0/logs/public%2Flogs%2Flive.log#L957

(The metadata and logs for current Taskcluster tasks expire after a year. This is configurable when scheduling tasks.)

**Comment by CYBAI** [comment]
```
--- stderr
      0 [main] sh 4280 fork_copy: linked dll data/bss pass 0 failed, 0x1F1000..0x1F1A54, done 0, windows pid 5000, Win32 error 998
C:/Users/TA34A4~1/AppData/Local/Temp/make1208-4.sh: fork: Resource temporarily unavailable
mozmake: *** [makefile.cargo:196: maybe-configure] Error 128
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\task_1576028758\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\build.rs:133:5
stack backtrace:
   0: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\sys_common\backtrace.rs:61
   1: core::fmt::write
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libcore\fmt\mod.rs:1024
   2: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\io\mod.rs:1428
   3: std::panicking::default_hook::{{closure}}
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\panicking.rs:193
   4: std::panicking::default_hook
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\panicking.rs:210
   5: std::panicking::rust_panic_with_hook
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\panicking.rs:471
   6: std::panicking::begin_panic<str*>
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\src\libstd\panicking.rs:404
   7: build_script_build::build_jsapi
             at .\build.rs:133
   8: build_script_build::main
             at .\build.rs:19
   9: std::rt::lang_start::{{closure}}<()>
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\src\libstd\rt.rs:67
  10: std::panicking::try::do_call<closure-0,i32>
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\panicking.rs:292
  11: panic_unwind::__rust_maybe_catch_panic
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libpanic_unwind\lib.rs:78
  12: std::rt::lang_start_internal
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\/src\libstd\rt.rs:51
  13: std::rt::lang_start<()>
             at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63\src\libstd\rt.rs:67
  14: main
  15: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Observed in another [task](https://community-tc.services.mozilla.com/tasks/UaWwkN6oTuSwwGH9EnjeOw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FUaWwkN6oTuSwwGH9EnjeOw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1780-1818)

**Comment by jdm** [comment]
I haven't seen this on Taskcluster since we upgraded to more recent Windows server 2019 base images.
