### ISSUE TITLE
Windows taskcluster build intermittently crashes during mozjs configure (Couldn't reserve space for cygwin's heap, Win32 error 0)

### ISSUE THREAD

**Issue by jdm** [servo/servo#22212]
```
error: failed to run custom build command for `mozjs_sys v0.61.2`
process didn't exit successfully: `C:\Users\task_1542424298\repo\target\debug\build\mozjs_sys-cc0d89accd431be8\build-script-build` (exit code: 101)
--- stdout
[[ /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/configure -ot /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/configure.in ]] && touch /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/configure || true
[[ /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/old-configure -ot /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/old-configure.in ]] && touch /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/old-configure || true
! [[ /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/configure.in -ot /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/configure ]] && touch /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/configure || true
! [[ /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/old-configure.in -ot /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/old-configure ]] && touch /c/Users/task_1542424298/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/old-configure || true

--- stderr
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0xBF0000, BaseAddress 0xD40000, RegionSize 0xAD000, State 0x2000
C:\Users\task_1542424298\repo\.servo\msvc-dependencies\moztools\3.2\msys\bin\sh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
mozmake: *** [makefile.cargo:158: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\task_1542424298\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.2\build.rs:110:5
stack backtrace:
   0: <std::sync::barrier::BarrierWaitResult as core::fmt::Debug>::fmt
   1: <std::path::Iter<'a> as core::convert::AsRef<std::path::Path>>::as_ref
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic<str*>
             at \libstd\panicking.rs:410
   6: build_script_build::build_jsapi
             at .\build.rs:110
   7: build_script_build::main
             at .\build.rs:20
   8: std::rt::lang_start::{{closure}}<()>
             at \libstd\rt.rs:74
   9: std::panicking::update_panic_count
  10: _rust_maybe_catch_panic
  11: std::rt::lang_start_internal
  12: std::rt::lang_start<()>
             at \libstd\rt.rs:74
  13: main
  14: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  15: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
```
Given https://stackoverflow.com/a/31970708 I could totally believe that we have some older versions of some msys tools in https://github.com/servo/servo/blob/master/python/servo/packages.py.

**Comment by jdm** [comment]
This might be fixed by upgrading moztools. There's some code that could be stolen from https://github.com/servo/servo/compare/master...jdm:ndk-llvm.

**Comment by jdm** [comment]
Nevermind, we upgraded to a newer moztools almost a year ago :(

**Comment by saschanaz** [comment]
Might try MozillaBuild 3.3, if moztools means MozillaBuild? Doesn't seem like a contributable part as the script downloads it from AWS and no 3.3 there.

**Comment by jdm** [comment]
The changelog at https://hg.mozilla.org/mozilla-build/pushloghtml?fromchange=MOZILLABUILD_3_2_0_RELEASE&tochange=MOZILLABUILD_3_3_0_RELEASE doesn't look like it should make a difference to us, sadly.

**Comment by jdm** [comment]
If #24888 does not make the problem disappear, we might try forcing the GitForWindows path to be closer to the front of the PATH than the moztools path. Unfortunately the moztools path is added in https://github.com/servo/mozjs/blob/618398c43fe9ec2a471687a243808a399f077d2a/build.rs#L128 and the GitForWindows path is added in https://github.com/servo/servo/blob/a020522f37241001b01ee77dab562d50b6e7a924/etc/taskcluster/decisionlib.py#L533 (which happens before the build even starts).

**Comment by jdm** [comment]
I found a way to affect the PATH that looks like it should work, so I've added it to #24888.

**Comment by jdm** [comment]
```
--- stderr
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x607A0000, RegionSize 0x10000, State 0x10000
C:\Users\task_1575015520\repo\.servo\msvc-dependencies\moztools\3.2\msys\bin\pwd.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x607A0000, RegionSize 0x10000, State 0x10000
C:\Users\task_1575015520\repo\.servo\msvc-dependencies\moztools\3.2\msys\bin\sh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
mozmake: *** [makefile.cargo:193: maybe-configure] Error 1
```
Observed in a task since #24888 merged, sadly.

**Comment by saschanaz** [comment]
It still points 3.2, not using 3.3.

**Comment by mrobinson** [comment]
I think we can close this since we've moved to GitHub Actions.
