### ISSUE TITLE
Intermittent timeout in /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#22262]
```

  ▶ TIMEOUT [expected ERROR] /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 18.3.0-devel
```

**Comment by jdm** [comment]
```
  ▶ ERROR [expected TIMEOUT] /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html
  └   → Got results from /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html#iframe#document-domain, expected /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html
Traceback (most recent call last):
  File "/Users/worker/tasks/task_1544801404/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 162, in run_test
    result = self.do_test(test)
  File "/Users/worker/tasks/task_1544801404/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 110, in do_test
    result = self.convert_result(test, self.result_data)
  File "/Users/worker/tasks/task_1544801404/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 69, in __call__
    (result_url, test.url))
AssertionError: Got results from /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html#iframe#document-domain, expected /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_feature_policy.tentative.sub.html

```
