### ISSUE TITLE
Intermittent error in bluetooth tests 

### ISSUE THREAD

**Issue by jdm** [servo/servo#22537]
The error appears something like this:
```
  ▶ ERROR [expected OK] /bluetooth/characteristic/getDescriptor/gen-descriptor-get-same-object.https.html
  └   → ''
```
But earlier in the log there's a webdriver issue:
```
Traceback (most recent call last):
  File "/Users/servo/buildbot/slave/mac-rel-wpt4/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/protocol.py", line 48, in setup
    self.connect()
  File "/Users/servo/buildbot/slave/mac-rel-wpt4/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservodriver.py", line 100, in connect
    self.session.start()
  File "/Users/servo/buildbot/slave/mac-rel-wpt4/build/tests/wpt/web-platform-tests/tools/webdriver/webdriver/client.py", line 421, in start
    value = self.send_command("POST", "session", body=body)
  File "/Users/servo/buildbot/slave/mac-rel-wpt4/build/tests/wpt/web-platform-tests/tools/webdriver/webdriver/client.py", line 472, in send_command
    raise err
SessionNotCreatedException: session not created (500): Session is already started
```

**Comment by TimvdLippe** [comment]
Closing as stale as this issue has not received any failure references for over a month
