### ISSUE TITLE
Import Error: No module named certifi when ./mach bootstrap

### ISSUE THREAD

**Issue by kenta7777** [servo/servo#22587]
When I ran `./mach bootstrap`, I got this error.
```
$ ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 96, in <module>
    main(sys.argv)
  File "./mach", line 24, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/kenta/servo/python/mach_bootstrap.py", line 232, in bootstrap_command_only
    from servo.bootstrap import bootstrap
  File "/home/kenta/servo/python/servo/bootstrap.py", line 17, in <module>
    from servo.util import extract, download_file, host_triple
  File "/home/kenta/servo/python/servo/util.py", line 33, in <module>
    import certifi
ImportError: No module named certifi
```

I think cirtifi has been already installed so I don't understand why I have got this error.
```
$ pip install certifi
Requirement already satisfied: certifi in /home/kenta/anaconda3/lib/python3.6/site-packages (2018.11.29)
```

**Comment by tigercosmos** [comment]
Thanks for report. 
` ./mach bootstrap`  has an issue. 
You can avoid it with hard code like [this](https://github.com/servo/servo/pull/22250/files) for now.

 But we should fix it. Keep tracking with #22590
