### ISSUE TITLE
mach bootstrap: pip install issue with `certifi`

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#22590]
There is an issue that `./mach bootstrap` cannot work in Ubuntu 16(not test in other system)

```log
$ ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 96, in <module>
    main(sys.argv)
  File "./mach", line 24, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/tigercosmos/servo/python/mach_bootstrap.py", line 232, in bootstrap_command_only
    from servo.bootstrap import bootstrap
  File "/home/tigercosmos/servo/python/servo/bootstrap.py", line 17, in <module>
    from servo.util import extract, download_file, host_triple
  File "/home/tigercosmos/servo/python/servo/util.py", line 33, in <module>
    import certifi
ImportError: No module named certifi
```

## solution 

There is a possible solution provided by @jdm at #22250

jdm: Ok, so it's caused by us importing `util.py` before executing the code that processes `requirements.txt`. Let's make `STATIC_RUST_LANG_ORG_DIST` and `URLOPEN_KWARGS` methods instead of global constants, and we can set a `HAS_SNI_AND_RECENT_PYTHON` global constant instead that the two new methods can check. We can import certifi inside the new method for `URLOPEN_KWARGS` and that will avoid the issue.

**Comment by jdm** [comment]
Code: `python/servo/util.py`

**Comment by shanavas786** [comment]
@highfive  assign me
