### ISSUE TITLE
load times for NYT homepage are unbearable

### ISSUE THREAD

**Issue by jdm** [servo/servo#22603]
I opened http://newyorktimes.com in a servo nightly and sat watching a lot of blank space for at least 60 seconds.

**Comment by Eijebong** [comment]
I tried reproducing this and got a nice

```
[2019-01-03T23:39:22Z ERROR script::dom::bindings::error] Error at https://news.google.com/swg/js/v1/swg.js:8:323 a.HTMLDocument is undefined
```

**Comment by CYBAI** [comment]
Same as @Eijebong 

```
→ ./mach run http://newyorktimes.com/
[2019-01-06T06:12:47Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
[2019-01-06T06:12:49Z ERROR script::dom::bindings::error] Error at https://news.google.com/swg/js/v1/swg.js:8:323 a.HTMLDocument is undefined
aborted swg
Optimizely: Timeout vi_bar1
Optimizely: Timeout vi_welcome
```

**Comment by arihant2math** [comment]
Loads up at a normal speed now.
