### ISSUE TITLE
`mach bootstrap` not supporting elementaryOS

### ISSUE THREAD

**Issue by MaCunZhang** [servo/servo#22626]
Hi there, I am using [elementaryOS](https://elementary.io/) 5.0 (Juno) which based on Ubuntu 18.04 LTS. 
```
$ ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 96, in <module>
    main(sys.argv)
  File "./mach", line 24, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/mcz/source/servo/python/mach_bootstrap.py", line 239, in bootstrap_command_only
    bootstrap(context, force)
  File "/home/mcz/source/servo/python/servo/bootstrap.py", line 382, in bootstrap
    distro, version = get_linux_distribution()
  File "/home/mcz/source/servo/python/servo/bootstrap.py", line 370, in get_linux_distribution
    raise Exception('mach bootstrap does not support %s, please file a bug' % distro)
Exception: mach bootstrap does not support elementary, please file a bug
```

**Comment by jdm** [comment]
@MaCunZhang If you would like to fix this, you will want to add a conditional like [this one](https://github.com/servo/servo/blob/bab4e9efa5b73f28feeb98235afeff410d73a430/python/servo/bootstrap.py#L347-L362) to recognize elementaryOS and treat it appropriately.
