### ISSUE TITLE
Can't use --debugger with servodriver WPT harness

### ISSUE THREAD

**Issue by jdm** [servo/servo#22664]
```
godot:servo jdm$ ./mach test-wpt --product servodriver --headless tests/wpt/mozilla/tests/css/img_simple.html --debugger
 0:02.96 LOG: MainThread INFO Using 1 client processes
 0:03.46 LOG: MainThread INFO Starting http server on 127.0.0.1:8000
 0:03.47 LOG: MainThread INFO Starting https server on 127.0.0.1:8443
 0:03.47 LOG: MainThread INFO Starting http server on 127.0.0.1:8001
 0:03.95 SUITE_START: MainThread 1
 0:03.95 LOG: MainThread INFO Running reftest tests
 0:03.96 LOG: TestRunnerManager-1 INFO Starting runner
(lldb) target create "/Users/jdm/src/servo/target/debug/servo"
 0:04.99 LOG: TestRunnerManager-1 ERROR Traceback (most recent call last):
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 363, in run
    new_state = self.wait_event()
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 408, in wait_event
    self.browser.started and not self.browser.is_alive()):
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 240, in is_alive
    return self.browser.is_alive()
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/browsers/servodriver.py", line 169, in is_alive
    if self.runner:
AttributeError: 'ServoWebDriverBrowser' object has no attribute 'runner'
```

**Comment by shanavas786** [comment]
@highfive assign me
