### ISSUE TITLE
GC threshhold default values should be higher 

### ISSUE THREAD

**Issue by jdm** [servo/servo#23076]
We are passing nonsense values like 1 and checking that the preference values lie between 0 and 10,000 at https://github.com/servo/servo/blob/ba929208e46639ca57eabb274cd98d37108ee365/components/script/script_runtime.rs#L487-L504. The values are divided by 100 when used: https://github.com/servo/mozjs/blob/9b44b1e870cae2d96ea41bf2aa8a7d5eaa4cdce7/mozjs/js/src/gc/GC.cpp#L1390-L1399

**Comment by asajeffrey** [comment]
With a `--debugmozjs` build, this produces:
```
Thread 2 "ScriptThread Pi" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 15978.16037]
0x0000aaaacce8e508 in JS_SetGCParameter (cx=0x400037c62000, key=JSGC_ALLOCATION_THRESHOLD_FACTOR, value=1)
    at /Users/ajeffrey/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.13/mozjs/js/src/jsapi.cpp:1541
1541	    MOZ_ALWAYS_TRUE(cx->runtime()->gc.setParameter(key, value, lock));
(gdb) bt
#0  0x0000aaaacce8e508 in JS_SetGCParameter (cx=0x400037c62000, key=JSGC_ALLOCATION_THRESHOLD_FACTOR, value=1)
    at /Users/ajeffrey/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.13/mozjs/js/src/jsapi.cpp:1541
#1  0x0000aaaac966cc44 in script::script_runtime::new_rt_and_cx_with_parent::h9326a24aeae7d12c (parent=...) at components/script/script_runtime.rs:488
#2  0x0000aaaac966b234 in script::script_runtime::new_rt_and_cx::hd6e5d08c75147534 () at components/script/script_runtime.rs:339
#3  0x0000aaaac9321e84 in script::script_thread::ScriptThread::new::h116419323b7ce839 (state=..., port=..., chan=...) at components/script/script_thread.rs:1070
#4  0x0000aaaac8b72eb8 in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h4b46284cd34109ec () at components/script/script_thread.rs:714
#5  0x0000aaaacffbe9dc in std::sys_common::backtrace::__rust_begin_short_backtrace::h4e248a02b2c014bd (f=...)
    at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/sys_common/backtrace.rs:136
#6  0x0000aaaaced560b4 in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hda73e68f84833483 ()
    at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/thread/mod.rs:469
#7  0x0000aaaace272e54 in _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h1f3da702dda6c742 (self=..., 
    _args=0) at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:309
#8  0x0000aaaaceaf7774 in std::panicking::try::do_call::haa8c29099cc9173d (data=0x4000435ff2a8 "")
    at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:293
#9  0x0000aaaacdc69f58 in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:85
#10 0x0000aaaacea260fc in std::panicking::try::hb132b2a20c63b94a (f=...) at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
#11 0x0000aaaace2e4a48 in std::panic::catch_unwind::h5cf78cf69fd69ad2 (f=...) at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
#12 0x0000aaaaced54134 in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h20553c02bb69188b ()
    at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/thread/mod.rs:468
#13 0x0000aaaac8b8e12c in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hc2b49d22ae6846ac ()
    at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
#14 0x0000aaaacdc54d80 in call_once<(),FnOnce<()>> () at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
#15 0x0000aaaacdc69830 in call_once<(),alloc::boxed::Box<FnOnce<()>>> () at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
#16 start_thread () at src/libstd/sys_common/thread.rs:13
#17 thread_start () at src/libstd/sys/unix/thread.rs:79
#18 0x000040003327f6f8 in __pthread_start(void*) ()
   from /Users/ajeffrey/github/asajeffrey/servo/target/magicleap/aarch64-linux-android/debug/debug_lumin_clang-3.8_aarch64/libc.so
#19 0x0000400033232680 in __start_thread ()
   from /Users/ajeffrey/github/asajeffrey/servo/target/magicleap/aarch64-linux-android/debug/debug_lumin_clang-3.8_aarch64/libc.so
#20 0x0000000000000000 in ?? ()
```
