### ISSUE TITLE
assertion failed: rect.size.width >= Zero::zero() caused by BlockFlow::setip_clip_scroll_node_for_overflow

### ISSUE THREAD

**Issue by mateon1** [servo/servo#23093]
Another euclid crash found while fuzzing.

```html
<br style="float: right; border: 1px solid; border-collapse: collapse; overflow: auto;" />
```

https://github.com/servo/servo/blob/40d599e39ffdd627b8912388dc24de77291f700f/components/layout/display_list/builder.rs#L2585
At this point `border_box` has a zero width and 1118 Au height, and the border is nonzero, causing `inner_rect` to panic.

Most likely relevant part:
```gdb
   9:     0x55df687b6120 - <euclid::rect::TypedRect<T, U>>::inner_rect::h1b6e3a58314dc57f
                        at /shared/dev/rust/servo/<::core::macros::panic macros>:3
  10:     0x55df68752742 - layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clip_scroll_node_for_overflow::hc2a022384c012667
                        at components/layout/display_list/builder.rs:2584
  11:     0x55df6875170e - layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clipping_for_block::hcd0e4f63bb9efa4d
                        at components/layout/display_list/builder.rs:2435
  12:     0x55df68750fb1 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2349
  13:     0x55df6874dba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
```

<details>
<summary>Full backtrace</summary>

```gdb
VMware, Inc.
llvmpipe (LLVM 7.0, 256 bits)
3.3 (Core Profile) Mesa 18.3.4
assertion failed: rect.size.width >= Zero::zero() (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.19.4/src/rect.rs:270)
stack backtrace:
   0:     0x55df6b94ded6 - backtrace::backtrace::libunwind::trace::h8af3b710f1a5e12e
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h2a1223234ae0346f
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55df6b9484e3 - backtrace::capture::Backtrace::new_unresolved::h2dd57ce7b77a7435
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x55df6b94843d - backtrace::capture::Backtrace::new::h8c6b161078e28d12
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:     0x55df64900351 - servo::main::{{closure}}::h5fe9a894213f10e8
                        at ports/servo/non_android_main.rs:110
   4:     0x55df6da3ba48 - rust_panic_with_hook
                        at src/libstd/panicking.rs:482
   5:     0x55df6da3b4e1 - continue_panic_fmt
                        at src/libstd/panicking.rs:385
   6:     0x55df6da3b3c5 - rust_begin_unwind
   7:     0x55df6da5acac - panic_fmt
                        at src/libcore/panicking.rs:85
   8:     0x55df6da5abeb - panic
                        at src/libcore/panicking.rs:49
   9:     0x55df687b6120 - <euclid::rect::TypedRect<T, U>>::inner_rect::h1b6e3a58314dc57f
                        at /shared/dev/rust/servo/<::core::macros::panic macros>:3
  10:     0x55df68752742 - layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clip_scroll_node_for_overflow::hc2a022384c012667
                        at components/layout/display_list/builder.rs:2584
  11:     0x55df6875170e - layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clipping_for_block::hcd0e4f63bb9efa4d
                        at components/layout/display_list/builder.rs:2435
  12:     0x55df68750fb1 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2349
  13:     0x55df6874dba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
  14:     0x55df68727cd2 - layout::flow::BaseFlow::collect_stacking_contexts_for_children::h294d4c160414c815
                        at components/layout/flow.rs:1217
  15:     0x55df68751206 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2366
  16:     0x55df6874dba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
  17:     0x55df68727cd2 - layout::flow::BaseFlow::collect_stacking_contexts_for_children::h294d4c160414c815
                        at components/layout/flow.rs:1217
  18:     0x55df68751206 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2366
  19:     0x55df6874dba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
  20:     0x55df6886811a - layout::sequential::build_display_list_for_subtree::hb58463b7cb5cec03
                        at components/layout/sequential.rs:77
  21:     0x55df652975f9 - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}}::h58075e51d552f326
                        at components/layout_thread/lib.rs:1035
  22:     0x55df652dc5f6 - profile_traits::time::profile::h9fe2e60f7ec7f2e7
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:142
  23:     0x55df6516b07b - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::h1ed2d9657645f024
                        at components/layout_thread/lib.rs:1010
  24:     0x55df65172145 - layout_thread::LayoutThread::perform_post_main_layout_passes::h01232d83b35f4388
                        at components/layout_thread/lib.rs:1798
  25:     0x55df65171e7e - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::he179434151a2cc3e
                        at components/layout_thread/lib.rs:1778
  26:     0x55df6516e762 - layout_thread::LayoutThread::handle_reflow::ha8796ca750bf9a52
                        at components/layout_thread/lib.rs:1459
  27:     0x55df652968e9 - layout_thread::LayoutThread::handle_request_helper::{{closure}}::hbfae2b3293339477
                        at components/layout_thread/lib.rs:726
  28:     0x55df652dbdee - profile_traits::time::profile::h85dc10afe741d48b
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:142
  29:     0x55df6516712d - layout_thread::LayoutThread::handle_request_helper::h57e1d40c3617997c
                        at components/layout_thread/lib.rs:722
  30:     0x55df65166334 - layout_thread::LayoutThread::handle_request::hb5fa803528c22ce9
                        at components/layout_thread/lib.rs:672
  31:     0x55df65164d72 - layout_thread::LayoutThread::start::hf920768435aa8160
                        at components/layout_thread/lib.rs:558
  32:     0x55df65295492 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::{{closure}}::heb8dfaef58fad40e
                        at components/layout_thread/lib.rs:313
  33:     0x55df65236a7e - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hc617bc87948860f1
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:88
  34:     0x55df65295d58 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hb9e0a07a00999f71
                        at components/layout_thread/lib.rs:311
  35:     0x55df653feb94 - std::sys_common::backtrace::__rust_begin_short_backtrace::h69408bfd53070bc1
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/sys_common/backtrace.rs:136
  36:     0x55df65340413 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hff71ded556757c3e
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:469
  37:     0x55df653fdbf3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6c192e3f82a95cfb
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:309
  38:     0x55df65419b29 - std::panicking::try::do_call::hde4e69918d8709c8
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:297
  39:     0x55df6da465f9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:87
  40:     0x55df6541924f - std::panicking::try::he65f80095cf99d71
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:276
  41:     0x55df653fdeb5 - std::panic::catch_unwind::h5f0795995ca0c47c
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:388
  42:     0x55df653401df - std::thread::Builder::spawn_unchecked::{{closure}}::hb09d73e49d72953c
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:468
  43:     0x55df653404e8 - <F as alloc::boxed::FnBox<A>>::call_box::h9566bf7cccb22507
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:749
  44:     0x55df6da4593d - call_once<(),()>
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:759
                         - start_thread
                        at src/libstd/sys_common/thread.rs:14
                         - thread_start
                        at src/libstd/sys/unix/thread.rs:80
  45:     0x7f24253f8fa2 - start_thread
  46:     0x7f242530d82e - clone
  47:                0x0 - <unknown>
[2019-03-25T12:43:45Z ERROR servo] assertion failed: rect.size.width >= Zero::zero()
Pipeline failed in hard-fail mode.  Crashing!
```
</details>

**Comment by mateon1** [comment]
Here's a version for the `rect.size.height` assertion:

```html
<pre style="border: solid; border-collapse: collapse; max-height: 0vh; overflow-x: scroll">x</pre>
```

<details>
<summary>Backtrace</summary>

```gdb
VMware, Inc.
llvmpipe (LLVM 7.0, 256 bits)
3.3 (Core Profile) Mesa 18.3.4
assertion failed: rect.size.height >= Zero::zero() (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.19.4/src/rect.rs:271)
stack backtrace:
   0:     0x55805082aed6 - backtrace::backtrace::libunwind::trace::h8af3b710f1a5e12e
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h2a1223234ae0346f
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x5580508254e3 - backtrace::capture::Backtrace::new_unresolved::h2dd57ce7b77a7435
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x55805082543d - backtrace::capture::Backtrace::new::h8c6b161078e28d12
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:     0x5580497dd351 - servo::main::{{closure}}::h5fe9a894213f10e8
                        at ports/servo/non_android_main.rs:110
   4:     0x558052918a48 - rust_panic_with_hook
                        at src/libstd/panicking.rs:482
   5:     0x5580529184e1 - continue_panic_fmt
                        at src/libstd/panicking.rs:385
   6:     0x5580529183c5 - rust_begin_unwind
   7:     0x558052937cac - panic_fmt
                        at src/libcore/panicking.rs:85
   8:     0x558052937beb - panic
                        at src/libcore/panicking.rs:49
   9:     0x55804d693173 - <euclid::rect::TypedRect<T, U>>::inner_rect::h1b6e3a58314dc57f
                        at /shared/dev/rust/servo/<::core::macros::panic macros>:3
  10:     0x55804d62f742 - layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clip_scroll_node_for_overflow::hc2a022384c012667
                        at components/layout/display_list/builder.rs:2584
  11:     0x55804d62e70e - layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clipping_for_block::hcd0e4f63bb9efa4d
                        at components/layout/display_list/builder.rs:2435
  12:     0x55804d62dfb1 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2349
  13:     0x55804d62aba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
  14:     0x55804d604cd2 - layout::flow::BaseFlow::collect_stacking_contexts_for_children::h294d4c160414c815
                        at components/layout/flow.rs:1217
  15:     0x55804d62e206 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2366
  16:     0x55804d62aba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
  17:     0x55804d604cd2 - layout::flow::BaseFlow::collect_stacking_contexts_for_children::h294d4c160414c815
                        at components/layout/flow.rs:1217
  18:     0x55804d62e206 - layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block::h76d47c9e157ed822
                        at components/layout/display_list/builder.rs:2366
  19:     0x55804d62aba1 - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6b155fa8c821f330
                        at components/layout/block.rs:2564
  20:     0x55804d74511a - layout::sequential::build_display_list_for_subtree::hb58463b7cb5cec03
                        at components/layout/sequential.rs:77
  21:     0x55804a1745f9 - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}}::h58075e51d552f326
                        at components/layout_thread/lib.rs:1035
  22:     0x55804a1b95f6 - profile_traits::time::profile::h9fe2e60f7ec7f2e7
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:142
  23:     0x55804a04807b - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::h1ed2d9657645f024
                        at components/layout_thread/lib.rs:1010
  24:     0x55804a04f145 - layout_thread::LayoutThread::perform_post_main_layout_passes::h01232d83b35f4388
                        at components/layout_thread/lib.rs:1798
  25:     0x55804a04ee7e - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::he179434151a2cc3e
                        at components/layout_thread/lib.rs:1778
  26:     0x55804a04b762 - layout_thread::LayoutThread::handle_reflow::ha8796ca750bf9a52
                        at components/layout_thread/lib.rs:1459
  27:     0x55804a1738e9 - layout_thread::LayoutThread::handle_request_helper::{{closure}}::hbfae2b3293339477
                        at components/layout_thread/lib.rs:726
  28:     0x55804a1b8dee - profile_traits::time::profile::h85dc10afe741d48b
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:142
  29:     0x55804a04412d - layout_thread::LayoutThread::handle_request_helper::h57e1d40c3617997c
                        at components/layout_thread/lib.rs:722
  30:     0x55804a043334 - layout_thread::LayoutThread::handle_request::hb5fa803528c22ce9
                        at components/layout_thread/lib.rs:672
  31:     0x55804a041d72 - layout_thread::LayoutThread::start::hf920768435aa8160
                        at components/layout_thread/lib.rs:558
  32:     0x55804a172492 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::{{closure}}::heb8dfaef58fad40e
                        at components/layout_thread/lib.rs:313
  33:     0x55804a113a7e - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hc617bc87948860f1
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:88
  34:     0x55804a172d58 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hb9e0a07a00999f71
                        at components/layout_thread/lib.rs:311
  35:     0x55804a2dbb94 - std::sys_common::backtrace::__rust_begin_short_backtrace::h69408bfd53070bc1
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/sys_common/backtrace.rs:136
  36:     0x55804a21d413 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hff71ded556757c3e
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:469
  37:     0x55804a2dabf3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6c192e3f82a95cfb
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:309
  38:     0x55804a2f6b29 - std::panicking::try::do_call::hde4e69918d8709c8
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:297
  39:     0x5580529235f9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:87
  40:     0x55804a2f624f - std::panicking::try::he65f80095cf99d71
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:276
  41:     0x55804a2daeb5 - std::panic::catch_unwind::h5f0795995ca0c47c
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:388
  42:     0x55804a21d1df - std::thread::Builder::spawn_unchecked::{{closure}}::hb09d73e49d72953c
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:468
  43:     0x55804a21d4e8 - <F as alloc::boxed::FnBox<A>>::call_box::h9566bf7cccb22507
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:749
  44:     0x55805292293d - call_once<(),()>
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:759
                         - start_thread
                        at src/libstd/sys_common/thread.rs:14
                         - thread_start
                        at src/libstd/sys/unix/thread.rs:80
  45:     0x7f718b88dfa2 - start_thread
  46:     0x7f718b7a282e - clone
  47:                0x0 - <unknown>
Pipeline failed in hard-fail mode.  Crashing!
```</details>

**Comment by Manishearth** [comment]
I'm getting this same assertion on https://glitch.com/~servo-web-layer-gl

cc @SimonSapin 

```
assertion failed: rect.size.width >= Zero::zero() (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at <::core::macros::panic macros>:3)
```

<details>
```
#15 0x000055555fdfa920 in std::panicking::rust_panic_with_hook () at src/libstd/panicking.rs:468
#16 0x000055555fdfa3ee in std::panicking::continue_panic_fmt () at src/libstd/panicking.rs:373
#17 0x000055555fdfa2d6 in rust_begin_unwind () at src/libstd/panicking.rs:302
#18 0x000055555fe1d12e in core::panicking::panic_fmt () at src/libcore/panicking.rs:82
#19 0x000055555fe1d07a in core::panicking::panic () at src/libcore/panicking.rs:50
#20 0x000055555b55c56f in euclid::rect::Rect<T,U>::inner_rect (self=0x7fff6abe79e8, offsets=...)
    at <::core::macros::panic macros>:2
#21 0x000055555b3d23d2 in layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clip_scroll_node_for_overflow (self=0x7ffed7900e10, state=0x7fff6abe9ea8, border_box=...) at components/layout/display_list/builder.rs:2597
#22 0x000055555b3d12c7 in layout::display_list::builder::<impl layout::block::BlockFlow>::setup_clipping_for_block (self=0x7ffed7900e10, state=0x7fff6abe9ea8, preserved_state=0x7fff6abe7ae8, stacking_context_type=..., established_reference_frame=..., flags=...) at components/layout/display_list/builder.rs:2448
#23 0x000055555b3d0b56 in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed7900e10, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2362
#24 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed7900e10, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#25 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7ffed7b39690, state=0x7fff6abe9ea8) at components/layout/flow.rs:1165
#26 0x000055555b3d3058 in layout::display_list::builder::<impl layout::block::BlockFlow>::create_pseudo_stacking_context_for_block (self=0x7ffed7b39690, stacking_context_type=layout::display_list::items::StackingContextType::PseudoPositioned, parent_stacking_context_id=..., parent_clipping_and_scrolling=..., state=0x7fff6abe9ea8)
    at components/layout/display_list/builder.rs:2693
#27 0x000055555b3d0d84 in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed7b39690, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2389
#28 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed7b39690, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#29 0x000055555b4cb251 in <layout::flex::FlexFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed7b39690, state=0x7fff6abe9ea8) at components/layout/flex.rs:1089
#30 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7ffed7b39910, state=0x7f---Type <return> to continue, or q <return> to quit---
ff6abe9ea8) at components/layout/flow.rs:1165
#31 0x000055555b3d0d1c in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed7b39910, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2379
#32 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed7b39910, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#33 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7ffed79f4110, state=0x7fff6abe9ea8) at components/layout/flow.rs:1165
#34 0x000055555b3d0d1c in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed79f4110, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2379
#35 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed79f4110, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#36 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7ffed79f4390, state=0x7fff6abe9ea8) at components/layout/flow.rs:1165
#37 0x000055555b3d0d1c in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed79f4390, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2379
#38 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed79f4390, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#39 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7ffed79f4610, state=0x7fff6abe9ea8) at components/layout/flow.rs:1165
#40 0x000055555b3d0d1c in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed79f4610, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2379
#41 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed79f4610, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#42 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7ffed79f4890, state=0x7fff6abe9ea8) at components/layout/flow.rs:1165
#43 0x000055555b3d0d1c in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7ffed79f4890, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2379
#44 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7ffed79f4890, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#45 0x000055555b4accad in layout::flow::BaseFlow::collect_stacking_contexts_for_children (self=0x7fffb6b11d10, state=0x7fff6abe9ea8) at components/layout/flow.rs:1165
#46 0x000055555b3d0d1c in layout::display_list::builder::<impl layout::block::BlockFlow>::collect_stacking_contexts_for_block (self=0x7fffb6b11d10, state=0x7fff6abe9ea8, flags=...) at components/layout/display_list/builder.rs:2379
---Type <return> to continue, or q <return> to quit---
#47 0x000055555b3cda62 in <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts (self=0x7fffb6b11d10, state=0x7fff6abe9ea8) at components/layout/block.rs:2571
#48 0x000055555b3f525e in layout::sequential::build_display_list_for_subtree (flow_root=..., layout_context=0x7fff6abed2c8, background_color=..., client_size=...) at components/layout/sequential.rs:80
#49 0x0000555556e82b83 in layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}} ()
    at components/layout_thread/lib.rs:1138
#50 0x0000555556e3d55a in profile_traits::time::profile (category=profile_traits::time::ProfilerCategory::LayoutDispListBuild, meta=..., profiler_chan=..., callback=...)
    at /home/manishearth/mozilla/voser/components/profile_traits/time.rs:147
#51 0x0000555556d91099 in layout_thread::LayoutThread::compute_abs_pos_and_build_display_list (self=0x7fff6abf0428, data=0x7fff6abee1e0, reflow_goal=0x7fff6abee1b0, document=..., layout_root=..., layout_context=0x7fff6abed2c8, rw_data=0x7fffb6a46020) at components/layout_thread/lib.rs:1113
#52 0x0000555556d9843c in layout_thread::LayoutThread::perform_post_main_layout_passes (self=0x7fff6abf0428, data=0x7fff6abee1e0, root_flow=0x7fff6abedb70, reflow_goal=0x7fff6abee1b0, document=..., rw_data=0x7fffb6a46020, layout_context=0x7fff6abed2c8) at components/layout_thread/lib.rs:1926
#53 0x0000555556d981ad in layout_thread::LayoutThread::perform_post_style_recalc_layout_passes (self=0x7fff6abf0428, root_flow=0x7fff6abedb70, data=0x7fff6abee1e0, reflow_goal=0x7fff6abee1b0, document=..., rw_data=0x7fffb6a46020, context=0x7fff6abed2c8, invalid_nodes=...) at components/layout_thread/lib.rs:1906
#54 0x0000555556d94b7f in layout_thread::LayoutThread::handle_reflow (self=0x7fff6abf0428, data=0x7fff6abee198, possibly_locked_rw_data=0x7fff6abf03e8) at components/layout_thread/lib.rs:1578
#55 0x0000555556e81eca in layout_thread::LayoutThread::handle_request_helper::{{closure}} ()
    at components/layout_thread/lib.rs:818
#56 0x0000555556e3e592 in profile_traits::time::profile (category=profile_traits::time::ProfilerCategory::LayoutPerform, meta=..., profiler_chan=..., callback=...) at /home/manishearth/mozilla/voser/components/profile_traits/time.rs:147
#57 0x0000555556d8d2da in layout_thread::LayoutThread::handle_request_helper (self=0x7fff6abf0428, request=..., possibly_locked_rw_data=0x7fff6abf03e8) at components/layout_thread/lib.rs:814
#58 0x0000555556d8c4ae in layout_thread::LayoutThread::handle_request (self=0x7fff6abf0428, possibly_locked_rw_data=0x7fff6abf03e8) at components/layout_thread/lib.rs:762
#59 0x0000555556d8ae73 in layout_thread::LayoutThread::start (self=...) at components/layout_thread/lib.rs:646
#60 0x0000555556e80ab5 in <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::{{closure}} () at components/layout_thread/lib.rs:369
#61 0x0000555556eab71c in profile_traits::mem::ProfilerChan::run_with_memory_reporting (self=0x7fff6abf4580, f=..., reporter_name="layout-reporter-(1,1)", channel_for_reporter=..., msg=0x0)
---Type <return> to continue, or q <return> to quit---
    at /home/manishearth/mozilla/voser/components/profile_traits/mem.rs:88
#62 0x0000555556e814f7 in <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}} ()
    at components/layout_thread/lib.rs:367
#63 0x0000555556fd9845 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...)
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/sys_common/backtrace.rs:136
#64 0x0000555556f96494 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} ()
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/thread/mod.rs:469
#65 0x0000555557000534 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=()) at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panic.rs:316
#66 0x000055555700b0f1 in std::panicking::try::do_call (data=0x7fff6abf4d10 "\001")
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panicking.rs:287
#67 0x000055555fe0465a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:81
#68 0x000055555700a568 in std::panicking::try (f=...)
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panicking.rs:265
#69 0x0000555557000926 in std::panic::catch_unwind (f=...)
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panic.rs:395
#70 0x0000555556f9626d in std::thread::Builder::spawn_unchecked::{{closure}} ()
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/thread/mod.rs:468
#71 0x0000555556f7c414 in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libcore/ops/function.rs:227
#72 0x000055555fde919f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/liballoc/boxed.rs:942
#73 0x000055555fe03720 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/liballoc/boxed.rs:942
#74 0x000055555fe03720 in std::sys_common::thread::start_thread () at src/libstd/sys_common/thread.rs:13
#75 0x000055555fe03720 in std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:79
#76 0x00007ffff51be6db in start_thread (arg=0x7fff6abfb700) at pthread_create.c:463
#77 0x00007ffff36f988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```
</details>

**Comment by Manishearth** [comment]
This seems to affect all Glitch pages, e.g. https://glitch.com/~iw-agenda-generator

**Comment by Manishearth** [comment]
Workaround is to use foo.glitch.me instead of glitch.com/~foo, but that's a different view.

**Comment by dralley** [comment]
Another variant from https://github.com/servo/servo/issues/20029, which appears to be a duplicate issue:

```
<div style="border-collapse: collapse; overflow-y: hidden; border-top: inset">
```

**Comment by simonwuelker** [comment]
This issue is not present in the new layout engine.
