### ISSUE TITLE
Linux perf data s3 upload is broken

### ISSUE THREAD

**Issue by jdm** [servo/servo#23302]
```
aws s3 sync --size-only --acl public-read ./etc/ci/performance/output s3://servo-perf
 in dir /home/servo/buildbot/slave/linux-nightly/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['aws', 's3', 'sync', '--size-only', '--acl', 'public-read', './etc/ci/performance/output', 's3://servo-perf']
 using PTY: False
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 28, in <module>
    from awscli.formatter import get_formatter
  File "/usr/local/lib/python2.7/dist-packages/awscli/formatter.py", line 20, in <module>
    from awscli.table import MultiTable, Styler, ColorizedStyler
  File "/usr/local/lib/python2.7/dist-packages/awscli/table.py", line 17, in <module>
    import colorama
ImportError: No module named colorama
```

**Comment by SimonSapin** [comment]
This is the upload of performance data. The Nightly build was moved to Taskcluster in https://github.com/servo/servo/pull/22464.
