### ISSUE TITLE
Intermittent failure in sampling profiler unit test

### ISSUE THREAD

**Issue by jdm** [servo/servo#23354]
Observed on a mac job on taskcluster:
```
thread 'test_sampler' panicked at 'assertion failed: data.len() > 1', components/background_hang_monitor/tests/hang_monitor_tests.rs:63:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: alloc::alloc::dealloc
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:408
   6: hang_monitor_tests::test_sampler
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:63
   7: hang_monitor_tests::test_sampler::{{closure}}
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:24
   8: core::ops::function::FnOnce::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  11: test::run_test::run_test_inner::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
failures:
    test_sampler

```

**Comment by CYBAI** [comment]
Also

```
---- test_hang_monitoring stdout ----
thread 'test_hang_monitoring' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: std::sys_common::poison::Flag::borrow
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/macros.rs:18
   9: std::sys_common::poison::Flag::borrow
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/result.rs:800
  10: hang_monitor_tests::test_hang_monitoring
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:74
  11: hang_monitor_tests::test_hang_monitoring::{{closure}}
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:73
  12: core::ops::function::FnOnce::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468

---- test_hang_monitoring_unregister stdout ----
thread 'test_hang_monitoring_unregister' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: std::sys_common::poison::Flag::borrow
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/macros.rs:18
   9: std::sys_common::poison::Flag::borrow
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/result.rs:800
  10: hang_monitor_tests::test_hang_monitoring_unregister
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:172
  11: hang_monitor_tests::test_hang_monitoring_unregister::{{closure}}
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:171
  12: core::ops::function::FnOnce::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
```

Refer to https://taskcluster-artifacts.net/FeGXLcSGR22CmNQyA-Ty5Q/0/public/logs/live_backing.log
