### ISSUE TITLE
Scope error for linux build task when creating new docker image build task

### ISSUE THREAD

**Issue by jdm** [servo/servo#23361]
When trying to test https://github.com/servo/servo/pull/23357 in isolation, I encountered this error on taskcluster:
```
Found task d5Ur5WfBRGC55RmXaWcfJQ indexed at project.servo.servo.docker-image.694b11174d014b57c829e87e93c94271efd8b517009c928290cbfcacb1cba8da
Traceback (most recent call last):
  File "/repo/etc/taskcluster/decisionlib.py", line 265, in find_or_create
    task_id = Task.find(index_path)
  File "/repo/etc/taskcluster/decisionlib.py", line 238, in find
    task_id = SHARED.index_service.findTask(full_index_path)["taskId"]
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/index.py", line 138, in findTask
    return self._makeApiCall(self.funcinfo["findTask"], *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 262, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 534, in _makeHttpRequest
    superExc=None
taskcluster.exceptions.TaskclusterRestFailure: Indexed task has expired

---

* method:     findTask
* errorCode:  ResourceNotFound
* statusCode: 404
* time:       2019-05-10T00:09:59.960Z
```
This looks like the expected behaviour when the docker image has expired. However, this was followed by:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "etc/taskcluster/decision_task.py", line 793, in <module>
    main(task_for=os.environ["TASK_FOR"])
  File "etc/taskcluster/decision_task.py", line 75, in main
    function()
  File "etc/taskcluster/decision_task.py", line 417, in linux_nightly
    .find_or_create("build.linux_x64_nightly" + CONFIG.git_sha)
  File "/repo/etc/taskcluster/decisionlib.py", line 271, in find_or_create
    task_id = self.create()
  File "/repo/etc/taskcluster/decisionlib.py", line 231, in create
    SHARED.queue_service.createTask(task_id, queue_payload)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/queue.py", line 169, in createTask
    return self._makeApiCall(self.funcinfo["createTask"], *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 262, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 534, in _makeHttpRequest
    superExc=None
taskcluster.exceptions.TaskclusterRestFailure: Client ID task-client/aKDUTOgER0ScnQfPVy9tjQ/0/on/us-west-1/i-0a13185c2ec113124/until/1557448184.498 does not have sufficient scopes and is missing the following scopes:

secrets:get:project/servo/s3-upload-credentials
```
Which doesn't make any sense to me.

**Comment by jdm** [comment]
This was explained to me on IRC: https://mozilla.logbot.info/servo/20190510#c16299745-c16299763
