### ISSUE TITLE
Unable to build mozjs-sys due to cargo home being on a different drive

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#23371]
```
--- stderr
which: python2.7: unknown command
Reticulating splines...
Traceback (most recent call last):
  File "c:/Users/kungf/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/e21c05b/mozjs/js/src/../../configure.py", line 124, in <module>
    sys.exit(main(sys.argv))
  File "c:/Users/kungf/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/e21c05b/mozjs/js/src/../../configure.py", line 35, in main
    return config_status(config)
  File "c:/Users/kungf/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/e21c05b/mozjs/js/src/../../configure.py", line 119, in config_status
    return config_status(args=[], **encode(sanitized_config, encoding))
  File "c:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\mozjs\python\mozbuild\mozbuild\config_status.py", line 146, in config_status
    the_backend.consume(definitions)
  File "c:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\mozjs\python\mozbuild\mozbuild\backend\base.py", line 128, in consume
    if (not self.consume_object(obj) and
  File "c:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\mozjs\python\mozbuild\mozbuild\backend\recursivemake.py", line 438, in consume_object
    consumed = CommonBackend.consume_object(self, obj)
  File "c:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\mozjs\python\mozbuild\mozbuild\backend\common.py", line 133, in consume_object
    with self._get_preprocessor(obj) as pp:
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\mozjs\python\mozbuild\mozbuild\backend\base.py", line 320, in _get_preprocessor
    srcdir_rel=mozpath.relpath(srcdir, mozpath.dirname(obj.output_path)),
  File "c:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\mozjs\python\mozbuild\mozpack\path.py", line 31, in relpath
    rel = normsep(os.path.relpath(path, start))
  File "d:\Workspace\servo\target\debug\build\mozjs_sys-7ec9cbde7792de62\out\_virtualenvs\init\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive d:
mozmake: *** [makefile.cargo:182: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\kungf\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\e21c05b\build.rs:117:5
stack backtrace:
   0: std::sys_common::backtrace::_print
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\sys_common\backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\panicking.rs:197
   2: std::panicking::default_hook
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\panicking.rs:211
   3: std::panicking::rust_panic_with_hook
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\panicking.rs:474
   4: std::panicking::begin_panic<str*>
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\panicking.rs:408
   5: build_script_build::build_jsapi
             at .\build.rs:117
   6: build_script_build::main
             at .\build.rs:22
   7: std::rt::lang_start::{{closure}}<()>
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\rt.rs:64
   8: std::panicking::try::do_call<closure,i32>
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\panicking.rs:293
   9: panic_unwind::__rust_maybe_catch_panic
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libpanic_unwind\lib.rs:85
  10: std::rt::lang_start_internal
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\rt.rs:48
  11: std::rt::lang_start<()>
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\rt.rs:64
  12: main
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  14: BaseThreadInitThunk
  15: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
```

My cargo home directory is located at `C:\Users\kungf\.cargo` as it is shown in the logs, but my servo project root is located in `D:\Workspace\servo`. I'm not sure what the best way to fix this is -- is it even possible to instruct cargo to install packages under a different drive/path?

**Comment by jdm** [comment]
You could probably work around this by using a cargo.toml patch that points at a clone mozjs on the same drive as servo.

**Comment by jdm** [comment]
Alternatively, it seems like the CARGO_HOME variable is able to change where cargo looks for packages: https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by KiChjang** [comment]
I was able to get servo compiling by setting CARGO_HOME to `.\.cargo`, though I'm not sure if this is a good general solution to make a PR for.

**Comment by KiChjang** [comment]
I ended up putting `mach.bat` into `.git/info/exclude`.
