### ISSUE TITLE
Servo build failure RPMBUILD

### ISSUE THREAD

**Issue by gatoWololo** [servo/servo#23648]
As of the latest commit on master  61cadfa building Servo on Ubuntu failed with:
```
error:
INFO: checking for rpmbuild...
DEBUG: rpmbuild: Trying rpmbuild INFO: not found
```
Doing `./mach bootstrap` returns `Dependencies were already installed!`. Should we add `rpm` as a dependency for mach boostrap?

After manually installing RPM I now see:
```
DEBUG: rpmbuild: Trying rpmbuild
INFO: /usr/bin/rpmbuild

--- stderr
Traceback (most recent call last):
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/js/src/../../configure.py", line 132, in <module>
    sys.exit(main(sys.argv))
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/js/src/../../configure.py", line 38, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 481, in run
    func(*args)
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 525, in _value_for
    return self._value_for_depends(obj)
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/util.py", line 947, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 534, in _value_for_depends
    value = obj.result()
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/util.py", line 947, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 151, in result
    return self._func(*resolved_args)
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1097, in wrapped
    return new_func(*args, **kwargs)
  File "/home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/mozjs/moz.configure", line 604, in llvm_objdump
    clang = bindgen_config_paths.clang_path
AttributeError: 'ReadOnlyNamespace' object has no attribute 'clang_path'
make: *** [makefile.cargo:186: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /home/gatowololo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b2f8393/build.rs:117:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

```

**Comment by jdm** [comment]
My immediate suggestion is to try installing the clang, llvm, and llvm-dev packages.

**Comment by gatoWololo** [comment]
Installing `llvm-dev` fixed this for me!

**Comment by KiChjang** [comment]
Closing as fixed.
