### ISSUE TITLE
Can't move camera in babylon demos

### ISSUE THREAD

**Issue by jdm** [servo/servo#24363]
```
[2019-10-03T19:24:15Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:234 setting getter-only property "buttons"
[2019-10-03T19:24:15Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:15Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:15Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:16Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:16Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:16Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:16Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:17Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:153:28 setting getter-only property "buttons"
[2019-10-03T19:24:26Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:26Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:26Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:29Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
[2019-10-03T19:24:45Z ERROR script::dom::bindings::error] Error at https://code.jquery.com/pep/0.4.2/pep.min.js:149:48 setting getter-only property "buttons"
```

**Comment by jdm** [comment]
This comes from this code:
```
prepareButtonsForMove:function(a,b){var c=H.get(this.POINTER_ID);
// Update buttons state after possible out-of-document mouseup.
0!==b.which&&c?a.buttons=c.buttons:a.buttons=0,b.buttons=a.buttons}
```
I believe b comes from calling this function:
```
prepareEvent:function(a){var b=u.cloneEvent(a),c=b.preventDefault;return b.preventDefault=function(){a.preventDefault(),c()},b.pointerId=this.POINTER_ID,b.isPrimary=!0,b.pointerType=this.POINTER_TYPE,b}
```
And then there's:
```
     * Returns a snapshot of inEvent, with writable properties.
     *
     * @param {Event} inEvent An event that contains properties to copy.
     * @return {Object} An object containing shallow copies of `inEvent`'s
     *    properties.
     */
cloneEvent:function(a){for(var b,c=Object.create(null),d=0;d<q.length;d++)b=q[d],c[b]=a[b]||r[d],
// Work around SVGInstanceElement shadow tree
// Return the <use> element that is represented by the instance for Safari, Chrome, IE.
// This is the behavior implemented by Firefox.
!t||"target"!==b&&"relatedTarget"!==b||c[b]instanceof SVGElementInstance&&(c[b]=c[b].correspondingUseElement);
// keep the semantics of preventDefault
return a.preventDefault&&(c.preventDefault=function(){a.preventDefault()}),c}
```
So something about cloneEvent is causing the writable properties not to work right.

**Comment by jdm** [comment]
```
var q=[
// MouseEvent
"bubbles","cancelable","view","detail","screenX","screenY","clientX","clientY","ctrlKey","altKey","shiftKey","metaKey","button","relatedTarget",
// DOM Level 3
"buttons",
// PointerEvent
"pointerId","width","height","pressure","tiltX","tiltY","pointerType","hwTimestamp","isPrimary",
// event instance
"type","target","currentTarget","which","pageX","pageY","timeStamp"],r=[
// MouseEvent
!1,!1,null,null,0,0,0,0,!1,!1,!1,!1,0,null,
// DOM Level 3
0,
// PointerEvent
0,0,0,0,0,0,"",0,!1,
// event instance
"",null,null,0,0,0,0]
```

**Comment by jdm** [comment]
Adding SVGElementInstance through a userscript did not make a difference.

**Comment by paulrouget** [comment]
Which demo?

**Comment by jdm** [comment]
Anyif the ones that I've tried on desktop.

**Comment by paulrouget** [comment]
Oh, not in immersive mode right?

**Comment by jdm** [comment]
Correct.

**Comment by jdm** [comment]
This now works as expected. I wonder if #24409 fixed it?

**Comment by paulrouget** [comment]
> This now works as expected. I wonder if #24409 fixed it?

Nope. I changed the bbjs code to not fail.

**Comment by paulrouget** [comment]
To reproduce: http://paulrouget.com/test/bbjs/basic/index.pepbug.html

**Comment by paulrouget** [comment]
This is actually the proper behavior when using `use strict;` + `event.buttons = ...`.

The problem is that this jquery test fails when it should not: https://github.com/jquery/PEP/blob/e880e9d26c7a45cab153b8bf2e03fc51b64844bf/src/mouse.js#L13

The `buttons` property is introduced here where it is set to 0 not matter what comes with the constructor: https://github.com/servo/servo/commit/be3cb00c775f7adff864200512f54ec8d8090a09#diff-bc92fc3e149d38d401fb237b255cab2cR133

PR incoming.

**Comment by paulrouget** [comment]
With #24564, no errors, and the camera moves as expected.
