### ISSUE TITLE
Intermittent failure of fetch::test_fetch_blocked_nosniff

### ISSUE THREAD

**Issue by gterzian** [servo/servo#24380]
```
thread 'fetch::test_fetch_blocked_nosniff' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', components/net/tests/fetch.rs:771:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:207
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  13: std::thread::local::fast::Key<T>::try_initialize
  14: main::fetch::test_fetch_blocked_nosniff::test_nosniff_request
             at components/net/tests/fetch.rs:771
  15: main::fetch::test_fetch_blocked_nosniff
             at components/net/tests/fetch.rs:782
  16: main::fetch::test_fetch_blocked_nosniff::{{closure}}
             at components/net/tests/fetch.rs:742
  17: core::ops::function::FnOnce::call_once
             at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/libcore/ops/function.rs:227
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/liballoc/boxed.rs:922
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: std::panicking::try
             at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/libstd/panicking.rs:271
  21: std::panic::catch_unwind
             at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/libstd/panic.rs:394
  22: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1460
```

Noted while running tests locally at https://github.com/servo/servo/pull/24318

**Comment by TimvdLippe** [comment]
Closing as stale as this issue has not received any failure references for over a month
