### ISSUE TITLE
WPT update job broke

### ISSUE THREAD

**Issue by jdm** [servo/servo#24666]
```
+ ./etc/ci/update-wpt-checkout fetch-and-update-expectations
Switched to a new branch 'wpt_update'
"/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/bin/python2.7" "-m" "pip" "install" "-I" "-r" "/Users/worker/tasks/task_1572948828/repo/tests/wpt/web-platform-tests/tools/wptrunner/requirements_firefox.txt" failed with error code 2:
Output:
Processing /Users/worker/Library/Caches/pip/wheels/08/79/46/3694e3dbc401d02a1e3677c89b8ecda9f22f8e157dde381aa1/marionette_driver-3.0.0-cp27-none-any.whl
Collecting mozcrash==1.1.0
  Using cached https://files.pythonhosted.org/packages/c6/c6/84b232a5e1ebf97287211777b3859d86b9e268d288568f66a5e3db751933/mozcrash-1.1.0-py2.py3-none-any.whl
Collecting mozdownload==1.26.0
  Using cached https://files.pythonhosted.org/packages/d1/19/01b869f8c4fb65fc6590b7edcfe8a04aaa30468d7e1634579498853070db/mozdownload-1.26.0-py2-none-any.whl
Processing /Users/worker/Library/Caches/pip/wheels/b3/09/b9/b682485afe40c958580e07d8556e4eb5a88af90c1d75d9daf4/mozInstall-2.0.0-py2.py3-none-any.whl
Collecting mozleak==0.2
  Using cached https://files.pythonhosted.org/packages/e0/f9/f8e451afe9bc366efc968a9bd8c18c3830a6770a766f8f4373f7045aa488/mozleak-0.2-py2.py3-none-any.whl
Processing /Users/worker/Library/Caches/pip/wheels/c3/f6/ed/ac0af1e6be733e088b2f70845130a48fb16cbb0ccb5f89db28/moznetwork-0.27-cp27-none-any.whl
Collecting mozprocess==1.0.0
  Using cached https://files.pythonhosted.org/packages/3f/de/cd2d1831026bff999ee7ee47fe7e2c26f402c9504cdaaa2d20e2f5775966/mozprocess-1.0.0-py2.py3-none-any.whl
Collecting mozprofile==2.4.0
  Using cached https://files.pythonhosted.org/packages/0d/be/642d5f8565a0b0e929ef97b14f867da68ccfe001da8c2dba904e95dbb966/mozprofile-2.4.0-py2.py3-none-any.whl
Collecting mozrunner==7.7.0
  Using cached https://files.pythonhosted.org/packages/91/df/7cf7b37d015928bd0306f9870a2844ebac35059944d0416c46014c837621/mozrunner-7.7.0-py2.py3-none-any.whl
Collecting mozversion==2.2.0
  Using cached https://files.pythonhosted.org/packages/25/ba/93f13ea23a44e22ca48601b495eed55c803e178ab085e9da6ba7f3bc9bb6/mozversion-2.2.0-py2.py3-none-any.whl
Collecting psutil==5.6.4
  Downloading https://files.pythonhosted.org/packages/47/ea/d3b6d6fd0b4a6c12984df652525f394e68c8678d2b05075219144eb3a1cf/psutil-5.6.4.tar.gz (447kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
Error:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/Users/worker/tasks/task_1572948828/repo/python/_virtualenv/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable
```

**Comment by jdm** [comment]
https://github.com/web-platform-tests/wpt/pull/20177 will fix this.

**Comment by SimonSapin** [comment]
It seems back up.
