### ISSUE TITLE
Moon Rider a-frame demo triggers gstreamer critical failure

### ISSUE THREAD

**Issue by jdm** [servo/servo#24800]
```
godot:master-servo jdm$ ./mach run -d https://aframe.io/examples/showcase/moonrider/
A-Frame Version: 0.9.2 (Date 2019-05-30, Commit #154f7d07)
three Version (https://github.com/supermedium/three.js):
^0.102.2
WebVR Polyfill Version:
^0.10.10
%ccore:schema:warn %cDefault value `false` does not match type `number` in component `layout`%c
color: orange
color: inherit
color: orange
[2019-11-20T17:48:42Z ERROR script::dom::bindings::error] Error at https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js:2:57408 Error: No input element in the page matches .docs-search-sidebar .search-field
THREE.WebGLRenderer
103dev
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
null

(<unknown>:61281): GStreamer-CRITICAL **: 12:48:45.890: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:61281): GStreamer-CRITICAL **: 12:48:45.890: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(<unknown>:61281): GLib-CRITICAL **: 12:48:45.890: g_source_set_callback: assertion 'source != NULL' failed

(<unknown>:61281): GStreamer-CRITICAL **: 12:48:45.893: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed
Stack trace
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace
   2: backtrace::capture::Backtrace::create
   3: backtrace::capture::Backtrace::new
   4: servo::install_crash_handler::handler
   5: _sigtramp
   6: g_source_attach
   7: gst_player_main
   8: g_thread_proxy
   9: _pthread_body
  10: _pthread_start
```

**Comment by jdm** [comment]
Similar behaviour for https://aframe.io/examples/showcase/beatsaver-viewer/.
```
godot:master-servo jdm$ ./mach run -d https://aframe.io/examples/showcase/beatsaver-viewer//
A-Frame Version: 0.8.2 (Date 2019-11-20, Commit #358c5da5)
three Version:
0.95.0
[2019-11-20T17:51:19Z ERROR script::dom::bindings::error] Error at https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js:2:57408 Error: No input element in the page matches .docs-search-sidebar .search-field
%ccore:schema:warn %cDefault value `false` does not match type `number` in component `layout`%c
color: orange
color: inherit
color: orange
THREE.WebGLRenderer
95
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
[2019-11-20T17:51:19Z ERROR script::dom::bindings::error] Error at https://supermedium.com/beatsaver-viewer/build/build.js:145:1962 document.getElementById(...) is null

(<unknown>:62946): GStreamer-CRITICAL **: 12:51:20.601: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:62946): GStreamer-CRITICAL **: 12:51:20.604: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:62946): GLib-ERROR **: 12:51:20.623: Creating pipes for GWakeup: Too many open files
Servo exited with return value -5
```

**Comment by jdm** [comment]
And https://aframe.io/examples/showcase/a-painter/:
```
godot:servo jdm$ ./mach run -r https://aframe.io/examples/showcase/a-painter
[2019-11-20T18:04:14Z ERROR script::dom::bindings::error] Error at https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js:2:57408 Error: No input element in the page matches .docs-search-sidebar .search-field
A-Frame Version: 0.7.0 (Date 2018-02-05, Commit #39daf67)
three Version:
github:dmarcos/three.js#r89fix
WebVR Polyfill Version:
^0.9.40
%ccore:schema:warn %cDefault value `0 1 0` does not match type `vec3` in component `teleport-controls`%c
color: orange
color: inherit
color: orange
THREE.WebGLRenderer
89
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
THREE.XHRLoader has been renamed to THREE.FileLoader.
A-PAINTER Version: 1.2
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
https://cdn.aframe.io/a-painter/sounds/ui_click0.ogg
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
https://cdn.aframe.io/a-painter/sounds/ui_click1.ogg
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
https://cdn.aframe.io/a-painter/sounds/ui_menu.ogg
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
https://cdn.aframe.io/a-painter/sounds/ui_undo.ogg
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
https://cdn.aframe.io/a-painter/sounds/ui_tick.ogg
%ccore:a-assets:warn %cCross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)%c
color: orange
color: inherit
color: orange
https://cdn.aframe.io/a-painter/sounds/ui_paint.ogg

(<unknown>:71117): GStreamer-CRITICAL **: 13:04:16.396: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:71117): GStreamer-CRITICAL **: 13:04:16.396: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:71117): GStreamer-CRITICAL **: 13:04:16.397: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:71117): GStreamer-CRITICAL **: 13:04:16.397: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(<unknown>:71117): GStreamer-CRITICAL **: 13:04:16.397: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(<unknown>:71117): GLib-CRITICAL **: 13:04:16.397: g_source_set_callback: assertion 'source != NULL' failed
Stack trace
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: servo::install_crash_handler::handler
   3: _sigtramp
   4: g_source_attach
   5: gst_player_main
   6: g_thread_proxy
   7: _pthread_body
   8: _pthread_start

Servo exited with return value 11
```
