### ISSUE TITLE
Mint 19.2 VM on Virtualbox under Windows 10 can't build osmesa for release

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24852]
I notice these errors seem to have a lot of messages in common with issue #22063. This only happens in -r; in -d this part of the build goes fine. This his happened for me for two separate 64-bit Mint 19.2 VMs on Virtualbox under two separate Windows 10 host machines.

error: failed to run custom build command for `osmesa-src v0.1.1 (https://github.com/servo/osmesa-src#1a9519c3)`

Caused by:
  process didn't exit successfully: `/home/pshaughn/servo/target/release/build/osmesa-src-9e8fc9ae85dee98a/build-script-build` (exit code: 101)
--- stdout
running: "touch" "configure.ac" "aclocal.m4" "configure" "Makefile.am" "Makefile.in" "src/compiler/glsl/glcpp/glcpp-lex.c" "src/mesa/program/lex.yy.c" "src/compiler/glsl/glcpp/glcpp-parse.c" "src/compiler/glsl/glsl_parser.cpp" "src/mesa/program/program_parse.tab.c" "src/compiler/glsl/glsl_lexer.cpp" "src/glx/indirect.h" "src/glx/indirect_init.c" "src/mapi/glapi/glapi_mapi_tmp.h"
running: "/home/pshaughn/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1a9519c/mesa-src/configure" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--disable-dri" "--disable-driglx-direct" "--disable-dri3" "--disable-egl" "--disable-gbm" "--disable-gles1" "--disable-gles2" "--disable-glx" "--disable-glx-tls" "--with-platforms=" "--enable-gallium-osmesa" "--with-gallium-drivers=swrast"
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for x86_64-unknown-linux-gnu-gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking dependency style of clang... gcc3
checking for x86_64-unknown-linux-gnu-ar... no
checking for x86_64-unknown-linux-gnu-lib... no
checking for x86_64-unknown-linux-gnu-link... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to run the C preprocessor... clang -E
checking for x86_64-unknown-linux-gnu-gcc... (cached) clang
checking whether we are using the GNU C compiler... (cached) yes
checking whether clang accepts -g... (cached) yes
checking for clang option to accept ISO C89... (cached) none needed
checking whether clang understands -c and -o together... (cached) yes
checking dependency style of clang... (cached) gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking dependency style of clang++... gcc3
checking for grep that handles long lines and -e... /bin/grep
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking dependency style of clang... gcc3
checking for GNU make... make
checking for a Python interpreter with version >= 2.7... python
checking for python... /home/pshaughn/servo/python/_virtualenv/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for a sed that does not truncate output... /bin/sed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by clang... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for x86_64-unknown-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-unknown-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-unknown-linux-gnu-ar... ar
checking for archiver @FILE support... @
checking for x86_64-unknown-linux-gnu-strip... no
checking for strip... strip
checking for x86_64-unknown-linux-gnu-ranlib... no
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from clang object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-unknown-linux-gnu-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fPIC -DPIC
checking if clang PIC flag -fPIC -DPIC works... yes
checking if clang static flag -static works... yes
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... clang++ -E
checking for ld used by clang++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the clang++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for clang++ option to produce PIC... -fPIC -DPIC
checking if clang++ PIC flag -fPIC -DPIC works... yes
checking if clang++ static flag -static works... yes
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for rm... rm -f
checking for bison... bison -y
checking if bison is the parser generator... yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking if flex is the lexer generator... yes
checking for indent... cat
checking if module mako in python is installed... no
checking if compiling with clang... yes
checking whether __SUNPRO_C is declared... no
checking for __builtin_bswap32... yes
checking for __builtin_bswap64... yes
checking for __builtin_clz... yes
checking for __builtin_clzll... yes
checking for __builtin_ctz... yes
checking for __builtin_expect... yes
checking for __builtin_ffs... yes
checking for __builtin_ffsll... yes
checking for __builtin_popcount... yes
checking for __builtin_popcountll... yes
checking for __builtin_unreachable... yes
checking for __attribute__((const))... yes
checking for __attribute__((flatten))... yes
checking for __attribute__((format))... yes
checking for __attribute__((malloc))... yes
checking for __attribute__((packed))... yes
checking for __attribute__((pure))... yes
checking for __attribute__((returns_nonnull))... yes
checking for __attribute__((unused))... yes
checking for __attribute__((visibility))... yes
checking for __attribute__((warn_unused_result))... yes
checking for __attribute__((weak))... yes
checking for __attribute__((alias))... yes
checking for __attribute__((noreturn))... yes
checking for x86_64-unknown-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Werror=implicit-function-declaration... yes
checking whether C compiler accepts -Werror=missing-prototypes... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wmissing-field-initializers... yes
checking whether C compiler accepts -Wformat-truncation... no
checking whether C compiler accepts -fno-math-errno... yes
checking whether C compiler accepts -fno-trapping-math... yes
checking whether C compiler accepts -fvisibility=hidden... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -fno-math-errno... yes
checking whether C++ compiler accepts -fno-trapping-math... yes
checking whether C++ compiler accepts -fvisibility=hidden... yes
checking whether C++ compiler accepts -Wmissing-field-initializers... yes
checking whether C++ compiler accepts -Wformat-truncation... no
checking whether C compiler accepts -Werror=pointer-arith... yes
checking whether C compiler accepts -Werror=vla... yes
checking whether C++ compiler accepts -Werror=pointer-arith... yes
checking whether C++ compiler accepts -Werror=vla... yes
checking whether c++11 is enabled by default... yes
checking whether C compiler accepts -Woverride-init... no
checking whether C compiler accepts -Winitializer-overrides... yes
checking whether __atomic_load_n is supported... yes
checking whether __sync_add_and_fetch_8 is supported... yes
checking whether byte ordering is bigendian... no
checking whether gcc supports -mpower8-vector... no
checking if ld supports -Bsymbolic... yes
checking whether ld supports --gc-sections... yes
checking if the linker supports version-scripts... yes
checking if the linker supports --dynamic-list... yes
checking whether to enable assembly... yes, x86_64
checking whether sys/types.h defines makedev... no
checking sys/mkdev.h usability... no
checking sys/mkdev.h presence... no
checking for sys/mkdev.h... no
checking sys/sysmacros.h usability... yes
checking sys/sysmacros.h presence... yes
checking for sys/sysmacros.h... yes
checking xlocale.h usability... no
checking xlocale.h presence... no
checking for xlocale.h... no
checking sys/sysctl.h usability... yes
checking sys/sysctl.h presence... yes
checking for sys/sysctl.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking for dlfcn.h... (cached) yes
checking for strtof... yes
checking for mkostemp... yes
checking for timespec_get... yes
checking for memfd_create... yes
checking whether strtod has locale support... yes
checking for dlopen... no
checking for dlopen in -ldl... yes
checking for dladdr... yes
checking for dl_iterate_phdr... yes
checking for clock_gettime... yes
checking for posix_memalign... yes
checking for zlib >= 1.2.3... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether pthread_setaffinity_np is supported... yes
checking linux/futex.h usability... yes
checking linux/futex.h presence... yes
checking for linux/futex.h... yes
checking for libelf... no
checking for elf_memory in -lelf... no
checking for x86_64-unknown-linux-gnu-llvm-config... no
checking for llvm-config... /usr/bin/llvm-config
checking for libunwind... yes
checking for libdrm >= 2.4.75... yes
checking for expat... yes

--- stderr
No module named mako
Package libtizcore was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtizcore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtizcore' found
/home/pshaughn/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1a9519c/mesa-src/configure: line 23721: test: : integer expression expected
/home/pshaughn/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1a9519c/mesa-src/configure: line 23727: test: : integer expression expected
configure: error: LLVM 3.3.0 or newer is required for gallium
thread 'main' panicked at 'failed with: exit code: 1', /home/pshaughn/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1a9519c/build.rs:76:9
stack backtrace:
   0:     0x55a95ad90cc4 - backtrace::backtrace::libunwind::trace::hf6fab806f99173ae
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55a95ad90cc4 - backtrace::backtrace::trace_unsynchronized::h9d880e161d3dd682
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55a95ad90cc4 - std::sys_common::backtrace::_print_fmt::h7fa7703959a17af0
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x55a95ad90cc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he957ece4cedb167a
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55a95adae10c - core::fmt::write::h58c6b2373fe36ade
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55a95ad8ee77 - std::io::Write::write_fmt::h60db73a9329f6f82
                               at src/libstd/io/mod.rs:1412
   6:     0x55a95ad92d6e - std::sys_common::backtrace::_print::h229cbaa1a1c4ad99
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55a95ad92d6e - std::sys_common::backtrace::print::h7f2c9bdc49f4ce67
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55a95ad92d6e - std::panicking::default_hook::{{closure}}::h70a5919b862fb68b
                               at src/libstd/panicking.rs:188
   9:     0x55a95ad92a61 - std::panicking::default_hook::hccd427c2c397d85b
                               at src/libstd/panicking.rs:205
  10:     0x55a95ad933bb - std::panicking::rust_panic_with_hook::h5b585879e33d0e2b
                               at src/libstd/panicking.rs:464
  11:     0x55a95ad92f5e - std::panicking::continue_panic_fmt::h01f40c7ab9f22e43
                               at src/libstd/panicking.rs:373
  12:     0x55a95ad92e9f - std::panicking::begin_panic_fmt::h53ce78b634a0dfa1
                               at src/libstd/panicking.rs:328
  13:     0x55a95ad8731a - build_script_build::run::h0f8a51819e816d91
  14:     0x55a95ad86c40 - build_script_build::main::h5fd11b035ebba1ae
  15:     0x55a95ad85943 - std::rt::lang_start::{{closure}}::he5336b4f63b39588
  16:     0x55a95ad92e33 - std::rt::lang_start_internal::{{closure}}::h157dcfe4decb817a
                               at src/libstd/rt.rs:48
  17:     0x55a95ad92e33 - std::panicking::try::do_call::hc2f5aba95a6f451f
                               at src/libstd/panicking.rs:287
  18:     0x55a95ad98fea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:81
  19:     0x55a95ad9389d - std::panicking::try::h2c111f6072f0d75a
                               at src/libstd/panicking.rs:265
  20:     0x55a95ad9389d - std::panic::catch_unwind::h29bae07df62a8939
                               at src/libstd/panic.rs:395
  21:     0x55a95ad9389d - std::rt::lang_start_internal::h53a1cfbcc48622f0
                               at src/libstd/rt.rs:47
  22:     0x55a95ad87362 - main
  23:     0x7f013b843b97 - __libc_start_main
  24:     0x55a95ad8585a - _start
  25:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
   Completed encoding_rs v0.8.12 in 15.2s
error: build failed
Build FAILED in 0:00:18

**Comment by pshaughn** [comment]
additional note: the system LLVM is at 6.0.0, so the "LLVM 3.3.0 or newer is required for gallium" message is a red herring unless mach has itself somehow pulled in an older LLVM.

**Comment by jdm** [comment]
I doubt it's a red herring so much as a real indication that the configure script is not finding the installed version of LLVM.

**Comment by pshaughn** [comment]
Quite possible! The line it references there where it's expecting an integer is testing $LLVM_VERSION_MAJOR; I don't know what is responsible for setting that here?

**Comment by jdm** [comment]
It comes from this:
```
llvm_set_environment_variables() {
    if test "x$LLVM_CONFIG" != xno; then
        LLVM_VERSION=`$LLVM_CONFIG --version | egrep -o '^[0-9.]+'`
        LLVM_CPPFLAGS=`strip_unwanted_llvm_flags "$LLVM_CONFIG --cppflags"`
        LLVM_INCLUDEDIR=`$LLVM_CONFIG --includedir`
        LLVM_LIBDIR=`$LLVM_CONFIG --libdir`

        # We need to respect LLVM_CPPFLAGS when compiling LLVM headers.
        save_CFLAGS="$CFLAGS"
        CFLAGS="$CFLAGS $LLVM_CPPFLAGS"

        if ac_fn_c_compute_int "$LINENO" "LLVM_VERSION_MAJOR" "LLVM_VERSION_MAJOR"        "#include \"${LLVM_INCLUDEDIR}/llvm/Config/llvm-config.h\""; then :

fi

        if ac_fn_c_compute_int "$LINENO" "LLVM_VERSION_MINOR" "LLVM_VERSION_MINOR"        "#include \"${LLVM_INCLUDEDIR}/llvm/Config/llvm-config.h\""; then :

fi

        if ac_fn_c_compute_int "$LINENO" "LLVM_VERSION_PATCH" "LLVM_VERSION_PATCH"        "#include \"${LLVM_INCLUDEDIR}/llvm/Config/llvm-config.h\""; then :

fi


        CFLAGS="$save_CFLAGS"

        # Only needed for LLVM < 3.6.0
        if test -z "$LLVM_VERSION_PATCH"; then
            LLVM_VERSION_PATCH=0
        fi

        LLVM_VERSION_INT="${LLVM_VERSION_MAJOR}0${LLVM_VERSION_MINOR}"

        FOUND_LLVM=yes
    else
        FOUND_LLVM=no
        LLVM_VERSION_INT=0
    fi
}
```
And llvm-config is coming from /usr/bin/llvm-config based on `checking for llvm-config... /usr/bin/llvm-config` in the log.

**Comment by jdm** [comment]
If you're using Mint, have you tried `./mach bootstrap`? Otherwise, you might want to verify that the LLVM development package is installed.

**Comment by pshaughn** [comment]
I used mach bootstrap, then later in the build I got a complaint about not having some llvm thing, so I also used apt install llvm. I have not yet tried apt installing llvm-dev, only llvm, so if it needs dev that could be the issue (all this would also imply that mach bootstrap is missing something it should have).

**Comment by jdm** [comment]
Yes, llvm-dev is required, so https://github.com/servo/servo/blob/master/python/servo/bootstrap.py#L114 and https://github.com/servo/servo/blob/master/README.md#on-debian-based-linuxes should be updated to include the appropriate package.
