### ISSUE TITLE
Some ways of adding, getting, and removing HTMLSelectElement options don't work

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25003]
WPT custom-elements/reactions/HTMLSelectElement.html adds and removes `<option>` elements from a `<select>` various ways. `select[0]=option` and `select.add(option)` fail to add, and `select[0] = null` fails to remove. `select.length = 0` and `select.remove(0)` do successfully remove. (appendChild and removeChild are not tested by this test)

**Comment by pshaughn** [comment]
WebIDL/ecmascript-binding/legacy-platform-object.html is trying to ["0"] a select and getting undefined instead of an option. Much of what's happening here might relate to incomplete "legacy platform object" implementation; https://heycam.github.io/webidl/#es-legacy-platform-objects describes various things legacy platform objects are supposed to be able to do.

**Comment by pshaughn** [comment]
html/semantics/forms/the-select-element/select-add.html is also having trouble here.

**Comment by pshaughn** [comment]
The indexed setter is commented out in HTMLSelectElement.webidl, and while that doesn't account for every one of these failures, it accounts for several!

**Comment by pshaughn** [comment]
Both add() and the indexed setter just need to forward to already-existing methods in HTMLOptionsCollection, and maybe that will fix it all.

**Comment by pshaughn** [comment]
uncommenting the indexed setter from HTMLSelectElement.webidl produces this:

```
error: failed to run custom build command for `script v0.0.1 (/home/pshaughn/servo/components/script)`

Caused by:
  process didn't exit successfully: `/home/pshaughn/servo/target/debug/build/script-f05a965ea2abfd61/build-script-build` (exit code: 1)
--- stderr
Traceback (most recent call last):
  File "dom/bindings/codegen/run.py", line 119, in <module>
    main()
  File "dom/bindings/codegen/run.py", line 52, in main
    module = CGBindingRoot(config, prefix, filename).define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 6772, in define
    return stripTrailingWhitespace(self.root.define())
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1915, in define
    defn = self.child.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1915, in define
    defn = self.child.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1915, in define
    defn = self.child.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2351, in define
    return self.join(child.define() for child in self.children if child is not None)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2348, in join
    return self.joiner.join(s for s in iterable if len(s) > 0)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2348, in <genexpr>
    return self.joiner.join(s for s in iterable if len(s) > 0)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2351, in <genexpr>
    return self.join(child.define() for child in self.children if child is not None)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 6349, in define
    return self.cgRoot.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2351, in define
    return self.join(child.define() for child in self.children if child is not None)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2348, in join
    return self.joiner.join(s for s in iterable if len(s) > 0)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2348, in <genexpr>
    return self.joiner.join(s for s in iterable if len(s) > 0)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2351, in <genexpr>
    return self.join(child.define() for child in self.children if child is not None)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1915, in define
    defn = self.child.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1915, in define
    defn = self.child.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1915, in define
    defn = self.child.define()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2351, in define
    return self.join(child.define() for child in self.children if child is not None)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2348, in join
    return self.joiner.join(s for s in iterable if len(s) > 0)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2348, in <genexpr>
    return self.joiner.join(s for s in iterable if len(s) > 0)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2351, in <genexpr>
    return self.join(child.define() for child in self.children if child is not None)
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 2578, in define
    body = self.definition_body()
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 5277, in definition_body
    return CGGeneric(self.getBody())
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 5268, in getBody
    CGIndenter(CGProxyNamedGetter(self.descriptor)).define() +
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 5087, in __init__
    CGProxySpecialOperation.__init__(self, descriptor, 'NamedGetter')
  File "/home/pshaughn/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 5004, in __init__
    assert len(operation.signatures()) == 1
AttributeError: 'NoneType' object has no attribute 'signatures'

Build FAILED in 0:00:12
```

It looks kind of like it's trying to find a NamedGetter, despite that not being necessary here at all.

**Comment by pshaughn** [comment]
possibly https://github.com/servo/servo/blob/1d645f37418719a3f965f5729543c97c2d057d01/components/script/dom/bindings/codegen/CodegenRust.py#L5266 needs to be an elif like https://github.com/servo/servo/blob/1d645f37418719a3f965f5729543c97c2d057d01/components/script/dom/bindings/codegen/CodegenRust.py#L5252 and it just hasn't come up because this is the first time it's had an indexed setter thrown at it without also having a named getter.
