### ISSUE TITLE
Test runner for .xml tests gets unexpected results "from undefinedundefinedundefined"

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25134]
getElementsByClassName-10.xml and getElementsByClassName-11.xml also do this for me. I'm in Mint 19.2.

```pshaughn@pshaughn-VirtualBox:~/servo$ ./mach test-wpt dom/nodes/Node-contains-xml.xml --headless
Running 1 tests in web-platform-tests

  ▶ ERROR [expected OK] /dom/nodes/Node-contains-xml.xml
  │   → Got results from undefinedundefinedundefined, expected /dom/nodes/Node-contains-xml.xml
  │   → Traceback (most recent call last):
  │   →   File "/home/pshaughn/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 251, in run_test
  │   →     result = self.do_test(test)
  │   →   File "/home/pshaughn/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 110, in do_test
  │   →     result = self.convert_result(test, self.result_data)
  │   →   File "/home/pshaughn/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 71, in __call__
  │   →     (result_url, test.url))
  └   → AssertionError: Got results from undefinedundefinedundefined, expected /dom/nodes/Node-contains-xml.xml

Ran 1 tests finished in 8.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests had errors unexpectedly```

**Comment by pshaughn** [comment]
I can't reproduce this myself now; it might have been a problem in my python environment related to #25247.

**Comment by pshaughn** [comment]
I'm going to assume my environment here and close it.
