### ISSUE TITLE
Python stack trace in WPT cors/basic.htm

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25180]
I don't have a WPT setup for other browsers so I don't know if this stack trace is a Servo problem or a WPT problem; all browsers are failing this test, so it could be a WPT problem. What happens after this trace is Servo receiving a 500 response (what the test server does on an uncaught exception in general) with a body that naturally doesn't contain the string it wants.

  File "/home/pshaughn/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 314, in __call__
    rv = self.func(request, response)
  File "/home/pshaughn/servo/tests/wpt/web-platform-tests/cors/resources/cors-makeheader.py", line 19, in main
    response.headers.set("Access-Control-Allow-Origin", origin)
  File "/home/pshaughn/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 333, in set
    value = _maybe_encode(value)
  File "/home/pshaughn/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 317, in _maybe_encode
    raise TypeError("Unexpected value in ResponseHeaders: %r" % s)
TypeError: Unexpected value in ResponseHeaders: None

**Comment by jdm** [comment]
It [appears](https://github.com/servo/servo/blob/e8d677ad264876838d297bd6843d0b02cc488dd9/tests/wpt/web-platform-tests/cors/resources/cors-makeheader.py#L4) that either the request does not include an Origin header, or there is an "origin" query parameter that is being converted to None somehow.

**Comment by CYBAI** [comment]
I got the failure while trying to make module script to recognize `crossOrigin` and I also can't get the `/html/semantics/scripting-1/the-script-element/module/credentials.sub.html` PASS. I suspect it's same issue 🤔

```
 0:11.04 WARNING Unexpected value in ResponseHeaders: None
Traceback (most recent call last):
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/server.py", line 273, in finish_handling
    handler(request, response)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 276, in __call__
    self._set_path_and_load_file(request, response, func)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 259, in _set_path_and_load_file
    return func(request, response, environ, path)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 271, in func
    handler(request, response)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 329, in __call__
    response.headers.update(headers)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 388, in update
    self.append(name, value)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 344, in append
    value = _maybe_encode(value)
  File "/Users/cybai/codespace/mozilla/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/response.py", line 317, in _maybe_encode
    raise TypeError("Unexpected value in ResponseHeaders: %r" % s)
TypeError: Unexpected value in ResponseHeaders: None
```

**Comment by jdm** [comment]
I suspect this is related to the differences I enumerate in #24907, particularly the response tainting vs. the algorithm cors flag.
