### ISSUE TITLE
reftests in servodriver product are busted

### ISSUE THREAD

**Issue by jdm** [servo/servo#25501]
```
+ ./mach test-wpt --release --product=servodriver --headless tests/wpt/mozilla/tests/mozilla/DOMParser.html tests/wpt/mozilla/tests/css/per_glyph_font_fallback_a.html tests/wpt/mozilla/tests/css/img_simple.html tests/wpt/mozilla/tests/mozilla/secure.https.html
+ cat
Running 4 tests in web-platform-tests
Traceback (most recent call last):
  File "/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 161, in start_runner
    executor = executor_cls(browser, **executor_kwargs)
  File "/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservodriver.py", line 238, in __init__
    with open(os.path.join(here, "reftest-wait_webdriver.js")) as f:
IOError: [Errno 2] No such file or directory: '/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/reftest-wait_webdriver.js'
Unsupported test type wdspec for product servodriver
  [1/4] /_mozilla/mozilla/DOMParser.html
  [2/4] /_mozilla/mozilla/secure.https.html
Unsupported test type crashtest for product servodriver
```

**Comment by mrobinson** [comment]
I don't think this is an issue any longer as we've been using WebDriver for a while now.
