### ISSUE TITLE
Intermittent "OSError: [Errno 12] Cannot allocate memory" during linux WPT tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#25530]
```
  ▶ ERROR [expected OK] /css/css-fonts/parsing/font-weight-valid.html
  │   → Traceback (most recent call last):
  │   →   File "/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 256, in run_test
  │   →     result = self.do_test(test)
  │   →   File "/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test
  │   →     self.proc.run()
  │   →   File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozprocess/processhandler.py", line 785, in run
  │   →     self.proc = self.Process([self.cmd] + self.args, **args)
  │   →   File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozprocess/processhandler.py", line 123, in __init__
  │   →     universal_newlines, startupinfo, creationflags)
  │   →   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
  │   →     errread, errwrite)
  │   →   File "/usr/lib/python2.7/subprocess.py", line 938, in _execute_child
  │   →     self.pid = os.fork()
  └   → OSError: [Errno 12] Cannot allocate memory
  ▶ ERROR [expected OK] /referrer-policy/gen/top.meta/strict-origin-when-cross-origin/fetch/same-http.keep-origin.http.html
  │   → Traceback (most recent call last):
  │   →   File "/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 256, in run_test
  │   →     result = self.do_test(test)
  │   →   File "/repo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test
  │   →     self.proc.run()
  │   →   File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozprocess/processhandler.py", line 785, in run
  │   →     self.proc = self.Process([self.cmd] + self.args, **args)
  │   →   File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozprocess/processhandler.py", line 123, in __init__
  │   →     universal_newlines, startupinfo, creationflags)
  │   →   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
  │   →     errread, errwrite)
  │   →   File "/usr/lib/python2.7/subprocess.py", line 938, in _execute_child
  │   →     self.pid = os.fork()
  └   → OSError: [Errno 12] Cannot allocate memory
```

The answer here may be to run fewer processes on linux.

**Comment by SimonSapin** [comment]
If we’re actually running out of available RAM (as opposed to this error being a symptom of some other issue), another option is to change the machine type in https://github.com/mozilla/community-tc-config/blob/7aa0cac71031313b9cd6549b968d4c74ff4b1322/config/projects.yml#L394-L412
