### ISSUE TITLE
Installing pip upgrade on CI fails since 20.0 release

### ISSUE THREAD

**Issue by jdm** [servo/servo#25567]
```
"/repo/python/_virtualenv2.7/bin/python2.7" "-m" "pip" "install" "-I" "-U" "pip" failed with error code 1:
Output:
Error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/repo/python/_virtualenv2.7/local/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/repo/python/_virtualenv2.7/local/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/repo/python/_virtualenv2.7/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/repo/python/_virtualenv2.7/local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "/repo/python/_virtualenv2.7/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 16, in <module>
    from pip._internal.distributions import (
  File "/repo/python/_virtualenv2.7/local/lib/python2.7/site-packages/pip/_internal/distributions/__init__.py", line 1, in <module>
    from pip._internal.distributions.source import SourceDistribution
ImportError: cannot import name SourceDistribution
```

https://github.com/pypa/pip/issues/7217 seems to have many people experiencing the same issue before this point.

**Comment by Flid** [comment]
Our (completely unrelated) project has just started failing with the same symptoms on python 3.5, 3.6 and 3.7. Looks like `pip` guys have broken something.

**Comment by jdm** [comment]
I'm going to try following https://github.com/pypa/pip/issues/7217#issuecomment-562456833 and installing a specific known working version.

**Comment by Flid** [comment]
https://github.com/pypa/pip/issues/7620 - that's the right issue to track I guess

**Comment by jdm** [comment]
20.0.1 was released with a fix and CI jobs are no longer failing immediately.
