### ISSUE TITLE
grouping_formatter doesn't understand PRECONDITION_FAILED

### ISSUE THREAD

**Issue by jdm** [servo/servo#25756]
https://hg.mozilla.org/mozilla-central/rev/165dd3fa6c49c7c45770b07e979a92d583d50407 added some new error handling to the mozlog formatters, but our custom formatter (https://github.com/servo/servo/blob/master/tests/wpt/grouping_formatter.py) needs to be updated as well. We see errors like this on CI:
```
mozlog.structuredlog: Failure calling log handler:
Traceback (most recent call last):
  File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozlog/structuredlog.py", line 274, in _handle_log
    handler(data)
  File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozlog/handlers/base.py", line 74, in __call__
    formatted = self.formatter(data)
  File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozlog/handlers/base.py", line 42, in __call__
    return self.inner(item)
  File "/repo/python/_virtualenv2.7/lib/python2.7/site-packages/mozlog/reader.py", line 74, in __call__
    return handler(data)
  File "/repo/tests/wpt/grouping_formatter.py", line 205, in test_end
    self.expected[test_status] += 1
KeyError: 'PRECONDITION_FAILED'
```

I suspect it's triggered by domparsing/DOMParser-parseFromString-encoding.html but I haven't been able to reproduce it locally.

**Comment by SimonSapin** [comment]
It should be straightforward to port changes from https://hg.mozilla.org/mozilla-central/rev/165dd3fa6c49c7c45770b07e979a92d583d50407 into https://github.com/servo/servo/blob/master/tests/wpt/grouping_formatter.py ?
