### ISSUE TITLE
./mach bootstrap doesn't work on Pop!_OS (Ubuntu)

### ISSUE THREAD

**Issue by humancalico** [servo/servo#25965]
```
Traceback (most recent call last):
  File "./mach", line 103, in <module>
    main(sys.argv)
  File "./mach", line 31, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/humancalico/oss/servo/python/mach_bootstrap.py", line 254, in bootstrap_command_only
    bootstrap(context, force)
  File "/home/humancalico/oss/servo/python/servo/bootstrap.py", line 401, in bootstrap
    distrib, version = get_linux_distribution()
  File "/home/humancalico/oss/servo/python/servo/bootstrap.py", line 389, in get_linux_distribution
    raise Exception('mach bootstrap does not support %s, please file a bug' % distrib)
Exception: mach bootstrap does not support Pop!_OS, please file a bug
```

**Comment by humancalico** [comment]
Also I have run the command ```sudo apt install git curl autoconf libx11-dev libfreetype6-dev libgl1-mesa-dri \
    libglib2.0-dev xorg-dev gperf g++ build-essential cmake libssl-dev \
    libbz2-dev liblzma-dev libosmesa6-dev libxmu6 libxmu-dev libglu1-mesa-dev \
    libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libharfbuzz-dev ccache \
    clang libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev autoconf2.13 llvm-dev``` and then I ran `./mach bootstrap-gstreamer` to set GStreamer up and it reported:
```
Error running mach:

    ['bootstrap-gstreamer']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

Exception: mach bootstrap does not support Pop!_OS, please file a bug

  File "/home/humancalico/oss/servo/python/servo/bootstrap_commands.py", line 65, in bootstrap_gstreamer
    return bootstrap.bootstrap(self.context, force=force, specific="gstreamer")
  File "/home/humancalico/oss/servo/python/servo/bootstrap.py", line 401, in bootstrap
    distrib, version = get_linux_distribution()
  File "/home/humancalico/oss/servo/python/servo/bootstrap.py", line 389, in get_linux_distribution
    raise Exception('mach bootstrap does not support %s, please file a bug' % distrib)
```

**Comment by jdm** [comment]
To support Pop! OS you will need to add extra handling to https://github.com/servo/servo/blob/master/python/servo/bootstrap.py#L349-L364 like we do for Linux mint, which is also based on ubuntu.

**Comment by humancalico** [comment]
@jdm Should I sent a PR for this?

**Comment by jdm** [comment]
Sure!

**Comment by nebrelbug** [comment]
Whoa I was just about to open up an issue for this! Good to know it's being worked on. @humancalico if you can't get to it let me know :)

**Comment by humancalico** [comment]
Thanks @nebrelbug , I have already written the patch. But I'm having problem testing it since I have already done a manual build. So I'm setting up a VM right now. It would be great to know if there was a better way to test it.
