### ISSUE TITLE
Intermittent panic in http_loader::test_origin_set

### ISSUE THREAD

**Issue by jdm** [servo/servo#26895]
```
  10: std::panicking::rust_panic_with_hook
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8\/src\libstd\panicking.rs:477
  11: std::panicking::begin_panic_handler
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8\/src\libstd\panicking.rs:385
  12: core::panicking::panic_fmt
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8\/src\libcore\panicking.rs:89
  13: core::panicking::panic
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8\/src\libcore\panicking.rs:52
  14: core::option::Option<alloc::boxed::Box<net_traits::response::Response>>::unwrap<alloc::boxed::Box<net_traits::response::Response>>
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8\src\libcore\macros\mod.rs:10
  15: main::http_loader::test_origin_set
             at .\tests\http_loader.rs:1437
  16: main::http_loader::test_origin_set::{{closure}}
             at .\tests\http_loader.rs:1375
```

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/37394a892c79d6edbef868d6451710648669cc1c/components/net/tests/http_loader.rs#L1438-L1444 is failing. A more recent rust compiler might be able to provide a more specific failing unwrap call, since https://github.com/rust-lang/rust/pull/73182 merged recently.

**Comment by gterzian** [comment]
So it looks like the response is none:

```

  13: core::panicking::panic
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8\/src\libcore\panicking.rs:52
  14: core::option::Option<alloc::boxed::Box<net_traits::response::Response>>::unwrap<alloc::boxed::Box<net_traits::response::Response>>
```
https://community-tc.services.mozilla.com/tasks/ennyDdgxQ_2ovzskg4Nzvg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FennyDdgxQ_2ovzskg4Nzvg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log#L2587

**Comment by jdm** [comment]
```
thread 'http_loader::test_origin_set' panicked at 'Expected internal response, got Response { response_type: Error(Internal("executor failed to spawn task: custom executor failed")), termination_reason: None, url: None, url_list: [], status: None, raw_status: None, headers: {}, body: Mutex { data: Empty }, cache_state: None, https_state: None, referrer: None, referrer_policy: None, cors_exposed_header_name_list: [], location_url: None, internal_response: None, return_internal: true, aborted: false, resource_timing: Mutex { data: ResourceFetchTiming { domain_lookup_start: 0, timing_check_passed: true, timing_type: Error, redirect_count: 0, request_start: 0, secure_connection_start: 0, response_start: 0, fetch_start: 0, response_end: 0, redirect_start: 0, redirect_end: 0, connect_start: 0, connect_end: 0, start_time: 0 } } }', components\net\tests\http_loader.rs:1443:13
```
Wow, honestly not what I was expecting to see at all.

**Comment by jdm** [comment]
That error looks like it comes from https://github.com/hyperium/hyper/blob/a115c30f1c869a0027dc73157f11adf66b113dbb/src/common/exec.rs#L74-L79.
