### ISSUE TITLE
task 'LayoutWorker' failed at 'assertion failed: glyph_count <= char_max'

### ISSUE THREAD

**Issue by nical** [servo/servo#2704]
On Fedora 64 bits.
Test case: open http://www.wikipedia.org

Backtrace:
```
#0  0x0000000000b6df70 in rust_fail ()
#1  0x0000000000b6df43 in rt::unwind::Unwinder::begin_unwind::h6f64311f41adb19deny::v0.11.0.pre ()
#2  0x0000000000b48818 in rt::unwind::begin_unwind_inner::he197f021c5dbab5dvuy::v0.11.0.pre ()
#3  0x0000000000b46c11 in rt::unwind::begin_unwind_fmt::h9dc0698dc49220aaFty::v0.11.0.pre ()
#4  0x000000000062a4b6 in run_fmt (fmt=0x1) at <std macros>:22
#5  save_glyph_results (self=<optimized out>, text=..., glyphs=<optimized out>, buffer=<optimized out>) at <std macros>:24
#6  gfx::text::shaping::harfbuzz::Shaper.ShaperMethods::shape_text (self=<optimized out>, glyphs=<optimized out>, text=...)
    at /home/nical/dev/mozilla/servo/src/components/gfx/text/shaping/harfbuzz.rs:216
#7  0x0000000000626790 in gfx::font::Font::shape_text (self=0x7fffcd05f380, is_whitespace=<optimized out>, text=...) at /home/nical/dev/mozilla/servo/src/components/gfx/font.rs:423
#8  0x0000000000646bdc in gfx::text::text_run::TextRun::break_and_shape (font=0x7fffcd05f380, text=...) at /home/nical/dev/mozilla/servo/src/components/gfx/text/text_run.rs:172
#9  0x00000000006246cb in gfx::text::text_run::TextRun::new (font=0x7fffcd05f380, text=..., decoration=...) at /home/nical/dev/mozilla/servo/src/components/gfx/text/text_run.rs:121
#10 0x000000000058f734 in servo::layout::text::TextRunScanner::flush_clump_to_list (self=0x7fffe18e9dc0, font_context=<optimized out>, out_fragments=0x7fffe18e7090, 
    last_whitespace=<optimized out>, in_fragments=...) at /home/nical/dev/mozilla/servo/src/components/main/layout/text.rs:220
#11 0x0000000000515122 in servo::layout::text::TextRunScanner::scan_for_runs (self=0x7fffe18e9dc0, font_context=0x7fffcd06e180, flow=...)
    at /home/nical/dev/mozilla/servo/src/components/main/layout/text.rs:69
#12 0x000000000051d78e in flush_inline_fragments_to_flow_or_list (flow_list=<optimized out>, whitespace_stripping=StripWhitespaceFromEnd, node=<optimized out>, self=<optimized out>, 
    fragment_accumulator=..., flow=<optimized out>) at /home/nical/dev/mozilla/servo/src/components/main/layout/construct.rs:300
#13 servo::layout::construct::FlowConstructor<'a>::build_flow_using_children (self=0x7fffe18f37e0, flow=..., node=0x7fffe18f37d0)
    at /home/nical/dev/mozilla/servo/src/components/main/layout/construct.rs:452
#14 0x0000000000520e82 in servo::layout::construct::FlowConstructor<'a>::build_flow_for_block (self=0x7fffe18f37e0, node=0x7fffe18f37d0)
    at /home/nical/dev/mozilla/servo/src/components/main/layout/construct.rs:486
#15 0x0000000000581fdd in process (self=<optimized out>, node=<optimized out>) at /home/nical/dev/mozilla/servo/src/components/main/layout/construct.rs:967
#16 servo::layout::parallel::construct_flows (proxy=0x7fffe18fc198, unsafe_layout_node=...) at /home/nical/dev/mozilla/servo/src/components/main/layout/parallel.rs:317
#17 0x000000000057e331 in servo::layout::parallel::recalc_style_for_node (proxy=0x7fffe18fc198, unsafe_layout_node=...) at /home/nical/dev/mozilla/servo/src/components/main/layout/parallel.rs:300
#18 0x000000000055cf63 in workqueue::WorkQueue$LT$QueueData$C$$x20WorkData$GT$::new::closure.30282 ()
#19 0x0000000000aa8ba8 in task::spawn_opts::closure.7819 ()
#20 0x0000000000b694b3 in rt::task::Task::run::closure.25268 ()
#21 0x0000000000b7782c in rust_try ()
#22 0x0000000000b6941f in rt::task::Task::run::h1b1fa7602039b7638iw::v0.11.0.pre ()
#23 0x0000000000aa8a10 in task::spawn_opts::closure.7792 ()
#24 0x0000000000b6d144 in rt::thread::thread_start::hc6dec59479bd4c22G2w::v0.11.0.pre ()
#25 0x00007ffff7bc7f33 in start_thread () from /lib64/libp
```

**Comment by mbrubeck** [comment]
This should be fixed by #10895 or earlier work.
