### ISSUE TITLE
task failure in compositor.rs when borwsing timecube.com

### ISSUE THREAD

**Issue by nical** [servo/servo#2706]
Assertion: 
```
task '<main>' failed at 'assertion failed: layer.set_clipping_rect(pipeline_id, layer_id, new_rect)', /home/nical/dev/mozilla/servo/src/components/main/compositing/compositor.rs:469
```

Backtrace:
```
#0  0x0000000000b6df70 in rust_fail ()
#1  0x0000000000b6df43 in rt::unwind::Unwinder::begin_unwind::h6f64311f41adb19deny::v0.11.0.pre ()
#2  0x0000000000b48818 in rt::unwind::begin_unwind_inner::he197f021c5dbab5dvuy::v0.11.0.pre ()
#3  0x0000000000b46c11 in rt::unwind::begin_unwind_fmt::h9dc0698dc49220aaFty::v0.11.0.pre ()
#4  0x0000000000468225 in servo::compositing::compositor::IOCompositor::run (self=<optimized out>) at /home/nical/dev/mozilla/servo/src/components/main/compositing/compositor.rs:799
#5  0x0000000000484c42 in create (app=<optimized out>, port=..., constellation_chan=..., profiler_chan=..., opts=..., port=..., constellation_chan=..., profiler_chan=...)
    at /home/nical/dev/mozilla/servo/src/components/main/compositing/compositor.rs:180
#6  servo::compositing::CompositorTask::create (port=..., constellation_chan=..., profiler_chan=..., opts=...)
    at /home/nical/dev/mozilla/servo/src/components/main/compositing/compositor_task.rs:233
#7  0x000000000059529e in spawn_main (compositor_port=..., profiler_chan=..., opts=..., compositor_port=..., profiler_chan=..., result_port=..., p=<optimized out>)
    at /home/nical/dev/mozilla/servo/src/components/main/servo.rs:169
#8  servo::run (opts=...) at /home/nical/dev/mozilla/servo/src/components/main/servo.rs:197
#9  0x00000000005944b7 in fn32484 () at /home/nical/dev/mozilla/servo/src/components/main/servo.rs:126
#10 0x0000000000aa91c3 in start::closure.7872 ()
#11 0x0000000000b694b3 in rt::task::Task::run::closure.25268 ()
#12 0x0000000000b7782c in rust_try ()
#13 0x0000000000b6941f in rt::task::Task::run::h1b1fa7602039b7638iw::v0.11.0.pre ()
#14 0x0000000000aa8fdb in start::h2d44e22b2cfb6771qqe::v0.11.0.pre ()
#15 0x0000000000594279 in main () at /home/nical/dev/mozilla/servo/src/components/main/servo.rs:125
```

**Comment by mbrubeck** [comment]
This should be fixed by #2819 or related work.
