### ISSUE TITLE
Build error from Script v1.0.0 and mozjs_sys v0.68.2

### ISSUE THREAD

**Issue by uniformbuffer** [servo/servo#27669]
Hi,
i'm trying to build Servo on linux aarch64 gnu locally (so same target) and while compiling i got some errors.  I'm currently on Armbian Buster with Debian Sid repository upgrade.
I'm compiling current master branch and i use Python 3.8.6rc1.
Initially i got:
```
error: failed to run custom build command for `script v0.0.1 (/home/****/servo/components/script)`

Caused by:
  process didn't exit successfully: `/home/****/servo/target/release/build/script-8eecfecfb26fbe7e/build-script-build` (exit code: 1)
  --- stderr
  Traceback (most recent call last):
    File "dom/bindings/codegen/run.py", line 119, in <module>
      main()
    File "dom/bindings/codegen/run.py", line 28, in main
      parser.parse(f.read(), filename)
    File "./parser/WebIDL.py", line 7562, in parse
      self._productions.extend(self.parser.parse(lexer=self.lexer, tracking=True))
    File "./ply/ply/yacc.py", line 263, in parse
      return self.parseopt(input,lexer,debug,tracking,tokenfunc)
    File "./ply/ply/yacc.py", line 649, in parseopt
      lookahead = get_token()     # Get the next token
    File "./ply/ply/lex.py", line 313, in token
      if lexdata[lexpos] in lexignore:
  TypeError: 'in <string>' requires string as left operand, not int

```
Seems that at some point lexdata[lexpos] is not a string, but an int.

I have tried to enforce string type at "/home/****/servo/components/script/dom/bindings/codegen/ply/ply/lex.py" at line 248:
```
    # ------------------------------------------------------------
    # input() - Push a new string into the lexer
    # ------------------------------------------------------------
    def input(self,s):
        # Pull off the first character to see if s looks like a string
        c = s[:1]
        if not isinstance(c,StringTypes):
            raise ValueError("Expected a string")
        s2 = str() //<---added here
        self.lexdata = s2 //<---changed here
        self.lexpos = 0
        self.lexlen = len(s2)  //<---changed here
```

This seems to fix this error, but after that i got:
```
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs?rev=a40b829f0fefa06a743f006260c7facebcfa27aa#a40b829f)`

Caused by:
  process didn't exit successfully: `/home/****/servo/target/release/build/mozjs_sys-e7f30a17a09e02f3/build-script-build` (exit code: 101)
  --- stdout
  cargo:outdir=/home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build
  [[ '/home//****//.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -ot '/home//****//.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in ]] && touch '/home//****//.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  [[ '/home//****//.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure -ot '/home//****//.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  ! [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  ! [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  if [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -nt config.status ]] ; then \
    PYTHON="python2" MOZ_TOOLS="" \
    CC="clang" CFLAGS="" \
    CPP="gcc -E" CPPFLAGS="-I/home/****/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
    CXX="clang++" CXXFLAGS="" \
    AS="" AR="ar" \
    STLPORT_LIBS="" \
    '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake || (cat config.log && exit 1) ; \
  fi

  --- stderr
  gmake: *** Nessun obiettivo specificato e nessun makefile trovato.  Arresto.
  /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Iterable
  Traceback (most recent call last):
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py", line 170, in <module>
      sys.exit(main(sys.argv))
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py", line 46, in main
      sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 446, in run
      self.include_file(path)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
      exec_(code, self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
      exec(object, globals, locals)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/moz.configure", line 7, in <module>
      include('build/moz.configure/init.configure')
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 769, in include_impl
      self.include_file(what)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
      exec_(code, self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
      exec(object, globals, locals)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/init.configure", line 24, in <module>
      def check_build_environment(help, dist):
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 752, in decorator
      depends = DependsFunction(self, func, dependencies, when=when)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 129, in __init__
      sandbox._value_for(self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 543, in _value_for
      return self._value_for_depends(obj)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
      cache[args] = self.func(instance, *args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 552, in _value_for_depends
      value = obj.result()
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
      cache[args] = self.func(instance, *args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 155, in result
      return self._func(*resolved_args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1152, in wrapped
      return new_func(*args, **kwargs)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/init.configure", line 73, in check_build_environment
      if '\r' in data:
  TypeError: a bytes-like object is required, not 'str'
  cat: config.log: File o directory non esistente
  gmake: *** [/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/makefile.cargo:194: maybe-configure] Errore 1
  thread 'main' panicked at 'assertion failed: result.success()', /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/build.rs:177:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

This seems to be related to the previous error.
Seems like somethins is passed to functions that expect strings and cause multiple python functions to fail.

Can someone help me to figure out what is the cause?

Thanks for the attention,
Have a good day

**Comment by jdm** [comment]
It looks like you're building with python3 only, but we require python2 to be available as well. You should be able to work around that by setting the PYTHON2 environment variable to point to an appropriate python2 binary.

**Comment by uniformbuffer** [comment]
Yes, since i have no more programs that rely on python2 i had removed it from the system. I had a lot of problems to install python dependencies because mach has been setted to ignore system-installed packages: simply pip packages not reliable on architecture different from x86. Basically every pip package that have a binary component ships with an x86 precompiled binary. If the architecture is different, it try to compile it on the machine, but, from experience, at least 50% of that are not able to build locally (at least on aarch64), making impossible to install other packages that rely on it. This became a big problem with projects that use a lot of pip packages. To manage this problem i had to modify the mach script removing the "-I" on the bootstrap command (at "servo/python/mach_bootstrap.py" line 213), making possible to use system-installed pip packages. Pip packages shipped with linux distro are MUCH MUCH more reliable then installing from pip. I don't know if this could lead some problems for dependencies, but at least make the bootstrap procedure work.

Anyway, after installing python2 dependencies i got a different error:
```
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs?rev=a40b829f0fefa06a743f006260c7facebcfa27aa#a40b829f)`

Caused by:
  process didn't exit successfully: `/home/****/servo/target/release/build/mozjs_sys-e7f30a17a09e02f3/build-script-build` (exit code: 101)
  --- stdout
  cargo:outdir=/home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build
  [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  ! [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  ! [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  if [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -nt config.status ]] ; then \
    PYTHON="python3" MOZ_TOOLS="" \
    CC="clang" CFLAGS="" \
    CPP="gcc -E" CPPFLAGS="-I/home/****/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
    CXX="clang++" CXXFLAGS="" \
    AS="" AR="ar" \
    STLPORT_LIBS="" \
    '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake || (cat config.log && exit 1) ; \
  fi
  Creating Python environment
  Using base prefix '/usr'
  New python executable in /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python3
  Also creating executable in /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python
  Installing setuptools, pip, wheel...done.
  /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/third_party/python/virtualenv/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  RuntimeError: Bad magic number in .pyc file
  INFO: Creating Python environment
  INFO: Using base prefix '/usr'
  INFO: New python executable in /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python3
  INFO: Also creating executable in /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python
  INFO: Installing setuptools, pip, wheel...done.
  INFO: /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/third_party/python/virtualenv/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  INFO:   import imp
  INFO: RuntimeError: Bad magic number in .pyc file

  --- stderr
  gmake: *** Nessun obiettivo specificato e nessun makefile trovato.  Arresto.
  Traceback (most recent call last):
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py", line 170, in <module>
      sys.exit(main(sys.argv))
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py", line 46, in main
      sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 446, in run
      self.include_file(path)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
      exec_(code, self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
      exec(object, globals, locals)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/moz.configure", line 7, in <module>
      include('build/moz.configure/init.configure')
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 769, in include_impl
      self.include_file(what)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
      exec_(code, self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
      exec(object, globals, locals)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/init.configure", line 212, in <module>
      @imports('distutils.sysconfig')
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 752, in decorator
      depends = DependsFunction(self, func, dependencies, when=when)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 129, in __init__
      sandbox._value_for(self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 543, in _value_for
      return self._value_for_depends(obj)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
      cache[args] = self.func(instance, *args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 552, in _value_for_depends
      value = obj.result()
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
      cache[args] = self.func(instance, *args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 155, in result
      return self._func(*resolved_args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1152, in wrapped
      return new_func(*args, **kwargs)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/init.configure", line 261, in virtualenv_python
      manager.build(python)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 488, in build
      raise Exception('Error populating virtualenv.')
  Exception: Error populating virtualenv.
  gmake: *** [/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/makefile.cargo:194: maybe-configure] Errore 1
  thread 'main' panicked at 'assertion failed: result.success()', /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/build.rs:177:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

I got "Exception: Error populating virtualenv." that i honestly don't know how to fix. Seems like mozjs create another venv on which it install some python packages. I think that is the same problems as before: probably it use the -I flag to ignore system-dependencies and trigger some compile error from them.

Anyway thanks a lot for the very fast answer and the dedicated time.,
Have a good day

**Comment by uniformbuffer** [comment]
Hi, executing build command a second time leads to a different error:
```
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs?rev=a40b829f0fefa06a743f006260c7facebcfa27aa#a40b829f)`

Caused by:
  process didn't exit successfully: `/home/****/servo/target/release/build/mozjs_sys-e7f30a17a09e02f3/build-script-build` (exit code: 101)
  --- stdout
  cargo:outdir=/home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build
  [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  ! [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  ! [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in -ot '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure ]] && touch '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  if [[ '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -nt config.status ]] ; then \
    PYTHON="python3" MOZ_TOOLS="" \
    CC="clang" CFLAGS="" \
    CPP="gcc -E" CPPFLAGS="-I/home/****/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
    CXX="clang++" CXXFLAGS="" \
    AS="" AR="ar" \
    STLPORT_LIBS="" \
    '/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake || (cat config.log && exit 1) ; \
  fi
  Creating Python environment
  Using base prefix '/usr'
  New python executable in /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python3
  Not overwriting existing python script /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python (you must use /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python3)
  Installing setuptools, pip, wheel...done.
  /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/third_party/python/virtualenv/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  b'running build_ext\ncopying build/lib.linux-aarch64-3.8/psutil/_psutil_linux.cpython-38-aarch64-linux-gnu.so -> psutil\ncopying build/lib.linux-aarch64-3.8/psutil/_psutil_posix.cpython-38-aarch64-linux-gnu.so -> psutil\n'
  Error processing command. Ignoring because optional. (optional:packages.txt:comm/build/virtualenv_packages.txt)
  Reexecuting in the virtualenv
  INFO: Creating Python environment
  INFO: Using base prefix '/usr'
  INFO: New python executable in /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python3
  INFO: Not overwriting existing python script /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python (you must use /home/****/servo/target/release/build/mozjs_sys-c85a09a6828410b9/out/build/_virtualenvs/init/bin/python3)
  INFO: Installing setuptools, pip, wheel...done.
  INFO: /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/third_party/python/virtualenv/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  INFO:   import imp
  INFO: b'running build_ext\ncopying build/lib.linux-aarch64-3.8/psutil/_psutil_linux.cpython-38-aarch64-linux-gnu.so -> psutil\ncopying build/lib.linux-aarch64-3.8/psutil/_psutil_posix.cpython-38-aarch64-linux-gnu.so -> psutil\n'
  INFO: Error processing command. Ignoring because optional. (optional:packages.txt:comm/build/virtualenv_packages.txt)
  INFO: Reexecuting in the virtualenv

  --- stderr
  gmake: *** Nessun obiettivo specificato e nessun makefile trovato.  Arresto.
  Traceback (most recent call last):
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py", line 170, in <module>
      sys.exit(main(sys.argv))
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/../../configure.py", line 46, in main
      sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 446, in run
      self.include_file(path)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
      exec_(code, self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
      exec(object, globals, locals)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/moz.configure", line 7, in <module>
      include('build/moz.configure/init.configure')
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 769, in include_impl
      self.include_file(what)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
      exec_(code, self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
      exec(object, globals, locals)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/init.configure", line 24, in <module>
      def check_build_environment(help, dist):
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 752, in decorator
      depends = DependsFunction(self, func, dependencies, when=when)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 129, in __init__
      sandbox._value_for(self)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 543, in _value_for
      return self._value_for_depends(obj)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
      cache[args] = self.func(instance, *args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 552, in _value_for_depends
      value = obj.result()
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
      cache[args] = self.func(instance, *args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 155, in result
      return self._func(*resolved_args)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1152, in wrapped
      return new_func(*args, **kwargs)
    File "/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/init.configure", line 73, in check_build_environment
      if '\r' in data:
  TypeError: a bytes-like object is required, not 'str'
  gmake: *** [/home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/makefile.cargo:194: maybe-configure] Errore 1
  thread 'main' panicked at 'assertion failed: result.success()', /home/****/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/build.rs:177:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by uniformbuffer** [comment]
I think i have solved the issue, but i'm still (very slowly) compiling. I have forced the script to use only python2 using "PYTHON=python2","PYTHON2=python2" and "alias python=python2". I will update in case of other errors.

Anyway thanks a lot for the help!

**Comment by uniformbuffer** [comment]
Well, seems that the trick work, but i cannot go beyond "script" compilation. Script require so much memory to compile that trigger the oom killer (on my machine i currently have 2GB of memory+ 1GB swap). I cannot go past since i don't have a more memory capable machine to use. Maybe in a future, when the project became more stable, someone could maintain precompiled binary for aarch64, like deb package or similar. 
Anyway thanks a lot for the help,
Good luck and have fun with rust (i love rust :smile: )

**Comment by okias** [comment]
@uniformbuffer  Hello, since recently Python2 support got dropped, do you still have this problem on aarch64? I just tried compilation on aarch64 (flatpak, qemu) and it failed at same step (Python3 only)

**Comment by jdm** [comment]
I'm going to proactively close this since it's a python2 problem.
