### ISSUE TITLE
Unexpected crash in test-wpt /_webgl/conformance/context/context-release-with-workers.html

### ISSUE THREAD

**Issue by jonathanKingston** [servo/servo#27819]
Running: `./mach test-wpt /_webgl/conformance/context/context-release-with-workers.html --debugger`

```
#0  __GI___pthread_mutex_lock (mutex=0x3b3b3b3b3b3b8803) at ../nptl/pthread_mutex_lock.c:67
#1  0x00005555594dbdb6 in mozilla::detail::MutexImpl::mutexLock() (this=0x3b3b3b3b3b3b8803) at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/mozglue/misc/Mutex_posix.cpp:125
#2  mozilla::detail::MutexImpl::lock() (this=0x3b3b3b3b3b3b8803) at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/mozglue/misc/Mutex_posix.cpp:149
#3  0x00005555594b86fe in js::Mutex::lock() (this=0x3b3b3b3b3b3b8803) at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/threading/Mutex.h:72
#4  js::ExclusiveData<mozilla::Vector<js::wasm::Instance*, 0ul, js::SystemAllocPolicy> >::acquire() const (this=0x3b3b3b3b3b3b8803)
    at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/threading/ExclusiveData.h:92
#5  js::ExclusiveData<mozilla::Vector<js::wasm::Instance*, 0ul, js::SystemAllocPolicy> >::Guard::Guard(js::ExclusiveData<mozilla::Vector<js::wasm::Instance*, 0ul, js::SystemAllocPolicy> > const&)
    (this=<optimised out>, parent=...) at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/threading/ExclusiveData.h:138
#6  js::ExclusiveData<mozilla::Vector<js::wasm::Instance*, 0ul, js::SystemAllocPolicy> >::lock() const (this=0x3b3b3b3b3b3b8803)
    at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/threading/ExclusiveData.h:175
#7  js::wasm::InterruptRunningCode(JSContext*) (cx=<optimised out>) at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/wasm/WasmRealm.cpp:131
#8  0x00005555584d3c8e in script::script_runtime::ContextForRequestInterrupt::request_interrupt (self=0x7fff47fe9c68) at components/script/script_runtime.rs:868
#9  0x0000555557b31d72 in <script::dom::globalscope::AutoCloseWorker as core::ops::drop::Drop>::drop (self=0x7fff47fe9c30) at components/script/dom/globalscope.rs:158
#10 0x0000555557a76026 in core::ptr::drop_in_place () at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libcore/ptr/mod.rs:184
#11 0x00005555575af9f7 in core::mem::dropPython Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x3b3b3b3b3b3b8803:
 (_x=#12 0x00005555580d250e in script::dom::globalscope::GlobalScope::remove_web_messaging_and_dedicated_workers_infra::{{closure}} (worker=...)
    at components/script/dom/globalscope.rs:940
#13 0x000055555733852a in core::iter::traits::iterator::Iterator::for_each::call::{{closure}} (item=...) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libcore/iter/traits/iterator.rs:646
#14 0x00005555576db4fd in core::iter::traits::iterator::Iterator::fold (self=..., init=(), f=...) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libcore/iter/traits/iterator.rs:2003
#15 0x00005555576dccb3 in core::iter::traits::iterator::Iterator::for_each (self=..., f=...) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libcore/iter/traits/iterator.rs:649
#16 0x0000555557c97615 in script::dom::globalscope::GlobalScope::remove_web_messaging_and_dedicated_workers_infra (self=0x7fffc3e40c00) at components/script/dom/globalscope.rs:937
#17 0x00005555587466cb in script::dom::window::Window::clear_js_runtime (self=0x7fffc3e40c00) at components/script/dom/window.rs:1470
#18 0x0000555557bdebc0 in script::script_thread::ScriptThread::handle_exit_pipeline_msg (self=0x7fff47ff4cc8, id=..., discard_bc=script_traits::DiscardBrowsingContext::No)
    at components/script/script_thread.rs:2958
#19 0x0000555557bccf13 in script::script_thread::ScriptThread::handle_msg_from_constellation (self=0x7fff47ff4cc8, msg=...) at components/script/script_thread.rs:2031
#20 0x0000555557e94b8c in script::script_thread::ScriptThread::handle_msgs::{{closure}} () at components/script/script_thread.rs:1649
#21 0x0000555557e96aa9 in script::script_thread::ScriptThread::profile_event (self=0x7fff47ff4cc8, category=script::script_runtime::ScriptThreadEventCategory::ConstellationMsg, pipeline_id=..., f=...)
    at components/script/script_thread.rs:1893
#22 0x0000555557bc9b34 in script::script_thread::ScriptThread::handle_msgs (self=0x7fff47ff4cc8) at components/script/script_thread.rs:1643
#23 0x0000555557bc6dcd in script::script_thread::ScriptThread::start (self=0x7fff47ff4cc8) at components/script/script_thread.rs:1447
#24 0x0000555557e902aa in <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}} () at components/script/script_thread.rs:834
#25 0x000055555872c27a in profile_traits::mem::ProfilerChan::run_with_memory_reporting (self=0x7fff47ff4ca8, f=..., reporter_name=..., channel_for_reporter=..., msg=0x7fff47ff5710)
    at /home/jonathan/debugging/servo/servo/components/profile_traits/mem.rs:88
#26 0x0000555557e90c49 in <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}} () at components/script/script_thread.rs:832
#27 0x00005555583b2933 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/sys_common/backtrace.rs:130
#28 0x0000555558620714 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/thread/mod.rs:475
#29 0x0000555556e123e6 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=()) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panic.rs:318
#30 0x0000555557608f97 in std::panicking::try::do_call (data=0x7fff47ff6868 "\240}\030\241\377\177") at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:348
#31 0x000055555761c1cd in __rust_try () at /home/jonathan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/js/src/wasm/WasmStubs.cpp:470
#32 0x0000555557608cf4 in std::panicking::try (f=...) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:325
#33 0x0000555556e128c6 in std::panic::catch_unwind (f=...) at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panic.rs:394
#34 0x000055555861f3b5 in std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/thread/mod.rs:474
#35 0x00005555579f49bf in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libcore/ops/function.rs:233
#36 0x000055555d5f937a in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/liballoc/boxed.rs:1074
#37 <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/liballoc/boxed.rs:1074
#38 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:87
#39 0x00007ffff7244609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#40 0x00007ffff6fc2293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by mrobinson** [comment]
I'm not seeing this either on Linux. I guess we can close this for now and reopen if someone encounters it again.
