### ISSUE TITLE
Bootstrap error with Python 3.9

### ISSUE THREAD

**Issue by ghostd** [servo/servo#27849]
Hi,

I upgraded my debian some days ago, and now i can't build servo. It seems the required `setuptools` is not compatible with python 3.9. When i run `python3 ./mach bootstrap` i get this:
```
(skip some lines...)
Installing collected packages: blessings, distro, six, mozfile, mozinfo, mozprocess, mach, mozdebug, mozterm, mozlog, setuptools, toml, pyflakes, mccabe, pycodestyle, flake8, pep8, voluptuous, PyYAML, ply, colorama, python-dateutil, docutils, jmespath, botocore, s3transfer, boto3, certifi, servo-tidy
  Running setup.py develop for servo-tidy
Error:
    ERROR: Command errored out with exit status 1:
     command: /home/xxxx/servo/python/_virtualenv3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxx/servo/python/tidy/setup.py'"'"'; __file__='"'"'/home/xxxx/servo/python/tidy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/xxxx/servo/python/tidy/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxx/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "/home/xxxx/servo/python/_virtualenv3.9/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/home/xxxx/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools.depends import Require
      File "/home/xxxx/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/xxxx/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/xxxx/servo/python/_virtualenv3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxx/servo/python/tidy/setup.py'"'"'; __file__='"'"'/home/xxxx/servo/python/tidy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

According [to the documentation](https://docs.python.org/3/whatsnew/3.9.html): `The unescape() method in the html.parser.HTMLParser class has been removed (it was deprecated since Python 3.4).` And the current version of setuptools has the following code:
```python
unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
```

I tried to change the version of `setuptools` in `python/requirements.txt`, but no success. I didn't find how to re-install a newer version of setuptools.

**Comment by jdm** [comment]
Is there any change if you remove `python/_virtualenv3.9` after changing setuptools version in python/requirements.txt?

**Comment by ghostd** [comment]
Thanks, you're right, i did this 20 minutes ago and it works:
* i changed the setuptools version to 50.3.2
* i changed a file in the setuptools directory
* i re-ran bootstrap.

Now i have an issue with WTP while running a single test:
```
The details of the failure are as follows:

TypeError: Object of type bytes is not JSON serializable

  File "/home/xxxxx/servo/python/servo/testing_commands.py", line 407, in test_wpt
    ret = self.run_test_list_or_dispatch(kwargs["test_list"], "wpt", self._test_wpt, **kwargs)
  File "/home/xxxxx/servo/python/servo/testing_commands.py", line 447, in run_test_list_or_dispatch
    return correct_function(**kwargs)
  File "/home/xxxxx/servo/python/servo/testing_commands.py", line 433, in _test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "/home/xxxxx/servo/python/servo/testing_commands.py", line 485, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "/home/xxxxx/servo/tests/wpt/run.py", line 54, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/home/xxxxx/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 219, in run_tests
    with env.TestEnvironment(test_paths,
  File "/home/xxxxx/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/environment.py", line 82, in __enter__
    self.stash.__enter__()
  File "/home/xxxxx/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/stash.py", line 42, in __enter__
    store_env_config(self.address, self.authkey)
  File "/home/xxxxx/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/stash.py", line 61, in store_env_config
    os.environ["WPT_STASH_CONFIG"] = json.dumps((address, authkey.decode("ascii")))
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

I'm still digging in the issues of WTP to check the problem is known...

**Comment by ghostd** [comment]
I changed the second line of `store_env_config` in `stash.py` to this:
```python
    os.environ["WPT_STASH_CONFIG"] = json.dumps((address.decode("ascii"), authkey.decode("ascii")))
```
Now i can run the tests, but i dont know if it's a bug of WPT itself or a bug a WPT+mach

**Comment by jimreesman** [comment]
I recently encountered the AttributeError: 'HTMLParser' object has no attribute 'unescape' error on my initial attempt to build servo on MacOS. After some research, the .unescape method was apparently removed in Python 3.9. It seems present in 3.5 - 3.8. I use pyenv - switched to Python 3.8.0 and I was able to build successfully.

**Comment by jdm** [comment]
I've submitted #27961 to fix that issue.

**Comment by ghostd** [comment]
My last issue in `stash.py` should be fixed by this [WPT PR](https://github.com/web-platform-tests/wpt/pull/26976)

**Comment by ghostd** [comment]
@jdm i guess i can close this issue now you have merged you pretty PR :)

**Comment by jdm** [comment]
Thanks for all the help!
