### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by ngortheone** [servo/servo#27987]
Maser branch today

```
./mach build --dev   

......

error: failed to run custom build command for `script v0.0.1 (/usr/local/src/github.com/servo/servo/components/script)`

Caused by:
  process didn't exit successfully: `/usr/local/src/github.com/servo/servo/target/debug/build/script-773f8c9677b88710/build-script-build` (exit code: 1)
  --- stderr
  ./parser/WebIDL.py:5481: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
    raise WebIDLError("[CrossOriginCallable] is only allowed on non-static "
  Traceback (most recent call last):
    File "dom/bindings/codegen/run.py", line 119, in <module>
      main()
    File "dom/bindings/codegen/run.py", line 28, in main
      parser.parse(f.read(), filename)
    File "./parser/WebIDL.py", line 7562, in parse
      self._productions.extend(self.parser.parse(lexer=self.lexer, tracking=True))
    File "./ply/ply/yacc.py", line 263, in parse
      return self.parseopt(input,lexer,debug,tracking,tokenfunc)
    File "./ply/ply/yacc.py", line 649, in parseopt
      lookahead = get_token()     # Get the next token
    File "./ply/ply/lex.py", line 313, in token
      if lexdata[lexpos] in lexignore:
  TypeError: 'in <string>' requires string as left operand, not int
warning: build failed, waiting for other jobs to finish...
   Completed glib v0.9.3 in 15.0s
   Completed webxr-api v0.0.1 in 5.9s
   Completed tinyfiledialogs v3.3.9 custom-build (run) in 110.2s
   Completed webrender_api v0.61.0 in 15.1s
   Completed glslopt v0.1.7 custom-build (run) in 167.4s
   Completed mozangle v0.2.7 custom-build (run) in 206.6s
error: build failed
```

**Comment by twilco** [comment]
What OS are you running?  And what version of Python (I'm guessing >3.8 based on [this article](https://adamj.eu/tech/2020/06/21/why-does-python-syntaxwarning-saying-list-indices-must-be-integers-or-slices/))?

FWIW, this line hasn't been udpated in ~2 years: https://github.com/servo/servo/blame/94ad42066ac78fdcc11b14989a3d96a177586d31/components/script/dom/bindings/codegen/parser/WebIDL.py#L5481

**Comment by ngortheone** [comment]
I am on Gentoo, this is python3.8

**Comment by twilco** [comment]
I'm running Manjaro and have both Python 3.8 and 2.7.18 installed and don't have any issues building.  Running `./mach --debug-command build --dev -p servo`, `mach` is using my Python 2.7.18 installation.  Looking at the top of the `mach` shell script, I found this:

```bash
# The beginning of this script is both valid shell and valid python,
# such that the script starts with the shell and is reexecuted with
# the right python.
''':' && if [ ! -z "$MSYSTEM" ] ; then exec python "$0" "$@" ; else which python2.7 > /dev/null 2> /dev/null && exec python2.7 "$0" "$@" || exec python "$0" "$@" ; fi
'''
```

Do you have Python 2 installed?  If not, maybe try that?

**Comment by Darkspirit** [comment]
On Debian Testing I'm always using `python3 ./mach build --dev`. Could that help here?

**Comment by mrobinson** [comment]
I think this shouldn't be an issue any longer now that we are always using Python 3.
