### ISSUE TITLE
Bootstrap error on Ubuntu 20.10

### ISSUE THREAD

**Issue by pwnorbitals** [servo/servo#28045]
```
> ./mach bootstrap

Traceback (most recent call last):
  File "./mach", line 109, in <module>
    main(sys.argv)
  File "./mach", line 31, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/chris/servo/python/mach_bootstrap.py", line 254, in bootstrap_command_only
    bootstrap(context, force)
  File "/home/chris/servo/python/servo/bootstrap.py", line 399, in bootstrap
    distrib, version = get_linux_distribution()
  File "/home/chris/servo/python/servo/bootstrap.py", line 378, in get_linux_distribution
    raise Exception('unsupported version of %s: %s' % (distrib, version))
Exception: unsupported version of Ubuntu: 20.10
```

Happens while following the README. Didn't happen on my other VMs though, weird. Is this a known issue ?

**Comment by ghostd** [comment]
I guess we should update this code:
https://github.com/servo/servo/blob/2efc2e28806c669bd4d9c0a079d44bf196de05a1/python/servo/bootstrap.py#L376-L378

**Comment by jdm** [comment]
Yes, that should fix it.
