### ISSUE TITLE
Mach says that virtualenv is not installed even though it is

### ISSUE THREAD

**Issue by Soveu** [servo/servo#28121]
OS: Fedora 33
```
soveu@localhost ~/f/servo (master)> sudo dnf install python3-virtualenv
Last metadata expiration check: 0:16:03 ago on Sun 31 Jan 2021 11:36:29 AM CET.
Package python3-virtualenv-20.0.30-1.fc33.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
soveu@localhost ~/f/servo (master)> ./mach build --release
Python virtualenv is not installed. Please install it prior to running mach.
soveu@localhost ~/f/servo (master) [1]>
```

**Comment by jdm** [comment]
Trying running `python3 ./mach build --release`?

**Comment by Soveu** [comment]
Similar error to #28120 - `AttributeError: 'HTMLParser' object has no attribute 'unescape'`
```
soveu@localhost ~/f/servo (master)> python3 ./mach build --release
"/home/soveu/foss/servo/python/_virtualenv3.9/bin/python" "-m" "pip" "install" "-I" "-r" "/home/soveu/foss/servo/python/requirements.txt" failed with error code 1:
Output:
Obtaining file:///home/soveu/foss/servo/python/tidy (from -r /home/soveu/foss/servo/python/requirements.txt (line 35))
Error:
    ERROR: Command errored out with exit status 1:
     command: /home/soveu/foss/servo/python/_virtualenv3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/soveu/foss/servo/python/tidy/setup.py'"'"'; __file__='"'"'/home/soveu/foss/servo/python/tidy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n91fvdpr
         cwd: /home/soveu/foss/servo/python/tidy/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 14, in <module>
        from setuptools.dist import Distribution, Feature
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 23, in <module>
        from setuptools.depends import Require
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/py33compat.py", line 54, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
WARNING: Discarding file:///home/soveu/foss/servo/python/tidy. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by andreubotella** [comment]
> Trying running `python3 ./mach build --release`?

For the record, Fedora 33 has the `python` command default to `python3`, but running `./mach` still uses Python 2 (tested by adding `print(sys.version_info)` in the python part of the script). Gecko's mach does the right thing here. It seems like #27999 would solve that, though.


> Similar error to #28120 - `AttributeError: 'HTMLParser' object has no attribute 'unescape'`

Change `python/requirements.txt` to have `setuptools = 50.3.2` (or some other version that supports Python 3.9; see #27961) and then delete the `python/_virtualenv3.9` folder.

**Comment by triscuitcircuit** [comment]
I am having the same issue on the latest stable release of MacOS (11.2). Even with `python3 ./mach build --release` it still says `Python virtualenv is not installed. Please install it prior to running mach.`

```
pip install virtualenv
Requirement already satisfied: virtualenv in /opt/homebrew/lib/python3.9/site-packages (20.4.2)
Requirement already satisfied: filelock<4,>=3.0.0 in /opt/homebrew/lib/python3.9/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: appdirs<2,>=1.4.3 in /opt/homebrew/lib/python3.9/site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: six<2,>=1.9.0 in /opt/homebrew/lib/python3.9/site-packages (from virtualenv) (1.15.0)

**Comment by MichaelMcDonnell** [comment]
I think this will be fixed by #28092 which updates the setuptools dependency (#27999 was closed without merging).

**Comment by MichaelMcDonnell** [comment]
Please re-test. I no longer get this error after #28092 was merged.

**Comment by Soveu** [comment]
Works :ok_hand:

**Comment by CYBAI** [comment]
> Works 👌

Thanks for confirmation! Closing now.
