### ISSUE TITLE
Mach bootstrap does not work on Fedora 33

### ISSUE THREAD

**Issue by Soveu** [servo/servo#28120]
```
soveu@localhost ~/f/servo (master)> python3 ./mach bootstrap
"/home/soveu/foss/servo/python/_virtualenv3.9/bin/python" "-m" "pip" "install" "-I" "-r" "/home/soveu/foss/servo/python/requirements.txt" failed with error code 1:
Output:
Obtaining file:///home/soveu/foss/servo/python/tidy (from -r /home/soveu/foss/servo/python/requirements.txt (line 35))
Collecting blessings==1.6
  Using cached blessings-1.6.tar.gz (19 kB)
Collecting distro==1.4
  Using cached distro-1.4.0-py2.py3-none-any.whl (17 kB)
Collecting mach==1.0.0
  Using cached mach-1.0.0.tar.gz (27 kB)
Collecting mozdebug==0.2
  Using cached mozdebug-0.2.0-py2.py3-none-any.whl (6.0 kB)
Collecting mozinfo==1.1.0
  Using cached mozinfo-1.1.0-py2.py3-none-any.whl (7.0 kB)
Collecting mozlog==5.0
  Using cached mozlog-5.0-py2.py3-none-any.whl (67 kB)
Collecting setuptools==39.0
  Using cached setuptools-39.0.0-py2.py3-none-any.whl (569 kB)
Collecting toml==0.9.2
  Using cached toml-0.9.2.tar.gz (7.6 kB)
Collecting flake8==3.8.3
  Using cached flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting pep8==1.5.7
  Using cached pep8-1.5.7-py2.py3-none-any.whl (37 kB)
Collecting pyflakes==2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting ply==3.8
  Using cached ply-3.8.tar.gz (157 kB)
Collecting colorama==0.3.7
  Using cached colorama-0.3.7-py2.py3-none-any.whl (19 kB)
Collecting boto3==1.4.4
  Using cached boto3-1.4.4-py2.py3-none-any.whl (127 kB)
Collecting certifi
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting six==1.12
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting voluptuous==0.11.5
  Downloading voluptuous-0.11.5-py2.py3-none-any.whl (27 kB)
Collecting PyYAML==5.1
  Downloading PyYAML-5.1.tar.gz (274 kB)
Collecting s3transfer<0.2.0,>=0.1.10
  Using cached s3transfer-0.1.13-py2.py3-none-any.whl (59 kB)
Collecting botocore<1.6.0,>=1.5.0
  Using cached botocore-1.5.95-py2.py3-none-any.whl (3.6 MB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting mozfile
  Using cached mozfile-2.1.0.tar.gz (5.9 kB)
Collecting mozprocess
  Downloading mozprocess-1.2.1-py2.py3-none-any.whl (22 kB)
Collecting mozterm
  Using cached mozterm-1.0.0-py2.py3-none-any.whl (3.4 kB)
Collecting docutils>=0.10
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Building wheels for collected packages: blessings, mach, ply, toml, PyYAML, mozfile
  Building wheel for blessings (setup.py): started
  Building wheel for blessings (setup.py): finished with status 'done'
  Created wheel for blessings: filename=blessings-1.6-py3-none-any.whl size=19157 sha256=a5b531a837b03623d70ff9cc4532c5e000c9d8264b64ca48299946fbd6f3d8e8
  Stored in directory: /home/soveu/.cache/pip/wheels/b9/f3/71/b67ae328dbf2dd1e2b05cbb1d47cfa819ca9072d3d453bf1f8
  Building wheel for mach (setup.py): started
  Building wheel for mach (setup.py): finished with status 'done'
  Created wheel for mach: filename=mach-1.0.0-py2.py3-none-any.whl size=33219 sha256=a3bad94e924ffd1bf39e667092b34a0b50efd76c8b434186f8562f1980bd67ce
  Stored in directory: /home/soveu/.cache/pip/wheels/3a/b9/1a/0635a02d611170ef84aec5c984ed9d9805425847b456e73bc8
  Building wheel for ply (setup.py): started
  Building wheel for ply (setup.py): finished with status 'done'
  Created wheel for ply: filename=ply-3.8-py2.py3-none-any.whl size=48244 sha256=4fac69fa8c2089d68e967120dce716d25a05b3671274295717871d6edc6528c6
  Stored in directory: /home/soveu/.cache/pip/wheels/94/87/b7/4c9074125833e6e6e0fe2a2473e1763f580dee96611533de3e
  Building wheel for toml (setup.py): started
  Building wheel for toml (setup.py): finished with status 'done'
  Created wheel for toml: filename=toml-0.9.2-py3-none-any.whl size=8279 sha256=3b074b884907fc3e76372f21a97dc8c876302e3eda83747423ffd32dcfa8bf78
  Stored in directory: /home/soveu/.cache/pip/wheels/dd/79/21/95e1bd078c90ac3767bb62943526cb79a2f0ec37a4631ba93d
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.1-cp39-cp39-linux_x86_64.whl size=44073 sha256=2f4e4e883ad8343de837940143678d08da09d47e3e6cc8145c9edd8d7e193851
  Stored in directory: /home/soveu/.cache/pip/wheels/68/be/8f/b6c454cd264e0b349b47f8ee00755511f277618af9e5dae20d
  Building wheel for mozfile (setup.py): started
  Building wheel for mozfile (setup.py): finished with status 'done'
  Created wheel for mozfile: filename=mozfile-2.1.0-py2.py3-none-any.whl size=6505 sha256=f5f3253cea49ac09afea91681941bea9db1408934ada892a23ddc1f3a2665213
  Stored in directory: /home/soveu/.cache/pip/wheels/b3/aa/24/d89535081f09d71990c447987650c78f9d7ed8912cc3b894c2
Successfully built blessings mach ply toml PyYAML mozfile
Installing collected packages: six, python-dateutil, mozfile, jmespath, docutils, pyflakes, pycodestyle, mozinfo, mccabe, botocore, voluptuous, toml, s3transfer, PyYAML, mozterm, mozprocess, flake8, colorama, blessings, setuptools, servo-tidy, ply, pep8, mozlog, mozdebug, mach, distro, certifi, boto3
  Running setup.py develop for servo-tidy
Error:
    ERROR: Command errored out with exit status 1:
     command: /home/soveu/foss/servo/python/_virtualenv3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/soveu/foss/servo/python/tidy/setup.py'"'"'; __file__='"'"'/home/soveu/foss/servo/python/tidy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/soveu/foss/servo/python/tidy/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 14, in <module>
        from setuptools.dist import Distribution, Feature
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 23, in <module>
        from setuptools.depends import Require
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/soveu/foss/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/py33compat.py", line 54, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/soveu/foss/servo/python/_virtualenv3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/soveu/foss/servo/python/tidy/setup.py'"'"'; __file__='"'"'/home/soveu/foss/servo/python/tidy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by jdm** [comment]
This will be addressed by https://github.com/servo/servo/pull/27999.

**Comment by MichaelMcDonnell** [comment]
If you don't want to wait for the fix in #28092 then you just need to update two dependencies in python/requirements.txt. You need to update setuptools to at least 42 and six to 1.13.

**Comment by MichaelMcDonnell** [comment]
@Soveu could you please re-test? I just tried it with Debian testing and it works now that #28092 got merged.

**Comment by Soveu** [comment]
Yep, now it is working
