### ISSUE TITLE
Intermittent panic in http_loader::test_when_cookie_received_marked_secure_is_ignored_for_http

### ISSUE THREAD

**Issue by jdm** [servo/servo#28274]
this occurred in the windows github actions unit tests:
```
---- http_loader::test_when_cookie_received_marked_secure_is_ignored_for_http stdout ----
thread 'http_loader::test_when_cookie_received_marked_secure_is_ignored_for_http' panicked at 'called `Option::unwrap()` on a `None` value', components\net\tests\http_loader.rs:825:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\/library\core\src\panicking.rs:50
   3: main::http_loader::test_when_cookie_received_marked_secure_is_ignored_for_http
   4: alloc::boxed::{{impl}}::call_once
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\library\alloc\src\boxed.rs:1546
   5: std::panic::{{impl}}::call_once
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\library\std\src\panic.rs:344
   6: std::panicking::try::do_call
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\library\std\src\panicking.rs:379
   7: std::panicking::try
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\library\std\src\panicking.rs:343
   8: std::panic::catch_unwind
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\library\std\src\panic.rs:431
   9: test::run_test_in_process
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\/library\test\src\lib.rs:590
  10: test::run_test::run_test_inner::{{closure}}
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\/library\test\src\lib.rs:487
  11: test::run_test::run_test_inner::{{closure}}
             at /rustc/a8486b64b0c87dabd045453b6c81500015d122d6\/library\test\src\lib.rs:512
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/2985d48b773c25910b20f6201e99ed2240a46a55/components/net/tests/http_loader.rs#L825

**Comment by jdm** [comment]
This still happens after #28350:
```
---- http_loader::test_when_cookie_received_marked_secure_is_ignored_for_http stdout ----
thread 'http_loader::test_when_cookie_received_marked_secure_is_ignored_for_http' panicked at 'called `Option::unwrap()` on a `None` value', components\net\tests\http_loader.rs:827:10
```
https://github.com/servo/servo/blob/d35f1ee5e74c1b7d0efffff13717ef70f738f5ad/components/net/tests/http_loader.rs#L823-L829

**Comment by TimvdLippe** [comment]
Closing as stale as this issue has not received any failure references for over a month
