### ISSUE TITLE
Error running `./mach bootstrap-android --build`

### ISSUE THREAD

**Issue by teymour-aldridge** [servo/servo#28531]
```
teymouraldridge@Teymours-MBP servo % ./mach bootstrap-android --build
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
Error running mach:

    ['bootstrap-android', '--build']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

subprocess.CalledProcessError: Command '['/Users/teymouraldridge/Desktop/tmp/servo/android-toolchains/sdk/tools/bin/sdkmanager', 'platform-tools', 'platforms;android-18']' returned non-zero exit status 1.

  File "/Users/teymouraldridge/Desktop/tmp/servo/python/servo/bootstrap_commands.py", line 185, in bootstrap_android
    subprocess.check_call(sdkmanager)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
```

**Comment by jdm** [comment]
Android builds haven't been supported for at least a year and a half at this point. I've seen that error come from the wrong version of Java being used, I think?
