### ISSUE TITLE
macOS CI is broken

### ISSUE THREAD

**Issue by jdm** [servo/servo#28704]
It started within the past day, and manifests as the mozjs build reporting that the setuptools python package is not found. We should see if there were any GitHub environment changes made.

**Comment by jdm** [comment]
https://github.com/actions/virtual-environments/commits/main

**Comment by jdm** [comment]
Example of failed build: https://github.com/servo/servo/runs/4881699034?check_suite_focus=true

```
  Creating Python 3 environment
  Traceback (most recent call last):
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv.py", line 56, in <module>
      run()
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv.py", line 50, in run
      from virtualenv.__main__ import run as run_virtualenv
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/__init__.py", line 3, in <module>
      from .run import cli_run, session_via_cli
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/run/__init__.py", line 13, in <module>
      from .plugin.creators import CreatorSelector
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/run/plugin/creators.py", line 6, in <module>
      from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
      from virtualenv.create.creator import Creator
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/create/creator.py", line 15, in <module>
      from virtualenv.discovery.cached_py_info import LogCmd
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/discovery/cached_py_info.py", line 16, in <module>
      from virtualenv.discovery.py_info import PythonInfo
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/discovery/py_info.py", line 16, in <module>
      from distutils import dist
    File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in create_module
      return importlib.import_module('setuptools._distutils')
    File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  ModuleNotFoundError: No module named 'setuptools'
  DEBUG: python3: running with pid 43895
  DEBUG: python3: sys.executable: '/Users/runner/work/servo/servo/python/_virtualenv3.9/bin/python3'
  DEBUG: python3: executable from configuration: None
  DEBUG: python3: found executable: '/Users/runner/work/servo/servo/python/_virtualenv3.9/bin/python3'
  INFO: Creating Python 3 environment
  INFO: Traceback (most recent call last):
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv.py", line 56, in <module>
  INFO:     run()
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv.py", line 50, in run
  INFO:     from virtualenv.__main__ import run as run_virtualenv
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/__init__.py", line 3, in <module>
  INFO:     from .run import cli_run, session_via_cli
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/run/__init__.py", line 13, in <module>
  INFO:     from .plugin.creators import CreatorSelector
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/run/plugin/creators.py", line 6, in <module>
  INFO:     from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
  INFO:     from virtualenv.create.creator import Creator
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/create/creator.py", line 15, in <module>
  INFO:     from virtualenv.discovery.cached_py_info import LogCmd
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/discovery/cached_py_info.py", line 16, in <module>
  INFO:     from virtualenv.discovery.py_info import PythonInfo
  INFO:   File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/discovery/py_info.py", line 16, in <module>
  INFO:     from distutils import dist
  INFO:   File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in create_module
  INFO:     return importlib.import_module('setuptools._distutils')
  INFO:   File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  INFO:     return _bootstrap._gcd_import(name[level:], package, level)
  INFO: ModuleNotFoundError: No module named 'setuptools'

  --- stderr
  Traceback (most recent call last):
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/js/src/../../configure.py", line 231, in <module>
      sys.exit(main(sys.argv))
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/js/src/../../configure.py", line 55, in main
      sandbox.run(os.path.join(os.path.dirname(__file__), "moz.configure"))
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 502, in run
      self.include_file(path)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 493, in include_file
      exec_(code, self)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/util.py", line 55, in exec_
      exec(object, globals, locals)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/moz.configure", line 7, in <module>
      include("build/moz.configure/init.configure")
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 853, in include_impl
      self.include_file(what)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 493, in include_file
      exec_(code, self)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/util.py", line 55, in exec_
      exec(object, globals, locals)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/build/moz.configure/init.configure", line 241, in <module>
      def virtualenv_python3(env_python, virtualenv_name, build_env, mozconfig, help):
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 836, in decorator
      depends = DependsFunction(self, func, dependencies, when=when)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 137, in __init__
      sandbox._value_for(self)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 614, in _value_for
      return self._value_for_depends(obj)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/util.py", line 1049, in method_call
      cache[args] = self.func(instance, *args)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 623, in _value_for_depends
      value = obj.result()
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/util.py", line 1049, in method_call
      cache[args] = self.func(instance, *args)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 162, in result
      return self._func(*resolved_args)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1298, in wrapped
      return new_func(*args, **kwargs)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/build/moz.configure/init.configure", line 354, in virtualenv_python3
      manager.build(python)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 526, in build
      self.create(python)
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 280, in create
      raise Exception(
  Exception: Failed to create virtualenv: /Users/runner/work/servo/servo/target/release/build/mozjs_sys-fedf2ed60ae44607/out/build/_virtualenvs/init_py3 (virtualenv.py retcode: 1)
```

**Comment by jdm** [comment]
I'm seeing if the mozjs repository is affected the same way: https://github.com/servo/mozjs/pull/294

**Comment by jdm** [comment]
It does not affect the mozjs repository. I suspect it's related to the mach setup, in that case.
