### ISSUE TITLE
WPT Nightly Sync doesn't work during push to servo-wpt-sync

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#28920]
In the cron [job triggered last night](https://github.com/servo/servo/runs/7849689407?check_suite_focus=true), it failed during the push to servo-wpt-sync repo:

```
Push to branch wpt_update_16-08-2022
Pushing to https://github.com/servo-wpt-sync/servo.git
POST git-receive-pack (chunked)
To https://github.com/servo-wpt-sync/servo.git
 ! [remote rejected]       HEAD -> wpt_update_16-08-2022 (permission denied)
error: failed to push some refs to 'https://github.com/servo-wpt-sync/servo.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

@jdm could you please help me confirm if the WPT_SYNC_TOKEN is created from the @servo-wpt-sync account with branch push permission to the repo? 🙏

**Comment by jdm** [comment]
I'm fixing this in https://github.com/servo/servo/pull/29042.
