### ISSUE TITLE
Servo Benchmark dromaeo

### ISSUE THREAD

**Issue by MJUCOM** [servo/servo#29095]
Hi all!
I proceed the benchmark with dromaeo test suit. 

I start the benchmark the commend `./mach test-droaeo` after building servo with release version.

But i got the error below.

```
[dromaeo] jQuery - unbind x10
[dromaeo] jQuery - unbind x10
[dromaeo] jQuery - unbind x10
[dromaeo] jQuery - unbind x10
[dromaeo] createElement
[dromaeo] createElement
[dromaeo] createElement
[dromaeo] createElement
[dromaeo] createElement
[dromaeo] createTextNode
[dromaeo] createTextNode
[dromaeo] createTextNode
[dromaeo] createTextNode
[dromaeo] createTextNode
[dromaeo] innerHTML
[dromaeo] innerHTML
[dromaeo] innerHTML
[dromaeo] innerHTML
already mutably borrowed: BorrowError (thread Script(1,1), at components/script/dom/bindings/cell.rs:78)
[2022-11-24T11:28:26Z ERROR servo] already mutably borrowed: BorrowError
Pipeline failed in hard-fail mode.  Crashing!
mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
Stack tracethread panicked while processing panic. aborting.
Redirecting call to abort() to mozalloc_abort
```

Is there any solution to complete the benchmark??

**Comment by MJUCOM** [comment]
Thank you for your comment!

**Comment by MJUCOM** [comment]
Hi all!
I have some question about the dromaeo benchmark test suit.

Currently, I keep finding the above error code in Servo repo using Backtrace and gdb.
But, my goal is the to test the servo using benchmark dromaeo.

So i want to check the dromaeo benchmark test list and disregard error test case. Is there any file or directory to define the test case or benchmark list in dromaeo??

**Comment by jdm** [comment]
You will need to read through https://github.com/notriddle/dromaeo to figure that out. It's been too many years since I looked at it to be able to help.

**Comment by jdm** [comment]
It looks like it's possible to run a subset of the tests though: https://github.com/servo/servo/blob/901b76297d1fd56a55642e9398ebc1dcc0a25861/python/servo/testing_commands.py#L672

**Comment by MJUCOM** [comment]
Thank you!
Currently, I solve this problem!!

**Comment by MJUCOM** [comment]
But I have another problem to benchmark the dromaeo test.

when i execute the benchmark from commend` ./mach test-dromaeo` , I receive this error like below.
```

[dromaeo] Concat String Object
[dromaeo] Concat String from charCode
[dromaeo] Array String Join
[dromaeo] String Split
[dromaeo] String Split on Char
[dromaeo] charAt
[dromaeo] [Number]
[dromaeo] charCodeAt
[dromaeo] indexOf
[dromaeo] lastIndexOf
[dromaeo] slice
[dromaeo] substr
[dromaeo] substring
[dromaeo] toLowerCase
[dromaeo] toUpperCase
[dromaeo] comparing
[dromaeo] Parse JSON
[dromaeo] Make Tag Cloud
[dromaeo] Binary Trees
[dromaeo] Cordic
[dromaeo] Validate Email Input
[dromaeo] Validate Zipcode Input
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56856)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/wldns190/servo/tests/dromaeo/run_dromaeo.py", line 38, in do_POST
    self.wfile.write("<HTML>POST OK.<BR><BR>")
  File "/usr/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------


```

Is there any solution??

**Comment by jdm** [comment]
Update the line to use `self.wfile.write("<HTML>POST OK.<BR><BR>".encode())`. It was never updated for python3.

**Comment by MJUCOM** [comment]
Thank you for your comment!

I modify the `servo/tets/dromaeo/run_dromaeo.py` to use `self.wfile.write("<HTML>POST OK.<BR><BR>").encode()`. However, Same errror occur and the error message like below.

```
[dromaeo] Cordic
[dromaeo] Validate Email Input
[dromaeo] Validate Zipcode Input
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41166)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/wldns190/servo/tests/dromaeo/run_dromaeo.py", line 38, in do_POST
    self.wfile.write("<HTML>POST OK.<BR><BR>").encode()
  File "/usr/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
---------------------------------------- 
```

Is there any more files to modify??
Thank you very much!

**Comment by MJUCOM** [comment]
Thank you for your comment!!

I solve the problem to use `self.wfile.write("<HTML>POST OK.<BR><BR>".encode())` . But there are some problem the run_dromaeo.py code due to the python version. The problem occurs in  below code.
```
    def do_POST(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write("<HTML>POST OK.<BR><BR>".encode())
        length = int(self.headers.getheader('content-length'))
        parameters = urlparse.parse_qs(self.rfile.read(length))
        self.server.got_post = True
        self.server.post_data = parameters['data']
```

the similar errors occur in below code line and I guess that  the error will be occur in another code line in run_dromaeo.py.
```
        self.wfile.write("<HTML>POST OK.<BR><BR>".encode())
        length = int(self.headers.getheader('content-length'))
        parameters = urlparse.parse_qs(self.rfile.read(length))
```

So, I have some question about the error.
1. what is the python version to use in testing servo with dromaeo benchmarking?
2. Is there any solution above error?? I think that it occurs the python version.

Thank you so much for the answers!!

**Comment by jdm** [comment]
It's hard to say because you didn't actually mention what the problem was. The code used to work with python2, but we haven't tested it since we migrated the rest of servo to python3.

**Comment by MJUCOM** [comment]
The error message is like below.

```
[dromaeo] Cordic
[dromaeo] Validate Email Input
[dromaeo] Validate Zipcode Input
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51756)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/wldns190/servo/tests/dromaeo/run_dromaeo.py", line 47, in do_POST
    self.server.post_data = parameters['data']
KeyError: 'data'
```

I think that the problem is that the code use the python2 version function but the code is compiled by python3 version.. Is it right???
Thank you!!

**Comment by jdm** [comment]
I suspect the following changes will allow it to run:
```diff
diff --git a/tests/dromaeo/run_dromaeo.py b/tests/dromaeo/run_dromaeo.py
index 3a12652021..3a72c0c3b6 100755
--- a/tests/dromaeo/run_dromaeo.py
+++ b/tests/dromaeo/run_dromaeo.py
@@ -7,9 +7,8 @@
 import os
 import subprocess
 import sys
-import BaseHTTPServer
-import SimpleHTTPServer
-import urlparse
+import http.server
+import urllib.parse
 import json


@@ -30,17 +29,19 @@ def print_usage():


 # Handle the POST at the end
-class RequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
+class RequestHandler(http.server.SimpleHTTPRequestHandler):
     def do_POST(self):
+        print("post")
         self.send_response(200)
         self.end_headers()
-        self.wfile.write("<HTML>POST OK.<BR><BR>")
-        length = int(self.headers.getheader('content-length'))
-        parameters = urlparse.parse_qs(self.rfile.read(length))
+        self.wfile.write(b"<HTML>POST OK.<BR><BR>")
+        length = int(self.headers.get('content-length'))
+        parameters = urllib.parse.parse_qs(self.rfile.read(length))
         self.server.got_post = True
-        self.server.post_data = parameters['data']
+        self.server.post_data = parameters[b'data']

     def log_message(self, format, *args):
+        print(format % args)
         return


@@ -57,7 +58,7 @@ if __name__ == '__main__':
             sys.exit(1)

         # Start the test server
-        server = BaseHTTPServer.HTTPServer(('', TEST_SERVER_PORT), RequestHandler)
+        server = http.server.HTTPServer(('', TEST_SERVER_PORT), RequestHandler)

         print("Testing Dromaeo on Servo!")
         proc = run_servo(servo_exe, tests)
```

**Comment by MJUCOM** [comment]
Thank you so much!
Now, it can perform servo benchmark to dromaeo!!

Have a nice day!
