### ISSUE TITLE
Servo build Error : "× python setup.py egg_info did not run successfully."

### ISSUE THREAD

**Issue by MJUCOM** [servo/servo#29094]
Hi all!
I`m trying to build servo in Linux 5.13.0(Ubuntu 20.04.1) but i have some problem to build servo using mach commend.
When i proceed `./mach bootstrap` to install the package or dependencies before building the servo.
So I proceed the below commend.

```
sudo apt install git curl autoconf libx11-dev libfreetype6-dev libgl1-mesa-dri \
    libglib2.0-dev xorg-dev gperf g++ build-essential cmake libssl-dev \
    liblzma-dev libxmu6 libxmu-dev \
    libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev \
    libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libharfbuzz-dev ccache \
    clang libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev autoconf2.13 llvm-dev
```

To build the servo using` ./mach build --release` , i got the error report like below.

```
"/home/wldns190/servo/python/_virtualenv3.8/bin/python" "-m" "pip" "install" "-I" "-r" "/home/wldns190/servo/python/requirements.txt" failed with error code 1:
Output:
Obtaining file:///home/wldns190/servo/python/tidy (from -r /home/wldns190/servo/python/requirements.txt (line 34))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/wldns190/servo/python/tidy/setup.py", line 41, in <module>
          setup(
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
          self.finalize_options()
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/wldns190/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

But i don`t know how to handle this error. Is there any solution to build the servo using mach??
Thank you!!

**Comment by michaelgrigoryan25** [comment]
Could you please try completely cleaning the potential build cache generated by Mach and retrying? You can do that by running:
```sh
$ ./mach clean
$ ./mach build
```

However, if any of those commands fail, please include the full stack trace of the error in your reply. Please also include the version of Python you have installed by running:
```sh
$ python --version
```

If you stumble upon any errors during the process, please include all of them in your reply, since it would help the maintainers and contributors investigate your issue much better.

**Comment by jdm** [comment]
You could also try updating the version of setuptools in use (https://github.com/servo/servo/blob/309c4f9b51a4a0c951da1b96a91fdef040b52e82/python/requirements.txt#L9) to 65.6.3 and see if that helps. Run `./mach clean` before `./mach build` to be sure.

**Comment by MJUCOM** [comment]
Thank you!!
Currently, I solve this problem!
Have a nice day:)

**Comment by michaelgrigoryan25** [comment]
Great to hear! Seems like we can close this issue then.

**Comment by shrkamat** [comment]
Facing same issue but `./mach clean` is not helping.

```
./mach clean
"/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/bin/python" "-m" "pip" "install" "-I" "-r" "/home/skamath/Projects/spidermonkey/servo/python/requirements.txt" failed with error code 1:
Output:
Obtaining file:///home/skamath/Projects/spidermonkey/servo/python/tidy (from -r /home/skamath/Projects/spidermonkey/servo/python/requirements.txt (line 34))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/skamath/Projects/spidermonkey/servo/python/tidy/setup.py", line 41, in <module>
          setup(
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
          self.finalize_options()
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/skamath/Projects/spidermonkey/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mrego** [comment]
This issue is also discussed at #29334.
