### ISSUE TITLE
servo build Error : ./mach bootstrap

### ISSUE THREAD

**Issue by MJUCOM** [servo/servo#29334]
Hi all!

I have some problem to build the servo. I proceed the below commends. And There are no problem and error.

`curl https://sh.rustup.rs -sSf | sh`

`curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none`

`sudo apt install python3-virtualenv python3-pip`

But when i proceed the below commend line, there are some problem like below.

`./mach bootstrap
`
[Error Message]
```
"/home/rozit/servo/python/_virtualenv3.8/bin/python" "-m" "pip" "install" "-I" "-r" "/home/rozit/servo/python/requirements.txt" failed with error code 1:
Output:
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/rozit/servo/python/tidy (from -r /home/rozit/servo/python/requirements.txt (line 34))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/rozit/servo/python/tidy/setup.py", line 41, in <module>
          setup(
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Following the servo readme, I proceed the commend like below.
```
sudo apt install git curl autoconf libx11-dev libfreetype6-dev libgl1-mesa-dri \
    libglib2.0-dev xorg-dev gperf g++ build-essential cmake libssl-dev \
    liblzma-dev libxmu6 libxmu-dev \
    libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev \
    libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libharfbuzz-dev ccache \
    clang libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev autoconf2.13 llvm-dev
```

And start the build ./mach build --release but i got the same problem and error message.

Is there any solution to start the `./mach bootstrap`? 
And, Is there any way to build the servo??

Have a nice day!
Thank you very much☺️

**Comment by jdm** [comment]
I believe this has to do with an outdated version of python's setuptools. You may need to upgrade your version of python beyond 3.8 and run `./mach clean` before building again.

**Comment by MJUCOM** [comment]
Thank you for your comment!!

However, I still have some error like below when proceed` ./mach bootstrap`

```
"/home/rozit/servo/python/_virtualenv3.8/bin/python" "-m" "pip" "install" "-I" "-r" "/home/rozit/servo/python/requirements.txt" failed with error code 1:
Output:
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/rozit/servo/python/tidy (from -r /home/rozit/servo/python/requirements.txt (line 34))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/rozit/servo/python/tidy/setup.py", line 41, in <module>
          setup(
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/rozit/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I set the environment to use python version 3.8.10 and python3 version 3.8.10.

I wonder that how to set the python`s setuptools version beyond 3.8. Or, Is there any solution??

Thank you very much!
Have a nice day!

**Comment by jdm** [comment]
I mean that you may need to install python 3.9 or 3.10.

**Comment by MJUCOM** [comment]
Thank you for your comment!

I solve this problem!

**Comment by sheerun** [comment]
@jdm It is not true: Debian bullseye has python 3.9.2 and this error still happens

**Comment by jdm** [comment]
What's the full error output you see?

**Comment by seccompgeek** [comment]
I'm experiencing the same issue. May I know how you managed to solve this problem?

**Comment by mrego** [comment]
I see a similar error en Debian bullseye:
```
$ ./mach bootstrap
"/root/servo-master/python/_virtualenv3.9/bin/python" "-m" "pip" "install" "-I" "-r" "/root/servo-master/python/requirements.txt" failed with error code 1:
Output:
Ignoring dataclasses: markers 'python_version < "3.7"' don't match your environment
Obtaining file:///root/servo-master/python/tidy (from -r /root/servo-master/python/requirements.txt (line 42))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/root/servo-master/python/tidy/setup.py", line 41, in <module>
          setup(
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/root/servo-master/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mrego** [comment]
As mentioned on the [PR](https://github.com/servo/servo/pull/29877#issuecomment-1593196726) this doesn't solve the issue in Debian Bullseye. Now the error is different but we still get a similar error:
```
rego@1e97a99ee391:~/servo$ ./mach bootstrap
"/home/rego/servo/python/_virtualenv3.9/bin/python" "-m" "pip" "install" "-I" "-r" "/home/rego/servo/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt" failed with error code 1:
Output:
Collecting html5lib==1.1 (from -r /home/rego/servo/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt (line 1))
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting mozdebug==0.3.0 (from -r /home/rego/servo/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt (line 2))
  Using cached mozdebug-0.3.0-py2.py3-none-any.whl (6.0 kB)
Collecting mozinfo==1.2.2 (from -r /home/rego/servo/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt (line 3))
  Using cached mozinfo-1.2.2.tar.gz (5.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  &#9474; exit code: 1
  &#9584;&#9472;> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6as17ggn/mozinfo_3792d52b07714134829f647aad339b5a/setup.py", line 17, in <module>
          setup(
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/rego/servo/python/_virtualenv3.9/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
&#9584;&#9472;> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mrego** [comment]
Thanks @mrobinson for the help, I managed to solve this issue on my system doing the following:
```
$ source python/_virtualenv*/bin/activate
$ pip install -r python/requirements.txt
```

Which upgraded `setuptools`, you can see this message in the output:
```
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
      Successfully uninstalled setuptools-44.1.1
Successfully installed setuptools-65.5.1
```

Then `./mach bootstrap` worked without issues.
