### ISSUE TITLE
'./mach build' fails to run

### ISSUE THREAD

**Issue by msscaroso** [servo/servo#29353]
I'm on `Ubuntu 22.04.1`  with `python3.10.6`.

When running `./mach build` (either --release or --dev), the following error occurs and the build terminates:

```
  FileNotFoundError: [Errno 2] No such file or directory: '/home/marcio/github.com/servo/servo/target/debug/build/mozjs_sys-ce67ba622c0390d8/out/build/_virtualenvs/build/lib/python3.10/site-packages/mach.pth'
```

(which comes in the middle of :point_down:  )
```
  created virtual environment CPython3.10.6.final.0-64 in 35ms
    creator CPython3Posix(dest=/home/marcio/github.com/servo/servo/target/debug/build/mozjs_sys-ce67ba622c0390d8/out/build/_virtualenvs/build, clear=False, no_vcs_ignore=False, global=False)
    activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
  Using Python 3.10.6 from /home/marcio/github.com/servo/servo/python/_virtualenv3.10/bin/python3
  Site not up-to-date reason: "/home/marcio/github.com/servo/servo/target/debug/build/mozjs_sys-ce67ba622c0390d8/out/build/_virtualenvs/build" does not exist

  --- stderr
  gmake: *** No targets specified and no makefile found.  Stop.
  Traceback (most recent call last):
    File "/home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/js/src/../../configure.py", line 350, in <module>
      sys.exit(main(sys.argv))
    File "/home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/js/src/../../configure.py", line 121, in main
      _activate_build_virtualenv()
    File "/home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/js/src/../../configure.py", line 344, in _activate_build_virtualenv
      if not build_site.ensure():
    File "/home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/python/mach/mach/site.py", line 565, in ensure
      _create_venv_with_pthfile(
    File "/home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/python/mach/mach/site.py", line 1191, in _create_venv_with_pthfile
      with open(os.path.join(platlib_site_packages_dir, PTH_FILENAME), "w") as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/home/marcio/github.com/servo/servo/target/debug/build/mozjs_sys-ce67ba622c0390d8/out/build/_virtualenvs/build/lib/python3.10/site-packages/mach.pth'
  cat: config.log: No such file or directory
  make: *** [/home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/makefile.cargo:195: maybe-configure] Error 1
  thread 'main' panicked at 'assertion failed: result.success()', /home/marcio/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/build.rs:178:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```

This looks like the same issue as https://bugzilla.mozilla.org/show_bug.cgi?id=1766497. Since it was fixed, I guess we just need to upgrade match. 

In the thread, it's said to be MacOS, but by the error it seems the same.

I tried the workaround of using python3.9 and it worked.

The workaround:

### 1 -  Alt install python3.9 (in case you don't have it yet)

Download source files https://www.python.org/downloads/release/python-3916/, extract and cd into the extracted folder.

Then:

```
./configure
make
sudo make altinstall
```

Check that it worked: `python3.9 --version`

### 2 - Change mach script to use python3.9

Open `servo/servo/mach` and change it to use python3.9.
Removes the initial shell scripting lines and it should begin like this:

```python
#!/usr/local/bin/python3.9
from __future__ import print_function, unicode_literals

import os
import sys

if sys.version_info < (3, 5):
    print("mach does not support python < 3.5, please install python 3 >= 3.5")
    sys.exit(1)

...
```

Run the build command and it should work

**Comment by msscaroso** [comment]
Found more about the issue.
It's not actually related to the python version. It happens if you are using the system python in a debian based distro.

When I use the system python (`/usr/bin/python3`).
The mozjs build will call `mach` via [configure.py](https://github.com/servo/mozjs/blob/dba8a79581c83232b06db7d536e1a4f318404494/mozjs/mozjs/configure.py),
which then creates a virtual env in
`servo/servo/target/release/build/mozjs_sys-c1d0a308a9f247e9/out/build/_virtualenvs/`.

You will get a slightly different directore structure if you are using a system python or not in a debian based distro.
system python you get:  `_virtualenvs/build/lib/python3.10/dist-packages/`,
local python `_virtualenvs/build/lib/python3.10/site-packages/`.

The issue: `mach` is incorrectly looking for `site-packages` and the build fails.
I believe the culprit is this line [here](https://github.com/mozilla/gecko-dev/blob/b579290e6b830d1b3f0a941203b0c0e1e56c42a3/python/mach/mach/site.py#L828-L836) forcing `posix_prefix` whereas the correct scheme should be `posix_local`.


I'm closing because this is not an issue specific to servo and there's an easy workaround
