### ISSUE TITLE
thread 'main' panicked at 'Can't read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', p orts/winit/resources.rs:79:24

### ISSUE THREAD

**Issue by luphoria** [servo/servo#29868]
Attempting to start `servo` on Arch is giving me the following error (using RUST_BACKTRACE=full):
```
thread 'main' panicked at 'Can't read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ports/winit/resources.rs:79:24
stack backtrace:
   0:     0x5589a641ca6a - std::backtrace_rs::backtrace::libunwind::trace::h0c22b655db076f8f
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5589a641ca6a - std::backtrace_rs::backtrace::trace_unsynchronized::hcdd4102b3a0150ac
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5589a641ca6a - std::sys_common::backtrace::_print_fmt::hf85e841224953c0f
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5589a641ca6a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd24e715ba1140cb
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5589a64453ce - core::fmt::write::heff0333d94dc3611
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/fmt/mod.rs:1232:17
   5:     0x5589a64166a5 - std::io::Write::write_fmt::hb2c8997cfd3a0f64
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/io/mod.rs:1682:15
   6:     0x5589a641c835 - std::sys_common::backtrace::_print::hfec2f148629f279f
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5589a641c835 - std::sys_common::backtrace::print::h4f363203c4b7325a
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5589a641e20f - std::panicking::default_hook::{{closure}}::h3eafb1e588ec9ebd
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:267:22
   9:     0x5589a641df4b - std::panicking::default_hook::hc13d68d7c25a30e4
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:286:9
  10:     0x5589a641e929 - std::panicking::rust_panic_with_hook::he1eefea5c8f2ac79
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:688:13
  11:     0x5589a641e6c9 - std::panicking::begin_panic_handler::{{closure}}::h4bc7f07ca679bf76
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
  12:     0x5589a641cf1c - std::sys_common::backtrace::__rust_end_short_backtrace::h31f73c68c53ad6bd
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5589a641e3d2 - rust_begin_unwind
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
  14:     0x5589a35508c3 - core::panicking::panic_fmt::hf1444176bba18781
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
  15:     0x5589a3550d73 - core::result::unwrap_failed::hcca4aab4bc0aac16
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/result.rs:1790:5
  16:     0x5589a366962e - <servo::resources::ResourceReader as embedder_traits::resources::ResourceReaderMethods>::read::h0ffebfb166bf3ef2
  17:     0x5589a60341cd - embedder_traits::resources::read_bytes::h3858f49d2881481c
  18:     0x5589a60342e5 - embedder_traits::resources::read_string::hbe71d7dac8ba305c
  19:     0x5589a3530483 - std::sys_common::once::futex::Once::call::hd34d6efde9b0e35c
  20:     0x5589a5fec081 - servo_config::opts::from_cmdline_args::hc5dce3623c9b9e2e
  21:     0x5589a360739f - servo::main::hf89b64314495b49c
  22:     0x5589a3615103 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcfe78a14a2cb95e1
  23:     0x5589a35b3d89 - std::rt::lang_start::{{closure}}::heb3e906255003ec7
  24:     0x5589a640f72c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc7c7c64ba20a055a
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:287:13
  25:     0x5589a640f72c - std::panicking::try::do_call::h24f98f748a1313dd
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
  26:     0x5589a640f72c - std::panicking::try::h9bb275b0821d06db
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
  27:     0x5589a640f72c - std::panic::catch_unwind::h6c1095f6295b379e
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
  28:     0x5589a640f72c - std::rt::lang_start_internal::{{closure}}::h5751dcc710702ab6
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:48
  29:     0x5589a640f72c - std::panicking::try::do_call::h8fd8ad02b94dd2c3
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
  30:     0x5589a640f72c - std::panicking::try::h4e5995cea98a0ac3
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
  31:     0x5589a640f72c - std::panic::catch_unwind::h9220e61283178032
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
  32:     0x5589a640f72c - std::rt::lang_start_internal::h1a4a8fb9fce35175
                               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:20
  33:     0x5589a36080f5 - main
  34:     0x7f2d3f68c850 - <unknown>
  35:     0x7f2d3f68c90a - __libc_start_main
  36:     0x5589a35517ee - _start
  37:                0x0 - <unknown>
```

Am I doing something wrong? Thanks :)

**Comment by jdm** [comment]
How did you obtain your servo binary and what does the working directory look like from where you're running it?

**Comment by luphoria** [comment]
Download link from the official downloads page, for Linux - https://download.servo.org/nightly/linux/servo-latest.tar.gz. I created a folder ~/Downloads/servo, unpacked the archive, and tried to run.

**Comment by jdm** [comment]
I believe the file that's having trouble is https://github.com/servo/servo/blob/7d9839acc8a56499e81c5b0e20ca874b0f005757/components/config/prefs.rs#L16, which corresponds to [prefs.json](https://github.com/servo/servo/blob/7d9839acc8a56499e81c5b0e20ca874b0f005757/ports/winit/resources.rs#L20) which should be in the `resources` directory in ~/Downloads/servo. What working directory are you in when you run the binary? https://github.com/servo/servo/blob/7d9839acc8a56499e81c5b0e20ca874b0f005757/ports/winit/resources.rs#L53-L70 is the code that tries to find the resources directory to load files from it.

**Comment by luphoria** [comment]
Hi, thanks for the response; the specific working directory is `/home/trent/Downloads/servo` if I'm understanding you correctly. I tried a few other things, and now it's `/home/trent/Downloads/servo_testing/servo`. 
I don't know the specification of Rust, but I'm assuming it's either:
Because of the FIXME in right above your code quote:
https://github.com/servo/servo/blob/7d9839acc8a56499e81c5b0e20ca874b0f005757/ports/winit/resources.rs#LL50C1-L52C60
(because my executable is not in a structure like this)
or because the code `current_exe` results in a path including the executable itself, i.e. `/path/to/servo/servo`. Unfortunately I can't really test this because I can't have `servo` as both a file and directory in the same path.
Could be something else too. I'm a bit of a noob :sweat_smile:

**Comment by jdm** [comment]
Is there a `resources` directory under `/home/trent/Downloads/servo_testing/`? Does it contain a `prefs.json` file?

**Comment by luphoria** [comment]
No, but there is a `resources/` dir in servo_testing/servo. Nothing is in the folder though.

**Comment by jdm** [comment]
Oh, well that's your problem then. When I unzipped the tar file there was a resources directory that contained a bunch of files alongside the servo binary.

**Comment by luphoria** [comment]
```
~/Downloads/servo_testing  tree
.
└── servo
    ├── 00.example.js
    ├── ahem
    ├── ahem.css
    ├── Ahem.ps
    ├── Ahem.sit
    ├── AHEM____.TTF
    ├── android_params
    ├── badcert.html
    ├── badcert.jpg
    ├── cert-google-only
    ├── certs
    ├── cert-wpt-only
    ├── COPIED-FROM
    ├── COPYING
    ├── Credits.rtf.mako
    ├── gatt_blocklist.txt
    ├── hsts_preload.json
    ├── iso-8859-8.css
    ├── media-controls.css
    ├── media-controls.js
    ├── neterror.html
    ├── not-found.html
    ├── prefs.json
    ├── presentational-hints.css
    ├── privatekey_for_testing.key
    ├── public_domains.txt
    ├── quirks-mode.css
    ├── quotes.css
    ├── README
    ├── resources
    ├── rippy.png
    ├── self_signed_certificate_for_testing.crt
    ├── servo
    ├── servo_1024.png
    ├── servo_64.png
    ├── servo.css
    ├── servo.icns
    ├── servo.ico
    ├── servo.svg
    ├── tumbeast.png
    ├── user-agent.css
    └── user-agent-js

5 directories, 39 files
```
Servo binary had plenty of stuff, just not any folders with stuff in them.

It ended up being a problem with how I unpacked the arhcive though. I used 7z twice which clearly led to some issues. Using `tar zxf` worked :)

**Comment by mucinoab** [comment]
This also happened to me while building from source.
I had to unset the `CARGO_TARGET_DIR` environment variable.
