### ISSUE TITLE
#29877 broke ./mach

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#29889]
Since #29877, when I run something like `./mach build`, `./mach test-wpt` or `./mach update-wpt` I get an error:

```
Traceback (most recent call last):
  File "/home/oriol/src/servo/./mach", line 47, in <module>
    main(sys.argv)
  File "/home/oriol/src/servo/./mach", line 29, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/home/oriol/src/servo/python/mach_bootstrap.py", line 322, in bootstrap
    mach.load_commands_from_file(os.path.join(topdir, path), module_name)
  File "/home/oriol/src/servo/python/mach/mach/main.py", line 266, in load_commands_from_file
    imp.load_source(module_name, path)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oriol/src/servo/python/servo/testing_commands.py", line 23, in <module>
    import tidy
  File "/home/oriol/src/servo/python/tidy/tidy.py", line 24, in <module>
    from .licenseck import OLD_MPL, MPL, APACHE, COPYRIGHT, licenses_toml, licenses_dep_toml
ImportError: attempted relative import with no known parent package
```

Effectively, in order to do `important tidy` in python, I need to install `python3-utidylib`. However, installing it doesn't fix `./mach`, maybe because it's using a virtualenv or something that doesn't see `python3-utidylib`?

Cc @mrobinson

**Comment by Loirooriol** [comment]
Just removing that `import tidy` fixes the problem for me and I can compile just fine

**Comment by mrobinson** [comment]
You need to remove the `python/_virtualenv*` directory and rerun `./mach bootstrap`. This is an issue with the old `.pth` file handing around there. I'm not sure if there is a way to ensure this or not...

**Comment by mrobinson** [comment]
I think we can close this, since it simply requires removing the Python virtual environment.
