### ISSUE TITLE
failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs#98b67828)`

### ISSUE THREAD

**Issue by charlesxsh** [servo/servo#30008]
```
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs#98b67828)`

Caused by:
  process didn't exit successfully: `D:\code\servo\target\debug\build\mozjs_sys-e8def70a72eafd5a\build-script-build` (exit code: 101)
  --- stdout
  cargo:outdir=D:\code\servo\target\debug\build\mozjs_sys-3aa3d5b6bc06ac9c\out\build
  [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure.in ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure || true
  [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure.in ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure || true
  ! [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure.in -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure || true
  ! [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure.in -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure || true
  if [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure -nt config.status ]] ; then \
    PYTHON="C:\Users\charl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe" MOZ_TOOLS="/" \
    CC="clang-cl.exe" CFLAGS="-MD" \
    CPP="" CPPFLAGS="-ID:/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
    CXX="clang-cl.exe" CXXFLAGS="-MD" \
    AS="" AR="" \
    STLPORT_LIBS="" \
    'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake --enable-js-streams --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 || (cat config.log && exit 1) ; \
  fi

  --- stderr
   - Cannot opencat: config.log: No such file or directory
  mozmake: *** [D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\makefile.cargo:195: maybe-configure] Error 1
  thread 'main' panicked at 'assertion failed: result.success()', D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\build.rs:178:5
```

System: Windows 11 Pro
Python: Python 11 (C:\Users\charl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe)
Servo Git Version: ae3f33b9d03393eb25503fa3b30f05957119f9a7 (07/18/23)

I tried to set PYTHON3 environment variable but failed (https://github.com/servo/servo/issues/29142)

**Comment by mrobinson** [comment]
Can you try building with -vv and paste the output here?

**Comment by charlesxsh** [comment]
Sure
```
[mozjs_sys 0.68.2] cargo:outdir=D:\code\servo\target\debug\build\mozjs_sys-3aa3d5b6bc06ac9c\out\build
[mozjs_sys 0.68.2] [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure.in ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure || true
[mozjs_sys 0.68.2] [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure.in ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure || true
[mozjs_sys 0.68.2] ! [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure.in -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure || true
[mozjs_sys 0.68.2] ! [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure.in -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure || true
[mozjs_sys 0.68.2] if [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure -nt config.status ]] ; then \
[mozjs_sys 0.68.2]   PYTHON="C:\Users\charl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe" MOZ_TOOLS="/" \
[mozjs_sys 0.68.2]   CC="clang-cl.exe" CFLAGS="-MD" \
[mozjs_sys 0.68.2]   CPP="" CPPFLAGS="-ID:/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
[mozjs_sys 0.68.2]   CXX="clang-cl.exe" CXXFLAGS="-MD" \
[mozjs_sys 0.68.2]   AS="" AR="" \
[mozjs_sys 0.68.2]   STLPORT_LIBS="" \
[mozjs_sys 0.68.2]   'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake --enable-js-streams --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 || (([[ -e config.log ]] && cat config.log) && exit 1) ; \
[mozjs_sys 0.68.2] fi
[mozjs_sys 0.68.2]  - Cannot openmozmake: *** [D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\makefile.cargo:195: maybe-configure] Error 1
[mozjs_sys 0.68.2] thread 'main' panicked at 'assertion failed: result.success()', D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\build.rs:178:5
[mozjs_sys 0.68.2] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs#98b67828)`

Caused by:
  process didn't exit successfully: `D:\code\servo\target\debug\build\mozjs_sys-e8def70a72eafd5a\build-script-build` (exit code: 101)
  --- stdout
  cargo:outdir=D:\code\servo\target\debug\build\mozjs_sys-3aa3d5b6bc06ac9c\out\build
  [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure.in ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure || true
  [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure.in ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure || true
  ! [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure.in -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure || true
  ! [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure.in -ot 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure ]] && touch 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/old-configure || true
  if [[ 'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure -nt config.status ]] ; then \
    PYTHON="C:\Users\charl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe" MOZ_TOOLS="/" \
    CC="clang-cl.exe" CFLAGS="-MD" \
    CPP="" CPPFLAGS="-ID:/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
    CXX="clang-cl.exe" CXXFLAGS="-MD" \
    AS="" AR="" \
    STLPORT_LIBS="" \
    'D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake --enable-js-streams --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 || (([[ -e config.log ]] && cat config.log) && exit 1) ; \
  fi

  --- stderr
   - Cannot openmozmake: *** [D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\makefile.cargo:195: maybe-configure] Error 1
  thread 'main' panicked at 'assertion failed: result.success()', D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\build.rs:178:5
```

**Comment by charlesxsh** [comment]
<img width="236" alt="image" src="https://github.com/servo/servo/assets/8362565/8be68b3e-cc48-41ba-a855-908d81a5cb6e">

**Comment by cannero** [comment]
To which path is `PYTHON3` is set, what does `echo %PYTHON3%` show?

I get a similar error if `PYTHON3` isn't set at all:
```
--- stderr
  C:\Users\nile\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs/js/src/configure: line 13: exec: python3: not found
  cat: config.log: No such file or directory
```
In the build output `PYTHON` is still set correctly from the path:
```
PYTHON="C:\Program Files\Python311\python.exe" MOZ_TOOLS="/" \
    CC="clang-cl.exe" CFLAGS="-MD" \
```

**Comment by charlesxsh** [comment]
> To which path is `PYTHON3` is set, what does `echo %PYTHON3%` show?
> 
> I get a similar error if `PYTHON3` isn't set at all:
> 
> ```
> --- stderr
>   C:\Users\nile\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs/js/src/configure: line 13: exec: python3: not found
>   cat: config.log: No such file or directory
> ```
> 
> In the build output `PYTHON` is still set correctly from the path:
> 
> ```
> PYTHON="C:\Program Files\Python311\python.exe" MOZ_TOOLS="/" \
>     CC="clang-cl.exe" CFLAGS="-MD" \
> ```

Your error looks different.
1.   C:\Users\nile\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs/js/src/configure: line 13: exec: python3: not found
This file `C:\Users\nile\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs/js/src/configure` is following:
```
SRCDIR=$(dirname $0)
TOPSRCDIR="$SRCDIR"/../..
PYTHON3="${PYTHON3:-python3}"
export OLD_CONFIGURE="$SRCDIR"/old-configure

set -- "$@" --enable-project=js

exec "$PYTHON3" "$TOPSRCDIR/configure.py" "$@"  
```

`PYTHON3="${PYTHON3:-python3}"` this line 13 give the default value 'python3' to Env PYTHON3. Then it uses Env PYTHON3 to execute the file C:\Users\nile\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\mozjs\configure.py. So if your PATH variable cannot let system find 'python3', it will have the error you mentioned here.

2. buid output 'PYTHON'
This thing comes from file "C:\Users\nile\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\makefile.cargo", line 196:

start from line 196:
```
PYTHON="$(PYTHON)" MOZ_TOOLS="$(MOZ_TOOLS)" \
	  CC="$(CC)" CFLAGS="$(CFLAGS)" \
	  CPP="$(CPP)" CPPFLAGS="$(CPPFLAGS)" \
	  CXX="$(CXX)" CXXFLAGS="$(CXXFLAGS)" \
	  AS="$(AS)" AR="$(AR)" \
	  STLPORT_LIBS="$(STLPORT_LIBS)" \
	  $(JSSRC)/configure $(strip $(CONFIGURE_FLAGS)) || (cat config.log && exit 1) ; \
```

which is simply setting a bunch of environment variables to call `configure` as we mentioned earlier. Notes here it sets Env PYTHON, instead of Env PYTHON3 used in `configure`.

**Comment by cannero** [comment]
Yes, the error is not the same.
When you say that you tried to set PYTHON3 environment variable but failed what do you mean? Do you have a python3 in your path? The installation with choco contains only a python.exe.

**Comment by charlesxsh** [comment]
I mean the moz_js compilation also failed. Actually setting PYTHON3 seems like is unrelated to the error I had here. The error "Cannot open mozmake: *** [D:\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\98b6782\mozjs\makefile.cargo:195: maybe-configure] Error 1" is related to `mozmake`

**Comment by sagudev** [comment]
`mozmake` should be download when running `mach bootstrap`. It should be in `target\dependencies\moztools-3.2\bin\mozmake.exe`. Make sure it is working/wasn't corrupted on downloading/extracting.

**Comment by charlesxsh** [comment]
Yes, it is working. It is placed at `target\dependencies\moztools\3.2\bin\mozmake.exe`

**Comment by charlesxsh** [comment]
I think I figured out, the MOZ_TOOLS="/" in  `mozjs\makefile.cargo` is wrong.

**Comment by sagudev** [comment]
We should probably have "?=" assignment, because "MOZ_TOOLS"=/ is accurate when in mozilla_build shell. Although if I'm being honest I'm reluctant to change it altogether, as soon we remove JS streams from servo I plan to upgrade mozjs, which should change requirement. Also I would like to make standalone builds not use mozilla-build anymore, like we do with servo, this should hopefully lower number mozjs building problems reports.

**Comment by mrobinson** [comment]
I think this is no longer an issue now after some changes to mozjs? @sagudev?

**Comment by sagudev** [comment]
We now do not use mozilla-build anymore, because we completely replace it with moztools, that also has mozmake: https://github.com/servo/servo-build-deps/blob/main/AssemblingMozTools.md

This landed in https://github.com/servo/mozjs/pull/368.
