### ISSUE TITLE
Servo Build issue in Ubuntu system 

### ISSUE THREAD

**Issue by tpravee** [servo/servo#30188]
We are facing the build issue, while building the servo in Ubuntu-20. Can you share the detailed configuration dependency in Ubuntu-20

Build Error:
  Using cached mozlog-8.0.0.tar.gz (53 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lobu90r1/mozlog_701a7a96d0bf444f88494312e1a6d04b/setup.py", line 17, in <module>
          setup(
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/pshetty/SERVO/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 20.0.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

**Comment by mukilan** [comment]
This error seems similar to the one in #29334. Can you try upgrading your python version to 3.9 or above as specified in that linked issue?

**Comment by tpravee** [comment]
Thanks for the update...
