### ISSUE TITLE
Crash on github.com

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [servo/servo#30489]
This crash sometimes happens :trollface:.

I am on commit: `f5d40a473b677960b5873160a6830fc1274dddc3` and have built Servo in release mode on Arch Linux. To reproduce run `./mach --release`, go to https://github.com and violently move your mouse over the menu items before the page is fully loaded. After you have done that, servo crashes.

Here is the backtrace:
```
[2023-10-04T05:47:50Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/vendors-node_modules_stacktrace-parser_dist_stack-trace-parser_esm_js-node_modules_github_bro-a4c183-18bf85b8e9f4.js:1:4152 AbortSignal is not defined
[2023-10-04T05:47:50Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/vendors-node_modules_github_filter-input-element_dist_index_js-node_modules_github_remote-inp-b7d8f4-9cf7d828a39b.js:1:16064 IntersectionObserver is not defined
[2023-10-04T05:47:50Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/vendors-node_modules_github_file-attachment-element_dist_index_js-node_modules_primer_view-co-821777-b03c18faaa84.js:1:19393 IntersectionObserver is not defined
[2023-10-04T05:47:50Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/behaviors-90a219eaae18.js:8:26106 AbortController is not defined
[2023-10-04T05:47:50Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/marketing-491859bb3d7a.js:1:7662 IntersectionObserver is not defined
[2023-10-04T05:47:50Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/home-0369a2a6b0c5.js:1:121 IntersectionObserver is not defined
[2023-10-04T05:47:51Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/ui_packages_query-builder-element_query-builder-element_ts-e9e1a1c0cd1d.js:1:10118 AbortController is not defined
[2023-10-04T05:47:51Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/chunk-app_assets_modules_github_onfocus_ts-app_assets_modules_github_visible_ts-app_components_sear-8eff57-56b36b522837.js:5:1628 AbortController is not defined
[2023-10-04T05:47:51Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/sessions-04ec2c51e991.js:1:6656 AbortController is not defined
index out of bounds: the len is 1385 but the index is 1385 (thread main, at /home/andy/work/tmp/servo/components/compositing/compositor.rs:1129)
   0: servo::backtrace::print
   1: servo::main2::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::panicking::panic_bounds_check
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:159:5
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: compositing::compositor::IOCompositor<Window>::hit_test_at_point_with_flags_and_pipeline
  11: compositing::compositor::IOCompositor<Window>::dispatch_mouse_window_move_event_class
  12: servo::Servo<Window>::handle_events
  13: servo::app::App::handle_events
  14: servo::events_loop::EventsLoop::run_forever::{{closure}}
  15: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}
  16: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
  17: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
  18: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  19: winit::platform_impl::platform::x11::EventLoop<T>::run
  20: winit::platform_impl::platform::EventLoop<T>::run
  21: winit::event_loop::EventLoop<T>::run
  22: servo::app::App::run
  23: servo::main2::main
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::rt::lang_start::{{closure}}
  26: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:20
  27: main
  28: <unknown>
  29: __libc_start_main
  30: _start
  ```

**Comment by Andy-Python-Programmer** [comment]
Sometimes you get the same out of bounds error but with a different index and length and a larger backtrace.

```
[2023-10-04T05:53:36Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/vendors-node_modules_stacktrace-parser_dist_stack-trace-parser_esm_js-node_modules_github_bro-a4c183-18bf85b8e9f4.js:1:4152 AbortSignal is not defined
index out of bounds: the len is 1341 but the index is 1359 (thread main, at /home/andy/work/tmp/servo/components/compositing/compositor.rs:1129)
   0: servo::backtrace::print
   1: servo::main2::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::panicking::panic_bounds_check
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:159:5
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: compositing::compositor::IOCompositor<Window>::hit_test_at_point_with_flags_and_pipeline
  11: compositing::compositor::IOCompositor<Window>::dispatch_mouse_window_move_event_class
  12: servo::Servo<Window>::handle_events
  13: servo::app::App::handle_events
  14: servo::events_loop::EventsLoop::run_forever::{{closure}}
  15: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}
  16: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
  17: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
  18: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  19: winit::platform_impl::platform::x11::EventLoop<T>::run
  20: winit::platform_impl::platform::EventLoop<T>::run
  21: winit::event_loop::EventLoop<T>::run
  22: servo::app::App::run
  23: servo::main2::main
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::rt::lang_start::{{closure}}
  26: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:20
  27: main
  28: <unknown>
  29: __libc_start_main
  30: _start
[2023-10-04T05:53:36Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/vendors-node_modules_github_filter-input-element_dist_index_js-node_modules_github_remote-inp-b7d8f4-9cf7d828a39b.js:1:16064 IntersectionObserver is not defined
[2023-10-04T05:53:36Z ERROR servo::main2] index out of bounds: the len is 1341 but the index is 1359
[2023-10-04T05:53:36Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/vendors-node_modules_github_file-attachment-element_dist_index_js-node_modules_primer_view-co-821777-b03c18faaa84.js:1:19393 IntersectionObserver is not defined
[2023-10-04T05:53:36Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/marketing-491859bb3d7a.js:1:7662 IntersectionObserver is not defined
[2023-10-04T05:53:36Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/home-0369a2a6b0c5.js:1:121 IntersectionObserver is not defined
called `Option::unwrap()` on a `None` value (thread WRSceneBuilder#0, at third_party/webrender/webrender/src/scene_builder_thread.rs:502)
   0: servo::backtrace::print
   1: servo::main2::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:577:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::panicking::panic
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:114:5
   8: webrender::scene_builder_thread::SceneBuilderThread::process_transaction
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  11: webrender::scene_builder_thread::SceneBuilderThread::run
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys/unix/thread.rs:108:17
  15: <unknown>
  16: <unknown>
[2023-10-04T05:53:36Z ERROR script::dom::bindings::error] Error at https://github.githubassets.com/assets/sessions-04ec2c51e991.js:1:6656 AbortController is not defined
[2023-10-04T05:53:36Z ERROR servo::main2] called `Option::unwrap()` on a `None` value
error receiving image key result: Disconnected (thread <unnamed>, at components/net_traits/lib.rs:844)
   0: servo::backtrace::print
   1: servo::main2::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::result::unwrap_failed
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/result.rs:1790:5
   8: net_traits::WebrenderIpcSender::generate_image_key
   9: net::image_cache::set_webrender_image_key
  10: net::image_cache::ImageCacheStore::complete_load
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys/unix/thread.rs:108:17
  14: <unknown>
  15: <unknown>
[2023-10-04T05:53:36Z ERROR servo::main2] error receiving image key result: Disconnected
called `Result::unwrap()` on an `Err` value: PoisonError { .. } (thread <unnamed>, at components/net/image_cache.rs:640)
   0: servo::backtrace::print
   1: servo::main2::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::result::unwrap_failed
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/result.rs:1790:5
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys/unix/thread.rs:108:17
  11: <unknown>
  12: <unknown>
[2023-10-04T05:53:36Z ERROR servo::main2] called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by mrobinson** [comment]
Thanks for reporting this issue. It looks like a duplicate of #29796 to me.

**Comment by Andy-Python-Programmer** [comment]
Yep https://github.com/servo/servo/commit/ce183d85818e4d9b64f45cc4d7203b1871b3182e, seems to have fixed it. Thanks!
