### ISSUE TITLE
[Error] ImportError to specific package(html5lib)

### ISSUE THREAD

**Issue by MJUCOM** [servo/servo#30531]
I have some problem to process build commend :  `python3.10 ./mach bootstrap `

My environment of python and pip like below :  
```
servo git log : e7c92e962734518972b6bd2c31383333ea4abd16
python : Python 3.10.12 
pip : pip 23.2.1 from /home/dy3199/.local/lib/python3.10/site-packages/pip (python 3.10)
```

However, It generates error to process mach commend:

```
"/home/dy3199/servo/python/_virtualenv3.10/bin/python" "-m" "pip" "install" "-I" "-r" "/home/dy3199/servo/python/requirements.txt" failed with error code 1:
Output:
Error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_vendor/__init__.py)
```

To solve this issue, I reset python3.10 to use commend(`curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10`)
However, it still has problem to use mach commend( python3.10 ./mach bootstrap , python3.10 ./mach build --release)

Is there any solution?? Thank you!
Have a nice day :)

**Comment by mrobinson** [comment]
What happen is you upgrade your installed version of pip?

```
curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
```

**Comment by MJUCOM** [comment]
It upgrade the python3.10 version to use commend(`curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10`)

```
dy3199@s2lab-eval01:~/servo$ curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/50/c2/e06851e8cc28dcad7c155f4753da8833ac06a5c704c109313b8d5a62968a/pip-23.2.1-py3-none-any.whl.metadata
  Using cached pip-23.2.1-py3-none-any.whl.metadata (4.2 kB)
Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.2.1

```

And then if process to build the servo or bootstrap build commend like below, but it still have same ImportError problem.


```
dy3199@s2lab-eval01:~/servo$ python3.10 ./mach bootstrap
"/home/dy3199/servo/python/_virtualenv3.10/bin/python" "-m" "pip" "install" "-I" "-r" "/home/dy3199/servo/python/requirements.txt" failed with error code 1:
Output:
Error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/dy3199/servo/python/_virtualenv3.10/lib/python3.10/site-packages/pip/_vendor/__init__.py)
```

Is there any solution??

**Comment by mrobinson** [comment]
Maybe you can try some of the ideas in https://stackoverflow.com/questions/70431655/importerror-cannot-import-name-html5lib-from-pip-vendor-usr-lib-python3.
