### ISSUE TITLE
'Non floating-type complex?' error when compiling with clang 16

### ISSUE THREAD

**Issue by joshua-holmes** [servo/servo#30587]
I was able to compile fine a month ago, but I pulled the latest code and can't now. I started from scratch and followed the instructions:
1. deleted entire `servo` directory and pulled a fresh one from GitHub master branch
2. made sure my dependencies were installed by running the `./mach bootstrap` command
3. updated to the latest version of rustc nightly (v1.75.0-nightly)
4. ran the `./mach build -d` command

Sadly it still fails. Here are my system specs from `neofetch`:
```
                   -`                    josh@archy 
                  .o+`                   ---------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.5.7-arch1-1 
               `+oooooo:                 Uptime: 6 hours, 7 mins 
               -+oooooo+:                Packages: 1868 (pacman), 8 (flatpak) 
             `/:-:++oooo+:               Shell: bash 5.1.16 
            `/++++/+++++++:              Resolution: 1920x1080 
           `/++++++++++++++:             DE: Hyprland 
          `/+++ooooooooooooo/`           Theme: Gruvbox-Dark-BL [GTK2/3] 
         ./ooosssso++osssssso+`          Icons: Windows-XP [GTK2/3] 
        .oossssso-````/ossssss+`         Terminal: kitty 
       -osssssso.      :ssssssso.        CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
      :osssssss/        osssso+++.       GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
     /ossssssss/        +ssssooo/-       Memory: 3142MiB / 32017MiB 
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:                            
 `++:.                           `-/+/                           
 .`                                 `/
```

Here is an excerpt from running `RUST_BACKTRACE=full ./mach build -d`.
```
  running: "ar" "s" "/home/josh/Development/projects/servo/target/debug/build/mozangle-0388aba21044aa34/out/libangle.a"
  exit status: 0
  cargo:rustc-link-lib=static:-whole-archive=angle
  cargo:rustc-link-search=native=/home/josh/Development/projects/servo/target/debug/build/mozangle-0388aba21044aa34/out
  cargo:rerun-if-env-changed=CXXSTDLIB_x86_64-unknown-linux-gnu
  CXXSTDLIB_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXSTDLIB_x86_64_unknown_linux_gnu
  CXXSTDLIB_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXSTDLIB
  HOST_CXXSTDLIB = None
  cargo:rerun-if-env-changed=CXXSTDLIB
  CXXSTDLIB = None
  cargo:rustc-link-lib=stdc++

  --- stderr
  thread 'main' panicked at 'Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))', /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/context.rs:2020:26
  stack backtrace:
     0:     0x563c7a74785a - std::backtrace_rs::backtrace::libunwind::trace::h0c22b655db076f8f
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x563c7a74785a - std::backtrace_rs::backtrace::trace_unsynchronized::hcdd4102b3a0150ac
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x563c7a74785a - std::sys_common::backtrace::_print_fmt::hf85e841224953c0f
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x563c7a74785a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd24e715ba1140cb
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x563c7a7701de - core::fmt::write::heff0333d94dc3611
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/fmt/mod.rs:1232:17
     5:     0x563c7a7433d5 - std::io::Write::write_fmt::hb2c8997cfd3a0f64
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/io/mod.rs:1682:15
     6:     0x563c7a747625 - std::sys_common::backtrace::_print::hfec2f148629f279f
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x563c7a747625 - std::sys_common::backtrace::print::h4f363203c4b7325a
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x563c7a74902f - std::panicking::default_hook::{{closure}}::h3eafb1e588ec9ebd
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:267:22
     9:     0x563c7a748d6b - std::panicking::default_hook::hc13d68d7c25a30e4
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:286:9
    10:     0x563c7a749799 - std::panicking::rust_panic_with_hook::he1eefea5c8f2ac79
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:688:13
    11:     0x563c7a749539 - std::panicking::begin_panic_handler::{{closure}}::h4bc7f07ca679bf76
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
    12:     0x563c7a747d0c - std::sys_common::backtrace::__rust_end_short_backtrace::h31f73c68c53ad6bd
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
    13:     0x563c7a749242 - rust_begin_unwind
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
    14:     0x563c7a76e2c3 - core::panicking::panic_fmt::hf1444176bba18781
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
    15:     0x563c7a0b046c - bindgen::ir::context::BindgenContext::build_builtin_ty::h9b5a7dc188882cef
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/context.rs:2020:26
    16:     0x563c7a0af2fb - bindgen::ir::context::BindgenContext::builtin_or_resolved_ty::h77d0bcb55424e2f4
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/context.rs:1917:9
    17:     0x563c7a22e651 - bindgen::ir::item::Item::from_ty_or_ref_with_id::h0186c8db841da543
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/item.rs:1535:27
    18:     0x563c7a22e46f - bindgen::ir::item::Item::from_ty_or_ref::h9c54fa931d4a7123
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/item.rs:1498:9
    19:     0x563c7a10c63c - bindgen::ir::function::args_from_ty_and_cursor::{{closure}}::h3d3deb7059f63e7b
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/function.rs:406:20
    20:     0x563c7a0e9935 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h2d16e2dbdc9f432f
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:310:13
    21:     0x563c7a1637b4 - core::option::Option<T>::map::h0667152930eedcbe
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/option.rs:970:29
    22:     0x563c7a1c2afa - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hf90fafe40e272737
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/iter/adapters/map.rs:103:9
    23:     0x563c7a03f41c - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h65d90d5e1c08cc67
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
    24:     0x563c7a06364e - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h4c220029586379b4
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/vec/spec_from_iter.rs:33:9
    25:     0x563c7a061936 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h5ea4dc944de8b183
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/vec/mod.rs:2724:9
    26:     0x563c7a1cc8de - core::iter::traits::iterator::Iterator::collect::he1942f44321c5f2d
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/iter/traits/iterator.rs:1860:9
    27:     0x563c7a10c34c - bindgen::ir::function::args_from_ty_and_cursor::h6682aa8306ef456d
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/function.rs:390:5
    28:     0x563c7a10cbbd - bindgen::ir::function::FunctionSig::from_ty::h8bff3767ee7ff120
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/function.rs:464:17
    29:     0x563c7a1b8cf4 - bindgen::ir::ty::Type::from_clang_ty::h4866a676e7601d31
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/ty.rs:1084:37
    30:     0x563c7a22f8bc - bindgen::ir::item::Item::from_ty_with_id::hb1498601d276f1aa
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/item.rs:1681:22
    31:     0x563c7a22ed75 - bindgen::ir::item::Item::from_ty::heacbc1ee8aa5c46d
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/item.rs:1574:9
    32:     0x563c7a22ce5a - bindgen::ir::item::Item::parse::h98dce9eb944f92fc
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/item.rs:1423:19
    33:     0x563c7a098fee - bindgen::parse_one::h6b0098a47eaada9c
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/lib.rs:1099:11
    34:     0x563c7a0996e9 - bindgen::parse::{{closure}}::{{closure}}::h00997bd1858c0d87
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/lib.rs:1145:47
    35:     0x563c7a1dde29 - bindgen::clang::Cursor::visit_sorted::{{closure}}::he9d5408af10925cd
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/clang.rs:517:17
    36:     0x563c7a1e03aa - bindgen::clang::visit_children::h4cd7148bc4024e73
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/clang.rs:1127:5
    37:     0x7fd49a6055de - <unknown>
    38:     0x7fd49a606ef6 - <unknown>
    39:     0x7fd49a6071a8 - <unknown>
    40:     0x7fd49a60494e - <unknown>
    41:     0x7fd49a607b40 - clang_visitChildren
    42:     0x563c7a40084e - clang_sys::clang_visitChildren::h22d49425c9bf1fb1
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.3.1/src/link.rs:153:17
    43:     0x563c7a1dd38b - bindgen::clang::Cursor::visit::h5885c33db90864f0
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/clang.rs:497:13
    44:     0x563c7a1ddb74 - bindgen::clang::Cursor::visit_sorted::h4eba70ddcfd22efb
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/clang.rs:516:20
    45:     0x563c7a099688 - bindgen::parse::{{closure}}::h1178c7f00d863ad6
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/lib.rs:1145:9
    46:     0x563c7a0b20c5 - bindgen::ir::context::BindgenContext::with_module::h7a7dc890541c0ecc
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/context.rs:2252:9
    47:     0x563c7a099536 - bindgen::parse::h275bd7380fbb6832
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/lib.rs:1144:5
    48:     0x563c7a0960de - bindgen::Bindings::generate::h14550c6b0037aeb8
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/lib.rs:899:13
    49:     0x563c7a093c21 - bindgen::Builder::generate::h2b8e8d8515ae59a6
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/lib.rs:344:9
    50:     0x563c7a038ed9 - build_script_build::build_angle::hc69981a0eaaf5dcf
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/mozangle-0.
4.0/build.rs:253:5
    51:     0x563c7a037c3e - build_script_build::main::h1da9feb5f03e7fc8
                                 at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/mozangle-0.4.0/build.rs:31:5
    52:     0x563c7a03a3bb - core::ops::function::FnOnce::call_once::h85de1e7d57746341
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:250:5
    53:     0x563c7a03777e - std::sys_common::backtrace::__rust_begin_short_backtrace::h7cecdb57bab5fb8d
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:121:18
    54:     0x563c7a036b21 - std::rt::lang_start::{{closure}}::h06ad8a56a94a2d99
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:166:18
    55:     0x563c7a73db7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc7c7c64ba20a055a
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:287:13
    56:     0x563c7a73db7c - std::panicking::try::do_call::h24f98f748a1313dd
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
    57:     0x563c7a73db7c - std::panicking::try::h9bb275b0821d06db
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
    58:     0x563c7a73db7c - std::panic::catch_unwind::h6c1095f6295b379e
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
    59:     0x563c7a73db7c - std::rt::lang_start_internal::{{closure}}::h5751dcc710702ab6
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:48
    60:     0x563c7a73db7c - std::panicking::try::do_call::h8fd8ad02b94dd2c3
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
    61:     0x563c7a73db7c - std::panicking::try::h4e5995cea98a0ac3
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
    62:     0x563c7a73db7c - std::panic::catch_unwind::h9220e61283178032
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
    63:     0x563c7a73db7c - std::rt::lang_start_internal::h1a4a8fb9fce35175
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:20
    64:     0x563c7a036afa - std::rt::lang_start::h20a86c2153905476
                                 at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:165:17
    65:     0x563c7a03967e - main
    66:     0x7fd4a100ccd0 - <unknown>
    67:     0x7fd4a100cd8a - __libc_start_main
    68:     0x563c7a0349c5 - _start
    69:                0x0 - <unknown>
      Timing report saved to /home/josh/Development/projects/servo/target/cargo-timings/cargo-timing-20231019T050730Z.html
Failed in 0:00:34
```

**Comment by mrobinson** [comment]
There is a thread about this issue, which seems to be an issue of bindgen + very new clang libraries on Zulip: https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Building.20Servo.20on.20Arch.20Linux/near/397187821

**Comment by joshua-holmes** [comment]
Thank you for connecting that message @mrobinson! I read the thread and was able to get it to compile. Here are the minimum steps I performed to get it to compile:
- apply the patch to rust's bindgen package from [OrionOth's message](https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Building.20Servo.20on.20Arch.20Linux/near/397431188)
    - to do this, I monkey-patched my bindgen package by editing this file: `~/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.68.1/ir/context.rs`
    - the path might vary slightly for someone else. Also, I made a backup of `bindgen-0.68.1` directory so I can easily revert, if needed
    - finally, I ran `./mach clean` to remove the bindgen package that was already compiled and then `./mach build -d` to build. and it worked!

I'll put this in the chat on ZulipChat also, just in case my minimum steps work for other people too. Also hopefully this gets into a Rust release soon.

**Comment by IlyaBizyaev** [comment]
As far as I understand, this should be resolved with a release of `rust-bindgen` that includes https://github.com/rust-lang/rust-bindgen/commit/d77e53ed8398743bf68831d25063719fa0f4f136

**Comment by delan** [comment]
For anyone waiting on the new bindgen: you can use the fixed version locally by applying the patch below, or alternatively you can try [our new Nix-based dev environment](https://github.com/servo/servo/wiki/Building#nix-on-other-distros), which uses an older version of clang :)
```diff
diff --git a/Cargo.toml b/Cargo.toml
index cb81b83168..21bf47fc08 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -133,6 +133,7 @@ debug-assertions = false
 #
 #     [patch."https://github.com/servo/<repository>"]
 #     <crate> = { path = "/path/to/local/checkout" }
+bindgen = { git = "https://github.com/sagudev/rust-bindgen", branch = "f16" }
 
 # This is required because we want all dependencies that use WebRender to
 # use our vendored version.
```

**Comment by IlyaBizyaev** [comment]
An update for `rust-bindgen` has been released: https://github.com/rust-lang/rust-bindgen/releases/tag/v0.69.2

**Comment by mrobinson** [comment]
> An update for `rust-bindgen` has been released: https://github.com/rust-lang/rust-bindgen/releases/tag/v0.69.2

It does not contain the fix for this issue unfortunately.

**Comment by gasche** [comment]
Note: the upstream bindgen issue is https://github.com/rust-lang/rust-bindgen/pull/2667 , which was merged by commit https://github.com/rust-lang/rust-bindgen/commit/d77e53ed8398743bf68831d25063719fa0f4f136 . It is not included in rust-bindgen 0.69.2 that was released later, and will presumably be part of 0.70 whenever that comes out. (Anyone active in servo could ping the rust-bindgen maintainer to suggest a new release, as was done in https://github.com/rust-lang/rust-bindgen/issues/2209 )

**Comment by yodatak** [comment]
v0.69.4 bindgen is out so i think it must work because it integrate float https://github.com/rust-lang/rust-bindgen/compare/v0.69.2...v0.69.4

**Comment by mrobinson** [comment]
This should be fixed by https://github.com/servo/servo/pull/31306.

**Comment by delan** [comment]
Note that we still need to build Servo with clang 14 for now: #31059
