### ISSUE TITLE
Cookies unit test fail in production profile

### ISSUE THREAD

**Issue by sagudev** [servo/servo#30693]
Run: https://github.com/sagudev/servo/actions/runs/6754545093/job/18362127853#step:13:7162

Excerpt:
```
---- cookie::fn_cookie_constructor stdout ----
thread 'cookie::fn_cookie_constructor' panicked at 'Resource reader not set.', components/shared/embedder/resources.rs:35:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/option.rs:2091:5
   5: embedder_traits::resources::read_bytes
   6: embedder_traits::resources::read_string
   7: std::sys_common::once::futex::Once::call
   8: net_traits::pub_domains::is_pub_domain
   9: net::cookie::Cookie::new_wrapped
  10: main::cookie::fn_cookie_constructor
  11: core::ops::function::FnOnce::call_once
  12: core::ops::function::FnOnce::call_once
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- cookie::test_cookie_eviction_all_secure_new_nonsecure stdout ----
thread 'cookie::test_cookie_eviction_all_secure_new_nonsecure' panicked at 'Once instance has previously been poisoned', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:30:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/panicking.rs:64:14
   2: std::sys_common::once::futex::Once::call
   3: net_traits::pub_domains::is_pub_domain
   4: net::cookie::Cookie::new_wrapped
   5: net::cookie::Cookie::from_cookie_string
   6: main::cookie::add_retrieve_cookies
   7: main::cookie::test_cookie_eviction_all_secure_new_nonsecure
   8: core::ops::function::FnOnce::call_once
   9: core::ops::function::FnOnce::call_once
             at /rustc/13afbdaa0655dda23d7129e59ac48f1ec88b2084/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by sagudev** [comment]
Just did new run on all platforms: https://github.com/sagudev/servo/actions/runs/6773834072 and not only cookie test fail:
> 135 passed; 290 failed

failures https://github.com/sagudev/servo/actions/runs/6773834072/job/18409578570#step:10:19846

cc @delan

**Comment by sagudev** [comment]
Currently we done unit-test always in debug mode (when release flag was passed it was ignored, but `--profile production` was not ignored). I try to deal with this in #30707
