### ISSUE TITLE
No new nightly builds?

### ISSUE THREAD

**Issue by atouchet** [servo/servo#30835]
https://github.com/servo/servo-nightly-builds

Latest build on GitHub and servo.org is from two days ago. Have nightly versions stopped being built?

**Comment by atouchet** [comment]
This doesn't appear to have been fixed.

**Comment by sagudev** [comment]
Now t here is problem in bootstrap: 
```
Downloading mozlog-8.0.0.tar.gz (53 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/runner/work/servo/servo/python/_venv3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hs4k9c1i/mozlog/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hs4k9c1i/mozlog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hs4k9c1i/mozlog/pip-egg-info
         cwd: /tmp/pip-install-hs4k9c1i/mozlog/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hs4k9c1i/mozlog/setup.py", line 17, in <module>
        setup(
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
        return distutils.core.setup(**attrs)
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 303, in __init__
        _Distribution.__init__(self, dist_attrs)
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
        self.finalize_options()
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 679, in finalize_options
        for ep in sorted(loaded, key=by_order):
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 678, in <lambda>
        loaded = map(lambda e: e.load(), filtered)
      File "/home/runner/work/servo/servo/python/_venv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 210, in load
        return functools.reduce(getattr, attrs, module)
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
"/home/runner/work/servo/servo/python/_venv3.8/bin/python" "-m" "pip" "install" "-I" "-r" "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/requirements.txt" failed with error code 1:
Output:
Error:
```

Upgrading python might fix it.

**Comment by mrego** [comment]
It seems nightly builds are back to https://servo.org/download/

**Comment by sagudev** [comment]
> It seems nightly builds are back to https://servo.org/download/

This is from https://github.com/servo/servo/pull/30848 test run.
