### ISSUE TITLE
Cannot import name 'Github' from github

### ISSUE THREAD

**Issue by kallisti5** [servo/servo#30986]
```
/Data/servo> rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03)

/Data/servo> uname -a
Haiku shredder 1 hrev57492 Dec 31 2023 07:15:48 x86_64 x86_64 Haiku

/Data/servo> ./mach build --dev
Traceback (most recent call last):
  File "/Data/servo/./mach", line 46, in <module>
    main(sys.argv)
  File "/Data/servo/./mach", line 27, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/Data/servo/python/mach_bootstrap.py", line 263, in bootstrap
    mach.load_commands_from_file(os.path.join(topdir, path), module_name)
  File "/Data/servo/python/mach/mach/main.py", line 262, in load_commands_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Data/servo/python/servo/package_commands.py", line 11, in <module>
    from github import Github
ImportError: cannot import name 'Github' from 'github' (/packages/python3.10-3.10.13-1/.self/non-packaged/lib/python3.10/site-packages/github/__init__.py)


/Data/servo> cat /packages/python3.10-3.10.13-1/.self/non-packaged/lib/python3.10/site-packages/github/__init__.py 
# == __init__.py ==#

__title__ = 'Github-Api-Wrapper'
__authors__ = 'VarMonke', 'sudosnok'
__version__ = '1.2.7'
__license__ = 'MIT'
__copyright__ = 'Copyright (c) 2022-present VarMonke & sudosnok'

from .client import *
from .exceptions import *
from .http import *
from .objects import *
from .urls import *
```

**Comment by kallisti5** [comment]
I should note, the error above is after ```pip3 install github``` to solve...

```
> ./mach build --dev
Traceback (most recent call last):
  File "/Data/servo/./mach", line 46, in <module>
    main(sys.argv)
  File "/Data/servo/./mach", line 27, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/Data/servo/python/mach_bootstrap.py", line 263, in bootstrap
    mach.load_commands_from_file(os.path.join(topdir, path), module_name)
  File "/Data/servo/python/mach/mach/main.py", line 262, in load_commands_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Data/servo/python/servo/package_commands.py", line 11, in <module>
    from github import Github
ModuleNotFoundError: No module named 'github'
```

**Comment by mrobinson** [comment]
The package you need isn't `github`, but `PyGithub`. You shouldn't need to install anything as `./mach bootstrap` should install the package in the venv.

Are you trying to build on Haiku? We do not support that platform.

**Comment by mrobinson** [comment]
I'd be happy to review pull requests that address issues building on Haiku, especially if folks are willing to help maintain this build. I definitely don't have time to track and fix issues with this build though. Sorry!

**Comment by kallisti5** [comment]
No worries!  If you're ok accepting Haiku PR's i'll see what I can do.  Thanks for clearifying PyGithub though... that wasn't obvious.

Thanks!
