### ISSUE TITLE
rustc_ast

### ISSUE THREAD

**Issue by WebReflection** [servo/servo#31683]
I just followed the instructions and this happened:

```
 * Installing crown (the Servo linter)...
  Installing crown v0.1.0 (/home/ag/git/servo/support/crown)
   Compiling crown v0.1.0 (/home/ag/git/servo/support/crown)
error[E0463]: can't find crate for `rustc_ast`
  --> support/crown/src/main.rs:10:1
   |
10 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_driver`
  --> support/crown/src/main.rs:11:1
   |
11 | extern crate rustc_driver;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_error_messages`
  --> support/crown/src/main.rs:12:1
   |
12 | extern crate rustc_error_messages;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_hir`
  --> support/crown/src/main.rs:13:1
   |
13 | extern crate rustc_hir;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_infer`
  --> support/crown/src/main.rs:14:1
   |
14 | extern crate rustc_infer;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_interface`
  --> support/crown/src/main.rs:15:1
   |
15 | extern crate rustc_interface;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_lint`
  --> support/crown/src/main.rs:16:1
   |
16 | extern crate rustc_lint;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_middle`
  --> support/crown/src/main.rs:17:1
   |
17 | extern crate rustc_middle;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_session`
  --> support/crown/src/main.rs:18:1
   |
18 | extern crate rustc_session;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_span`
  --> support/crown/src/main.rs:19:1
   |
19 | extern crate rustc_span;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_trait_selection`
  --> support/crown/src/main.rs:20:1
   |
20 | extern crate rustc_trait_selection;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_type_ir`
  --> support/crown/src/main.rs:21:1
   |
21 | extern crate rustc_type_ir;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error: cannot determine resolution for the macro `declare_tool_lint`
  --> support/crown/src/unrooted_must_root.rs:17:1
   |
17 | declare_tool_lint! {
   | ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `declare_tool_lint`
  --> support/crown/src/trace_in_no_trace.rs:19:1
   |
19 | declare_tool_lint! {
   | ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `declare_tool_lint`
  --> support/crown/src/trace_in_no_trace.rs:25:1
   |
25 | declare_tool_lint! {
   | ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `declare_lint`
 --> support/crown/src/crown_is_not_used.rs:8:1
  |
8 | declare_lint! {
  | ^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
  --> support/crown/src/unrooted_must_root.rs:25:34
   |
25 |     lint_store.register_lints(&[&UNROOTED_MUST_ROOT]);
   |                                  ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
   --> support/crown/src/unrooted_must_root.rs:192:25
    |
192 |                         UNROOTED_MUST_ROOT,
    |                         ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
   --> support/crown/src/unrooted_must_root.rs:215:33
    |
215 | ...                   UNROOTED_MUST_ROOT,
    |                       ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
   --> support/crown/src/unrooted_must_root.rs:250:29
    |
250 |                     cx.lint(UNROOTED_MUST_ROOT, "Type must be rooted", |lint| {
    |                             ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
   --> support/crown/src/unrooted_must_root.rs:259:25
    |
259 |                 cx.lint(UNROOTED_MUST_ROOT, "Type must be rooted", |lint| {
    |                         ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
   --> support/crown/src/unrooted_must_root.rs:290:21
    |
290 |                     UNROOTED_MUST_ROOT,
    |                     ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `UNROOTED_MUST_ROOT` in this scope
   --> support/crown/src/unrooted_must_root.rs:332:25
    |
332 |                         UNROOTED_MUST_ROOT,
    |                         ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `TRACE_IN_NO_TRACE` in this scope
  --> support/crown/src/trace_in_no_trace.rs:37:34
   |
37 |     lint_store.register_lints(&[&TRACE_IN_NO_TRACE, &EMPTY_TRACE_IN_NO_TRACE]);
   |                                  ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `EMPTY_TRACE_IN_NO_TRACE` in this scope
  --> support/crown/src/trace_in_no_trace.rs:37:54
   |
31 | / const EMPTY_TRACE_IN_NO_TRACE_MSG: &str =
32 | |     "must_not_have_traceable marked wrapper is not needed for types that implements \
33 | | empty Traceable (like primitive types). Consider removing the wrapper.";
   | |________________________________________________________________________- similarly named constant `EMPTY_TRACE_IN_NO_TRACE_MSG` defined here
...
37 |       lint_store.register_lints(&[&TRACE_IN_NO_TRACE, &EMPTY_TRACE_IN_NO_TRACE]);
   |                                                        ^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `EMPTY_TRACE_IN_NO_TRACE_MSG`

error[E0425]: cannot find value `EMPTY_TRACE_IN_NO_TRACE` in this scope
   --> support/crown/src/trace_in_no_trace.rs:135:29
    |
31  | / const EMPTY_TRACE_IN_NO_TRACE_MSG: &str =
32  | |     "must_not_have_traceable marked wrapper is not needed for types that implements \
33  | | empty Traceable (like primitive types). Consider removing the wrapper.";
    | |________________________________________________________________________- similarly named constant `EMPTY_TRACE_IN_NO_TRACE_MSG` defined here
...
135 |                               EMPTY_TRACE_IN_NO_TRACE,
    |                               ^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `EMPTY_TRACE_IN_NO_TRACE_MSG`

error[E0425]: cannot find value `TRACE_IN_NO_TRACE` in this scope
   --> support/crown/src/trace_in_no_trace.rs:141:29
    |
141 | ...                   TRACE_IN_NO_TRACE,
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `CROWN_IS_NOT_USED` in this scope
  --> support/crown/src/crown_is_not_used.rs:15:34
   |
15 |     lint_store.register_lints(&[&CROWN_IS_NOT_USED]);
   |                                  ^^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0463.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `crown` (bin "crown") due to 28 previous errors
error: failed to compile `crown v0.1.0 (/home/ag/git/servo/support/crown)`, intermediate artifacts can be found at `/home/ag/git/servo/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Traceback (most recent call last):
  File "/home/ag/git/servo/./mach", line 48, in <module>
    main(sys.argv)
  File "/home/ag/git/servo/./mach", line 25, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ag/git/servo/python/mach_bootstrap.py", line 201, in bootstrap_command_only
    servo.platform.get().bootstrap('-f' in sys.argv or '--force' in sys.argv)
  File "/home/ag/git/servo/python/servo/platform/base.py", line 59, in bootstrap
    installed_something |= self.install_crown(force)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ag/git/servo/python/servo/platform/base.py", line 77, in install_crown
    raise EnvironmentError("Installation of crown failed.")
OSError: Installation of crown failed.
[ag@archibold servo]$ can't find crate for `rustc_ast`
```

The bottom line is that this throws even on AUR (ArchLinux here) on the [servo-git](https://aur.archlinux.org/packages/servo-git) package:

```
error: could not execute process `crown -vV` (never executed)
```

Is this a thing caused by the fact I won't install a different rust toolchain as that gave me tons of warnings about not being desired when another (official) rust already landed on my machine?

Thank You!

**Comment by WebReflection** [comment]
right ... [I ended up here](https://www.rust-lang.org/tools/install) and forced-thinged the thingy so now it works, apologies for the noise ... I wonder why that's not a default though, but that's another story 👋
