### ISSUE TITLE
skipped test output is broken 

### ISSUE THREAD

**Issue by jdm** [servo/servo#33184]
```
mozlog.structuredlog: Failure calling log handler:
Traceback (most recent call last):
  File "/home/runner/work/servo/servo/python/_venv3.10/lib/python3.10/site-packages/mozlog/structuredlog.py", line 313, in _handle_log
    handler(data)
  File "/home/runner/work/servo/servo/python/_venv3.10/lib/python3.10/site-packages/mozlog/handlers/base.py", line 74, in __call__
    formatted = self.formatter(data)
  File "/home/runner/work/servo/servo/python/_venv3.10/lib/python3.10/site-packages/mozlog/handlers/base.py", line 42, in __call__
    return self.inner(item)
  File "/home/runner/work/servo/servo/python/_venv3.10/lib/python3.10/site-packages/mozlog/reader.py", line 72, in __call__
    return handler(data)
  File "/home/runner/work/servo/servo/python/wpt/grouping_formatter.py", line 309, in test_end
    lines = [f"SKIP {data['test']}", f"{data['message']}\n"]
KeyError: 'message'
```
From CI logs.

**Comment by sagudev** [comment]
Introduced by 0afcb83e9f13bdaeb0ef01b4809ed298b9f24ac0.
