### ISSUE TITLE
RenderTask panicked at 'called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by zoonman** [servo/servo#4034]
OS X 10.9.5 (13F34)

```
   Darwin philmms.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
```

Crash report:

```
    philmms:servo zoonman$ ./mach run -g -t 4 -i  http://marketmesuite.com/login
ERROR:js::rust: Error at http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js:1: TypeError: j is undefined

ERROR:js::rust: Error at http://marketmesuite.com/l/assets/module/main-build.js?v=1:2: TypeError: r.style is undefined

task 'RenderTask' panicked at 'called `Option::unwrap()` on a `None` value', /Users/jack/src/rust/src/libcore/option.rs:347
task '<unnamed>' panicked at 'receiving on a closed channel', /Users/jack/src/rust/src/libsync/comm/mod.rs:835
task 'LayoutTask' panicked at 'RenderChan.send: render port closed', render_task.rs:90
task 'ScriptTask' panicked at 'receiving on a closed channel', /Users/jack/src/rust/src/libsync/comm/mod.rs:835
task 'ScriptTask' panicked at 'sending on a closed channel', /Users/jack/src/rust/src/libsync/comm/mod.rs:571
stack backtrace:
   1:        0x10edc280f - rt::backtrace::imp::write::h298e9a24ace789eapjq
   2:        0x10edc5d53 - failure::on_fail::h7c66d5e44af7228beAq
   3:        0x10edd9205 - unwind::begin_unwind_inner::he450059582cbe456MJd
   4:        0x10edd8e4f - unwind::begin_unwind_fmt::h4dc90f262f1a5aa2eHd
   5:        0x10edd8bf2 - rust_begin_unwind
   6:        0x10edf8bdc - panicking::panic_fmt::haaad4a2be0412d03x7j
   7:        0x10edf876f - panicking::panic::h68a5c57451296fc4B4j
   8:        0x10e391c4b - comm::Sender<T>::send::h1776240922858710908
   9:        0x10e3b6b14 - dom::node::Node::reap_layout_data::h1db5a481c29daf25669
  10:        0x10e059e5a - dom::node::Node.Drop::drop::hfef4f5af7ca08010uv8
  11:        0x10e059dbe - dom..node..Node::glue_drop.64936::h73b421e9670f6085
  12:        0x10e059d36 - dom..characterdata..CharacterData::glue_drop.64933::hb0147d8eafe10b55
  13:        0x10e2569de - dom..text..Text::glue_drop.73945::h511730b18b2284c9
  14:        0x10e25698c - Box<dom..text..Text>::glue_drop.73942::hd732636cb85caa3a
  15:        0x10e2566c2 - dom::bindings::codegen::Bindings::TextBinding::_finalize::__rust_abi
  16:        0x10e256602 - dom::bindings::codegen::Bindings::TextBinding::_finalize::h1f8e62da5ca8cfcbCpx
  17:        0x10e68c699 - _ZN2js2gcL14FinalizeArenasEPNS_6FreeOpEPPNS0_11ArenaHeaderERNS0_9ArenaListENS0_9AllocKindERNS_11SliceBudgetE
  18:        0x10e68d8ef - _ZN2js2gc10ArenaLists20queueObjectsForSweepEPNS_6FreeOpE
  19:        0x10e69261f - _ZL23IncrementalCollectSliceP9JSRuntimexN2js8gcreason6ReasonENS1_18JSGCInvocationKindE
  20:        0x10e690e19 - _ZL7GCCycleP9JSRuntimebxN2js18JSGCInvocationKindENS1_8gcreason6ReasonE
  21:        0x10e68ee19 - _ZL7CollectP9JSRuntimebxN2js18JSGCInvocationKindENS1_8gcreason6ReasonE
  22:        0x10e665545 - _ZN2js14DestroyContextEP9JSContextNS_18DestroyContextModeE
  23:        0x10e58b7e5 - rust::Cx.Drop::drop::h0db2a0af39ab3c0fRHc
  24:        0x10e0b5a22 - js..rust..Cx::glue_drop.66681::h0f40d3676df2170d
  25:        0x10e0b5757 - rc::Rc<T>.Drop::drop::h6918874517699102824
  26:        0x10e0b561e - alloc..rc..Rc<js..rust..Cx>::glue_drop.66678::h916336c57be59ab1
  27:        0x10e1bf1e5 - page..JSPageInfo::glue_drop.71600::h5c710c65b7e7e12f
  28:        0x10e1bf1a6 - core..option..Option<page..JSPageInfo>::glue_drop.71597::h6d9494364c97d6cb
  29:        0x10e4d7d98 - script_task::ScriptMemoryFailsafe<'a>.Drop::drop::hc3bee234cba4dcfeAqh
  30:        0x10da25fb6 - script..script_task..ScriptMemoryFailsafe<'_>::glue_drop.10861::hb2e6c06db59817c1
  31:        0x10da0bba3 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10067
  32:        0x10eb20fc2 - rtinstrument::instrument::ha6729a754c03086b3Yd
  33:        0x10d9f194b - task::spawn_named_with_send_on_failure::closure.9543
  34:        0x10da07936 - task::TaskBuilder<S>::try_future::closure.9959
  35:        0x10ecabeed - task::NativeSpawner.Spawner::spawn::closure.8532
  36:        0x10edd9d2c - rust_try_inner
  37:        0x10edd9d16 - rust_try
  38:        0x10edd6f77 - unwind::try::h919714955bbeaccbuyd
  39:        0x10edd6e4c - task::Task::run::hea91e954c6decde6hKc
  40:        0x10ecabd13 - task::NativeSpawner.Spawner::spawn::closure.8469
  41:        0x10edd8137 - thread::thread_start::h0e052142e72d7915w5c
  42:     0x7fff84469899 - _pthread_body
  43:     0x7fff8446972a - _pthread_struct_init
task failed during unwinding. aborting.
Error running mach:

    ['run', '-g', '-t', '4', '-i', 'http://marketmesuite.com/login']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'target/servo', '-g', '-t', '4', '-i', 'http://marketmesuite.com/login']' returned non-zero exit status -4

  File "/Users/zoonman/www/tmp/servo/python/servo/post_build_commands.py", line 30, in run
    env=self.build_env())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 504, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by jdm** [comment]
I can't reproduce this any more, and lots of the relevant code has changed in very significant ways.
