### ISSUE TITLE
Crash dropping native surface on twitter.com

### ISSUE THREAD

**Issue by jdm** [servo/servo#4517]
STR:
load www.twitter.com

```
Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to process 2670 thread 0xc907]
0x00007fff89bed4c4 in CFRelease ()
(gdb) bt
#0  0x00007fff89bed4c4 in CFRelease ()
#1  0x00000001014ec78f in _ZN10io_surface14IOSurface.Drop4dropE (self=0x11d9fc610) at lib.rs:64
#2  0x00000001014e00c6 in io_surface..IOSurface::glue_drop.7385::h6799ff85bf9f0af1 () at <std macros>:8
#3  0x00000001014ea4ef in _ZN6layers8platform5macos7surface34NativeSurface.NativeSurfaceMethods6uploadE (self=0x116c27900, data={data_ptr = 0x10790d9f0 "", length = 0}) at surface.rs:213
#4  0x0000000100f3853e in fn"fn"(14395) (data={data_ptr = 0x10790d9f0 "", length = 0}) at paint_task.rs:553
#5  0x00000001012fe115 in slice::raw::buf_as_slice::h10693748271806363923 () at <std macros>:8
#6  0x00000001012fdfa8 in _ZN5azure8azure_hl17DataSourceSurface9with_dataE (self=0x11d9fc980, f={void (struct &[u8])} 0x11d9fc878) at azure_hl.rs:874
#7  0x0000000100f34723 in _ZN3gfx10paint_task12WorkerThread36create_layer_buffer_for_painted_tileE (self=0x11d9fcc58, tile=0x11d9fcaf0, layer_buffer={RUST$ENCODED$ENUM$0$None = {0x0}}, draw_target={azure_draw_target = 0x10790d900, data = {{RUST$ENUM$DISR = core::option::None}, {RUST$ENUM$DISR = core::option::None, {_ptr = 0x0}}}, skia_context = {{RUST$ENUM$DISR = core::option::None}, {RUST$ENUM$DISR = core::option::None, 0x0}}}, scale=2) at paint_task.rs:552
#8  0x0000000100f2284a in _ZN3gfx10paint_task12WorkerThread4mainE (self=0x11d9fcc58) at paint_task.rs:476
#9  0x0000000100f22152 in fn"fn"(13998) () at paint_task.rs:416
#10 0x00000001012d68bd in task::NativeSpawner.Spawner::spawn::closure.2481 ()
#11 0x000000010170bcfc in rust_try_inner ()
#12 0x0000000101708fbc in task::Task::run::h7b157ac3b133c93aS2b ()
#13 0x00000001012d66e3 in task::NativeSpawner.Spawner::spawn::closure.2405 ()
#14 0x000000010170a167 in thread::thread_start::hc61b1801c678e684Ync ()
#15 0x00007fff87ec0899 in _pthread_body ()
#16 0x00007fff87ec072a in _pthread_start ()
#17 0x00007fff87ec4fc9 in thread_start ()
```

**Comment by sviter** [comment]
Is it still valid?

**Comment by jdm** [comment]
No; all the graphics code was rewritten.
