### ISSUE TITLE
LayoutTask unwraps None value

### ISSUE THREAD

**Issue by jdm** [servo/servo#4563]
https://www.chillingeffects.org/notices/10275257# yields `task 'LayoutTask' panicked at 'called `Option::unwrap()` on a `None` value', /Users/larsberg/rust/src/libcore/option.rs:356`

**Comment by mttr** [comment]
I'm not sure if the underlying problem is fixed or not, but that link works for me on the latest master.

**Comment by jdm** [comment]
I feel a bit silly that I didn't include the backtrace :<

**Comment by jdm** [comment]
```
godot2:servo jdm$ ./mach run https://www.chillingeffects.org/notices/10275257#
thread 'LayoutWorker worker 6/6' panicked at 'called `Option::unwrap()` on a `None` value', /Users/larsberg/rust/src/libcore/option.rs:362
stack backtrace:
   1:        0x101a37097 - sys::backtrace::write::h3b4873bcf313d3b3uvy
   2:        0x101a4d003 - failure::on_fail::h3f7c39a5b3cedd4cdOF
   3:        0x101a19e78 - rt::unwind::begin_unwind_inner::hdfd918fd87b731b6FvF
   4:        0x101a1a5e1 - rt::unwind::begin_unwind_fmt::h2b939bfe8195c6debuF
   5:        0x101a4c9fe - rust_begin_unwind
   6:        0x101a6f707 - panicking::panic_fmt::h2e5db15731ca5e85yow
   7:        0x101a6edb2 - panicking::panic::hf2146cf95c33cd06Bmw
   8:        0x10107f2bb - option::Option<T>::unwrap::h1285818116853674192
   9:        0x10107edb9 - text::glyph::is_simple_advance::ha32f5c5121f9d0abREf
  10:        0x1010863d3 - text::glyph::GlyphStore::add_glyph_for_char_index::glyph_is_compressible::h94d717728c3d78e4Yrg
  11:        0x101086091 - text::glyph::GlyphStore::add_glyph_for_char_index::h3453d9981924da77Crg
  12:        0x10108df7b - text::shaping::harfbuzz::Shaper::save_glyph_results::ha467835d80eef36dU9g
  13:        0x1010102ce - text::shaping::harfbuzz::Shaper.ShaperMethods::shape_text::hea357f1f925f0c6eV7g
  14:        0x10100cd50 - font::Font::shape_text::h9b8a3c78c02b8974gUd
  15:        0x1010937c9 - text::text_run::TextRun::break_and_shape::hf14a602583d40afevZh
  16:        0x101019230 - text::text_run::TextRun::new::he3a91cc5769d095dIYh
  17:        0x1008249ae - text::TextRunScanner::flush_clump_to_list::h298f87f53ed3f765iMq
  18:        0x10067f676 - text::TextRunScanner::scan_for_runs::h02cd3160e283dbebDIq
  19:        0x10068989a - construct::FlowConstructor<'a>::build_flow_for_block_starting_with_fragment::h1cf61309bdf83c5arjd
  20:        0x10068f330 - construct::FlowConstructor<'a>::build_flow_for_block::hffc90a1d57d8b062hmd
  21:        0x10069172e - construct::FlowConstructor<'a>::build_flow_for_nonfloated_block::h64220303f99907d3Und
  22:        0x10068b3f3 - construct::FlowConstructor<'a>.PostorderNodeMutTraversal::process::h077d5421a3133f50CQd
  23:        0x100689323 - construct::FlowConstructor<'a>::build_flow_for_block_starting_with_fragment::h1cf61309bdf83c5arjd
  24:        0x10068f330 - construct::FlowConstructor<'a>::build_flow_for_block::hffc90a1d57d8b062hmd
  25:        0x10069172e - construct::FlowConstructor<'a>::build_flow_for_nonfloated_block::h64220303f99907d3Und
  26:        0x10068d62f - construct::FlowConstructor<'a>.PostorderNodeMutTraversal::process::h077d5421a3133f50CQd
  27:        0x100812851 - traversal::ConstructFlows<'a>.PostorderDomTraversal::process::h96f038b8bf3f3e13skr
  28:        0x1008125cb - parallel::ParallelPostorderDomTraversal::run_parallel::h9012991433927543202
  29:        0x1008124fe - parallel::construct_flows::hdee2f6e9b861a792S9n
  30:        0x1008117f8 - parallel::RecalcStyleForNode<'a>.ParallelPreorderDomTraversal::run_parallel::h33bf6d49f6e7cdd3G8n
  31:        0x10081244e - parallel::recalc_style::h938c0c0cdc6386efb9n
  32:        0x1007bcb10 - workqueue::WorkerThread<QueueData, WorkData>::start::h7080364904056637261
  33:        0x1007bc3e3 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.31052
  34:        0x1007bc071 - task::spawn_named::closure.31045
  35:        0x1007bbf44 - thunk::Thunk<(), R>::new::closure.31041
  36:        0x1007bbe0d - thunk::F.Invoke<A, R>::invoke::h12250987527000033781
  37:        0x1006f9481 - thunk::Thunk<A, R>::invoke::h9940435265896837600
  38:        0x1006fa1ba - thread::Builder::spawn_inner::closure.28144
  39:        0x1006fa13f - rt::unwind::try::try_fn::__rust_abi::h7984379530504870261
  40:        0x1006fa0da - rt::unwind::try::try_fn::h7984379530504870261
  41:        0x101a4e9e9 - rust_try_inner
  42:        0x101a4e9d6 - rust_try
  43:        0x1006f95cc - rt::unwind::try::h12947530630962226871
  44:        0x1006f830f - thread::Builder::spawn_inner::closure.28042
  45:        0x1006fb1f9 - thunk::Thunk<(), R>::new::closure.28168
  46:        0x1006fb0e1 - thunk::F.Invoke<A, R>::invoke::h12244828050685914734
  47:        0x101a3aac3 - sys::thread::thread_start::h5b7d5c87e4ddcba2hDB
  48:     0x7fff87f82899 - _pthread_body
  49:     0x7fff87f8272a - _pthread_struct_init
```

**Comment by jdm** [comment]
Looks like #4614.
