### ISSUE TITLE
Test failures against Master

### ISSUE THREAD

**Issue by chotchki** [servo/servo#4701]
The following tests failed when building against revision: 94ebc7c32d5ce58ada3f9d8ffdb60cc025eb5997 on Mac OSX

```
---- acid2_noscroll.html == acid2_ref_broken.html stdout ----
	task 'acid2_noscroll.html == acid2_ref_broken.html' panicked at 'rendering difference: /tmp/servo-reftest-000098-diff.png', ../../tests/reftest.rs:337


---- block_formatting_context_complex_a.html == block_formatting_context_complex_ref.html stdout ----
	task 'block_formatting_context_complex_a.html == block_formatting_context_complex_ref.html' panicked at 'rendering difference: /tmp/servo-reftest-000136-diff.png', ../../tests/reftest.rs:337


---- floated_table_with_margin_a.html == floated_table_with_margin_ref.html stdout ----
	task 'floated_table_with_margin_a.html == floated_table_with_margin_ref.html' panicked at 'rendering difference: /tmp/servo-reftest-000134-diff.png', ../../tests/reftest.rs:337


---- linebreak_simple_a.html == linebreak_simple_b.html stdout ----
	task 'linebreak_simple_a.html == linebreak_simple_b.html' panicked at 'rendering difference: /tmp/servo-reftest-000079-diff.png', ../../tests/reftest.rs:337


---- minimum_line_height_a.html == minimum_line_height_b.html stdout ----
	task 'minimum_line_height_a.html == minimum_line_height_b.html' panicked at 'rendering difference: /tmp/servo-reftest-000068-diff.png', ../../tests/reftest.rs:337


---- position_fixed_tile_edge.html == position_fixed_tile_edge_ref.html stdout ----
	task 'position_fixed_tile_edge.html == position_fixed_tile_edge_ref.html' panicked at 'assertion failed: `(left == right) && (right == left)` (left: `exit code: 1`, right: `exit code: 0`)', ../../tests/reftest.rs:286


---- vertical-lr-blocks.html == vertical-lr-blocks_ref.html stdout ----
	task 'vertical-lr-blocks.html == vertical-lr-blocks_ref.html' panicked at 'rendering difference: /tmp/servo-reftest-000087-diff.png', ../../tests/reftest.rs:337



failures:
    acid2_noscroll.html == acid2_ref_broken.html
    block_formatting_context_complex_a.html == block_formatting_context_complex_ref.html
    floated_table_with_margin_a.html == floated_table_with_margin_ref.html
    linebreak_simple_a.html == linebreak_simple_b.html
    minimum_line_height_a.html == minimum_line_height_b.html
    position_fixed_tile_edge.html == position_fixed_tile_edge_ref.html
    vertical-lr-blocks.html == vertical-lr-blocks_ref.html

test result: FAILED. 204 passed; 7 failed; 0 ignored; 0 measured
```

**Comment by jdm** [comment]
With each of these, you can run Servo against the two html files and compare the output visually.

**Comment by dancek** [comment]
Interestingly, I have a different set of failures on the same commit (94ebc7c). This is on OS X 10.10 (14A389), MacbookPro11,3. I ran with `./mach test-ref --cpu`.

```
failures:
    acid2_noscroll.html == acid2_ref_broken.html
    block_formatting_context_complex_a.html == block_formatting_context_complex_ref.html
    float_table_a.html == float_table_ref.html
    floated_table_with_margin_a.html == floated_table_with_margin_ref.html
    iframe/multiple_external.html == iframe/multiple_external_ref.html
    line_height_a.html == line_height_ref.html
    linear_gradients_corners_a.html != linear_gradients_corners_ref.html
    linear_gradients_lengths_a.html == linear_gradients_lengths_ref.html
    linear_gradients_parsing_a.html == linear_gradients_parsing_ref.html
    linebreak_inline_span_a.html == linebreak_inline_span_b.html
    linebreak_simple_a.html == linebreak_simple_b.html
    minimum_line_height_a.html == minimum_line_height_b.html
    negative_margin_uncle_a.html == negative_margin_uncle_b.html
    outlines_simple_a.html == outlines_simple_ref.html
    outlines_wrap_a.html == outlines_wrap_ref.html
    pre_ignorable_whitespace_a.html == pre_ignorable_whitespace_ref.html
    pseudo_element_a.html == pseudo_element_b.html
    pseudo_inherit.html == pseudo_inherit_ref.html

test result: FAILED. 193 passed; 18 failed; 0 ignored; 0 measured
```

**Comment by nox** [comment]
I'm pretty sure this can be closed.
