### ISSUE TITLE
Haven't been able to run servo in quite some time

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#4763]
It's been a month or so since I've been able to run anything with servo. I'm running on OS X Yosemite.

Here's the error I always get:

```
~/D/servo (master|…) $ ./mach run google.com
thread 'ScriptTask' panicked at 'Failed to load page URL file:///Users/coreyf/Development/servo/google.com, error: couldn't open path as file', parse/html.rs:197
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x10367c5fc - parse::html::parse_html::h52da017ce940b1b1UMB
   6:        0x1038b148e - script_task::ScriptTask::load::hbfc77695c0517ff9vkD
   7:        0x1038adf11 - script_task::ScriptTask::handle_msg_from_constellation::h56f0d54c481cb1f4s5C
   8:        0x10388ade4 - script_task::ScriptTask::handle_msgs::h23743985783bd861JYC
   9:        0x1038892d2 - script_task::ScriptTask::start::h4a3df697ce6b5f0ayYC
  10:        0x102cfde5e - script_task::ScriptTask.ScriptTaskFactory::create::unboxed_closure.10458
  11:        0x102cfd382 - task::spawn_named_with_send_on_failure::unboxed_closure.10445
  12:        0x102cfd28c - thunk::Thunk<(*, R>::new::unboxed_closure.10441
  13:        0x102cfd187 - thunk::F.Invoke<A, R>::invoke::h13258011375681503481
  14:        0x102c2cc51 - thunk::Thunk<A, R>::invoke::h1758463329604743876
  15:        0x102c2d99a - thread::Builder::spawn_inner::unboxed_closure.5345
  16:        0x102c2d91f - rt::unwind::try::try_fn::__rust_abi::h5564697778693967227
  17:        0x102c2d8ba - rt::unwind::try::try_fn::h5564697778693967227
  18:        0x104400d59 - rust_try_inner
  19:        0x104400d46 - rust_try
  20:        0x102c2cda0 - rt::unwind::try::h13219397950734276130
  21:        0x102c2b9cd - thread::Builder::spawn_inner::unboxed_closure.5194
  22:        0x102c2eac9 - thunk::Thunk<(*, R>::new::unboxed_closure.5368
  23:        0x102c2e9b1 - thunk::F.Invoke<A, R>::invoke::h4744309663374176267
  24:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  25:     0x7fff872eb268 - _pthread_body
  26:     0x7fff872eb1e5 - _pthread_body
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "sending on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x1030111f5 - result::Result<T, E>::unwrap::h13455818682184793124
   8:        0x10301994b - pipeline::Pipeline::force_exit::h8bbe31e4214bc69eITc
   9:        0x102cc95ed - constellation::Constellation<LTF, STF>::handle_failure_msg::h14971924396988203939
  10:        0x102cbabb5 - constellation::Constellation<LTF, STF>::handle_request::h495971980260084567
  11:        0x102cb5696 - constellation::Constellation<LTF, STF>::run::h5741696414501774391
  12:        0x102c90511 - constellation::Constellation<LTF, STF>::start::unboxed_closure.7133
  13:        0x102c8f71c - task::spawn_named::unboxed_closure.7126
  14:        0x102c8f62c - thunk::Thunk<(*, R>::new::unboxed_closure.7122
  15:        0x102c8f52a - thunk::F.Invoke<A, R>::invoke::h14573519323502060031
  16:        0x102c2cc51 - thunk::Thunk<A, R>::invoke::h1758463329604743876
  17:        0x102c2d99a - thread::Builder::spawn_inner::unboxed_closure.5345
  18:        0x102c2d91f - rt::unwind::try::try_fn::__rust_abi::h5564697778693967227
  19:        0x102c2d8ba - rt::unwind::try::try_fn::h5564697778693967227
  20:        0x104400d59 - rust_try_inner
  21:        0x104400d46 - rust_try
  22:        0x102c2cda0 - rt::unwind::try::h13219397950734276130
  23:        0x102c2b9cd - thread::Builder::spawn_inner::unboxed_closure.5194
  24:        0x102c2eac9 - thunk::Thunk<(*, R>::new::unboxed_closure.5368
  25:        0x102c2e9b1 - thunk::F.Invoke<A, R>::invoke::h4744309663374176267
  26:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  27:     0x7fff872eb268 - _pthread_body
  28:     0x7fff872eb1e5 - _pthread_body
thread 'StorageManager' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
stack backtrace:
thread 'LayoutTask' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103de0982 - result::Result<T, E>::unwrap::h6357430758850953419
   8:        0x103ddd314 - storage_task::StorageManager::start::heb79d8c6e4494415p0b
   9:        0x103ddd234 - storage_task::StorageTask.StorageTaskFactory::new::unboxed_closure.12249
  10:        0x103ddceff - task::spawn_named::unboxed_closure.12242
  11:        0x103ddce4f - thunk::Thunk<(*, R>::new::unboxed_closure.12238
  12:        0x103ddcd8f - thunk::F.Invoke<A, R>::invoke::h3593243973323706667
  13:        0x103d0ed51 - thunk::Thunk<A, R>::invoke::h13499003564431701313
  14:        0x103d0fa9a - thread::Builder::spawn_inner::unboxed_closure.8769
  15:        0x103d0fa1f - rt::unwind::try::try_fn::__rust_abi::h16045507415480198383
  16:        0x103d0f9ba - rt::unwind::try::try_fn::h16045507415480198383
  17:        0x104400d59 - rust_try_inner
  18:        0x104400d46 - rust_try
  19:        0x103d0eea0 - rt::unwind::try::h6057487482421447671
  20:        0x103d0dacd - thread::Builder::spawn_inner::unboxed_closure.8618
  21:        0x103d10bc9 - thunk::Thunk<(*, R>::new::unboxed_closure.8792
  22:        0x103d10ab1 - thunk::F.Invoke<A, R>::invoke::h16257397529749864493
  23:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  24:     0x7fff872eb268 - _pthread_body
  25:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x10321f0f4 - result::Result<T, E>::unwrap::h11300205262697794970
   8:        0x10320f4ac - layout_task::LayoutTask::handle_request::h491d6d61f84f0619hek
   9:        0x1031dd5f0 - layout_task::LayoutTask::start::he4ad3559a67d032c1ck
  10:        0x1031c7fe0 - layout_task::LayoutTask.LayoutTaskFactory::create::unboxed_closure.28606
  11:        0x1031c7512 - task::spawn_named_with_send_on_failure::unboxed_closure.28593
  12:        0x1031c741c - thunk::Thunk<(*, R>::new::unboxed_closure.28589
  13:        0x1031c7317 - thunk::F.Invoke<A, R>::invoke::h14416988839020376179
  14:        0x103144751 - thunk::Thunk<A, R>::invoke::h5305478574340540044
  15:        0x10314549a - thread::Builder::spawn_inner::unboxed_closure.26684
  16:        0x10314541f - rt::unwind::try::try_fn::__rust_abi::h14292791922065648334
  17:        0x1031453ba - rt::unwind::try::try_fn::h14292791922065648334
  18:        0x104400d59 - rust_try_inner
  19:        0x104400d46 - rust_try
  20:        0x1031448a0 - rt::unwind::try::h17614306589905634903
  21:        0x1031434cd - thread::Builder::spawn_inner::unboxed_closure.26579
  22:        0x1031465c9 - thunk::Thunk<(*, R>::new::unboxed_closure.26707
  23:        0x1031464b1 - thunk::F.Invoke<A, R>::invoke::h5816070722465926202
  24:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  25:     0x7fff872eb268 - _pthread_body
  26:     0x7fff872eb1e5 - _pthread_body
thread 'PaintTask' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
stack backtrace:
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x102d24c85 - result::Result<T, E>::unwrap::h9899679859730660193
   8:        0x102d22ecf - paint_task::PaintTask<C>::start::h6059050851116411079
   9:        0x102d12dc2 - paint_task::PaintTask<C>::create::unboxed_closure.10858
  10:        0x102d124ea - task::spawn_named_with_send_on_failure::unboxed_closure.10847
  11:        0x102d123f4 - thunk::Thunk<(*, R>::new::unboxed_closure.10843
  12:        0x102d122fe - thunk::F.Invoke<A, R>::invoke::h10818628969664824264
  13:        0x102c2cc51 - thunk::Thunk<A, R>::invoke::h1758463329604743876
  14:        0x102c2d99a - thread::Builder::spawn_inner::unboxed_closure.5345
  15:        0x102c2d91f - rt::unwind::try::try_fn::__rust_abi::h5564697778693967227
  16:        0x102c2d8ba - rt::unwind::try::try_fn::h5564697778693967227
  17:        0x104400d59 - rust_try_inner
  18:        0x104400d46 - rust_try
  19:        0x102c2cda0 - rt::unwind::try::h13219397950734276130
  20:        0x102c2b9cd - thread::Builder::spawn_inner::unboxed_closure.5194
  21:        0x102c2eac9 - thunk::Thunk<(*, R>::new::unboxed_closure.5368
  22:        0x102c2e9b1 - thunk::F.Invoke<A, R>::invoke::h4744309663374176267
  23:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  24:     0x7fff872eb268 - _pthread_body
  25:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103203d1a - result::Result<T, E>::unwrap::h10056488610532532924
   8:        0x103203445 - workqueue::WorkerThread<QueueData, WorkData>::start::h3637463313264756779
   9:        0x103203343 - workqueue::WorkQueue<QueueData, WorkData>::new::unboxed_closure.29664
  10:        0x103202f61 - task::spawn_named::unboxed_closure.29657
  11:        0x103202e34 - thunk::Thunk<(*, R>::new::unboxed_closure.29653
  12:        0x103202cfd - thunk::F.Invoke<A, R>::invoke::h6732775514546197959
  13:        0x103144751 - thunk::Thunk<A, R>::invoke::h5305478574340540044
  14:        0x10314549a - thread::Builder::spawn_inner::unboxed_closure.26684
  15:        0x10314541f - rt::unwind::try::try_fn::__rust_abi::h14292791922065648334
  16:        0x1031453ba - rt::unwind::try::try_fn::h14292791922065648334
  17:        0x104400d59 - rust_try_inner
  18:        0x104400d46 - rust_try
  19:        0x1031448a0 - rt::unwind::try::h17614306589905634903
  20:        0x1031434cd - thread::Builder::spawn_inner::unboxed_closure.26579
  21:        0x1031465c9 - thunk::Thunk<(*, R>::new::unboxed_closure.26707
  22:        0x1031464b1 - thunk::F.Invoke<A, R>::invoke::h5816070722465926202
  23:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  24:     0x7fff872eb268 - _pthread_body
  25:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103203d1a - result::Result<T, E>::unwrap::h10056488610532532924
   8:        0x103203445 - workqueue::WorkerThread<QueueData, WorkData>::start::h3637463313264756779
   9:        0x103203343 - workqueue::WorkQueue<QueueData, WorkData>::new::unboxed_closure.29664
  10:        0x103202f61 - task::spawn_named::unboxed_closure.29657
  11:        0x103202e34 - thunk::Thunk<(*, R>::new::unboxed_closure.29653
  12:        0x103202cfd - thunk::F.Invoke<A, R>::invoke::h6732775514546197959
  13:        0x103144751 - thunk::Thunk<A, R>::invoke::h5305478574340540044
  14:        0x10314549a - thread::Builder::spawn_inner::unboxed_closure.26684
  15:        0x10314541f - rt::unwind::try::try_fn::__rust_abi::h14292791922065648334
  16:        0x1031453ba - rt::unwind::try::try_fn::h14292791922065648334
  17:        0x104400d59 - rust_try_inner
  18:        0x104400d46 - rust_try
  19:        0x1031448a0 - rt::unwind::try::h17614306589905634903
  20:        0x1031434cd - thread::Builder::spawn_inner::unboxed_closure.26579
  21:        0x1031465c9 - thunk::Thunk<(*, R>::new::unboxed_closure.26707
  22:        0x1031464b1 - thunk::F.Invoke<A, R>::invoke::h5816070722465926202
  23:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  24:     0x7fff872eb268 - _pthread_body
  25:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103203d1a - result::Result<T, E>::unwrap::h10056488610532532924
   8:        0x103203445 - workqueue::WorkerThread<QueueData, WorkData>::start::h3637463313264756779
   9:        0x103203343 - workqueue::WorkQueue<QueueData, WorkData>::new::unboxed_closure.29664
  10:        0x103202f61 - task::spawn_named::unboxed_closure.29657
  11:        0x103202e34 - thunk::Thunk<(*, R>::new::unboxed_closure.29653
  12:        0x103202cfd - thunk::F.Invoke<A, R>::invoke::h6732775514546197959
  13:        0x103144751 - thunk::Thunk<A, R>::invoke::h5305478574340540044
  14:        0x10314549a - thread::Builder::spawn_inner::unboxed_closure.26684
  15:        0x10314541f - rt::unwind::try::try_fn::__rust_abi::h14292791922065648334
  16:        0x1031453ba - rt::unwind::try::try_fn::h14292791922065648334
  17:        0x104400d59 - rust_try_inner
  18:        0x104400d46 - rust_try
  19:        0x1031448a0 - rt::unwind::try::h17614306589905634903
  20:        0x1031434cd - thread::Builder::spawn_inner::unboxed_closure.26579
  21:        0x1031465c9 - thunk::Thunk<(*, R>::new::unboxed_closure.26707
  22:        0x1031464b1 - thunk::F.Invoke<A, R>::invoke::h5816070722465926202
  23:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  24:     0x7fff872eb268 - _pthread_body
  25:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103c2c7a3 - result::Result<T, E>::unwrap::h13311088526773448755
   8:        0x103c1d638 - paint_task::WorkerThread::main::heb9ab636e16384caJcd
   9:        0x103c1cf05 - paint_task::WorkerThreadProxy::spawn::unboxed_closure.15324
  10:        0x103c1ccfc - thunk::Thunk<(*, R>::new::unboxed_closure.15320
  11:        0x103c1cbc1 - thunk::F.Invoke<A, R>::invoke::h18094018673770018736
  12:        0x103c1a7a1 - thunk::Thunk<A, R>::invoke::h13879629867050755449
  13:        0x103c1b4ea - thread::Builder::spawn_inner::unboxed_closure.15287
  14:        0x103c1b46f - rt::unwind::try::try_fn::__rust_abi::h13182145393098491843
  15:        0x103c1b40a - rt::unwind::try::try_fn::h13182145393098491843
  16:        0x104400d59 - rust_try_inner
  17:        0x104400d46 - rust_try
  18:        0x103c1a8f0 - rt::unwind::try::h18373468840831823939
  19:        0x103c1951d - thread::Builder::spawn_inner::unboxed_closure.15148
  20:        0x103c1c619 - thunk::Thunk<(*, R>::new::unboxed_closure.15310
  21:        0x103c1c501 - thunk::F.Invoke<A, R>::invoke::h3393205117388017845
  22:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  23:     0x7fff872eb268 - _pthread_body
  24:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103c2c7a3 - result::Result<T, E>::unwrap::h13311088526773448755
   8:        0x103c1d638 - paint_task::WorkerThread::main::heb9ab636e16384caJcd
   9:        0x103c1cf05 - paint_task::WorkerThreadProxy::spawn::unboxed_closure.15324
  10:        0x103c1ccfc - thunk::Thunk<(*, R>::new::unboxed_closure.15320
  11:        0x103c1cbc1 - thunk::F.Invoke<A, R>::invoke::h18094018673770018736
  12:        0x103c1a7a1 - thunk::Thunk<A, R>::invoke::h13879629867050755449
  13:        0x103c1b4ea - thread::Builder::spawn_inner::unboxed_closure.15287
  14:        0x103c1b46f - rt::unwind::try::try_fn::__rust_abi::h13182145393098491843
  15:        0x103c1b40a - rt::unwind::try::try_fn::h13182145393098491843
  16:        0x104400d59 - rust_try_inner
  17:        0x104400d46 - rust_try
  18:        0x103c1a8f0 - rt::unwind::try::h18373468840831823939
  19:        0x103c1951d - thread::Builder::spawn_inner::unboxed_closure.15148
  20:        0x103c1c619 - thunk::Thunk<(*, R>::new::unboxed_closure.15310
  21:        0x103c1c501 - thunk::F.Invoke<A, R>::invoke::h3393205117388017845
  22:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  23:     0x7fff872eb268 - _pthread_body
  24:     0x7fff872eb1e5 - _pthread_body
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103c2c7a3 - result::Result<T, E>::unwrap::h13311088526773448755
   8:        0x103c1d638 - paint_task::WorkerThread::main::heb9ab636e16384caJcd
   9:        0x103c1cf05 - paint_task::WorkerThreadProxy::spawn::unboxed_closure.15324
  10:        0x103c1ccfc - thunk::Thunk<(*, R>::new::unboxed_closure.15320
  11:        0x103c1cbc1 - thunk::F.Invoke<A, R>::invoke::h18094018673770018736
  12:        0x103c1a7a1 - thunk::Thunk<A, R>::invoke::h13879629867050755449
  13:        0x103c1b4ea - thread::Builder::spawn_inner::unboxed_closure.15287
  14:        0x103c1b46f - rt::unwind::try::try_fn::__rust_abi::h13182145393098491843
  15:        0x103c1b40a - rt::unwind::try::try_fn::h13182145393098491843
  16:        0x104400d59 - rust_try_inner
  17:        0x104400d46 - rust_try
  18:        0x103c1a8f0 - rt::unwind::try::h18373468840831823939
  19:        0x103c1951d - thread::Builder::spawn_inner::unboxed_closure.15148
  20:        0x103c1c619 - thunk::Thunk<(*, R>::new::unboxed_closure.15310
  21:        0x103c1c501 - thunk::F.Invoke<A, R>::invoke::h3393205117388017845
  22:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  23:     0x7fff872eb268 - _pthread_body
  24:     0x7fff872eb1e5 - _pthread_body
thread 'FontCacheTask' panicked at 'called `Result::unwrap()` on an `Err` value: "receiving on a closed channel"', /Users/larsberg/rust/src/libcore/result.rs:746
stack backtrace:
   1:        0x1043ea4b5 - sys::backtrace::write::habdc320444a07b69lCt
   2:        0x1043ff289 - failure::on_fail::h518a2e1bba17c9c90Hz
   3:        0x1043ce98a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz
   4:        0x1043ceb84 - rt::unwind::begin_unwind_fmt::hf3d322d122a35172noz
   5:        0x1043fec1e - rust_begin_unwind
   6:        0x104421217 - panicking::panic_fmt::hd6c77548964d848fpfl
   7:        0x103c549a2 - result::Result<T, E>::unwrap::h16918294797974067874
   8:        0x103c53b44 - font_cache_task::FontCache::run::h5f47a7d4a22efa34Oce
   9:        0x103c88736 - font_cache_task::FontCacheTask::new::unboxed_closure.16964
  10:        0x103c880af - task::spawn_named::unboxed_closure.16957
  11:        0x103c87fcf - thunk::Thunk<(*, R>::new::unboxed_closure.16953
  12:        0x103c87eda - thunk::F.Invoke<A, R>::invoke::h1516609202855576519
  13:        0x103c1a7a1 - thunk::Thunk<A, R>::invoke::h13879629867050755449
  14:        0x103c1b4ea - thread::Builder::spawn_inner::unboxed_closure.15287
  15:        0x103c1b46f - rt::unwind::try::try_fn::__rust_abi::h13182145393098491843
  16:        0x103c1b40a - rt::unwind::try::try_fn::h13182145393098491843
  17:        0x104400d59 - rust_try_inner
  18:        0x104400d46 - rust_try
  19:        0x103c1a8f0 - rt::unwind::try::h18373468840831823939
  20:        0x103c1951d - thread::Builder::spawn_inner::unboxed_closure.15148
  21:        0x103c1c619 - thunk::Thunk<(*, R>::new::unboxed_closure.15310
  22:        0x103c1c501 - thunk::F.Invoke<A, R>::invoke::h3393205117388017845
  23:        0x1043ee344 - sys::thread::thread_start::h1ff6fbf82b65b913drw
  24:     0x7fff872eb268 - _pthread_body
  25:     0x7fff872eb1e5 - _pthread_body
```

**Comment by glennw** [comment]
Try http://google.com - it's attempting to open google.com as a local file.

**Comment by frewsxcv** [comment]
Wow. That was silly of me.
