### ISSUE TITLE
Hacker News newcomments causes crash

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#4933]
Currently on 3e7dc57

```
~/D/servo (master|✔) $ ./mach run http://news.ycombinator.com/newcomments
ERROR:script::parse::html: remove_from_parent not implemented!
thread 'ScriptTask' panicked at 'unimplemented', /Users/coreyf/Development/servo/components/script/parse/html.rs:168
stack backtrace:
   1:        0x110f1f787 - sys::backtrace::write::h084c3267f5afd4a3hvy
   2:        0x110f356f3 - failure::on_fail::hc5ca3b9ac2e803f33NF
   3:        0x110f02c18 - rt::unwind::begin_unwind_inner::h6a7a87805596eb8avvF
   4:        0x10fd29aa7 - rt::unwind::begin_unwind::h1774502948422658099
   5:        0x11024f887 - parse::html::servohtmlparser..Sink.TreeSink::reparent_children::hf9f845e1c65e30d7NtC
   6:        0x11024cd2b - tree_builder::actions::super..TreeBuilder<Handle, Sink>.TreeBuilderActions<Handle>::adoption_agency::h17469607436752435949
   7:        0x11022adba - tree_builder::rules::super..TreeBuilder<Handle, Sink>.TreeBuilderStep<Handle>::step::h11157669615711889626
   8:        0x1102392c4 - tree_builder::rules::super..TreeBuilder<Handle, Sink>.TreeBuilderStep<Handle>::step::h11157669615711889626
   9:        0x110224bb7 - tree_builder::TreeBuilder<Handle, Sink>::process_to_completion::h3602939436487711564
  10:        0x110223679 - tree_builder::TreeBuilder<Handle, Sink>.TokenSink::process_token::h2544577113652428471
  11:        0x11022286d - tokenizer::Tokenizer<Sink>::process_token::h2098597153589824887
  12:        0x11025b346 - tokenizer::Tokenizer<Sink>::emit_current_tag::h7022898056842536121
  13:        0x11021b6a9 - tokenizer::Tokenizer<Sink>::step::h9031867991148398011
  14:        0x11021941c - tokenizer::Tokenizer<Sink>::run::h10996526480779673615
  15:        0x110219263 - tokenizer::Tokenizer<Sink>::feed::h15852587159161170183
  16:        0x1102190c5 - dom::servohtmlparser::ServoHTMLParser.Parser::parse_chunk::h4cd74e996765f7d28ix
  17:        0x1101497ab - parse::html::parse_html::hac5dae056f984360vuC
  18:        0x110356903 - script_task::ScriptTask::load::he559f4da6ee89ba293D
  19:        0x110352ce4 - script_task::ScriptTask::handle_msg_from_constellation::hb3cc9562eb9114a2HOD
  20:        0x11032f18c - script_task::ScriptTask::handle_msgs::h463ec6ae42eea184wHD
  21:        0x11032d4b2 - script_task::ScriptTask::start::had882fd508f3164emHD
  22:        0x10f81b581 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10037
  23:        0x10f81aaf2 - task::spawn_named_with_send_on_failure::closure.10024
  24:        0x10f81a9fc - thunk::Thunk<(), R>::new::closure.10020
  25:        0x10f81a8f7 - thunk::F.Invoke<A, R>::invoke::h3364452413257889894
  26:        0x10f750101 - thunk::Thunk<A, R>::invoke::h17562729461457776048
  27:        0x10f750e3a - thread::Builder::spawn_inner::closure.5172
  28:        0x10f750dbf - rt::unwind::try::try_fn::__rust_abi::h2972931501965523557
  29:        0x10f750d5a - rt::unwind::try::try_fn::h2972931501965523557
  30:        0x110f370d9 - rust_try_inner
  31:        0x110f370c6 - rust_try
  32:        0x10f75024c - rt::unwind::try::h3220175846342749462
  33:        0x10f74ef8f - thread::Builder::spawn_inner::closure.5024
  34:        0x10f751e79 - thunk::Thunk<(), R>::new::closure.5196
  35:        0x10f751d61 - thunk::F.Invoke<A, R>::invoke::h18101276016754963175
  36:        0x110f231b3 - sys::thread::thread_start::h8d91e5be653c10c05CB
  37:     0x7fff9201f268 - _pthread_body
  38:     0x7fff9201f1e5 - _pthread_body
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:        0x110f1f787 - sys::backtrace::write::h084c3267f5afd4a3hvy
   2:        0x110f356f3 - failure::on_fail::hc5ca3b9ac2e803f33NF
   3:        0x110f02c18 - rt::unwind::begin_unwind_inner::h6a7a87805596eb8avvF
   4:        0x110f03381 - rt::unwind::begin_unwind_fmt::h1fd6919e00fae1f31tF
   5:        0x110f350ee - rust_begin_unwind
   6:        0x110f57c47 - panicking::panic_fmt::hd22743a6fa1fac27zow
   7:        0x11031883c - result::Result<T, E>::unwrap::h2846367562058920054
   8:        0x11031861d - script_task::NonWorkerScriptChan.ScriptChan::send::hecb04000168592efxrD
   9:        0x1101ea0ad - dom::bindings::refcounted::Trusted<T>.Drop::drop::h2814891413804540459
  10:        0x1101e9ebe - dom..bindings..refcounted..Trusted<dom..htmlscriptelement..HTMLScriptElement>::glue_drop.84321::h2d99174fa68ad151
  11:        0x1101ea11c - Box<dom..bindings..refcounted..Trusted<dom..htmlscriptelement..HTMLScriptElement>>::glue_drop.84324::hfddebdc713936679
  12:        0x10f7f50f0 - Box<script..script_task..Runnable $u2b$$u20$Send$GT$::glue_drop.9262::h7437ca3656e646ad
  13:        0x10f7f3fda - script..script_task..ScriptMsg::glue_drop.9222::h0e64eb6715522e56
  14:        0x10f7f707f - std..sync..mpsc..mpsc_queue..PopResult<script..script_task..ScriptMsg>::glue_drop.9289::h0f8217df60f56a79
  15:        0x10f7f6a28 - sync::mpsc::shared::Packet<T>::drop_port::h1431322632099401595
  16:        0x10f7f52fa - sync::mpsc::Receiver<T>.Drop::drop::h11933626434304558797
  17:        0x10f7f51ce - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.9268::h7b60620f1d1531e5
  18:        0x10f7f5173 - std..sync..mpsc..oneshot..MyUpgrade<script..script_task..ScriptMsg>::glue_drop.9265::h30499bd24dd6ed6d
  19:        0x10f7f3c37 - std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>::glue_drop.9216::haee6081b541cc5b9
  20:        0x10f7f3bbe - core..cell..UnsafeCell<std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>>::glue_drop.9213::h40a2d48bc4087899
  21:        0x10f7f9452 - mem::drop::h8090896654703900224
  22:        0x10f7f92b4 - arc::Arc<T>.Drop::drop::h17005361695692019347
  23:        0x10f7f90de - alloc..arc..Arc<core..cell..UnsafeCell<std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>>>::glue_drop.9316::h45d2a770c63c6d60
  24:        0x10f7f906f - std..sync..mpsc..Flavor<script..script_task..ScriptMsg>::glue_drop.9313::h46e0e43b65af5657
  25:        0x10f7f8fee - core..cell..UnsafeCell<std..sync..mpsc..Flavor<script..script_task..ScriptMsg>>::glue_drop.9310::h217fa2c10952c28d
  26:        0x10f7f51d9 - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.9268::h7b60620f1d1531e5
  27:        0x10f81f8e6 - script..script_task..ScriptTask::glue_drop.10203::hf236c69d3feab705
  28:        0x10f81b5d8 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10037
  29:        0x10f81aaf2 - task::spawn_named_with_send_on_failure::closure.10024
  30:        0x10f81a9fc - thunk::Thunk<(), R>::new::closure.10020
  31:        0x10f81a8f7 - thunk::F.Invoke<A, R>::invoke::h3364452413257889894
  32:        0x10f750101 - thunk::Thunk<A, R>::invoke::h17562729461457776048
  33:        0x10f750e3a - thread::Builder::spawn_inner::closure.5172
  34:        0x10f750dbf - rt::unwind::try::try_fn::__rust_abi::h2972931501965523557
  35:        0x10f750d5a - rt::unwind::try::try_fn::h2972931501965523557
  36:        0x110f370d9 - rust_try_inner
  37:        0x110f370c6 - rust_try
  38:        0x10f75024c - rt::unwind::try::h3220175846342749462
  39:        0x10f74ef8f - thread::Builder::spawn_inner::closure.5024
  40:        0x10f751e79 - thunk::Thunk<(), R>::new::closure.5196
  41:        0x10f751d61 - thunk::F.Invoke<A, R>::invoke::h18101276016754963175
  42:        0x110f231b3 - sys::thread::thread_start::h8d91e5be653c10c05CB
  43:     0x7fff9201f268 - _pthread_body
  44:     0x7fff9201f1e5 - _pthread_body
thread panicked while panicking. aborting.
Error running mach:

    ['run', 'http://news.ycombinator.com/newcomments']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/servo', 'http://news.ycombinator.com/newcomments']' returned non-zero exit status -4

  File "/Users/coreyf/Development/servo/python/servo/post_build_commands.py", line 78, in run
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by jdm** [comment]
@kmcallister When upgrading html5ever for the most recent upgrade I stubbed out the new reparent_children trait method. What's involved in implementing it properly?

**Comment by jdm** [comment]
@kmcallister Also, what's it mean that remove_from_parent is unimplemented in the parser as well?

**Comment by nithinmurali** [comment]
hi, i would like to work on this bug. @jdm  I am :lazybug  :)

**Comment by jdm** [comment]
@nithinmurali Great! I would suggest making reparent_children remove all of the child nodes of `node` and add them as children of `new_parent`. Similarly, we might as well implement `remove_from_parent` in the obvious way too.

**Comment by nithinmurali** [comment]
@jdm i have made an pull request ; should i use panic!() inplace of the println!() and continuing loop ??

**Comment by frewsxcv** [comment]
`http://news.ycombinator.com/newcomments` no longer crashes this. Thanks everyone for fixing this.
