### ISSUE TITLE
mobile GotG page in static suite crashes

### ISSUE THREAD

**Issue by metajack** [servo/servo#5076]
```
[jack@ocate servo]$ ./mach run --resolution 1280x1024 ../static-suite/wikipedia/mobile/Guardians\ of\ the\ Galaxy\ \(film\)\ -\ Wikipedia\,\ the\ free\ encyclopedia.html 
ERROR:js::rust: Error at file:///home/jack/src/static-suite/wikipedia/mobile/Guardians%20of%20the%20Galaxy%20%28film%29%20-%20Wikipedia,%20the%20free%20encyclopedia_files/load_004.php:28: TypeError: document.write is not a function

ERROR:js::rust: Error at file:///home/jack/src/static-suite/wikipedia/mobile/Guardians%20of%20the%20Galaxy%20%28film%29%20-%20Wikipedia,%20the%20free%20encyclopedia_files/load_002.php:58: TypeError: div.firstChild is null

ERROR:js::rust: Error at file:///home/jack/src/static-suite/wikipedia/mobile/Guardians%20of%20the%20Galaxy%20%28film%29%20-%20Wikipedia,%20the%20free%20encyclopedia_files/load.php:1: ReferenceError: mw is not defined

ERROR:js::rust: Error at file:///home/jack/src/static-suite/wikipedia/mobile/Guardians%20of%20the%20Galaxy%20%28film%29%20-%20Wikipedia,%20the%20free%20encyclopedia_files/load_003.php:1: ReferenceError: mw is not defined

thread 'LayoutWorker worker 3/3' panicked at 'assertion failed: !self.range.is_empty()', /home/jack/src/servo/components/gfx/text/text_run.rs:121
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7ff02168f330 - rt::unwind::begin_unwind::h14626050634566053023
   5:     0x7ff0217b6600 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h17770571729476809112
   6:     0x7ff0217b4460 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h3442547142235548481
   7:     0x7ff0217b3f30 - fragment::Fragment::calculate_split_position::h6192187a1758f3bdZaj
   8:     0x7ff02187eeb0 - inline::LineBreaker::append_fragment_to_line_if_possible::h09c52a345d1d064cdrm
   9:     0x7ff02187c540 - inline::LineBreaker::reflow_fragments::h10555987961404427608
  10:     0x7ff02187b6f0 - inline::LineBreaker::scan_for_lines::hd71b9843a01b2c26sUl
  11:     0x7ff021701c20 - inline::InlineFlow.Flow::assign_block_size::hb455178afba35184jcn
  12:     0x7ff021891240 - traversal::AssignBSizesAndStoreOverflow<'a>.PostorderFlowTraversal::process::h29ff8ba78f651849wzr
  13:     0x7ff021890ea0 - parallel::ParallelPostorderFlowTraversal::run_parallel::h15467951526756109907
  14:     0x7ff02188e7d0 - parallel::assign_block_sizes_and_store_overflow::h755a8b80873667143fo
  15:     0x7ff02188df00 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::habe7de13263d9e06Obo
  16:     0x7ff02188e720 - parallel::assign_inline_sizes::hd0cbdea21f254d8cmfo
  17:     0x7ff021839fd0 - workqueue::WorkerThread<QueueData, WorkData>::start::h3126424248260774734
  18:     0x7ff021839e40 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.31512
  19:     0x7ff021839b60 - task::spawn_named::closure.31505
  20:     0x7ff021839a60 - thunk::Thunk<(), R>::new::closure.31501
  21:     0x7ff0218398f0 - thunk::F.Invoke<A, R>::invoke::h17835060694743158420
  22:     0x7ff021777730 - thunk::Thunk<A, R>::invoke::h14063232307924075085
  23:     0x7ff021778430 - thread::Builder::spawn_inner::closure.28593
  24:     0x7ff0217783c0 - rt::unwind::try::try_fn::__rust_abi::h1855026725727266269
  25:     0x7ff021778380 - rt::unwind::try::try_fn::h1855026725727266269
  26:     0x7ff022b72980 - rust_try_inner
  27:     0x7ff022b72970 - rust_try
  28:     0x7ff0217777c0 - rt::unwind::try::h1451289760882031375
  29:     0x7ff021776510 - thread::Builder::spawn_inner::closure.28492
  30:     0x7ff0217793c0 - thunk::Thunk<(), R>::new::closure.28617
  31:     0x7ff0217792a0 - thunk::F.Invoke<A, R>::invoke::h14044084656094621362
  32:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  33:     0x7ff020236460 - start_thread
  34:     0x7ff01f714769 - clone
  35:                0x0 - <unknown>
thread 'LayoutWorker worker 2/3' panicked at 'assertion failed: !self.range.is_empty()', /home/jack/src/servo/components/gfx/text/text_run.rs:121
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7ff02168f330 - rt::unwind::begin_unwind::h14626050634566053023
   5:     0x7ff0217b6600 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h17770571729476809112
   6:     0x7ff0217b4460 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h3442547142235548481
   7:     0x7ff0217b3f30 - fragment::Fragment::calculate_split_position::h6192187a1758f3bdZaj
   8:     0x7ff02187eeb0 - inline::LineBreaker::append_fragment_to_line_if_possible::h09c52a345d1d064cdrm
   9:     0x7ff02187c540 - inline::LineBreaker::reflow_fragments::h10555987961404427608
  10:     0x7ff02187b6f0 - inline::LineBreaker::scan_for_lines::hd71b9843a01b2c26sUl
  11:     0x7ff021701c20 - inline::InlineFlow.Flow::assign_block_size::hb455178afba35184jcn
  12:     0x7ff021891240 - traversal::AssignBSizesAndStoreOverflow<'a>.PostorderFlowTraversal::process::h29ff8ba78f651849wzr
  13:     0x7ff021890ea0 - parallel::ParallelPostorderFlowTraversal::run_parallel::h15467951526756109907
  14:     0x7ff02188e7d0 - parallel::assign_block_sizes_and_store_overflow::h755a8b80873667143fo
  15:     0x7ff02188df00 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::habe7de13263d9e06Obo
  16:     0x7ff02188e720 - parallel::assign_inline_sizes::hd0cbdea21f254d8cmfo
  17:     0x7ff021839fd0 - workqueue::WorkerThread<QueueData, WorkData>::start::h3126424248260774734
  18:     0x7ff021839e40 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.31512
  19:     0x7ff021839b60 - task::spawn_named::closure.31505
  20:     0x7ff021839a60 - thunk::Thunk<(), R>::new::closure.31501
  21:     0x7ff0218398f0 - thunk::F.Invoke<A, R>::invoke::h17835060694743158420
  22:     0x7ff021777730 - thunk::Thunk<A, R>::invoke::h14063232307924075085
  23:     0x7ff021778430 - thread::Builder::spawn_inner::closure.28593
  24:     0x7ff0217783c0 - rt::unwind::try::try_fn::__rust_abi::h1855026725727266269
  25:     0x7ff021778380 - rt::unwind::try::try_fn::h1855026725727266269
  26:     0x7ff022b72980 - rust_try_inner
  27:     0x7ff022b72970 - rust_try
  28:     0x7ff0217777c0 - rt::unwind::try::h1451289760882031375
  29:     0x7ff021776510 - thread::Builder::spawn_inner::closure.28492
  30:     0x7ff0217793c0 - thunk::Thunk<(), R>::new::closure.28617
  31:     0x7ff0217792a0 - thunk::F.Invoke<A, R>::invoke::h14044084656094621362
  32:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  33:     0x7ff020236460 - start_thread
  34:     0x7ff01f714769 - clone
  35:                0x0 - <unknown>
thread 'LayoutWorker worker 1/3' panicked at 'assertion failed: !self.range.is_empty()', /home/jack/src/servo/components/gfx/text/text_run.rs:121
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7ff02168f330 - rt::unwind::begin_unwind::h14626050634566053023
   5:     0x7ff0217b6600 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h17770571729476809112
   6:     0x7ff0217b4460 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h3442547142235548481
   7:     0x7ff0217b3f30 - fragment::Fragment::calculate_split_position::h6192187a1758f3bdZaj
   8:     0x7ff02187eeb0 - inline::LineBreaker::append_fragment_to_line_if_possible::h09c52a345d1d064cdrm
   9:     0x7ff02187c540 - inline::LineBreaker::reflow_fragments::h10555987961404427608
  10:     0x7ff02187b6f0 - inline::LineBreaker::scan_for_lines::hd71b9843a01b2c26sUl
  11:     0x7ff021701c20 - inline::InlineFlow.Flow::assign_block_size::hb455178afba35184jcn
  12:     0x7ff021891240 - traversal::AssignBSizesAndStoreOverflow<'a>.PostorderFlowTraversal::process::h29ff8ba78f651849wzr
  13:     0x7ff021890ea0 - parallel::ParallelPostorderFlowTraversal::run_parallel::h15467951526756109907
  14:     0x7ff02188e7d0 - parallel::assign_block_sizes_and_store_overflow::h755a8b80873667143fo
  15:     0x7ff02188df00 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::habe7de13263d9e06Obo
  16:     0x7ff02188e720 - parallel::assign_inline_sizes::hd0cbdea21f254d8cmfo
  17:     0x7ff021839fd0 - workqueue::WorkerThread<QueueData, WorkData>::start::h3126424248260774734
  18:     0x7ff021839e40 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.31512
  19:     0x7ff021839b60 - task::spawn_named::closure.31505
  20:     0x7ff021839a60 - thunk::Thunk<(), R>::new::closure.31501
  21:     0x7ff0218398f0 - thunk::F.Invoke<A, R>::invoke::h17835060694743158420
  22:     0x7ff021777730 - thunk::Thunk<A, R>::invoke::h14063232307924075085
  23:     0x7ff021778430 - thread::Builder::spawn_inner::closure.28593
  24:     0x7ff0217783c0 - rt::unwind::try::try_fn::__rust_abi::h1855026725727266269
  25:     0x7ff021778380 - rt::unwind::try::try_fn::h1855026725727266269
  26:     0x7ff022b72980 - rust_try_inner
  27:     0x7ff022b72970 - rust_try
  28:     0x7ff0217777c0 - rt::unwind::try::h1451289760882031375
  29:     0x7ff021776510 - thread::Builder::spawn_inner::closure.28492
  30:     0x7ff0217793c0 - thunk::Thunk<(), R>::new::closure.28617
  31:     0x7ff0217792a0 - thunk::F.Invoke<A, R>::invoke::h14044084656094621362
  32:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  33:     0x7ff020236460 - start_thread
  34:     0x7ff01f714769 - clone
  35:                0x0 - <unknown>
thread 'LayoutTask' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7ff022b384e0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7ff022b684e0 - rust_begin_unwind
   6:     0x7ff022b95a50 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7ff021866cd0 - result::Result<T, E>::unwrap::h320230190843676159
   8:     0x7ff021891a00 - workqueue::WorkQueue<QueueData, WorkData>::run::h1134961875040517245
   9:     0x7ff021871380 - parallel::traverse_flow_tree_preorder::h691999593b0c0c7aZio
  10:     0x7ff021871180 - layout_task::LayoutTask::solve_constraints_parallel::h2aadd37fc9626fbdLMk
  11:     0x7ff021875c80 - layout_task::LayoutTask::handle_reflow::closure.32059
  12:     0x7ff021875a80 - time::profile::h17770836684741176103
  13:     0x7ff021864cd0 - layout_task::LayoutTask::handle_reflow::ha7b59695b033ab09AXk
  14:     0x7ff021861540 - layout_task::LayoutTask::handle_script_request::closure.31856
  15:     0x7ff021861350 - time::profile::h17587380793460380235
  16:     0x7ff021858560 - layout_task::LayoutTask::handle_script_request::haea309c679ab06dc3zk
  17:     0x7ff021846560 - layout_task::LayoutTask::handle_request::h6e6c914fb94372c8Gwk
  18:     0x7ff021814e60 - layout_task::LayoutTask::start::hba00ed33ce617109rvk
  19:     0x7ff021800290 - layout_task::LayoutTask.LayoutTaskFactory::create::closure.30542
  20:     0x7ff0217ffce0 - task::spawn_named_with_send_on_failure::closure.30529
  21:     0x7ff0217ffbf0 - thunk::Thunk<(), R>::new::closure.30525
  22:     0x7ff0217ffab0 - thunk::F.Invoke<A, R>::invoke::h10161283853233742202
  23:     0x7ff021777730 - thunk::Thunk<A, R>::invoke::h14063232307924075085
  24:     0x7ff021778430 - thread::Builder::spawn_inner::closure.28593
  25:     0x7ff0217783c0 - rt::unwind::try::try_fn::__rust_abi::h1855026725727266269
  26:     0x7ff021778380 - rt::unwind::try::try_fn::h1855026725727266269
  27:     0x7ff022b72980 - rust_try_inner
  28:     0x7ff022b72970 - rust_try
  29:     0x7ff0217777c0 - rt::unwind::try::h1451289760882031375
  30:     0x7ff021776510 - thread::Builder::spawn_inner::closure.28492
  31:     0x7ff0217793c0 - thunk::Thunk<(), R>::new::closure.28617
  32:     0x7ff0217792a0 - thunk::F.Invoke<A, R>::invoke::h14044084656094621362
  33:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  34:     0x7ff020236460 - start_thread
  35:     0x7ff01f714769 - clone
  36:                0x0 - <unknown>
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rtthread '::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   PaintTask: Saw ExitMsg, 6 buffers in use
4: Constellation ' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"  ', /home/larsberg/rust/src/libcore/result.rs 0x:7437ff022b384e0 - 
rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7ff022b684e0 - rust_begin_unwind
   6:     0x7ff022b95a50 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7ff021ed5e50 - result::Result<T, E>::unwrap::h729654645766015411
   8:     0x7ff021ed1270 - page::Page::join_layout::h77e9e37f0ad7a7b9jGF
   9:     0x7ff021ecce10 - page::Page::reflow::h45f480bbf3d1d8fbyJF
  10:     0x7ff021f0e5c0 - script_task::ScriptTask::force_reflow::he34bdfa5ca3fad2d1VG
  11:     0x7ff021f22320 - script_task::ScriptTask::handle_resize_event::h1a7b70e29f8fe94bq6G
  12:     0x7ff021ef0a40 - script_task::ScriptTask::handle_event::h55f48c759d43e556tWG
  13:     0x7ff021eec8e0 - script_task::ScriptTask::handle_msgs::hb476a48d6df1ab3bNkG
  14:     0x7ff021eec890 - script_task::ScriptTask::start::h4fd3d00a55f28598DkG
  15:     0x7ff0212d35b0 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10215
  16:     0x7ff0212d3040 - task::spawn_named_with_send_on_failure::closure.10202
  17:     0x7ff0212d2f50 - thunk::Thunk<(), R>::new::closure.10198
  18:     0x7ff0212d2e10 - thunk::F.Invoke<A, R>::invoke::h6057843338654291913
  19:     0x7ff021209570 - thunk::Thunk<A, R>::invoke::h13964921828523259527
  20:     0x7ff02120a270 - thread::Builder::spawn_inner::closure.5356
  21:     0x7ff02120a200 - rt::unwind::try::try_fn::__rust_abi::h16658249750897147825
  22:     0x7ff02120a1c0 - rt::unwind::try::try_fn::h16658249750897147825
  23:     0x7ff022b72980 - rust_try_inner
  24:     0x7ff022b72970 - rust_try
  25:     0x7ff021209600 - rt::unwind::try::h14191389496274021445
  26:     0x7ff021208350 - thread::Builder::spawn_inner::closure.5209
  27:     0x7ff02120b200 - thunk::Thunk<(), R>::new::closure.5380
  28:     0x7ff02120b0e0 - thunk::F.Invoke<A, R>::invoke::h6583845587759592007
  29:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  30:     0x7ff020236460 - start_thread
  31:     0x7ff01f714769 - clone
  32:                0x0 - <unknown>
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7ff022b384e0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7ff022b684e0 - rust_begin_unwind
   6:     0x7ff022b95a50 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7ff021627730 - result::Result<T, E>::unwrap::h5180843107622632845
   8:     0x7ff021627620 - pipeline::Pipeline::force_exit::h52c3481365d26db0MXc
   9:     0x7ff02129fbb0 - constellation::Constellation<LTF, STF>::handle_failure_msg::h1126299388928762774
  10:     0x7ff021291e00 - constellation::Constellation<LTF, STF>::handle_request::h9649638093535241179
  11:     0x7ff02128c9f0 - constellation::Constellation<LTF, STF>::run::h3086737389320972051
  12:     0x7ff021267ec0 - constellation::Constellation<LTF, STF>::start::closure.6966
  13:     0x7ff021267ba0 - task::spawn_named::closure.6959
  14:     0x7ff021267a70 - thunk::Thunk<(), R>::new::closure.6955
  15:     0x7ff0212678b0 - thunk::F.Invoke<A, R>::invoke::h12593442608953116717
  16:     0x7ff021209570 - thunk::Thunk<A, R>::invoke::h13964921828523259527
  17:     0x7ff02120a270 - thread::Builder::spawn_inner::closure.5356
  18:     0x7ff02120a200 - rt::unwind::try::try_fn::__rust_abi::h16658249750897147825
  19:     0x7ff02120a1c0 - rt::unwind::try::try_fn::h16658249750897147825
  20:     0x7ff022b72980 - rust_try_inner
  21:     0x7ff022b72970 - rust_try
  22:     0x7ff021209600 - rt::unwind::try::h14191389496274021445
  23:     0x7ff021208350 - thread::Builder::spawn_inner::closure.5209
  24:     0x7ff02120b200 - thunk::Thunk<(), R>::new::closure.5380
  25:     0x7ff02120b0e0 - thunk::F.Invoke<A, R>::invoke::h6583845587759592007
  26:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  27:     0x7ff020236460 - start_thread
  28:     0x7ff01f714769 - clone
  29:                0x0 - <unknown>
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7ff022b535e0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7ff022b685c0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7ff022b379d0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7ff022b384e0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7ff022b684e0 - rust_begin_unwind
   6:     0x7ff022b95a50 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7ff021a1d770 - result::Result<T, E>::unwrap::h10110199428271554648
   8:     0x7ff021daee00 - dom::bindings::refcounted::Trusted<T>.Drop::drop::h9606933670518923154
   9:     0x7ff021daed50 - dom..bindings..refcounted..Trusted<dom..htmlscriptelement..HTMLScriptElement>::glue_drop.85794::h6430da254f45330c
  10:     0x7ff021daed20 - dom..htmlscriptelement..EventDispatcher::glue_drop.85791::he56051e7f76e55a0
  11:     0x7ff021daefe0 - Box<dom..htmlscriptelement..EventDispatcher>::glue_drop.85797::h1d903b3bada177eb
  12:     0x7ff0212ad750 - Box<script..script_task..Runnable $u2b$$u20$Send$GT$::glue_drop.9440::h681fb27036f03a66
  13:     0x7ff0212ac430 - script..script_task..ScriptMsg::glue_drop.9399::hed3c9ffdf6aea1ac
  14:     0x7ff0212af6c0 - std..sync..mpsc..mpsc_queue..PopResult<script..script_task..ScriptMsg>::glue_drop.9467::hc7943da65077f1ad
  15:     0x7ff0212aef70 - sync::mpsc::shared::Packet<T>::drop_port::h15038377372635129590
  16:     0x7ff0212ad8b0 - sync::mpsc::Receiver<T>.Drop::drop::h2900551443974857450
  17:     0x7ff0212ad830 - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.9446::habfe251b5c0ff5cb
  18:     0x7ff0212ad7b0 - std..sync..mpsc..oneshot..MyUpgrade<script..script_task..ScriptMsg>::glue_drop.9443::hfd5a70a59c34a2b5
  19:     0x7ff0212ac0f0 - std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>::glue_drop.9393::h8c37f8fb9cff0bd5
  20:     0x7ff0212ac0c0 - core..cell..UnsafeCell<std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>>::glue_drop.9390::h94692668922b9e46
  21:     0x7ff0212b1a70 - mem::drop::h5264606723976201668
  22:     0x7ff0212b1770 - arc::Arc<T>.Drop::drop::h6368733882043335226
  23:     0x7ff0212b1740 - alloc..arc..Arc<core..cell..UnsafeCell<std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>>>::glue_drop.9494::hf25c9d9d59978733
  24:     0x7ff0212b1680 - std..sync..mpsc..Flavor<script..script_task..ScriptMsg>::glue_drop.9491::h3989314627fe854c
  25:     0x7ff0212b1650 - core..cell..UnsafeCell<std..sync..mpsc..Flavor<script..script_task..ScriptMsg>>::glue_drop.9488::h16cec079a5f60f9c
  26:     0x7ff0212ad830 - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.9446::habfe251b5c0ff5cb
  27:     0x7ff0212d7ce0 - script..script_task..ScriptTask::glue_drop.10381::h9f2a64378c85f5d4
  28:     0x7ff0212d35b0 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10215
  29:     0x7ff0212d3040 - task::spawn_named_with_send_on_failure::closure.10202
  30:     0x7ff0212d2f50 - thunk::Thunk<(), R>::new::closure.10198
  31:     0x7ff0212d2e10 - thunk::F.Invoke<A, R>::invoke::h6057843338654291913
  32:     0x7ff021209570 - thunk::Thunk<A, R>::invoke::h13964921828523259527
  33:     0x7ff02120a270 - thread::Builder::spawn_inner::closure.5356
  34:     0x7ff02120a200 - rt::unwind::try::try_fn::__rust_abi::h16658249750897147825
  35:     0x7ff02120a1c0 - rt::unwind::try::try_fn::h16658249750897147825
  36:     0x7ff022b72980 - rust_try_inner
  37:     0x7ff022b72970 - rust_try
  38:     0x7ff021209600 - rt::unwind::try::h14191389496274021445
  39:     0x7ff021208350 - thread::Builder::spawn_inner::closure.5209
  40:     0x7ff02120b200 - thunk::Thunk<(), R>::new::closure.5380
  41:     0x7ff02120b0e0 - thunk::F.Invoke<A, R>::invoke::h6583845587759592007
  42:     0x7ff022b56e90 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  43:     0x7ff020236460 - start_thread
  44:     0x7ff01f714769 - clone
  45:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

**Comment by nox** [comment]
Is this still true?

**Comment by mrobinson** [comment]
This does not appear to crash any longer.
