### ISSUE TITLE
Error while navigating to Wikipedia

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#5081]
```
./mach run https://en.wikipedia.org

pci id for fd 4: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
ERROR:js::rust: Error at https://bits.wikimedia.org/en.wikipedia.org/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector&*:77: TypeError: document.write is not a function

ERROR:net::image::base: stb_image failed: stbi_load_from_memory failed
thread 'LayoutTask' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7f8dd9459dd0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7f8dd946edb0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7f8dd943e1c0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7f8dd943ecd0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7f8dd946ecd0 - rust_begin_unwind
   6:     0x7f8dd949c240 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7f8dd8bdf220 - result::Result<T, E>::unwrap::h13355869393254291968
   8:     0x7f8dd8bdef30 - font_context::FontContext::create_layout_font::h9bcb781d6eb2a6e5sfe
   9:     0x7f8dd8bdff80 - font_context::FontContext::get_layout_font_group_for_style::h971455347667d82azge
  10:     0x7f8dd81a6840 - text::TextRunScanner::flush_clump_to_list::h310a7534f27f2cdaZRq
  11:     0x7f8dd8004720 - text::TextRunScanner::scan_for_runs::h2de72636659c75d3kOq
  12:     0x7f8dd800df60 - construct::FlowConstructor<'a>::build_flow_for_block_starting_with_fragment::hf101b55a26636328Bkd
  13:     0x7f8dd80137c0 - construct::FlowConstructor<'a>::build_flow_for_block::ha252a0fcfe0010b4rnd
  14:     0x7f8dd8016230 - construct::FlowConstructor<'a>::build_flow_for_nonfloated_block::h8fd3fb563ae507584od
  15:     0x7f8dd800f7f0 - construct::FlowConstructor<'a>.PostorderNodeMutTraversal::process::h4a1a3d2a1347f302MRd
  16:     0x7f8dd81953e0 - traversal::ConstructFlows<'a>.PostorderDomTraversal::process::h7b6448ac097211abIpr
  17:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  18:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  19:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  20:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  21:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  22:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  23:     0x7f8dd819ca20 - sequential::traverse_dom_preorder::doit::h0c42edabf08647dfUmo
  24:     0x7f8dd817a100 - sequential::traverse_dom_preorder::h3125d2f6eb9905e3Hmo
  25:     0x7f8dd8179e50 - layout_task::LayoutTask::handle_reflow::closure.32059
  26:     0x7f8dd8179bd0 - time::profile::h2410418668313955435
  27:     0x7f8dd8169ec0 - layout_task::LayoutTask::handle_reflow::h990f71e758cd30eabYk
  28:     0x7f8dd8166730 - layout_task::LayoutTask::handle_script_request::closure.31863
  29:     0x7f8dd8166540 - time::profile::h7689285696206574362
  30:     0x7f8dd815d750 - layout_task::LayoutTask::handle_script_request::h555be6c1fdf085ee3zk
  31:     0x7f8dd814b770 - layout_task::LayoutTask::handle_request::ha51a3eaacef10874Gwk
  32:     0x7f8dd811a080 - layout_task::LayoutTask::start::he5878db1f7c6fae7rvk
  33:     0x7f8dd81054b0 - layout_task::LayoutTask.LayoutTaskFactory::create::closure.30549
  34:     0x7f8dd8104f00 - task::spawn_named_with_send_on_failure::closure.30536
  35:     0x7f8dd8104e10 - thunk::Thunk<(), R>::new::closure.30532
  36:     0x7f8dd8104cd0 - thunk::F.Invoke<A, R>::invoke::h5985422038932469791
  37:     0x7f8dd807c960 - thunk::Thunk<A, R>::invoke::h10618962875019408824
  38:     0x7f8dd807d660 - thread::Builder::spawn_inner::closure.28600
  39:     0x7f8dd807d5f0 - rt::unwind::try::try_fn::__rust_abi::h14908835170374481435
  40:     0x7f8dd807d5b0 - rt::unwind::try::try_fn::h14908835170374481435
  41:     0x7f8dd9479170 - rust_try_inner
  42:     0x7f8dd9479160 - rust_try
  43:     0x7f8dd807c9f0 - rt::unwind::try::h18213326416216814531
  44:     0x7f8dd807b740 - thread::Builder::spawn_inner::closure.28499
  45:     0x7f8dd807e5f0 - thunk::Thunk<(), R>::new::closure.28624
  46:     0x7f8dd807e4d0 - thunk::F.Invoke<A, R>::invoke::h4142950305457891742
  47:     0x7f8dd945d680 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  48:     0x7f8dd6b3b2b0 - start_thread
  49:     0x7f8dd6046249 - __clone
  50:                0x0 - <unknown>
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7f8dd9459dd0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7f8dd946edb0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7f8dd943e1c0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7f8dd943ecd0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7f8dd946ecd0 - rust_begin_unwind
   6:     0x7f8dd949c240 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7f8dd87dcd30 - result::Result<T, E>::unwrap::h12913032266632697121
   8:     0x7f8dd87d8150 - page::Page::join_layout::h06be9a84bc1f18fa0NF
   9:     0x7f8dd87d3cf0 - page::Page::reflow::h7cd07b0483f91070fRF
  10:     0x7f8dd8765d60 - page::Page::flush_layout::he23dcff53a57efaaVEF
  11:     0x7f8dd85f6560 - dom::window::JSRef<'a, Window>.WindowHelpers::flush_layout::hd0b8a2e9a08966efo0B
  12:     0x7f8dd881aad0 - script_task::ScriptTask::load::h6c46c9df7d00644dzQG
  13:     0x7f8dd88191f0 - script_task::ScriptTask::handle_msg_from_constellation::h119e9aa0f5cfe33ftzG
  14:     0x7f8dd87f37c0 - script_task::ScriptTask::handle_msgs::h861cc37c496ee804isG
  15:     0x7f8dd87f3770 - script_task::ScriptTask::start::hdd9d26dadf2649b78rG
  16:     0x7f8dd7bd8860 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10217
  17:     0x7f8dd7bd82f0 - task::spawn_named_with_send_on_failure::closure.10204
  18:     0x7f8dd7bd8200 - thunk::Thunk<(), R>::new::closure.10200
  19:     0x7f8dd7bd80c0 - thunk::F.Invoke<A, R>::invoke::h3813742927069182881
  20:     0x7f8dd7b0e830 - thunk::Thunk<A, R>::invoke::h11113008793583676785
  21:     0x7f8dd7b0f530 - thread::Builder::spawn_inner::closure.5358
  22:     0x7f8dd7b0f4c0 - rt::unwind::try::try_fn::__rust_abi::h8544738732613659633
  23:     0x7f8dd7b0f480 - rt::unwind::try::try_fn::h8544738732613659633
  24:     0x7f8dd9479170 - rust_try_inner
  25:     0x7f8dd9479160 - rust_try
  26:     0x7f8dd7b0e8c0 - rt::unwind::try::h17804846966167590403
  27:     0x7f8dd7b0d610 - thread::Builder::spawn_inner::closure.5211
  28:     0x7f8dd7b104c0 - thunk::Thunk<(), R>::new::closure.5382
  29:     0x7f8dd7b103a0 - thunk::F.Invoke<A, R>::invoke::h15238565985459708238
  30:     0x7f8dd945d680 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  31:     0x7f8dd6b3b2b0 - start_thread
  32:     0x7f8dd6046249 - __clone
  33:                0x0 - <unknown>
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7f8dd9459dd0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7f8dd946edb0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7f8dd943e1c0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7f8dd943ecd0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7f8dd946ecd0 - rust_begin_unwind
   6:     0x7f8dd949c240 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7f8dd7f2c970 - result::Result<T, E>::unwrap::h6539797247766742893
   8:     0x7f8dd7f2c860 - pipeline::Pipeline::force_exit::h6556f63fbd2ec01dMXc
   9:     0x7f8dd7ba4e60 - constellation::Constellation<LTF, STF>::handle_failure_msg::h17371403062027698862
  10:     0x7f8dd7b970b0 - constellation::Constellation<LTF, STF>::handle_request::h10523698902739598188
  11:     0x7f8dd7b91cb0 - constellation::Constellation<LTF, STF>::run::h678605415553903314
  12:     0x7f8dd7b6d180 - constellation::Constellation<LTF, STF>::start::closure.6968
  13:     0x7f8dd7b6ce60 - task::spawn_named::closure.6961
  14:     0x7f8dd7b6cd30 - thunk::Thunk<(), R>::new::closure.6957
  15:     0x7f8dd7b6cb70 - thunk::F.Invoke<A, R>::invoke::h6351167051772042247
  16:     0x7f8dd7b0e830 - thunk::Thunk<A, R>::invoke::h11113008793583676785
  17:     0x7f8dd7b0f530 - thread::Builder::spawn_inner::closure.5358
  18:     0x7f8dd7b0f4c0 - rt::unwind::try::try_fn::__rust_abi::h8544738732613659633
  19:     0x7f8dd7b0f480 - rt::unwind::try::try_fn::h8544738732613659633
  20:     0x7f8dd9479170 - rust_try_inner
  21:     0x7f8dd9479160 - rust_try
  22:     0x7f8dd7b0e8c0 - rt::unwind::try::h17804846966167590403
  23:     0x7f8dd7b0d610 - thread::Builder::spawn_inner::closure.5211
  24:     0x7f8dd7b104c0 - thunk::Thunk<(), R>::new::closure.5382
  25:     0x7f8dd7b103a0 - thunk::F.Invoke<A, R>::invoke::h15238565985459708238
  26:     0x7f8dd945d680 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  27:     0x7f8dd6b3b2b0 - start_thread
  28:     0x7f8dd6046249 - __clone
  29:                0x0 - <unknown>
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:     0x7f8dd9459dd0 - sys::backtrace::write::ha4a9415e174db438Rsy
   2:     0x7f8dd946edb0 - failure::on_fail::hac5db0a0a6a39fd6LWF
   3:     0x7f8dd943e1c0 - rt::unwind::begin_unwind_inner::h6e98ac6f3dbe1e23iBF
   4:     0x7f8dd943ecd0 - rt::unwind::begin_unwind_fmt::h3ff55cf900dead24OzF
   5:     0x7f8dd946ecd0 - rust_begin_unwind
   6:     0x7f8dd949c240 - panicking::panic_fmt::he4401c5a20a31443zow
   7:     0x7f8dd8322ac0 - result::Result<T, E>::unwrap::h385261726882178063
   8:     0x7f8dd86b6740 - dom::bindings::refcounted::Trusted<T>.Drop::drop::h9805745430275012596
   9:     0x7f8dd86b6690 - dom..bindings..refcounted..Trusted<dom..htmlscriptelement..HTMLScriptElement>::glue_drop.85833::he29fae49d1a100f2
  10:     0x7f8dd86b6660 - dom..htmlscriptelement..EventDispatcher::glue_drop.85830::hd61a40e047f14eb4
  11:     0x7f8dd86b6920 - Box<dom..htmlscriptelement..EventDispatcher>::glue_drop.85836::h131bea24d0023b99
  12:     0x7f8dd7bb2a00 - Box<script..script_task..Runnable $u2b$$u20$Send$GT$::glue_drop.9442::hcc652b9f94db9ffb
  13:     0x7f8dd7bb16e0 - script..script_task..ScriptMsg::glue_drop.9401::h03a011261ccd3920
  14:     0x7f8dd7bb4970 - std..sync..mpsc..mpsc_queue..PopResult<script..script_task..ScriptMsg>::glue_drop.9469::h5aff57abc465cccf
  15:     0x7f8dd7bb4220 - sync::mpsc::shared::Packet<T>::drop_port::h9567203770652552810
  16:     0x7f8dd7bb2b60 - sync::mpsc::Receiver<T>.Drop::drop::h1157393948056023480
  17:     0x7f8dd7bb2ae0 - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.9448::hbd61fa937369c336
  18:     0x7f8dd7bb2a60 - std..sync..mpsc..oneshot..MyUpgrade<script..script_task..ScriptMsg>::glue_drop.9445::h8d708acc59fc149b
  19:     0x7f8dd7bb13a0 - std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>::glue_drop.9395::h6f58515979c66943
  20:     0x7f8dd7bb1370 - core..cell..UnsafeCell<std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>>::glue_drop.9392::h3d684538b95df47d
  21:     0x7f8dd7bb6d20 - mem::drop::h2792231746665220377
  22:     0x7f8dd7bb6a20 - arc::Arc<T>.Drop::drop::h5737596153498441395
  23:     0x7f8dd7bb69f0 - alloc..arc..Arc<core..cell..UnsafeCell<std..sync..mpsc..oneshot..Packet<script..script_task..ScriptMsg>>>::glue_drop.9496::h10faccf8388f5b88
  24:     0x7f8dd7bb6930 - std..sync..mpsc..Flavor<script..script_task..ScriptMsg>::glue_drop.9493::hd30322a106719a4e
  25:     0x7f8dd7bb6900 - core..cell..UnsafeCell<std..sync..mpsc..Flavor<script..script_task..ScriptMsg>>::glue_drop.9490::hb1efa3c6ec157d1d
  26:     0x7f8dd7bb2ae0 - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.9448::hbd61fa937369c336
  27:     0x7f8dd7bdcf90 - script..script_task..ScriptTask::glue_drop.10383::h92209d53c229835e
  28:     0x7f8dd7bd8860 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10217
  29:     0x7f8dd7bd82f0 - task::spawn_named_with_send_on_failure::closure.10204
  30:     0x7f8dd7bd8200 - thunk::Thunk<(), R>::new::closure.10200
  31:     0x7f8dd7bd80c0 - thunk::F.Invoke<A, R>::invoke::h3813742927069182881
  32:     0x7f8dd7b0e830 - thunk::Thunk<A, R>::invoke::h11113008793583676785
  33:     0x7f8dd7b0f530 - thread::Builder::spawn_inner::closure.5358
  34:     0x7f8dd7b0f4c0 - rt::unwind::try::try_fn::__rust_abi::h8544738732613659633
  35:     0x7f8dd7b0f480 - rt::unwind::try::try_fn::h8544738732613659633
  36:     0x7f8dd9479170 - rust_try_inner
  37:     0x7f8dd9479160 - rust_try
  38:     0x7f8dd7b0e8c0 - rt::unwind::try::h17804846966167590403
  39:     0x7f8dd7b0d610 - thread::Builder::spawn_inner::closure.5211
  40:     0x7f8dd7b104c0 - thunk::Thunk<(), R>::new::closure.5382
  41:     0x7f8dd7b103a0 - thunk::F.Invoke<A, R>::invoke::h15238565985459708238
  42:     0x7f8dd945d680 - sys::thread::thread_start::hc5bbfed3723b5236ICB
  43:     0x7f8dd6b3b2b0 - start_thread
  44:     0x7f8dd6046249 - __clone
  45:                0x0 - <unknown>
thread panicked while panicking. aborting.
Error running mach:

    ['run', 'https://en.wikipedia.org']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/servo', 'https://en.wikipedia.org']' returned non-zero exit status -4

  File "/home/keith/Workspace/servo/python/servo/post_build_commands.py", line 83, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by jdm** [comment]
Looks like the same as #5081.

**Comment by KiChjang** [comment]
This issue IS #5081. Did you mean to point to another issue instead?

**Comment by jdm** [comment]
Yep, #4503.

**Comment by frewsxcv** [comment]
I'm able to navigate to Wikipedia with the current master, can this be closed?

**Comment by jdm** [comment]
What operating system are you using?

**Comment by frewsxcv** [comment]
OSX 10.10

**Comment by KiChjang** [comment]
The latest commit to master allows me to navigate to WIkipedia, closing this issue.
