### ISSUE TITLE
Update web-platform-tests.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5085]
I started on this: <https://github.com/servo/servo/compare/servo:master...Ms2ger:wpt_20150228>, but I get
```
Traceback (most recent call last):
  File "tests/wpt/run.py", line 49, in <module>
    sys.exit(0 if main() else 1)
  File "tests/wpt/run.py", line 46, in main
    return run_tests(**kwargs)
  File "tests/wpt/run.py", line 30, in run_tests
    return wptrunner.run_tests(**kwargs)
  File "tests/wpt/_virtualenv/local/lib/python2.7/site-packages/wptrunner/wptrunner.py", line 369, in run_tests
    do_delayed_imports(serve_root)
  File "tests/wpt/_virtualenv/local/lib/python2.7/site-packages/wptrunner/wptrunner.py", line 78, in do_delayed_imports
    import serve
  File "tests/wpt/web-platform-tests/tools/serve/__init__.py", line 1, in <module>
    import serve
  File "tests/wpt/web-platform-tests/tools/serve/serve.py", line 16, in <module>
    from .. import localpaths
ValueError: Attempted relative import beyond toplevel package
```

CC @jgraham

**Comment by dmarcos** [comment]
@jdm I see this error when running ./mach test-wpt. I'm on OSX (10.10.2)

**Comment by dmarcos** [comment]
I think is a regression introduced by https://github.com/servo/servo/commit/c6ab60dbfc6da7b4f800c9e40893c8b58413960c

**Comment by dmarcos** [comment]
Everything works fine on https://github.com/servo/servo/commit/203240c1d82b780ce49261d8b47e6cbe6af50950 (parent of https://github.com/servo/servo/commit/a8553c36064f336fb3e2b0ab4e62a19ced8561f6)

**Comment by jdm** [comment]
You'll need to remove the _virtualenv directory in tests/wpt.

**Comment by dmarcos** [comment]
@jdm Thanks. I can run them now
