### ISSUE TITLE
Intermittent reftest timeout

### ISSUE THREAD

**Issue by jdm** [servo/servo#5142]
```
 (view as text)

./mach test-ref --kind cpu
 in dir /home/servo/buildbot/slave/linux1/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['./mach', 'test-ref', '--kind', 'cpu']
 environment:
  ADDRFAM=inet
  DISPLAY=:0
  HOME=/home/servo
  IFACE=eth0
  LOGICAL=eth0
  METHOD=dhcp
  PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  PWD=/home/servo/buildbot/slave/linux1/build
  RUST_BACKTRACE=1
  SERVO_HEADLESS=1
  TERM=linux
  UPSTART_EVENTS=local-filesystems net-device-up
  UPSTART_INSTANCE=
  UPSTART_JOB=buildbot-slave
 using PTY: False
Synchronizing submodule url for 'support/android-rs-glue'
Synchronizing submodule url for 'tests/wpt/web-platform-tests'
Scanning /home/servo/buildbot/slave/linux1/build/tests/ref for manifests

	/home/servo/buildbot/slave/linux1/build/tests/ref/basic.list [246 tests]
	/home/servo/buildbot/slave/linux1/build/tests/ref/csswg/css21/css21.list [2 tests]

running 248 tests
test abs_float_pref_width_a.html == abs_float_pref_width_ref.html ... ok
test after_block_iteration.html == after_block_iteration_ref.html ... ok
test alpha_png_a.html == alpha_png_b.html ... ok
test acid1_a.html == acid1_b.html ... ok
test acid2_noscroll.html == acid2_ref_broken.html ... ok
test ../html/acid2.html != acid2_ref.html ... ok
test append_style_a.html == append_style_b.html ... ok
test anon_block_inherit_a.html == anon_block_inherit_b.html ... ok
test attr_exists_selector.html == attr_exists_selector_ref.html ... ok
test attr_selector_case_sensitivity.html == attr_selector_case_sensitivity_ref.html ... ok
test background_external_stylesheet.html == background_ref.html ... ok
test background_image_position_a.html == background_image_position_ref.html ... ok
test background_none_a.html == background_none_b.html ... ok
test background_position_a.html == background_position_b.html ... ok
test background_position_keyword.html == background_position_b.html ... ok
test background_position_percent.html == background_position_b.html ... ok
test background_position_shorthand.html == background_position_shorthand_ref.html ... ok
test background_repeat_both_a.html == background_repeat_both_b.html ... ok
test background_repeat_none_a.html == background_repeat_none_b.html ... ok
test background_repeat_x_a.html == background_repeat_x_b.html ... ok
test background_repeat_y_a.html == background_repeat_y_b.html ... ok
test background_size_shorthand_a.html == background_size_shorthand_ref.html ... ok
test background_size_a.html == background_size_ref.html ... ok
test background_style_attr.html == background_ref.html ... ok
test basic_width_px.html == basic_width_em.html ... ok
test block-formatting-contexts-005.htm == block-formatting-contexts-005-ref.htm ... ok
test block_formatting_context_a.html == block_formatting_context_ref.html ... ok
test block_formatting_context_complex_a.html == block_formatting_context_complex_ref.html ... ok
test block-formatting-contexts-006.htm == block-formatting-contexts-006-ref.htm ... ok
test block_formatting_context_containing_floats_a.html == block_formatting_context_containing_floats_ref.html ... ok
test block_formatting_context_relative_a.html == block_formatting_context_ref.html ... ok
test block_formatting_context_translation_a.html == block_formatting_context_translation_ref.html ... ok
test block_image.html != noteq_500x300_white.html ... ok
test block_image.html == 500x300_green.html ... ok
test block_replaced_content_a.html == block_replaced_content_ref.html ... ok
test block_replaced_content_b.html == block_replaced_content_ref.html ... ok
test border_black_groove.html != border_black_solid.html ... ok
test border_black_ridge.html != border_black_groove.html ... ok
test border_black_ridge.html != border_black_solid.html ... ok
test border_code_tag.html == border_code_tag_ref.html ... ok
test border_radius_clip_a.html == border_radius_clip_ref.html ... ok
test border_radius_overlapping_a.html == border_radius_overlapping_ref.html ... ok
test box_shadow_blur_a.html != box_shadow_blur_ref.html ... ok
test border_style_none_a.html == border_style_none_b.html ... ok
test box_shadow_border_box_a.html == box_shadow_border_box_ref.html ... ok
test borders_a.html == borders_b.html ... ok
test box_shadow_default_color_a.html == box_shadow_default_color_ref.html ... ok
test box_shadow_inset_a.html == box_shadow_inset_ref.html ... ok
test box_shadow_paint_order_a.html == box_shadow_paint_order_ref.html ... ok
test box_shadow_inset_parsing_a.html == box_shadow_inset_parsing_ref.html ... ok
test box_shadow_spread_a.html == box_shadow_spread_ref.html ... ok
test box_sizing_border_box_a.html == box_sizing_border_box_ref.html ... ok
test box_sizing_sanity_check_a.html == box_sizing_sanity_check_ref.html ... ok
test br.html == br-ref.html ... ok
test canvas_transform_a.html == canvas_transform_ref.html ... ok
test canvas_lineto_a.html == canvas_lineto_ref.html ... ok
test clear_generated_content_table_a.html == clear_generated_content_table_ref.html ... ok
test case-insensitive-font-family.html == case-insensitive-font-family-ref.html ... ok
test clip_a.html == clip_ref.html ... ok
test data_img_a.html == data_img_b.html ... ok
test empty_cells_a.html == empty_cells_ref.html ... ok
test filter_opacity_a.html == filter_opacity_ref.html ... ok
test filter_sepia_a.html == filter_sepia_ref.html ... ok
test first_of_type_pseudo_a.html == first_of_type_pseudo_b.html ... ok
test first_child_pseudo_a.html == first_child_pseudo_b.html ... ok
test fixed_width_overrides_child_intrinsic_width_a.html == fixed_width_overrides_child_intrinsic_width_ref.html ... ok
test float_clearance_a.html == float_clearance_ref.html ... ok
test float_intrinsic_width_a.html == float_intrinsic_width_ref.html ... ok
test float_intrinsic_height.html == float_intrinsic_height_ref.html ... ok
test float_right_intrinsic_width_a.html == float_right_intrinsic_width_ref.html ... ok
test float_table_a.html == float_table_ref.html ... ok
test floated_generated_content_a.html == floated_generated_content_b.html ... ok
test floated_list_item_a.html == floated_list_item_ref.html ... ok
test floated_table_with_margin_a.html == floated_table_with_margin_ref.html ... ok
test font_size.html == font_size_ref.html ... ok
test height_compute_reset.html == height_compute.html ... ok
test font_style.html == font_style_ref.html ... ok
test hello_a?foo#bar.html == hello_b.html ... ok
test hide_after_create.html == hide_after_create_ref.html ... ok
test iframe/hide_and_show.html == iframe/hide_and_show_ref.html ... ok
test iframe/bg_color.html == iframe/bg_color_ref.html ... ok
test iframe/hide_layers1.html == iframe/hide_layers_ref.html ... ok
test iframe/multiple_external.html == iframe/multiple_external_ref.html ... ok
test iframe/overflow.html == iframe/overflow_ref.html ... ok
test iframe/positioning_margin.html == iframe/positioning_margin_ref.html ... ok
test iframe/simple.html == iframe/simple_ref.html ... ok
test iframe/simple_inline_default.html == iframe/simple_inline_default_ref.html ... ok
test iframe/simple_inline_height.html == iframe/simple_inline_height_ref.html ... ok
test iframe/simple_inline_max.html == iframe/simple_inline_max_ref.html ... ok
test iframe/simple_inline_min.html == iframe/simple_inline_min_ref.html ... ok
test iframe/simple_inline_width.html == iframe/simple_inline_width_ref.html ... ok
test iframe/simple_inline_width_height.html == iframe/simple_inline_width_height_ref.html ... ok
test iframe/simple_inline_width_percentage.html == iframe/simple_inline_width_percentage_ref.html ... ok
test image_rendering_auto_a.html != image_rendering_pixelated_a.html ... ok
test image_rendering_pixelated_a.html == image_rendering_pixelated_ref.html ... ok
test img_block_display_a.html == img_block_display_ref.html ... ok
test img_block_maxwidth_a.html == img_block_maxwidth_ref.html ... ok
test img_block_maxwidth_b.html == img_block_maxwidth_ref.html ... ok
test img_dynamic_remove.html == img_dynamic_remove_ref.html ... ok
test img_simple.html != img_simple_ref.html ... ok
test img_size_a.html == img_size_b.html ... ok
test incremental_float_a.html == incremental_float_ref.html ... ok
test inline_background_a.html != inline_background_ref.html ... ok
test inline_block_baseline_a.html == inline_block_baseline_ref.html ... ok
test inline_block_border_a.html == inline_block_border_ref.html ... ok
test inline_block_img_a.html == inline_block_img_ref.html ... ok
test inline_block_margin_a.html == inline_block_margin_ref.html ... ok
test inline_block_min_width.html == inline_block_min_width_ref.html ... ok
test inline_block_overflow.html == inline_block_overflow_ref.html ... ok
test inline_block_overflow_hidden_a.html == inline_block_overflow_hidden_ref.html ... ok
test inline_block_parent_width_percentage.html == inline_block_parent_width_ref.html ... ok
test inline_block_parent_width.html == inline_block_parent_width_ref.html ... ok
test inline_block_parent_padding_a.html == inline_block_parent_padding_ref.html ... ok
test inline_block_percentage_height_a.html == inline_block_percentage_height_ref.html ... ok
test inline_block_with_margin_a.html == inline_block_with_margin_ref.html ... ok
test inline_element_border_a.html == inline_element_border_ref.html ... ok
test inline_hypothetical_box_a.html == inline_hypothetical_box_ref.html ... ok
test inline_padding_a.html == inline_padding_b.html ... ok
test inline_whitespace_a.html == inline_whitespace_ref.html ... ok
test inline_whitespace_b.html == inline_whitespace_ref.html ... ok
test input_height_a.html != input_height_ref.html ... ok
test inset.html == inset_ref.html ... ok
test inset_blackborder.html != blackborder_ref.html ... ok
test issue-1324.html == issue-1324-ref.html ... ok
test last_child_pseudo_a.html == last_child_pseudo_b.html ... ok
test last_of_type_pseudo_a.html == last_of_type_pseudo_b.html ... ok
test legacy_table_border_attribute_a.html == legacy_table_border_attribute_ref.html ... ok
test legacy_input_size_attribute_override_a.html == legacy_input_size_attribute_override_ref.html ... ok
test legacy_td_bgcolor_attribute_a.html == legacy_td_bgcolor_attribute_ref.html ... ok
test legacy_td_width_attribute_a.html == legacy_td_width_attribute_ref.html ... ok
test letter_spacing_a.html == letter_spacing_ref.html ... ok
test linear_gradients_corners_a.html != linear_gradients_corners_ref.html ... ok
test line_height_a.html == line_height_ref.html ... ok
test linear_gradients_lengths_a.html == linear_gradients_lengths_ref.html ... ok
test linear_gradients_parsing_a.html == linear_gradients_parsing_ref.html ... ok
test linear_gradients_reverse_a.html == linear_gradients_reverse_ref.html ... ok
test linear_gradients_smoke_a.html != linear_gradients_smoke_ref.html ... ok
test linebreak_inline_span_a.html == linebreak_inline_span_b.html ... ok
test linebreak_simple_a.html == linebreak_simple_b.html ... ok
test list_style_position_a.html == list_style_position_ref.html ... ok
test list_style_type_a.html != list_style_type_ref.html ... ok
test link_style_order.html == link_style_order_ref.html ... ok
test many_brs_a.html == many_brs_ref.html ... ok
test margin_a.html == margin_b.html ... ok
test max_width_simple_a.html == max_width_simple_b.html ... ok
test margins_inside_floats_a.html == margins_inside_floats_ref.html ... ok
test max_width_float_simple_a.html == max_width_float_simple_b.html ... ok
test min_max_height_a.html == min_max_height_b.html ... ok
test min_width_float_simple_a.html == min_width_float_simple_b.html ... ok
test min_width_simple_a.html == min_width_simple_b.html ... ok
test minimum_line_height_a.html == minimum_line_height_b.html ... ok
test mix_blend_mode_a.html == mix_blend_mode_ref.html ... ok
test multiple_css_class_a.html == multiple_css_class_b.html ... ok
test negative_margin_uncle_a.html == negative_margin_uncle_b.html ... ok
test negative_margins_a.html == negative_margins_b.html ... ok
test noscript.html == noscript_ref.html ... ok
test noteq_attr_exists_selector.html != attr_exists_selector_ref.html ... ok
test nth_child_pseudo_a.html == nth_child_pseudo_b.html ... ok
test nth_last_child_pseudo_a.html == nth_last_child_pseudo_b.html ... ok
test nth_last_of_type_pseudo_a.html == nth_last_of_type_pseudo_b.html ... ok
test nth_of_type_pseudo_a.html == nth_of_type_pseudo_b.html ... ok
test object_element_a.html == object_element_b.html ... ok
test only_child_pseudo_a.html == only_child_pseudo_b.html ... ok
test only_of_type_pseudo_a.html == only_of_type_pseudo_b.html ... ok
test opacity_simple_a.html == opacity_simple_ref.html ... ok
test opacity_stacking_context_a.html == opacity_stacking_context_ref.html ... ok
test outline_offset_a.html == outline_offset_ref.html ... ok
test outlines_simple_a.html == outlines_simple_ref.html ... ok
test outlines_wrap_a.html == outlines_wrap_ref.html ... ok
test outset_blackborder.html != blackborder_ref.html ... ok
test outset.html == outset_ref.html ... ok
test overconstrained_block.html != overconstrained_block_ref.html ... ok
test overflow_auto.html == overflow_simple_b.html ... ok
test overflow_scroll.html == overflow_simple_b.html ... ok
test overflow_simple_a.html == overflow_simple_b.html ... ok
test overflow_wrap_a.html == overflow_wrap_ref.html ... ok
test overflow_xy_a.html == overflow_xy_ref.html ... ok
test percent_height.html == percent_height_ref.html ... ok
test percentage_height_float_a.html == percentage_height_float_ref.html ... ok
test png_rgba_colorspace_a.html == png_rgba_colorspace_b.html ... ok
test percentage_height_root.html == percentage_height_root_ref.html ... ok
test position_abs_cb_with_non_cb_kid_a.html == position_abs_cb_with_non_cb_kid_b.html ... ok
test position_abs_height_width_a.html == position_abs_height_width_b.html ... ok
test position_abs_left_a.html == position_abs_left_b.html ... ok
test position_abs_margin_top_percentage_a.html == position_abs_margin_top_percentage_b.html ... ok
test position_abs_nested_a.html == position_abs_nested_b.html ... ok
test position_abs_pseudo_a.html == position_abs_pseudo_b.html ... ok
test position_abs_replaced_simple_a.html == position_abs_replaced_simple_b.html ... ok
test position_abs_static_y_a.html == position_abs_static_y_b.html ... ok
test position_abs_width_percentage_a.html == position_abs_width_percentage_b.html ... ok
test position_fixed_overflow_a.html == position_fixed_overflow_b.html ... ok
test position_fixed_background_color_a.html == position_fixed_background_color_b.html ... ok
test position_fixed_tile_edge.html == position_fixed_tile_edge_ref.html ... ok
test position_fixed_tile_edge_3.html == position_fixed_tile_edge_ref.html ... ok
test position_fixed_tile_edge_2.html == position_fixed_tile_edge_ref.html ... ok
test position_relative_a.html == position_relative_b.html ... ok
test position_relative_top_percentage_a.html == position_relative_top_percentage_b.html ... ok
test pre_ignorable_whitespace_a.html == pre_ignorable_whitespace_ref.html ... ok
test pseudo_element_a.html == pseudo_element_b.html ... ok
test pseudo_inherit.html == pseudo_inherit_ref.html ... ok
test root_height_a.html == root_height_b.html ... ok
test root_margin_collapse_a.html == root_margin_collapse_b.html ... ok
test root_pseudo_a.html == root_pseudo_b.html ... ok
test setattribute_id_restyle_a.html == setattribute_id_restyle_b.html ... ok
test stacking_context_overflow_a.html == stacking_context_overflow_ref.html ... ok
test stacking_context_overflow_relative_outline_a.html == stacking_context_overflow_relative_outline_ref.html ... ok
test table_auto_width.html == table_auto_width_ref.html ... ok
test table_caption_bottom_a.html == table_caption_bottom_ref.html ... ok
test table_caption_top_a.html == table_caption_top_ref.html ... ok
test table_colspan_fixed_a.html == table_colspan_fixed_ref.html ... ok
test table_colspan_simple_a.html == table_colspan_simple_ref.html ... ok
test table_containing_block_a.html == table_containing_block_ref.html ... ok
test table_expansion_to_fit_a.html == table_expansion_to_fit_ref.html ... ok
test table_percentage_capping_a.html == table_percentage_capping_ref.html ... ok
test table_padding_a.html == table_padding_ref.html ... ok
test table_percentage_width_a.html == table_percentage_width_ref.html ... ok
test text_align_complex_a.html == text_align_complex_ref.html ... ok
test text_align_justify_a.html == text_align_justify_ref.html ... ok
test text_decoration_cached.html == text_decoration_cached_ref.html ... ok
test text_decoration_smoke_a.html != text_decoration_smoke_ref.html ... ok
test text_indent_a.html == text_indent_ref.html ... ok
test text_justify_none_a.html == text_justify_none_ref.html ... ok
test text_overflow_a.html != text_overflow_ref.html ... ok
test text_overflow_basic_a.html == text_overflow_basic_ref.html ... ok
test text_shadow_blur_a.html == text_shadow_blur_ref.html ... ok
test text_shadow_decorations_a.html == text_shadow_decorations_ref.html ... ok
test text_shadow_simple_a.html == text_shadow_simple_ref.html ... ok
test text_transform_lowercase_a.html == text_transform_lowercase_ref.html ... ok
test text_transform_capitalize_a.html == text_transform_capitalize_ref.html ... ok
test text_transform_none_a.html == text_transform_none_ref.html ... ok
test text_transform_uppercase_a.html == text_transform_uppercase_ref.html ... ok
test upper_id_attr.html == upper_id_attr_ref.html ... ok
test vertical-lr-blocks.html == vertical-lr-blocks_ref.html ... ok
test vertical_align_sub_a.html == vertical_align_sub_ref.html ... ok
test vertical_align_bottom_a.html == vertical_align_bottom_ref.html ... ok
test vertical_align_super_a.html == vertical_align_super_ref.html ... ok
test vertical_align_text_bottom_a.html == vertical_align_text_bottom_ref.html ... ok
test vertical_align_text_top_a.html == vertical_align_text_top_ref.html ... ok
test vertical_align_top_a.html == vertical_align_top_ref.html ... ok
test vertical_align_top_bottom_a.html == vertical_align_top_bottom_ref.html ... ok
test vertical_align_top_span_a.html == vertical_align_top_span_ref.html ... ok
test visibility_hidden.html == visibility_hidden_ref.html ... ok
test whitespace_nowrap_a.html == whitespace_nowrap_ref.html ... ok
test whitespace_pre.html == whitespace_pre_ref.html ... ok
test width_nonreplaced_block_simple_a.html == width_nonreplaced_block_simple_b.html ... ok
test word_break_a.html == word_break_ref.html ... ok
test word_spacing_a.html == word_spacing_ref.html ... ok

command timed out: 1200 seconds without output running ['./mach', 'test-ref', '--kind', 'cpu'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1339.513798
```

**Comment by JIoJIaJIu** [comment]
The problem  is in deadlock, workaround - starting two process at the same time
```
.components/servo/target/reftest-* cpu tests/ref
```

```gdb
#0  0x00007f70d73fc9bc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f70d7d300a5 in thread::Thread::park::hf0b293306356d169Vnu ()
#2  0x00007f70d7d12623 in sync::mpsc::blocking::WaitToken::wait::h6094679ce92db2a0vxu ()
#3  0x00007f70d7c9a7b8 in sync::mpsc::Receiver$LT$T$GT$::recv::h17799599843542093549 ()
#4  0x00007f70d7c8904d in run_tests_console::h026e6c19704c1297DNb ()
```

**Comment by jdm** [comment]
Yep, that was #5161.
