### ISSUE TITLE
'arithmetic operation overflowed' on dn.se

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#5275]
Servo panics on http://dn.se/ with the following console output:

```
thread 'LayoutWorker worker 3/3' panicked at 'arithmetic operation overflowed', /Users/ulf/Documents/Code/servo/components/util/deque/mod.rs:394
stack backtrace:
   1:        0x10f1dfadd - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10f1f4cad - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10f1bea79 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10f1beefe - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10f1f453d - rust_begin_unwind
   6:        0x10f217115 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10f2167e7 - panicking::panic::h4158d1652bbc7938TXs
   8:        0x10dbb3023 - deque::Buffer<T>::resize::h17215137163654208494
   9:        0x10dbb2ca1 - deque::Deque<T>::maybe_shrink::h17547148438034740610
  10:        0x10dbb2973 - deque::Deque<T>::pop::h2711590732951389477
  11:        0x10dbb27e8 - deque::Worker<T>::pop::h16225865880017506680
  12:        0x10dbad4d3 - workqueue::WorkerThread<QueueData, WorkData>::start::h3051914657309924488
  13:        0x10dbad19c - workqueue::WorkQueue<QueueData, WorkData>::new::closure.34101
  14:        0x10dbad030 - task::spawn_named::closure.34097
  15:        0x10dbacf03 - thunk::Thunk<'a, (), R>::new::closure.34094
  16:        0x10dbacdcc - thunk::F.Invoke<A, R>::invoke::h14311423014243183731
  17:        0x10daf0c40 - thunk::Thunk<'a, A, R>::invoke::h2621809648179875306
  18:        0x10daf19a9 - thread::Builder::spawn_inner::closure.31567
  19:        0x10daf192e - rt::unwind::try::try_fn::__rust_abi::h4202468074377112138
  20:        0x10daf18c9 - rt::unwind::try::try_fn::h4202468074377112138
  21:        0x10f1f6c18 - rust_try_inner
  22:        0x10f1f6c05 - rust_try
  23:        0x10daf0d8b - rt::unwind::try::h12282771134787286682
  24:        0x10daef94c - thread::Builder::spawn_inner::closure.31460
  25:        0x10daf29e7 - thunk::Thunk<'a, (), R>::new::closure.31585
  26:        0x10daf28dc - thunk::F.Invoke<A, R>::invoke::h2959571540315697791
  27:        0x10f1e3692 - sys::thread::thread_start::hc1f580397175540a22E
  28:     0x7fff90c35898 - _pthread_body
  29:     0x7fff90c35729 - _pthread_start
thread 'LayoutWorker worker 1/3' panicked at 'arithmetic operation overflowed', /Users/ulf/Documents/Code/servo/components/util/deque/mod.rs:394
stack backtrace:
   1:        0x10f1dfadd - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10f1f4cad - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10f1bea79 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10f1beefe - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10f1f453d - rust_begin_unwind
   6:        0x10f217115 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10f2167e7 - panicking::panic::h4158d1652bbc7938TXs
   8:        0x10dbb3023 - deque::Buffer<T>::resize::h17215137163654208494
   9:        0x10dbb2ca1 - deque::Deque<T>::maybe_shrink::h17547148438034740610
  10:        0x10dbb2973 - deque::Deque<T>::pop::h2711590732951389477
  11:        0x10dbb27e8 - deque::Worker<T>::pop::h16225865880017506680
  12:        0x10dbad4d3 - workqueue::WorkerThread<QueueData, WorkData>::start::h3051914657309924488
  13:        0x10dbad19c - workqueue::WorkQueue<QueueData, WorkData>::new::closure.34101
  14:        0x10dbad030 - task::spawn_named::closure.34097
  15:        0x10dbacf03 - thunk::Thunk<'a, (), R>::new::closure.34094
  16:        0x10dbacdcc - thunk::F.Invoke<A, R>::invoke::h14311423014243183731
  17:        0x10daf0c40 - thunk::Thunk<'a, A, R>::invoke::h2621809648179875306
  18:        0x10daf19a9 - thread::Builder::spawn_inner::closure.31567
  19:        0x10daf192e - rt::unwind::try::try_fn::__rust_abi::h4202468074377112138
  20:        0x10daf18c9 - rt::unwind::try::try_fn::h4202468074377112138
  21:        0x10f1f6c18 - rust_try_inner
  22:        0x10f1f6c05 - rust_try
  23:        0x10daf0d8b - rt::unwind::try::h12282771134787286682
  24:        0x10daef94c - thread::Builder::spawn_inner::closure.31460
  25:        0x10daf29e7 - thunk::Thunk<'a, (), R>::new::closure.31585
  26:        0x10daf28dc - thunk::F.Invoke<A, R>::invoke::h2959571540315697791
  27:        0x10f1e3692 - sys::thread::thread_start::hc1f580397175540a22E
  28:     0x7fff90c35898 - _pthread_body
  29:     0x7fff90c35729 - _pthread_start
```

**Comment by jdm** [comment]
Thanks for finding this! http://mxr.mozilla.org/servo/source/components/util/deque/mod.rs#304 calls mxr.mozilla.org/servo/source/components/util/deque/mod.rs#394 with a delta of -1, and the comment right above explains how this used to work with wrapping arithmetic. Should be an easy replacement of wrapping_add.
