### ISSUE TITLE
WPT tests occasionally complain that they can't fork

### ISSUE THREAD

**Issue by jdm** [servo/servo#5285]
```
 0:39.26 TEST_START: Thread-TestrunnerManager-3 /2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-num-2.html
 0:39.27 LOG: Thread-Log INFO STDERR: ['/home/servo/buildbot/slave/linux2/build/components/servo/target/debug/servo', '--cpu', '--hard-fail', '-z', u'http://localhost:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-num-2.html']
 0:39.29 TEST_END: Thread-TestrunnerManager-3 ERROR, expected OK
Traceback (most recent call last):
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/_virtualenv/local/lib/python2.7/site-packages/wptrunner/executors/base.py", line 113, in run_test
    result = self.do_test(test)
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/_virtualenv/local/lib/python2.7/site-packages/wptrunner/executors/executorservo.py", line 55, in do_test
    self.proc.run()
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/_virtualenv/local/lib/python2.7/site-packages/mozprocess/processhandler.py", line 700, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/_virtualenv/local/lib/python2.7/site-packages/mozprocess/processhandler.py", line 103, in __init__
    universal_newlines, startupinfo, creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

 0:39.33 LOG: Thread-TestrunnerManager-3 WARNING u'runner_teardown' ()
```

**Comment by nox** [comment]
The tests in 588e9780efc028400b1d399e7c962cfb39227259  aren't disabled anymore.
