### ISSUE TITLE
CalledProcessError: Command '[u'components/servo/target/debug/servo', 'tests/html/about-mozilla.html']' returned non-zero exit status 101

### ISSUE THREAD

**Issue by Jayflux** [servo/servo#5655]
```
jason@jason-VirtualBox:~/workspace/servo$ ./mach run tests/html/about-mozilla.html
libGL error: pci id for fd 4: 80ee:beef, driver (null)
OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
OpenGL Warning: glVertexArrayRangeNV not found in mesa table
OpenGL Warning: glCombinerInputNV not found in mesa table
OpenGL Warning: glCombinerOutputNV not found in mesa table
OpenGL Warning: glCombinerParameterfNV not found in mesa table
OpenGL Warning: glCombinerParameterfvNV not found in mesa table
OpenGL Warning: glCombinerParameteriNV not found in mesa table
OpenGL Warning: glCombinerParameterivNV not found in mesa table
OpenGL Warning: glFinalCombinerInputNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glDeleteFencesNV not found in mesa table
OpenGL Warning: glFinishFenceNV not found in mesa table
OpenGL Warning: glGenFencesNV not found in mesa table
OpenGL Warning: glGetFenceivNV not found in mesa table
OpenGL Warning: glIsFenceNV not found in mesa table
OpenGL Warning: glSetFenceNV not found in mesa table
OpenGL Warning: glTestFenceNV not found in mesa table
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
OpenGL Warning: XGetVisualInfo returned 0 visuals for 00007fa2efe32c40
OpenGL Warning: Retry with 0x8002 returned 0 visuals
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseVisual failed")', /home/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:     0x7fa2ee9adcb2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7fa2ee9c0b92 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7fa2ee990539 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7fa2ee9908e1 - rt::unwind::begin_unwind_fmt::hac94a0d8ab692f55WlJ
   5:     0x7fa2ee9c04b7 - rust_begin_unwind
   6:     0x7fa2ee9ed224 - panicking::panic_fmt::hf7c6f0a83af17872HZs
   7:     0x7fa2eddf0f13 - result::Result<T, E>::unwrap::h4237758465097874350
                        at /home/larsberg/rust/src/libcore/macros.rs:27
   8:     0x7fa2eddf0722 - window::Window::new::h4e0c7cf3efdbfbccmoa
                        at /home/jason/workspace/servo/ports/glutin/window.rs:77
   9:     0x7fa2edec1d4a - create_window::h842c60c6069be600fTa
                        at /home/jason/workspace/servo/ports/glutin/lib.rs:46
  10:     0x7fa2ecc83de8 - main::ha4fdb8e9778a1262Faa
                        at /home/jason/workspace/servo/components/servo/main.rs:120
  11:     0x7fa2ee9caa68 - rust_try_inner
  12:     0x7fa2ee9caa55 - rust_try
  13:     0x7fa2ee9c22e0 - rt::lang_start::h198f2d8a631cfb22yBJ
  14:     0x7fa2ecc84474 - main
  15:     0x7fa2eaf32ec4 - __libc_start_main
  16:     0x7fa2ecc80148 - <unknown>
  17:                0x0 - <unknown>
Error running mach:

    ['run', 'tests/html/about-mozilla.html']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/debug/servo', 'tests/html/about-mozilla.html']' returned non-zero exit status 101

  File "/home/jason/workspace/servo/python/servo/post_build_commands.py", line 117, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

Using virtualbox with Ubuntu 14.04 
Already installed the pre-reqs

**Comment by larsbergstrom** [comment]
Verified running locally and not trying to use X forwarding. Couple of things to check:
1) Are any GL-related environment variables set? `LIBGL_ALWAYS_SOFTWARE` can cause us problems. Also, if `DISPLAY` is not set to ":0" you might have issues.
2) What is the output of glxinfo in this window w.r.t. opengl?
```
 glxinfo | grep OpenGL
```

cc @glennw who knows more about this stuff...

**Comment by Jayflux** [comment]
1)
no LIBGL_ALWAYS_SOFTWARE is not set

2) 
i don't seem to have glxinfo

**Comment by jdm** [comment]
#5643 suggests the virtualbox with 3d acceleration is known to break our video setup.

**Comment by Jayflux** [comment]
@jdm should we mention somewhere in the readme to switch this off?

**Comment by jdm** [comment]
Sounds like a reasonable suggestion.

**Comment by Jayflux** [comment]
Ok added, thanks guys.
Maybe we can close this?
