### ISSUE TITLE
thread 'LayoutTask' panicked at 'no layout root', /home/larsberg/rust/src/libcore/option.rs:330

### ISSUE THREAD

**Issue by christianweinz** [servo/servo#5676]
**Intro**

I just compiled servo. I followed the [official instructions](https://github.com/servo/servo) but did not install `msttcorefonts`.

After asking in #servo I was told I'm ought to file an issue.

My system is Debian Jessie amd64.

**Steps to reproduce**
1. Run `mach run http://www.csicop.org/sb/show/shooting_for_the_sun/`
2. Click on the "Tweet" button over the article text.

**Console output**

```
/servo$ ./mach run http://www.csicop.org/sb/show/shooting_for_the_sun/
ERROR:js::rust: Error at https://platform.twitter.com/widgets.js:1: TypeError: t.top is undefined

ERROR:js::rust: Error at https://apis.google.com/js/plusone.js:16: TypeError: a[b].name is undefined

ERROR:js::rust: Error at http://www.csicop.org/sb/show/shooting_for_the_sun/:3: TypeError: document.write is not a function

Invalid App Id: Must be a number or numeric string representing the application id.
ERROR:js::rust: Error at http://connect.facebook.net/en_US/all.js#xfbml=1:85: ReferenceError: Image is not defined

ERROR:js::rust: Error at http://www.csicop.org/js/csi-master1.js?1:14: ReferenceError: top is not defined

ERROR:net_traits::image::base: stb_image failed: stbi_load_from_memory failed
ERROR:js::rust: Error at https://twitter.com/intent/tweet?url=&original_referer=:4: ReferenceError: top is not defined

ERROR:js::rust: Error at https://abs.twimg.com/a/1428597205/tfw/tfw/intents/tweetbox.js:8: Error: Unable to set selection range.

ERROR:js::rust: Error at https://twitter.com/intent/tweet?url=&original_referer=:3: TypeError: document.write is not a function

thread 'LayoutTask' panicked at 'no layout root', /home/larsberg/rust/src/libcore/option.rs:330
stack backtrace:
   1:     0x7fa2b10b68f2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7fa2b10c97d2 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7fa2b1099179 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7fa2b1099521 - rt::unwind::begin_unwind_fmt::hac94a0d8ab692f55WlJ
   5:     0x7fa2b10c90f7 - rust_begin_unwind
   6:     0x7fa2b10f5e64 - panicking::panic_fmt::hf7c6f0a83af17872HZs
   7:     0x7fa2af96ec29 - option::Option<T>::expect::h3339688317685781230
                        at /home/larsberg/rust/src/libcore/macros.rs:27
   8:     0x7fa2af96ea3a - layout_task::LayoutTask::get_layout_root::h0ae5f3c490deed4bBDl
                        at servo/components/layout/layout_task.rs:654
   9:     0x7fa2af96112c - layout_task::LayoutTask::handle_reflow::h57b6e316b3a9f06ehOl
                        at servo/components/layout/layout_task.rs:884
  10:     0x7fa2af95ce8c - layout_task::LayoutTask::handle_request_helper::closure.35367
                        at servo/components/layout/layout_task.rs:482
  11:     0x7fa2af95ccca - time::profile::h16274892730613040173
                        at servo/components/profile/time.rs:279
  12:     0x7fa2af953e36 - layout_task::LayoutTask::handle_request_helper::hd702f6077470f3a8Bpl
                        at servo/components/layout/layout_task.rs:479
  13:     0x7fa2af9424a6 - layout_task::LayoutTask::handle_request::h803c61f15c73d749jml
                        at servo/components/layout/layout_task.rs:429
  14:     0x7fa2af90b15f - layout_task::LayoutTask::start::ha379f92f435fee20Tkl
                        at servo/components/layout/layout_task.rs:360
  15:     0x7fa2af908b3b - layout_task::LayoutTask.LayoutTaskFactory::create::closure.34432
                        at servo/components/layout/layout_task.rs:243
  16:     0x7fa2af908591 - task::spawn_named_with_send_on_failure::closure.34428
                        at servo/components/util/task.rs:31
  17:     0x7fa2af90849b - thunk::Thunk<'a, (), R>::new::closure.34425
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  18:     0x7fa2af908396 - thunk::F.Invoke<A, R>::invoke::h2905619847661435863
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  19:     0x7fa2af87a78c - thunk::Thunk<'a, A, R>::invoke::h1399628975552477894
                        at /home/larsberg/rust/src/libstd/thunk.rs:41
  20:     0x7fa2af87b4a8 - thread::Builder::spawn_inner::closure.32497
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  21:     0x7fa2af87b43e - rt::unwind::try::try_fn::__rust_abi::h7736092607595797889
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:139
  22:     0x7fa2af87b3d9 - rt::unwind::try::try_fn::h7736092607595797889
  23:     0x7fa2b10d36a8 - rust_try_inner
  24:     0x7fa2b10d3695 - rust_try
  25:     0x7fa2af87a8cb - rt::unwind::try::h435792804797237308
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:125
  26:     0x7fa2af8796ea - thread::Builder::spawn_inner::closure.32392
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  27:     0x7fa2af87c507 - thunk::Thunk<'a, (), R>::new::closure.32515
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  28:     0x7fa2af87c419 - thunk::F.Invoke<A, R>::invoke::h3002028234228865626
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  29:     0x7fa2b10b98c5 - sys::thread::thread_start::h04d056c6180f4496s8E
  30:     0x7fa2aeb410a3 - start_thread
  31:     0x7fa2ad65304c - __clone
  32:                0x0 - <unknown>
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:     0x7fa2b10b68f2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7fa2b10c97d2 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7fa2b1099179 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7fa2b1099521 - rt::unwind::begin_unwind_fmt::hac94a0d8ab692f55WlJ
   5:     0x7fa2b10c90f7 - rust_begin_unwind
   6:     0x7fa2b10f5e64 - panicking::panic_fmt::hf7c6f0a83af17872HZs
   7:     0x7fa2b007a385 - result::Result<T, E>::unwrap::h8383685303818673880
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/larsberg/rust/src/libcore/result.rs:744
                        at /home/larsberg/rust/src/libcore/macros.rs:27
   8:     0x7fa2b00777d8 - dom::window::JSRef<'a, Window>.WindowHelpers::join_layout::hef44f6178d9f3dd8tBz
                        at servo/components/script/dom/window.rs:620
   9:     0x7fa2afecfdd1 - dom::window::JSRef<'a, Window>.WindowHelpers::reflow::h5b8455e4750ec2ce1uz
                        at servo/components/script/dom/window.rs:600
  10:     0x7fa2b01440f7 - script_task::ScriptTask::load::h662f5b5040d476253AE
                        at servo/components/script/script_task.rs:1097
  11:     0x7fa2b013c1ed - script_task::ScriptTask::handle_page_fetch_complete::h5bfc1b2a271a9901jxE
                        at servo/components/script/script_task.rs:905
  12:     0x7fa2b0138e25 - script_task::ScriptTask::handle_msg_from_script::h0de5d02af232d6f40fE
                        at servo/components/script/script_task.rs:690
  13:     0x7fa2b01131a0 - script_task::ScriptTask::handle_msgs::hbec9efcc708db9c935D
                        at servo/components/script/script_task.rs:624
  14:     0x7fa2b0111911 - script_task::ScriptTask::start::h1e74a9510fef314cT5D
                        at servo/components/script/script_task.rs:496
  15:     0x7fa2af463ac7 - script_task::ScriptTask.ScriptTaskFactory::create::closure.11025
                        at servo/components/script/script_task.rs:387
  16:     0x7fa2af463421 - task::spawn_named_with_send_on_failure::closure.11021
                        at servo/components/util/task.rs:31
  17:     0x7fa2af46332b - thunk::Thunk<'a, (), R>::new::closure.11018
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  18:     0x7fa2af463226 - thunk::F.Invoke<A, R>::invoke::h12714540376742948869
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  19:     0x7fa2af3dff5c - thunk::Thunk<'a, A, R>::invoke::h9094058378683519406
                        at /home/larsberg/rust/src/libstd/thunk.rs:41
  20:     0x7fa2af3e0c78 - thread::Builder::spawn_inner::closure.7270
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  21:     0x7fa2af3e0c0e - rt::unwind::try::try_fn::__rust_abi::h9386810838098338737
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:139
  22:     0x7fa2af3e0ba9 - rt::unwind::try::try_fn::h9386810838098338737
  23:     0x7fa2b10d36a8 - rust_try_inner
  24:     0x7fa2b10d3695 - rust_try
  25:     0x7fa2af3e009b - rt::unwind::try::h14535381740159702374
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:125
  26:     0x7fa2af3deeba - thread::Builder::spawn_inner::closure.7114
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  27:     0x7fa2af3e1cd7 - thunk::Thunk<'a, (), R>::new::closure.7288
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  28:     0x7fa2af3e1be9 - thunk::F.Invoke<A, R>::invoke::h973448228728928561
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  29:     0x7fa2b10b98c5 - sys::thread::thread_start::h04d056c6180f4496s8E
  30:     0x7fa2aeb410a3 - start_thread
  31:     0x7fa2ad65304c - __clone
  32:                0x0 - <unknown>
stack backtrace:
   1:     0x7fa2b10b68f2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7fa2b10c97d2 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7fa2b1099179 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7fa2b1099521 - rt::unwind::begin_unwind_fmt::hac94a0d8ab692f55WlJ
   5:     0x7fa2b10c90f7 - rust_begin_unwind
   6:     0x7fa2b10f5e64 - panicking::panic_fmt::hf7c6f0a83af17872HZs
   7:     0x7fa2b064526c - result::Result<T, E>::unwrap::h16379447119157799830
thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/larsberg/rust/src/libcore/result.rs:744
                        at /home/larsberg/rust/src/libcore/macros.rs:27
   8:     0x7fa2b0645135 - pipeline::Pipeline::force_exit::he57b6225ce0c64b7oQc
                        at servo/components/compositing/pipeline.rs:241
   9:     0x7fa2af41f997 - constellation::Constellation<LTF, STF>::close_pipeline::h11125645087345675487
                        at servo/components/compositing/constellation.rs:843
  10:     0x7fa2af41ded0 - constellation::Constellation<LTF, STF>::handle_failure_msg::h12902831654550497516
                        at servo/components/compositing/constellation.rs:417
  11:     0x7fa2af40f959 - constellation::Constellation<LTF, STF>::handle_request::h13977583585424574770
                        at servo/components/compositing/constellation.rs:308
  12:     0x7fa2af40a2f5 - constellation::Constellation<LTF, STF>::run::h10831987652459881239
                        at servo/components/compositing/constellation.rs:220
  13:     0x7fa2af3e3279 - constellation::Constellation<LTF, STF>::start::closure.7311
                        at servo/components/compositing/constellation.rs:212
  14:     0x7fa2af3e26d9 - task::spawn_named::closure.7304
                        at servo/components/util/task.rs:16
  15:     0x7fa2af3e25a9 - thunk::Thunk<'a, (), R>::new::closure.7301
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  16:     0x7fa2af3e245f - thunk::F.Invoke<A, R>::invoke::h13215509868695544205
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  17:     0x7fa2af3dff5c - thunk::Thunk<'a, A, R>::invoke::h9094058378683519406
                        at /home/larsberg/rust/src/libstd/thunk.rs:41
  18:     0x7fa2af3e0c78 - thread::Builder::spawn_inner::closure.7270
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  19:     0x7fa2af3e0c0e - rt::unwind::try::try_fn::__rust_abi::h9386810838098338737
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:139
  20:     0x7fa2af3e0ba9 - rt::unwind::try::try_fn::h9386810838098338737
  21:     0x7fa2b10d36a8 - rust_try_inner
  22:     0x7fa2b10d3695 - rust_try
  23:     0x7fa2af3e009b - rt::unwind::try::h14535381740159702374
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:125
  24:     0x7fa2af3deeba - thread::Builder::spawn_inner::closure.7114
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  25:     0x7fa2af3e1cd7 - thunk::Thunk<'a, (), R>::new::closure.7288
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  26:     0x7fa2af3e1be9 - thunk::F.Invoke<A, R>::invoke::h973448228728928561
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  27:     0x7fa2b10b98c5 - sys::thread::thread_start::h04d056c6180f4496s8E
  28:     0x7fa2aeb410a3 - start_thread
  29:     0x7fa2ad65304c - __clone
  30:                0x0 - <unknown>
stack backtrace:
   1:     0x7fa2b10b68f2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7fa2b10c97d2 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7fa2b1099179 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7fa2b1099521 - rt::unwind::begin_unwind_fmt::hac94a0d8ab692f55WlJ
   5:     0x7fa2b10c90f7 - rust_begin_unwind
   6:     0x7fa2b10f5e64 - panicking::panic_fmt::hf7c6f0a83af17872HZs
   7:     0x7fa2afb8d935 - result::Result<T, E>::unwrap::h15504969939650489961
                        at /home/larsberg/rust/src/libcore/macros.rs:27
   8:     0x7fa2affa541c - dom::bindings::refcounted::Trusted<T>.Drop::drop::h11584450736382631957
                        at servo/components/script/dom/bindings/refcounted.rs:120
   9:     0x7fa2affa51dd - dom..bindings..refcounted..Trusted<dom..htmlscriptelement..HTMLScriptElement>::glue_drop.97081::hb24506483b87a635
  10:     0x7fa2affa54dd - dom..htmlscriptelement..EventDispatcher::glue_drop.97087::h58c61cbff066fbaf
  11:     0x7fa2affa548b - Box<dom..htmlscriptelement..EventDispatcher>::glue_drop.97084::hd30f034cc1472115
  12:     0x7fa2af42e0bf - Box<script..script_task..Runnable $u2b$$u20$Send$GT$::glue_drop.10167::h0a71cfc32a69a5b2
  13:     0x7fa2af42e01f - script..script_task..ScriptMsg::glue_drop.10164::h4450345ec5f18702
  14:     0x7fa2af4302de - std..sync..mpsc..mpsc_queue..PopResult<script..script_task..ScriptMsg>::glue_drop.10197::hc84395eb3e5a1cf3
  15:     0x7fa2af42fbce - sync::mpsc::shared::Packet<T>::drop_port::h15415178289371142655
                        at /home/larsberg/rust/src/libstd/sync/mpsc/shared.rs:369
  16:     0x7fa2af42e329 - sync::mpsc::Receiver<T>.Drop::drop::h3570419950228991646
                        at /home/larsberg/rust/src/libstd/sync/mpsc/mod.rs:958
  17:     0x7fa2af42e1fd - std..sync..mpsc..Receiver<script..script_task..ScriptMsg>::glue_drop.10176::h4293c4b869a2b89d
  18:     0x7fa2af4685b5 - script..script_task..ScriptTask::glue_drop.11117::hd79fd3e12765795b
  19:     0x7fa2af463afc - script_task::ScriptTask.ScriptTaskFactory::create::closure.11025
                        at servo/components/script/script_task.rs:366
  20:     0x7fa2af463421 - task::spawn_named_with_send_on_failure::closure.11021
                        at servo/components/util/task.rs:31
  21:     0x7fa2af46332b - thunk::Thunk<'a, (), R>::new::closure.11018
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  22:     0x7fa2af463226 - thunk::F.Invoke<A, R>::invoke::h12714540376742948869
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  23:     0x7fa2af3dff5c - thunk::Thunk<'a, A, R>::invoke::h9094058378683519406
                        at /home/larsberg/rust/src/libstd/thunk.rs:41
  24:     0x7fa2af3e0c78 - thread::Builder::spawn_inner::closure.7270
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  25:     0x7fa2af3e0c0e - rt::unwind::try::try_fn::__rust_abi::h9386810838098338737
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:139
  26:     0x7fa2af3e0ba9 - rt::unwind::try::try_fn::h9386810838098338737
  27:     0x7fa2b10d36a8 - rust_try_inner
  28:     0x7fa2b10d3695 - rust_try
  29:     0x7fa2af3e009b - rt::unwind::try::h14535381740159702374
                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:125
  30:     0x7fa2af3deeba - thread::Builder::spawn_inner::closure.7114
                        at /home/larsberg/rust/src/libstd/thread.rs:318
  31:     0x7fa2af3e1cd7 - thunk::Thunk<'a, (), R>::new::closure.7288
                        at /home/larsberg/rust/src/libstd/thunk.rs:27
  32:     0x7fa2af3e1be9 - thunk::F.Invoke<A, R>::invoke::h973448228728928561
                        at /home/larsberg/rust/src/libstd/thunk.rs:54
  33:     0x7fa2b10b98c5 - sys::thread::thread_start::h04d056c6180f4496s8E
  34:     0x7fa2aeb410a3 - start_thread
  35:     0x7fa2ad65304c - __clone
  36:                0x0 - <unknown>
thread panicked while panicking. aborting.
Error running mach:

    ['run', 'http://www.csicop.org/sb/show/shooting_for_the_sun/']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/debug/servo', 'http://www.csicop.org/sb/show/shooting_for_the_sun/']' returned non-zero exit status -4

  File "servo/python/servo/post_build_commands.py", line 117, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by jdm** [comment]
Could be the same problem as #3849.

**Comment by dralley** [comment]
Page 404s, so this is no longer reproducable.
