### ISSUE TITLE
Intermittent XOpenDisplay errors in WPT canvas tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#5798]
```
 1:10.81 TEST_START: Thread-TestrunnerManager-3 /2dcontext/shadows/2d.shadow.attributes.shadowColor.invalid.html
 1:10.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) Full command: /home/servo/buildbot/slave/linux2/build/components/servo/target/debug/servo --cpu --hard-fail -z http://localhost:8000/2dcontext/shadows/2d.shadow.attributes.shadowColor.invalid.html
(pid:28749) "thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "XOpenDisplay"', /home/larsberg/rust/src/libcore/result.rs:744"
1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   1:     0x7fe92df989b2 - sys::backtrace::write::h754dbf5d2d3172ebPBA"
 1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   2:     0x7fe92dfab892 - panicking::on_panic::hdb9e837ac064f8afiHJ"
 1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   3:     0x7fe92df7b1b9 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ"
 1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   4:     0x7fe92df7b561 - rt::unwind::begin_unwind_fmt::hac94a0d8ab692f55WlJ"
 1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   5:     0x7fe92dfab1b7 - rust_begin_unwind"
 1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   6:     0x7fe92dfd7f24 - panicking::panic_fmt::hf7c6f0a83af17872HZs"
 1:11.55 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   7:     0x7fe92c2d8b1e - result::Result<T, E>::unwrap::h3046707937228198880"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libcore/macros.rs:27"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   8:     0x7fe92c2b1716 - constellation::Constellation<LTF, STF>::start::closure.8635"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/servo/buildbot/slave/linux2/build/components/compositing/constellation.rs:219"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "   9:     0x7fe92c2b0b39 - task::spawn_named::closure.8628"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/servo/buildbot/slave/linux2/build/components/util/task.rs:16"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  10:     0x7fe92c2b0a09 - thunk::Thunk<'a, (), R>::new::closure.8625"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thunk.rs:27"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  11:     0x7fe92c2b08bf - thunk::F.Invoke<A, R>::invoke::h512363410565675064"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thunk.rs:54"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  12:     0x7fe92c2ae3bc - thunk::Thunk<'a, A, R>::invoke::h18421192380078646695"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thunk.rs:41"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  13:     0x7fe92c2af0d8 - thread::Builder::spawn_inner::closure.8594"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thread.rs:318"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  14:     0x7fe92c2af06e - rt::unwind::try::try_fn::__rust_abi::h13015545278964340699"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:139"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  15:     0x7fe92c2af009 - rt::unwind::try::try_fn::h13015545278964340699"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  16:     0x7fe92dfb5768 - rust_try_inner"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  17:     0x7fe92dfb5755 - rust_try"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  18:     0x7fe92c2ae4fb - rt::unwind::try::h10068198939133317352"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/rt/unwind.rs:125"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  19:     0x7fe92c2ad31a - thread::Builder::spawn_inner::closure.8428"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thread.rs:318"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  20:     0x7fe92c2b0137 - thunk::Thunk<'a, (), R>::new::closure.8612"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thunk.rs:27"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  21:     0x7fe92c2b0049 - thunk::F.Invoke<A, R>::invoke::h5910199685886419682"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "                        at /home/larsberg/rust/src/libstd/thunk.rs:54"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  22:     0x7fe92df9b985 - sys::thread::thread_start::h04d056c6180f4496s8E"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  23:     0x7fe92b90b181 - start_thread"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  24:     0x7fe92ae1347c - __clone"
 1:11.75 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:28749) "  25:                0x0 - <unknown>"
```

**Comment by jdm** [comment]
@glennw Any idea what's up here?

**Comment by glennw** [comment]
@jdm Not off the top of my head - has this just started happening recently? I can't quite recall but I thought we ran the WPT tests with OSMesa on the builders, in order to avoid these intermittent X issues?

**Comment by jdm** [comment]
This definitely started happening in the past couple of days.

**Comment by glennw** [comment]
I'll see if I can reproduce it locally today.

**Comment by glennw** [comment]
@jdm @jgraham x11-clipboard opens an X display when we are running in headless / osmesa mode, which is probably why the problem started happening recently.

We should not init x11-clipboard when running in headless mode.

**Comment by jdm** [comment]
Sounds like the Constellation should store an `Option<ClipboardContext>`.

**Comment by jdm** [comment]
@aweinstock314 Interested in making this change?

**Comment by jgraham** [comment]
I am taking a look at this.

I tried adding a `supports_clipboard(&self) -> bool` method to `WindowTraits` and passing in the result to the constellation (the `ClipboardContext` itself isn't `Send` so I can't just pass the context in). I'm not sure this is a great approach though.

**Comment by nox** [comment]
@jgraham Ping on this? Could this be made into an `E-less easy` ticket?

**Comment by nox** [comment]
Wait, that was done.
