### ISSUE TITLE
SegFault with primusrun

### ISSUE THREAD

**Issue by max6cn** [servo/servo#5982]
### Command to trigger:

``` bash
primusrun ./mach run  --release http://www.github.com
```
### Output

``` log
primusrun ./mach run  --release http://www.github.com
sh: line 1: 21305 Segmentation fault      (core dumped) /sbin/ldconfig -p 2> /dev/null
sh: line 1: 21315 Segmentation fault      (core dumped) /sbin/ldconfig -p 2> /dev/null
thread '<main>' panicked at 'assertion failed: glXBindTexImageEXT as *mut c_void != ptr::null_mut()', /home/mark/rust/servo/.cargo/git/checkouts/rust-layers-3d9d5f0b4e4d9002/master/src/platform/linux/surface.rs:289
stack backtrace:
   1:     0x7fcd9a32db79 - sys::backtrace::write::h6dd465a29c00292cqYr
   2:     0x7fcd9a331741 - panicking::on_panic::hce7ca60568ec6ad9low
   3:     0x7fcd9a31c9a2 - rt::unwind::begin_unwind_inner::h2ea6b65af87d2482v3v
   4:     0x7fcd9a07209e - rt::unwind::begin_unwind::h3751135423666612265
   5:     0x7fcd9a07a434 - platform::linux::surface::PixmapNativeSurface::bind_to_texture::h201fd423f5cf81b9cVb
   6:     0x7fcd9a0795f8 - tiling::TileGrid::create_textures::he0de5886d0857155cCb
   7:     0x7fcd9933e6af - rendergl::layers..Layer<T>.Render::render::h9044460351882798105
   8:     0x7fcd9933ec5b - rendergl::layers..Layer<T>.Render::render::h9044460351882798105
   9:     0x7fcd9933d1a9 - compositor::IOCompositor<Window>::composite_specific_target::h7769137433026729039
  10:     0x7fcd993257a1 - compositor::IOCompositor<Window>.CompositorEventListener::handle_event::h4195279628258086555
  11:     0x7fcd99341f25 - Browser::handle_event::h652e9d77e521433fJca
  12:     0x7fcd992eef0f - main::h7ccd2b457f918f47paa
  13:     0x7fcd9a3367d8 - rust_try_inner
  14:     0x7fcd9a3367c5 - rust_try
  15:     0x7fcd9a332f9f - rt::lang_start::h09e0526b407d67dbQiw
  16:     0x7fcd98293ec4 - __libc_start_main
  17:     0x7fcd992ee408 - <unknown>
  18:                0x0 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/mark/rust/servo/.cargo/git/checkouts/rust-layers-3d9d5f0b4e4d9002/master/src/platform/linux/surface.rs:224
stack backtrace:
   1:     0x7fcd9a32db79 - sys::backtrace::write::h6dd465a29c00292cqYr
   2:     0x7fcd9a331741 - panicking::on_panic::hce7ca60568ec6ad9low
   3:     0x7fcd9a31c9a2 - rt::unwind::begin_unwind_inner::h2ea6b65af87d2482v3v
   4:     0x7fcd9a07209e - rt::unwind::begin_unwind::h3751135423666612265
   5:     0x7fcd9a0722be - platform::linux::surface::PixmapNativeSurface.Drop::drop::h1acf5b49d12da661kTb
   6:     0x7fcd993219a3 - layers..layers..Layer<compositing..compositor_layer..CompositorData>::drop.7704::h630f5fb04768477b
   7:     0x7fcd99321b6c - vec::Vec<T>.Drop::drop::h3725450331057121229
   8:     0x7fcd99321885 - layers..layers..Layer<compositing..compositor_layer..CompositorData>::drop.7704::h630f5fb04768477b
   9:     0x7fcd99323875 - compositing..compositor..IOCompositor<glutin_app..window..Window>::drop.8027::h5ad749172842bec7
  10:     0x7fcd992ef034 - main::h7ccd2b457f918f47paa
  11:     0x7fcd9a3367d8 - rust_try_inner
  12:     0x7fcd9a3367c5 - rust_try
  13:     0x7fcd9a332f9f - rt::lang_start::h09e0526b407d67dbQiw
  14:     0x7fcd98293ec4 - __libc_start_main
  15:     0x7fcd992ee408 - <unknown>
  16:                0x0 - <unknown>
thread panicked while panicking. aborting.
Error running mach:

    ['run', '--release', 'http://www.github.com']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/release/servo', 'http://www.github.com']' returned non-zero exit status -4

  File "/home/mark/rust/servo/python/servo/post_build_commands.py", line 117, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

```
### Other Information
- Host information

```
uname -a
Linux u530 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```
-  servo renders correctly without primusrun
-  Firefox is fine with primusrun
-  Building log

``` log
./mach build --release
   Compiling png-sys v1.6.16 (https://github.com/servo/rust-png#34fca101)
   Compiling task_info v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling harfbuzz v0.1.0 (https://github.com/servo/rust-harfbuzz#33b6fd01)
   Compiling fontconfig-sys v2.11.1 (https://github.com/servo/libfontconfig#ce4a3863)
   Compiling freetype-sys v2.4.11 (https://github.com/servo/libfreetype2#50c1cf41)
   Compiling mod_path v0.1.5
   Compiling skia v0.0.20130412 (https://github.com/servo/skia#d60e6753)
   Compiling js v0.1.0 (https://github.com/servo/rust-mozjs#30a1ad31)
   Compiling style v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling stb_image v0.1.0 (https://github.com/servo/rust-stb-image#f6c411b3)
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#19edb950)
   Compiling azure v0.1.0 (https://github.com/servo/rust-azure#91e18a32)
   Compiling expat-sys v2.1.0 (https://github.com/servo/libexpat#5f798cfb)
   Compiling script v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling smallvec v0.1.3
   Compiling gcc v0.3.4
   Compiling unicase v0.1.0
   Compiling pkg-config v0.3.3
   Compiling khronos_api v0.0.5
   Compiling typeable v0.1.1
   Compiling phf_shared v0.7.3
   Compiling mac v0.0.2
   Compiling traitobject v0.0.1
   Compiling string_cache_shared v0.1.0 (https://github.com/servo/string-cache#c5912f92)
   Compiling regex v0.1.30
   Compiling httparse v0.1.1
   Compiling matches v0.1.2
   Compiling fnv v1.0.0
   Compiling tenacious v0.0.1 (https://github.com/Manishearth/rust-tenacious.git#5112359c)
   Compiling quicksort v1.0.0
   Compiling lazy_static v0.1.10
   Compiling mac v0.0.2 (https://github.com/reem/rust-mac#6316d3f4)
   Compiling rustc-serialize v0.3.13
   Compiling libc v0.1.6
   Compiling debug-builders v0.1.0
   Compiling encoding_index_tests v0.1.4
   Compiling bitflags v0.1.1
   Compiling byteorder v0.3.9
   Compiling png v0.1.0 (https://github.com/servo/rust-png#34fca101)
   Compiling miniz-sys v0.1.4
   Compiling time v0.1.25
   Compiling osmesa-sys v0.0.3
   Compiling openssl-sys v0.6.1
   Compiling string_cache_plugin v0.1.1 (https://github.com/servo/string-cache#c5912f92)
   Compiling plugins v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling regex_macros v0.1.17
   Compiling x11 v0.0.32
   Compiling num_cpus v0.2.4
   Compiling freetype v0.1.0 (https://github.com/servo/rust-freetype#f256a9ac)
   Compiling clock_ticks v0.0.5 (https://github.com/tomaka/clock_ticks#46284873)
   Compiling egl v0.1.0 (https://github.com/servo/rust-egl#c0159346)
   Compiling gl_common v0.0.4
   Compiling log v0.3.1
   Compiling core_foundation v0.1.0 (https://github.com/servo/rust-core-foundation#928efbae)
   Compiling rand v0.3.8
   Compiling phf v0.7.3
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling xlib v0.1.0 (https://github.com/servo/rust-xlib#1a0f3d48)
   Compiling xml-rs v0.1.24
   Compiling html5ever_macros v0.0.0 (https://github.com/servo/html5ever#74dc5f5a)
   Compiling webdriver_traits v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling url v0.2.31
   Compiling mime v0.0.10
   Compiling core_graphics v0.1.0 (https://github.com/servo/rust-core-graphics#da0d2fe9)
   Compiling phf_generator v0.7.3
   Compiling uuid v0.1.17
   Compiling num v0.1.24
   Compiling clipboard v0.0.1 (https://github.com/servo/rust-x11-clipboard#43afb218)
   Compiling encoding v0.2.32
   Compiling gl_generator v0.0.24
   Compiling core_text v0.1.0 (https://github.com/servo/rust-core-text#bc6994c3)
   Compiling phf_macros v0.7.3
   Compiling geom v0.1.0 (https://github.com/servo/rust-geom#c4bdb1ef)
   Compiling cssparser v0.3.1
   Compiling flate2 v0.2.7
   Compiling glx v0.0.1 (https://github.com/servo/rust-glx#60ac0aee)
   Compiling gl v0.0.12
   Compiling gleam v0.0.1 (https://github.com/servo/gleam#f2edabf2)
   Compiling glutin v0.0.26 (https://github.com/servo/glutin?branch=servo#11389c9e)
   Compiling fontconfig v0.1.0 (https://github.com/servo/rust-fontconfig#7839e5ad)
   Compiling openssl v0.6.1
   Compiling profile_traits v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling string_cache v0.1.0 (https://github.com/servo/string-cache#c5912f92)
   Compiling cookie v0.1.19
   Compiling selectors v0.1.0 (https://github.com/servo/rust-selectors#1fda09bf)
   Compiling html5ever v0.0.0 (https://github.com/servo/html5ever#74dc5f5a)
   Compiling hyper v0.3.16
   Compiling cgl v0.0.1 (https://github.com/servo/rust-cgl#851ca1b9)
   Compiling io_surface v0.1.0 (https://github.com/servo/rust-io-surface#ab0ebd4e)
   Compiling offscreen_gl_context v0.0.1 (https://github.com/ecoal95/rust-offscreen-rendering-context#c2b3dfd7)
   Compiling layers v0.1.0 (https://github.com/servo/rust-layers#018259e8)
   Compiling util v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling profile v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling websocket v0.11.8
   Compiling webdriver v0.1.0 (https://github.com/jgraham/webdriver-rust.git#c2038b41)
   Compiling msg v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling devtools_traits v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling net_traits v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling webdriver_server v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling devtools v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling net v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling script_traits v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling gfx v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling layout_traits v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling canvas v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling compositing v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling glutin_app v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling layout v0.0.1 (file:///home/mark/rust/servo/components/servo)
   Compiling servo v0.0.1 (file:///home/mark/rust/servo/components/servo)
Build completed in 839.27s

```

**Comment by jdm** [comment]
What does "servo renders correctly without primusrun" mean, exactly?

**Comment by max6cn** [comment]
> What does "servo renders correctly without primusrun" mean, exactly?
sorry for the confusion.If launched with the integrated graphics  card(Intel HD4400),
`` `
./mach run  --release http://www.github.com
```
the webpage looks fine and doesn't crash. 

I also tried the following command, 
```
components/servo/target/release/servo http://www.github.com
```
works fine, same as `mach run --release ...`
```
primusrun components/servo/target/release/servo http://www.github.com
```
Crash after a black window show up, output :
```log
thread '<main>' panicked at 'assertion failed: glXBindTexImageEXT as *mut c_void != ptr::null_mut()', /home/mark/rust/servo/.cargo/git/checkouts/rust-layers-3d9d5f0b4e4d9002/master/src/platform/linux/surface.rs:289
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/mark/rust/servo/.cargo/git/checkouts/rust-layers-3d9d5f0b4e4d9002/master/src/platform/linux/surface.rs:224
stack backtrace:
thread 'PaintTask' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/larsberg/rust/src/libcore/result.rs:729
   1:     0x7f79e22a4b79 - sys::backtrace::write::h6dd465a29c00292cqYr
   2:     0x7f79e22a8821 - panicking::on_panic::hce7ca60568ec6ad9low
   3:     0x7f79e22939a2 - rt::unwind::begin_unwind_inner::h2ea6b65af87d2482v3v
   4:     0x7f79e1fe909e - rt::unwind::begin_unwind::h3751135423666612265
   5:     0x7f79e1fe92be - platform::linux::surface::PixmapNativeSurface.Drop::drop::h1acf5b49d12da661kTb
   6: thread '    0x7f79e12989a3 - layers..layers..Layer<compositing..compositor_layer..CompositorData>::drop.7704::h630f5fb04768477b
   7:     0x7f79e1298b6c - vec::Vec<T>.Drop::drop::h3725450331057121229
   8:  thread '   0x7f79e1298885 - layers..layers..Layer<compositing..compositor_layer..CompositorData>::drop.7704::h630f5fb04768477b
   9:     0xPaintWorker7f79e129a875 - compositing..compositor..IOCompositor' panicked at '<glutin_app..window..Window>Constellation::drop.8027::called `Result::unwrap()` on an `Err` value: RecvErrorh5ad749172842bec7
' panicked at '  10PaintChan.send: paint port closed:   ',   0x7f79e1266034',  - main::h7ccd2b457f918f47paa
  11:     0x7f79e22ad7d8 - rust_try_inner
  12:     0x7f79e22ad7c5 - rust_try
  13:     0x7f79e22a9f9f - rt::lang_start::h09e0526b407d67dbQiw
  14:     0x7f79e020aec4 - __libc_start_main
  15:     0x7f79e1265408 - <unknown>
  16:                0x0 - <unknown>
thread panicked while panicking. aborting.
[1]    23173 illegal hardware instruction (core dumped)  primusrun components/servo/target/release/servo http://www.github.com
```

**Comment by ecoal95** [comment]
Seems that the glx extension that servo uses to bind an opengl texture to a pixmap is not found there... I don't think too much can be done :S

**Comment by mrobinson** [comment]
I don't see any references in primus to glXBindTexImage, so it seems like this is really just a missing feature in primus.

https://github.com/amonakov/primus/search?utf8=%E2%9C%93&q=glXBindTexImage&type=Code

**Comment by glennw** [comment]
This code no longer exists.
