### ISSUE TITLE
unrooted_must_root lint can't handle struct enum variants

### ISSUE THREAD

**Issue by jdm** [servo/servo#6069]
```
pub enum TimerRequest {
    Add { timeout: u32, tx: Sender<TimerResponse> },
    Remove { id: u32 },
}
```
yields
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'expected item, found variant Add in timers::Add (id=649981)', /Users/larsberg/rust/src/libsyntax/ast_map/mod.rs:332```


## Meta

```rustc 1.0.0-nightly (cfea8ec41 2015-03-10) (built 2015-03-10)
binary: rustc
commit-hash: cfea8ec41699e25c8fb524d625190f0cb860dc71
commit-date: 2015-03-10
build-date: 2015-03-10
host: x86_64-apple-darwin
release: 1.0.0-nightly```

Backtrace:
```thread 'rustc' panicked at 'expected item, found variant Add in timers::Add (id=649981)', /Users/larsberg/rust/src/libsyntax/ast_map/mod.rs:332

stack backtrace:
   1:        0x106c334ef - sys::backtrace::write::h6990067d88907b48zVr
   2:        0x106c3bb60 - panicking::on_panic::he976cdbadffd9e1bEVv
   3:        0x106bf7ed5 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
   4:        0x106bf8d0c - rt::unwind::begin_unwind_fmt::h15c2d4adf8e8ecdatCv
   5:        0x106374382 - ast_map::Map<'ast>::expect_item::h4e16fb1d667f8361hhw
   6:        0x118830118 - lints::unrooted_must_root::UnrootedPass.LintPass::check_struct_def::habd1bd66de6adfa3qUa
   7:        0x10442ca73 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_struct_def::h0bcd744d676ee3caais
   8:        0x104434127 - visit::walk_variant::h2224026504919007410
   9:        0x104433751 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h11574635434562495924
  10:        0x104427839 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h3545367658681599959
  11:        0x10442c418 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_mod::hbcd53c11c2326899Mps
  12:        0x104427725 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h3545367658681599959
  13:        0x10442c418 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_mod::hbcd53c11c2326899Mps
  14:        0x10443ae42 - lint::context::check_crate::h13f19518a42a4859LJs
  15:        0x10372121f - driver::phase_3_run_analysis_passes::h318fe58bfd9a5097tGa
  16:        0x1037007dc - driver::compile_input::hd0d89b8b8141ab40Qba
  17:        0x1037bfbb3 - run_compiler::h2abbc25866a06d5065b
  18:        0x1037bd31a - boxed::F.FnBox<A>::call_box::h14521997622206872592
  19:        0x1037bc857 - rt::unwind::try::try_fn::h10757206887470260719
  20:        0x106cc1278 - rust_try_inner
  21:        0x106cc1265 - rust_try
  22:        0x1037bcb3e - boxed::F.FnBox<A>::call_box::h2889731625864154681
  23:        0x106c3a55d - sys::thread::Thread::new::thread_start::h5fcf8fe12ec3c274mYu
  24:     0x7fff8af8c267 - _pthread_body
  25:     0x7fff8af8c1e4 - _pthread_start
```

**Comment by Manishearth** [comment]
Ugh, I was hoping we don't have to :)

**Comment by Manishearth** [comment]
Fix: https://github.com/servo/servo/blob/master/components/plugins/lints/unrooted_must_root.rs#L55 should be changed to just do `.get(id)`, and if it isn't an `Item`, get its parent and try again.

**Comment by jdm** [comment]
@pgonda want to give it a try?

**Comment by pgonda** [comment]
I'm on it!

**Comment by Manishearth** [comment]
Feel free to ping me here or in IRC for any help!

http://doc.rust-lang.org/nightly/syntax/ast_map/struct.Map.html

might help you here

**Comment by pgonda** [comment]
@Manishearth  I changed the function to this but I still see the expect_item in the backtrace, any ideas?
```
    fn check_struct_def(&mut self, cx: &Context, def: &ast::StructDef, _i: ast::Ident, _gen: &ast::Generics, id: ast::NodeId) {
        match cx.tcx.map.get(id) {
            ast_map::Node::NodeItem(item) => {
                if item.attrs.iter().all(|a| !a.check_name("must_root")) {
                    for ref field in def.fields.iter() {
                        lint_unrooted_ty(cx, &*field.node.ty,
                        "Type must be rooted, use #[must_root] on the struct definition to propagate");
                    }
                }
            }
            _ => {
                let parent_id = cx.tcx.map.get_parent(id);
                self.check_struct_def(cx, def, _i, _gen, parent_id);
            },
        }
    }
```

**Comment by Manishearth** [comment]
Are you sure it's the same backtrace? We aren't using `expect_item` anymore

**Comment by pgonda** [comment]
here it is, looks the same.  Panic on the expect_item.  Which shouldn't be in check_struct_def anymore
```stack backtrace:
   1:        0x104b434ef - sys::backtrace::write::h6990067d88907b48zVr
   2:        0x104b4bb60 - panicking::on_panic::he976cdbadffd9e1bEVv
   3:        0x104b07ed5 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
   4:        0x104b08d0c - rt::unwind::begin_unwind_fmt::h15c2d4adf8e8ecdatCv
   5:        0x10428a382 - ast_map::Map<'ast>::expect_item::h4e16fb1d667f8361hhw
   6:        0x116841e78 - TenaciousPass.LintPass::check_struct_def::hdb84ab189a85e6656ba
   7:        0x102347a73 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_struct_def::h0bcd744d676ee3caais
   8:        0x10234f127 - visit::walk_variant::h2224026504919007410
   9:        0x10234e751 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h11574635434562495924
  10:        0x102342839 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h3545367658681599959
  11:        0x102347418 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_mod::hbcd53c11c2326899Mps
  12:        0x102342725 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h3545367658681599959
  13:        0x102347418 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_mod::hbcd53c11c2326899Mps
  14:        0x102355e42 - lint::context::check_crate::h13f19518a42a4859LJs
  15:        0x10164821f - driver::phase_3_run_analysis_passes::h318fe58bfd9a5097tGa
  16:        0x1016277dc - driver::compile_input::hd0d89b8b8141ab40Qba
  17:        0x1016e6bb3 - run_compiler::h2abbc25866a06d5065b
  18:        0x1016e431a - boxed::F.FnBox<A>::call_box::h14521997622206872592
  19:        0x1016e3857 - rt::unwind::try::try_fn::h10757206887470260719
  20:        0x104bd1278 - rust_try_inner
  21:        0x104bd1265 - rust_try
  22:        0x1016e3b3e - boxed::F.FnBox<A>::call_box::h2889731625864154681
  23:        0x104b4a55d - sys::thread::Thread::new::thread_start::h5fcf8fe12ec3c274mYu
  24:     0x7fff8af8c267 - _pthread_body
  25:     0x7fff8af8c1e4 - _pthread_start
```

**Comment by jdm** [comment]
@pgonda Looks like we need to modify https://github.com/Manishearth/rust-tenacious/blob/master/src/lib.rs similarly.

**Comment by Manishearth** [comment]
Oh, that's in tenacious. I've got it.
