### ISSUE TITLE
http_loader::load::verifier panics on Twitter

### ISSUE THREAD

**Issue by jruderman** [servo/servo#6075]
Servo on Mac

./mach run --release "https://twitter.com/"

Terminal window shows two panicked threads, but the browser window stays up.

```
thread 'http_loader' panicked at 'called `Result::unwrap()` on an `Err` value: OpenSslErrors([UnknownError { library: "x509 certificate routines", function: "X509_load_cert_crl_file", reason: "PEM lib" }])', /Users/larsberg/rust/src/libcore/result.rs:729

   1:        0x101bf564f - sys::backtrace::write::h6990067d88907b48zVr
   2:        0x101bf9024 - panicking::on_panic::he976cdbadffd9e1bEVv
   3:        0x101be4c55 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
   4:        0x101be548c - rt::unwind::begin_unwind_fmt::h15c2d4adf8e8ecdatCv
   5:        0x101bf88dc - rust_begin_unwind
   6:        0x101c1dd85 - panicking::panic_fmt::haa553fbfab6eff2cNKy
   7:        0x100f5ec28 - http_loader::load::verifier::h7e27802aaa5b3a81Bqa
   8:        0x10184533b - net::HttpConnector.NetworkConnector::connect::h9d7aadda0853d8ebari
   9:        0x100f4ac75 - http_loader::load::ha6ff59125430264e7la
  10:        0x100f4a6c1 - boxed::F.FnBox<A>::call_box::h6411041859944391839
  11:        0x100f30267 - rt::unwind::try::try_fn::h13410538147360861356
  12:        0x101bfad18 - rust_try_inner
  13:        0x101bfad05 - rust_try
  14:        0x100f30552 - boxed::F.FnBox<A>::call_box::h4417194301208147025
  15:        0x101bf79ad - sys::thread::Thread::new::thread_start::h5fcf8fe12ec3c274mYu
  16:     0x7fff8e43e267 - _pthread_body
  17:     0x7fff8e43e1e4 - _pthread_start
```

**Comment by Manishearth** [comment]
Might be an SSL error. 

Perhaps we should just disable Servo's HTTPS verification until rust-pkix or similar is finished? We already know that generic openssl doesn't export full verification capabilities. cc @larsbergstrom

**Comment by larsbergstrom** [comment]
@Manishearth Hrm, that might be the right answer, though it really is a shame we can't leave it enabled. I was hoping that for any "alpha" release we do we could mix some sort of site white-list and crazy cert checking to reduce the risk of rogue content before we're ready with a full-up security response team. Though maybe I'm overthinking it and we just need to brand similarly to FF Nightly :-)

**Comment by Manishearth** [comment]
I believe that later versions of openssl have all the bits we need; so for alpha purposes we could  extend rust-openssl bindings for those and write a cargo feature gated SSL verifier that will only work for people with a really up to date openssl dylib.

I'm not sure of this though (and I don't have the time to investigate immediately)

**Comment by tyoc213** [comment]
```
     System Version: OS X 10.10.5 (14F27)
      Kernel Version: Darwin 14.5.0
```

I got ```TypeError: qa.lb is not a function```

```
$ ./mach run --release http://google.com
ERROR:js::rust: Error at https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.vwFhyajD8zA.O/m=gapi_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/am=AAI/rs=AItRSTPOWGI_kROKlKX9NGLO-MOVVH8_gQ/cb=gapi.loaded_0:200: TypeError: qa.lb is not a function

thread 'http_loader' panicked at 'called `Result::unwrap()` on an `Err` value: OpenSslErrors([UnknownError { library: "x509 certificate routines", function: "X509_load_cert_crl_file", reason: "PEM lib" }])', src/libcore/result.rs:732
stack backtrace:
   1:        0x10c32ac90 - sys::backtrace::write::h095d0f07f92e7e3eYts
   2:        0x10c32e063 - panicking::on_panic::h5f4115f30a6b4860Z7w
   3:        0x10c31d022 - rt::unwind::begin_unwind_inner::h7c54671eea5e313e0Cw
   4:        0x10c31d537 - rt::unwind::begin_unwind_fmt::h1bf10e625ad90c4f6Bw
   5:        0x10c32da87 - rust_begin_unwind
   6:        0x10c3529a0 - panicking::panic_fmt::ha8483564b9ba8c9c47D
   7:        0x10b240ec3 - http_loader::load::heb7af1147db18decPma
   8:        0x10b2339b1 - boxed::F.FnBox<A>::call_box::h1495725116212991550
   9:        0x10b22e812 - rt::unwind::try::try_fn::h6934650759630326033
  10:        0x10c32da38 - __rust_try
  11:        0x10c329690 - rt::unwind::try::inner_try::h39d984f71e9cc780Tyw
  12:        0x10b22e9c7 - boxed::F.FnBox<A>::call_box::h2462892429981721232
  13:        0x10c32cd2d - sys::thread::Thread::new::thread_start::h999b3790b6d4b23deXv
  14:     0x7fff99e0d059 - _pthread_body
  15:     0x7fff99e0cfd6 - _pthread_start
```

as for ```rust-pkix```is this the author? https://github.com/servo/servo/issues/4954#issuecomment-128057090

**Comment by nox** [comment]
This doesn't panic anymore.
