### ISSUE TITLE
LayoutTask panic loading http://en.wikipedia.org/wiki/China

### ISSUE THREAD

**Issue by snf** [servo/servo#6087]
It's failing in layout code (intermitent) in release and debug builds:
commit 089862090285b1126deaa2357505d2a027e56b2e (15/5/2015)

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcf3fb700 (LWP 43242)]
0x0000555555b9dc7d in core..option..Option$LT$Box$LT$collections..linked_list..Node$LT$fragment..Fragment$GT$$GT$$GT$::drop.34645::hae3b1cc0b88614bf ()
(gdb) bt
#0  0x0000555555b9dc7d in core..option..Option$LT$Box$LT$collections..linked_list..Node$LT$fragment..Fragment$GT$$GT$$GT$::drop.34645::hae3b1cc0b88614bf ()
#1  0x0000555555b9dd56 in collections..linked_list..Node$LT$fragment..Fragment$GT$::drop.34651::hd94d4528fc117fc9 ()
#2  0x0000555555b9dd02 in Box$LT$collections..linked_list..Node$LT$fragment..Fragment$GT$$GT$::drop.34648::h69cbccd260a71fb2 ()
#3  0x0000555555b9dc9f in core..option..Option$LT$Box$LT$collections..linked_list..Node$LT$fragment..Fragment$GT$$GT$$GT$::drop.34645::hae3b1cc0b88614bf ()
#4  0x0000555555b9dd56 in collections..linked_list..Node$LT$fragment..Fragment$GT$::drop.34651::hd94d4528fc117fc9 ()
#5  0x0000555555b9dd02 in Box$LT$collections..linked_list..Node$LT$fragment..Fragment$GT$$GT$::drop.34648::h69cbccd260a71fb2 ()
#6  0x0000555555b9dc9f in core..option..Option$LT$Box$LT$collections..linked_list..Node$LT$fragment..Fragment$GT$$GT$$GT$::drop.34645::hae3b1cc0b88614bf ()
#7  0x0000555555b9d99a in layout::linked_list::LinkedList<T>.Drop::drop (self=0x7fffcf3f4108) at /home/larsberg/rust/src/libcollections/linked_list.rs:638
#8  0x0000555555b9d893 in collections..linked_list..LinkedList$LT$fragment..Fragment$GT$::drop.34641::h597c4cae6c48a415 ()
#9  0x0000555555da3154 in layout::text::TextRunScanner::flush_clump_to_list (self=0x7fffcf3f4108, font_context=0x7ffff1d80860, out_fragments=0x7fffcf3f3948, last_whitespace=true) at /home/asdf/dev/servo/components/layout/text.rs:164
#10 0x0000555555bbc41b in layout::text::TextRunScanner::scan_for_runs (self=0x7fffcf3f4108, font_context=0x7ffff1d80860, fragments=...) at /home/asdf/dev/servo/components/layout/text.rs:68
#11 0x0000555555bcb5e6 in flush_inline_fragments_to_flow_or_list (self=0x7fffcf3f6588, fragment_accumulator=..., flow=0x7fffcf3f3eb0, flow_list=0x7fffcf3f3e00, whitespace_stripping=FromEnd, node=0x7fffcf3f65b0)
    at /home/asdf/dev/servo/components/layout/construct.rs:426
#12 layout::construct::FlowConstructor<'a>::build_flow_for_block_starting_with_fragments (self=0x7fffcf3f6588, flow=..., node=0x7fffcf3f65b0, initial_fragments=...) at /home/asdf/dev/servo/components/layout/construct.rs:611
#13 0x0000555555bce1ce in layout::construct::FlowConstructor<'a>::build_flow_for_block_like (self=0x7fffcf3f6588, flow=..., node=0x7fffcf3f65b0) at /home/asdf/dev/servo/components/layout/construct.rs:673
#14 0x0000555555bd0d09 in layout::construct::FlowConstructor<'a>::build_flow_for_block (self=0x7fffcf3f6588, node=0x7fffcf3f65b0, float_kind=...) at /home/asdf/dev/servo/components/layout/construct.rs:714
#15 0x0000555555bcd531 in layout::construct::FlowConstructor<'a>.PostorderNodeMutTraversal::process (self=0x7fffcf3f6588, node=0x7fffcf3f65b0) at /home/asdf/dev/servo/components/layout/construct.rs:1438
#16 0x0000555555d803f7 in layout::traversal::ConstructFlows<'a>.PostorderDomTraversal::process (self=0x7fffcf3f6638, node=...) at /home/asdf/dev/servo/components/layout/traversal.rs:231
#17 0x0000555555d87f74 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:33
#18 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#19 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#20 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#21 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#22 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#23 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#24 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#25 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#26 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#27 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#28 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#29 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#30 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#31 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#32 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#33 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#34 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#35 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#36 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#37 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#38 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#39 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#40 0x0000555555d87f53 in layout::sequential::traverse_dom_preorder::doit (node=..., recalc_style=..., construct_flows=...) at /home/asdf/dev/servo/components/layout/sequential.rs:30
#41 0x0000555555d5ef12 in layout::sequential::traverse_dom_preorder (root=..., shared_layout_context=0x7fffcf3f78f8) at /home/asdf/dev/servo/components/layout/sequential.rs:40
#42 0x0000555555d5ecbd in fnfn () at /home/asdf/dev/servo/components/layout/layout_task.rs:925
#43 0x0000555555d5eabb in layout::time::profile<(),closure> (category=LayoutStyleRecalc, meta=..., profiler_chan=..., callback={void (())} 0x7fffcf3f7350) at /home/asdf/dev/servo/components/profile_traits/time.rs:84
#44 0x0000555555d49fb3 in layout::layout_task::LayoutTask::handle_reflow (self=0x7fffcf3f9938, data=0x7ffff1e0b080, possibly_locked_rw_data=0x7fffcf3f9920) at /home/asdf/dev/servo/components/layout/layout_task.rs:917
#45 0x0000555555d459ed in fnfn () at /home/asdf/dev/servo/components/layout/layout_task.rs:509
#46 0x0000555555d4581b in layout::time::profile<(),closure> (category=LayoutPerform, meta=..., profiler_chan=..., callback={void (())} 0x7fffcf3f8190) at /home/asdf/dev/servo/components/profile_traits/time.rs:84
#47 0x0000555555d3c3f5 in layout::layout_task::LayoutTask::handle_request_helper (self=0x7fffcf3f9938, request=..., possibly_locked_rw_data=0x7fffcf3f9920) at /home/asdf/dev/servo/components/layout/layout_task.rs:506
#48 0x0000555555d25569 in layout::layout_task::LayoutTask::handle_request (self=0x7fffcf3f9938, possibly_locked_rw_data=0x7fffcf3f9920) at /home/asdf/dev/servo/components/layout/layout_task.rs:424
#49 0x0000555555ce9580 in layout::layout_task::LayoutTask::start (self=...) at /home/asdf/dev/servo/components/layout/layout_task.rs:343
#50 0x0000555555ce6e80 in fnfn () at /home/asdf/dev/servo/components/layout/layout_task.rs:226
#51 0x0000555555ce6875 in fnfn () at /home/asdf/dev/servo/components/util/task.rs:31
#52 0x0000555555ce6785 in layout::boxed::F.FnBox<A>::call_box (self=0x7ffff1cdc200, args=0) at /home/larsberg/rust/src/liballoc/boxed.rs:369
---Type <return> to continue, or q <return> to quit---
#53 0x0000555555ce6188 in layout::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once (self=..., args=0) at /home/larsberg/rust/src/liballoc/boxed.rs:385
#54 0x0000555555ce5844 in fnfn () at /home/larsberg/rust/src/libstd/thread/mod.rs:346
#55 0x0000555555ce57cf in layout::rt::unwind::try::try_fn<closure> (opt_closure=0x7fffcf3fa980) at /home/larsberg/rust/src/libstd/rt/unwind.rs:139
#56 0x0000555555ce576a in rt::unwind::try::try_fn::h10394029065617953192 ()
#57 0x0000555557ac6449 in rust_try_inner ()
#58 0x0000555557ac6436 in rust_try ()
#59 0x0000555555ce4c5b in layout::rt::unwind::try<closure> (f={void (())} 0x7fffcf3fa9a0) at /home/larsberg/rust/src/libstd/rt/unwind.rs:125
#60 0x0000555555ce4a21 in fnfn () at /home/larsberg/rust/src/libstd/thread/mod.rs:346
#61 0x0000555555ce64ae in layout::boxed::F.FnBox<A>::call_box (self=0x7ffff1cce150, args=0) at /home/larsberg/rust/src/liballoc/boxed.rs:369
#62 0x0000555557abff12 in sys::thread::Thread::new::thread_start::hfc58bae990d0713aR9u ()
#63 0x00007ffff7bc40a5 in start_thread (arg=0x7fffcf3fb700) at pthread_create.c:309
#64 0x00007ffff71c1cfd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
Warning: the current language does not match this frame.
```

**Comment by jdm** [comment]
@pcwalton This seems like a scary intermittent segfault in layout code.

**Comment by nox** [comment]
```
Float position error (thread <unnamed>, at /Users/nox/src/servo/components/layout/floats.rs:245)
stack backtrace:
   0:        0x1030e583e - backtrace::backtrace::trace::h36bfa93cec5a7495
   1:        0x1030e4a29 - backtrace::capture::Backtrace::new::h511e2c9424a387ee
   2:        0x102b09729 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h4bca88d9a5de6cbe
   3:        0x1056624d1 - std::panicking::rust_panic_with_hook::h45dfd77e4441d909
   4:        0x1035e7227 - std::panicking::begin_panic::hac30fa84bfe2968b
   5:        0x1035cb38f - layout::floats::Floats::available_rect::hab01dcfbe150027a
   6:        0x1035cb5f0 - layout::floats::Floats::place_between_floats::h87e724a1bff85786
   7:        0x103511a2a - layout::inline::LineBreaker::initial_line_placement::h5e1ef9163cdd7376
   8:        0x103511b0d - layout::inline::LineBreaker::reflow_fragment::h94348394dcd0281f
   9:        0x103590a8a - layout::inline::LineBreaker::reflow_fragments::h324c398735cf41f8
  10:        0x103514b4c - _$LT$layout..inline..InlineFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size::he30f9af04d280dad
  11:        0x1034d5590 - layout::flow::Flow::assign_block_size_for_inorder_child_if_necessary::h520b91e0c9cea041
  12:        0x10354b219 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  13:        0x103549013 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size_for_inorder_child_if_necessary::h0fc8e0a62412882e
  14:        0x10354b219 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  15:        0x103549013 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size_for_inorder_child_if_necessary::h0fc8e0a62412882e
  16:        0x10354b219 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  17:        0x103549013 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size_for_inorder_child_if_necessary::h0fc8e0a62412882e
  18:        0x10354b219 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  19:        0x103549013 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size_for_inorder_child_if_necessary::h0fc8e0a62412882e
  20:        0x10354b219 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  21:        0x103549013 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size_for_inorder_child_if_necessary::h0fc8e0a62412882e
  22:        0x10354b219 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  23:        0x103549013 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size_for_inorder_child_if_necessary::h0fc8e0a62412882e
  24:        0x103549e3e - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::fragment::hd766f018f5f01f6b
  25:        0x1035490a7 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::assign_block_size::h29aa060fd2f905c8
  26:        0x1035da801 - layout::parallel::top_down_flow::ha537b2482b293365
  27:        0x1035da8be - layout::parallel::top_down_flow::ha537b2482b293365
  28:        0x1035f80c6 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h9ddcfcd5ee7cf864
  29:        0x1035e74fd - std::panicking::try::do_call::hb3cd88024dc403cd
  30:        0x10566f2cc - __rust_maybe_catch_panic
  31:        0x1035e727b - std::panicking::try::h267b02e840beba18
  32:        0x1035f814f - std::panic::catch_unwind::h0c1b2349684c4395
  33:        0x1035f94bf - rayon_core::unwind::halt_unwinding::hb0e26b7b37412bfd
  34:        0x1035f0184 - rayon_core::scope::Scope::execute_job::h3762a316f1f6a3c0
  35:        0x1035dcd9a - _$LT$rayon_core..job..HeapJob$LT$BODY$GT$$u20$as$u20$rayon_core..job..Job$GT$::execute::hc93dc3b1e3ef4001
  36:        0x104dfd6f5 - rayon_core::registry::WorkerThread::wait_until_cold::h51900367aab0f6f8
  37:        0x104e0309f - rayon_core::scope::Scope::steal_till_jobs_complete::h2035b128a6c3e0f6
  38:        0x1035edb35 - rayon_core::registry::in_worker::h279f74b537aa11b0
  39:        0x1035f0344 - rayon_core::scope::scope::h97fd84510df10637
  40:        0x1035f7f2c - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h0233377478498b09
  41:        0x1035e7494 - std::panicking::try::do_call::h218e8e94865ce015
  42:        0x10566f2cc - __rust_maybe_catch_panic
  43:        0x1035e7301 - std::panicking::try::h7df6c691b3d48244
  44:        0x1035f8185 - std::panic::catch_unwind::h140929b3e9ad315e
  45:        0x1035f94f5 - rayon_core::unwind::halt_unwinding::hfa7cef6f806de7d0
  46:        0x1035dceca - _$LT$rayon_core..job..StackJob$LT$L$C$$u20$F$C$$u20$R$GT$$u20$as$u20$rayon_core..job..Job$GT$::execute::h618c081a1c7eb03e
  47:        0x104dfd6f5 - rayon_core::registry::WorkerThread::wait_until_cold::h51900367aab0f6f8
  48:        0x104dfdbb0 - rayon_core::registry::main_loop::hce3b8f273ce81dcf
  49:        0x104e0231f - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb196d8e37fe704ae
  50:        0x104dff4ff - std::panicking::try::do_call::he277f15f6b13aee9
  51:        0x10566f2cc - __rust_maybe_catch_panic
  52:        0x104dff432 - std::panicking::try::hae25aa2548f97471
  53:        0x104e02423 - std::panic::catch_unwind::h4364ea9f462b3ecf
  54:        0x104dffd52 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h7ec934835d1754e6
  55:        0x10566121b - std::sys::imp::thread::Thread::new::thread_start::h059092f30f9b13ea
  56:     0x7fffb54a393a - _pthread_body
  57:     0x7fffb54a3886 - _pthread_start
ERROR:servo: Float position error
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(1)) }, at src/libcore/result.rs:906)
stack backtrace:
   0:        0x1030e583e - backtrace::backtrace::trace::h36bfa93cec5a7495
   1:        0x1030e4a29 - backtrace::capture::Backtrace::new::h511e2c9424a387ee
   2:        0x102b09729 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h4bca88d9a5de6cbe
   3:        0x1056624d1 - std::panicking::rust_panic_with_hook::h45dfd77e4441d909
   4:        0x1056622f4 - std::panicking::begin_panic::h086bc4c09932ef88
   5:        0x105662242 - std::panicking::begin_panic_fmt::hb4108dd2abc8d550
   6:        0x1056621aa - rust_begin_unwind
   7:        0x10569be13 - core::panicking::panic_fmt::h511718275b8414ef
   8:        0x103c145c1 - core::result::unwrap_failed::hf384fec6d4e00ee9
   9:        0x103b57945 - script::dom::document::Document::add_stylesheet::h6f5ab0213a0f345f
  10:        0x103e1edb8 - script::dom::htmllinkelement::HTMLLinkElement::set_stylesheet::h3e846098ab901021
  11:        0x103f07b7f - _$LT$script..stylesheet_loader..StylesheetContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::h12ba5de0e61fb0aa
  12:        0x103f925c4 - _$LT$net_traits..FetchResponseMsg$u20$as$u20$net_traits..Action$LT$T$GT$$GT$::process::h5ae8952b9ff9ad61
  13:        0x103f8f0b1 - _$LT$script..network_listener..ListenerTask$LT$A$C$$u20$Listener$GT$$u20$as$u20$script..task..TaskOnce$GT$::run_once::h116fbe04e9e0bfab
  14:        0x103cf2f50 - _$LT$T$u20$as$u20$script..task..TaskBox$GT$::run_box::h6b5edd03bf1fde11
  15:        0x103c03880 - script::script_thread::ScriptThread::handle_msg_from_script::hcfa95fff6433d4b3
  16:        0x103fc6689 - script::script_thread::ScriptThread::profile_event::h3a0684c3e403e515
  17:        0x103bfa9cd - script::script_thread::ScriptThread::start::h50c29d0459b78f00
  18:        0x10405f81e - profile_traits::mem::ProfilerChan::run_with_memory_reporting::h15401f631eed0b6d
  19:        0x103c688af - std::sys_common::backtrace::__rust_begin_short_backtrace::h65776958eb0a9787
  20:        0x1042bf0ed - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h9f4c1af60cc71a2a
  21:        0x1039688cd - std::panicking::try::do_call::hae595c6c28828f4f
  22:        0x10566f2cc - __rust_maybe_catch_panic
  23:        0x10392a12b - std::panicking::try::he1d99ca594b167b4
  24:        0x10437a4af - std::panic::catch_unwind::h2f9c5d8243a49d74
  25:        0x103e2c3f8 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h3d38621286c2c19e
  26:        0x10566121b - std::sys::imp::thread::Thread::new::thread_start::h059092f30f9b13ea
  27:     0x7fffb54a393a - _pthread_body
  28:     0x7fffb54a3886 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"
```

**Comment by mrobinson** [comment]
This was an issue with legacy layout, so I'm going to go ahead and close this.
