### ISSUE TITLE
Get pdf.js working in Servo

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#6098]
https://mozilla.github.io/pdf.js/

**Comment by KiChjang** [comment]
Using the current trunk, the console outputted the following when I clicked on "Demo":
```
$ ./mach run https://mozilla.github.io/pdf.js/

ERROR:net_traits::image::base: stb_image failed: stbi_load_from_memory failed
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.1.147)
Warning: Unhandled rejection: TypeError: window.history is undefined
pdfHistoryInitialize@https://mozilla.github.io/pdf.js/web/viewer.js:1466
pdfViewLoad/<@https://mozilla.github.io/pdf.js/web/viewer.js:6372
runHandlers@https://mozilla.github.io/pdf.js/build/pdf.js:1159
```
Here's the screenshot of what I have:

![pdfjs](https://cloud.githubusercontent.com/assets/3248587/7671307/bc9d6778-fc97-11e4-94f7-05954439200c.png)

**Comment by kmcallister** [comment]
Yeah that's how it looks here as well. I didn't get the console output though (maybe I have it disabled somehow).

You can try my [piston-image](https://github.com/kmcallister/servo/tree/piston-image) branch, although it too fails on [many images](http://kmcallister.github.io/docs/piston-image-report/index.html).

**Comment by jdm** [comment]
#5669 is relevant to the console output.

**Comment by eefriedman** [comment]
Current status: pdf.js assumes window.history exists.  If you hack past that, there aren't any errors, the UI renders, and the progress bar works, but it never actually shows the rendered page.

**Comment by yurydelendik** [comment]
You don't have to block this by `window.history` or `localStorage` API -- those are not essential APIs for PDF.js library. The viewer for Servo might look different or not use the same DOM APIs.

The main part of the library is canvas support specifically context 2d. See `ctx.xxxx` function usages in the https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js. (And probably @font-face usage with canvas).

Please find more simplified viewer at http://mozilla.github.io/pdf.js/examples/learning/prevnext.html

**Comment by yurydelendik** [comment]
See also #8917

**Comment by atouchet** [comment]
I tried testing this out and loading https://mozilla.github.io/pdf.js/web/viewer.html resulted in an error message in Servo.

![PDF1](https://user-images.githubusercontent.com/26315797/80892482-6dda9c00-8c7f-11ea-8054-672429fdce06.png)

https://mozilla.github.io/pdf.js/es5/web/viewer.html loaded however no content in the PDF was visible.

![PDF2](https://user-images.githubusercontent.com/26315797/80892488-7501aa00-8c7f-11ea-8392-9c0cc20fc706.png)

**Comment by sagudev** [comment]
The first error I get is about missing AbortController, we have PR landed, but sadly it got reverted due to flakiness: https://github.com/servo/servo/pull/31361, but even if I use that PR PDF is note rendered (see last image of previous comment), up-to-date link for legacy pdf.js: https://mozilla.github.io/pdf.js/legacy/web/viewer.html. https://mozilla.github.io/pdf.js/examples/ gives this error:
>pdf.mjs:11002:32 Promise.withResolvers is not a function

I will try to get the list what we are missing for it to work apart from the two known ones.

**Comment by msub2** [comment]
@sagudev Any update on what else might be blocking this (aside from AbortController support)?

**Comment by sagudev** [comment]
Not really, as I got sidetracked so you can pick it up.

**Comment by arihant2math** [comment]
`AbortSignal` is needed for the legacy viewer.

**Comment by arihant2math** [comment]
https://mozilla.github.io/pdf.js/legacy/web/viewer.html works now!

<img width="2016" height="1438" alt="Image" src="https://github.com/user-attachments/assets/86bc43ed-2927-4e2f-a9a6-9361e2bea790" />

the top buttons are still black, mainly because they are neither images nor svgs, but some sort of font (from what it seems).

**Comment by arihant2math** [comment]
Current issue with the non-legacy viewer: #38811

**Comment by arihant2math** [comment]
Progress on the modern viewer: <img width="1136" height="880" alt="Image" src="https://github.com/user-attachments/assets/0e137467-4a35-4cc0-aa9a-9467c17a28f8" />

**Comment by arihant2math** [comment]
Logs:
```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
evaluate_script failed
[2025-10-02T03:31:28Z ERROR script::dom::bindings::error] Error at https://mozilla.github.io/pdf.js/build/pdf.worker.mjs:5441:28 import.meta may only appear in a module
Warning: Setting up fake worker.
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 5.4.284 [3234912c8])
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Enable the `dom.textMetrics.fontBoundingBox.enabled` preference in `about:config` to improve TextLayer rendering.
Warning: Enable the `dom.textMetrics.fontBoundingBox.enabled` preference in `about:config` to improve TextLayer rendering.
Warning: ICCBased color space: "InvalidAccessError: The object does not support the operation or argument.".
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
Warning: Failed to load font '': 'SyntaxError: The string did not match the expected pattern.'.
```
The `dom.textMetrics.fontBoundingBox.enabled`message is from pdfjs

**Comment by jdm** [comment]
>[2025-10-02T03:31:28Z ERROR script::dom::bindings::error] Error at https://mozilla.github.io/pdf.js/build/pdf.worker.mjs:5441:28 import.meta may only appear in a module

This is https://github.com/servo/servo/issues/23308.

**Comment by arihant2math** [comment]
Is the font issue already known?

**Comment by jdm** [comment]
I predict that it's coming from https://github.com/servo/servo/blob/9e380614eef25828bfab9c106870e619791fffa3/components/script/dom/fontface.rs#L194, but I don't think the issue is known already.

**Comment by arihant2math** [comment]
Yup that was it:
backtrace as of 615a5c63d72 (with patch):
```
* thread #49, name = 'Script(1,1)', stop reason = breakpoint 1.1
  * frame #0: 0x00000001021f2d08 servo`script::dom::fontface::FontFace::new_failed_font_face::h82e52db4a9a38c97(global=0x000000013bf30c00, (null)=CanGc @ 0x000000017573323e) at fontface.rs:194:56
    frame #1: 0x00000001021f319c servo`script::dom::fontface::FontFace::new_inherited::hd3e56647d7548c6d(global=0x000000013bf30c00, family_name=DOMString @ 0x00000001757339a0, source=StringOrArrayBufferViewOrArrayBuffer @ 0x00000001757339c0, descriptors=0x0000000175733c90, (null)=CanGc @ 0x00000001757336f6) at fontface.rs:231:20
    frame #2: 0x00000001021f3520 servo`script::dom::fontface::FontFace::new::h6c2c2a883aa529ec(global=0x000000013bf30c00, proto=Option<mozjs::gc::root::Handle<*mut mozjs_sys::generated::root::JSObject>> @ 0x0000000175733918, font_family=<unavailable>, source=<unavailable>, descriptors=0x0000000175733c90, (null)=CanGc @ 0x000000017573392e) at fontface.rs:284:22
    frame #3: 0x00000001021f6600 servo`_$LT$script..dom..fontface..FontFace$u20$as$u20$script_bindings..codegen..GenericBindings..FontFaceBinding..FontFace_Binding..FontFaceMethods$LT$script..dom..bindings..codegen..DomTypeHolder..DomTypeHolder$GT$$GT$::Constructor::h8c7a94dc16f26090(window=0x000000013bf30c00, proto=Option<mozjs::gc::root::Handle<*mut mozjs_sys::generated::root::JSObject>> @ 0x00000001757339e8, (null)=CanGc @ 0x00000001757339f7, family=DOMString @ 0x0000000175733fa0, source=StringOrArrayBufferViewOrArrayBuffer @ 0x0000000175733fc0, descriptors=0x0000000175733c90) at fontface.rs:575:9
    frame #4: 0x0000000101468cfc servo`script_bindings::codegen::GenericBindings::FontFaceBinding::FontFace_Binding::_constructor::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he473d000efceec58(cx=JSContext @ 0x0000000175733b70, args=0x0000000175734238, global=0x000000013bf30c00, desired_proto=Handle<*mut mozjs_sys::generated::root::JSObject> @ 0x0000000175734000) at FontFaceBinding.rs:2186:44
    frame #5: 0x00000001016f0e14 servo`script_bindings::constructor::call_default_constructor::h073f2c26bf85ae7e(cx=JSContext @ 0x0000000175734128, args=0x0000000175734238, global=0x000000013bf30c00, proto_id=FontFace, ctor_name="FontFace", creator=0x000000010146c990, constructor={closure_env#0}<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder> @ 0x00000001757341b8) at constructor.rs:36:5
    frame #6: 0x0000000101468640 servo`script_bindings::codegen::GenericBindings::FontFaceBinding::FontFace_Binding::_constructor::_$u7b$$u7b$closure$u7d$$u7d$::h2af002beb26dcec0 at FontFaceBinding.rs:2130:21
    frame #7: 0x0000000103b84998 servo`core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$mut$u20$F$GT$::call_once::h8f1881a942d811e2(self=&mut dyn core::ops::function::FnMut<(), Output=()> @ 0x0000000175734320, args=<unavailable>) at function.rs:305:21
```

patch:
```
diff --git a/components/script/dom/resizeobserver.rs b/components/script/dom/resizeobserver.rs
index ce3d9a03c4d..8d98db0359f 100644
--- a/components/script/dom/resizeobserver.rs
+++ b/components/script/dom/resizeobserver.rs
@@ -155,7 +155,7 @@ impl ResizeObserver {
                 &window,
                 target,
                 &content_rect,
-                &[],
+                &[&*observer_size],
                 &[&*observer_size],
                 &[],
                 can_gc,
```
