### ISSUE TITLE
GL error in test-js-image.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#644]
Run the test, then close the window while it's executing:
```
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Serial number of failed request:  10124
  Current serial number in output stream:  10125
```
```
#0  0x0000000000000000 in ?? ()
#1  0x00007fffdfd5f9ce in brw_upload_indices () from /usr/lib64/dri/i965_dri.so
#2  0x00007fffdfd9fb42 in brw_upload_state () from /usr/lib64/dri/i965_dri.so
#3  0x00007fffdfd5f25f in brw_draw_prims () from /usr/lib64/dri/i965_dri.so
#4  0x00007fffdf89d93e in vbo_handle_primitive_restart () from /lib64/libdricore9.2.0.so.1
#5  0x00007fffdf89e8a5 in vbo_validated_drawrangeelements () from /lib64/libdricore9.2.0.so.1
#6  0x00007fffdf89ec04 in vbo_exec_DrawElements () from /lib64/libdricore9.2.0.so.1
#7  0x00007ffff7423d36 in GrGpuGL::onGpuDraw(GrDrawTarget::DrawInfo const&) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#8  0x00007ffff73f6c71 in GrInOrderDrawBuffer::flush() () from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#9  0x00007ffff73e2b55 in GrContext::flush(int) () from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#10 0x00007ffff73e2e8b in GrContext::resolveRenderTarget(GrRenderTarget*) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#11 0x00007ffff686c3a9 in __morestack () from /run/media/jdm/ssd/servo/build/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustrt.so
#12 0x00007ffff685c8ec in call_on_c_stack (fn_ptr=0x7ffff7362750 <AzDrawTargetFlush__c_stack_shim>, args=0x7fffd4205798, this=0x7fffe4206b40) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_task.h:481
#13 upcall_call_shim_on_c_stack (args=0x7fffd4205798, fn_ptr=0x7ffff7362750 <AzDrawTargetFlush__c_stack_shim>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_upcall.cpp:70
#14 0x00007ffff7360da8 in azure_hl::__extensions__::meth_6256::flush::_7696d3b5ca3f6f5::_0$x2e1 ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#15 0x00000000004b3c6a in render_task::__extensions__::render_27527::anon::anon::anon::anon::expr_fn_27570 ()
#16 0x000000000045c93e in time::profile_19811::_c2d03091e655a184::_0$x2e1 ()
#17 0x00000000004b354d in render_task::__extensions__::render_27527::anon::anon::expr_fn_27532 ()
#18 0x000000000045c93e in time::profile_19811::_c2d03091e655a184::_0$x2e1 ()
#19 0x00000000004b2977 in render_task::__extensions__::render_27527::anon::expr_fn_27530 ()
#20 0x000000000045c93e in time::profile_19811::_c2d03091e655a184::_0$x2e1 ()
#21 0x000000000054e8e8 in __morestack ()
#22 0x00000000004a1800 in render_task::__extensions__::create_26404::anon::expr_fn_26425 ()
#23 0x000000000054e8e8 in __morestack ()
#24 0x00007ffff7bfb575 in task::spawn::spawn_raw_oldsched::make_child_wrapper::anon::expr_fn_18675 ()
   from /run/media/jdm/ssd/servo/build/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff7cfd1a0 in __morestack () from /run/media/jdm/ssd/servo/build/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff685b74b in task_start_wrapper (a=0x7fffe42144b0) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_task.cpp:164
#27 0x0000000000000000 in ?? ()
```

**Comment by jdm** [comment]
Super old graphics code, not worth tracking.
