### ISSUE TITLE
WebSockets crash.

### ISSUE THREAD

**Issue by nickdesaulniers** [servo/servo#6481]
backtrace was:

```
WebSocket open
[object Arguments]
thread 'ScriptTask PipelineId(0)' panicked at 'called `Option::unwrap()` on a `None` value', /Users/larsberg/rust/src/libcore/option.rs:362
stack backtrace:
   1:        0x103b57435 - sys::backtrace::write::h0f775b94d5ab846csas
   2:        0x103b5acf4 - panicking::on_panic::h2c2da1880263a4ecOtw
   3:        0x103b47728 - rt::unwind::begin_unwind_inner::h4859292dfbc160e26bw
   4:        0x103b47dec - rt::unwind::begin_unwind_fmt::h96f92c9348b5a966cbw
   5:        0x103b5a5ac - rust_begin_unwind
   6:        0x103b82965 - panicking::panic_fmt::h8dfe66741ed7f9d7i5B
   7:        0x103b7fbc4 - panicking::panic::h18cb8179d18d634aP3B
   8:        0x10234d9e8 - option::Option<T>::unwrap::h8423211507191548498
   9:        0x10234b843 - dom::document::_&'a Document.DocumentHelpers<'a>::handle_mouse_move_event::h4721cb70bba2f524Swy
  10:        0x1025d1ace - script_task::ScriptTask::handle_event::h9468360999a2754ceZ2
  11:        0x1025f5c88 - script_task::ScriptTask::handle_msg_from_constellation::h593df61cd59cd22b9d2
  12:        0x1025ce860 - script_task::ScriptTask::handle_msgs::h98dbe92caff45ee6l51
  13:        0x1025ccdb1 - script_task::ScriptTask::start::hdce9b45a914a265db51
  14:        0x101473d47 - script_task::ScriptTask.ScriptTaskFactory::create::closure.17542
  15:        0x1014734e4 - task::spawn_named_with_send_on_failure::closure.17536
  16:        0x1014733f4 - boxed::F.FnBox<A>::call_box::h1711554796321986499
  17:        0x10139cf2b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h2369927054582299281
  18:        0x10139c9bb - thread::Builder::spawn_inner::closure.11090
  19:        0x10139c93e - rt::unwind::try::try_fn::__rust_abi::h1103550376137095098
  20:        0x10139c8d9 - rt::unwind::try::try_fn::h1103550376137095098
  21:        0x103b5c8a8 - rust_try_inner
  22:        0x103b5c895 - rust_try
  23:        0x103b55625 - rt::unwind::try::inner_try::h27133e9e14aca845Z7v
  24:        0x10139c83f - rt::unwind::try::h9276038484245866040
  25:        0x10139c674 - thread::Builder::spawn_inner::closure.11039
  26:        0x10139d26d - boxed::F.FnBox<A>::call_box::h1185152306260835494
  27:        0x103b5963d - sys::thread::Thread::new::thread_start::hd4ea41c9b4c4555dywv
  28:     0x7fff8e539267 - _pthread_body
  29:     0x7fff8e5391e4 - _pthread_start
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:731
stack backtrace:
   1:        0x103b57435 - sys::backtrace::write::h0f775b94d5ab846csas
   2:        0x103b5acf4 - panicking::on_panic::h2c2da1880263a4ecOtw
   3:        0x103b47728 - rt::unwind::begin_unwind_inner::h4859292dfbc160e26bw
   4:        0x103b47dec - rt::unwind::begin_unwind_fmt::h96f92c9348b5a966cbw
   5:        0x103b5a5ac - rust_begin_unwind
   6:        0x103b82965 - panicking::panic_fmt::h8dfe66741ed7f9d7i5B
   7:        0x102dcd369 - result::Result<T, E>::unwrap::h7180025777479075802
   8:        0x102dcd571 - pipeline::Pipeline::force_exit::hf517f5d573ed7bc4L6c
   9:        0x101429e7c - constellation::Constellation<LTF, STF>::close_pipeline::h990000882221690864
  10:        0x1014280a8 - constellation::Constellation<LTF, STF>::handle_failure_msg::h3989823880587830185
  11:        0x101418b5b - constellation::Constellation<LTF, STF>::handle_request::h15191182854002092880
  12:        0x1014132c8 - constellation::Constellation<LTF, STF>::run::h12655382341489615043
  13:        0x10139e4f8 - constellation::Constellation<LTF, STF>::start::closure.11125
  14:        0x10139d5ce - task::spawn_named::closure.11118
  15:        0x10139d4e4 - boxed::F.FnBox<A>::call_box::h5519369724648841770
  16:        0x10139cf2b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h2369927054582299281
  17:        0x10139c9bb - thread::Builder::spawn_inner::closure.11090
  18:        0x10139c93e - rt::unwind::try::try_fn::__rust_abi::h1103550376137095098
  19:        0x10139c8d9 - rt::unwind::try::try_fn::h1103550376137095098
  20:        0x103b5c8a8 - rust_try_inner
  21:        0x103b5c895 - rust_try
  22:        0x103b55625 - rt::unwind::try::inner_try::h27133e9e14aca845Z7v
  23:        0x10139c83f - rt::unwind::try::h9276038484245866040
  24:        0x10139c674 - thread::Builder::spawn_inner::closure.11039
  25:        0x10139d26d - boxed::F.FnBox<A>::call_box::h1185152306260835494
  26:        0x103b5963d - sys::thread::Thread::new::thread_start::hd4ea41c9b4c4555dywv
  27:     0x7fff8e539267 - _pthread_body
  28:     0x7fff8e5391e4 - _pthread_start
thread 'StorageManager' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:731
stack backtrace:
   1:        0x103b57435 - sys::backtrace::write::h0f775b94d5ab846csas
   2:        0x103b5acf4 - panicking::on_panic::h2c2da1880263a4ecOtw
   3:        0x103b47728 - rt::unwind::begin_unwind_inner::h4859292dfbc160e26bw
   4:        0x103b47dec - rt::unwind::begin_unwind_fmt::h96f92c9348b5a966cbw
   5:        0x103b5a5ac - rust_begin_unwind
   6:        0x103b82965 - panicking::panic_fmt::h8dfe66741ed7f9d7i5B
   7:        0x102f99009 - result::Result<T, E>::unwrap::h3040041500036889112
   8:        0x102f96b15 - storage_task::StorageManager::start::hfb51f807ca127c7eWXf
   9:        0x102f96a27 - storage_task::StorageTask.StorageTaskFactory::new::closure.30288
  10:        0x102f968ec - task::spawn_named::closure.30282
  11:        0x102f96845 - boxed::F.FnBox<A>::call_box::h12645339685218875796
  12:        0x102df929b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h13628475787335208920
  13:        0x102df8d2b - thread::Builder::spawn_inner::closure.16345
  14:        0x102df8cae - rt::unwind::try::try_fn::__rust_abi::h11048045091749574904
  15:        0x102df8c49 - rt::unwind::try::try_fn::h11048045091749574904
  16:        0x103b5c8a8 - rust_try_inner
  17:        0x103b5c895 - rust_try
  18:        0x103b55625 - rt::unwind::try::inner_try::h27133e9e14aca845Z7v
  19:        0x102df8baf - rt::unwind::try::h5923044064747676670
  20:        0x102df89e4 - thread::Builder::spawn_inner::closure.16294
  21:        0x102df964d - boxed::F.FnBox<A>::call_box::h14579291427427563025
  22:        0x103b5963d - sys::thread::Thread::new::thread_start::hd4ea41c9b4c4555dywv
  23:     0x7fff8e539267 - _pthread_body
  24:     0x7fff8e5391e4 - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:731
stack backtrace:
   1:        0x103b57435 - sys::backtrace::write::h0f775b94d5ab846csas
   2:        0x103b5acf4 - panicking::on_panic::h2c2da1880263a4ecOtw
   3:        0x103b47728 - rt::unwind::begin_unwind_inner::h4859292dfbc160e26bw
   4:        0x103b47dec - rt::unwind::begin_unwind_fmt::h96f92c9348b5a966cbw
   5:        0x103b5a5ac - rust_begin_unwind
   6:        0x103b82965 - panicking::panic_fmt::h8dfe66741ed7f9d7i5B
   7:        0x10123b389 - result::Result<T, E>::unwrap::h17134747915864894117
   8:        0x10123a5ec - compositor::IOCompositor<Window>::send_viewport_rect_for_layer::h12775575905330047495
   9:        0x101239fc0 - compositor::IOCompositor<Window>::send_viewport_rects_for_all_layers::h17903675239302571170
  10:        0x10126c52f - compositor::IOCompositor<Window>::process_pending_scroll_events::h11018134351463400827
  11:        0x10125baa4 - compositor::IOCompositor<Window>::composite_specific_target::h4140492717290617639
  12:        0x101274961 - compositor::IOCompositor<Window>::composite::h13748739011498413661
  13:        0x101213435 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h13429031280921982533
  14:        0x10127be85 - Browser::handle_events::h38af4d0b89668ad41ca
  15:        0x1010cc1a5 - main::h0ff72bcd2eb25e2dqaa
  16:        0x103b5c8a8 - rust_try_inner
  17:        0x103b5c895 - rust_try
  18:        0x103b5b450 - rt::lang_start::h5c2e9daa2b12406fSow
  19:        0x10127a37e - main
thread 'LayoutTask PipelineId(0)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:731
stack backtrace:
   1:        0x103b57435 - sys::backtrace::write::h0f775b94d5ab846csas
   2:        0x103b5acf4 - panicking::on_panic::h2c2da1880263a4ecOtw
   3:        0x103b47728 - rt::unwind::begin_unwind_inner::h4859292dfbc160e26bw
   4:        0x103b47dec - rt::unwind::begin_unwind_fmt::h96f92c9348b5a966cbw
   5:        0x103b5a5ac - rust_begin_unwind
   6:        0x103b82965 - panicking::panic_fmt::h8dfe66741ed7f9d7i5B
Servo exited with return value 101
```

**Comment by Ms2ger** [comment]
There's plenty of those; I expect to fix them in Q3.

**Comment by jdm** [comment]
Does this still occur?

**Comment by nox** [comment]
Let's say it doesn't, it's been 2 years.
