### ISSUE TITLE
Failure at float_context.clone()

### ISSUE THREAD

**Issue by tikue** [servo/servo#669]
To reproduce: go to http://en.wikipedia.org/wiki/Main_Page
The failure occurs nondeterministically by clicking portal links in the upper left corner. Technology and Society have both caused the failure.

```
Breakpoint 1, upcall_fail (expr=0x100165320 "Can't clone an invalid float context", file=0x100165350 "/Users/tkuehn/servo/src/components/main/layout/float_context.rs", line=54) at rust_upcall.cpp:126
126	            size_t line) {
(gdb) bt
#0  upcall_fail (expr=0x100165320 "Can't clone an invalid float context", file=0x100165350 "/Users/tkuehn/servo/src/components/main/layout/float_context.rs", line=54) at rust_upcall.cpp:126
#1  0x000000010035d3f2 in sys::rustrt::rust_upcall_fail::_f25e955198ccc5c0::_0$x2e8$x2dpre ()
#2  0x000000010035d6d0 in sys::begin_unwind_::_89e154cd0915671::_0$x2e8$x2dpre ()
#3  0x000000010035e007 in sys::__extensions__::fail_with::anon::anon::expr_fn_22325 ()
#4  0x000000010035d490 in str::as_buf_22316::_f8c6f4a6f9cb738::_0$x2e8$x2dpre ()
#5  0x000000010035df4e in sys::__extensions__::fail_with::anon::expr_fn_22323 ()
#6  0x000000010035d490 in str::as_buf_22316::_f8c6f4a6f9cb738::_0$x2e8$x2dpre ()
#7  0x0000000100257820 in sys::__extensions__::meth_11962::fail_with::_db4c44d01ce4116::_0$x2e8$x2dpre ()
#8  0x00000001000fd675 in layout::inline::__extensions__::meth_31796::assign_height_inline::_d84e9e81e3c1aa8a::_0$x2e1 ()
#9  0x0000000100147dd7 in __morestack ()
#10 0x00000001000fcd6c in layout::inline::__extensions__::meth_31796::assign_height_inline::_d84e9e81e3c1aa8a::_0$x2e1 ()
#11 0x00000001000f7afe in layout::float::__extensions__::assign_height_float::anon::expr_fn_31703 ()
#12 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#13 0x00000001000f5f08 in layout::float::__extensions__::meth_31701::assign_height_float::_d84e9e81e3c1aa8a::_0$x2e1 ()
#14 0x00000001000bf7b8 in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#15 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#16 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#17 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#18 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#19 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#20 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#21 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#22 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#23 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#24 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#25 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#26 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#27 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#28 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#29 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#30 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#31 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#32 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#33 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#34 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#35 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#36 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#37 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#38 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#39 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#40 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#41 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#42 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#43 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#44 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#45 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#46 0x00000001000bf7cf in layout::flow::__extensions__::meth_29448::assign_height::_f8dbe3d04590c84f::_0$x2e1 ()
#47 0x00000001000bf4a3 in layout::block::__extensions__::assign_height_block::anon::expr_fn_29441 ()
#48 0x00000001000b7e45 in tree::__extensions__::each_child_29304::_865977c434d6a::_0$x2e1 ()
#49 0x00000001000be061 in layout::block::__extensions__::meth_29428::assign_height_block::_d84e9e81e3c1aa8a::_0$x2e1 ()
#50 0x0000000100147dd7 in __morestack ()
```

**Comment by narfg** [comment]
I can't reproduce this.

**Comment by jdm** [comment]
Agreed.
