### ISSUE TITLE
Android Nightly fails due to lack of GCC 4.7

### ISSUE THREAD

**Issue by jdm** [servo/servo#6743]
mozjs has configure checks for 4.7, which the nightly builder is apparently lacking.

```
failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#065c9a42)`
Process didn't exit successfully: `/home/servo/buildbot/slave/android-nightly/build/target/release/build/mozjs_sys-e411d274df144795/build-script-build` (exit code: 101)
--- stdout
cd /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/build/mozjs_sys-e411d274df144795/out && \
MOZ_TOOLS="" CC="arm-linux-androideabi-gcc" CPP="arm-linux-androideabi-gcc -E" CXX="arm-linux-androideabi-g++" AR="arm-linux-androideabi-ar" \
/home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure --enable-gczeal --target=arm-linux-androideabi --with-android-ndk=/home/servo/android-ndk-r10c/ --with-android-toolchain=/home/servo/ndk-toolchain/ --without-intl-api --disable-jemalloc
creating cache ./config.cache
checking host system type... x86_64-unknown-linux-gnu
checking target system type... arm-linux-android
checking build system type... x86_64-unknown-linux-gnu
checking for gawk... gawk
checking for perl5... no
checking for perl... /usr/bin/perl
checking for android platform directory... /home/servo/android-ndk-r10c//platforms/android-9/arch-arm
cross compiling from x86_64-unknown-linux-gnu to arm-linux-android
checking for host c compiler... checking for cc... cc
cc
checking for host c++ compiler... checking for c++... c++
c++
checking for ranlib... no
checking for ar... no
checking whether the host c compiler (cc    ) works... yes
checking whether the host c++ compiler (c++    ) works... yes
checking for arm-linux-androideabi-gcc... arm-linux-androideabi-gcc
checking for gcc... arm-linux-androideabi-gcc
checking whether the C compiler (arm-linux-androideabi-gcc -mandroid -fno-short-enums -fno-exceptions  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined ) works... yes
checking whether the C compiler (arm-linux-androideabi-gcc -mandroid -fno-short-enums -fno-exceptions  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined ) is a cross-compiler... yes
checking whether we are using GNU C... yes
checking whether arm-linux-androideabi-gcc accepts -g... yes
checking for arm-linux-androideabi-g++... arm-linux-androideabi-g++
checking for c++... arm-linux-androideabi-g++
checking whether the C++ compiler (arm-linux-androideabi-g++ -mandroid -fno-short-enums -fno-exceptions -Wno-psabi  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined ) works... yes
checking whether the C++ compiler (arm-linux-androideabi-g++ -mandroid -fno-short-enums -fno-exceptions -Wno-psabi  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined ) is a cross-compiler... yes
checking whether we are using GNU C++... yes
checking whether arm-linux-androideabi-g++ accepts -g... yes
checking for arm-linux-androideabi-ranlib... /home/servo/ndk-toolchain//bin/arm-linux-androideabi-ranlib
checking for arm-linux-androideabi-ar... /home/servo/ndk-toolchain//bin/arm-linux-androideabi-ar
checking for arm-linux-androideabi-as... /home/servo/ndk-toolchain//bin/arm-linux-androideabi-as
checking for arm-linux-androideabi-ld... /home/servo/ndk-toolchain//bin/arm-linux-androideabi-ld
checking for arm-linux-androideabi-strip... /home/servo/ndk-toolchain//bin/arm-linux-androideabi-strip
checking for arm-linux-androideabi-windres... no
checking for arm-linux-android-windres... no
checking for arm-linux-androideabi-otool... no
checking for arm-linux-android-otool... no
------ config.log ------
configure:2168: checking whether we are using GNU C
configure:2177: arm-linux-androideabi-gcc -E conftest.c
configure:2196: checking whether arm-linux-androideabi-gcc accepts -g
configure:2232: checking for arm-linux-androideabi-g++
configure:2268: checking for c++
configure:2300: checking whether the C++ compiler (arm-linux-androideabi-g++ -mandroid -fno-short-enums -fno-exceptions -Wno-psabi  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined ) works
configure:2316: arm-linux-androideabi-g++ -o conftest -mandroid -fno-short-enums -fno-exceptions -Wno-psabi  -idirafter /home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/include  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined  conftest.C  1>&5
configure:2342: checking whether the C++ compiler (arm-linux-androideabi-g++ -mandroid -fno-short-enums -fno-exceptions -Wno-psabi  -mandroid -L/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib -Wl,-rpath-link=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/lib --sysroot=/home/servo/android-ndk-r10c//platforms/android-9/arch-arm -llog -Wl,--allow-shlib-undefined ) is a cross-compiler
configure:2347: checking whether we are using GNU C++
configure:2356: arm-linux-androideabi-g++ -E conftest.C
configure:2375: checking whether arm-linux-androideabi-g++ accepts -g
configure:2424: arm-linux-androideabi-gcc -c -mandroid -fno-short-enums -fno-exceptions  -idirafter /home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/include  conftest.c 1>&5
configure:2441: arm-linux-androideabi-gcc -c -mandroid -fno-short-enums -fno-exceptions  -idirafter /home/servo/android-ndk-r10c//platforms/android-9/arch-arm/usr/include  conftest.c 1>&5
configure: In function 'main':
configure:2437:1: warning: incompatible implicit declaration of built-in function 'exit' [enabled by default]
configure:2463: checking for arm-linux-androideabi-ranlib
configure:2498: checking for arm-linux-androideabi-ar
configure:2533: checking for arm-linux-androideabi-as
configure:2568: checking for arm-linux-androideabi-ld
configure:2603: checking for arm-linux-androideabi-strip
configure:2638: checking for arm-linux-androideabi-windres
configure:2638: checking for arm-linux-android-windres
configure:2673: checking for arm-linux-androideabi-otool
configure:2673: checking for arm-linux-android-otool
configure: error: Only GCC 4.7 or newer supported
makefile.cargo:52: recipe for target 'all' failed

--- stderr
/home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
configure: error: Only GCC 4.7 or newer supported
make: *** [all] Error 1
thread '<main>' panicked at 'assertion failed: result.success()', /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/build.rs:16
stack backtrace:
   1:     0x7fe39adf354e - sys::backtrace::write::hfe027f56cae344aapps
   2:     0x7fe39adfb9a5 - panicking::on_panic::hcd0100c6199f27b1Cax
   3:     0x7fe39adbdf9e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw
   4:     0x7fe39b5486ec - rt::unwind::begin_unwind::h17422982905091001258
                        at src/libstd/rt/unwind/mod.rs:226
   5:     0x7fe39b542046 - main::h5fbf0d7980f50530iaa
                        at /home/servo/buildbot/slave/android-nightly/build/components/servo/<std macros>:3
   6:     0x7fe39ae76898 - rust_try_inner
   7:     0x7fe39ae76885 - rust_try
   8:     0x7fe39adfd5a8 - rt::lang_start::h6c59a9adbeceea29z5w
   9:     0x7fe39b548b9b - main
  10:     0x7fe39a535ec4 - __libc_start_main
  11:     0x7fe39b541cf8 - <unknown>
  12:                0x0 - <unknown>
```

cc @larsbergstrom

**Comment by larsbergstrom** [comment]
We added the `--toolchain=arm-linux-androideabi-4.8` argument to the NDK installer arguments for the builders, but only force-pushed the update to the normal android+gonk builder. Since salt is purely file-based and didn't know this needed to be re-run, I blew away the directory and forced it to be reinstalled.
