### ISSUE TITLE
Intermittent timeout in /html/semantics/embedded-content/the-img-element/current-pixel-density/error.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#6785]
```
 8:54.63 TEST_START: Thread-TestrunnerManager-2 /html/semantics/embedded-content/the-img-element/current-pixel-density/error.html
 8:54.88 LOG: Thread-Log INFO STDERR: Exception in thread ProcessReader:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 894, in _read
    callback(line.rstrip())
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 814, in __call__
    e(*args, **kwargs)
  File "/home/servo/buildbot/slave/linux2/build/tests/wpt/harness/wptrunner/executors/executorservo.py", line 132, in on_output
    self.result_data = json.loads(line[len(prefix):])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4486 - line 1 column 4563 (char 4485 - 4562)
 9:09.73 TEST_END: Thread-TestrunnerManager-2 TIMEOUT, expected OK
```
Looks super similar to #6701.

**Comment by nox** [comment]
See #6701.
