### ISSUE TITLE
WebGlContext Crashing

### ISSUE THREAD

**Issue by farodin91** [servo/servo#6805]
System: Ubuntu 15.04
GPU: GTX 560 Ti
Driver: version 346.59

```
./mach run http://html5test.com
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "glx::ChooseFBConfig"', src/libcore/result.rs:731
stack backtrace:
   1:     0x7f98c157b05e - sys::backtrace::write::hfe027f56cae344aapps
   2:     0x7f98c157e745 - panicking::on_panic::hcd0100c6199f27b1Cax
   3:     0x7f98c156b89e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw
   4:     0x7f98c156c28c - rt::unwind::begin_unwind_fmt::h5a900a56c2bf32ccmPw
   5:     0x7f98c157e136 - rust_begin_unwind
   6:     0x7f98c15b0354 - panicking::panic_fmt::h205f328075c6fc3cneC
   7:     0x7f98beb20927 - result::Result<T, E>::unwrap::h8927847030657896045
                        at src/libcore/macros.rs:28
   8:     0x7f98beb205ab - constellation::Constellation<LTF, STF>::handle_create_webgl_paint_task_msg::h16292102507790458183
                        at /home/farodin/Git/servo/components/compositing/constellation.rs:948
   9:     0x7f98bea4c2d2 - constellation::Constellation<LTF, STF>::handle_request::h15274289277729788676
                        at /home/farodin/Git/servo/components/compositing/constellation.rs:508
  10:     0x7f98bea40ed8 - constellation::Constellation<LTF, STF>::run::h2305798151297767270
                        at /home/farodin/Git/servo/components/compositing/constellation.rs:280
  11:     0x7f98bea07c8f - constellation::Constellation<LTF, STF>::start::closure.7507
                        at /home/farodin/Git/servo/components/compositing/constellation.rs:272
  12:     0x7f98bea06c04 - task::spawn_named::closure.7500
                        at /home/farodin/Git/servo/components/util/task.rs:16
  13:     0x7f98bea06b34 - boxed::F.FnBox<A>::call_box::h12399738554317021473
                        at src/liballoc/boxed.rs:396
  14:     0x7f98bea065b0 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h11153329658984742844
                        at src/liballoc/boxed.rs:412
  15:     0x7f98bea06062 - thread::Builder::spawn_inner::closure.7472
                        at src/libstd/thread/mod.rs:349
  16:     0x7f98bea05fde - rt::unwind::try::try_fn::__rust_abi::h18275140666430221924
                        at src/libstd/rt/unwind/mod.rs:158
  17:     0x7f98bea05f79 - rt::unwind::try::try_fn::h18275140666430221924
  18:     0x7f98c15836f8 - rust_try_inner
  19:     0x7f98c15836e5 - rust_try
  20:     0x7f98c1578af7 - rt::unwind::try::inner_try::h63857c7efe7ef4ac9Lw
  21:     0x7f98bea05ed8 - rt::unwind::try::h11107500316499062534
                        at src/libstd/rt/unwind/mod.rs:130
  22:     0x7f98bea05d33 - thread::Builder::spawn_inner::closure.7422
                        at src/libstd/thread/mod.rs:349
  23:     0x7f98bea068bd - boxed::F.FnBox<A>::call_box::h15485162644176560569
                        at src/liballoc/boxed.rs:396
  24:     0x7f98c157d281 - sys::thread::Thread::new::thread_start::hb94dd6e8abd80527WVv
  25:     0x7f98be0056a9 - start_thread
  26:     0x7f98bd810eec - clone
  27:                0x0 - <unknown>
thread 'ScriptTask PipelineId(0)' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:731
stack backtrace:
   1:     0x7f98c157b05e - sys::backtrace::write::hfe027f56cae344aapps
   2:     0x7f98c157e745 - panicking::on_panic::hcd0100c6199f27b1Cax
   3:     0x7f98c156b89e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw
   4:     0x7f98c156c28c - rt::unwind::begin_unwind_fmt::h5a900a56c2bf32ccmPw
   5:     0x7f98c157e136 - rust_begin_unwind
   6:     0x7f98c15b0354 - panicking::panic_fmt::h205f328075c6fc3cneC
   7:     0x7f98bf98ad6d - result::Result<T, E>::unwrap::h9303859634396253954
                        at src/libcore/macros.rs:28
   8:     0x7f98bfd1afb5 - dom::webglrenderingcontext::WebGLRenderingContext::new_inherited::hdf3c246261f2737cxTV
                        at /home/farodin/Git/servo/components/script/dom/webglrenderingcontext.rs:73
   9:     0x7f98bfba9f0b - dom::webglrenderingcontext::WebGLRenderingContext::new::hddca7990f2e48c7eFUV
                        at /home/farodin/Git/servo/components/script/dom/webglrenderingcontext.rs:86
  10:     0x7f98bfba9bdf - dom::htmlcanvaselement::_&'a HTMLCanvasElement.HTMLCanvasElementHelpers::get_or_init_webgl_context::hdb3d83db431f2b12V8E
                        at /home/farodin/Git/servo/components/script/dom/htmlcanvaselement.rs:197
  11:     0x7f98bf73c944 - dom::htmlcanvaselement::_&'a HTMLCanvasElement.HTMLCanvasElementMethods::GetContext::hc5b845bf83bb19faydF
                        at /home/farodin/Git/servo/components/script/dom/htmlcanvaselement.rs:248
  12:     0x7f98bf73bdd5 - dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::getContext::__rust_abi
                        at /home/farodin/Git/servo/target/debug/build/script-a00fdee974ebd974/out/Bindings/HTMLCanvasElementBinding.rs:259
  13:     0x7f98bf73b9ad - dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::getContext::he14a6d6179b6ed393oX
  14:     0x7f98c15b9522 - CallJitMethodOp
  15:     0x7f98bf5ce357 - dom::bindings::utils::generic_call::ha9e78b934dd4fb852nc
                        at /home/farodin/Git/servo/components/script/dom/bindings/utils.rs:748
  16:     0x7f98bf5ce6f0 - dom::bindings::utils::generic_method::__rust_abi
                        at /home/farodin/Git/servo/components/script/dom/bindings/utils.rs:755
  17:     0x7f98bf5ce697 - dom::bindings::utils::generic_method::haa0d6f20cf57ae5akrc
  18:     0x7f98c02029c8 - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  19:     0x7f98c01fd709 - _ZL9InterpretP9JSContextRN2js8RunStateE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  20:     0x7f98c020266d - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  21:     0x7f98c02028fa - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  22:     0x7f98c0208f11 - _ZN2js17InvokeConstructorEP9JSContextN2JS8CallArgsE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:585
  23:     0x7f98c0209132 - _ZN2js17InvokeConstructorEP9JSContextN2JS5ValueEjPKS3_NS2_13MutableHandleIS3_EE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:611
  24:     0x7f98c03ae553 - _ZN2js3jitL14DoCallFallbackEP9JSContextPNS0_13BaselineFrameEPNS0_15ICCall_FallbackEjPN2JS5ValueENS7_13MutableHandleIS8_EE
                        at /home/farodin/Git/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jit/BaselineIC.cpp:9624
  25:     0x7f98b5c5562f - <unknown>
fatal runtime error: Could not unwind stack, error = 5
Servo exited with return value -4
```

**Comment by jdm** [comment]
@ecoal95 Any suggestions here?

**Comment by ecoal95** [comment]
With the introduction of e10s, the WebGL pain task result is unwrapped, I'll take care of it :P

**Comment by jdm** [comment]
@ecoal95 Well, that can be dealt with in #6806, but I'm curious about the reason the creation actually failed.

**Comment by ecoal95** [comment]
@jdm That error is returned when `glxChooseFbConfig` returns null. If no x11/glx errors appeared (they should be catched by glutin printing the error code), it just means that there's no framebuffer configuration able to render on a pixmap...

With more info from @farodin91 (output of `glxinfo` for example) we could debug it.

@farodin91 does any context creation on that page fails on firefox?

**Comment by farodin91** [comment]
https://pastebin.mozilla.org/8840824

**Comment by farodin91** [comment]
@ecoal95 How can i test this in Firefox? 
Nothing in the Web Console & Browser Console

**Comment by ecoal95** [comment]
@farodin91 Sorry, firefox doesn't log anything when it fails to create a context. The only thing that page does to test webgl support is effectively `document.createElement('canvas').getContext('webgl')`.

Paste that in the console, you should get `null` instead of `WebGLRenderingContext { ... }`

**Comment by farodin91** [comment]
In Firefox i get WebGLRenderingContext

**Comment by ecoal95** [comment]
I've been testing, and it happens to me too, but just in release mode. Even in the simplest webgl test we have:

```
$ ./mach run -d tests/ref/webgl-context/clearcolor.html
(Ok)
```

```
$ ./mach run -r tests/ref/webgl-context/clearcolor.html 
ERROR:script::dom::webglrenderingcontext: Couldn't create WebGLRenderingContext: glx::ChooseFBConfig
```

@farodin91 could you do the same? (you will get a crash instead of the error message but...)

@jdm do you know what could trigger this just in release mode?

**Comment by farodin91** [comment]
In debug it crashed. 
In release I don't know wait nearly 18 min for complete build, it isn't finished. I doesn't know why?

**Comment by ecoal95** [comment]
I checked out a version pre-e10s (a3821bf) and worked nicely in both release and debug mode...

**Comment by farodin91** [comment]
Both are crashing!

**Comment by jdm** [comment]
@pcwalton e10s regression!

**Comment by ecoal95** [comment]
Checked out e10s version (next commit, bb99b2f) and it crashes on release but works on debug mode.

@farodin91 Could you tell us if when you run `glxinfo -v` you see a FBConfig with pixmap type? It should look like this:

```
FBConfig ID: 99  Visual ID=aa  depth=24  class=DirectColor, type=window,pixmap,pbuffer
...
```

Maybe Firefox is using a different WebGL backend for him, and @farodin91's issue is just the lack of FBConfigs which allow rendering to a pixmap (though it will be weird).

**Comment by farodin91** [comment]
https://pastebin.mozilla.org/8840838

**Comment by jdm** [comment]
Pastebin is cutting off your output; can you use https://gist.github.com/gists instead?

**Comment by farodin91** [comment]
Okay

**Comment by farodin91** [comment]
https://gist.github.com/farodin91/0ad01b3b7e9c1607efef

**Comment by metajack** [comment]
This page also triggers this error:
https://schteppe.github.io/p2.js/demos/ragdoll.html

**Comment by jdm** [comment]
On https://schteppe.github.io/p2.js/demos/ragdoll.html I see the same error as https://github.com/servo/servo/issues/14680 now.

**Comment by sviter** [comment]
Can't see error on https://schteppe.github.io/p2.js/demos/ragdoll.html
