### ISSUE TITLE
Add bindings support for unrestricted float values

### ISSUE THREAD

**Issue by saneyuki** [servo/servo#707]
This error happen on parsing HTMLMediaElement.webidl.
HTMLMediaElement.webidl: http://mxr.mozilla.org/mozilla-central/source/dom/webidl/HTMLMediaElement.webidl

```
Traceback (most recent call last):
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/pythonpath.py", line 60, in <module>
    main(sys.argv[1:])
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/pythonpath.py", line 52, in main
    execfile(script, frozenglobals)
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/GlobalGen.py", line 88, in <module>
    main()
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/GlobalGen.py", line 66, in main
    parser.parse(''.join(lines), fullPath)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/parser/WebIDL.py", line 3885, in parse
    self._productions.extend(self.parser.parse(lexer=self.lexer,tracking=True))
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 263, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 792, in parseopt
    tok = self.errorfunc(errtoken)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/parser/WebIDL.py", line 3835, in p_error
    raise WebIDLError("invalid syntax", [Location(self.lexer, p.lineno, p.lexpos, self._filename)])
WebIDL.WebIDLError: error: invalid syntax, /Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/HTMLMediaElement.webidl line 55:34
  readonly attribute unrestricted double duration;
                                  ^
make: *** [/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/ParserResults.pkl] Error 1
```

**Comment by Ms2ger** [comment]
The IDL parser code is already imported; will just need the codegen changes. @saneyuki, want to have a go at this?
