### ISSUE TITLE
thread 'CanvasTask' panicked at 'assertion failed: libc::munmap(self.ptr as *mut c_void, self.length as size_t) == 0'

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7108]
```
$ ./mach test-wpt html/semantics/embedded-content/the-canvas-element/size.attributes.setAttribute.zero.html
 0:04.56 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "thread 'CanvasTask' panicked at 'assertion failed: libc::munmap(self.ptr as *mut c_void, self.length as size_t) == 0', ipc-channel/platform/linux/mod.rs:502"
 0:04.56 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "stack backtrace:"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   1:     0x7f753d897b9e - sys::backtrace::write::h4461ce907fdef7c9Cys"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   2:     0x7f753d89b780 - panicking::on_panic::hbb749401295aefc5Lnx"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   3:     0x7f753d88778e - rt::unwind::begin_unwind_inner::hb561d488e4095b19o3w"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   4:     0x7f753d73bcfc - rt::unwind::begin_unwind::h13474835002061264746"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/libstd/rt/unwind/mod.rs:225"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   5:     0x7f753d72b13d - platform::linux::UnixSharedMemory.Drop::drop::h555058c40ac60f2fFfb"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at /components/servo/<std macros>:3"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   6:     0x7f753c41c2b1 - ipc_channel..platform..linux..UnixSharedMemory::drop.8466::h4d777ad4a003b5e9"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   7:     0x7f753c4745aa - ipc_channel..ipc..IpcSharedMemory::drop.10359::h86719a34ced959a6"
 0:04.97 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   8:     0x7f753c474544 - ipc::IpcSender<T>::send::h15028877555337072042"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at ipc-channel/ipc.rs:140"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "   9:     0x7f753c474356 - canvas_paint_task::CanvasPaintTask<'a>::send_pixel_contents::closure.10349"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at /components/canvas/canvas_paint_task.rs:559"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  10:     0x7f753c4742c1 - azure_hl::DataSourceSurface::with_data::h13221260199712428498"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at rust-azure/src/azure_hl.rs:1007"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  11:     0x7f753c46fa6d - canvas_paint_task::CanvasPaintTask<'a>::send_pixel_contents::h2fdbbefe022d64437Ma"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at /components/canvas/canvas_paint_task.rs:558"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  12:     0x7f753c466c59 - canvas_paint_task::CanvasPaintTask<'a>::start::closure.10066"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at /components/canvas/canvas_paint_task.rs:241"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  13:     0x7f753c465639 - task::spawn_named::closure.10058"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at /components/util/task.rs:16"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  14:     0x7f753c465591 - boxed::F.FnBox<A>::call_box::h16292996187402755506"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/liballoc/boxed.rs:514"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  15:     0x7f753c4650d0 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h1345628719500430854"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/liballoc/boxed.rs:530"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  16:     0x7f753c464b82 - thread::Builder::spawn_inner::closure.10028"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/libstd/thread/mod.rs:322"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  17:     0x7f753c464afe - rt::unwind::try::try_fn::h7692098356484805451"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/libstd/rt/unwind/mod.rs:157"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  18:     0x7f753d89ae8f - __rust_try_inner"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  19:     0x7f753d89aeca - __rust_try"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  20:     0x7f753d895737 - rt::unwind::try::inner_try::h2721e05d3675a507hZw"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  21:     0x7f753c464a48 - rt::unwind::try::h12589766041056825139"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/libstd/rt/unwind/mod.rs:129"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  22:     0x7f753c4648ae - thread::Builder::spawn_inner::closure.9981"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/libstd/thread/mod.rs:322"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  23:     0x7f753c4653dd - boxed::F.FnBox<A>::call_box::h9371740016873426761"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "                        at src/liballoc/boxed.rs:514"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  24:     0x7f753d89a041 - sys::thread::Thread::new::thread_start::h3e0fc9f59f3e6025X8v"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  25:     0x7f753988b181 - start_thread"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  26:     0x7f753a3ee47c - __clone"
 0:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:22309) "  27:                0x0 - <unknown>"
```

**Comment by Ms2ger** [comment]
cc @pcwalton

**Comment by dralley** [comment]
This particular issue cannot be reproduced any longer
