### ISSUE TITLE
Python KeyError on WPT XHR auth tests

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7113]
# Command

`./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/send-authentication-basic-repeat-no-args.htm`

# Result

```
0:04.19 SUITE_START: MainThread 1
 0:04.19 LOG: MainThread INFO Running testharness tests
 0:04.28 LOG: Thread-Log INFO STDOUT: /XMLHttpRequest/send-authentication-basic-repeat-no-args.htm
 0:04.83 LOG: Thread-7 wptserve WARNING Traceback (most recent call last):
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 234, in __call__
    rv = self.func(request, response)
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/XMLHttpRequest/resources/auth1/auth.py", line 10, in main
    return auth.main(request, response)
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/XMLHttpRequest/resources/auth1/../authentication.py", line 13, in main
    if token is not None and request.server.stash.take(token) is not None:
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/request.py", line 37, in stash
    address, authkey = stash.load_env_config()
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/stash.py", line 38, in load_env_config
    address, authkey = json.loads(os.environ["WPT_STASH_CONFIG"])
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'WPT_STASH_CONFIG'

 0:04.86 LOG: Thread-8 wptserve WARNING Traceback (most recent call last):
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 234, in __call__
    rv = self.func(request, response)
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/XMLHttpRequest/resources/auth1/auth.py", line 10, in main
    return auth.main(request, response)
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/XMLHttpRequest/resources/auth1/../authentication.py", line 13, in main
    if token is not None and request.server.stash.take(token) is not None:
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/request.py", line 37, in stash
    address, authkey = stash.load_env_config()
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/stash.py", line 38, in load_env_config
    address, authkey = json.loads(os.environ["WPT_STASH_CONFIG"])
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'WPT_STASH_CONFIG'
```

**Comment by Ms2ger** [comment]
CC @jgraham

**Comment by frewsxcv** [comment]
I no longer see this error for the command I pasted above.
