### ISSUE TITLE
Intermittent timeout in WPT reftests (`Result::unwrap()` on an `Err` value in http_loader)

### ISSUE THREAD

**Issue by jdm** [servo/servo#7437]
```
1:02.98 TEST_START: Thread-TestrunnerManager-35 /css21_dev/html4/background-color-075.htm
 1:03.19 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) Full command: /home/servo/buildbot/slave/linux2/build/target/release/servo --cpu --hard-fail --exit -u Servo/wptrunner -Z disable-text-aa --output=/tmp/tmpRp06Iu/a6fe72d9-a29b-40e3-88c5-e4dac2995b9f http://localhost:8000/css21_dev/html4/background-color-075.htm --user-stylesheet /home/servo/buildbot/slave/linux2/build/resources/ahem.css
(pid:27586) "thread 'http_loader' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:732"
 1:03.19 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "stack backtrace:"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   1:     0x7f645f4335c9 - sys::backtrace::write::h29675241e432c301Pws"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   2:     0x7f645f436eb9 - panicking::on_panic::h1e1c334783ff2a38jzx"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   3:     0x7f645f4247fe - rt::unwind::begin_unwind_inner::hb529041d76c2c802L1w"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   4:     0x7f645f425111 - rt::unwind::begin_unwind_fmt::h027d2621615b5dcfR0w"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   5:     0x7f645f4368b1 - rust_begin_unwind"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   6:     0x7f645f466a7f - panicking::panic_fmt::ha8483564b9ba8c9c47D"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   7:     0x7f645e8425c9 - http_loader::load::h19ac6a5bc624e6cfdpa"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   8:     0x7f645e83d504 - boxed::F.FnBox<A>::call_box::h11481485006043150976"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   9:     0x7f645e837244 - rt::unwind::try::try_fn::h12677946051234551213"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  10:     0x7f645f436858 - __rust_try"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  11:     0x7f645f4314c2 - rt::unwind::try::inner_try::hbf179233f048e0c1EXw"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  12:     0x7f645e8373de - boxed::F.FnBox<A>::call_box::h3081112056388942627"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  13:     0x7f645f435c43 - sys::thread::Thread::new::thread_start::hb07a6549e7b84f0f46v"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  14:     0x7f645cdca181 - start_thread"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  15:     0x7f645d8ff47c - __clone"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  16:                0x0 - <unknown>"
```

This is caused by an IPC channel creation failure in the HTTP loader. Also reported https://github.com/pcwalton/ipc-channel/issues/6 .

**Comment by jdm** [comment]
```
  ▶ CRASH [expected PASS] /css21_dev/html4/margin-right-applies-to-015.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', src/libcore/result.rs:736
  │ stack backtrace:
  │    1:        0x10749ddb8 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
  │    2:        0x10749ff9f - panicking::log_panic::_<closure>::closure.38923
  │    3:        0x10749fa49 - panicking::log_panic::h87af6096e0b6fa7c4Uw
  │    4:        0x10748b766 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
  │    5:        0x10748bb4e - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r
  │    6:        0x10749d447 - rust_begin_unwind
  │    7:        0x1074c38e0 - panicking::panic_fmt::h54ca80e608a83d7dwZK
  │    8:        0x106bd8bbf - mem::_<impl>::send::h19122b4e0957bf80Bea
  │    9:        0x106643d23 - boxed::_<impl>::call_box::call_box::h14542610734019300004
  │   10:        0x106206cf2 - sys_common::unwind::try::try_fn::try_fn::h12226746912188056795
  │   11:        0x10749d288 - __rust_try
  │   12:        0x10749a72e - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r
  │   13:        0x106206e97 - boxed::_<impl>::call_box::call_box::h8010242368454586177
  │   14:        0x10749f36d - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw
  │   15:     0x7fff8416a059 - _pthread_body
  │   16:     0x7fff84169fd6 - _pthread_start
```

**Comment by jdm** [comment]
Specifically, "recursive IPC channel use during serialization". Interesting.

**Comment by jdm** [comment]
#8961
