### ISSUE TITLE
src/libcore/slice.rs: assertion failed: dst.len() >= len_src

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7574]
Sadly, I do not have any STR. But this crash keeps happening. Anything I can do to help understand what's going on?

```
thread 'PaintWorker' panicked at 'assertion failed: dst.len() >= len_src', src/libcore/slice.rs:1507
stack backtrace:
   1:        0x10c6afdf0 - sys::backtrace::tracing::imp::write::hd0176e40ebe71d28Vks
   2:        0x10c6b2ff9 - panicking::on_panic::h929e7e75bc4f2c31NXw
   3:        0x10c6a2192 - rt::unwind::begin_unwind_inner::h9d2d49cde66c0c4b0sw
   4:        0x10c6a283d - rt::unwind::begin_unwind_fmt::h30d162ea92169f156rw
   5:        0x10c6b2a57 - rust_begin_unwind
thread 'PaintWorker' panicked at 'assertion failed: dst.len() >= len_src', src/libcore/slice.rs:1507
thread 'PaintWorker' panicked at 'assertion failed: dst.len() >= len_src', src/libcore/slice.rs:1507
   6:        0x10c6d7ba0 - panicking::panic_fmt::ha85fd08dcab4df5d8PE
   7:        0x10c6d3ccc - panicking::panic::h51e678ec5afc872cFOE
   8:        0x10c66b909 - IOSurface::upload::h49f8cfc13f8896f7ifa
   9:        0x10be8c839 - platform::surface::NativeSurface::upload::h1994a27581742600Ygc
  10:        0x10b6fde30 - paint_task::WorkerThread::main::h3fa1cd1eeb7118dfZ8i
  11:        0x10b6fca78 - boxed::F.FnBox<A>::call_box::h9007657883254816557
  12:        0x10b6fc0d2 - rt::unwind::try::try_fn::h5216464315939067335
  13:        0x10c6b2a08 - __rust_try
  14:        0x10c6ae710 - rt::unwind::try::inner_try::h03cd26bf8e2ee1ceTow
  15:        0x10b6fc277 - boxed::F.FnBox<A>::call_box::h4038924545937116678
  16:        0x10c6b1dbd - sys::thread::Thread::new::thread_start::he62641fb2961f41aBNv
  17:     0x7fff8b2189b0 - _pthread_body
  18:     0x7fff8b21892d - _pthread_start
stack backtrace:
Servo exited with return value -5
```

**Comment by frewsxcv** [comment]
This is probably a duplicate of https://github.com/servo/servo/issues/6952

**Comment by paulrouget** [comment]
Most likely.
