### ISSUE TITLE
error on running ./mach test-dromaeo  (ubuntu 14.04 32-bit)

### ISSUE THREAD

**Issue by jdramani** [servo/servo#7704]
./mach test-dromaeo command gives the following error..

Already up-to-date.
make: Entering directory `/home/jaydeep/servo/tests/dromaeo/dromaeo'
make: `web' is up to date.
make: Leaving directory `/home/jaydeep/servo/tests/dromaeo/dromaeo'
Traceback (most recent call last):
  File "/home/jaydeep/servo/tests/dromaeo/run_dromaeo.py", line 60, in <module>
    server = BaseHTTPServer.HTTPServer(('', TEST_SERVER_PORT), RequestHandler)
  File "/home/jaydeep/anaconda/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/home/jaydeep/anaconda/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/home/jaydeep/anaconda/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/home/jaydeep/anaconda/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Error running mach:

    ['test-dromaeo']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'/home/jaydeep/servo/tests/dromaeo/run_dromaeo.py', u'recommended', '/home/jaydeep/servo/target/release/servo', u'/home/jaydeep/servo/tests/dromaeo']' returned non-zero exit status 1

  File "/home/jaydeep/servo/python/servo/testing_commands.py", line 286, in test_dromaeo
    return self.dromaeo_test_runner(tests, release, dev)
  File "/home/jaydeep/servo/python/servo/testing_commands.py", line 367, in dromaeo_test_runner
    [run_file, "|".join(tests), bin_path, base_dir])
  File "/home/jaydeep/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by jdm** [comment]
Looks like you already have a web server running on port 80?

**Comment by jdm** [comment]
Sorry, port 8192 according to http://mxr.mozilla.org/servo/source/tests/dromaeo/run_dromaeo.py#17 .

**Comment by jdramani** [comment]
I found out which pid is using this port by:
fuser 8192/tcp
I got pid: 7713
Then I checked which process is this by:
ls -l /proc/7713/exe
output: lrwxrwxrwx 1 jaydeep jaydeep 0 Sep 21 23:08 /proc/7713/exe -> /home/jaydeep/servo/python/_virtualenv/bin/python2

I do not understand this. I tried to kill this process by sudo kill 7713 but nothing happens.
Do you know anything about this?

**Comment by jdm** [comment]
I don't, sorry :/ Maybe `sudo kill -9 7713` will work?
