### ISSUE TITLE
Panic under IOSurface::upload

### ISSUE THREAD

**Issue by jdm** [servo/servo#7820]
To reproduce on OS X, I just keep clicking the ">" link in http://emoon.github.io/prodbg-web/rust_pres/index.html over and over, and eventually get this:

```
thread 'PaintWorker' panicked at 'assertion failed: dst.len() >= len_src', src/libcore/slice.rs:1509
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #7: tid = 0x101b43, 0x00000001029cd8e0 servo`rust_panic, name = 'PaintWorker', stop reason = breakpoint 1.1
  * frame #0: 0x00000001029cd8e0 servo`rust_panic
    frame #1: 0x00000001029bea98 servo`sys_common::unwind::begin_unwind_inner::h879cfd5a30161a9evas + 424
    frame #2: 0x00000001029bef0f servo`sys_common::unwind::begin_unwind_fmt::h86e9e878cb969fb5B9r + 207
    frame #3: 0x00000001029cda98 servo`rust_begin_unwind + 56
    frame #4: 0x00000001029f3aa1 servo`panicking::panic_fmt::h74e66b6fcc9eaf3cwZK + 129
    frame #5: 0x00000001029ef62d servo`panicking::panic::he6e1bfb72056e4793XK + 109
    frame #6: 0x0000000102974b0e servo`io_surface::slice::bytes::copy_memory(src=(data_ptr = "", length = 696320), dst=(data_ptr = unsigned char * = 0x0000000000000000, length = 0)) + 94 at macros.rs:20
    frame #7: 0x0000000102974a20 servo`io_surface::IOSurface::upload(self=0x00000001239ffeb8, data=(data_ptr = "", length = 696320)) + 304 at lib.rs:156
    frame #8: 0x00000001019fb413 servo`layers::platform::macos::surface::IOSurfaceNativeSurface::upload(self=0x0000000108c50464, data=(data_ptr = "", length = 696320)) + 83 at surface.rs:113
    frame #9: 0x00000001019fcf84 servo`layers::platform::surface::NativeSurface::upload(self=0x0000000108c50460, display=0x0000000123a00a10, data=(data_ptr = "", length = 696320)) + 100 at surface.rs:85
    frame #10: 0x000000010154df27 servo`fnfn(data=(data_ptr = "", length = 696320)) + 167 at paint_task.rs:651
    frame #11: 0x000000010154de28 servo`gfx::azure_hl::DataSourceSurface::with_data<closure>(self=0x0000000123a00290, f=closure at 0x0000000123a000e8) + 168 at azure_hl.rs:1007
    frame #12: 0x0000000101549a45 servo`gfx::paint_task::WorkerThread::optimize_and_paint_tile(self=0x0000000123a009d8, thread_id=5, tile=BufferRequest at 0x0000000123a00660, paint_layer=Arc<gfx::paint_task::PaintLayer> at 0x0000000123a00658, scale=2, layer_kind=NoTransform) + 2645 at paint_task.rs:650
    frame #13: 0x000000010153bcd8 servo`gfx::paint_task::WorkerThread::main(self=0x0000000123a009d8) + 392 at paint_task.rs:544
    frame #14: 0x000000010153b783 servo`fnfn + 323 at paint_task.rs:461
    frame #15: 0x000000010153b5b7 servo`fnfn + 119 at task.rs:16
    frame #16: 0x000000010153b4f6 servo`gfx::boxed::F.FnBox<A>::call_box(self=0x00000001198271e0, args=<unavailable>) + 118 at boxed.rs:485
    frame #17: 0x000000010150d87c servo`gfx::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once(self=Box<FnBox<()>> at 0x0000000123a00bc0, args=<unavailable>) + 60 at boxed.rs:501
    frame #18: 0x000000010150d45e servo`fnfn + 78 at mod.rs:280
    frame #19: 0x000000010150d40a servo`gfx::sys_common::unwind::try::try_fn<closure>(opt_closure=0x0000000123a00cf0) + 58 at mod.rs:164
    frame #20: 0x00000001029cd8d9 servo`__rust_try + 9
    frame #21: 0x00000001029caca1 servo`sys_common::unwind::try::inner_try::h30a7e5c7446717a0T6r + 97
    frame #22: 0x000000010150d374 servo`gfx::sys_common::unwind::try<closure>(f=closure at 0x0000000123a00d08) + 100 at mod.rs:136
    frame #23: 0x000000010150d1ec servo`fnfn + 412 at mod.rs:280
    frame #24: 0x000000010150da9d servo`gfx::boxed::F.FnBox<A>::call_box(self=0x00000001198230a0, args=<unavailable>) + 77 at boxed.rs:485
    frame #25: 0x00000001029cfd7e servo`sys::thread::Thread::new::thread_start::h6e92c6728040a269Mxw + 142
    frame #26: 0x00007fff94079899 libsystem_pthread.dylib`_pthread_body + 138
    frame #27: 0x00007fff9407972a libsystem_pthread.dylib`_pthread_start + 137
    frame #28: 0x00007fff9407dfc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by jdm** [comment]
```
frame #7: 0x0000000102974a20 servo`io_surface::IOSurface::upload(self=0x00000001239ffeb8, data=(data_ptr = "", length = 696320)) + 304 at lib.rs:156
   153 	            let size = (height * stride) as usize;
   154 	            let address = IOSurfaceGetBaseAddress(surface) as *mut u8;
   155 	            let dest: &mut [u8] = slice::from_raw_parts_mut(address, size);
-> 156 	            copy_memory(data, dest);
   157
   158 	            // FIXME(pcwalton): RAII
   159 	            IOSurfaceUnlock(surface, 0, &mut seed);
(lldb) p address
(unsigned char *) $0 = 0x0000000000000000
(l
```

**Comment by jdm** [comment]
```
(lldb) up
frame #8: 0x00000001019fb413 servo`layers::platform::macos::surface::IOSurfaceNativeSurface::upload(self=0x0000000108c50464, data=(data_ptr = "", length = 696320)) + 83 at surface.rs:113
   110
   111 	    pub fn upload(&mut self, _: &NativeDisplay, data: &[u8]) {
   112 	        let io_surface = io_surface::lookup(self.io_surface_id.unwrap());
-> 113 	        io_surface.upload(data)
   114 	    }
   115
   116 	    pub fn get_id(&self) -> isize {
(lldb) p data
(&[u8]) $4 = (data_ptr = "", length = 696320)
(lldb) p *self
(layers::platform::macos::surface::IOSurfaceNativeSurface) $5 = {
  io_surface_id = {
     = (RUST$ENUM$DISR = Some)
     = (RUST$ENUM$DISR = Some, __0 = 0)
  }
  will_leak = false
  size = (width = 340, height = 512)
}
```

**Comment by jdm** [comment]
This is probably a duplicate of #6952 but I have an actual testcase that doesn't take long to reproduce.

**Comment by nox** [comment]
I can't reproduce this anymore.
