### ISSUE TITLE
Consistent non-success process termination for webgl-context reftests

### ISSUE THREAD

**Issue by jdm** [servo/servo#7931]
```

failures:
    webgl-context/clearcolor.html == webgl-context/clearcolor_ref.html
    webgl-context/draw_arrays_simple.html == webgl-context/draw_arrays_simple_ref.html
    webgl-context/tex_image_2d_canvas.html == webgl-context/tex_image_2d_canvas_ref.html
    webgl-context/tex_image_2d_canvas2d.html == webgl-context/tex_image_2d_canvas_ref.html
    webgl-context/tex_image_2d_canvas_no_context.html == webgl-context/tex_image_2d_canvas_no_context_ref.html
    webgl-context/tex_image_2d_simple.html == webgl-context/tex_image_2d_simple_ref.html
```

Sample:

```
---- webgl-context/tex_image_2d_simple.html == webgl-context/tex_image_2d_simple_ref.html stdout ----
    thread 'webgl-context/tex_image_2d_simple.html == webgl-context/tex_image_2d_simple_ref.html' panicked at 'assertion failed: exit_status.success()', ../../tests/reftest.rs:335
stack backtrace:
   1:     0x7ffb1f767270 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x7ffb1f769f55 - panicking::log_panic::_<closure>::closure.39180
   3:     0x7ffb1f7699c5 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x7ffb1f74d693 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x7ffb1f6beab7 - sys_common::unwind::begin_unwind::begin_unwind::h6074138493330590073
                        at src/libstd/sys/common/unwind/mod.rs:214
   6:     0x7ffb1f6dad8b - capture::hff9977986cfb9b32YNa
                        at /home/servo/buildbot/slave/linux-dev/build/components/servo/<std macros>:3
   7:     0x7ffb1f6d8bb8 - check_reftest::hf0aac9bc09fd257ekXa
                        at ../../tests/reftest.rs:351
   8:     0x7ffb1f6d8ac7 - make_test::_<closure>::closure.15753
                        at ../../tests/reftest.rs:278
   9:     0x7ffb1f6d9a17 - boxed::_<impl>::call_box::call_box::h5794098128060069563
                        at src/liballoc/boxed.rs:516
  10:     0x7ffb1f739eb8 - boxed::_<impl>::call_box::call_box::h17282746878263628964
  11:     0x7ffb1f738224 - sys_common::unwind::try::try_fn::try_fn::h14061410362995320864
  12:     0x7ffb1f7667a8 - __rust_try
  13:     0x7ffb1f75ddcb - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  14:     0x7ffb1f7383be - boxed::_<impl>::call_box::call_box::h7646584381128873602
  15:     0x7ffb1f768a43 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  16:     0x7ffb1e579181 - start_thread
  17:     0x7ffb1ed9347c - __clone
  18:                0x0 - <unknown>
```

**Comment by jdm** [comment]
This is blocking landing any PR right now.

**Comment by Ms2ger** [comment]
```
#0  0x00007ffff6f23f80 in XDefaultScreen () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x0000555557201270 in offscreen_gl_context::platform::with_glx::utils::create_offscreen_pixmap_backed_context (size=...)
    at /home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/platform/with_glx/utils.rs:67
#2  0x0000555557202a42 in offscreen_gl_context::platform::with_glx::native_gl_context::NativeGLContext.NativeGLContextMethods::create_headless ()
    at /home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/platform/with_glx/native_gl_context.rs:83
#3  0x0000555557202bd4 in offscreen_gl_context::gl_context::GLContext::create_headless () at /home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/gl_context.rs:38
#4  0x0000555557203825 in offscreen_gl_context::gl_context::GLContext::create_offscreen_with_color_attachment (size=..., attributes=..., color_attachment_type=TextureWithSurface)
    at /home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/gl_context.rs:62
#5  0x0000555556dafe65 in canvas::webgl_paint_task::WebGLPaintTask::new (size=..., attrs=...) at /home/servo/buildbot/slave/linux-dev/build/components/canvas/webgl_paint_task.rs:34
#6  0x0000555556db4de6 in canvas::webgl_paint_task::WebGLPaintTask::start (size=..., attrs=...) at /home/servo/buildbot/slave/linux-dev/build/components/canvas/webgl_paint_task.rs:181
#7  0x0000555555ae3f55 in servo::constellation::Constellation<LTF, STF>::handle_create_webgl_paint_task_msg (self=0x7fffe93fe290, size=0x7fffe93fd778, attributes=..., response_sender=...)
    at /home/servo/buildbot/slave/linux-dev/build/components/compositing/constellation.rs:997
#8  0x00005555559e5db0 in servo::constellation::Constellation<LTF, STF>::handle_request (self=0x7fffe93fe290, request=...)
    at /home/servo/buildbot/slave/linux-dev/build/components/compositing/constellation.rs:538
#9  0x00005555559daafc in servo::constellation::Constellation<LTF, STF>::run (self=0x7fffe93fe290) at /home/servo/buildbot/slave/linux-dev/build/components/compositing/constellation.rs:299
#10 0x00005555559ae8ea in fnfn () at /home/servo/buildbot/slave/linux-dev/build/components/compositing/constellation.rs:291
#11 0x00005555559ad690 in fnfn () at /home/servo/buildbot/slave/linux-dev/build/components/util/task.rs:16
#12 0x00005555559ad5e8 in servo::boxed::F.FnBox<A>::call_box (self=0x7ffff2456000, args=0) at src/liballoc/boxed.rs:516
#13 0x00005555559ad20c in servo::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once (self=..., args=0) at src/liballoc/boxed.rs:532
#14 0x00005555559acdfe in fnfn () at src/libstd/thread/mod.rs:280
#15 0x00005555559acdaa in servo::sys_common::unwind::try::try_fn<closure> (opt_closure=0x7fffe93fe870 "") at src/libstd/sys/common/unwind/mod.rs:146
#16 0x0000555557da2529 in __rust_try ()
#17 0x0000555557d9ed2c in sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r ()
#18 0x00005555559acd14 in servo::sys_common::unwind::try<closure> (f=...) at src/libstd/sys/common/unwind/mod.rs:116
#19 0x00005555559acba9 in fnfn () at src/libstd/thread/mod.rs:280
#20 0x00005555559ad41d in servo::boxed::F.FnBox<A>::call_box (self=0x7fffeb6ae8a0, args=0) at src/liballoc/boxed.rs:516
#21 0x0000555557da4154 in sys::thread::_$LT$impl$GT$::new::thread_start::h89508aa1f401717d8Dw ()
#22 0x00007ffff59a8182 in start_thread (arg=0x7fffe93ff700) at pthread_create.c:312
#23 0x00007ffff61c247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by jdm** [comment]
Not fixed by #8291, unfortunately.

**Comment by glennw** [comment]
@jdm @ecoal95 The webgl reftests might be fixed by https://github.com/ecoal95/rust-offscreen-rendering-context/pull/43.

**Comment by jdm** [comment]
Not fixed by ecoal95/rust-offscreen-rendering-context#43, unfortunately (see #8743).

**Comment by jdm** [comment]
Haven't seen this for a long time.
