### ISSUE TITLE
ipc-channel panic on Linux with zero-length data

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#8082]
Running the Dromaeo DOM Core tests:

    $ ./target/release/servo tests/dromaeo/dromaeo/web/index.html 
    [dromaeo] getAttribute
    ...
    [dromaeo] cloneNode
    thread 'ImageCacheThread' panicked at 'assertion failed: libc::close(self.fd) == 0', /home/ajeffrey /tmp/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:101
    thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/libcollections/vec.rs:1044
    thread 'ImageCacheThread' panicked at 'assertion failed: libc::close(self.fd) == 0', /home/ajeffrey/tmp/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:101
    stack backtrace:
    thread '<unnamed>' panicked at 'assertion failed: libc::close(pollfd.fd) >= 0', /home/ajeffrey/tmp/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:300
    thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
       1:     0x7ff7133be070 - sys::fatal runtime error: backtrace::tracing::imp::Could not unwind stack, error = write::h23bfa7a49ed99d87Klt5
       2:     0x7ff7133c05c5 - panicking::log_panic::_<closureIllegal instruction (core dumped)

Looks similar to https://github.com/servo/servo/pull/7802 but for Linux rather than MacOS.

**Comment by jdm** [comment]
cc @pcwalton

**Comment by nox** [comment]
Is this still true?

**Comment by lumiscosity** [comment]
Running the Dromaeo suite with `./mach test-dromaeo dom`, as well as the web suite on a slightly older commit a few weeks ago, I can't get this to happen anymore. Tested on Arch Linux x86_64, Servo built against commit f31edc5d6a0001fc1362d9e6f28156ff0b59e276, dev build.

**Comment by jdm** [comment]
Pretty sure this was fixed by https://github.com/servo/ipc-channel/pull/335.
