### ISSUE TITLE
Compositor panics when moving mouse while closing window

### ISSUE THREAD

**Issue by jdm** [servo/servo#8102]
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:     0x7fe68fa2bde0 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x7fe68fa2e335 - panicking::log_panic::_<closure>::closure.39180
   3:     0x7fe68fa2dd81 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x7fe68fa1ae23 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x7fe68fa1b4d8 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x7fe68fa2b4b1 - rust_begin_unwind
   7:     0x7fe68fa5bcef - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:     0x7fe68d210d3e - result::_<impl>::unwrap::unwrap::h15278686958470034438
                        at src/libcore/macros.rs:28
   9:     0x7fe68d2729bc - compositor_layer::_<impl>::send_mouse_move_event::send_mouse_move_event::h16016352989847185492
                        at /home/jdm/servo/components/compositing/compositor_layer.rs:389
  10:     0x7fe68d272858 - compositor::_<impl>::on_mouse_window_move_event_class::on_mouse_window_move_event_class::h13068851754856276957
                        at /home/jdm/servo/components/compositing/compositor.rs:1095
  11:     0x7fe68d26e886 - compositor::_<impl>::handle_window_message::handle_window_message::h15554983989746496171
                        at /home/jdm/servo/components/compositing/compositor.rs:1011
  12:     0x7fe68d1efad6 - compositor::_<impl>::handle_events::handle_events::h15246432749300380735
                        at /home/jdm/servo/components/compositing/compositor.rs:1862
  13:     0x7fe68d32f318 - _<impl>::handle_events::h4ca31518299d59eeLda
                        at /home/jdm/servo/components/servo/lib.rs:175
  14:     0x7fe68d19e9a8 - main::h8fd21a89dceb8751naa
                        at /home/jdm/servo/components/servo/main.rs:70
  15:     0x7fe68fa2dac4 - sys_common::unwind::try::try_fn::h10604132475359592391
  16:     0x7fe68fa2b318 - __rust_try
  17:     0x7fe68fa2d75f - rt::lang_start::hd74bfb7a606308914ix
  18:     0x7fe68d2747e9 - main
  19:     0x7fe68af0eec4 - __libc_start_main
  20:     0x7fe68d19e418 - <unknown>
  21:                0x0 - <unknown>
```

**Comment by jdm** [comment]
`send_mouse_move_event` calls `unwrap` on the result of the `send` call. This is silly, because the script thread that is being sent to could die at any time (as we see), so we should just drop the error silently instead with `let _ = pipeline.script_chan.send(...);`

Code: components/compositing/compositor_layer.rs

**Comment by nxnfufunezn** [comment]
Working on this..
