### ISSUE TITLE
glutin can only start from DISPLAY=:0.0

### ISSUE THREAD

**Issue by farseerfc** [servo/servo#8146]
Hi, I have a multiple display screen setup, which means I have one X instance running on 4 monitors, each have a seperate X screen (not combined by xrandr/xinerama).

If I run the current master branch build (ea000471d345c50791fb524b4ea66ca8f0594b3c) on 3 of my slave monitors (DISPLAY=:0.1 to :0.3), servo will failed with these error:
```
./mach run --release "http://farseerfc.me/"
[glutin] x error code=46 major=0 minor=0!
[glutin] x error code=47 major=0 minor=0!
[glutin] x error code=48 major=0 minor=0!
[glutin] x error code=49 major=0 minor=0!
[glutin] x error code=52 major=0 minor=0!
[glutin] x error code=53 major=0 minor=0!
[glutin] x error code=54 major=0 minor=0!
[glutin] x error code=56 major=0 minor=0!
[glutin] x error code=59 major=0 minor=0!
[glutin] x error code=62 major=0 minor=0!
[glutin] x error code=64 major=0 minor=0!
[glutin] x error code=65 major=0 minor=0!
[glutin] x error code=66 major=0 minor=0!
[glutin] x error code=73 major=0 minor=0!
Servo exited with return value -11
```

If I run servo on my primary screen (whose DISPLAY=:0.0), servo will run without problems.

I found this issue https://github.com/servo/servo/issues/6042 may be related, but it should have been fixed.

**Comment by jdm** [comment]
@glennw any recommendation here?

**Comment by jdm** [comment]
@zmike may also have ideas.

**Comment by glennw** [comment]
Could you paste the output of glxinfo from the first display (that works) and one of the displays that doesn't work?

**Comment by farseerfc** [comment]
Sure, this is the output of glxinfo from my primary screen (too long so I uploaded to dropbox):
https://www.dropbox.com/s/n78mmti21sekg09/0.0.txt?dl=0

And this is from my second screen:
https://www.dropbox.com/s/e3xiy2mnigjzgc1/0.1.txt?dl=0

**Comment by glennw** [comment]
There's nothing obviously wrong to me there. The next step is probably to run under gdb, place a breakpoint at https://github.com/servo/glutin/blob/servo/src/api/x11/xdisplay.rs#L37 and paste the backtrace of the first few errors that occur.

**Comment by farseerfc** [comment]
Sorry, using gdb to debug rust code is (currently) beyond my ability.

I did a git bisect on glutin and test with `cargo run --example window`, here is my git bisect log:

```
git bisect start
# bad: [dcd5c49b7f479c10004c54623c73cdb4434498a8] Merge pull request #629 from tomaka/fix-win-vsync
git bisect bad dcd5c49b7f479c10004c54623c73cdb4434498a8
# bad: [fa48f4b8457ce4e04fb089780d6a5cccb0e5ec11] Publish 0.3.6
git bisect bad fa48f4b8457ce4e04fb089780d6a5cccb0e5ec11
# good: [bfa7e091d031e9ffb0c030f0ec484759acb881de] Publish 0.1.3
git bisect good bfa7e091d031e9ffb0c030f0ec484759acb881de
# good: [4eacfce59e99e4d841255a053ce6acdc77b0c91c] Split creating an EGL context in two parts
git bisect good 4eacfce59e99e4d841255a053ce6acdc77b0c91c
# good: [be0440666b948faa92f6e3a81a2a384490ed9d10] Merge pull request #553 from tomaka/egl-default
git bisect good be0440666b948faa92f6e3a81a2a384490ed9d10
# bad: [73e4a7d4b17bfc08acc198e0336a2f5c7fd2036a] Merge pull request #576 from retep998/master
git bisect bad 73e4a7d4b17bfc08acc198e0336a2f5c7fd2036a
# skip: [5c60456e16b118f2d2cbbe5344fa887cbeb59cc8] Merge pull request #567 from paulrouget/opengl-profile-selection-fix
git bisect skip 5c60456e16b118f2d2cbbe5344fa887cbeb59cc8
# good: [dff7612e4547aa3ef0acdb83b0cb05e5e865800e] Merge pull request #561 from braden/master
git bisect good dff7612e4547aa3ef0acdb83b0cb05e5e865800e
# bad: [6c73209746331f1fe3bac402b58c1702798f7e62] Prefer GLX over EGL
git bisect bad 6c73209746331f1fe3bac402b58c1702798f7e62
# skip: [90e62083d686ed9c878beb348e9b54853242eab0] Merge pull request #566 from tomaka/display-egl
git bisect skip 90e62083d686ed9c878beb348e9b54853242eab0
# skip: [e90f377b9fbab23a140029e71ef57933b266c473] Merge pull request #565 from tomaka/correct-example
git bisect skip e90f377b9fbab23a140029e71ef57933b266c473
# skip: [691bac6528b09c04bed5abaf9e988eb9105ca86b] Merge pull request #568 from paulrouget/x11-crasher
git bisect skip 691bac6528b09c04bed5abaf9e988eb9105ca86b
# skip: [26139f8c5c66e6fdf1508cd5e07018bbf9b62a76] Fix OpenGL profile selection
git bisect skip 26139f8c5c66e6fdf1508cd5e07018bbf9b62a76
# good: [bee3e0e0f0ed4b642afaa6d82389839e87c840f0] Get the list of extensions only once
git bisect good bee3e0e0f0ed4b642afaa6d82389839e87c840f0
# skip: [86408438fcaeb901684c82662608e84c381b11bd] Fix a rare crash in some X11 implementations (details below).
git bisect skip 86408438fcaeb901684c82662608e84c381b11bd
# skip: [587dedaa9e95236f891d9a0e4ec04ee3700236a8] Correctly handle eglGetDisplay
git bisect skip 587dedaa9e95236f891d9a0e4ec04ee3700236a8
# good: [9261408cc8d2ba54ddea0c9ddd43560e03d45bdc] Use modern GL code for the examples
git bisect good 9261408cc8d2ba54ddea0c9ddd43560e03d45bdc
# only skipped commits left to test
# possible first bad commit: [6c73209746331f1fe3bac402b58c1702798f7e62] Prefer GLX over EGL
# possible first bad commit: [5c60456e16b118f2d2cbbe5344fa887cbeb59cc8] Merge pull request #567 from paulrouget/opengl-profile-selection-fix
# possible first bad commit: [691bac6528b09c04bed5abaf9e988eb9105ca86b] Merge pull request #568 from paulrouget/x11-crasher
# possible first bad commit: [26139f8c5c66e6fdf1508cd5e07018bbf9b62a76] Fix OpenGL profile selection
# possible first bad commit: [86408438fcaeb901684c82662608e84c381b11bd] Fix a rare crash in some X11 implementations (details below).
# possible first bad commit: [e90f377b9fbab23a140029e71ef57933b266c473] Merge pull request #565 from tomaka/correct-example
# possible first bad commit: [90e62083d686ed9c878beb348e9b54853242eab0] Merge pull request #566 from tomaka/display-egl
# possible first bad commit: [587dedaa9e95236f891d9a0e4ec04ee3700236a8] Correctly handle eglGetDisplay
```

I skipped the commits with build errors. I hope this might provide a clue.

I will study and try gdb later.

**Comment by farseerfc** [comment]
Here is me trying to get a backtrace from rust-gdb at https://github.com/servo/glutin/commit/6c73209746331f1fe3bac402b58c1702798f7e62 
```
(gdb) rbreak x_error_callback
Breakpoint 1 at 0x76788: file src/api/x11/xdisplay.rs, line 39.
static i32 glutin::api::x11::xdisplay::XConnection::new::x_error_callback(struct XErrorEvent *);
(gdb) run
Starting program: /home/farseerfc/github/glutin/target/debug/examples/window 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffed8ac700 (LWP 25702)]
[New Thread 0x7fffecea6700 (LWP 25707)]

Breakpoint 1, glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
39	            println!("[glutin] x error code={} major={} minor={}!", (*event).error_code,
(gdb) bt
#0  glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
#1  0x00005555555c856d in api::x11::xdisplay::_$LT$impl$GT$::new::x_error_callback::hcdb40003ba27babfevg
    () at src/libcore/clone.rs:66
#2  0x00007ffff650287d in _XError () from /usr/lib/libX11.so
#3  0x00007ffff64ff7c7 in ?? () from /usr/lib/libX11.so
#4  0x00007ffff64ff885 in ?? () from /usr/lib/libX11.so
#5  0x00007ffff6500830 in _XReply () from /usr/lib/libX11.so
#6  0x00007ffff64eb407 in XInternAtom () from /usr/lib/libX11.so
#7  0x00005555555c446d in fnfn (delete_window=0x7ffff682d040 "WM_DELETE_WINDOW")
    at src/api/x11/window.rs:461
#8  0x00005555555c43b6 in glutin::api::x11::window::with_c_str<closure,u64> (s="WM_DELETE_WINDOW", 
    f=closure = {...}) at src/api/x11/window.rs:38
#9  0x00005555555c19f9 in glutin::api::x11::window::Window::new (display=0x7ffff6823008, 
    builder=BuilderAttribs = {...}) at src/api/x11/window.rs:460
#10 0x00005555555cb5b5 in glutin::platform::platform::api_dispatch::Window::new (
    builder=BuilderAttribs = {...}) at src/platform/linux/api_dispatch.rs:155
#11 0x00005555555cfe03 in glutin::window::WindowBuilder<'a>::build (self=WindowBuilder = {...})
    at src/window.rs:182
#12 0x000055555556f376 in window::main () at examples/window.rs:22
#13 0x000055555568e0e5 in sys_common::unwind::try::try_fn::h8173478492453661613 ()
#14 0x000055555568bae9 in __rust_try ()
#15 0x000055555568dd80 in rt::lang_start::hbeb1bf39635abdcc9kx ()
#16 0x000055555557599a in main ()
(gdb) continue
Continuing.
[glutin] x error code=46 major=0 minor=0!

Breakpoint 1, glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
39	            println!("[glutin] x error code={} major={} minor={}!", (*event).error_code,
(gdb) bt
#0  glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
#1  0x00005555555c856d in api::x11::xdisplay::_$LT$impl$GT$::new::x_error_callback::hcdb40003ba27babfevg
    () at src/libcore/clone.rs:66
#2  0x00007ffff650287d in _XError () from /usr/lib/libX11.so
#3  0x00007ffff64ff7c7 in ?? () from /usr/lib/libX11.so
#4  0x00007ffff64ff885 in ?? () from /usr/lib/libX11.so
#5  0x00007ffff6500830 in _XReply () from /usr/lib/libX11.so
#6  0x00007ffff64eb407 in XInternAtom () from /usr/lib/libX11.so
#7  0x00005555555c446d in fnfn (delete_window=0x7ffff682d040 "WM_DELETE_WINDOW")
    at src/api/x11/window.rs:461
#8  0x00005555555c43b6 in glutin::api::x11::window::with_c_str<closure,u64> (s="WM_DELETE_WINDOW", 
    f=closure = {...}) at src/api/x11/window.rs:38
#9  0x00005555555c19f9 in glutin::api::x11::window::Window::new (display=0x7ffff6823008, 
    builder=BuilderAttribs = {...}) at src/api/x11/window.rs:460
#10 0x00005555555cb5b5 in glutin::platform::platform::api_dispatch::Window::new (
    builder=BuilderAttribs = {...}) at src/platform/linux/api_dispatch.rs:155
#11 0x00005555555cfe03 in glutin::window::WindowBuilder<'a>::build (self=WindowBuilder = {...})
    at src/window.rs:182
#12 0x000055555556f376 in window::main () at examples/window.rs:22
#13 0x000055555568e0e5 in sys_common::unwind::try::try_fn::h8173478492453661613 ()
#14 0x000055555568bae9 in __rust_try ()
#15 0x000055555568dd80 in rt::lang_start::hbeb1bf39635abdcc9kx ()
#16 0x000055555557599a in main ()
(gdb) continue
Continuing.
[glutin] x error code=47 major=0 minor=0!

Breakpoint 1, glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
39	            println!("[glutin] x error code={} major={} minor={}!", (*event).error_code,
(gdb) bt
#0  glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
#1  0x00005555555c856d in api::x11::xdisplay::_$LT$impl$GT$::new::x_error_callback::hcdb40003ba27babfevg
    () at src/libcore/clone.rs:66
#2  0x00007ffff650287d in _XError () from /usr/lib/libX11.so
#3  0x00007ffff64ff7c7 in ?? () from /usr/lib/libX11.so
#4  0x00007ffff64ff885 in ?? () from /usr/lib/libX11.so
#5  0x00007ffff6500830 in _XReply () from /usr/lib/libX11.so
#6  0x00007ffff64eb407 in XInternAtom () from /usr/lib/libX11.so
#7  0x00005555555c446d in fnfn (delete_window=0x7ffff682d040 "WM_DELETE_WINDOW")
    at src/api/x11/window.rs:461
#8  0x00005555555c43b6 in glutin::api::x11::window::with_c_str<closure,u64> (s="WM_DELETE_WINDOW", 
    f=closure = {...}) at src/api/x11/window.rs:38
#9  0x00005555555c19f9 in glutin::api::x11::window::Window::new (display=0x7ffff6823008, 
    builder=BuilderAttribs = {...}) at src/api/x11/window.rs:460
#10 0x00005555555cb5b5 in glutin::platform::platform::api_dispatch::Window::new (
    builder=BuilderAttribs = {...}) at src/platform/linux/api_dispatch.rs:155
#11 0x00005555555cfe03 in glutin::window::WindowBuilder<'a>::build (self=WindowBuilder = {...})
    at src/window.rs:182
#12 0x000055555556f376 in window::main () at examples/window.rs:22
#13 0x000055555568e0e5 in sys_common::unwind::try::try_fn::h8173478492453661613 ()
#14 0x000055555568bae9 in __rust_try ()
#15 0x000055555568dd80 in rt::lang_start::hbeb1bf39635abdcc9kx ()
#16 0x000055555557599a in main ()
(gdb) continue
Continuing.
[glutin] x error code=48 major=0 minor=0!

Breakpoint 1, glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
39	            println!("[glutin] x error code={} major={} minor={}!", (*event).error_code,
(gdb) bt
#0  glutin::api::x11::xdisplay::XConnection::new::x_error_callback (event=0x7fffffff7b10)
    at src/api/x11/xdisplay.rs:39
#1  0x00005555555c856d in api::x11::xdisplay::_$LT$impl$GT$::new::x_error_callback::hcdb40003ba27babfevg
    () at src/libcore/clone.rs:66
#2  0x00007ffff650287d in _XError () from /usr/lib/libX11.so
#3  0x00007ffff64ff7c7 in ?? () from /usr/lib/libX11.so
#4  0x00007ffff64ff885 in ?? () from /usr/lib/libX11.so
#5  0x00007ffff6500830 in _XReply () from /usr/lib/libX11.so
#6  0x00007ffff64eb407 in XInternAtom () from /usr/lib/libX11.so
#7  0x00005555555c446d in fnfn (delete_window=0x7ffff682d040 "WM_DELETE_WINDOW")
    at src/api/x11/window.rs:461
#8  0x00005555555c43b6 in glutin::api::x11::window::with_c_str<closure,u64> (s="WM_DELETE_WINDOW", 
    f=closure = {...}) at src/api/x11/window.rs:38
#9  0x00005555555c19f9 in glutin::api::x11::window::Window::new (display=0x7ffff6823008, 
    builder=BuilderAttribs = {...}) at src/api/x11/window.rs:460
#10 0x00005555555cb5b5 in glutin::platform::platform::api_dispatch::Window::new (
    builder=BuilderAttribs = {...}) at src/platform/linux/api_dispatch.rs:155
#11 0x00005555555cfe03 in glutin::window::WindowBuilder<'a>::build (self=WindowBuilder = {...})
    at src/window.rs:182
#12 0x000055555556f376 in window::main () at examples/window.rs:22
#13 0x000055555568e0e5 in sys_common::unwind::try::try_fn::h8173478492453661613 ()
#14 0x000055555568bae9 in __rust_try ()
#15 0x000055555568dd80 in rt::lang_start::hbeb1bf39635abdcc9kx ()
#16 0x000055555557599a in main ()
(gdb) 
```

**Comment by farseerfc** [comment]
Confirmed that this has been fixed in https://github.com/servo/glutin/commit/d78affcb5e45de46338f8f8082c1ed6a4a71d46c and https://github.com/servo/servo/commit/c075092fe067292b58a781169da937d1f047b62e .
I will close this issue.
