### ISSUE TITLE
Mach build error Ubuntu 15.04

### ISSUE THREAD

**Issue by nathansizemore** [servo/servo#8233]
I get the following error when attempting `./mach build --dev`:

~~~
Traceback (most recent call last):
  File "./mach", line 25, in <module>
    main(sys.argv)
  File "./mach", line 21, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "./python/mach_bootstrap.py", line 151, in bootstrap
    _activate_virtualenv(topdir)
  File "./python/mach_bootstrap.py", line 105, in _activate_virtualenv
    execfile(activate_path, dict(__file__=activate_path))
IOError: [Errno 2] No such file or directory: '~/development/bin/servo/python/_virtualenv/bin/activate_this.py'
~~~

**Comment by frewsxcv** [comment]
Can you remove the _virtualenv directory, try building again, and see if you get the same error?

**Comment by nathansizemore** [comment]
After that, got this:

~~~
Running virtualenv with interpreter ~/development/bin/ndk-standalone-14-arm/bin/python2.7
New python executable in ~/development/bin/servo/python/_virtualenv/bin/python2.7
Also creating executable in ~/development/bin/servo/python/_virtualenv/bin/python
Installing setuptools, pip...
  Complete output from command ~/develop...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 73, in <module>
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/util.py", line 20, in <module>
  File "~/development/bin/servo/python/_virtualenv/lib/python-wheels/distlib-0.1.9-py2.py3-none-any.whl/distlib/version.py", line 14, in <module>
  File "~/development/bin/servo/python/_virtualenv/lib/python-wheels/distlib-0.1.9-py2.py3-none-any.whl/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2378, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 830, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1032, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 975, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 917, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command ~/develop...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
Python virtualenv failed to execute properly.

~~~

**Comment by frewsxcv** [comment]
Looks like a non-servo issue. Maybe try something from here? http://stackoverflow.com/questions/20688034/importerror-cannot-import-name-httpshandler-using-pip

**Comment by frewsxcv** [comment]
Sorry, am on mobile right now if that seemed like a lazy response :P

**Comment by nathansizemore** [comment]
Nah, you're fine. It happened to be my python was symlinked to the Android NDKs python from an earlier setup and I forgot to unlink it.
