### ISSUE TITLE
Intermittent panic in /css21_dev/html4/left-077.htm

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8236]
```
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) Full command: /Users/servo/buildbot/slave/mac-rel-css/build/target/release/servo --cpu --hard-fail --exit -u Servo/wptrunner -Z disable-text-aa --output=/var/folders/16/h7h_cw7d42gbp2bphlppgf_h0000gp/T/tmph85geQ/a995f8d2-644c-4100-bf8e-f40a77270bf6 http://web-platform.test:8000/css21_dev/html4/left-077.htm --user-stylesheet /Users/servo/buildbot/slave/mac-rel-css/build/resources/ahem.css
(pid:47220) "thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:736"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "stack backtrace:"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   1:        0x10db47b58 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   2:        0x10db4964f - panicking::log_panic::_<closure>::closure.38923"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   3:        0x10db490f9 - panicking::log_panic::h87af6096e0b6fa7c4Uw"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   4:        0x10db380f6 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   5:        0x10db384de - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   6:        0x10db471e7 - rust_begin_unwind"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   7:        0x10db6cf90 - panicking::panic_fmt::h54ca80e608a83d7dwZK"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   8:        0x10d00326e - mem::_<impl>::send::h0444e63fa5efdb7bCba"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   9:        0x10cd120b8 - boxed::_<impl>::call_box::call_box::h7441143315341015046"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  10:        0x10c8dcf42 - sys_common::unwind::try::try_fn::try_fn::h2585283473086766647"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  11:        0x10db47028 - __rust_try"
 9:10.95 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  12:        0x10db444ce - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  13:        0x10c8dd0e7 - boxed::_<impl>::call_box::call_box::h3399541081563954605"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  14:        0x10db48a1d - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  15:     0x7fff91449059 - _pthread_body"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  16:     0x7fff91448fd6 - _pthread_start"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:365"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "stack backtrace:"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   1:        0x10db47b58 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   2:        0x10db4964f - panicking::log_panic::_<closure>::closure.38923"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   3:        0x10db490f9 - panicking::log_panic::h87af6096e0b6fa7c4Uw"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   4:        0x10db37ff4 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   5:        0x10db384de - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   6:        0x10db471e7 - rust_begin_unwind"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   7:        0x10db6cf90 - panicking::panic_fmt::h54ca80e608a83d7dwZK"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   8:        0x10db68b1c - panicking::panic::h2a24d1d860d3cd423XK"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "   9:        0x10c8f69d9 - page::_<impl>::window::hdf120399705f8f239oW"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  10:        0x10cd10684 - script_task::_<impl>::drop::hbe222196f0075108BsX"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  11:        0x10cd12825 - boxed::_<impl>::call_box::call_box::h7441143315341015046"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  12:        0x10c8dcf42 - sys_common::unwind::try::try_fn::try_fn::h2585283473086766647"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  13:        0x10db47028 - __rust_try"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  14:        0x10db444ce - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  15:        0x10c8dd0e7 - boxed::_<impl>::call_box::call_box::h3399541081563954605"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  16:        0x10db48a1d - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  17:     0x7fff91449059 - _pthread_body"
 9:10.96 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:47220) "  18:     0x7fff91448fd6 - _pthread_start"
```

```
Summary
=======

Ran 6961 tests (6691 parents, 270 subtests)
Expected results: 6950
Unexpected results: 1 (CRASH: 1)
Skipped: 10

Unexpected Results
==================

/css21_dev/html4/left-077.htm
-----------------------------
CRASH [Parent]
13:15.88 LOG: MainThread INFO Closing logging queue
13:15.88 LOG: MainThread INFO queue closed
program finished with exit code 1
elapsedTime=798.759052
```

**Comment by jdm** [comment]
That is one of the least informative stack traces I've ever seen.

**Comment by jdm** [comment]
Hasn't been seen in months; not disabled => close.
