### ISSUE TITLE
Navigating back in history results in panic

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8324]
Currently on 86e3add8fdc35fc6980bb63695781925607437b8 running on OSX 10.11

![untitled](https://cloud.githubusercontent.com/assets/416575/10928462/7eb2c948-8276-11e5-8251-18ec8c777788.gif)

**Comment by jdm** [comment]
Could you grab the backtrace from rust_panic in lldb?

**Comment by frewsxcv** [comment]
Ah, forgot to add that in the original post

```
ERROR:js::rust: Error at https://meta.wikimedia.org/w/load.php?debug=false&lang=en&modules=ext.gadget.wm-portal&only=scripts&skin=vector&*:5:243: TypeError: document.searchwiki.elements is undefined

thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: self.suspended_since.get().is_none()', /Users/coreyf/Development/rust/servo/components/script/timers.rs:286
stack backtrace:
   1:        0x10ac61e18 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
   2:        0x10ac6390f - panicking::log_panic::_<closure>::closure.38923
   3:        0x10ac633b9 - panicking::log_panic::h87af6096e0b6fa7c4Uw
   4:        0x10ac52486 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
   5:        0x109953254 - sys_common::unwind::begin_unwind::begin_unwind::h4227116571666615755
   6:        0x109d65a70 - timers::_<impl>::schedule_timer_call::h5bbd94dd52a1f8a6v3Y
   7:        0x109d6a1a4 - dom::window::_<impl>::thaw::h7d0cabeff68c00ecqsS
   8:        0x109db77f1 - script_task::_<impl>::handle_msg_from_constellation::h396fed1063cb0c9esMW
   9:        0x109db5d15 - script_task::_<impl>::handle_msgs::_<closure>::closure.149177
  10:        0x109d9e55e - script_task::_<impl>::handle_msgs::h653864c1a4a5f86e5zW
  11:        0x109d88f77 - boxed::_<impl>::call_box::call_box::h11308801362075513240
  12:        0x10995c9e2 - sys_common::unwind::try::try_fn::try_fn::h10377635494035671278
  13:        0x10ac612e8 - __rust_try
  14:        0x10ac5e78e - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r
  15:        0x10995cb87 - boxed::_<impl>::call_box::call_box::h5765860204961138911
  16:        0x10ac62cdd - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw
  17:     0x7fff9ab319b0 - _pthread_body
  18:     0x7fff9ab3192d - _pthread_start
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:        0x10ac61e18 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
   2:        0x10ac6390f - panicking::log_panic::_<closure>::closure.38923
   3:        0x10ac633b9 - panicking::log_panic::h87af6096e0b6fa7c4Uw
   4:        0x10ac52486 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
   5:        0x10ac5286e - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r
   6:        0x10ac614a7 - rust_begin_unwind
   7:        0x10ac87250 - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:        0x10a0abec6 - pipeline::_<impl>::force_exit::h0de9cc5dd5b48b85AHf
   9:        0x1097953e8 - constellation::_<impl>::close_pipeline::close_pipeline::h3343466691774888673
  10:        0x109782d65 - constellation::_<impl>::handle_request::handle_request::h13841867577141189727
  11:        0x109771878 - export::compositing::constellation::_<impl>::start::_<closure>::closure.20001
  12:        0x10976fe3d - boxed::_<impl>::call_box::call_box::h1408734385257270500
  13:        0x10976f812 - sys_common::unwind::try::try_fn::try_fn::h9807883478414137302
  14:        0x10ac612e8 - __rust_try
  15:        0x10ac5e78e - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r
  16:        0x10976f9b7 - boxed::_<impl>::call_box::call_box::h10295156486093541426
  17:        0x10ac62cdd - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw
  18:     0x7fff9ab319b0 - _pthread_body
  19:     0x7fff9ab3192d - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:        0x10ac61e18 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
   2:        0x10ac6390f - panicking::log_panic::_<closure>::closure.38923
   3:        0x10ac633b9 - panicking::log_panic::h87af6096e0b6fa7c4Uw
   4:        0x10ac52486 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
   5:        0x10ac5286e - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r
   6:        0x10ac614a7 - rust_begin_unwind
   7:        0x10ac87250 - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:        0x109737f6a - compositor::_<impl>::handle_events::handle_events::h9845075675319180751
   9:        0x109763087 - _<impl>::handle_events::h392d074a5a260823Lda
  10:        0x109720d95 - main::h88b1797263a28c78Jaa
  11:        0x10ac63142 - sys_common::unwind::try::try_fn::h5790516615995350782
  12:        0x10ac612e8 - __rust_try
  13:        0x10ac62fe9 - rt::lang_start::h3dc147628bf597f5cSw
thread 'thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ', src/libcore/result.rssrc/libcore/result.rs::736736

stack backtrace:
   1:        0x10ac61e18 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
Servo exited with return value 101
```

**Comment by frewsxcv** [comment]
In the process of a bisect...

**Comment by frewsxcv** [comment]
Traced it back to 553a0dbefd8a8724f7c894b1c25e6c15c35d6d04

**Comment by jdm** [comment]
Probably fixed by #8175?

**Comment by frewsxcv** [comment]
> Probably fixed by #8175?

Yes. Confirmed it last night

**Comment by karyon** [comment]
i saw a similar crash (it also contained `thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: self.suspended_since.get().is_none()',`), although it happened when merely visiting a site, and updating to current master fixed it.

**Comment by jdm** [comment]
Great :)

**Comment by frewsxcv** [comment]
New issue similar to this: 8461
