### ISSUE TITLE
about.twitter.com panic

### ISSUE THREAD

**Issue by muattiyah** [servo/servo#8380]
https://gist.github.com/skeuomorf/035d76b3162d5248bc80

**Comment by jdm** [comment]
```
thread 'FontCacheTask' panicked at 'Unable to find any fonts that match (do you have fallback fonts installed?)', /home/skeuomorf/Projects/rust/servo/components/gfx/font_cache_task.rs:273
stack backtrace:
   1:     0x5652ae7290b0 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x5652ae72b605 - panicking::log_panic::_<closure>::closure.39180
   3:     0x5652ae72b051 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x5652ae717af3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x5652ad366147 - sys_common::unwind::begin_unwind::begin_unwind::h4921121113011615803
                        at src/libstd/sys/common/unwind/mod.rs:214
   6:     0x5652ad3cbe4e - font_cache_task::_<impl>::last_resort_font_template::h5ad38b3067e9c7f00Dk
                        at /home/skeuomorf/Projects/rust/servo/components/servo/<std macros>:3
   7:     0x5652ad3b0c13 - font_cache_task::_<impl>::run::hcc3634c16d9e5232Vsk
                        at /home/skeuomorf/Projects/rust/servo/components/gfx/font_cache_task.rs:127
   8:     0x5652ad4061e7 - font_cache_task::_<impl>::new::_<closure>::closure.39190
                        at /home/skeuomorf/Projects/rust/servo/components/gfx/font_cache_task.rs:309
   9:     0x5652ad405df8 - boxed::_<impl>::call_box::call_box::h5066436557140378820
                        at src/liballoc/boxed.rs:516
  10:     0x5652ad405aab - boxed::_<impl>::call_once::call_once::h17344310899336438832
                        at src/liballoc/boxed.rs:532
  11:     0x5652ad40569d - std::thread::_<impl>::spawn_inner::_<closure>::_<closure>::closure.39166
                        at src/libstd/thread/mod.rs:280
  12:     0x5652ad405649 - sys_common::unwind::try::try_fn::try_fn::h13299187265058896337
                        at src/libstd/sys/common/unwind/mod.rs:146
  13:     0x5652ae7285e8 - __rust_try
  14:     0x5652ae724bbb - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  15:     0x5652ad4055b3 - sys_common::unwind::try::try::h18410520955237964349
                        at src/libstd/sys/common/unwind/mod.rs:116
  16:     0x5652ad405448 - std::thread::_<impl>::spawn_inner::_<closure>::closure.39143
                        at src/libstd/thread/mod.rs:280
  17:     0x5652ad405cbc - boxed::_<impl>::call_box::call_box::h10548481233140077779
                        at src/liballoc/boxed.rs:516
  18:     0x5652ae72a0f3 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  19:     0x7fd93d7f94a3 - start_thread
  20:     0x7fd93dffa13c - clone
  21:                0x0 - <unknown>
```

**Comment by skeuomorf** [comment]
Running with RUST_BACKTRACE=1 https://gist.github.com/skeuomorf/6b9745611f503c29b092

**Comment by notriddle** [comment]
I can't reproduce. Do you not have any of the fallback fonts?

**Comment by skeuomorf** [comment]
Nope, here's the output of `fc-list` https://gist.github.com/skeuomorf/fba596884ee5686b64ec and here's my font configuration https://gist.github.com/skeuomorf/485c3f40a8b4d8e2e39b

**Comment by notriddle** [comment]
Well, there's the problem. Servo's set of fallback fonts are hardcoded at "Fira Sans", "DejaVu Sans", and "Arial". I can't find any of them in your `fc-list`.

**Comment by sviter** [comment]
Can't reproduce with Servo 0.0.1-08b9588 on Win10

**Comment by nox** [comment]
I can't reproduce this.
