### ISSUE TITLE
Nvidia on linux panics at `glx_bind_tex_image`

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#8396]
This was a release build, on a machine using `bumblebee` for Optimus.

```
$ optirun ./mach run -r https://google.com
thread '<main>' panicked at 'assertion failed: (glx_bind_tex_image as *mut c_void) != ptr::null_mut()', /home/manishearth/Mozilla/voser/./../.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:216
stack backtrace:
   1:     0x7f13b7095d40 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x7f13b7098295 - panicking::log_panic::_<closure>::closure.39180
   3:     0x7f13b7097ce1 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x7f13b7084853 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x7f13b670467f - sys_common::unwind::begin_unwind::begin_unwind::h4145240281731621136
   6:     0x7f13b670c02a - platform::linux::surface::_<impl>::bind_to_texture::h32153c8323327482Tgc
   7:     0x7f13b670b10e - tiling::_<impl>::create_textures::h37609448523ee12dJSb
   8:     0x7f13b5984dea - rendergl::_<impl>::render_3d_context::render_3d_context::h1211549539602193388
   9:     0x7f13b598538e - rendergl::_<impl>::render_3d_context::render_3d_context::h1211549539602193388
  10:     0x7f13b5984220 - rendergl::render_scene::render_scene::h4254356192062441325
  11:     0x7f13b5980ee6 - compositor::_<impl>::composite_specific_target::composite_specific_target::h15129295644874159899
  12:     0x7f13b59880c1 - compositor::_<impl>::composite::composite::h11298050138310878746
  13:     0x7f13b5962f71 - compositor::_<impl>::handle_events::handle_events::h5871735200720717414
  14:     0x7f13b599123c - _<impl>::handle_events::h47298b29f083eaf5Lda
  15:     0x7f13b5949295 - main::h6ac4149d54e3c2d9Jaa
  16:     0x7f13b7097a24 - sys_common::unwind::try::try_fn::h10604132475359592391
  17:     0x7f13b7095278 - __rust_try
  18:     0x7f13b70976bf - rt::lang_start::hd74bfb7a606308914ix
  19:     0x7f13b34e7a3f - __libc_start_main
  20:     0x7f13b593cef8 - _start
  21:                0x0 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/manishearth/Mozilla/voser/./../.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166
stack backtrace:
   1:     0x7f13b7095d40 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x7f13b7098295 - panicking::log_panic::_<closure>::closure.39180
   3:     0x7f13b7097ce1 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x7f13b7084778 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x7f13b670467f - sys_common::unwind::begin_unwind::begin_unwind::h4145240281731621136
   6:     0x7f13b6704780 - platform::linux::surface::_<impl>::drop::h53d5795b8d689dedxfc
   7:     0x7f13b595da67 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28705::h82d58d8bfef068ee
   8:     0x7f13b595dbb5 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28717::hccbd571cf17f6cb5
   9:     0x7f13b595d944 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28705::h82d58d8bfef068ee
  10:     0x7f13b595f9f3 - compositing..compositor..IOCompositor<app..window..Window>::drop.29082::hcaaf25679afc7cd2
  11:     0x7f13b59495af - main::h6ac4149d54e3c2d9Jaa
  12:     0x7f13b7097a24 - sys_common::unwind::try::try_fn::h10604132475359592391
  13:     0x7f13b7095278 - __rust_try
  14:     0x7f13b70976bf - rt::lang_start::hd74bfb7a606308914ix
  15:     0x7f13b34e7a3f - __libc_start_main
  16:     0x7f13b593cef8 - _start
  17:                0x0 - <unknown>
thread panicked while panicking. aborting.Servo exited with return value -4
```

**Comment by Manishearth** [comment]
triage: still a problem

**Comment by dralley** [comment]
Can it still be reproduced?

**Comment by jdm** [comment]
The relevant code isn't used any more.
