### ISSUE TITLE
Servo crashes with “Compositor layer has an unknown pipeline”

### ISSUE THREAD

**Issue by suhr** [servo/servo#8501]
How to reproduce:

1. Run `./mach run --release -- -g  http://2ch.hk/fl/`
2. Scroll down with Page Down key until it crashes

Console output:

```
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }).', /mnt/VCD/foo/servo/components/compositing/compositor.rs:688
stack backtrace:
   1:     0x555abd1df460 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x555abd1e19b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x555abd1e1401 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x555abd1cdf73 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x555abd1ce628 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x555abbaf6ce4 - compositor::_<impl>::send_viewport_rect_for_layer::send_viewport_rect_for_layer::h2925545938040216632
   7:     0x555abbaf6c3d - compositor::_<impl>::send_viewport_rect_for_layer::send_viewport_rect_for_layer::h2925545938040216632
   8:     0x555abbaf6c3d - compositor::_<impl>::send_viewport_rect_for_layer::send_viewport_rect_for_layer::h2925545938040216632
   9:     0x555abbaf6c3d - compositor::_<impl>::send_viewport_rect_for_layer::send_viewport_rect_for_layer::h2925545938040216632
  10:     0x555abbb0393e - compositor::_<impl>::composite_specific_target::composite_specific_target::h5796295134193584620
  11:     0x555abbb09581 - compositor::_<impl>::composite::composite::h7450723088071377407
  12:     0x555abbae489a - compositor::_<impl>::handle_events::handle_events::h8773525648245527613
  13:     0x555abbb1273c - _<impl>::handle_events::h210c254f99a5dc93Lda
  14:     0x555abbacaec5 - main::h6ac4149d54e3c2d9Jaa
  15:     0x555abd1e1144 - sys_common::unwind::try::try_fn::h10604132475359592391
  16:     0x555abd1de998 - __rust_try
  17:     0x555abd1e0ddf - rt::lang_start::hd74bfb7a606308914ix
  18:     0x7ffa1e15d79f - __libc_start_main
  19:     0x555abbabeb38 - <unknown>
  20:                0x0 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /mnt/VCD/foo/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166
stack backtrace:
   1:     0x555abd1df460 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x555abd1e19b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x555abd1e1401 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x555abd1cde98 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x555abc88d14f - sys_common::unwind::begin_unwind::begin_unwind::h7359809134813014923
   6:     0x555abc88d250 - platform::linux::surface::_<impl>::drop::h52e34fcbebadedb8xfc
   7:     0x555abbadf367 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28703::h304233cac1dc042a
   8:     0x555abbadf4b5 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28715::hb4fdef0af03ede03
   9:     0x555abbadf244 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28703::h304233cac1dc042a
  10:     0x555abbadf4b5 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28715::hb4fdef0af03ede03
  11:     0x555abbadf244 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28703::h304233cac1dc042a
  12:     0x555abbadf4b5 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28715::hb4fdef0af03ede03
  13:     0x555abbadf244 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28703::h304233cac1dc042a
  14:     0x555abbae12f3 - compositing..compositor..IOCompositor<app..window..Window>::drop.29080::hcaaf25679afc7cd2
  15:     0x555abbacb1df - main::h6ac4149d54e3c2d9Jaa
  16:     0x555abd1e1144 - sys_common::unwind::try::try_fn::h10604132475359592391
  17:     0x555abd1de998 - __rust_try
  18:     0x555abd1e0ddf - rt::lang_start::hd74bfb7a606308914ix
  19:     0x7ffa1e15d79f - __libc_start_main
  20:     0x555abbabeb38 - <unknown>
  21:                0x0 - <unknown>
thread panicked while panicking. aborting.Servo exited with return value -4
```

Additional bugs:

* The page is not rendered properly
* Some elements disappear after scrolling down
* High CPU usage on scrolling

OS: Linux x86_64

**Comment by jdm** [comment]
Is there any difference without `-g`? That's an argument I'm not used to seeing.

**Comment by suhr** [comment]
Nope, it crashes the same way without `-g`.

**Comment by suhr** [comment]
It doesn't crash anymore, but rendering is badly broken.

**Comment by jdm** [comment]
Ok, sounds like this can be closed. Please file a separate issue about the rendering output.
