### ISSUE TITLE
Wikipedia crashes on Android

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#8507]
On my Odroid XU3, running Android 4.4.4, Servo (f078f8fdf4157b4e57cef35eba00419c9c15464d) crashes on http://en.wikipedia.org/wiki/Rust

Here's the log:

```
E/AudioPolicyManagerBase( 2855): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManagerBase( 2855): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
D/AudioHardware( 2855): AudioHardware pcm playback is exiting standby.
D/AudioHardware( 2855): openPcmOut_l() mPcmOpenCnt: 0
D/AudioHardware( 2855): Have alternate card: 0 using 44100Hz rate
I/ActivityManager( 3210): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mozilla.servo/.MainActivity} from pid 3369
D/dalvikvm( 5164): Late-enabling CheckJNI
D/dalvikvm( 3210): GC_FOR_ALLOC freed 241K, 32% free 6970K/10140K, paused 39ms, total 39ms
I/dalvikvm-heap( 3210): Grow heap (frag case) to 10.869MB for 4194320-byte allocation
D/dalvikvm( 3210): GC_CONCURRENT freed 12K, 23% free 11053K/14240K, paused 2ms+4ms, total 37ms
D/dalvikvm( 3210): WAIT_FOR_CONCURRENT_GC blocked 35ms
D/dalvikvm( 3210): WAIT_FOR_CONCURRENT_GC blocked 35ms
D/dalvikvm( 3210): WAIT_FOR_CONCURRENT_GC blocked 35ms
I/ActivityManager( 3210): Start proc com.mozilla.servo for activity com.mozilla.servo/.MainActivity: pid=5164 uid=10062 gids={50062, 3003, 1028, 1015, 1023}
I/servo_wrapper( 5164): Loading the NativeActivity
D/dalvikvm( 5164): GC_FOR_ALLOC freed 64K, 5% free 2848K/2976K, paused 9ms, total 9ms
I/dalvikvm-heap( 5164): Grow heap (frag case) to 6.838MB for 4194320-byte allocation
D/dalvikvm( 5164): GC_CONCURRENT freed 2K, 2% free 6942K/7076K, paused 1ms+2ms, total 14ms
D/dalvikvm( 5164): WAIT_FOR_CONCURRENT_GC blocked 13ms
E/AudioPolicyManagerBase( 2855): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManagerBase( 2855): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
V/threaded_app( 5164): Creating: 0x76028e48
V/threaded_app( 5164): Config: mcc=0 mnc=0 lang=en cnt=US orien=2 touch=3 dens=160 keys=2 nav=1 keysHid=1 navHid=0 sdk=19 size=3 long=2 modetype=1 modenight=1
V/threaded_app( 5164): Start: 0x76028e48
D/RustAndroidGlueStdouterr( 5164): Entering android_main
D/RustAndroidGlueStdouterr( 5164): created application thread
V/threaded_app( 5164): activityState=10
V/threaded_app( 5164): Resume: 0x76028e48
V/threaded_app( 5164): activityState=11
V/threaded_app( 5164): InputQueueCreated: 0x76028e48 -- 0x76032b38
V/threaded_app( 5164): APP_CMD_INPUT_CHANGED
V/threaded_app( 5164): Attaching input queue to looper
V/threaded_app( 5164): NativeWindowCreated: 0x76028e48 -- 0x760381b8
V/threaded_app( 5164): APP_CMD_INIT_WINDOW
V/threaded_app( 5164): WindowFocusChanged: 0x76028e48 -- 1
I/        ( 5164): PLATFORM VERSION : JB-MR-2
D/mali_winsys( 5164): new_window_surface returns 0x3000
I/ActivityManager( 3210): Displayed com.mozilla.servo/.MainActivity: +1s913ms
D/RustAndroidGlueStdouterr( 5164): Fontconfig error: Cannot load default config file
D/AudioHardware( 2855): AudioHardware pcm playback is going to standby.
D/AudioHardware( 2855): closePcmOut_l() mPcmOpenCnt: 1
D/skia    ( 5164): Device supports ARM NEON instructions!
D/RustAndroidGlueStdouterr( 5164): thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'arithmetic operation overflowed', /home/mmatyas/Mozilla/servo-android/servo/target/arm-linux-androideabi/debug/build/script-49036527ec234d45/out/Bindings/WindowBinding.rs:2624
F/libc    ( 5164): Fatal signal 4 (SIGILL) at 0x7914d7f0 (code=1), thread 5208 (ScriptTask Pipe)
I/DEBUG   ( 4845): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 4845): Build fingerprint: 'ODROID/odroidxu3/odroidxu3:4.4.4/KTU84Q/eng.mmatyas.20150924.102136:eng/test-keys'
I/DEBUG   ( 4845): Revision: '256'
I/DEBUG   ( 4845): pid: 5164, tid: 5208, name: ScriptTask Pipe  >>> com.mozilla.servo <<<
I/DEBUG   ( 4845): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 7914d7f0
I/DEBUG   ( 4845):     r0 00000000  r1 00000000  r2 00000001  r3 00000001
I/DEBUG   ( 4845):     r4 81ca6790  r5 79926f38  r6 7d83f1c0  r7 00000a40
I/DEBUG   ( 4845):     r8 00000088  r9 795a0d00  sl 00019dec  fp 00000001
I/DEBUG   ( 4845):     ip 00000008  sp 80ff71f0  lr 7914dd98  pc 7914d7f0  cpsr 800f0010
I/DEBUG   ( 4845):     d0  4341425f5453554b  d1  ffff454341525454
I/DEBUG   ( 4845):     d2  0000000000000052  d3  0000000000000041
I/DEBUG   ( 4845):     d4  4022000000000000  d5  4024000000000000
I/DEBUG   ( 4845):     d6  4022000000000000  d7  40220000000003e8
I/DEBUG   ( 4845):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   ( 4845):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   ( 4845):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   ( 4845):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   ( 4845):     d16 006a002c0069006b  d17 0072006500750051
I/DEBUG   ( 4845):     d18 40f86a0000000000  d19 0000000000000000
I/DEBUG   ( 4845):     d20 0000000000000f30  d21 4000000000000000
I/DEBUG   ( 4845):     d22 0000000000000028  d23 ffffffffffffffff
I/DEBUG   ( 4845):     d24 000000000000000f  d25 ffffffffffffffcc
I/DEBUG   ( 4845):     d26 ffffffffffffffff  d27 ffffffffffffffc0
I/DEBUG   ( 4845):     d28 000000000000003f  d29 ffffffffffffffff
I/DEBUG   ( 4845):     d30 016a005b01620059  d31 4000000000000000
I/DEBUG   ( 4845):     scr 60000011
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): backtrace:
I/DEBUG   ( 4845):     #00  pc 031017f0  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):     #01  pc 03101d94  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): stack:
I/DEBUG   ( 4845):          80ff71b0  79926f88  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):          80ff71b4  00000001  
I/DEBUG   ( 4845):          80ff71b8  00000000  
I/DEBUG   ( 4845):          80ff71bc  00000000  
I/DEBUG   ( 4845):          80ff71c0  80ff7218  [stack:5208]
I/DEBUG   ( 4845):          80ff71c4  00000001  
I/DEBUG   ( 4845):          80ff71c8  7d83f1c0  
I/DEBUG   ( 4845):          80ff71cc  80ff71dc  [stack:5208]
I/DEBUG   ( 4845):          80ff71d0  00000000  
I/DEBUG   ( 4845):          80ff71d4  00000000  
I/DEBUG   ( 4845):          80ff71d8  00000000  
I/DEBUG   ( 4845):          80ff71dc  00000001  
I/DEBUG   ( 4845):          80ff71e0  81ca6790  
I/DEBUG   ( 4845):          80ff71e4  79926f38  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):          80ff71e8  7d83f1c0  
I/DEBUG   ( 4845):          80ff71ec  7914d7f0  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):     #00  80ff71f0  80ff72ac  [stack:5208]
I/DEBUG   ( 4845):          80ff71f4  00000009  
I/DEBUG   ( 4845):          80ff71f8  80ff71f4  [stack:5208]
I/DEBUG   ( 4845):          80ff71fc  791bfaf4  /data/app-lib/com.mozilla.servo-1/libmain.so (fmt::num::_$LT$impl$GT$::fmt::h8edd90231ae2bc5eP5V)
I/DEBUG   ( 4845):          80ff7200  79926f18  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):          80ff7204  00000001  
I/DEBUG   ( 4845):          80ff7208  00000000  
I/DEBUG   ( 4845):          80ff720c  00000000  
I/DEBUG   ( 4845):          80ff7210  80ff71f8  [stack:5208]
I/DEBUG   ( 4845):          80ff7214  00000001  
I/DEBUG   ( 4845):          80ff7218  80ff7200  [stack:5208]
I/DEBUG   ( 4845):          80ff721c  791c40b0  /data/app-lib/com.mozilla.servo-1/libmain.so (fmt::_$LT$impl$GT$::fmt::hebc66944d41e600ajWW)
I/DEBUG   ( 4845):          80ff7220  79926f88  /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):          80ff7224  00000001  
I/DEBUG   ( 4845):          80ff7228  00000000  
I/DEBUG   ( 4845):          80ff722c  00000000  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory near r4:
I/DEBUG   ( 4845):     81ca6770 00000001 00000001 87109f58 76ca01d4  
I/DEBUG   ( 4845):     81ca6780 8728c200 00000000 81c58000 30363101  
I/DEBUG   ( 4845):     81ca6790 7d89c280 0000003e 0000001f ffffffff  
I/DEBUG   ( 4845):     81ca67a0 1d1d1d1d 1d1d1d1d 1d1d1d1d 1d1d1d1d  
I/DEBUG   ( 4845):     81ca67b0 7d8b4dc0 0000001f 0000001f 39302541  
I/DEBUG   ( 4845):     81ca67c0 00000000 00000000 1d1d1d00 ffffffd4  
I/DEBUG   ( 4845):     81ca67d0 00000000 00000000 87142d78 80ff95d4  
I/DEBUG   ( 4845):     81ca67e0 000000e2 00000000 7a841028 ffffffff  
I/DEBUG   ( 4845):     81ca67f0 54535552 4341425f 4152544b ff004543  
I/DEBUG   ( 4845):     81ca6800 00000002 81c2d000 7f4321d4 ffffffff  
I/DEBUG   ( 4845):     81ca6810 7d8b4ce0 2f2f3a73 61736369 746e6572  
I/DEBUG   ( 4845):     81ca6820 00000001 00000001 8717b910 ffffffd4  
I/DEBUG   ( 4845):     81ca6830 00000001 00000001 87147458 80ff8ad4  
I/DEBUG   ( 4845):     81ca6840 000000e1 00000000 7a841028 ffffffff  
I/DEBUG   ( 4845):     81ca6850 000000e1 00000000 7a841028 ffffffff  
I/DEBUG   ( 4845):     81ca6860 00000002 81c2d000 000000d4 25676e69  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory near r5:
I/DEBUG   ( 4845):     79926f18 7981ec80 00000020 791141a8 00000004  
I/DEBUG   ( 4845):     79926f28 00000004 7914d8a4 7914d8f0 7914d9ec  
I/DEBUG   ( 4845):     79926f38 791140d8 0000000c 00000004 7914da50  
I/DEBUG   ( 4845):     79926f48 00000000 00000000 791141a8 00000004  
I/DEBUG   ( 4845):     79926f58 00000004 7914dfd4 7914dfdc 7914e0b0  
I/DEBUG   ( 4845):     79926f68 00000000 00000000 7914dc24 00000010  
I/DEBUG   ( 4845):     79926f78 00000004 7914dca0 7914dea4 7914df74  
I/DEBUG   ( 4845):     79926f88 7981ecb0 00000015 79926fa0 00000001  
I/DEBUG   ( 4845):     79926f98 7981ecd0 00000001 7981ecc5 00000002  
I/DEBUG   ( 4845):     79926fa8 7981ed1d 00000003 7981ed20 00000001  
I/DEBUG   ( 4845):     79926fb8 7981ed00 0000001d 000002b2 7981ed00  
I/DEBUG   ( 4845):     79926fc8 0000001d 000002b3 7981ed4e 00000006  
I/DEBUG   ( 4845):     79926fd8 7981ed54 00000008 7981ed5c 00000005  
I/DEBUG   ( 4845):     79926fe8 7981ed70 00000022 7981eda0 00000011  
I/DEBUG   ( 4845):     79926ff8 7981edc0 00000016 79926470 00000003  
I/DEBUG   ( 4845):     79927008 7981ede0 0000001e 0000002e 791141a8  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory near r6:
I/DEBUG   ( 4845):     7d83f1a0 00000001 00000000 00000000 000000d4  
I/DEBUG   ( 4845):     7d83f1b0 00000000 00000001 00000000 00000000  
I/DEBUG   ( 4845):     7d83f1c0 52555354 4d4f5a00 7914d5d0 00000000  
I/DEBUG   ( 4845):     7d83f1d0 00000000 00000000 00000000 00000000  
I/DEBUG   ( 4845):     7d83f1e0 00000000 00000000 00000000 00000000  
I/DEBUG   ( 4845):     7d83f1f0 00000000 00000000 00000000 00000000  
I/DEBUG   ( 4845):     7d83f200 00000000 00000000 78c17c30 79216b08  
I/DEBUG   ( 4845):     7d83f210 00000001 00000000 00000000 00000000  
I/DEBUG   ( 4845):     7d83f220 81ca6790 79926f38 00000000 7d5ff788  
I/DEBUG   ( 4845):     7d83f230 00000000 00000000 05000000 00000000  
I/DEBUG   ( 4845):     7d83f240 00000000 00000000 24000000 70747468  
I/DEBUG   ( 4845):     7d83f250 2f2f3a73 6d2e6e65 6b69772e 64657069  
I/DEBUG   ( 4845):     7d83f260 6f2e6169 772f6772 2f696b69 74737552  
I/DEBUG   ( 4845):     7d83f270 01000000 00000000 1b000000 6964654d  
I/DEBUG   ( 4845):     7d83f280 6b695761 646f4d69 53656c75 65726f74  
I/DEBUG   ( 4845):     7d83f290 776e653a 00696b69 00000000 00000000  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory near r9:
I/DEBUG   ( 4845):     795a0ce0 53626557 656b636f 74756174 736e696f  
I/DEBUG   ( 4845):     795a0cf0 746e6174 6f6f6d73 00006874 00000000  
I/DEBUG   ( 4845):     795a0d00 6d6f682f 6d6d2f65 61797461 6f4d2f73  
I/DEBUG   ( 4845):     795a0d10 6c6c697a 65732f61 2d6f7672 72646e61  
I/DEBUG   ( 4845):     795a0d20 2f64696f 76726573 61742f6f 74656772  
I/DEBUG   ( 4845):     795a0d30 6d72612f 6e696c2d 612d7875 6f72646e  
I/DEBUG   ( 4845):     795a0d40 61656469 642f6962 67756265 6975622f  
I/DEBUG   ( 4845):     795a0d50 732f646c 70697263 39342d74 35363330  
I/DEBUG   ( 4845):     795a0d60 63653732 64343332 6f2f3534 422f7475  
I/DEBUG   ( 4845):     795a0d70 69646e69 2f73676e 646e6957 6942776f  
I/DEBUG   ( 4845):     795a0d80 6e69646e 73722e67 61686562 726f6976  
I/DEBUG   ( 4845):     795a0d90 00000001 00000000 00000000 00000000  
I/DEBUG   ( 4845):     795a0da0 00000000 00000000 00000000 00000000  
I/DEBUG   ( 4845):     795a0db0 00000000 00000000 00000000 00000000  
I/DEBUG   ( 4845):     795a0dc0 7466656c 00706f74 00000000 00000000  
I/DEBUG   ( 4845):     795a0dd0 20746f4e 756f6e65 61206867 6d756772  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory near sl:
I/DEBUG   ( 4845):     00019dcc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019ddc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019dec ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019dfc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e0c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e1c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e2c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e3c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e4c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e5c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e6c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e7c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e8c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019e9c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019eac ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845):     00019ebc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory near sp:
I/DEBUG   ( 4845):     80ff71d0 00000000 00000000 00000000 00000001  
I/DEBUG   ( 4845):     80ff71e0 81ca6790 79926f38 7d83f1c0 7914d7f0  
I/DEBUG   ( 4845):     80ff71f0 80ff72ac 00000009 80ff71f4 791bfaf4  
I/DEBUG   ( 4845):     80ff7200 79926f18 00000001 00000000 00000000  
I/DEBUG   ( 4845):     80ff7210 80ff71f8 00000001 80ff7200 791c40b0  
I/DEBUG   ( 4845):     80ff7220 79926f88 00000001 00000000 00000000  
I/DEBUG   ( 4845):     80ff7230 80ff7218 00000001 81ca6790 79926f38  
I/DEBUG   ( 4845):     80ff7240 00000000 79117770 00000a40 00000000  
I/DEBUG   ( 4845):     80ff7250 7d89c280 7914d8e0 79838628 80ff7390  
I/DEBUG   ( 4845):     80ff7260 00000008 00000000 00000001 791c3368  
I/DEBUG   ( 4845):     80ff7270 80ff7d80 80ff7d80 89814010 89814010  
I/DEBUG   ( 4845):     80ff7280 80ff729c 83bac3c0 00000000 00000020  
I/DEBUG   ( 4845):     80ff7290 ffffff03 00000000 00000000 00000000  
I/DEBUG   ( 4845):     80ff72a0 00000000 7981db90 00000039 00000000  
I/DEBUG   ( 4845):     80ff72b0 00000000 00000000 00000000 80ff732c  
I/DEBUG   ( 4845):     80ff72c0 0000003e 0000001f 1d1d1d1d 7d89c280  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): code around pc:
I/DEBUG   ( 4845):     7914d7d0 e0830000 e28d3030 e8830007 e28d0028  
I/DEBUG   ( 4845):     7914d7e0 e58d0040 e58d1044 e28d0030 eb00009c  
I/DEBUG   ( 4845):     7914d7f0 e7ffdefe e1a06000 e3010d1d e3410d1d  
I/DEBUG   ( 4845):     7914d800 e1540000 0a00000c e5951000 e1a00004  
I/DEBUG   ( 4845):     7914d810 e12fff31 e5951004 e3510000 0a000006  
I/DEBUG   ( 4845):     7914d820 e5952008 e1a00004 eb007504 e1a00006  
I/DEBUG   ( 4845):     7914d830 eb023c37 eaffffff e1a06000 e1a00006  
I/DEBUG   ( 4845):     7914d840 eb023c33 008260f0 ff7d9d98 008260b0  
I/DEBUG   ( 4845):     7914d850 ffffc1ac fffb36e0 fffffe8c fffb3750  
I/DEBUG   ( 4845):     7914d860 e92d4800 e24dd028 e28dc010 e88c000f  
I/DEBUG   ( 4845):     7914d870 e59d0030 e28d1004 e58d0020 e59d0034  
I/DEBUG   ( 4845):     7914d880 e58d0024 e59d0038 e58d0004 e59d003c  
I/DEBUG   ( 4845):     7914d890 e58d0008 e59d0040 e58d000c e28d0010  
I/DEBUG   ( 4845):     7914d8a0 ebff2b46 e92d48f0 e5905000 e1a04002  
I/DEBUG   ( 4845):     7914d8b0 e1a06001 e1a01004 e1a00005 ebff1a99  
I/DEBUG   ( 4845):     7914d8c0 e3540000 0a000007 e5950000 e5957008  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): code around lr:
I/DEBUG   ( 4845):     7914dd78 e1a06002 e1a04000 e3550000 0a000011  
I/DEBUG   ( 4845):     7914dd88 e3a00002 e1a01006 e1a02005 eb024177  
I/DEBUG   ( 4845):     7914dd98 e3700001 1a000004 eb00248d e5900000  
I/DEBUG   ( 4845):     7914dda8 e3500004 0afffff5 ea00000e e3500000  
I/DEBUG   ( 4845):     7914ddb8 0a000012 e1550000 3a00001b e0455000  
I/DEBUG   ( 4845):     7914ddc8 e0866000 1affffed e59f0080 e59f1080  
I/DEBUG   ( 4845):     7914ddd8 e08f0000 e7b10000 e5840000 e9910003  
I/DEBUG   ( 4845):     7914dde8 e9840003 e8bd8070 e3a02001 e3a01000  
I/DEBUG   ( 4845):     7914ddf8 e5842000 e5841004 e5840008 e8bd8070  
I/DEBUG   ( 4845):     7914de08 e59f0038 e59f1038 e3a0301c e08f0000  
I/DEBUG   ( 4845):     7914de18 e0812000 e2840004 e3a0100e ebff414b  
I/DEBUG   ( 4845):     7914de28 e3a00001 e5840000 e8bd8070 e59f0014  
I/DEBUG   ( 4845):     7914de38 e59f1014 e08f0000 e7910000 eb011099  
I/DEBUG   ( 4845):     7914de48 00825a1c ffeaa268 008259f4 ffffc1f8  
I/DEBUG   ( 4845):     7914de58 00825a58 ffeaa0d8 e92d4010 e1a04000  
I/DEBUG   ( 4845):     7914de68 e1a01002 e3a00002 e1a02003 eb02413f  
I/DEBUG   ( 4845): 
I/DEBUG   ( 4845): memory map around fault addr 7914d7f0:
I/DEBUG   ( 4845):     76043000-7604c000 rw- 
I/DEBUG   ( 4845):     7604c000-7983a000 r-x /data/app-lib/com.mozilla.servo-1/libmain.so
I/DEBUG   ( 4845):     7983a000-7983b000 --- 
W/ActivityManager( 3210):   Force finishing activity com.mozilla.servo/.MainActivity
I/BootReceiver( 3210): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
D/dalvikvm( 3210): GC_FOR_ALLOC freed 1407K, 21% free 11280K/14236K, paused 38ms, total 38ms
W/InputDispatcher( 3210): channel '418e73e0 com.mozilla.servo/com.mozilla.servo.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 3210): channel '418e73e0 com.mozilla.servo/com.mozilla.servo.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/Zygote  ( 2853): Process 5164 terminated by signal (4)
W/InputDispatcher( 3210): Attempted to unregister already unregistered input channel '418e73e0 com.mozilla.servo/com.mozilla.servo.MainActivity (server)'
I/WindowState( 3210): WIN DEATH: Window{418e73e0 u0 com.mozilla.servo/com.mozilla.servo.MainActivity}
I/ActivityManager( 3210): Process com.mozilla.servo (pid 5164) has died.
D/mali_winsys( 3369): new_window_surface returns 0x3000
```

**Comment by jdm** [comment]
`D/RustAndroidGlueStdouterr( 5164): thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'arithmetic operation overflowed', /home/mmatyas/Mozilla/servo-android/servo/target/arm-linux-androideabi/debug/build/script-49036527ec234d45/out/Bindings/WindowBinding.rs:2624` is interesting. I wonder if this is another problem from `setTimeout`...

**Comment by jdm** [comment]
@mmatyas could you check the failing line, please?

**Comment by eefriedman** [comment]
Isn't this the same bug as #8484?  Should be fixed on master.

**Comment by jdm** [comment]
f078f8f is more recent than d4ce25d (ie. #8498) as far as I can tell.

**Comment by eefriedman** [comment]
Sure... but what the likelihood that someone found a new crash in exactly the same place on exactly the same page a few hours after the fix was committed?

**Comment by mmatyas** [comment]
Tried again with latest master, now it works correctly. I've probably forgot running `mach package`, sorry for the false alarm.
