### ISSUE TITLE
Servo panics ActiveTimers::schedule_internal_callback

### ISSUE THREAD

**Issue by mskrzypkows** [servo/servo#8583]
```./mach run -d http://google.com```
click on "Advertising" then:

```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: self.suspended_since.get().is_none()', /home/m.skrzypkows/Projects/servo/components/script/timers.rs:197
stack backtrace:
   1:     0x7f4dcad52520 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x7f4dcad54a75 - panicking::log_panic::_<closure>::closure.39180
   3:     0x7f4dcad544c1 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x7f4dcad41033 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x7f4dc8d4fd77 - sys_common::unwind::begin_unwind::begin_unwind::h17607704253381208013
                        at src/libstd/sys/common/unwind/mod.rs:214
   6:     0x7f4dc9608b6f - timers::_<impl>::schedule_internal_callback::h9c8f97cefe83ae6eNL1
                        at /home/m.skrzypkows/Projects/servo/components/servo/<std macros>:3
   7:     0x7f4dc9530ba6 - timers::_<impl>::set_timeout_or_interval::h5a32b6b3e6223cfd0I1
                        at /home/m.skrzypkows/Projects/servo/components/script/timers.rs:177
   8:     0x7f4dc917f28b - dom::window::_<impl>::SetTimeout::h22180ee1813ab0b34mU
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/window.rs:423
   9:     0x7f4dc917dfdf - dom::bindings::codegen::Bindings::WindowBinding::setTimeout::__rust_abi
                        at /home/m.skrzypkows/Projects/servo/target/debug/build/script-eb54dd315c30ddfb/out/Bindings/WindowBinding.rs:2692
  10:     0x7f4dc917cb78 - dom::bindings::codegen::Bindings::WindowBinding::setTimeout::h32897132f1a53744W47
  11:     0x7f4dca6c658d - CallJitMethodOp
  12:     0x7f4dc8e131e1 - dom::bindings::utils::generic_call::ha05569a2975928c07fg
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/bindings/utils.rs:715
  13:     0x7f4dc8e140b7 - dom::bindings::utils::generic_method::__rust_abi
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/bindings/utils.rs:723
  14:     0x7f4dc8e14072 - dom::bindings::utils::generic_method::hd4b734e46713ed6bJjg
  15:     0x7f4dca7e216c - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  16:     0x7f4dca7dd096 - _ZL9InterpretP9JSContextRN2js8RunStateE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  17:     0x7f4dca7e1e4c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  18:     0x7f4dca7e20cd - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  19:     0x7f4dcab1c938 - _ZN2js28CallOrConstructBoundFunctionEP9JSContextjPN2JS5ValueE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsfun.cpp:1588
  20:     0x7f4dca7e216c - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  21:     0x7f4dcab2a0d2 - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsfun.cpp:1311
  22:     0x7f4dca7e216c - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  23:     0x7f4dca7dd096 - _ZL9InterpretP9JSContextRN2js8RunStateE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  24:     0x7f4dca7e1e4c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  25:     0x7f4dca7e7f1f - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeENS_16AbstractFramePtrEPS9_
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:660
  26:     0x7f4dca7e9c2c - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:703
  27:     0x7f4dcaaab5d7 - _ZL8EvaluateP9JSContextN2JS6HandleIP8JSObjectEERKNS1_22ReadOnlyCompileOptionsERNS1_18SourceBufferHolderENS1_13MutableHandleINS1_5ValueEEE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4184
  28:     0x7f4dcaaab8bf - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4218
                        at /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4272
  29:     0x7f4dc8dfb64b - dom::window::_<impl>::evaluate_script_on_global_with_result::h16384748139566496794
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/window.rs:776
  30:     0x7f4dc92dd80d - dom::htmlscriptelement::_<impl>::execute::h4123a212af77a6720KE
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/htmlscriptelement.rs:437
  31:     0x7f4dc92d8645 - dom::document::_<impl>::process_asap_scripts::h156ea92bb01e8f2dEfp
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/document.rs:1274
  32:     0x7f4dc92d7a09 - dom::document::_<impl>::finish_load::h03b59666201fe6cfWbp
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/document.rs:1176
  33:     0x7f4dc941462f - dom::htmlscriptelement::_<impl>::response_complete::hfb0308b34c4837c9IyE
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/htmlscriptelement.rs:161
  34:     0x7f4dc9d71649 - _<impl>::process::ha3b655c2162ed808hzg
                        at /home/m.skrzypkows/Projects/servo/components/net_traits/lib.rs:193
  35:     0x7f4dc941b4c5 - network_listener::_<impl>::handler::h9652396288195299859
                        at /home/m.skrzypkows/Projects/servo/components/script/network_listener.rs:48
  36:     0x7f4dc95ab335 - script_task::_<impl>::handle_msg_from_script::hd095a11c102f95e1dFZ
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:1016
  37:     0x7f4dc95e0572 - script_task::_<impl>::handle_msgs::_<closure>::closure.156316
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:872
  38:     0x7f4dc95e0166 - script_task::_<impl>::profile_event::h689621730158922347
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:951
  39:     0x7f4dc95b3b0f - script_task::_<impl>::handle_msgs::h19e507a16499493eUpZ
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:864
  40:     0x7f4dc95a8550 - script_task::_<impl>::start::h6288a89a07ae9e76KpZ
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:724
  41:     0x7f4dc95a851c - script_task::_<impl>::create::_<closure>::_<closure>::closure.155853
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:526
  42:     0x7f4dc95a8254 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h14659827028526741455
                        at /home/m.skrzypkows/Projects/servo/components/profile_traits/mem.rs:60
  43:     0x7f4dc9599c0b - script_task::_<impl>::create::_<closure>::closure.155443
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:525
  44:     0x7f4dc9599267 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.155436
                        at /home/m.skrzypkows/Projects/servo/components/util/task.rs:29
  45:     0x7f4dc95991b7 - boxed::_<impl>::call_box::call_box::h919813389440421609
                        at src/liballoc/boxed.rs:516
  46:     0x7f4dc8d6ee1b - boxed::_<impl>::call_once::call_once::h6886689581083695599
                        at src/liballoc/boxed.rs:532
  47:     0x7f4dc8d6ea0d - std::thread::_<impl>::spawn_inner::_<closure>::_<closure>::closure.116126
                        at src/libstd/thread/mod.rs:280
  48:     0x7f4dc8d6e9b9 - sys_common::unwind::try::try_fn::try_fn::h4429261825785939250
                        at src/libstd/sys/common/unwind/mod.rs:146
  49:     0x7f4dcad51a58 - __rust_try
  50:     0x7f4dcad4e02b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  51:     0x7f4dc8d6e923 - sys_common::unwind::try::try::h17589937110400405109
                        at src/libstd/sys/common/unwind/mod.rs:116
  52:     0x7f4dc8d6e7b8 - std::thread::_<impl>::spawn_inner::_<closure>::closure.116103
                        at src/libstd/thread/mod.rs:280
  53:     0x7f4dc8d6f02c - boxed::_<impl>::call_box::call_box::h15642958903800657454
                        at src/liballoc/boxed.rs:516
  54:     0x7f4dcad53563 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  55:     0x7f4dc56dd181 - start_thread
  56:     0x7f4dc5ef747c - __clone
  57:                0x0 - <unknown>
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: *self.stack == mem::transmute(&*self)', /home/m.skrzypkows/Projects/servo/.cargo/git/checkouts/rust-mozjs-ebb4917e843c0a11/master/src/rust.rs:333
stack backtrace:
   1:     0x7f4dcad52520 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x7f4dcad54a75 - panicking::log_panic::_<closure>::closure.39180
   3:     0x7f4dcad544c1 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x7f4dcad40f58 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x7f4dc8d4fd77 - sys_common::unwind::begin_unwind::begin_unwind::h17607704253381208013
                        at src/libstd/sys/common/unwind/mod.rs:214
   6:     0x7f4dc8d952f0 - rust::_<impl>::drop::drop::h13005611520994692504
                        at /home/m.skrzypkows/Projects/servo/components/servo/<std macros>:3
   7:     0x7f4dc8d9524c - js..jsapi_linux_64..Rooted<js..jsapi_linux_64..Value>::drop.117329::h3e94843b001ad038
   8:     0x7f4dc92dd6a9 - dom::htmlscriptelement::_<impl>::execute::h4123a212af77a6720KE
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/htmlscriptelement.rs:463
   9:     0x7f4dc92d8645 - dom::document::_<impl>::process_asap_scripts::h156ea92bb01e8f2dEfp
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/document.rs:1274
  10:     0x7f4dc92d7a09 - dom::document::_<impl>::finish_load::h03b59666201fe6cfWbp
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/document.rs:1176
  11:     0x7f4dc941462f - dom::htmlscriptelement::_<impl>::response_complete::hfb0308b34c4837c9IyE
                        at /home/m.skrzypkows/Projects/servo/components/script/dom/htmlscriptelement.rs:161
  12:     0x7f4dc9d71649 - _<impl>::process::ha3b655c2162ed808hzg
                        at /home/m.skrzypkows/Projects/servo/components/net_traits/lib.rs:193
  13:     0x7f4dc941b4c5 - network_listener::_<impl>::handler::h9652396288195299859
                        at /home/m.skrzypkows/Projects/servo/components/script/network_listener.rs:48
  14:     0x7f4dc95ab335 - script_task::_<impl>::handle_msg_from_script::hd095a11c102f95e1dFZ
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:1016
  15:     0x7f4dc95e0572 - script_task::_<impl>::handle_msgs::_<closure>::closure.156316
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:872
  16:     0x7f4dc95e0166 - script_task::_<impl>::profile_event::h689621730158922347
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:951
  17:     0x7f4dc95b3b0f - script_task::_<impl>::handle_msgs::h19e507a16499493eUpZ
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:864
  18:     0x7f4dc95a8550 - script_task::_<impl>::start::h6288a89a07ae9e76KpZ
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:724
  19:     0x7f4dc95a851c - script_task::_<impl>::create::_<closure>::_<closure>::closure.155853
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:526
  20:     0x7f4dc95a8254 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h14659827028526741455
                        at /home/m.skrzypkows/Projects/servo/components/profile_traits/mem.rs:60
  21:     0x7f4dc9599c0b - script_task::_<impl>::create::_<closure>::closure.155443
                        at /home/m.skrzypkows/Projects/servo/components/script/script_task.rs:525
  22:     0x7f4dc9599267 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.155436
                        at /home/m.skrzypkows/Projects/servo/components/util/task.rs:29
  23:     0x7f4dc95991b7 - boxed::_<impl>::call_box::call_box::h919813389440421609
                        at src/liballoc/boxed.rs:516
  24:     0x7f4dc8d6ee1b - boxed::_<impl>::call_once::call_once::h6886689581083695599
                        at src/liballoc/boxed.rs:532
  25:     0x7f4dc8d6ea0d - std::thread::_<impl>::spawn_inner::_<closure>::_<closure>::closure.116126
                        at src/libstd/thread/mod.rs:280
  26:     0x7f4dc8d6e9b9 - sys_common::unwind::try::try_fn::try_fn::h4429261825785939250
                        at src/libstd/sys/common/unwind/mod.rs:146
  27:     0x7f4dcad51a58 - __rust_try
  28:     0x7f4dcad4e02b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  29:     0x7f4dc8d6e923 - sys_common::unwind::try::try::h17589937110400405109
                        at src/libstd/sys/common/unwind/mod.rs:116
  30:     0x7f4dc8d6e7b8 - std::thread::_<impl>::spawn_inner::_<closure>::closure.116103
                        at src/libstd/thread/mod.rs:280
  31:     0x7f4dc8d6f02c - boxed::_<impl>::call_box::call_box::h15642958903800657454
                        at src/liballoc/boxed.rs:516
  32:     0x7f4dcad53563 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  33:     0x7f4dc56dd181 - start_thread
  34:     0x7f4dc5ef747c - __clone
  35:                0x0 - <unknown>
thread panicked while panicking. aborting.Servo exited with return value -4
```

**Comment by jdm** [comment]
cc @benschulz
