### ISSUE TITLE
Intermittent Result::unwrap panic in /dom/nodes/Document-createElement-namespace.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#8614]
This is a regression from the e10s changes; I've seen panics like this as a result of `ipc::channel().unwrap()` before.

```
  ▶ CRASH [expected OK] /dom/nodes/Document-createElement-namespace.html
  │ 
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:736
  │ stack backtrace:
  │    1:     0x7f70684aa130 - <unknown>
  │    2:     0x7f70684ace75 - <unknown>
  │    3:     0x7f70684ac8c1 - <unknown>
  │    4:     0x7f7068496573 - <unknown>
  │    5:     0x7f7068496c28 - <unknown>
  │    6:     0x7f70684a9801 - <unknown>
  │    7:     0x7f70684da82f - <unknown>
  │    8:     0x7f7066ee30a7 - <unknown>
  │    9:     0x7f7066e74942 - <unknown>
  │   10:     0x7f7066e5dbd7 - <unknown>
  │   11:     0x7f7066e5cfd4 - <unknown>
  │   12:     0x7f70684a9668 - <unknown>
  │   13:     0x7f70684a5c3b - <unknown>
  │   14:     0x7f7066e5d164 - <unknown>
  │   15:     0x7f70684ab963 - <unknown>
  │   16:     0x7f70644c1181 - <unknown>
  │   17:     0x7f7064cdb47c - <unknown>
  │   18:                0x0 - <unknown>
  │ thread 'Constellation' panicked at 'assertion failed: libc::close(self.fd) == 0', /home/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:101
  │ stack backtrace:
  │    1:     0x7f70684aa130 - <unknown>
  │    2:     0x7f70684ace75 - <unknown>
  │    3:     0x7f70684ac8c1 - <unknown>
  │    4:     0x7f7068496498 - <unknown>
  │    5:     0x7f7067ba905f - <unknown>
  │    6:     0x7f7067ba2695 - <unknown>
  │    7:     0x7f7066e991e7 - <unknown>
  │    8:     0x7f7066ee3216 - <unknown>
  │    9:     0x7f7066e74942 - <unknown>
  │   10:     0x7f7066e5dbd7 - <unknown>
  │   11:     0x7f7066e5cfd4 - <unknown>
  │   12:     0x7f70684a9668 - <unknown>
  │   13:     0x7f70684a5c3b - <unknown>
  │   14:     0x7f7066e5d164 - <unknown>
  │   15:     0x7f70684ab963 - <unknown>
  │   16:     0x7f70644c1181 - <unknown>
  │   17:     0x7f7064cdb47c - <unknown>
  │   18:                0x0 - <unknown>
  └ thread panicked while panicking. aborting.
```

**Comment by SimonSapin** [comment]
This one seems particularly bad. (It fails more often than not.) Should we disable it?

**Comment by jdm** [comment]
We did in #8636.

**Comment by SimonSapin** [comment]
Should this be closed, or is it also used to track fixing the underlying issue?

**Comment by jdm** [comment]
I prefer to leave these open when the failing test is merely disabled.

**Comment by mrobinson** [comment]
I don't think we've seen this one and the test is no longer disabled.
