### ISSUE TITLE
Panic loading WebGL demo (under gl_context::init_offscreen)

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#8741]
Loading https://developer.mozilla.org/en-US/demos/detail/escher-puzzle/launch gives 

```
thread 'Constellation' panicked at 'assertion failed: gl::CheckFramebufferStatus(gl::FRAMEBUFFER) == gl::FRAMEBUFFER_COMPLETE', /Users/dzbarsky/mozilla/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/draw_buffer.rs:127
stack backtrace:
   1:        0x106919268 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10691b3af - panicking::log_panic::_<closure>::closure.40650
   3:        0x10691ae52 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x106906376 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x105d7c487 - sys_common::unwind::begin_unwind::begin_unwind::h4577851792254705744
   6:        0x105d7f85d - draw_buffer::_<impl>::new::ha97679c418c0c1263ta
   7:        0x105d7f14f - gl_context::_<impl>::create_draw_buffer::h0d32c7e170322c4cLqa
   8:        0x105d7ed14 - gl_context::_<impl>::init_offscreen::hcfd5f7badbf5ba4djpa
   9:        0x105d7eaa2 - gl_context::_<impl>::create_offscreen_with_color_attachment::h78afbeb7754ea65bska
  10:        0x1055ed654 - webgl_paint_task::_<impl>::new::h99ef29ac923bb581n8r
  11:        0x1055f273b - webgl_paint_task::_<impl>::start::h80653973f16dc8f17fs
  12:        0x1041f6d94 - constellation::_<impl>::handle_create_webgl_paint_task_msg::handle_create_webgl_paint_task_msg::h1473660829368543315
  13:        0x1040b4e02 - constellation::_<impl>::handle_request::handle_request::h18088209805845238262
  14:        0x1040afadc - constellation::_<impl>::run::run::h12837117060153743775
  15:        0x1040946d0 - export::compositing::constellation::_<impl>::start::_<closure>::closure.23370
  16:        0x1040929a3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.23359
  17:        0x104092918 - sys_common::unwind::try::try_fn::try_fn::h5957481253924694995
  18:        0x1069186a8 - __rust_try
  19:        0x1069157de - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  20:        0x104092855 - sys_common::unwind::try::try::h1961186302386097648
  21:        0x10409268e - std::thread::_<impl>::spawn::_<closure>::closure.23336
  22:        0x104094977 - boxed::_<impl>::call_box::call_box::h7279820229102645014
  23:        0x10691a63d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  24:     0x7fff91f03267 - _pthread_body
  25:     0x7fff91f031e4 - _pthread_start
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) }', ../src/libcore/result.rs:741
stack backtrace:
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
   1:        0x106919268 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10691b3af - panicking::log_panic::_<closure>::closure.40650
   3:        0x10691ae52 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x106906376 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10690675e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x106918887 - rust_begin_unwind
   7:        0x10693da10 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x105182966 - result::_<impl>::unwrap::unwrap::h11997013171818143171
   9:        0x1051820a5 - dom::webglrenderingcontext::_<impl>::new_inherited::hdf705f369d8857acpGR
  10:        0x105033ac8 - dom::webglrenderingcontext::_<impl>::new::hf1c887604c473afdLHR
  11:        0x105033697 - dom::htmlcanvaselement::_<impl>::get_or_init_webgl_context::hfb95fad8eec05e7ajUx
  12:        0x104c176c7 - dom::htmlcanvaselement::_<impl>::GetContext::h731e03f2560ab348L0x
  13:        0x104c16a30 - dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::getContext::__rust_abi
  14:        0x104c165b8 - dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::getContext::hcae57ceae7da528684Z
  15:        0x105f01e10 - CallJitMethodOp
  16:        0x104a8464d - dom::bindings::utils::generic_call::hca84ed24318ec437F8f
  17:        0x104a85537 - dom::bindings::utils::generic_method::__rust_abi
  18:        0x104a854f2 - dom::bindings::utils::generic_method::h67c7ada8fc990d99hcg
  19:        0x1061d5b64 - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  20:        0x1061e60c9 - _ZL9InterpretP9JSContextRN2js8RunStateE
  21:        0x1061dd399 - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  22:        0x1061eb856 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeENS_16AbstractFramePtrEPS9_
  23:        0x1061eb983 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  24:        0x1064ef762 - _ZL8EvaluateP9JSContextN2JS6HandleIP8JSObjectEERKNS1_22ReadOnlyCompileOptionsERNS1_18SourceBufferHolderENS1_13MutableHandleINS1_5ValueEEE
  25:        0x1064ef8ca - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
  26:        0x104a6c3fb - dom::window::_<impl>::evaluate_script_on_global_with_result::h14145736670694473067
  27:        0x104f5e305 - dom::htmlscriptelement::_<impl>::execute::h386c4e2c944356bfxKE
  28:        0x104f59286 - dom::document::_<impl>::maybe_execute_parser_blocking_script::h87cb5318066090ca7sp
  29:        0x104f583d6 - dom::document::_<impl>::finish_load::hb5ea679a7589bf46lrp
  30:        0x10509cc02 - dom::htmlscriptelement::_<impl>::response_complete::hc66c47278f8ac46eoyE
  31:        0x105a5db6f - _<impl>::process::hd87fab3645e12ef3psd
  32:        0x1050a3bb5 - network_listener::_<impl>::handler::h17686884591536265052
  33:        0x10524bc25 - script_task::_<impl>::handle_msg_from_script::h85804b4668de7449ECZ
  34:        0x1052cb01f - script_task::_<impl>::handle_msgs::_<closure>::closure.160913
  35:        0x1052caba2 - script_task::_<impl>::profile_event::h12494853204083835938
  36:        0x10529d6e9 - script_task::_<impl>::handle_msgs::h1f65535c2cddde2dIoZ
  37:        0x1052482c0 - script_task::_<impl>::start::h9688a8d9c59325aayoZ
  38:        0x105248274 - script_task::_<impl>::create::_<closure>::_<closure>::closure.159627
  39:        0x105247fe0 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h16543033206473658831
  40:        0x10523266f - script_task::_<impl>::create::_<closure>::closure.159005
  41:        0x105231a47 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.158992
  42:        0x105231433 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.158981
  43:        0x1052313a8 - sys_common::unwind::try::try_fn::try_fn::h12933991938220953887
  44:        0x1069186a8 - __rust_try
  45:        0x1069157de - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  46:        0x1052312e5 - sys_common::unwind::try::try::h9028235336497681879
  47:        0x10523111e - std::thread::_<impl>::spawn::_<closure>::closure.158978
  48:        0x105231c67 - boxed::_<impl>::call_box::call_box::h14696440856148069552
  49:        0x10691a63d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  50:     0x7fff91f03267 - _pthread_body
  51:     0x7fff91f031e4 - _pthread_start
stack backtrace:
   1:        0x106919268 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }' panicked at 'assertion failed: *self.stack == mem::transmute(&*self)', /Users/dzbarsky/mozilla/servo/.cargo/git/checkouts/rust-mozjs-ebb4917e843c0a11/master/src/rust.rs:333
   2:        0x10691b3af - panicking::log_panic::_<closure>::closure.40650
   3:        0x10691ae52 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x106906376 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10690675e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x106918887 - rust_begin_unwind
   7:        0x10693da10 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x104486309 - result::_<impl>::unwrap::unwrap::h1641706367431377465
   9:        0x1044668d6 - layout_task::_<impl>::handle_request::h67f7bc42bf91d647Kvq
  10:        0x10443325a - layout_task::_<impl>::start::hff0faeca0a3784100tq
  11:        0x1044330a7 - layout_task::_<impl>::create::_<closure>::_<closure>::closure.54941
  12:        0x10442d273 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h11079037392261494604
  13:        0x1043f7c00 - layout_task::_<impl>::create::_<closure>::closure.53232
  14:        0x1043f7007 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.53203
  15:        0x1043f69f3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.53192
  16:        0x1043f6968 - sys_common::unwind::try::try_fn::try_fn::h10438394186501004320
  17:        0x1069186a8 - __rust_try
  18:        0x1069157de - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  19:        0x1043f68a5 - sys_common::unwind::try::try::h11529942122215515108
  20:        0x1043f66de - std::thread::_<impl>::spawn::_<closure>::closure.53169
  21:        0x1043f7267 - boxed::_<impl>::call_box::call_box::h7224337311175617868
  22:        0x10691a63d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  23:     0x7fff91f03267 - _pthread_body
  24:     0x7fff91f031e4 - _pthread_start
stack backtrace:
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741thread '
thread 'LayoutWorker worker 1/6LayoutWorker worker 2/6' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'called `Result::unwrap()` on an `Err` value: RecvError', LayoutWorker worker 3/6', ../src/libcore/result.rs' panicked at '../src/libcore/result.rs:called `Result::unwrap()` on an `Err` value: RecvError:741', thread '../src/libcore/result.rs741
thread ':
LayoutWorker worker 5/6LayoutWorker worker 4/6741' panicked at '' panicked at '
called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ', ../src/libcore/result.rs../src/libcore/result.rs::741741

thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
   1:        0x106919268 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10691b3af - panicking::log_panic::_<closure>::closure.40650
   3:        0x10691ae52 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x106906274 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x1049b3f57 - sys_common::unwind::begin_unwind::begin_unwind::h11551657464333290030
   6:        0x104a078e0 - rust::_<impl>::drop::drop::h857102223996393456
   7:        0x104a0783c - js..jsapi_macos_64..Rooted<js..jsapi_macos_64..Value>::drop.120618::h98cdcc39fcaff7b6
   8:        0x104f5e1a1 - dom::htmlscriptelement::_<impl>::execute::h386c4e2c944356bfxKE
   9:        0x104f59286 - dom::document::_<impl>::maybe_execute_parser_blocking_script::h87cb5318066090ca7sp
  10:        0x104f583d6 - dom::document::_<impl>::finish_load::hb5ea679a7589bf46lrp
  11:        0x10509cc02 - dom::htmlscriptelement::_<impl>::response_complete::hc66c47278f8ac46eoyE
  12:        0x105a5db6f - _<impl>::process::hd87fab3645e12ef3psd
  13:        0x1050a3bb5 - network_listener::_<impl>::handler::h17686884591536265052
  14:        0x10524bc25 - script_task::_<impl>::handle_msg_from_script::h85804b4668de7449ECZ
  15:        0x1052cb01f - script_task::_<impl>::handle_msgs::_<closure>::closure.160913
  16:        0x1052caba2 - script_task::_<impl>::profile_event::h12494853204083835938
  17:        0x10529d6e9 - script_task::_<impl>::handle_msgs::h1f65535c2cddde2dIoZ
  18:        0x1052482c0 - script_task::_<impl>::start::h9688a8d9c59325aayoZ
  19:        0x105248274 - script_task::_<impl>::create::_<closure>::_<closure>::closure.159627
  20:        0x105247fe0 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h16543033206473658831
  21:        0x10523266f - script_task::_<impl>::create::_<closure>::closure.159005
  22:        0x105231a47 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.158992
  23:        0x105231433 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.158981
  24:        0x1052313a8 - sys_common::unwind::try::try_fn::try_fn::h12933991938220953887
  25:        0x1069186a8 - __rust_try
  26:        0x1069157de - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  27:        0x1052312e5 - sys_common::unwind::try::try::h9028235336497681879
  28:        0x10523111e - std::thread::_<impl>::spawn::_<closure>::closure.158978
  29:        0x105231c67 - boxed::_<impl>::call_box::call_box::h14696440856148069552
  30:        0x10691a63d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  31:     0x7fff91f03267 - _pthread_body
  32:     0x7fff91f031e4 - _pthread_start
thread panicked while panicking. aborting.stack backtrace:
Servo exited with return value -4
```

**Comment by jdm** [comment]
cc @ecoal95

**Comment by ecoal95** [comment]
@dzbarsky what platform are you on? I couldn't replicate on linux, I get the following output with current HEAD:

```
➜  servo git:(master) ./mach run -d https://developer.mozilla.org/en-US/demos/detail/escher-puzzle/launch
ERROR:js::rust: Error at https://developer.cdn.mozilla.net/static/build/js/main.a5c87b3a3ad2.js:4:8570: win.mdn is undefined

THREE.WebGLRenderer
71
THREE.WebGLRenderer: OES_texture_float extension not supported.
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
THREE.WebGLRenderer: OES_texture_half_float extension not supported.
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
THREE.WebGLRenderer: OES_standard_derivatives extension not supported.
THREE.WebGLRenderer: OES_element_index_uint extension not supported.
THREE.WebGLShader: Shader couldn't compile.
THREE.WebGLShader: gl.getShaderInfoLog()
ERROR: 0:1: 'highp' : precision is not supported in fragment shader 
ERROR: 0:2: 'highp' : precision is not supported in fragment shader 

1: precision highp float;
2: precision highp int;
[ommited]
941: 	gl_FragColor = vec4( outgoingLight, diffuseColor.a );
942: }
ERROR:js::rust: Error at https://developer.cdn.mozilla.net/media/uploads/demos/m/i/micahbolen/9454c6422543e80c4aea293577cdb3b0/escher-puzzle_1439967656_demo_package/js/three.js:24553:23: _gl.getProgramInfoLog is not a function

THREE.WebGLShader: Shader couldn't compile.
THREE.WebGLShader: gl.getShaderInfoLog()
ERROR: 0:1: 'highp' : precision is not supported in fragment shader 
ERROR: 0:2: 'highp' : precision is not supported in fragment shader 

1: precision highp float;
2: precision highp int;
[ommitted]
941: 	gl_FragColor = vec4( outgoingLight, diffuseColor.a );
942: }
ERROR:js::rust: Error at https://developer.cdn.mozilla.net/media/uploads/demos/m/i/micahbolen/9454c6422543e80c4aea293577cdb3b0/escher-puzzle_1439967656_demo_package/js/three.js:24553:23: _gl.getProgramInfoLog is not a function
```

**Comment by dzbarsky** [comment]
OSX Yosemite,
MacBook Pro (15-inch, Late 2011)
Graphics: AMD Radeon HD 6770M 1024 MB

**Comment by dzbarsky** [comment]
@ecoal95 I also see a panic at http://people.mozilla.org/\~sicking/webgl/ray.html. Maybe you can reproduce this one?

**Comment by simartin** [comment]
I can reproduce the initial case on my end
```
$ uname -a
Darwin Simons-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

The latest reported case is a different issue, that I'll open a separate ticket for.

**Comment by nox** [comment]
I can't reproduce this anymore.
