### ISSUE TITLE
Tiling panic

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8758]
No STR:

```
thread '<main>' panicked at 'assertion failed: vertex_cs.w > 0.0', /Users/paul/git/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/util.rs:137
stack backtrace:
   1:        0x11187aa48 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x11187cb8f - panicking::log_panic::_<closure>::closure.40650
   3:        0x11187c632 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x111867b26 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x110f2d9b7 - sys_common::unwind::begin_unwind::begin_unwind::h513874831113306267
   6:        0x110f3a209 - util::project_rect_to_screen::h06a2f4be3bc0216epWb
   7:        0x110f39538 - tiling::_<impl>::tile_intersects_rect::h35ffab85fd9de115zFb
   8:        0x110f3a6ff - tiling::_<impl>::mark_tiles_outside_of_rect_as_unused::he1bc60dabc0e3d8dKGb
   9:        0x110f44c4e - tiling::_<impl>::get_buffer_requests_in_rect::h7ad5e718347a54bbgJb
  10:        0x10ef844eb - layers::_<impl>::get_buffer_requests::get_buffer_requests::h10880478265195574143
  11:        0x10ef83909 - scene::_<impl>::get_buffer_requests_for_layer::get_buffer_requests_for_layer::h123908615902698855
  12:        0x10ef840c1 - scene::_<impl>::get_buffer_requests_for_layer::get_buffer_requests_for_layer::h123908615902698855
  13:        0x10ef840c1 - scene::_<impl>::get_buffer_requests_for_layer::get_buffer_requests_for_layer::h123908615902698855
  14:        0x10ef840c1 - scene::_<impl>::get_buffer_requests_for_layer::get_buffer_requests_for_layer::h123908615902698855
  15:        0x10ef840c1 - scene::_<impl>::get_buffer_requests_for_layer::get_buffer_requests_for_layer::h123908615902698855
  16:        0x10ef840c1 - scene::_<impl>::get_buffer_requests_for_layer::get_buffer_requests_for_layer::h123908615902698855
  17:        0x10ef8372b - scene::_<impl>::get_buffer_requests::get_buffer_requests::h12367030385042003188
  18:        0x10ef80f1e - compositor::_<impl>::send_buffer_requests_for_all_layers::send_buffer_requests_for_all_layers::h8651757014556937276
  19:        0x10ef1e114 - compositor::_<impl>::handle_browser_message::handle_browser_message::h13223401781791887956
  20:        0x10ef1bab2 - compositor::_<impl>::handle_events::handle_events::h14489177529748836225
  21:        0x10efe05b8 - _<impl>::handle_events::h9052d252db0945f7Tda
  22:        0x10eee003c - main::hb77cfbfb032d8741Laa
  23:        0x11187c3b2 - sys_common::unwind::try::try_fn::h15039379299886391
  24:        0x111879e88 - __rust_try
  25:        0x11187c259 - rt::lang_start::hb609b9e4718008c7Uxx
  26:        0x10efd3099 - main
```

**Comment by paulrouget** [comment]
I cant' reproduce anymore.

@gordonbrander is it still happening to you?

**Comment by gordonbrander** [comment]
@paulrouget it took more time, but I was able to reproduce. This was after clicking a link:

```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
stack backtrace:
[object Object]
[object Object]
[object Object]
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x1119432cc - panicking::panic::hbe2e3a5159c3d178iEK
   9:        0x110322bc2 - option::_<impl>::unwrap::unwrap::h8240992818544208912
  10:        0x1101f7144 - script_task::_<impl>::root_page::hd5dc72f81c3916a5NO2
  11:        0x110327107 - script_task::_<impl>::handle_event::h539bbd1736caf108iQ3
  12:        0x1103540d5 - script_task::_<impl>::handle_msg_from_constellation::hfecffd5c9226bbc7D02
  13:        0x110352a91 - script_task::_<impl>::handle_msgs::_<closure>::closure.162594
  14:        0x110352682 - script_task::_<impl>::profile_event::h14717905755339109898
[object Object]
[object Object]
[object Object]
  15:        0x1103252bd - script_task::_<impl>::handle_msgs::h8c8659d87f8d3579LP2
  16:        0x1102ce750 - script_task::_<impl>::start::h5f499036547dcbd9BP2
  17:        0x1102ce704 - script_task::_<impl>::create::_<closure>::_<closure>::closure.161304
  18:        0x1102ce470 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h7244890294817420583
  19:        0x1102b8acf - script_task::_<impl>::create::_<closure>::closure.160682
  20:        0x1102b7ea7 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.160669
  21:        0x1102b7893 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.160658
  22:        0x1102b7808 - sys_common::unwind::try::try_fn::try_fn::h14924432134403572301
  23:        0x11191dce8 - __rust_try
  24:        0x11191adee - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  25:        0x1102b7745 - sys_common::unwind::try::try::h14691589896679170832
  26:        0x1102b757e - std::thread::_<impl>::spawn::_<closure>::closure.160655
  27:        0x1102b80c7 - boxed::_<impl>::call_box::call_box::h7728668965161310799
[object Object]
[object Object]
[object Object]
  28:        0x11191fbfd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  29:     0x7fff8f808059 - _pthread_body
  30:     0x7fff8f807fd6 - _pthread_start
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
stack backtrace:
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741thread '
LayoutTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', ../src/libcore/result.rs:741
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x10f160aff - option::_<impl>::expect::expect::h9588151852895437660
   9:        0x10f2271c8 - constellation::_<impl>::handle_failure_msg::handle_failure_msg::h2834703002492497736
  10:        0x10f0eed42 - constellation::_<impl>::handle_request::handle_request::h5688585175130277185
  11:        0x10f0ebadc - constellation::_<impl>::run::run::h17242540213491243687
[object Object]
[object Object]
[object Object]
  12:        0x10f0d0630 - export::compositing::constellation::_<impl>::start::_<closure>::closure.23553
  13:        0x10f0ce903 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.23542
  14:        0x10f0ce878 - sys_common::unwind::try::try_fn::try_fn::h11372735546248349120
  15:        0x11191dce8 - __rust_try
  16:        0x11191adee - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  17:        0x10f0ce7b5 - sys_common::unwind::try::try::h3551860486257248819
  18:        0x10f0ce5ee - std::thread::_<impl>::spawn::_<closure>::closure.23519
  19:        0x10f0d08d7 - boxed::_<impl>::call_box::call_box::h2057553694708904740
  20:        0x11191fbfd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  21:     0x7fff8f808059 - _pthread_body
  22:     0x7fff8f807fd6 - _pthread_start
stack backtrace:
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x11050d206 - result::_<impl>::unwrap::unwrap::h2771201841968978469
   9:        0x11057d38e - gfx::paint_task::_<impl>::create::_<closure>::closure.32524
  10:        0x11057c577 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.32495
  11:        0x11057bf63 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.32484
  12:        0x11057bed8 - sys_common::unwind::try::try_fn::try_fn::h9283666893292663702
  13:        0x11191dce8 - __rust_try
  14:        0x11191adee - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  15:        0x11057be15 - sys_common::unwind::try::try::h4604334351589468113
  16:        0x11057bc4e - std::thread::_<impl>::spawn::_<closure>::closure.32461
  17:        0x11057c7d7 - boxed::_<impl>::call_box::call_box::h14547268701459004310
  18:        0x11191fbfd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  19:     0x7fff8f808059 - _pthread_body
  20:     0x7fff8f807fd6 - _pthread_start
stack backtrace:
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x10f6481b6 - result::_<impl>::unwrap::unwrap::h11170890287382796421
   9:        0x10f881c5b - layout_task::_<impl>::exit_now::h5a63b02eee361d13YLq
  10:        0x10f852b52 - layout_task::_<impl>::handle_request_helper::h931dc612a9a8a34amBq
  11:        0x10f829f5b - layout_task::_<impl>::handle_request::h7b0899414c669fcfMvq
  12:        0x10f7f636a - layout_task::_<impl>::start::hb5f4977bc025c11d2tq
  13:        0x10f7f61b7 - layout_task::_<impl>::create::_<closure>::_<closure>::closure.55462
  14:        0x10f7f0383 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h5244211801073323039
  15:        0x10f7bad00 - layout_task::_<impl>::create::_<closure>::closure.53753
  16:        0x10f7ba107 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.53724
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:741
  17:        0x10f7b9af3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.53713
  18:        0x10f7b9a68 - sys_common::unwind::try::try_fn::try_fn::h3346737908274401483
  19:        0x11191dce8 - __rust_try
  20:        0x11191adee - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  21:        0x10f7b99a5 - sys_common::unwind::try::try::h5873060135202733099
  22:        0x10f7b97de - std::thread::_<impl>::spawn::_<closure>::closure.53690
  23:        0x10f7ba367 - boxed::_<impl>::call_box::call_box::h3141961925543327181
  24:        0x11191fbfd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  25:     0x7fff8f808059 - _pthread_body
  26:     0x7fff8f807fd6 - _pthread_start
stack backtrace:
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x10ef1f98e - result::_<impl>::unwrap::unwrap::h6206053853890979455
   9:        0x10ef99a67 - compositor::_<impl>::update_subpage_size_if_necessary::update_subpage_size_if_necessary::h12692692784544764823
  10:        0x10ef95b8a - compositor::_<impl>::create_or_update_descendant_layer::create_or_update_descendant_layer::h12788451195021287847
  11:        0x10ef2456c - compositor::_<impl>::handle_browser_message::handle_browser_message::h424872536862062028
  12:        0x10ef21f22 - compositor::_<impl>::handle_events::handle_events::h9910740313028280841
  13:        0x10f068888 - _<impl>::handle_events::h1169c8c565313f92Tda
  14:        0x10eee612c - main::hb77cfbfb032d8741Laa
  15:        0x111920192 - sys_common::unwind::try::try_fn::h9781900235654175042
  16:        0x11191dce8 - __rust_try
  17:        0x111920039 - rt::lang_start::h7f8cb47bb0ba3293PBx
  18:        0x10efd9529 - main
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
stack backtrace:
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x10f849419 - result::_<impl>::unwrap::unwrap::h8987826244185417907
   9:        0x10f8299e6 - layout_task::_<impl>::handle_request::h7b0899414c669fcfMvq
  10:        0x10f7f636a - layout_task::_<impl>::start::hb5f4977bc025c11d2tq
  11:        0x10f7f61b7 - layout_task::_<impl>::create::_<closure>::_<closure>::closure.55462
  12:        0x10f7f0383 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h5244211801073323039
  13:        0x10f7bad00 - layout_task::_<impl>::create::_<closure>::closure.53753
  14:        0x10f7ba107 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.53724
  15:        0x10f7b9af3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.53713
  16:        0x10f7b9a68 - sys_common::unwind::try::try_fn::try_fn::h3346737908274401483
  17:        0x11191dce8 - __rust_try
  18:        0x11191adee - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  19:        0x10f7b99a5 - sys_common::unwind::try::try::h5873060135202733099
  20:        0x10f7b97de - std::thread::_<impl>::spawn::_<closure>::closure.53690
  21:        0x10f7ba367 - boxed::_<impl>::call_box::call_box::h3141961925543327181
  22:        0x11191fbfd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  23:     0x7fff8f808059 - _pthread_body
  24:     0x7fff8f807fd6 - _pthread_start
stack backtrace:
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', LayoutWorker worker 1/6../src/libcore/result.rs' panicked at ':called `Result::unwrap()` on an `Err` value: RecvError741', 
../src/libcore/result.rsthread ':LayoutWorker worker 3/6741' panicked at '
called `Result::unwrap()` on an `Err` value: RecvErrorthread '', LayoutWorker worker 2/6../src/libcore/result.rs' panicked at ':called `Result::unwrap()` on an `Err` value: RecvError741', 
../src/libcore/result.rs:741
thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', thread 'thread '../src/libcore/result.rsLayoutWorker worker 4/6LayoutWorker worker 6/6:' panicked at '' panicked at '741called `Result::unwrap()` on an `Err` value: RecvError', 
../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 741../src/libcore/result.rs
:741
   1:        0x11191e8a8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x11192096f - panicking::log_panic::_<closure>::closure.40842
   3:        0x111920412 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x11190c226 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x11190c60e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x11191dec7 - rust_begin_unwind
   7:        0x111942fd0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x10f849419 - result::_<impl>::unwrap::unwrap::h8987826244185417907
   9:        0x10f8299e6 - layout_task::_<impl>::handle_request::h7b0899414c669fcfMvq
  10:        0x10f7f636a - layout_task::_<impl>::start::hb5f4977bc025c11d2tq
  11:        0x10f7f61b7 - layout_task::_<impl>::create::_<closure>::_<closure>::closure.55462
  12:        0x10f7f0383 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h5244211801073323039
  13:        0x10f7bad00 - layout_task::_<impl>::create::_<closure>::closure.53753
  14:        0x10f7ba107 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.53724
Servo exited with return value 101
```

**Comment by jdm** [comment]
@gordonbrander That's a different panic. Could you file that separate with steps to reproduce?

**Comment by gordonbrander** [comment]
@jdm filed. Thanks!

**Comment by paulrouget** [comment]
I'm going to close this has I never managed to reproduce.
