### ISSUE TITLE
Intermittent crash in /webstorage/storage_functions_not_overwritten.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#8802]
Note: this only ends up crashing because of #6462. This looks like another issue caused by unwrapping `ipc::channel()`, so blocking #8771.
```
▶ CRASH [expected OK] /webstorage/storage_functions_not_overwritten.html
  │ 
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }', ../src/libcore/result.rs:741
  │ stack backtrace:
  │    1:     0x7f2a3f7ddba0 - sys::backtrace::tracing::imp::write::h064b2475ee0d772cxXt
  │    2:     0x7f2a3f7e0ad5 - panicking::log_panic::_<closure>::closure.40992
  │    3:     0x7f2a3f7e0550 - panicking::log_panic::h29f8d24759545d7862x
  │    4:     0x7f2a3f7c9803 - sys_common::unwind::begin_unwind_inner::hdadcc96a1ecb24974Ps
  │    5:     0x7f2a3f7c9eb8 - sys_common::unwind::begin_unwind_fmt::h9442bd88fc02b35caPs
  │    6:     0x7f2a3f7dd201 - rust_begin_unwind
  │    7:     0x7f2a3f80dc6f - panicking::panic_fmt::h2f3428e3725b99d6VFK
  │    8:     0x7f2a3e60843c - dom::storage::_<impl>::SetItem::hfe96c7b83002398fA9M
  │    9:     0x7f2a3e606be9 - dom::bindings::codegen::Bindings::StorageBinding::setItem::h96f7725ae4ca9671H9B
  │   10:     0x7f2a3f18f41a - CallJitMethodOp
  │   11:     0x7f2a3e475d57 - dom::bindings::utils::generic_call::h944a923566e8098dV7f
  │   12:     0x7f2a3f2acb8c - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  │   13:     0x7f2a3f2a7ab6 - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  │   14:     0x7f2a3f2ac86c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   15:     0x7f2a3f2acaed - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  │   16:     0x7f2a3f5f4af2 - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsfun.cpp:1311
  │   17:     0x7f2a3f2acb8c - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  │   18:     0x7f2a3f2a7ab6 - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  │   19:     0x7f2a3f2ac86c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   20:     0x7f2a3f2acaed - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  │   21:     0x7f2a3f2a7ab6 - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  │   22:     0x7f2a3f2ac86c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   23:     0x7f2a3f2b293f - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeENS_16AbstractFramePtrEPS9_
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:660
  │   24:     0x7f2a3f2b464c - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:703
  │   25:     0x7f2a3f575ff7 - _ZL8EvaluateP9JSContextN2JS6HandleIP8JSObjectEERKNS1_22ReadOnlyCompileOptionsERNS1_18SourceBufferHolderENS1_13MutableHandleINS1_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4184
  │   26:     0x7f2a3f5762df - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4218
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4272
  │   27:     0x7f2a3e470d9a - dom::window::_<impl>::evaluate_script_on_global_with_result::h15281180548092438244
  │   28:     0x7f2a3e71588c - dom::htmlscriptelement::_<impl>::execute::h2f87e0fe0b036e0e1jE
  │   29:     0x7f2a3e7af339 - dom::htmlscriptelement::_<impl>::prepare::he096f9186f4c7762n9D
  │   30:     0x7f2a3e7e625a - tree_builder::rules::_<impl>::step::step::h1433315216288022647
  │   31:     0x7f2a3e7d9761 - tree_builder::_<impl>::process_token::process_token::h2028747933900338001
  │   32:     0x7f2a3e7d8993 - tokenizer::_<impl>::process_token::process_token::h14398272511863804898
  │   33:     0x7f2a3e81180e - tokenizer::_<impl>::emit_current_tag::emit_current_tag::h2511240845110364477
  │   34:     0x7f2a3e80fffd - tokenizer::_<impl>::step::step::h10903579839619328057
  │   35:     0x7f2a3e804367 - tokenizer::_<impl>::run::run::h15393732411558041507
  │   36:     0x7f2a3e7d489c - dom::servohtmlparser::_<impl>::parse_sync::h047ec3d9f6f75408sXM
  │   37:     0x7f2a3e7118d6 - dom::document::_<impl>::finish_load::h69e8c1e9fa39cf05IZo
  │   38:     0x7f2a3e7ab8d9 - dom::htmlscriptelement::_<impl>::response_complete::h899118680413b010S7D
  │   39:     0x7f2a3ed3a164 - _<impl>::process::h303f4076b6893f65psd
  │   40:     0x7f2a3e7b1f47 - network_listener::_<impl>::handler::h11351790770010287679
  │   41:     0x7f2a3e878bee - script_task::_<impl>::handle_msg_from_script::h94f5f9a34cbcc6bbfcZ
  │   42:     0x7f2a3e8be75d - script_task::_<impl>::handle_msgs::_<closure>::closure.156590
  │   43:     0x7f2a3e8a2e33 - script_task::_<impl>::handle_msgs::h7ac06bf311b187b1cYY
  │   44:     0x7f2a3e868e27 - sys_common::unwind::try::try_fn::try_fn::h11572374405779984947
  │   45:     0x7f2a3f7dd048 - __rust_try
  │   46:     0x7f2a3f7d941b - sys_common::unwind::try::inner_try::hb6fbb19d6020cb51CMs
  │   47:     0x7f2a3e86a85a - boxed::_<impl>::call_box::call_box::h15209585567848232006
  │   48:     0x7f2a3f7df433 - sys::thread::_<impl>::new::thread_start::h51b5333730e2e1a3I5w
  │   49:     0x7f2a3b78f181 - start_thread
  │   50:     0x7f2a3bfa947c - __clone
  │   51:                0x0 - <unknown>
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: *self.stack == mem::transmute(&*self)', /home/servo/.cargo/git/checkouts/rust-mozjs-ebb4917e843c0a11/master/src/rust.rs:333
  │ stack backtrace:
  │    1:     0x7f2a3f7ddba0 - sys::backtrace::tracing::imp::write::h064b2475ee0d772cxXt
  │    2:     0x7f2a3f7e0ad5 - panicking::log_panic::_<closure>::closure.40992
  │    3:     0x7f2a3f7e0550 - panicking::log_panic::h29f8d24759545d7862x
  │    4:     0x7f2a3f7c9728 - sys_common::unwind::begin_unwind_inner::hdadcc96a1ecb24974Ps
  │    5:     0x7f2a3e43290f - sys_common::unwind::begin_unwind::begin_unwind::h13140831879653538881
  │    6:     0x7f2a3e716a4f - dom::htmlscriptelement::_<impl>::execute::h2f87e0fe0b036e0e1jE
  │    7:     0x7f2a3e7af339 - dom::htmlscriptelement::_<impl>::prepare::he096f9186f4c7762n9D
  │    8:     0x7f2a3e7e625a - tree_builder::rules::_<impl>::step::step::h1433315216288022647
  │    9:     0x7f2a3e7d9761 - tree_builder::_<impl>::process_token::process_token::h2028747933900338001
  │   10:     0x7f2a3e7d8993 - tokenizer::_<impl>::process_token::process_token::h14398272511863804898
  │   11:     0x7f2a3e81180e - tokenizer::_<impl>::emit_current_tag::emit_current_tag::h2511240845110364477
  │   12:     0x7f2a3e80fffd - tokenizer::_<impl>::step::step::h10903579839619328057
  │   13:     0x7f2a3e804367 - tokenizer::_<impl>::run::run::h15393732411558041507
  │   14:     0x7f2a3e7d489c - dom::servohtmlparser::_<impl>::parse_sync::h047ec3d9f6f75408sXM
  │   15:     0x7f2a3e7118d6 - dom::document::_<impl>::finish_load::h69e8c1e9fa39cf05IZo
  │   16:     0x7f2a3e7ab8d9 - dom::htmlscriptelement::_<impl>::response_complete::h899118680413b010S7D
  │   17:     0x7f2a3ed3a164 - _<impl>::process::h303f4076b6893f65psd
  │   18:     0x7f2a3e7b1f47 - network_listener::_<impl>::handler::h11351790770010287679
  │   19:     0x7f2a3e878bee - script_task::_<impl>::handle_msg_from_script::h94f5f9a34cbcc6bbfcZ
  │   20:     0x7f2a3e8be75d - script_task::_<impl>::handle_msgs::_<closure>::closure.156590
  │   21:     0x7f2a3e8a2e33 - script_task::_<impl>::handle_msgs::h7ac06bf311b187b1cYY
  │   22:     0x7f2a3e868e27 - sys_common::unwind::try::try_fn::try_fn::h11572374405779984947
  │   23:     0x7f2a3f7dd048 - __rust_try
  │   24:     0x7f2a3f7d941b - sys_common::unwind::try::inner_try::hb6fbb19d6020cb51CMs
  │   25:     0x7f2a3e86a85a - boxed::_<impl>::call_box::call_box::h15209585567848232006
  │   26:     0x7f2a3f7df433 - sys::thread::_<impl>::new::thread_start::h51b5333730e2e1a3I5w
  │   27:     0x7f2a3b78f181 - start_thread
  │   28:     0x7f2a3bfa947c - __clone
  │   29:                0x0 - <unknown>
  └ thread panicked while panicking. aborting.
```

**Comment by jdm** [comment]
#8815
