### ISSUE TITLE
Intermittent Result::unwrap() panic in WPT reftest ("Connection reset by peer" or "Couldn't receive FontCacheThread")

### ISSUE THREAD

**Issue by jdm** [servo/servo#8815]
```
 ▶ TIMEOUT [expected FAIL] /html/dom/elements/global-attributes/dir_auto-N-EN.html
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }', ../src/libcore/result.rs:741
  │ stack backtrace:
  │    1:     0x7feb8058e3a0 - sys::backtrace::tracing::imp::write::h064b2475ee0d772cxXt
  │    2:     0x7feb805912d5 - panicking::log_panic::_<closure>::closure.40992
  │    3:     0x7feb80590d50 - panicking::log_panic::h29f8d24759545d7862x
  │    4:     0x7feb8057a003 - sys_common::unwind::begin_unwind_inner::hdadcc96a1ecb24974Ps
  │    5:     0x7feb8057a6b8 - sys_common::unwind::begin_unwind_fmt::h9442bd88fc02b35caPs
  │    6:     0x7feb8058da01 - rust_begin_unwind
  │    7:     0x7feb805be46f - panicking::panic_fmt::h2f3428e3725b99d6VFK
  │    8:     0x7feb7ef6dc65 - constellation::_<impl>::handle_is_ready_to_save_image::handle_is_ready_to_save_image::h7464060649015599629
  │    9:     0x7feb7eefb4e5 - constellation::_<impl>::handle_request::handle_request::h2512767965772658699
  │   10:     0x7feb7eee5f47 - sys_common::unwind::try::try_fn::try_fn::h18033304662745029905
  │   11:     0x7feb8058d848 - __rust_try
  │   12:     0x7feb80589c1b - sys_common::unwind::try::inner_try::hb6fbb19d6020cb51CMs
  │   13:     0x7feb7eee81ba - boxed::_<impl>::call_box::call_box::h3977225798282015024
  │   14:     0x7feb8058fc33 - sys::thread::_<impl>::new::thread_start::h51b5333730e2e1a3I5w
  │   15:     0x7feb7c53a181 - start_thread
  │   16:     0x7feb7cd5447c - __clone
  └   17:                0x0 - <unknown>
```
This looks like a case of the layout/script threads already having shut down and the constellation racing to communicate with them.

**Comment by jdm** [comment]
These might be caused by https://github.com/servo/ipc-channel/issues/29.

**Comment by jdm** [comment]
This will hopefully be solved by https://github.com/servo/ipc-channel/pull/30.

**Comment by jdm** [comment]
Still happening.

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected PASS] /css-transforms-1_dev/html/svg-scalex-002.htm
  │ 
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:688
  │ stack backtrace:
  │    1:     0x7f8f0b7b81b0 - sys::backtrace::tracing::imp::write::hd273f86d5325347aweu
  │    2:     0x7f8f0b7bb0c5 - panicking::default_handler::_<closure>::closure.42335
  │    3:     0x7f8f0b7bab6f - panicking::default_handler::h907ce0af740f5f06spy
  │    4:     0x7f8f0b7a40d6 - sys_common::unwind::begin_unwind_inner::ha417239bcab1f2ff56s
  │    5:     0x7f8f0b7a4838 - sys_common::unwind::begin_unwind_fmt::hac4637ed0b5bb49eb6s
  │    6:     0x7f8f0b7b7811 - rust_begin_unwind
  │    7:     0x7f8f0b7ee7af - panicking::panic_fmt::he5f9c513e9167673LnK
  │    8:     0x7f8f0a08ce0c - constellation::Constellation<LTF, STF>::handle_request::h13343495223626346809
  │    9:     0x7f8f0a0773f7 - export::compositing::constellation::Constellation<LTF, STF>::start::_<closure>::closure.22535
  │   10:     0x7f8f0a076c53 - sys_common::unwind::try::try_fn::h2331431658975388735
  │   11:     0x7f8f0b7b7658 - __rust_try
  │   12:     0x7f8f0b7b393b - sys_common::unwind::try::inner_try::h62f00e3d34dbb509D3s
  │   13:     0x7f8f0a078c3a - boxed::F.FnBox<A>::call_box::h7687463075028640429
  │   14:     0x7f8f0b7b9933 - sys::thread::Thread::new::thread_start::hb3a0514b9d87669e1mx
  │   15:     0x7f8f07d42181 - start_thread
  │   16:     0x7f8f0785947c - __clone
  └   17:                0x0 - <unknown>
```

**Comment by jdm** [comment]
Unfortunately the stack here is much less informative than the original ones that prompted servo/ipc-channel#29 :(

**Comment by jdm** [comment]
```
  ▶ CRASH [expected OK] /webstorage/storage_enumerate.html
  │ 
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
  │ stack backtrace:
  │    1:     0x7f3165615d20 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
  │    2:     0x7f3165618c8b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
  │    3:     0x7f31656188f6 - panicking::default_handler::h7ae2e4523ef4c187IFy
  │    4:     0x7f31656027cc - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
  │    5:     0x7f3165602eb8 - sys_common::unwind::begin_unwind_fmt::hd62d57279546b0f2Jft
  │    6:     0x7f3165615371 - rust_begin_unwind
  │    7:     0x7f3165646c7f - panicking::panic_fmt::h27f7225e08792f40qYL
  │    8:     0x7f31643ccbf0 - result::unwrap_failed::h10414629120728834750
  │    9:     0x7f31645c2c98 - dom::storage::Storage.StorageMethods::GetItem::h3c7ce9cbacd8f9fdQh6
  │   10:     0x7f31645c672a - dom::bindings::codegen::Bindings::StorageBinding::hasOwn::ha72af3118a82ef56JoO
  │   11:     0x7f3164cbc42c - _ZNK22ForwardingProxyHandler6hasOwnEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEEPb
  │   12:     0x7f31654613b9 - _ZN2js5Proxy6hasOwnEP9JSContextN2JS6HandleIP8JSObjectEENS4_I4jsidEEPb
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/Proxy.cpp:265
  │   13:     0x7f31653d328c - _ZN2js14HasOwnPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEEPb
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsobj.cpp:2893
  │   14:     0x7f316510d515 - _ZN2js21SetPropertyByDefiningEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS3_INS2_5ValueEEEbRNS2_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1986
  │   15:     0x7f316510d92f - _ZL22SetNonexistentPropertyP9JSContextN2JS6HandleIPN2js12NativeObjectEEENS2_IP8JSObjectEENS2_I4jsidEENS3_13QualifiedBoolENS2_INS1_5ValueEEERNS1_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:2059
  │   16:     0x7f316510dd8a - _ZN2js17NativeSetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_IP8JSObjectEENS3_I4jsidEENS_13QualifiedBoolENS2_13MutableHandleINS2_5ValueEEERNS2_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:2261
  │   17:     0x7f31654486bf - _ZN2js30SetPropertyIgnoringNamedGetterEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEES6_NS9_I20JSPropertyDescriptorEERNS2_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.h:1451
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/BaseProxyHandler.cpp:108
  │   18:     0x7f31654487aa - _ZNK2js16BaseProxyHandler3setEP9JSContextN2JS6HandleIP8JSObjectEES7_NS4_I4jsidEENS3_13MutableHandleINS3_5ValueEEERNS3_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/BaseProxyHandler.cpp:91
  │   19:     0x7f3164cbc32c - _ZNK22ForwardingProxyHandler3setEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEERNS2_14ObjectOpResultE
  │   20:     0x7f3165461dc0 - _ZN2js5Proxy3setEP9JSContextN2JS6HandleIP8JSObjectEES7_NS4_I4jsidEENS3_13MutableHandleINS3_5ValueEEERNS3_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/Proxy.cpp:326
  │   21:     0x7f3165088c32 - _ZL17SetObjectPropertyP9JSContext4JSOpN2JS6HandleINS2_5ValueEEENS3_I4jsidEENS2_13MutableHandleIS4_EE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:330
  │   22:     0x7f31650b7566 - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:361
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2492
  │   23:     0x7f31650c2bbc - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   24:     0x7f31650c2e3d - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  │   25:     0x7f3165407fc2 - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsfun.cpp:1312
  │   26:     0x7f31650c2edc - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  │   27:     0x7f31650bdd27 - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  │   28:     0x7f31650c2bbc - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   29:     0x7f31650c2e3d - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  │   30:     0x7f31650bdd27 - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2609
  │   31:     0x7f31650c2bbc - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   32:     0x7f31650c8ccf - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeENS_16AbstractFramePtrEPS9_
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:660
  │   33:     0x7f31650ca9dc - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:703
  │   34:     0x7f316538a5a7 - _ZL8EvaluateP9JSContextN2JS6HandleIP8JSObjectEERKNS1_22ReadOnlyCompileOptionsERNS1_18SourceBufferHolderENS1_13MutableHandleINS1_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4185
  │   35:     0x7f316538a88f - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4219
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4273
  │   36:     0x7f31644030cd - dom::window::_&'a T.ScriptHelpers::evaluate_script_on_global_with_result::h18230509288963797354
  │   37:     0x7f31646e5156 - dom::htmlscriptelement::HTMLScriptElement::execute::h267ec9dd15e73bf2mHW
  │   38:     0x7f316478c3f3 - dom::htmlscriptelement::HTMLScriptElement::prepare::h18984bf702ee8d87PwW
  │   39:     0x7f31647c6c94 - tree_builder::rules::super..TreeBuilder<Handle, Sink>.TreeBuilderStep::step::h1292102997620411357
  │   40:     0x7f31647bb136 - tree_builder::TreeBuilder<Handle, Sink>.TokenSink::process_token::h11933795094250531870
  │   41:     0x7f31647ba57e - tokenizer::Tokenizer<Sink>::process_token::h14390719939577070727
  │   42:     0x7f31647f7eef - tokenizer::Tokenizer<Sink>::emit_current_tag::h4190571012748799109
  │   43:     0x7f31647eca58 - tokenizer::Tokenizer<Sink>::step::h9388283934397268950
  │   44:     0x7f31647e5ff7 - tokenizer::Tokenizer<Sink>::run::h14181911900568788416
  │   45:     0x7f31647b342c - dom::servohtmlparser::ServoHTMLParser::parse_sync::h975b341e6e987161LU5
  │   46:     0x7f31646e1e65 - dom::document::Document::finish_load::h323948ba53d444e8IbG
  │   47:     0x7f3164789abe - dom::htmlscriptelement::ScriptContext.AsyncResponseListener::response_complete::h3d40eb0d53cee60fkvW
  │   48:     0x7f3164b8e7de - ResponseAction::process::h15aacfc91b5e5c40eSe
  │   49:     0x7f3164790247 - network_listener::ListenerRunnable<T>.Runnable::handler::h3126939509473971850
  │   50:     0x7f316486fa10 - script_thread::ScriptThread::handle_msg_from_script::hd546fef80fe97c06Gej
  │   51:     0x7f31648a8617 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.170113
  │   52:     0x7f3164893f4a - script_thread::ScriptThread::handle_msgs::hf588c3b7943ef465k0i
  │   53:     0x7f3164861637 - sys_common::unwind::try::try_fn::h17886566462519321695
  │   54:     0x7f31656152fb - __rust_try
  │   55:     0x7f316561191d - sys_common::unwind::inner_try::hf5df2c554f3d837dFdt
  │   56:     0x7f3164862c4a - boxed::F.FnBox<A>::call_box::h9939960023260697713
  │   57:     0x7f3165617713 - sys::thread::Thread::new::thread_start::h05e6a3d5b147b01bsCx
  │   58:     0x7f3161b65181 - start_thread
  │   59:     0x7f316167c47c - __clone
  │   60:                0x0 - <unknown>
```

**Comment by jdm** [comment]
That previous stack trace looks like the exact problem that https://github.com/servo/ipc-channel/pull/30 was intended to solve.

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected PASS] /css-text-3_dev/html/text-align-end-004.htm
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
  │ stack backtrace:
  │    1:     0x7fcd4bc93c00 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
  │    2:     0x7fcd4bc97ebb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
  │    3:     0x7fcd4bc97b28 - panicking::default_handler::hffa00c845e94c6581nA
  │    4:     0x7fcd4bc8193c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
  │    5:     0x7fcd4bc81f68 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
  │    6:     0x7fcd4bc93071 - rust_begin_unwind
  │    7:     0x7fcd4bccf86f - panicking::panic_fmt::h548fe28297c9d83b7mM
  │    8:     0x7fcd4a88e830 - result::unwrap_failed::h15197564516607684196
  │    9:     0x7fcd4a8b5874 - font_cache_thread::FontCacheThread::exit::hcd9db9bae5719edaOnn
  │   10:     0x7fcd4a2ccfc1 - constellation::Constellation<LTF, STF>::handle_exit::h7108214929393823016
  │   11:     0x7fcd4a2ac13d - constellation::Constellation<LTF, STF>::handle_request::h16991008427106128809
  │   12:     0x7fcd4a29c067 - sys_common::unwind::try::try_fn::h15191647032876987592
  │   13:     0x7fcd4bc92ffb - __rust_try
  │   14:     0x7fcd4bc8fbfd - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  │   15:     0x7fcd4a29d05a - boxed::F.FnBox<A>::call_box::h14362483419259287613
  │   16:     0x7fcd4bc96969 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  │   17:     0x7fcd47efb181 - start_thread
  │   18:     0x7fcd47a1247c - __clone
  └   19:                0x0 - <unknown>
```

**Comment by emilio** [comment]
Since most of the occurrences of this now happen in `FontCacheThread::exit()`, I added debug info in #11166.

It's probably a race, but if it's not really important (something like the other side has already exited) and we don't care a lot (that depends on what the other side is and expects), we could drop the `unwrap()`s.

**Comment by mbrubeck** [comment]
```
  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/font-family-rule-001.htm
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'Constellation' panicked at 'Couldn't receive FontCacheThread reply: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:785
  │ stack backtrace:
  │    1:     0x7f4f8177b040 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:     0x7f4f817827bb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:     0x7f4f81782423 - std::panicking::default_hook::hc2c969e7453d080c
  │    4:     0x7f4f80eb4c47 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h625edf9a36237d31
  │    5:     0x7f4f81768503 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:     0x7f4f81769f48 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:     0x7f4f8177a291 - rust_begin_unwind
  │    8:     0x7f4f817b983f - core::panicking::panic_fmt::h257ceb0aa351d801
  │    9:     0x7f4f80a593e3 - core::result::unwrap_failed::h330560dbaf0a51e7
  │   10:     0x7f4f80a7f6ca - gfx::font_cache_thread::FontCacheThread::exit::ha2f1f4fd6ebc6397
  │   11:     0x7f4f7fdf0d68 - _<compositing..Constellation<LTF, STF>>::handle_exit::hae6d0417398a20fa
  │   12:     0x7f4f7fdc6592 - _<compositing..Constellation<LTF, STF>>::handle_request::h3c97e2d5b7782802
  │   13:     0x7f4f7fdba1dc - std::sys_common::unwind::try::try_fn::h12e8cdd1c52fbc04
  │   14:     0x7f4f8177a21b - __rust_try
  │   15:     0x7f4f8177a1ad - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   16:     0x7f4f7fdbb7ca - _<F as std..boxed..FnBox<A>>::call_box::h4fbd446f73dda14f
  │   17:     0x7f4f81780c74 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   18:     0x7f4f7d738181 - start_thread
  │   19:     0x7f4f7d24f47c - __clone
  └   20:                0x0 - <unknown>
```

**Comment by Ms2ger** [comment]
Seems to have disappeared.
