### ISSUE TITLE
Android nightly's busted.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8850]
```

failed to run custom build command for `hbs-pow-sys v0.1.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#5ce01d0e)`
Process didn't exit successfully: `/home/servo/buildbot/slave/android-nightly/build/target/release/build/hbs-pow-sys-4f2a0dd8d72ac62e/build-script-build` (exit code: 101)
--- stdout
-- Configuring incomplete, errors occurred!

--- stderr
CMake Error at cmake-toolchain/android.toolchain.cmake:446 (message):
  Could not find neither Android NDK nor Android standalone toolchain.

      You should either set an environment variable:
        export ANDROID_NDK=~/my-android-ndk
      or
        export ANDROID_STANDALONE_TOOLCHAIN=~/my-android-toolchain
      or put the toolchain or NDK in the default path:
        sudo ln -s ~/my-android-ndk /opt/android-ndk
        sudo ln -s ~/my-android-toolchain /opt/android-toolchain
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:3 (project)


CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/build/hbs-pow-sys-4f2a0dd8d72ac62e/out/_build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/build/hbs-pow-sys-4f2a0dd8d72ac62e/out/_build/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
thread '<main>' panicked at 'assertion failed: status.success()', /home/servo/.cargo/git/checkouts/heartbeats-simple-sys-203def3c271a26ee/master/hbs-pow-sys/build.rs:44
stack backtrace:
   1:     0x562f755d3ae0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x562f755d8365 - panicking::log_panic::_<closure>::closure.40991
   3:     0x562f755d7de0 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x562f755c1843 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x562f755bc6d7 - sys_common::unwind::begin_unwind::begin_unwind::h3137125601911614585
                        at ../src/libstd/sys/common/unwind/mod.rs:237
   6:     0x562f755bb1b5 - run::h678b4b83eaf6bbd38da
                        at /home/servo/buildbot/slave/android-nightly/build/components/servo/<std macros>:3
   7:     0x562f755b2b43 - main::hf11fc2fcbc7c5c83kaa
                        at /home/servo/.cargo/git/checkouts/heartbeats-simple-sys-203def3c271a26ee/master/hbs-pow-sys/build.rs:34
   8:     0x562f755d7b84 - sys_common::unwind::try::try_fn::h8505855046713178995
   9:     0x562f755d2f88 - __rust_try
  10:     0x562f755d7826 - rt::lang_start::h45458ea0787b3e00e0x
  11:     0x562f755bcd89 - main
  12:     0x7ff86972aec4 - __libc_start_main
  13:     0x562f755b1cd7 - <unknown>
  14:                0x0 - <unknown>
```

**Comment by larsbergstrom** [comment]
Oh, the Android nightly build is fixed now :-)

see: http://build.servo.org/builders/android-nightly/builds/119
