### ISSUE TITLE
Panic while panicking: unable to find pipeline - this is a bug

### ISSUE THREAD

**Issue by gkbrk** [servo/servo#8989]
Hey there! I got this crash on `http://gkbrk.com`. I hope the log is useful.

```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }' panicked at 'assertion failed: self.suspended_since.get().is_none()', /home/leonardo/Desktop/Unorganized/CompiledSoftware/servo/components/script/timers.rs:348
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
thread 'thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }', ' panicked at '../src/libcore/result.rs:741
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', ../src/libcore/result.rs:741
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', ../src/libcore/result.rs:741
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }).', /home/leonardo/Desktop/Unorganized/CompiledSoftware/servo/components/compositing/compositor.rs:686
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/leonardo/Desktop/Unorganized/CompiledSoftware/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166
stack backtrace:
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: RecvError', LayoutWorker worker 3/3../src/libcore/result.rs' panicked at ':called `Result::unwrap()` on an `Err` value: RecvError741', 
../src/libcore/result.rs:741
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
   1:     0x7f1203eccfc0 - sys::backtrace::tracing::imp::write::h92808652e552bec0MZt
   2:     0x7f1203ecfe35 - panicking::log_panic::_<closure>::closure.41184
   3:     0x7f1203ecf8b0 - panicking::log_panic::hc4038fe8a2a609d626x
   4:     0x7f1203eb8d38 - sys_common::unwind::begin_unwind_inner::hd5a3cc6e3320d6b8lSs
   5:     0x7f12035a36ef - sys_common::unwind::begin_unwind::begin_unwind::h5580129601238987449
   6:     0x7f12035a37f0 - platform::linux::surface::_<impl>::drop::h448c32674cd0072bjbc
   7:     0x7f12026e2d07 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.29105::he65cb8e7d33d3aee
   8:     0x7f12026e2e55 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.29117::hc45a3cf89d001c25
   9:     0x7f12026e2be4 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.29105::he65cb8e7d33d3aee
  10:     0x7f12026e4d21 - compositing..compositor..IOCompositor<app..window..Window>::drop.29482::h442d3fa04c2cc1e4
  11:     0x7f12026d2f1f - main::hb77cfbfb032d8741Laa
  12:     0x7f1203ecf654 - sys_common::unwind::try::try_fn::h7862647019611204684
  13:     0x7f1203ecc468 - __rust_try
  14:     0x7f1203ecf2f6 - rt::lang_start::h48fbdbf4c3b8b04ca4x
  15:     0x7f1201e7cec4 - __libc_start_main
  16:     0x7f12026c6789 - <unknown>
  17:                0x0 - <unknown>
thread panicked while panicking. aborting.Illegal instruction
```

**Comment by sviter** [comment]
Can't reproduse with Servo 0.0.1-08b9588 on win10

**Comment by jdm** [comment]
Thanks for checking!
