### ISSUE TITLE
bootstraping mach fails with --user in ~/.pip/pip.conf

### ISSUE THREAD

**Issue by gdamjan** [servo/servo#9046]
```
$ cat ~/.pip/pip.conf 
[install]
install-option=--user
```

```
$ ./mach build --release                                                                                                       
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/damjan/src/servo/python/_virtualenv/bin/python2.7
Not overwriting existing python script /home/damjan/src/servo/python/_virtualenv/bin/python (you must use /home/damjan/src/servo/python/_virtualenv/bin/python2.7)
Installing setuptools, pip, wheel...
  Complete output from command /home/damjan/src/ser...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  /usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/commands/install.py:199: UserWarning: Disabling all use of wheels
 due to the use of --build-options / --global-options / --install-options.
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
  Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptools
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/damjan/src/ser...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
Python virtualenv failed to execute properly.
```

servo at df087cc

ps. is it really needed to use the fragile virtualenv? pep-370 does everything virtualenv does and better. (hint PYTHONUSERBASE=$PWD/py-env pip2 install --user -r requirements.txt)

**Comment by mrobinson** [comment]
I'm closing this as we no longer use `virtualenv` in Servo.
