### ISSUE TITLE
Intermittent timeouts in tests/wpt/css-tests/mediaqueries-3_dev/html

### ISSUE THREAD

**Issue by gsnedders** [servo/servo#9052]
I've so far observed this in `calc-in-media-queries-001.htm`, `calc-in-media-queries-002.htm`, `mq-calc-002.htm`, `mq-calc-003.htm`, `mq-calc-004.htm`, `mq-calc-005.htm`.

Example stack trace: 

```
  ▶ TIMEOUT [expected CRASH] /mediaqueries-3_dev/html/calc-in-media-queries-001.htm
  │ 
  │ thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'internal error: entered unreachable code', /Users/gsnedders/Documents/other-projects/servo/components/style/media_queries.rs:40
  │ thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: !self.Document().needs_reflow() || self.window_size.get().is_none()', /Users/gsnedders/Documents/other-projects/servo/components/script/dom/window.rs:1006
  │ thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rsthread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ 741
  │ ', ../src/libcore/result.rs:741
  │ :741
  │ 
  └ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) }', ../src/libcore/result.rs:741
```

The initial panic is always the unreachable code; the assert isn't always hit.

**Comment by jdm** [comment]
Doesn't match tests we run any more.
