### ISSUE TITLE
thread '<main>' panicked at 'no entry found for key'

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#9320]
We sporadically experience crashes like this when running Browser.html. This particular crash was triggered when loading github.com in Browser.html with a Servo Webrender build (`./servo -w -b --pref dom.mozbrowser.enabled http://localhost:6060`).

cc @paulrouget

``` log
thread '<main>' panicked at 'no entry found for key', ../src/libcore/option.rs:335
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:741
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError
', ../src/libcore/result.rs:741

thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rsthread ':LayoutWorker worker 2/6741' panicked at '
called `Result::unwrap()` on an `Err` value: RecvErrorthread '', LayoutWorker worker 1/6../src/libcore/result.rs' panicked at ':741called `Result::unwrap()` on an `Err` value: RecvError
', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rsthread ':741PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741

thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', >>> Action:
../src/libcore/result.rs<unnamed>:' panicked at '741called `Result::unwrap()` on an `Err` value: "SendError(..)"
', ../src/libcore/result.rs:
741
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:<<< Model:
741

thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
../src/libcore/result.rs:741LayoutWorker worker 3/6
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', ../src/libcore/result.rs:741
LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'thread 'thread 'thread 'LayoutWorker worker 6/6PaintWorkerPaintWorker' panicked at '' panicked at 'LayoutWorker worker 5/6called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError' panicked at '' panicked at '', called `Result::unwrap()` on an `Err` value: RecvErrorthread '../src/libcore/result.rs', thread ':called `Result::unwrap()` on an `Err` value: RecvErrorPaintWorker', PaintWorker741../src/libcore/result.rs
', ../src/libcore/result.rs::741741../src/libcore/result.rs
:
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs741:741

thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError' panicked at '', ../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 741../src/libcore/result.rs
:741
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:thread '741
PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:741
stack backtrace:
   1:        0x10d446828 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x10d4488ef - panicking::log_panic::_<closure>::closure.40842
   3:        0x10d448392 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x10d433f84 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x10d43446e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
   6:        0x10d445e47 - rust_begin_unwind
   7:        0x10d46af50 - panicking::panic_fmt::h871c0ef100fda9e9LFK
   8:        0x10c3527ed - dom::node::_<impl>::dispose::hf85283abe0377c7btlY
   9:        0x10bffe838 - dom..node..Node::drop.134867::hc9381b662a09b325
  10:        0x10c06e5fb - dom..element..Element::drop.138466::h945a072a1d3ee0f7
  11:        0x10c0c21b6 - dom::bindings::codegen::Bindings::HTMLHtmlElementBinding::_finalize::h737776fefc2368de8fe
  12:        0x10d2f7362 - _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
  13:        0x10d2aeb55 - _ZL14FinalizeArenasPN2js6FreeOpEPPNS_2gc11ArenaHeaderERNS2_15SortedArenaListENS2_9AllocKindERNS_11SliceBudgetENS2_10ArenaLists14KeepArenasEnumE
  14:        0x10d2b2955 - _ZN2js2gc10ArenaLists30queueForegroundObjectsForSweepEPNS_6FreeOpE
  15:        0x10d2b8893 - _ZN2js2gc9GCRuntime22beginSweepingZoneGroupEv
  16:        0x10d2b9506 - _ZN2js2gc9GCRuntime15beginSweepPhaseEb
  17:        0x10d2bbd05 - _ZN2js2gc9GCRuntime23incrementalCollectSliceERNS_11SliceBudgetEN2JS8gcreason6ReasonE
  18:        0x10d2bc454 - _ZN2js2gc9GCRuntime7gcCycleEbRNS_11SliceBudgetEN2JS8gcreason6ReasonE
  19:        0x10d2bc9ee - _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8gcreason6ReasonE
  20:        0x10d26aaaa - _ZN2js14DestroyContextEP9JSContextNS_18DestroyContextModeE
  21:        0x10ce6bed1 - rust::_<impl>::drop::h53f00d0862243c27zLi
  22:        0x10c42b538 - script_thread..ScriptThread::drop.166362::h9674a833131fde83
  23:        0x10c42706f - sys_common::unwind::try::try_fn::try_fn::h14683358672392954919
  24:        0x10d445c68 - __rust_try
  25:        0x10d442c6e - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  26:        0x10c427571 - boxed::_<impl>::call_box::call_box::h17313149958084828180
  27:        0x10d447b7d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  28:     0x7fff991c3059 - _pthread_body
  29:     0x7fff991c2fd6 - _pthread_start
thread panicked while panicking. aborting.[1]    56453 illegal hardware instruction  ./servo -w -b --pref dom.mozbrowser.enabled http://localhost:6060
```

**Comment by metajack** [comment]
cc @jdm @Manishearth @pcwalton 

This seems scary because it looks like a double free of a dom node.

**Comment by jdm** [comment]
@metajack No, this is just a critical cascade triggered by the main thread panicking and every other thread panicking while attempting to communicate with the compositor. Note the first line of the log:
```
thread '<main>' panicked at 'no entry found for key', ../src/libcore/option.rs:335
```

**Comment by jdm** [comment]
@gordonbrander It will be easier to diagnose crashes like this by running with RUST_BACKTRACE=1.

**Comment by gordonbrander** [comment]
@jdm can you point me to a doc for how to run with `RUST_BACKTRACE=1`? Apologies if I'm missing something obvious.

**Comment by glennw** [comment]
I've seen this occasionally too - I'm pretty sure it's a WR bug somewhere, but I haven't tracked down the cause yet.

@gordonbrander If you run from a terminal, you should be able to just do:

RUST_BACKTRACE=1 <normal servo run command>

or:

export RUST_BACKTRACE=1
<normal servo run command>

**Comment by Manishearth** [comment]
@jdm we should still not be getting a double free on unwinding though, right?

(havent looked closely at the situation yet -- I have a build but my laptop isn't with me right now)

**Comment by jdm** [comment]
There's no double free occurring.

**Comment by nox** [comment]
This seems like the kind of issues that we fixed over time. Closing.
