### ISSUE TITLE
(WebRender) ScriptThread PipelineId panicked at 'no root stacking context!

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#9323]
This crash happened while loading the page http://github.com/mozilla/browserhtml in Browser.html with WebRender. (As an aside, please let me know if this is the right place to report bugs in WebRender builds).

```
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'no root stacking context!', /Users/paul/git/servo-webrender/components/layout/query.rs:102
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) }', ../src/libcore/result.rs:741
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:741
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rsthread ':741LayoutWorker worker 5/6
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', thread '../src/libcore/result.rsPaintWorker:' panicked at '741called `Result::unwrap()` on an `Err` value: RecvError
', ../src/libcore/result.rs:thread '741PaintWorker
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741thread '
PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
```

cc @metajack

**Comment by glennw** [comment]
I'm fine with reporting them in https://github.com/glennw/webrender or here (perhaps we need a webrender tag though?).

**Comment by nox** [comment]
This has probably been fixed since then.
