### ISSUE TITLE
Crash: "too many open files"

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#9609]
This was in a webrender build. cc @pcwalton @metajack 

```
thread 'http_loader for http://www.notempire.com/images/uploads/Cover-17.jpg' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', ../src/libstd/rand/mod.rs:160
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'http_loader for http://www.notempire.com/images/uploads/um-3.jpg' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', ../src/libstd/rand/mod.rs:160
thread 'http_loader for http://www.notempire.com/images/uploads/glass-42.jpg' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', /Users/paul/git/servo-webrender/.cargo/registry/src/github.com-0a35038f75765ae4/rand-0.3.12/src/lib.rs:873
thread 'http_loader for http://www.notempire.com/images/uploads/safari-5.jpg' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', ../src/libstd/rand/mod.rs:160
thread 'http_loader for http://www.notempire.com/images/uploads/technic.jpg' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', ../src/libstd/rand/mod.rs:160
thread 'http_loader for http://www.notempire.com/images/uploads/Ocean_Outdoor_Digital_Screen_Design.jpg' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', /Users/paul/git/servo-webrender/.cargo/registry/src/github.com-0a35038f75765ae4/rand-0.3.12/src/lib.rs:873
ERROR:js::rust: Error at http://www.notempire.com/js/gridview.v30.js:1:8: expected expression, got '<'

ERROR:js::rust: Error at http://www.notempire.com/js/gridview.v30.js:1:8: expected expression, got '<'

thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:704
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(38) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(37) }LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(33) }' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ', ../src/libcore/result.rs../src/libcore/result.rs::746746

thread 'thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(34) }LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(36) }' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
', ../src/libcore/result.rs:746
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(35) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(38) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 3/6thread '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 5/6', ' panicked at '../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 746../src/libcore/result.rs
:746
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 6/6', ' panicked at '../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 746../src/libcore/result.rs
:746
thread 'LayoutWorker worker 3/6' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 4/6', ' panicked at '../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 746../src/libcore/result.rs
:746
thread 'LayoutWorker worker 5/6thread '' panicked at 'LayoutWorker worker 6/6called `Result::unwrap()` on an `Err` value: RecvError' panicked at '', called `Result::unwrap()` on an `Err` value: RecvError../src/libcore/result.rs', :../src/libcore/result.rs746:
746
thread 'LayoutWorker worker 1/6' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 2/6', ' panicked at '../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 746../src/libcore/result.rs
:746
thread 'LayoutWorker worker 3/6' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 5/6', ' panicked at '../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvError:', 746../src/libcore/result.rs
:746
thread 'LayoutWorker worker 4/6thread '' panicked at 'LayoutWorker worker 6/6called `Result::unwrap()` on an `Err` value: RecvError' panicked at '', called `Result::unwrap()` on an `Err` value: RecvError../src/libcore/result.rs', :../src/libcore/result.rs746:
746
thread 'LayoutWorker worker 1/6thread '' panicked at 'LayoutWorker worker 2/6called `Result::unwrap()` on an `Err` value: RecvError' panicked at '', called `Result::unwrap()` on an `Err` value: RecvError../src/libcore/result.rs', :../src/libcore/result.rs746:
746
thread 'thread 'LayoutWorker worker 3/6LayoutWorker worker 4/6' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
', ../src/libcore/result.rs:746
thread 'thread 'LayoutWorker worker 5/6' panicked at 'thread 'LayoutWorker worker 6/6called `Result::unwrap()` on an `Err` value: RecvError' panicked at 'LayoutWorker worker 1/6', called `Result::unwrap()` on an `Err` value: RecvError' panicked at '../src/libcore/result.rs', called `Result::unwrap()` on an `Err` value: RecvError:../src/libcore/result.rs', 746:../src/libcore/result.rs
:746746

thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'thread '', LayoutWorker worker 4/6LayoutWorker worker 3/6../src/libcore/result.rs' panicked at '' panicked at ':called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError746', ', 
../src/libcore/result.rs../src/libcore/result.rs::746746

thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
../src/libcore/result.rs:746
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(37) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(39) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', LayoutWorker worker 2/6../src/libcore/result.rs' panicked at ':called `Result::unwrap()` on an `Err` value: RecvError746', 
../src/libcore/result.rs:746
thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', thread '../src/libcore/result.rs:746ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(37) }
' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(39) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
   1:        0x104265098 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1042671f5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x104266df6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x104252506 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x1042529be - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1042646a7 - rust_begin_unwind
   7:        0x104289a20 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x104289d1c - panicking::panic::h7ef5710ee3bbcba2XWL
   9:        0x103371c21 - script_thread::ScriptThread::load::AutoPageRemover<'a>.Drop::drop::h26b8a05714d17532nTj
  10:        0x10336f471 - script_thread::ScriptThread::load::hbb08329e3cb0a013QOj
  11:        0x1032572b3 - script_thread::ScriptThread::page_fetch_complete::h913c30830de9cbd7jTi
  12:        0x103255252 - dom::servohtmlparser::ParserContext.AsyncResponseListener::headers_available::hd0aa01deba919ce8FD5
  13:        0x103819c87 - ResponseAction::process::h57655560312a5e30oRe
  14:        0x103373a20 - network_listener::ListenerRunnable<T>.Runnable::handler::h7082494208025830107
  15:        0x103318866 - script_thread::ScriptThread::handle_msg_from_script::hc190e0e76c654cd9Pej
  16:        0x103355d17 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.170202
  17:        0x103340808 - script_thread::ScriptThread::handle_msgs::h5814a31d760d4b3ct0i
  18:        0x103309ae7 - sys_common::unwind::try::try_fn::h10802032986397135002
  19:        0x10426463b - __rust_try
  20:        0x1042615d3 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  21:        0x10330b17a - boxed::F.FnBox<A>::call_box::h13125219975059133107
  22:        0x10426647d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  23:     0x7fff86bc4059 - _pthread_body
  24:     0x7fff86bc3fd6 - _pthread_start
thread panicked while panicking. aborting.
[1]    9598 illegal hardware instruction
```

**Comment by jdm** [comment]
@gordonbrander Any steps to reproduce? What platform?

**Comment by gordonbrander** [comment]
@jdm Unfortunately, no STR. Webrender build on Mac. I had 3 tabs open in Browser.html/Servo and everything was working great. The crash happened without warning. @metajack was screensharing with me when it happened :)

**Comment by jdm** [comment]
@gordonbrander Had you loaded multiple pages before receiving this?

**Comment by gordonbrander** [comment]
@jdm yes, all 3 pages (iframes) were running without a problem in Browser.html for about 20 second. The crash didn't correspond to any obvious event.

**Comment by jdm** [comment]
@gordonbrander Any idea what pages were loaded in the frames? Had any of the frames been navigated from other pages previously? I'm just trying to establish some sort of useful context here :)

**Comment by gordonbrander** [comment]
Yeah, apologies I wasn't able to come up with a clean STR for this. I believe the tabs open were:

- http://github.com
- http://notcot.org
- metajack.im

**Comment by larsbergstrom** [comment]
We've seen this on the automation servers when we're creating WAY too many OS handles. I've hacked the macstadium servers to work around it, since we're running servo in a weird way there (lots of concurrent instances):
https://github.com/servo/servo/issues/6350#issuecomment-122274368

**Comment by dralley** [comment]
Without steps to reproduce, after 4 years, should this be closed?
