### ISSUE TITLE
Pipeline exiting causing segfault again.

### ISSUE THREAD

**Issue by tikue** [servo/servo#965]
It looks like #570 regressed.

```
CGLGetPixelFormat failed.
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
[Switching to process 21117 thread 0x4f03]
0x0000000100fee747 in AzCreateSkiaDrawTargetForFBO ()
(gdb) bt
#0  0x0000000100fee747 in AzCreateSkiaDrawTargetForFBO ()
#1  0x0000000100eee099 in new_with_fbo () at azure_hl.rs:343
#2  0x000000010007b27a in render_task::__extensions__::render_23929::anon::anon::expr_fn_23935 () at constellation.rs:62
#3  0x00000001000713cc in render_task::__extensions__::create_22796::anon::expr_fn_22924 () at constellation.rs:62
#4  0x000000010006f958 in task::__extensions__::spawn_with_22812::anon::expr_fn_22818 () at constellation.rs:62
#5  0x0000000100300c6c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
#6  0x00000001003a1254 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27304 ()
#7  0x00000001002a407c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
#8  0x000000010039ebc5 in rt::task::__extensions__::run::anon::expr_fn_27232 ()
#9  0x00000001003a1729 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
#10 0x00000001003a1687 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
#11 0x00000001021f9574 in rust_try (f=0x200, fptr=0x0, env=0x11d28a830) at rust_builtin.cpp:523
#12 0x000000010039ea92 in rt::task::Unwinder::try::_199ab8d6eb226980VZan::v0.8$x2dpre ()
#13 0x000000010039e926 in rt::task::Task::run::_199ab8d6eb226980iQam::v0.8$x2dpre ()
#14 0x00000001003a0ea7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27289 ()
#15 0x00000001004252a5 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
#16 0x0000000100425257 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
(gdb) 
```

To replicate:
1) ./servo http://en.wikipedia.org/wiki/Nero
2) Click _Roman Emperor_ link
3) Click backspace
4) Click _Roman Emperor_ link again.

**Comment by narfg** [comment]
I can't reproduce this anymore so I guess it was fixed.
