### ISSUE TITLE
Crash when visiting http://www.free.fr

### ISSUE THREAD

**Issue by kubrickfr** [servo/servo#9776]
here is the backtrace:

```

$ ./mach run --release http://www.free.fr
thread 'LayoutWorker worker 9/9' panicked at 'called `Result::unwrap()` on an `Err` value: EndOfStreamError', ../src/libcore/result.rs:746
stack backtrace:
thread 'LayoutWorker worker 3/9' panicked at 'called `Result::unwrap()` on an `Err` value: EndOfStreamError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 1/9' panicked at 'called `Result::unwrap()` on an `Err` value: EndOfStreamError', ../src/libcore/result.rs:746
   1:      0x2e59c1ceb50 - sys::backtrace::tracing::imp::write::hb39adb9cc1dae4a9Nyu
   2:      0x2e59c1d2f0b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43683
   3:      0x2e59c1d2b78 - panicking::default_handler::hced6c0d85eb2cb83bez
   4:      0x2e59c1bc71c - sys_common::unwind::begin_unwind_inner::hafb014b2dc8828386mt
   5:      0x2e59c1bcba8 - sys_common::unwind::begin_unwind_fmt::hd671b811c60b4ff4cmt
   6:      0x2e59c1ce031 - rust_begin_unwind
   7:      0x2e59c2035af - panicking::panic_fmt::h38cc775b27fedfe3yZL
   8:      0x2e59b41bae0 - result::unwrap_failed::h15477382761685336631
   9:      0x2e59b43ae75 - font_cache_thread::FontCacheThread::find_font_template::h008192376db7f5cc8cm
  10:      0x2e59b440483 - font_context::FontContext::layout_font_group_for_style::h5f5c8fbc4ceb1ce1bpm
  11:      0x2e59a9dbabc - text::TextRunScanner::scan_for_runs::h531f58ecc8751f93BQw
  12:      0x2e59ab03e06 - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>::build_flow_for_block_starting_with_fragments::h10351519308666213259
  13:      0x2e59ab00221 - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>.PostorderNodeMutTraversal<'ln, ConcreteThreadSafeLayoutNode>::process::h3859693457692349390
  14:      0x2e59aabbebe - traversal::RecalcStyleAndConstructFlows<'lc>.DomTraversalContext<'ln, ServoLayoutNode<'ln>>::process_postorder::h2556065082366626Qpx
  15:      0x2e59aac5f2a - parallel::top_down_dom::h9652298728894702431
  16:      0x2e59aa115c6 - sys_common::unwind::try::try_fn::h18108765470571238195
  17:      0x2e59c1cdfbb - __rust_try
  18:      0x2e59c1cac0d - sys_common::unwind::inner_try::hacd4193e6d9e10788jt
  19:      0x2e59aa12d09 - boxed::F.FnBox<A>::call_box::h7671955735126141469
  20:      0x2e59c1d19b9 - sys::thread::Thread::new::thread_start::h42fba1e2d4e7a4bevby
  21:      0x30485dca423 - start_thread
  22:      0x304858f3cbc - clone
  23:                0x0 - <unknown>
stack backtrace:
   1:      0x2e59c1ceb50 - sys::backtrace::tracing::imp::write::hb39adb9cc1dae4a9Nyu
   2:      0x2e59c1d2f0b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43683
   3:      0x2e59c1d2b78 - panicking::default_handler::hced6c0d85eb2cb83bez
   4:      0x2e59c1bc71c - sys_common::unwind::begin_unwind_inner::hafb014b2dc8828386mt
   5:      0x2e59c1bcba8 - sys_common::unwind::begin_unwind_fmt::hd671b811c60b4ff4cmt
   6:      0x2e59c1ce031 - rust_begin_unwind
   7:      0x2e59c2035af - panicking::panic_fmt::h38cc775b27fedfe3yZL
   8:      0x2e59b41bae0 - result::unwrap_failed::h15477382761685336631
   9:      0x2e59b43ae75 - font_cache_thread::FontCacheThread::find_font_template::h008192376db7f5cc8cm
  10:      0x2e59b440483 - font_context::FontContext::layout_font_group_for_style::h5f5c8fbc4ceb1ce1bpm
  11:      0x2e59a9dbabc - text::TextRunScanner::scan_for_runs::h531f58ecc8751f93BQw
  12:      0x2e59ab03e06 - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>::build_flow_for_block_starting_with_fragments::h10351519308666213259
  13:      0x2e59ab00221 - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>.PostorderNodeMutTraversal<'ln, ConcreteThreadSafeLayoutNode>::process::h3859693457692349390
  14:      0x2e59aabbebe - traversal::RecalcStyleAndConstructFlows<'lc>.DomTraversalContext<'ln, ServoLayoutNode<'ln>>::process_postorder::h2556065082366626Qpx
  15:      0x2e59aac5f2a - parallel::top_down_dom::h9652298728894702431
  16:      0x2e59aa115c6 - sys_common::unwind::try::try_fn::h18108765470571238195
  17:      0x2e59c1cdfbb - __rust_try
  18:      0x2e59c1cac0d - sys_common::unwind::inner_try::hacd4193e6d9e10788jt
  19:      0x2e59aa12d09 - boxed::F.FnBox<A>::call_box::h7671955735126141469
  20:      0x2e59c1d19b9 - sys::thread::Thread::new::thread_start::h42fba1e2d4e7a4bevby
  21:      0x30485dca423 - start_thread
  22:      0x304858f3cbc - clone
  23:                0x0 - <unknown>
stack backtrace:
   1:      0x2e59c1ceb50 - sys::backtrace::tracing::imp::write::hb39adb9cc1dae4a9Nyu
   2:      0x2e59c1d2f0b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43683
   3:      0x2e59c1d2b78 - panicking::default_handler::hced6c0d85eb2cb83bez
   4:      0x2e59c1bc71c - sys_common::unwind::begin_unwind_inner::hafb014b2dc8828386mt
   5:      0x2e59c1bcba8 - sys_common::unwind::begin_unwind_fmt::hd671b811c60b4ff4cmt
   6:      0x2e59c1ce031 - rust_begin_unwind
   7:      0x2e59c2035af - panicking::panic_fmt::h38cc775b27fedfe3yZL
   8:      0x2e59b41bae0 - result::unwrap_failed::h15477382761685336631
   9:      0x2e59b43ae75 - font_cache_thread::FontCacheThread::find_font_template::h008192376db7f5cc8cm
  10:      0x2e59b440483 - font_context::FontContext::layout_font_group_for_style::h5f5c8fbc4ceb1ce1bpm
  11:      0x2e59a9dbabc - text::TextRunScanner::scan_for_runs::h531f58ecc8751f93BQw
  12:      0x2e59ab03e06 - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>::build_flow_for_block_starting_with_fragments::h10351519308666213259
  13:      0x2e59ab00221 - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>.PostorderNodeMutTraversal<'ln, ConcreteThreadSafeLayoutNode>::process::h3859693457692349390
  14:      0x2e59aabbebe - traversal::RecalcStyleAndConstructFlows<'lc>.DomTraversalContext<'ln, ServoLayoutNode<'ln>>::process_postorder::h2556065082366626Qpx
  15:      0x2e59aac5f2a - parallel::top_down_dom::h9652298728894702431
  16:      0x2e59aa115c6 - sys_common::unwind::try::try_fn::h18108765470571238195
  17:      0x2e59c1cdfbb - __rust_try
  18:      0x2e59c1cac0d - sys_common::unwind::inner_try::hacd4193e6d9e10788jt
  19:      0x2e59aa12d09 - boxed::F.FnBox<A>::call_box::h7671955735126141469
  20:      0x2e59c1d19b9 - sys::thread::Thread::new::thread_start::h42fba1e2d4e7a4bevby
  21:      0x30485dca423 - start_thread
  22:      0x304858f3cbc - clone
  23:                0x0 - <unknown>

```

**Comment by kubrickfr** [comment]
Now crashes but for different reasons / different backtrace
