### ISSUE TITLE
crash running summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#984]
Almost immediately after startup while running in gdb, saw a black screen then a crash.

```
#0  0x00007fffef13809d in add_uniform(exec_list*, glsl_symbol_table*, char const*, glsl_type const*) () from /lib64/libdricore9.2.0-devel.so.1
#1  0x00007fffef13880c in generate_110_uniforms(exec_list*, _mesa_glsl_parse_state*, bool) () from /lib64/libdricore9.2.0-devel.so.1
#2  0x00007fffef138b1f in generate_110_fs_variables(exec_list*, _mesa_glsl_parse_state*, bool) () from /lib64/libdricore9.2.0-devel.so.1
#3  0x00007fffef138b89 in generate_120_fs_variables(exec_list*, _mesa_glsl_parse_state*, bool) () from /lib64/libdricore9.2.0-devel.so.1
#4  0x00007fffef13912d in _mesa_glsl_initialize_variables(exec_list*, _mesa_glsl_parse_state*) () from /lib64/libdricore9.2.0-devel.so.1
#5  0x00007fffef0006be in _mesa_get_fixed_func_fragment_program () from /lib64/libdricore9.2.0-devel.so.1
#6  0x00007fffef04ef22 in _mesa_update_state_locked () from /lib64/libdricore9.2.0-devel.so.1
#7  0x00007fffef04f101 in _mesa_update_state () from /lib64/libdricore9.2.0-devel.so.1
#8  0x00007fffef064610 in teximage () from /lib64/libdricore9.2.0-devel.so.1
#9  0x00007fffef065530 in _mesa_TexImage2D () from /lib64/libdricore9.2.0-devel.so.1
#10 0x00007ffff6209c87 in SkNativeSharedGLContext::init(int, int) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#11 0x00007ffff6141d60 in AzCreateSkiaSharedGLContext ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#12 0x00007ffff6140ea5 in new_with_fbo () at /home/jdm/sdb/servo/src/support/azure/rust-azure/azure_hl.rs:340
#13 0x000000000048a7ea in render_task::__extensions__::render_24059::anon::anon::expr_fn_24065 ()
#14 0x000000000047f9bc in render_task::__extensions__::create_22821::anon::expr_fn_22949 ()
#15 0x000000000047df48 in task::__extensions__::spawn_with_22837::anon::expr_fn_22843 ()
#16 0x00007ffff788021c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#17 0x00007ffff7920e84 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#18 0x00007ffff782355c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#19 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#20 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#21 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#22 0x00007ffff2e5ea73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#23 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#24 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#27 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x0000000000000000 in ?? ()
```

**Comment by jdm** [comment]
Haven't seen this in a long time.
