### ISSUE TITLE
Webrender panic: entered unreachable code

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9846]
```
thread '<main>' panicked at 'internal error: entered unreachable code', /Users/paul/git/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:1475
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
```

**Comment by paulrouget** [comment]
```
stack backtrace:
   1:        0x10d16c3d8 - sys::backtrace::tracing::imp::write::hbf901342cf42dd32Plu
   2:        0x10d16f7a5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43106
   3:        0x10d16f3c8 - panicking::default_handler::hc39cc975176a9eeceNy
   4:        0x10d15a9b6 - sys_common::unwind::begin_unwind_inner::h669bcd18f61ce724Bkt
   5:        0x10c3084d4 - sys_common::unwind::begin_unwind::h4175260459432736569
   6:        0x10c3b562c - renderer::Renderer::update_texture_cache::h2da7b4cb0a0e39a73ws
   7:        0x10c3b0f65 - renderer::Renderer::render::hfc07672034ba9617Hrs
   8:        0x10b9ae820 - compositor::IOCompositor<Window>::composite_specific_target::h11678236045218593599
   9:        0x10b9b5df1 - compositor::IOCompositor<Window>::composite::h7765994244262983890
  10:        0x10b982533 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h11195504845474798582
  11:        0x10b9bc4e7 - Browser::handle_events::h4f490bc07195a65fifa
  12:        0x10b96cfb9 - main::h8517eb49d15e90fbNaa
  13:        0x10d16efd2 - sys_common::unwind::try::try_fn::h13042820775962970873
  14:        0x10d16b92b - __rust_try
  15:        0x10d16ee90 - rt::lang_start::h311a4caf25eebe23kFy
```
