### ISSUE TITLE
crash while scrolling summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#985]
Run under gdb, see a black screen with no indication that layout is occurring, attempt to scrolling. Crash.
```
#0  0x00007ffff6159c8d in mozalloc_abort(char const*) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#1  0x00007ffff6159c70 in abort () from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#2  0x00007ffff79b5382 in rt::util::abort::abort::_7c12263797ed078::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#3  0x00007ffff781fa4b in rt::util::abort::_f2c3fded91cbadbb::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#4  0x00007ffff782013c in rt::task::Drop$x24Task::drop::_f3525925b944a51e8au::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#5  0x00007ffff781ff02 in rt..task..Task::glue_drop_16262::_76c9f6b747a472c ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#6  0x00007ffff78283b3 in unstable..sync..ExData$LT$$UP$$x5b$UP$rt..task..Task$x5d$GT$::glue_drop_16747::_720d834d869a11 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#7  0x00007ffff7828302 in option..Option$LT$unstable..sync..ExData$LT$$UP$$x5b$UP$rt..task..Task$x5d$GT$$GT$::glue_drop_16741::_a956f769e14c94 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#8  0x00007ffff7828285 in unstable..sync..ArcData$LT$unstable..sync..ExData$LT$$UP$$x5b$UP$rt..task..Task$x5d$GT$$GT$::glue_drop_16735::_95f56dbd2613de2d ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#9  0x00007ffff7828075 in unstable::sync::Drop$x24UnsafeArc::drop_16715::_f3525925b944a51Cz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#10 0x00007ffff7827bd7 in unstable..sync..UnsafeArc$LT$unstable..sync..ExData$LT$$UP$$x5b$UP$rt..task..Task$x5d$GT$$GT$::glue_drop_16713::_eab6d4adf6a57f0 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#11 0x00007ffff7827b98 in unstable..sync..Exclusive$LT$$UP$$x5b$UP$rt..task..Task$x5d$GT$::glue_drop_16707::_ae33d4aeb693b6b7 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#12 0x00007ffff7827a70 in rt..work_queue..WorkQueue$LT$$UP$rt..task..Task$GT$::glue_drop_16693::_1ddd9e5ac39cf82f ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#13 0x00007ffff78278cc in rt..sched..Scheduler::glue_drop_16687::_efa7c09fe28a1bae ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#14 0x00007ffff78349ba in option..Option$LT$$UP$rt..sched..Scheduler$GT$::glue_drop_17842::_c5ca74fb4ce0cdcf ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#15 0x00007ffff781ffbd in rt..task..Task::glue_drop_16262::_76c9f6b747a472c ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#16 0x00007ffff789a5b2 in rt::sched::Scheduler::bootstrap::_d21f69ccdafd98eoJae::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#17 0x00007ffff79bd95d in rt::run_::_82e8c355ab8d949f::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#18 0x00007ffff79bb657 in rt::run_on_main_thread::_d3cab0f3a053bc41::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#19 0x00007ffff79bb56e in rt::start_on_main_thread::_98ebfd32a7b8f1::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#20 0x0000000000504059 in main ()
```

**Comment by jdm** [comment]
File doesn't exist any more. I don't see this on the other summit files.
