### ISSUE TITLE
Crash deleting a GLProgram under summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#986]
Run under gdb, crash instantly.
```
#0  tcache_dalloc_small (binind=255, ptr=0x7fffe53bf380, tcache=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/jemalloc/include/jemalloc/internal/tcache.h:405
#1  arena_dalloc (arena=0x7ffff28245c0, try_tcache=true, ptr=0x7fffe53bf380, chunk=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/jemalloc/include/jemalloc/internal/arena.h:1003
#2  idallocx (try_tcache=true, ptr=0x7fffe53bf380) at include/jemalloc/internal/jemalloc_internal.h:913
#3  iqallocx (try_tcache=true, ptr=0x7fffe53bf380) at include/jemalloc/internal/jemalloc_internal.h:932
#4  iqalloc (ptr=0x7fffe53bf380) at include/jemalloc/internal/jemalloc_internal.h:939
#5  free (ptr=0x7fffe53bf380) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/jemalloc/src/jemalloc.c:1272
#6  0x00007fffeed2bedd in unsafe_free () from /lib64/libdricore9.2.0-devel.so.1
#7  0x00007fffeec4d617 in _mesa_reference_shader () from /lib64/libdricore9.2.0-devel.so.1
#8  0x00007fffeec4b367 in delete_shader () from /lib64/libdricore9.2.0-devel.so.1
#9  0x00007ffff626008d in GrGLProgram::~GrGLProgram() ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#10 0x00007ffff6260119 in GrGLProgram::~GrGLProgram() ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#11 0x00007ffff6262061 in GrGLProgram::Create(GrGLContext const&, GrGLProgramDesc const&, GrEffectStage const**) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#12 0x00007ffff6208579 in GrGpuGL::ProgramCache::getProgram(GrGLProgramDesc const&, GrEffectStage const**) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#13 0x00007ffff62089db in GrGpuGL::flushGraphicsState(GrGpu::DrawType, GrDeviceCoordTexture const*) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#14 0x00007ffff61d0c45 in GrGpu::onDraw(GrDrawTarget::DrawInfo const&) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#15 0x00007ffff61d5931 in GrInOrderDrawBuffer::flush() ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#16 0x00007ffff61c1815 in GrContext::flush(int) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#17 0x00007ffff61c1b4b in GrContext::resolveRenderTarget(GrRenderTarget*) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#18 0x00007ffff6141236 in flush () at /home/jdm/sdb/servo/src/support/azure/rust-azure/azure_hl.rs:406
#19 0x000000000048a9de in render_task::__extensions__::render_24059::anon::anon::expr_fn_24065 ()
#20 0x000000000047f9bc in render_task::__extensions__::create_22821::anon::expr_fn_22949 ()
#21 0x000000000047df48 in task::__extensions__::spawn_with_22837::anon::expr_fn_22843 ()
#22 0x00007ffff788021c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#23 0x00007ffff7920e84 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#24 0x00007ffff782355c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#27 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff2e5ea73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#29 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#31 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#32 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#33 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#34 0x0000000000000000 in ?? ()
```

**Comment by jdm** [comment]
Super old, not worth tracking any longer.
