### ISSUE TITLE
Crash loading the failing webpage in summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#987]
Summit demo ran fine until I clicked the link to the crashing page:
```
task <unnamed> failed at 'assertion failed: grandparent_gen.flow.is_block_like()', /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:494
task <unnamed> failed at 'killed by linked failure', /home/jdm/sdb/servo/src/compiler/rust/src/libstd/rt/kill.rs:627
task <unnamed> failed at 'killed by linked failure', /home/jdm/sdb/servo/src/compiler/rust/src/libstd/rt/kill.rs:627


There are not many persons who know what wonders are opened to them in the
stories and visions of their youth; for when as children we listen and dream,
we think but half-formed thoughts, and when as men we try to remember, we are
dulled and prosaic with the poison of life. But some of us awake in the night
with strange phantasms of enchanted hills and gardens, of fountains that sing
in the sun, of golden cliffs overhanging murmuring seas, of plains that stretch
down to sleeping cities of bronze and stone, and of shadowy companies of heroes
that ride caparisoned white horses along the edges of thick forests; and then
we know that we have looked back through the ivory gates into that world of
wonder which was ours before we were wise and unhappy.

fatal runtime error: assertion failed: task.unwinder.unwinding
Redirecting call to abort() to mozalloc_abort


Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1dfd700 (LWP 7587)]
0x00007ffff6159c8d in mozalloc_abort(char const*) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
(gdb) bt
#0  0x00007ffff6159c8d in mozalloc_abort(char const*) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#1  0x00007ffff6159c70 in abort () from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#2  0x00007ffff79b5382 in rt::util::abort::abort::_7c12263797ed078::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#3  0x00007ffff781fa4b in rt::util::abort::_f2c3fded91cbadbb::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#4  0x00007ffff7922176 in rt::kill::BlockedTask::try_block::_60c4eb7e125d16f3Psa7::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#5  0x00007ffff793fb3f in rt::sched::__extensions__::switch_running_tasks_and_then::anon::expr_fn_28498 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#6  0x00007ffff794133a in rt::sched::CleanupJob::run::_6eff636834a396dweaS::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#7  0x00007ffff7920ded in rt::sched::Scheduler::run_cleanup_job::_f3525925b944a51oJaI::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#8  0x00007ffff793f04a in rt::sched::Scheduler::change_task_context::_93e01b9e43a9e3oJax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#9  0x00007ffff79347e6 in rt::sched::Scheduler::resume_task_immediately::_27418afae572878oJa3::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#10 0x00007ffff7939779 in rt::sched::Scheduler::resume_task_immediately_cl::_34e81fe04e979bfoJaw::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#11 0x00007ffff7939673 in rt::sched::Scheduler::process_task::_5f88d2322d915oJav::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#12 0x00007ffff79387e0 in rt::sched::Scheduler::do_work::_54c71efee7c9931aoJal::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#13 0x00007ffff79341d6 in rt::sched::Scheduler::run_sched_once::_f3525925b944a51oJa2::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#14 0x00007ffff7965d2b in rt::uv::uvio::__extensions__::start::anon::expr_fn_29754 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#15 0x00007ffff799db99 in rt::uv::idle::IdleWatcher::restart::idle_cb::__rust_abi::_6z ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#16 0x00007ffff799dae5 in rt::uv::idle::IdleWatcher::restart::idle_cb::_37bc4ab8b7fd7e3c6z::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#17 0x00007ffff2e92592 in uv__run_idle () from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustrt.so
#18 0x00007ffff2e8e8b6 in uv_run () from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/librustrt.so
#19 0x00007ffff798fb91 in rt::uv::uvll::run::_ee364f6fbd3e54::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#20 0x00007ffff7964777 in rt::uv::Loop::run::_f3525925b944a510Haz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#21 0x00007ffff7937cda in rt::uv::uvio::EventLoop$x24UvEventLoop::run::_f3525925b944a51oPai::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#22 0x00007ffff7934a28 in rt::sched::Scheduler::run::_f3525925b944a51oJa4::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#23 0x00007ffff789a114 in rt::sched::Scheduler::bootstrap::_d21f69ccdafd98eoJae::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#24 0x00007ffff79c18c6 in rt::run_::anon::expr_fn_32974 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff2e5deba in rust_thread_start (ptr=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/sync/rust_thread.cpp:36
#26 0x0000003a5e607d15 in start_thread () from /lib64/libpthread.so.0
#27 0x0000003a5def253d in clone () from /lib64/libc.so.6
```

**Comment by jdm** [comment]
The failures now are very different. No point in leaving this open.
