### ISSUE TITLE
crash running summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#988]
Immediately after starting summit.html I see a crash.
```
#0  0x00007fffeed88522 in _mesa_glsl_link_shader () from /lib64/libdricore9.2.0-devel.so.1
#1  0x00007fffeec4b3ee in link_program () from /lib64/libdricore9.2.0-devel.so.1
#2  0x00007fffeed21653 in _mesa_meta_glsl_Clear () from /lib64/libdricore9.2.0-devel.so.1
#3  0x00007fffef15393b in brw_clear () from /usr/lib64/dri/i965_dri.so
#4  0x00007ffff6209e07 in SkNativeSharedGLContext::init(int, int) ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#5  0x00007ffff6141d60 in AzCreateSkiaSharedGLContext ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#6  0x00007ffff6140ea5 in new_with_fbo () at /home/jdm/sdb/servo/src/support/azure/rust-azure/azure_hl.rs:340
#7  0x000000000048a7ea in render_task::__extensions__::render_24059::anon::anon::expr_fn_24065 ()
#8  0x000000000047f9bc in render_task::__extensions__::create_22821::anon::expr_fn_22949 ()
#9  0x000000000047df48 in task::__extensions__::spawn_with_22837::anon::expr_fn_22843 ()
#10 0x00007ffff788021c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#11 0x00007ffff7920e84 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#12 0x00007ffff782355c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#13 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#14 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#15 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#16 0x00007ffff2e5ea73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#17 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#18 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#19 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#20 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#21 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#22 0x0000000000000000 in ?? ()
```

**Comment by jdm** [comment]
Not much to do here; file's gone.
