### ISSUE TITLE
fontconfig crash under create_font_from_identifier

### ISSUE THREAD

**Issue by jdm** [servo/servo#989]
Ran the summit demo, crashed immediately:
```
#0  0x000000321c61dad0 in FcStrCaseWalkerNextIgnoreBlanks () from /lib64/libfontconfig.so.1
#1  0x000000321c61dc00 in FcStrCmpIgnoreBlanksAndCase () from /lib64/libfontconfig.so.1
#2  0x000000321c609c40 in FcConfigCompareValue () from /lib64/libfontconfig.so.1
#3  0x000000321c60a898 in FcConfigSubstituteWithPat () from /lib64/libfontconfig.so.1
#4  0x00007ffff476f3c8 in path_from_identifier () at /home/jdm/sdb/servo/src/components/gfx/platform/linux/font_list.rs:186
#5  0x00007ffff4766fef in create_font_from_identifier () at /home/jdm/sdb/servo/src/components/gfx/platform/linux/font_context.rs:56
#6  0x00007ffff47662fc in create_font_instance () at /home/jdm/sdb/servo/src/components/gfx/font_context.rs:190
#7  0x00007ffff4765864 in get_font_by_descriptor () at /home/jdm/sdb/servo/src/components/gfx/font_context.rs:102
#8  0x00007ffff476458f in create_font_group () at /home/jdm/sdb/servo/src/components/gfx/font_context.rs:146
#9  0x00007ffff4762c9c in get_resolved_font_for_style () at /home/jdm/sdb/servo/src/components/gfx/font_context.rs:87
#10 0x00000000004fc95a in flush_clump_to_list () at /home/jdm/sdb/servo/src/components/main/layout/text.rs:214
#11 0x00000000004cbae0 in scan_for_runs () at /home/jdm/sdb/servo/src/components/main/layout/text.rs:88
#12 0x00000000004c8366 in simplify_children_of_flow () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:600
#13 0x00000000004c36f1 in construct_recursively () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:354
#14 0x00000000004c7b95 in fn_29555 () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:337
#15 0x00000000004c3646 in construct_recursively () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:76
#16 0x00000000004c7b95 in fn_29555 () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:337
#17 0x00000000004c3646 in construct_recursively () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:76
#18 0x00000000004cbf18 in construct_trees () at /home/jdm/sdb/servo/src/components/main/layout/box_builder.rs:624
#19 0x00000000004e0ab9 in handle_reflow () at /home/jdm/sdb/servo/src/components/main/layout/layout_task.rs:230
#20 0x00000000004dde27 in fn_30980 () at /home/jdm/sdb/servo/src/components/main/layout/layout_task.rs:155
#21 fn_16549 () at /home/jdm/sdb/servo/src/components/main/compositing/mod.rs:478
#22 handle_request () at /home/jdm/sdb/servo/src/components/main/layout/layout_task.rs:155
#23 start () at /home/jdm/sdb/servo/src/components/main/layout/layout_task.rs:130
#24 0x00000000004dc7ad in fn_30756 () at /home/jdm/sdb/servo/src/components/main/layout/layout_task.rs:95
#25 0x00007ffff788021c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff7920e84 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#27 0x00007ffff782355c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#29 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#31 0x00007ffff2e5ea73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#32 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#33 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#34 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#35 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#36 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#37 0x0000000000000000 in ?? ()
```

**Comment by mbrubeck** [comment]
This code has been rewritten and we haven't seen this crash in the current code.
