### ISSUE TITLE
Crash while watching summit.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#990]
Was zoomed in, but otherwise not doing much.
```
servo: xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len' failed.
Program received signal SIGABRT, Aborted.
0x0000003a5de35c55 in raise () from /lib64/libc.so.6
(gdb) bt

#0  0x0000003a5de35c55 in raise () from /lib64/libc.so.6
#1  0x0000003a5de37408 in abort () from /lib64/libc.so.6
#2  0x0000003a5de2e972 in __assert_fail_base () from /lib64/libc.so.6
#3  0x0000003a5de2ea22 in __assert_fail () from /lib64/libc.so.6
#4  0x0000003a6220a13f in _xcb_conn_wait () from /lib64/libxcb.so.1
#5  0x0000003a6220a497 in _xcb_out_send () from /lib64/libxcb.so.1
#6  0x0000003a6220ac07 in _xcb_out_flush_to () from /lib64/libxcb.so.1
#7  0x0000003a6220ad20 in xcb_take_socket () from /lib64/libxcb.so.1
#8  0x0000003a626428a8 in require_socket () from /lib64/libX11.so.6
#9  0x0000003a62643099 in _XFlush () from /lib64/libX11.so.6
#10 0x0000003a62645cc5 in _XGetRequest () from /lib64/libX11.so.6
#11 0x0000003a6263ed4b in XSync () from /lib64/libX11.so.6
#12 0x000000321ce40aef in dri2SwapBuffers () from /lib64/libGL.so.1
#13 0x00007ffff671de8f in _glfwPlatformSwapBuffers ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/glfw/glfw-rs/libglfw-5b503c2dbc41ad93-0.1.so
#14 0x00007ffff6719510 in glfwSwapBuffers () from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/glfw/glfw-rs/libglfw-5b503c2dbc41ad93-0.1.so
#15 0x0000000000446971 in scroll () at /home/jdm/sdb/servo/src/components/main/compositing/compositor_layer.rs:179
#16 scroll () at /home/jdm/sdb/servo/src/components/main/compositing/compositor_layer.rs:179
#17 fn_16549 () at /home/jdm/sdb/servo/src/components/main/compositing/mod.rs:518
#18 run () at /home/jdm/sdb/servo/src/components/main/compositing/mod.rs:534
#19 0x0000000000504f99 in run () at /home/jdm/sdb/servo/src/components/main/servo.rc:169
#20 0x000000000050414e in fn_33820 () at /home/jdm/sdb/servo/src/components/main/servo.rc:124
#21 0x00007ffff7920e84 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#22 0x00007ffff782355c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#23 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#24 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff2e5ea73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#27 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#29 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#31 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#32 0x0000000000000000 in ?? ()

```

**Comment by jdm** [comment]
File doesn't exist any more.
