### ISSUE TITLE
[meta] github.com bugs

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9914]
We want to properly support github.com. It needs to be rendered properly (homepage and issue pages) and make sure it behave properly. We want to be able to sign in and file issues.

See https://github.com/servo/servo/wiki/WebCompatBug

----

* https://github.com/servo/servo/issues/9829

**Comment by metajack** [comment]
We cannot block on #9998 because that requires SVG which is clearly out of scope for June.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/11333 fixes some github stuff

**Comment by Manishearth** [comment]
Added https://github.com/servo/servo/issues/11354, didn't prioritize yet

**Comment by atouchet** [comment]
#17465, #17489, #17490, #17511, and #17830 are github.com issues.

**Comment by atouchet** [comment]
#17847 is a github.com issue.

**Comment by atouchet** [comment]
#17490, #17830, and #17847 can be marked as fixed.

**Comment by atouchet** [comment]
#17572 is a github.com issue.

**Comment by metajack** [comment]
Updated

**Comment by atouchet** [comment]
Removed [meta] from the title as that is now covered by the label.

**Comment by arihant2math** [comment]
Currently #39068 is the issue when resizing the window to be too wide.

**Comment by arihant2math** [comment]
Somewhat better when not looking at the front page of a repo:

![Image](https://github.com/user-attachments/assets/f81217f8-8745-491a-b1e9-3a520afc3fdf)

**Comment by arihant2math** [comment]
The main rendering issue is the flex box deciding to render vertically instead of horizontally.

**Comment by arihant2math** [comment]
Now:
<img width="1702" height="884" alt="Image" src="https://github.com/user-attachments/assets/11f81caa-a9f4-44d9-8a9d-5e2324b20ff7" />

Main problem seems to be #36944 but also the same issue as #39618 for the weird icons. Also it's incredibly laggy/slow; looking into that. Also some styling bugs due to #38132

**Comment by NicTanghe** [comment]
Unable to open github issues,

I click issues and nothing happens.

Version: Servo 0.3.0-fb6c9d511f6
OS: CachyOS x86_64
Kernel: Linux 7.1.3-2-cachyos

<details>
<summary>Part of Errors</summary>

[2026-07-27T15:14:27Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
[2026-07-27T15:14:27Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
[2026-07-27T15:14:27Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined
[2026-07-27T15:14:30Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined
[2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined
[2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:2:7354 IntersectionObserver is not defined
[2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:2:7354 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/behaviors-f0b3a0a785807c81.js:27:67592 IntersectionObserver is not defined
[2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/behaviors-f0b3a0a785807c81.js:27:67592 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
[2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined
Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined
[2026-07-27T15:14:39Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined

</details>

**Comment by Taym95** [comment]
> Unable to open github issues,
> 
> I click issues and nothing happens.
> 
> Version: Servo 0.3.0-fb6c9d511f6 OS: CachyOS x86_64 Kernel: Linux 7.1.3-2-cachyos
> 
> Part of Errors
> [2026-07-27T15:14:27Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined [2026-07-27T15:14:27Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined [2026-07-27T15:14:27Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined [2026-07-27T15:14:30Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined [2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined [2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:243:1832 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:2:7354 IntersectionObserver is not defined [2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/91445-6f5c449d48bb47ab.js:2:7354 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/behaviors-f0b3a0a785807c81.js:27:67592 IntersectionObserver is not defined [2026-07-27T15:14:33Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/behaviors-f0b3a0a785807c81.js:27:67592 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined [2026-07-27T15:14:34Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:2:8576 IntersectionObserver is not defined Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined [2026-07-27T15:14:39Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/26533-36c85461b011ffd5.js:16:14124 can't access property "linkClickIntercepted", i.delegate is undefined

@NicTanghe can you try the experimental mode ? 

<img width="112" height="86" alt="Image" src="https://github.com/user-attachments/assets/f1b89b6e-c133-44a9-b1eb-48ba6c364271" />

**Comment by NicTanghe** [comment]
In experimental mode i was able to open the issues tab, but after doing so i was no longer able to click anny of the links on that page,
(could still open an new tab and browse around there)



<details>
<summary>Part of Errors</summary>

ithubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:34:41Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:34:41Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:34:41Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:34:42Z ERROR script::script_runtime] Unhandled promise rejection: (new TypeError("o.handleMessage is not a function", "https://github.githubassets.com/assets/environment-9aeec509803c58b3.js", 2))
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
[2026-07-27T18:35:36Z ERROR servoshell::desktop::headed_window] Error at https://github.githubassets.com/assets/78205-75aff589688e0be2.js:64:215 can't access property Symbol.iterator, e.adoptedStyleSheets is undefined
No valid entry type provided to observe().


</details>
