### ISSUE TITLE
summit.html hangs on quit sometimes

### ISSUE THREAD

**Issue by jdm** [servo/servo#992]
```
Thread 1 (Thread 0x7ffff2e3f840 (LWP 8298)):
#0  0x0000003a5e60de4d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003a5e60bd80 in pthread_cond_broadcast@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#2  0x0000003a6220a4b3 in _xcb_out_send () from /lib64/libxcb.so.1
#3  0x0000003a6220a603 in xcb_writev () from /lib64/libxcb.so.1
#4  0x0000003a62642d4e in _XSend () from /lib64/libX11.so.6
#5  0x0000003a62638fa6 in XQueryExtension () from /lib64/libX11.so.6
#6  0x0000003a6262cee2 in XInitExtension () from /lib64/libX11.so.6
#7  0x000000321ce1c7d5 in __glXInitialize () from /lib64/libGL.so.1
#8  0x000000321ce1ccf3 in __glXSetupForCommand () from /lib64/libGL.so.1
---Type <return> to continue, or q <return> to quit---
#9  0x000000321ce19354 in glXDestroyContext () from /lib64/libGL.so.1
#10 0x00007ffff6209f9c in SkNativeSharedGLContext::~SkNativeSharedGLContext() ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#11 0x00007ffff620a099 in SkNativeSharedGLContext::~SkNativeSharedGLContext() ()
   from /run/media/jdm/ssd/servo/build/../../../../../../home/jdm/sdb/servo/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#12 0x00007ffff614099e in drop () at /home/jdm/sdb/servo/src/support/azure/rust-azure/azure_hl.rs:283
#13 0x0000000000422b16 in azure..azure_hl..DrawTarget::glue_drop_11112::_5e8f577d57edeb14 () at /home/jdm/sdb/servo/src/components/main/compositing/compositor_layer.rs:88
#14 0x00007ffff7904fea in cleanup::annihilate::anon::expr_fn_26278 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#15 0x00007ffff7904bd2 in cleanup::each_live_alloc::_b612c3ea22865f8::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#16 0x00007ffff7904d67 in cleanup::annihilate::_82984335c95fdd5::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#17 0x00007ffff791e857 in rt::task::__extensions__::run::anon::anon::expr_fn_27245 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#18 0x00007ffff782365e in unstable::finally::Drop$x24Finallyalizer::drop::_f3525925b944a51lnaX::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#19 0x00007ffff7823609 in unstable..finally..Finallyalizer$LT$$GT$::glue_drop_16539::_8bee48b7b0f3c280 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#20 0x00007ffff7823571 in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#21 0x00007ffff791e7e5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#22 0x00007ffff7921359 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#23 0x00007ffff79212b7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#24 0x00007ffff2e5ea73 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>) at /home/jdm/sdb/servo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#25 0x00007ffff791e6b2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff791e546 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#27 0x00007ffff7920ad7 in rt::task::__extensions__::build_start_wrapper::anon::expr_fn_27300 ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff79a5045 in rt::context::Context::new::task_start_wrapper::__rust_abi::Yz ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#29 0x00007ffff79a4ff7 in rt::context::Context::new::task_start_wrapper::_1b9fdc38dc3bcfa4Yz::v0.8$x2dpre ()
   from /run/media/jdm/ssd/servo/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x0000000000000000 in ?? ()
```

**Comment by jdm** [comment]
Haven't come across this for a long time.
