### ISSUE TITLE
Texture cache panic using webrender on twitter.com

### ISSUE THREAD

**Issue by jdm** [servo/servo#9931]
```
thread '<unnamed>' panicked at 'No texture page for ID TextureId(1021)', /Users/jdm/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/texture_cache.rs:590
stack backtrace:
   1:        0x10a5974e8 - sys::backtrace::tracing::imp::write::h183d2a53683d2625euv
   2:        0x10a59a8b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44361
   3:        0x10a59a4d8 - panicking::default_handler::hab4234f091945e644Wz
   4:        0x10a5859e6 - sys_common::unwind::begin_unwind_inner::hbec2c0670ace64aa0su
   5:        0x10a585e9e - sys_common::unwind::begin_unwind_fmt::h50937c1b473590636ru
   6:        0x10979df44 - texture_cache::TextureCache::free::hb81548e8e87a56e9sxr
   7:        0x10973b4c2 - frame::Frame::build::hc198ea9310e52ba3dDk
   8:        0x109791225 - render_backend::RenderBackend::render::h0a27af431fdc3f9cKep
   9:        0x1097591a5 - render_backend::RenderBackend::run::ha2c0568e53b3688274o
  10:        0x1097acb1f - sys_common::unwind::try::try_fn::h4490716808976073743
  11:        0x10a59699b - __rust_try
  12:        0x10a593a33 - sys_common::unwind::inner_try::h4d309f32c9e9efb22pu
  13:        0x1097ad6ba - boxed::F.FnBox<A>::call_box::h4733473737979234780
  14:        0x10a599b3c - sys::thread::Thread::new::thread_start::he476c2b9535e28afvbz
  15:     0x7fff87319898 - _pthread_body
  16:     0x7fff87319729 - _pthread_start
```
STR: `./mach run -r http://twitter.com -w`

**Comment by acdha** [comment]
I was just about to report the same problem on a different site:

```
$ RUST_BACKTRACE=1 servo --webrender http://chris.improbable.org
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/quad.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/quad.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/blit.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/blit.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/border.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/border.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/blend.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/blend.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/filter.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/filter.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/box_shadow.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/box_shadow.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/blur.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/blur.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/mask.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/mask.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/debug_font.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/debug_font.fs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/debug_color.vs.glsl"
compile "/usr/local/Cellar/servo/HEAD/resources/shaders/debug_color.fs.glsl"
thread '<unnamed>' panicked at 'No texture page for ID TextureId(1022)', /private/tmp/servo20160315-11815-aju1wm/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/texture_cache.rs:591
stack backtrace:
   1:        0x10d0254f8 - sys::backtrace::tracing::imp::write::hdcc91e23d52f1e9feuv
   2:        0x10d0288c5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44400
   3:        0x10d0284e8 - panicking::default_handler::h5bfcd298419b6ef54Wz
   4:        0x10d0137e6 - sys_common::unwind::begin_unwind_inner::hbee05b49f1a706c20su
   5:        0x10d013e3e - sys_common::unwind::begin_unwind_fmt::habb588106280858f6ru
   6:        0x10c48d114 - texture_cache::TextureCache::free::hcd35782b56070d8bRQr
   7:        0x10c4a8ecf - resource_cache::ResourceCache::expire_old_resources::h6587eba71b435c37rOp
   8:        0x10c47e50c - frame::Frame::build::h659ddd9a444183afAIk
   9:        0x10c466058 - render_backend::RenderBackend::render::h6dddaef35853cf953qp
  10:        0x10c43239b - render_backend::RenderBackend::run::h0c1bcd3d457581f8Wgp
  11:        0x10c4c6e61 - sys_common::unwind::try::try_fn::h395477929595560923
  12:        0x10d0249ab - __rust_try
  13:        0x10d021a43 - sys_common::unwind::inner_try::hd157bd7fdf16dec72pu
  14:        0x10c4c722a - boxed::F.FnBox<A>::call_box::h5940467415725313374
  15:        0x10d027b4c - sys::thread::Thread::new::thread_start::h5b180fca632674e3vbz
  16:     0x7fff8ff79c12 - _pthread_body
  17:     0x7fff8ff79b8f - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10d0254f8 - sys::backtrace::tracing::imp::write::hdcc91e23d52f1e9feuv
   2:        0x10d0288c5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44400
   3:        0x10d0284e8 - panicking::default_handler::h5bfcd298419b6ef54Wz
   4:        0x10d0137e6 - sys_common::unwind::begin_unwind_inner::hbee05b49f1a706c20su
   5:        0x10d013e3e - sys_common::unwind::begin_unwind_fmt::habb588106280858f6ru
   6:        0x10d024a17 - rust_begin_unwind
   7:        0x10d04e450 - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:        0x10c994e29 - result::unwrap_failed::h12184811545227129757
   9:        0x10c9aa964 - api::RenderApi::translate_point_to_layer_space::h1805bd51d9ed9525g1b
  10:        0x10b8478b6 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h6079755326272747483
  11:        0x10b87fba7 - Browser::handle_events::h52caa2704d95c9e5Wea
  12:        0x10b8333e9 - main::h6cacdf732b49adebMaa
  13:        0x10d0280f2 - sys_common::unwind::try::try_fn::h12350329018951514371
  14:        0x10d0249ab - __rust_try
  15:        0x10d027fb0 - rt::lang_start::hb0216a17e8d25b77aPz
```

Scrolling down causes display corruption shortly before crashing:

![screenshot 2016-03-15 15 27 52](https://cloud.githubusercontent.com/assets/46565/13791309/d596e3fc-eac2-11e5-93cf-23b2b0006385.png)

**Comment by jdm** [comment]
cc @glennw @pcwalton

**Comment by jdm** [comment]
Seen on servo.org as well.

**Comment by emilio** [comment]
FWIW (I don't know if this is known), if you scroll with the spacebar, but the mouse out of the window, it doesn't happen for me (unless you do it super quickly), but just as you put the mouse over the window (not scrolling), servo just panics.

**Comment by jdm** [comment]
I still see the exact same issue on twitter, despite https://github.com/servo/webrender/pull/254.

**Comment by jdm** [comment]
Nevermind, different assertion now.
