### ISSUE TITLE
XOpenIM Failed

### ISSUE THREAD

**Issue by sorpaas** [servo/servo#9938]
I have a VirtualBox running with `LANG=en_HK.UTF-8`. Attempting to run Servo results in the following error. It is resolved by setting `LANG=en_US.UTF-8`.

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("XOpenIM failed")', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x562b7e239960 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x562b7e23dd0b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x562b7e23d978 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x562b7e22742c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x562b7e2278b8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x562b7e238dd1 - rust_begin_unwind
   7:     0x562b7e274daf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x562b7c8b41dd - result::unwrap_failed::h15991302836660339568
                        at ../src/libcore/macros.rs:29
   9:     0x562b7c8b0882 - result::Result<T, E>::unwrap::h5981323862845103665
                        at ../src/libcore/result.rs:687
  10:     0x562b7c8aba80 - window::Window::new::h99e0b6d39b8e509cDxa
                        at /home/sorpaas/repos/servo/ports/glutin/window.rs:115
  11:     0x562b7c8aae7a - create_window::hed34d686830f7b8f3ab
                        at /home/sorpaas/repos/servo/ports/glutin/lib.rs:47
  12:     0x562b7b0d729e - main::hb2ad826330afabd3Naa
                        at /home/sorpaas/repos/servo/components/servo/main.rs:82
  13:     0x562b7e23d5d4 - sys_common::unwind::try::try_fn::h17074903832088339578
  14:     0x562b7e238d5b - __rust_try
  15:     0x562b7e23d06b - rt::lang_start::hc48b7676a10bcd987fA
  16:     0x562b7b1dc769 - main
  17:     0x7fa6c1763a3f - __libc_start_main
  18:     0x562b7b09e678 - _start
  19:                0x0 - <unknown>
Servo exited with return value 101
```

On a VirtualBox running Ubuntu 15.10.

**Comment by nox** [comment]
Is this still an issue?

**Comment by jdm** [comment]
I would expect it to panic on https://github.com/servo/servo/blob/65d9b345bb2a588f41b0d6cdca1aaca2c3c69205/ports/glutin/window.rs#L271 still.

**Comment by jdm** [comment]
Presumably related to https://github.com/servo/glutin/blob/be125189adc8d72ec49622b7d2eadab76543fd37/src/api/x11/window.rs#L497-L506.

**Comment by jdm** [comment]
I wonder if https://www.mail-archive.com/fltk-bugs@easysw.com/msg01159.html might help?

**Comment by dralley** [comment]
These lines of code don't exist anymore, and Ubuntu 15.10 isn't supported anymore either, so it's probably best to go ahead and close this issue.
