### ISSUE TITLE
Crash iframe test case

### ISSUE THREAD

**Issue by sammykim** [servo/servo#999]
There is a test file on my gist link : https://gist.github.com/sammykim/6773342
Those testcase works fine without iframe but even simple test case that is hello.html doesn't work rarely. I leave some of backtrace logs. But if you test it, you will get more than those.

Crash-1
```
#0  0x00007fffe961bb44 in llvm::FoldingSetImpl::RemoveNode(llvm::FoldingSetImpl::Node*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#1  0x00007fffe90b4b25 in llvm::AttributeListImpl::~AttributeListImpl() ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#2  0x00007fffe90b4d7c in llvm::AttrListPtr::operator=(llvm::AttrListPtr const&) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#3  0x00007fffe90e0b69 in llvm::Function::addAttribute(unsigned int, llvm::Attributes) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#4  0x00007fffe91363c3 in llvm::Argument::addAttr(llvm::Attributes) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#5  0x00007fffe90d1cc3 in LLVMAddAttribute () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#6  0x00007fffea8c9467 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#7  0x00007fffea8ca432 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#8  0x00007fffea8c5a18 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#9  0x00007fffea8b7ca1 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#10 0x00007fffea5dd9e3 in st_draw_vbo () from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#11 0x00007fffea04559a in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#12 0x00007fffea046574 in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#13 0x00007fffea0468e4 in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#14 0x00007ffff5fe8566 in GrGpuGL::onGpuDraw(GrDrawTarget::DrawInfo const&) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#15 0x00007ffff5fbb1a1 in GrInOrderDrawBuffer::flush() ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#16 0x00007ffff5fa6e35 in GrContext::flush(int) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#17 0x00007ffff5fa716b in GrContext::resolveRenderTarget(GrRenderTarget*) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#18 0x00007ffff5f26266 in flush ()
    at /home/sammykim/servo-new/myservo1001/src/support/azure/rust-azure/azure_hl.rs:406
#19 0x000000000048a63e in render_task::__extensions__::render_24059::anon::anon::expr_fn_24065 ()
#20 0x000000000047f61c in render_task::__extensions__::create_22821::anon::expr_fn_22949 ()
#21 0x000000000047dba8 in task::__extensions__::spawn_with_22837::anon::expr_fn_22843 ()
#22 0x00007ffff766220c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#23 0x00007ffff7702e74 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#24 0x00007ffff760554c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff77007d5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff7703349 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#27 0x00007ffff77032a7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff2c6ec83 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>)
    at /home/sammykim/servo-new/myservo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#29 0x00007ffff77006a2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x00007ffff7700536 in rt::task::Task::run::_199ab8d6eb226980iQax::v0.8$x2dpre ()
```
Crash-2
```
#0  0x00007fffe8d73efc in llvm::ValueHandleBase::RemoveFromUseList() ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#1  0x00007fffe8d742f3 in llvm::ValueHandleBase::ValueIsDeleted(llvm::Value*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#2  0x00007fffe8d747cd in llvm::Value::~Value() () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#3  0x00007fffe8d40649 in llvm::AllocaInst::~AllocaInst() () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#4  0x00007fffe8cb78f5 in llvm::BasicBlock::~BasicBlock() () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#5  0x00007fffe8cb7a09 in llvm::BasicBlock::~BasicBlock() () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#6  0x00007fffe8ce0add in llvm::Function::dropAllReferences() () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#7  0x00007fffea1cb9ff in lp_func_delete_body () from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#8  0x00007fffea1b1ec5 in gallivm_jit_function () from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#9  0x00007fffea4c8377 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#10 0x00007fffea4c5a30 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#11 0x00007fffea4b7ca1 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#12 0x00007fffea1dd9e3 in st_draw_vbo () from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#13 0x00007fffe9c4559a in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#14 0x00007fffe9c46574 in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#15 0x00007fffe9c468e4 in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#16 0x00007ffff5fe8566 in GrGpuGL::onGpuDraw(GrDrawTarget::DrawInfo const&) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#17 0x00007ffff5fbb1a1 in GrInOrderDrawBuffer::flush() ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#18 0x00007ffff5fa6e35 in GrContext::flush(int) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#19 0x00007ffff5fa716b in GrContext::resolveRenderTarget(GrRenderTarget*) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#20 0x00007ffff5f26266 in flush ()
    at /home/sammykim/servo-new/myservo1001/src/support/azure/rust-azure/azure_hl.rs:406
#21 0x000000000048a63e in render_task::__extensions__::render_24059::anon::anon::expr_fn_24065 ()
#22 0x000000000047f61c in render_task::__extensions__::create_22821::anon::expr_fn_22949 ()
#23 0x000000000047dba8 in task::__extensions__::spawn_with_22837::anon::expr_fn_22843 ()
#24 0x00007ffff766220c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#25 0x00007ffff7702e74 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#26 0x00007ffff760554c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#27 0x00007ffff77007d5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff7703349 in rt::task::Unwinder::try::try_fn::__rust_abi::VZ ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#29 0x00007ffff77032a7 in rt::task::Unwinder::try::try_fn::_f279c486734e2394VZ::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x00007ffff2c6ec83 in rust_try (f=<optimized out>, fptr=<optimized out>, env=<optimized out>)
    at /home/sammykim/servo-new/myservo/src/compiler/rust/src/rt/rust_builtin.cpp:523
#31 0x00007ffff77006a2 in rt::task::Unwinder::try::_199ab8d6eb226980VZay::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
```
Crash-3
```
#0  0x00007fffe8d66bb9 in llvm::PMDataManager::add(llvm::Pass*, bool) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#1  0x00007fffe8d675fc in llvm::PMTopLevelManager::schedulePass(llvm::Pass*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#2  0x00007fffe8c1caef in llvm::TargetPassConfig::addPass(char&) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#3  0x00007fffe8c1d104 in llvm::TargetPassConfig::addMachineSSAOptimization() ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#4  0x00007fffe8c1d204 in llvm::TargetPassConfig::addMachinePasses() ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#5  0x00007fffe8b7a256 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#6  0x00007fffe8b7a7fa in llvm::LLVMTargetMachine::addPassesToEmitMC(llvm::PassManagerBase&, llvm::MCContext*&, llvm::raw_ostream&, bool) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#7  0x00007fffe8f25a4e in llvm::MCJIT::MCJIT(llvm::Module*, llvm::TargetMachine*, llvm::TargetJITInfo&, llvm::RTDyldMemoryManager*, bool) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#8  0x00007fffe8f25b89 in llvm::MCJIT::createJIT(llvm::Module*, std::string*, llvm::JITMemoryManager*, bool, llvm::TargetMachine*) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#9  0x00007fffe8da3d4b in llvm::EngineBuilder::create(llvm::TargetMachine*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.1.so.1
#10 0x00007fffea1cbf1a in lp_build_create_mcjit_compiler_for_module ()
   from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#11 0x00007fffea1b1e57 in gallivm_compile_module () from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#12 0x00007fffea4c835f in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#13 0x00007fffea4c5a30 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#14 0x00007fffea4b7ca1 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#15 0x00007fffea1dd9e3 in st_draw_vbo () from /usr/lib/x86_64-linux-gnu/libgallium.so.0
#16 0x00007fffe9c4559a in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#17 0x00007fffe9c46574 in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#18 0x00007fffe9c468e4 in ?? () from /usr/lib/x86_64-linux-gnu/libdricore9.0.3.so.1
#19 0x00007ffff5fe8566 in GrGpuGL::onGpuDraw(GrDrawTarget::DrawInfo const&) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#20 0x00007ffff5fbb1a1 in GrInOrderDrawBuffer::flush() ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#21 0x00007ffff5fa6e35 in GrContext::flush(int) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#22 0x00007ffff5fa716b in GrContext::resolveRenderTarget(GrRenderTarget*) ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/support/azure/rust-azure/libazure-1bdc5ce4bb2c9e2a-0.1.so
#23 0x00007ffff5f26266 in flush ()
    at /home/sammykim/servo-new/myservo1001/src/support/azure/rust-azure/azure_hl.rs:406
#24 0x000000000048a63e in render_task::__extensions__::render_24059::anon::anon::expr_fn_24065 ()
#25 0x000000000047f61c in render_task::__extensions__::create_22821::anon::expr_fn_22949 ()
#26 0x000000000047dba8 in task::__extensions__::spawn_with_22837::anon::expr_fn_22843 ()
#27 0x00007ffff766220c in task::spawn::spawn_raw::anon::expr_fn_20955 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#28 0x00007ffff7702e74 in rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn_27315 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#29 0x00007ffff760554c in unstable::finally::Finally$x24__extensions__::finally_16533::_199ab8d6eb226980IY::v0.8$x2dpre ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
#30 0x00007ffff77007d5 in rt::task::__extensions__::run::anon::expr_fn_27243 ()
   from /home/sammykim/servo-new/myservo1001/build/x86_64-unknown-linux-gnu/src/compiler/rust/x86_64-unknown-linux-gnu/stage2/lib/rustc/x86_64-unknown-linux-gnu/lib/libstd-6c65cf4b443341b1-0.8-pre.so
```

**Comment by glennw** [comment]
Tested, cannot repro.
